### ISSUE TITLE
Override template parameters: Unexpected token $

### ISSUE THREAD

**Issue by sarahkang58** [microsoft/azure-pipelines-tasks#14712] opened 2021-04-09 19:57 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: ARM Template Deployment

## Environment
- Server - Azure Pipelines

## Issue Description

We are getting this error with the ARM template deployment task:

> There was an error while overriding 'alertThresholdForIcMTrigger' parameter because of 'SyntaxError: Unexpected token $ in JSON at position 0', make sure it follows JavaScript Object Notation (JSON)

In the Override Template Parameters multiline input box, we have:
`-alertThresholdForIcMTrigger $(AlertThresholdForIcMTrigger)`
where `AlertThresholdForIcMTrigger` is set to an integer in the Variables section of the Release pipeline.

Would anyone know what is causing this issue?  Sorry if this was already addressed somewhere else.

**Comment by anuragc617** [comment] 2021-04-21 17:12
@sarahkang58 I am not able to reproduce it. Can you please share the debug logs with variable system.debug set to true?

**Comment by musema** [comment] 2021-04-26 07:27
@anuragc617 We are facing the same issue, the challenge is how can we effectively define an` integer` variable in Azure DevOps Classic release pipeline and pass as override parameter to **ARM template deployment** [task](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureResourceManagerTemplateDeploymentV3/README.md)? This task is assuming the value as `String`
**Task version**: `3.*`

**Comment by ddivanshu** [comment] 2021-05-19 07:23
@musema pls share debug logs

**Comment by ddivanshu** [comment] 2021-05-24 21:01
Closing this .
Feel free to reopen if issue persists.

**Closed by ddivanshu** 2021-05-24 21:01 UTC
Labels: Area: Release, question
