### ISSUE TITLE
"Path to custom test adapters" parameter of VSTest task does not work

### ISSUE THREAD

**Issue by Roman-Rostovtsev** [microsoft/azure-pipelines-tasks#11573] opened 2019-10-16 15:43 UTC
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VsTestV2 

## Environment
- Server - Azure Pipelines 
    
- Agent - Private: 
   OS: Windows 8.1 x64, agent version: '2.141.1'
    
## Issue Description

I develop a custom test adapter. It is deployed to some folder inside an agent's working folder (let's say "$(System.DefaultWorkingDirectory)\MyAdapter") so I specify this path "$(System.DefaultWorkingDirectory)\MyAdapter" in the "Path to custom test adapters" parameter of VSTest task of my build pipeline. The problem is that this VSTest task fails with the strange error "##[error]The slice of type 'Discovery' is 'Aborted' because of the error : System.Exception: Could not find extensions: c:\vstsAgent_work\22\s\MyAdapter" and tests do not start. The reproduction depends on the "Batch tests" option of VSTest task. If the value is "Based on test assemblies" or "Based on past running time of tests" then this issue occurs. However, if the value is "Based on number of tests and agents", then tests start and everything works fine.

The switch /TestAdapterPath:c:\vstsAgent\_work\22\s\MyAdapter works with vstest.console.exe fine, too

P.S.
I was redirected here from https://github.com/microsoft/vstest/issues/2225

## Steps to reproduce

1.   Create a build pipeline in Azure DevOps with two tasks: Test Platform installer and Visual Studio Test tasks.
2.    Specify in the VSTest task:
    "Path to custom test adapters" = "$(System.DefaultWorkingDirectory)\MyAdapter"
    "Batch tests" = "Based on test assemblies"
    "Select tests using" = "Test assemblies"
    "Search folder" and "Test files" to valid values
3.    Make sure that "Clean" is false in the "Get sources" operation
4.    Set Agent pool as Default
5.    Set Job's "Parallelism" parameter to "Multi-agent" and "Number of agents" to 1 (or "Parallelism" to "None" - it does not matter)
6.   Start build pipeline the first time. The VSTest task will fail with the error like "Error: Path to custom adapters 'C:\vstsAgent_work\22\s\MyAdapter' should be a directory and it should exist."
7.    To simplify reproduction place a custom test adapter to the folder which is mentioned in this error
8.    Start the build pipeline again

## Expected behavior

Tests start during build

## Actual behavior

The following error occurs:
"##[error]The slice of type 'Discovery' is 'Aborted' because of the error : System.Exception: Could not find extensions: c:\vstsAgent_work\22\s\MyAdapter"

### Task logs

[logs_378.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3735149/logs_378.zip)

### Error logs

[Insert error from the logs here for a quick overview]
The slice of type 'Discovery' is 'Aborted' because of the error : System.Exception: Could not find extensions: c:\vstsAgent_work\22\s\MyAdapter

**Comment by ShreyasRmsft** [comment] 2019-10-23 10:13
@Roman-Rostovtsev could you tell me what the name of your custom test adapter is?

Does it end with TestAdapter.dll (note this is case sensitive as of now)?

**Comment by Roman-Rostovtsev** [comment] 2019-10-23 11:48
Yes, its name is MyTestAdapter.dll

**Comment by ShreyasRmsft** [comment] 2019-10-23 12:40
Can you rename it to My.TestAdapter.dll and try?

**Comment by Roman-Rostovtsev** [comment] 2019-10-23 13:01
I just renamed and got the same symptoms: the same error when the option is "Based on test assemblies", and tests start when the option is "Based on number of tests and agents".

**Comment by ShreyasRmsft** [comment] 2019-10-23 13:11
Can you create a simple sample repro for me on GitHub?

Have one or 2 dummy tests and your adapter with the vstest having the same inputs.

**Comment by Roman-Rostovtsev** [comment] 2019-10-23 15:22
Ok, I will try in a day or two

**Comment by Roman-Rostovtsev** [comment] 2019-10-25 15:51
I've created a repository:
https://github.com/Roman-Rostovtsev/VSTest_Experiment/
It contains dummy test adapter which just checks whether test's filename length is even and two tests.
The build defintion is here: 
[build_definition.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3772770/build_definition.zip)
And the same error: 
The slice of type 'Discovery' is 'Aborted' because of the error : System.Exception: Could not find extensions: C:\vstsAgent-Instance2\_work\6\s\MyAdapter
Logs are here:
[logs_398.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3772790/logs_398.zip)

I hope that I understood correctly what you asked.

**Comment by ShreyasRmsft** [comment] 2019-10-26 08:42
@Roman-Rostovtsev thanks, I'll set this up locally after the weekend and hopefully will be able to narrow down what the issue is.

**Comment by ShreyasRmsft** [comment] 2019-10-29 06:01
Hey, it seems to be working just fine with the repro you shared:

With Custom adapter path tests ran: https://shrer.visualstudio.com/CustomAdapterPath/_build/results?buildId=131

Without Custom adapters:
https://shrer.visualstudio.com/CustomAdapterPath/_build/results?buildId=130

**Comment by ShreyasRmsft** [comment] 2019-10-29 06:02
Let me know if you see any differences between this and your setup.

**Comment by Roman-Rostovtsev** [comment] 2019-10-29 06:40
Did you try to change the "Batch tests" option of VSTest task to "Based on test assemblies" value? I see currently in your build definition 
"distributionBatchType":"basedOnTestCases"

**Comment by ShreyasRmsft** [comment] 2019-10-29 07:05
That shouldn't make a difference but let me do so.

**Comment by ShreyasRmsft** [comment] 2019-10-29 07:08
It worked fine with "based on assemblies also"

https://shrer.visualstudio.com/CustomAdapterPath/_build/results?buildId=132

**Comment by Roman-Rostovtsev** [comment] 2019-10-29 09:13
I see, but my build still do not start tests, although it seems I removed any difference from your build definition (including double slashes in paths, changing VSTest platform to pre-release, switching to hosted agent)
My definition: [4MS-2.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3782535/4MS-2.zip)
Build logs: 
[logs_406.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3782538/logs_406.zip)
I see only one difference in build logs: version of VSTest task (2.159.1 vs 2.157.5) and DTAExecutionHost (18.159.29407.1 vs 17.157.29494.1), but I can't understand why different versions are used.

**Comment by ShreyasRmsft** [comment] 2019-10-29 13:24
It is possible that your account has not received the latest task update yet (the rollout is phased) and should reach you in a week at most.

Please let me know if you face the issue post update to the latest version. (Give it a week to get rolled out to your account).

**Comment by Roman-Rostovtsev** [comment] 2019-10-29 13:49
Ok, I will check in a week. Maybe, the issue is really fixed in upcoming updates, because I compared my and your build definitions using http://www.jsondiff.com/ and I did not find differences, except for those fields which I believe can't be related to the issue (repository, team project, auth, etc.)

**Comment by ShreyasRmsft** [comment] 2019-11-08 05:52
@Roman-Rostovtsev closing this for now. Please re-open if you are still running into this issue post the task update to version 2.159.x

**Closed by ShreyasRmsft** 2019-11-08 05:52 UTC
Labels: Area: Test, bug

**Comment by Roman-Rostovtsev** [comment] 2019-11-15 10:15
It looks like the issue was fixed in the new version of VSTest task, thanks
