### ISSUE TITLE
Add support for VS 2022 to the VSBuild and any related tasks

### ISSUE THREAD

**Issue by SvetBonev** [microsoft/azure-pipelines-tasks#15051] opened 2021-07-16 15:16 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: VSBuild

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

The Developer Division at Microsoft is working on Visual Studio 2022 which is currently in Preview. In order to enable dogfooding scenarios (and customer scenarios once VS 2022 ships) we need the VSBuild task to support the use of VS 2022.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Small snippet of current behavior:
2021-06-17T20:57:07.9214251Z ##[command]"D:\AzDO\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.187.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [16.0,17.0) -latest -format json
2021-06-17T20:57:08.0634353Z ##[command]"D:\AzDO\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.187.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [16.0,17.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json
2021-06-17T20:57:08.1007136Z ##[command]"D:\AzDO\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.187.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [15.0,16.0) -latest -format json
2021-06-17T20:57:08.1280187Z ##[command]"D:\AzDO\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.187.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [15.0,16.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json
##[warning]Visual Studio was not found. Try installing a supported version of Visual Studio. See the task definition for a list of supported versions.
##[warning]Unable to find MSBuild version '14.0' for architecture 'x86'. Falling back to version '4.0'.

**Comment by DenisRumyantsev** [comment] 2021-08-16 11:18
[This ticket](https://github.com/microsoft/build-task-team/issues/1509) will need to be closed when the issue is fixed.

**Comment by krokofant** [comment] 2021-09-07 12:11
Is this fixed in Azure Pipelines Agent v2.191.1? I see the referenced PR is merged into releases/m191 but I'm not sure where it goes from there.

I don't see it in the Azure Pipelines Agent release notes https://github.com/microsoft/azure-pipelines-agent/releases

**Comment by anatolybolshakov** [comment] 2021-09-08 12:00
@krokofant the relevant fix is currently on deployment - we will let you know once it's available.

**Comment by japj** [comment] 2021-09-14 11:41
Which version of Azure DevOps Server is expected to have the updated tasks with VS2022 support? I.e. with .NET 6 support being in VS2022?

**Comment by AnnaOpareva** [comment] 2021-09-22 12:05
Hi, @japj, @krokofant 
Support VS 2022 added to VSBuild task in version 1.192.3. Currently, this version has been deployed.

**Closed by AnnaOpareva** 2021-09-22 12:05 UTC
Labels: enhancement, Area: ABTT, Task: MSBuild, Task: VSBuild

**Comment by rizi** [comment] 2021-10-18 09:52
@AnnaOpareva how do I get the updated VSBuild Task when using Azure Dev Ops Server 2020.1 on premises?
br
