### ISSUE TITLE
helm deploy fail when install is executed

### ISSUE THREAD

**Issue by quentled** [microsoft/azure-pipelines-tasks#13614] opened 2020-09-25 14:02 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: helm deploy  

## Environment
- Server - Azure Pipelines on ubuntu 18.04, hosted agent
    
    
## Issue Description
when trying to install chart with helm deploy task , always fail due to bad command line generation: use --name flag and --dep-up flag even if not avialable for this helm version v3.3.3+g55e3ca0 (default embedded in hosted ubuntu 18.04)

## pipeline config:
  - task: HelmDeploy@0
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscription: '****'
      azureResourceGroup: '*****'
      kubernetesCluster: '***'
      namespace: 'my_ns'
      command: 'install'
      chartType: 'FilePath'
      chartPath: 'path/to/my/chart'
      releaseName: 'my_release'
      overrideValues: '/path/to/my/values.yaml'
      updateDependency: true

### Error logs
/usr/local/bin/helm version --client --short

v3.3.3+g55e3ca0

/usr/local/bin/helm install --namespace my_ns --set /path/to/my/values.yaml --dep-up --name my_release --wait /path/to/my/chart

Error: unknown flag: --dep-up
[error]Error: unknown flag: --dep-up
and the task generate --name flag which is not working too if we desactivate dependance update
[error]Error: unknown flag: --name

**Comment by Haim-Bi** [comment] 2020-09-29 05:51
also for me :( "Error: unknown flag: --name"
it seems that it no longer recognizes that the helm version is V3. since this flag no longer exists in V3.

**Comment by shigupt202** [comment] 2020-09-29 13:30
@quentled Could you please check the HelmDeployV0 task version?

**Comment by shigupt202** [comment] 2020-09-29 13:31
@Haim-Bi This seems to be a different issue.

**Comment by quentled** [comment] 2020-09-29 13:59
hello 

```
/usr/local/bin/helm version
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/vsts/work/_temp/helmTask/1601387879580/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/vsts/work/_temp/helmTask/1601387879580/config
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

**Comment by shigupt202** [comment] 2020-09-29 14:12
@quentled This is Helm version. You can find the task version at the top of the logs.

**Comment by quentled** [comment] 2020-09-29 14:18
woups sorry bad reading
Version      : 0.175.4

**Comment by shigupt202** [comment] 2020-09-29 14:22
Thanks @quentled. This issue has been taken care of in this [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/13581). The fix should be deployed soon. In the mean time, you can use older versions of Helm.
@Haim-Bi It is indeed the same issue as you reported. It will be fixed soon.

**Comment by quentled** [comment] 2020-09-29 14:26
ok the issue was about... file permission ? ok interresting, i wait the update then

**Comment by shigupt202** [comment] 2020-09-29 14:48
Helm recently introduced a security warning which appears if the kubeconfig files has group and world readable permissions. We are changing the permission to get rid of the warning. But the deployment might take some time.
I would suggest to set `failOnStderr` to false in your pipeline, or use older versions for now.

**Comment by ejlouw** [comment] 2020-09-30 14:42
I am also having the same problem.

**Comment by rikkiprince** [comment] 2020-10-02 18:12
@shigupt202 Is there an issue tracking the update to the permissions on the kubeconfig?

**Comment by shigupt202** [comment] 2020-10-02 18:16
@rikkiprince The update has already been done in this PR https://github.com/microsoft/azure-pipelines-tasks/pull/13581.
The deployment with this change should begin within few days.

**Closed** 2020-10-05 11:53 UTC
Labels: Area: Release, bug

**Comment by punjprakash** [comment] 2020-10-08 14:00
How would we know that fix of this issue has been deployed?

**Comment by ds-ms** [comment] 2020-10-09 05:58
The version of the task would be `0.176.1`

**Comment by briggsy87** [comment] 2020-12-17 01:38
@shigupt202 i stumbled across this issue since I was also getting a "[error]Error: unknown flag: --name" error.

The original poster was commenting about that issue and --dep-up not working.

Somehow, a few comments in this seemed to get bundled into the other issue mentioned in the PR about the kubeconfig permissions.

While that error was in the log that the original poster later commented, I don't believe it was the posters original issue. Instead it is that helm3 does not support --name or --dep-up anymore.

**Comment by shigupt202** [comment] 2020-12-17 06:23
@briggsy87 Because of the issue that I have referred [here](https://github.com/microsoft/azure-pipelines-tasks/pull/13581), the task was not able to identify the [Helm version](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/HelmDeployV0/src/helmcommands/helminstall.ts#L53) in use appropriately. Hence it assumed the version to be 2.x by default and that's why the install command contains `--name` and `--dep-up` flags. But since the issue is now fixed, the helm install command should not be containing these flags.
