### ISSUE TITLE
Sporadic IndexOutOfRangeException when publishing test results

### ISSUE THREAD

**Issue by jupacaza** [microsoft/azure-pipelines-tasks#6919] opened 2018-04-09 22:51 UTC
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    VSTS
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
microsoft
"Universal Store"
SC.csPayments.PaymentInstrumentFrontDoor.Gated
Build 0513.20180409
[link](https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=8968874&_a=summary)

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Universal Store RFT [link](https://microsoft.visualstudio.com/Universal%20Store/_admin/_AgentQueue?queueId=1715)

## Issue Description
Every few builds, on the vstest task on the "publish test results" stage, build fails with an IndexOutOfRangeException.
![image](https://user-images.githubusercontent.com/5615302/38527069-c8b15f02-3c0d-11e8-8c9d-6104151358fe.png)

### Error logs

...
Results File: E:\work\5\s\TestResults\wpsetwtt_azepicrft007 2018-04-09 17_02_06.trx
2018-04-09T17:03:01.1054689Z Attachments:
2018-04-09T17:03:01.1054916Z   E:\work\5\s\TestResults\9e46b9c0-61c1-4e26-a719-bf9650a94de1\wpsetwtt_azepicrft007 2018-04-09 17_01_55.coverage
2018-04-09T17:03:01.1055051Z Total tests: 326. Passed: 326. Failed: 0. Skipped: 0.
2018-04-09T17:03:01.1056274Z Test Run Successful.
2018-04-09T17:03:01.1066968Z Test execution time: 1.0723 Minutes
2018-04-09T17:03:01.5988548Z **************** Completed test execution *********************
2018-04-09T17:03:01.6794944Z Test results files: E:\work\5\s\TestResults\wpsetwtt_azepicrft007 2018-04-09 17_02_06.trx
2018-04-09T17:03:02.2148776Z Created test run: 9600815
2018-04-09T17:03:02.2149128Z Publishing test results: 326
2018-04-09T17:03:02.2181903Z Publishing test results to test run '9600815'.
2018-04-09T17:03:02.2208358Z Test results remaining: 326. Test run id: 9600815.
2018-04-09T17:03:54.0630013Z ##[error]Failure attempting to call the restapis. Method: System.Threading.Tasks.Task`1[System.Collections.Generic.IList`1[Microsoft.TeamFoundation.TestManagement.WebApi.TestCaseResult]] <PublishTestRunResults>b__1(), Exception: System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
2018-04-09T17:03:54.0643698Z    at System.Collections.Generic.List`1.Add(T item)
2018-04-09T17:03:54.0644238Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<>c__DisplayClass6_1.<<UploadTestResultAttachments>b__0>d.MoveNext() in D:\V2.0\A1\_work\38\s\Ta\Tasks\PublishTestResults\Publisher\TestResultsPublisher.cs:line 231
2018-04-09T17:03:54.0644473Z --- End of stack trace from previous location where exception was thrown ---
2018-04-09T17:03:54.0644618Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-04-09T17:03:54.0645075Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-04-09T17:03:54.0645264Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<UploadTestResultAttachments>d__6.MoveNext() in D:\V2.0\A1\_work\38\s\Ta\Tasks\PublishTestResults\Publisher\TestResultsPublisher.cs:line 237
2018-04-09T17:03:54.0645618Z --- End of stack trace from previous location where exception was thrown ---
2018-04-09T17:03:54.0645742Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-04-09T17:03:54.0645920Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-04-09T17:03:54.0646229Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<BatchUploadAttachments>d__5.MoveNext() in D:\V2.0\A1\_work\38\s\Ta\Tasks\PublishTestResults\Publisher\TestResultsPublisher.cs:line 207
2018-04-09T17:03:54.0646396Z --- End of stack trace from previous location where exception was thrown ---
2018-04-09T17:03:54.0646519Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-04-09T17:03:54.0646847Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-04-09T17:03:54.0647023Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<BatchPublishResults>d__4.MoveNext() in D:\V2.0\A1\_work\38\s\Ta\Tasks\PublishTestResults\Publisher\TestResultsPublisher.cs:line 193
2018-04-09T17:03:54.0647193Z --- End of stack trace from previous location where exception was thrown ---
2018-04-09T17:03:54.0647363Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-04-09T17:03:54.0647496Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-04-09T17:03:54.0647671Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<AddTestResultsAsync>d__1.MoveNext() in D:\V2.0\A1\_work\38\s\Ta\Tasks\PublishTestResults\Publisher\TestResultsPublisher.cs:line 62
2018-04-09T17:03:54.0647857Z    --- End of inner exception stack trace ---
2018-04-09T17:03:54.0647982Z    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2018-04-09T17:03:54.0648140Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2018-04-09T17:03:54.0648352Z    at Microsoft.VisualStudio.TestService.Utility.HttpUtil.RunTaskWithRetriesOnServiceUnavailability[T](Func`1 getTask, Boolean ignoreFailure) in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.Utility\HttpUtil.cs:line 30
2018-04-09T17:03:54.0648538Z ---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
2018-04-09T17:03:54.0648690Z    at System.Collections.Generic.List`1.Add(T item)
2018-04-09T17:03:54.0648863Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<>c__DisplayClass6_1.<<UploadTestResultAttachments>b__0>d.MoveNext() in D:\V2.0\A1\_work\38\s\Ta\Tasks\PublishTestResults\Publisher\TestResultsPublisher.cs:line 231
2018-04-09T17:03:54.0649040Z --- End of stack trace from previous location where exception was thrown ---
2018-04-09T17:03:54.0649189Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-04-09T17:03:54.0649322Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-04-09T17:03:54.0649589Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<UploadTestResultAttachments>d__6.MoveNext() in D:\V2.0\A1\_work\38\s\Ta\Tasks\PublishTestResults\Publisher\TestResultsPublisher.cs:line 237
2018-04-09T17:03:54.0649779Z --- End of stack trace from previous location where exception was thrown ---
2018-04-09T17:03:54.0650222Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-04-09T17:03:54.0651135Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-04-09T17:03:54.0651301Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<BatchUploadAttachments>d__5.MoveNext() in D:\V2.0\A1\_work\38\s\Ta\Tasks\PublishTestResults\Publisher\TestResultsPublisher.cs:line 207
2018-04-09T17:03:54.0651453Z --- End of stack trace from previous location where exception was thrown ---
2018-04-09T17:03:54.0651624Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-04-09T17:03:54.0651764Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-04-09T17:03:54.0651925Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<BatchPublishResults>d__4.MoveNext() in D:\V2.0\A1\_work\38\s\Ta\Tasks\PublishTestResults\Publisher\TestResultsPublisher.cs:line 193
2018-04-09T17:03:54.0652102Z --- End of stack trace from previous location where exception was thrown ---
2018-04-09T17:03:54.0652227Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-04-09T17:03:54.0652351Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-04-09T17:03:54.0652535Z    at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestResultsPublisher.<AddTestResultsAsync>d__1.MoveNext() in D:\V2.0\A1\_work\38\s\Ta\Tasks\PublishTestResults\Publisher\TestResultsPublisher.cs:line 62<---
2018-04-09T17:03:54.0652666Z  
2018-04-09T17:03:54.0653070Z ##[error]Failed to publish test results: One or more errors occurred.
2018-04-09T17:03:54.0653912Z Completed TestExecution Model...
2018-04-09T17:03:54.0758083Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2018-04-09T17:03:54.1277985Z ##[error]Error: E:\work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.3.28\Modules\DTAExecutionHost.exe failed with return code: 1
2018-04-09T17:03:54.2314065Z ##[error]VsTest task failed.
2018-04-09T17:03:54.4162485Z ##[section]Finishing: VsTest - CITs

**Comment by abhishkk** [comment] 2018-04-10 13:38
@Sachin077 @SadagopanRajaram 
PublishTestResults task is throwing IndexOutOfRange while adding elements to list. Can you have a look?

**Comment by Faizan2304** [comment] 2018-10-05 13:51
Hi @bowerhaus, we are looking into it and will update you soon. 
One question: What is the version of TFS you are using? Is this TFS 2018 Update2?

**Comment by bowerhaus** [comment] 2018-10-05 14:13
It is TFS 2018 Update 3.

**Comment by Faizan2304** [comment] 2018-10-05 14:45
Thanks @bowerhaus for the info. I will update the thread soon.

**Comment by Faizan2304** [comment] 2018-10-12 12:47
Hi @bowerhaus,

We got the root cause of the issue. 
Will it work for you if we will provide you a dll with the fix which you can drop in your agent folder?

Thanks,
Faizan

**Comment by bowerhaus** [comment] 2018-10-12 14:10
Hi @Faizan2304, that would be cool, thanks.

**Comment by SadagopanRajaram** [comment] 2018-10-19 06:46
Hi @bowerhaus 
Can you please follow the steps in the link below to open a support ticket to make sure we get the fix to you in an appropriate manner? 
https://support.microsoft.com/en-us/getsupport?oaspworkflow=start_1.0.0.0&wf=0&wfname=productselection&gprid=10453&ccsid=636125714937824749&forceorigin=esmc
Thanks and sorry for the inconvenience
Sada

**Comment by bowerhaus** [comment] 2018-10-30 15:04
Hi @utkarshagoswami, we are in fact using on-premise TFS so I will follow the suggestion from @SadagopanRajaram and create a TFS ticket once I find out how to get hold of our TFS Support AccessID.

**Comment by bowerhaus** [comment] 2018-11-02 16:44
Hi @SadagopanRajaram. I have just spent a large part of this afternoon (circa 90 minutes) attempting to register a support ticket. I don't want to go into details but the Microsoft support phone line is excruciating to use, long winded and was ultimately ineffective. I found a support chat service that did issue me an AccessID but that errored in the support website. The chat agent then told me to use the phone line again, which I am not going to go through again.

Thank you for investigating (and fixing) this issue but it looks like I am going to have to continue with our stop-gap workaround and wait until your fix ultimately appears in the final product.

Best regards

**Comment by SadagopanRajaram** [comment] 2018-11-08 09:56
@bowerhaus 
I am sorry about your experience with the support process. 
If the issue is not resolved, please reach out to me at sadar@microsoft.com and I can see how to facilitate the creation of the support ticket and take it forward. 
Thanks
Sadagopan Rajaram

**Comment by bowerhaus** [comment] 2018-11-22 16:59
Hi @SadagopanRajaram. I have emailed you directly.
Best regards

**Comment by sahaassa** [comment] 2019-05-02 05:52
We are also getting this error when the build try to rerun failed tests, what is the solution?

**Comment by puagarwa** [comment] 2019-05-03 08:44
@sahaassa can you give us information about the product and version you are using, because we have fixed this issue sometime back.
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting
Environment

    Server - VSTS or TFS on-premises?
    VSTS

        If using TFS on-premises, provide the version:

        If using VSTS, provide the account name, team project name, build definition name/build number:
       
    Agent - Hosted or Private:

        If using Hosted agent, provide agent queue name:

        If using private agent, provide the OS of the machine running the agent and the agent version:

**Comment by navin22** [comment] 2020-01-08 06:22
Closing this issue, Please open another one. If you still face the issue.

**Closed by navin22** 2020-01-08 06:22 UTC
Labels: Area: Test, Area: TestManagement
