### ISSUE TITLE
VsTestV2: Rerun of failed NUnit TestCase fails.

### ISSUE THREAD

**Issue by vinnyrose** [microsoft/azure-pipelines-tasks#10202] opened 2019-04-24 14:45 UTC
## Required Information
**Question, Bug, or Feature?**
*Type*: Bug

**Enter Task Name**: VsTestV2

## Environment
- Server - Azure Pipelines
- Agent - Private: Microsoft Windows Server 2016 Datacenter

## Issue Description

​Setup a NUnit unit test using the TestCaseAttribute like so:

    namespace Regression.Tests
    {
    	internal sealed class FeatureFile
    	{
    		[TestCase("Test Case A")]
    		[TestCase("Test Case B")]
    		public void ScenarioTestCase(string name)
    		{
    			Assert.Fail();
    		}
    	}
    }

​Using the "Visual Studio Test" task for pipelines configured with "Rerun failed tests" on. Run this test.

After the test fails it is rerun using a TestCaseFilter by the "Visual Studio Test" task like so:

    vstest.console.exe "D:\a1\_work\r2\a\Tests\drop\Regression\bin\Release\Regression.dll"
    2019-04-24T08:04:38.4556922Z /Settings:"D:\a1\_work\_temp\u20tdeotmzp.runsettings"
    2019-04-24T08:04:38.4559489Z /Logger:"trx"
    2019-04-24T08:04:38.4561502Z /TestAdapterPath:"D:\a1\_work\r2\a\Tests"
    2019-04-24T08:04:38.4562416Z /Diag:"D:\a1\_work\_temp\Attempt-1_2d234l.diag"
    2019-04-24T08:04:38.4689722Z 
    /TestCaseFilter:"FullyQualifiedName=Regression.Tests.FeatureFile.ScenarioTestCase(\"Test Case 
    A\")|FullyQualifiedName=Regression.Tests.FeatureFile.ScenarioTestCase(\"Test Case B\")"

​Which will fail with the following error:

    2019-04-24T08:04:45.9116598Z ##[error]The test source file "D:\a1\_work\_temp\Case" provided was not found.

If the test name was `Regression.Tests.FeatureFile.ScenarioTestCase("Test Event")` the error would be:

    2019-04-24T08:04:45.9116598Z ##[error]The test source file "D:\a1\_work\_temp\Event" provided was not found.

If the test name was `Regression.Tests.FeatureFile.ScenarioTestCase("Test Frequency")` the error would be:

    2019-04-24T08:04:45.9116598Z ##[error]The test source file "D:\a1\_work\_temp\Frequency" provided was not found.

The unescaped spaces in the test name seem to be the issue.

**Comment by prawalagarwal** [comment] 2019-05-20 09:47
@vinnyrose For rerun to work correctly, our test results publisher unit should understand and publish the results of data driven tests correctly. The VsTest task today supports only MsTest based data driven tests and hence this scenario(nunit) is not supported.

**Comment by prawalagarwal** [comment] 2019-05-21 07:04
Closing this issue as this is by design today. Please reopen if you have any concerns here.

**Closed by prawalagarwal** 2019-05-21 07:04 UTC
Labels: Area: Test, bug

**Comment by vinnyrose** [comment] 2019-05-28 15:09
I was able to get reruns working by setting a custom batch size of 10000 and disabling diagnostics.
