### ISSUE TITLE
Secrets can be extracted in agent job with couple of lines of PowerShell code

### ISSUE THREAD

**Issue by alexmbaker** [microsoft/azure-pipelines-tasks#10588] opened 2019-06-06 03:41 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShell

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/AzurePosweShell

## Environment
- Server - Azure Pipelines 
- Agent - Private (Windows Server 2016)

## Issue Description

I have found that I can obtain all the authentication information for the Service Principal configured to run the task.  It takes a couple of lines of PowerShell code and reveals this information:

![image](https://user-images.githubusercontent.com/2808984/59005187-e06cad00-885f-11e9-9cd4-cdf5bc9eb192.png)

Is this supposed to be so easy?

**Comment by JustinGrote** [comment] 2019-06-06 16:52
Yes. It's still encrypted at rest, and if you specify it as a secret variable, Pipelines will attempt to mask it in output if possible.

You very specifically made an action to get at it. It doesn't show by default.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch

**Comment by Lovakumar** [comment] 2019-06-11 05:44
This is related to secrets in job/agent - passing onto core team.

**Comment by craigmpeters** [comment] 2019-08-20 10:04
Please can you say how to do this, I am unable to find a passed variable and need to actually debug how to find that variable and having a list of them would be great

**Comment by JustinGrote** [comment] 2019-08-20 14:59
@craigmpeters 
Just somewhere in your script do:
Get-Variable | ft | out-string
or
$env | ft | out-string

To get a summary of related variables. If you're debugging though, you really should read the section about debugging powershell using the azure functions core tools, you can set breakpoints and all taht fun stuff.

**Comment by craigmpeters** [comment] 2019-08-21 13:14
Cheers - Managed to work it out using Parameters into the script itself but might use this to see if it is there and I can streamline things a bit

**Comment by alexmbaker** [comment] 2019-08-24 12:54
Sorry for the delay, I have included a sample script below that gets the secrets and writes them out so you can see them in the task log.  

``` PowerShell
$m = Get-Module 'VstsTaskSdk' 
$stuff= $m.SessionState.PSVariable.Get("vault").Value

$taskVariables=@{}

$stuff.GetEnumerator() | % {
        $info =$_.Value.GetNetworkCredential()
        $taskVariables.Add($info.UserName, $info.Password)
    } 
$taskVariables | Out-Host
```

**Comment by alexmbaker** [comment] 2019-08-24 13:16
One solution would be to add the code below in to the task however I am not really sure this is the "Right" way to address the problem (Mainly because it assumes something about the internal implementation of the SDK)

Perhaps the SDK should be updated so that it has public function that can be called to clear all stored secrets?  This will address the issue for any DevOps takss that use the updated SDK code, not sure about tasks that don't use the updatd SDK.  Might need a little thought and ideas from a few people however my initial sense is that it won't be an issue.
``` PowerShell
    # Clear values from VstsTaskSdk variable vault before invoking the script to prevent 
    # people fishing for credentials
    Get-Module 'VstsTaskSdk' | ForEach-Object {
        $sdkVariableVault = $_.SessionState.PSVariable.GetValue('vault') -as [System.Collections.IDictionary]
        if ($sdkVariableVault) {
           $sdkVariableVault.Clear()
        }
    }
```
 Task | File | Line 
------|-----|-----
AzurePowerShellV2 | AzurePowerShell.ps1 | 102 
AzurePowerShellV3 | AzurePowerShell.ps1 | 105 
AzurePowerShellV3 | AzurePowerShell.ps1 | 84 
ServiceFabricPowerShellV1 | ServiceFabricPowerShell.ps1 |  71

**Comment by damccorm** [comment] 2019-11-20 17:41
This is working as designed. Secrets are meant only to mask exact matches - e.g. if you mask `abc`, the following output:

```
abc
helloabcworld
a
bc
adbc
```

should result in:

```
*****
hello*****world
a
bc
adbc
```

If people are able to arbitrarily run a script, they can just arbitrarily manibulate/send the secret anyways, at that point our security boundary has already been crossed. Closing since I don't think this is an issue, please comment if you think it should be reopened.

**Closed by damccorm** 2019-11-20 17:41 UTC
Labels: Area: Core, bug
