### ISSUE TITLE
Failed to restore nuget since NuGetCommand version 2.146.0

### ISSUE THREAD

**Issue by maboulianne** [Microsoft/azure-pipelines-tasks#9446] opened 2019-01-29 13:46 UTC
## Troubleshooting
Since the version 2.146.0 of the NuGetCommand our private agent failed to restore the nuget package from our artefact.

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Windows\ServiceProfiles\NetworkService\AppData\Local\NuGet\plugins-cache\7dfd0fa0c00db55241517876f045626154b6f02c$CredentialProvider.Microsoft.exe\https_comerco.pkgs.visualstudio.com_packaging_ea8caa50-9cf8-4ed7-b410-5bca3b71ec1c_nuget_v3_index.json.dat-new'.

## Environment
Server: Azure Pipelines   
Account name: Comerco Services
Team projet: Pueblo
Build definition: Pueblo (MAIN), 2019.1.28.11 to 2019.1.29.3
Private Agent:    
    - OS: Windows Server 2016 Standard
    - Agent version: 2.144.2

### Task logs

2019-01-29T12:56:21.8350754Z ##[section]Starting: NuGet restore $/Pueblo/Main/Comerco.Pueblo.BuildServer.sln
2019-01-29T12:56:21.8467272Z ==============================================================================
2019-01-29T12:56:21.8467340Z Task         : NuGet
2019-01-29T12:56:21.8467400Z Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Package Management and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
2019-01-29T12:56:21.8467438Z Version      : 2.146.0
2019-01-29T12:56:21.8467477Z Author       : Microsoft Corporation
2019-01-29T12:56:21.8467532Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613747)
2019-01-29T12:56:21.8467566Z ==============================================================================
2019-01-29T12:56:23.5115157Z SYSTEMVSSCONNECTION exists true
2019-01-29T12:56:23.7509954Z SYSTEMVSSCONNECTION exists true
2019-01-29T12:56:24.1704158Z [command]C:\Windows\system32\chcp.com 65001
2019-01-29T12:56:24.1724796Z Active code page: 65001
2019-01-29T12:56:24.2070497Z Detected NuGet version 4.9.3.5777 / 4.9.3+e5150f1e119e456e01c4f1e413213d392eda1c3a
2019-01-29T12:56:24.2084551Z SYSTEMVSSCONNECTION exists true
2019-01-29T12:56:24.3662172Z Saving NuGet.config to a temporary config file.
2019-01-29T12:56:24.3677191Z [command]c:\agent\_work\_tool\NuGet\4.9.3\x64\nuget.exe sources Add -NonInteractive -Name ea8caa50-9cf8-4ed7-b410-5bca3b71ec1c -Source https://comerco.pkgs.visualstudio.com/_packaging/ea8caa50-9cf8-4ed7-b410-5bca3b71ec1c/nuget/v3/index.json -ConfigFile c:\agent\_work\2\Nuget\tempNuGet_6880.config
2019-01-29T12:56:24.9531716Z Package Source with Name: ea8caa50-9cf8-4ed7-b410-5bca3b71ec1c added successfully.
2019-01-29T12:56:24.9574233Z [command]c:\agent\_work\_tool\NuGet\4.9.3\x64\nuget.exe sources Add -NonInteractive -Name NuGetOrg -Source https://www.nuget.org/api/v2/ -ConfigFile c:\agent\_work\2\Nuget\tempNuGet_6880.config
2019-01-29T12:56:25.4824728Z Package Source with Name: NuGetOrg added successfully.
2019-01-29T12:56:25.4855256Z [command]c:\agent\_work\_tool\NuGet\4.9.3\x64\nuget.exe restore c:\agent\_work\2\s\Main\Comerco.Pueblo.BuildServer.sln -NoCache -Verbosity Detailed -NonInteractive -ConfigFile c:\agent\_work\2\Nuget\tempNuGet_6880.config
2019-01-29T12:56:32.0226268Z NuGet Version: 4.9.3.5777
2019-01-29T12:56:32.0226524Z MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
2019-01-29T12:56:32.0226571Z MSBuild P2P timeout [ms]: 372000
2019-01-29T12:56:32.0227228Z C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin\msbuild.exe "C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\NuGetScratch\yqdormga.lko.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\NuGetScratch\cfbthcvp.3nb.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="c:\agent\_work\_tool\NuGet\4.9.3\x64\nuget.exe" /p:RestoreSolutionDirectory="c:\agent\_work\2\s\Main\\" /p:RestoreConfigFile="c:\agent\_work\2\Nuget\tempNuGet_6880.config" /p:SolutionDir="c:\agent\_work\2\s\Main\\" /p:SolutionName="Comerco.Pueblo.BuildServer"
2019-01-29T12:56:32.0227450Z 
2019-01-29T12:56:32.0227509Z Running restore with 8 concurrent jobs.

…. LOG TRUNCATE TOO LONG

2019-01-29T12:56:32.0547896Z Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/api/v2/FindPackagesById()?id='System.Windows.Interactivity.WPF'&semVerLevel=2.0.0'.
2019-01-29T12:56:32.0547939Z Could not find file 'C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\NuGet\TempCache\33b25c18-377b-4ca7-99a1-6754c02572a7\ylcwmjb0.gmn'.
2019-01-29T12:56:32.0548032Z   GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Windows.Interactivity.WPF'&semVerLevel=2.0.0
2019-01-29T12:56:32.0548084Z System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Windows\ServiceProfiles\NetworkService\AppData\Local\NuGet\plugins-cache\7dfd0fa0c00db55241517876f045626154b6f02c$CredentialProvider.Microsoft.exe\https_comerco.pkgs.visualstudio.com_packaging_ea8caa50-9cf8-4ed7-b410-5bca3b71ec1c_nuget_v3_index.json.dat-new'.
2019-01-29T12:56:32.0548131Z    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2019-01-29T12:56:32.0548220Z    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
2019-01-29T12:56:32.0548267Z    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
2019-01-29T12:56:32.0548438Z    at NuGet.Protocol.Plugins.PluginCacheEntry.<UpdateCacheFileAsync>d__20.MoveNext()
2019-01-29T12:56:32.0548476Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0548515Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0548587Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0548626Z    at NuGet.Protocol.Core.Types.PluginManager.<>c__DisplayClass24_0.<<TryCreatePluginAsync>b__0>d.MoveNext()
2019-01-29T12:56:32.0548664Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0548702Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0548775Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0548818Z    at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__2`1.MoveNext()
2019-01-29T12:56:32.0548928Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0548967Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0549044Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0549082Z    at NuGet.Protocol.Core.Types.PluginManager.<TryCreatePluginAsync>d__24.MoveNext()
2019-01-29T12:56:32.0549120Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0549197Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0549240Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0549278Z    at NuGet.Protocol.Core.Types.PluginManager.<CreatePluginsAsync>d__22.MoveNext()
2019-01-29T12:56:32.0549321Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0549415Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0549453Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0549492Z    at NuGet.Protocol.Core.Types.PluginResourceProvider.<TryCreate>d__3.MoveNext()
2019-01-29T12:56:32.0549560Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0549718Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0549756Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0549795Z    at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
2019-01-29T12:56:32.0549876Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0549923Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0549965Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0550004Z    at NuGet.Protocol.PluginFindPackageByIdResourceProvider.<TryCreate>d__1.MoveNext()
2019-01-29T12:56:32.0550080Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0550115Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0550157Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0550230Z    at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
2019-01-29T12:56:32.0550268Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0550302Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0550341Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0550520Z    at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
2019-01-29T12:56:32.0550558Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0550592Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0550631Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0550708Z    at NuGet.Commands.SourceRepositoryDependencyProvider.<EnsureResource>d__26.MoveNext()
2019-01-29T12:56:32.0550746Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0550780Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0550853Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0550891Z    at NuGet.Commands.SourceRepositoryDependencyProvider.<FindLibraryCoreAsync>d__20.MoveNext()
2019-01-29T12:56:32.0551006Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0551045Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0551164Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0551203Z    at NuGet.Commands.SourceRepositoryDependencyProvider.<>c__DisplayClass19_0.<<FindLibraryAsync>b__0>d.MoveNext()
2019-01-29T12:56:32.0551241Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0551314Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0551352Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0551390Z    at NuGet.Commands.SourceRepositoryDependencyProvider.<FindLibraryAsync>d__19.MoveNext()
2019-01-29T12:56:32.0551433Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0551523Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0551561Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0551599Z    at NuGet.DependencyResolver.ResolverUtility.<>c__DisplayClass7_1.<<FindLibraryFromSourcesAsync>b__0>d.MoveNext()
2019-01-29T12:56:32.0551685Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0551723Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0551762Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0551800Z    at NuGet.DependencyResolver.ResolverUtility.<FindLibraryFromSourcesAsync>d__7.MoveNext()
2019-01-29T12:56:32.0551872Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0551919Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0551958Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0551996Z    at NuGet.DependencyResolver.ResolverUtility.<FindLibraryByVersionAsync>d__6.MoveNext()
2019-01-29T12:56:32.0552073Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0552111Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0552150Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0552227Z    at NuGet.DependencyResolver.ResolverUtility.<FindLibraryMatchAsync>d__4.MoveNext()
2019-01-29T12:56:32.0552265Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0552303Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0552431Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0552512Z    at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d__1.MoveNext()
2019-01-29T12:56:32.0552547Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0552585Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0552666Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0552704Z    at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
2019-01-29T12:56:32.0552743Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0552777Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0552850Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0552965Z    at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
2019-01-29T12:56:32.0553003Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0553042Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0553127Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0553165Z    at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
2019-01-29T12:56:32.0553199Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0553272Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0553310Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0553349Z    at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
2019-01-29T12:56:32.0553400Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0553477Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0553515Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0553554Z    at NuGet.Commands.ProjectRestoreCommand.<WalkDependenciesAsync>d__10.MoveNext()
2019-01-29T12:56:32.0553630Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0553669Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0553707Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0553746Z    at NuGet.Commands.ProjectRestoreCommand.<TryRestoreAsync>d__8.MoveNext()
2019-01-29T12:56:32.0553818Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0553865Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0553908Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0553946Z    at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__47.MoveNext()
2019-01-29T12:56:32.0554023Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0554057Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0554095Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0554181Z    at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__32.MoveNext()
2019-01-29T12:56:32.0554223Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0554258Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0554296Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0554505Z    at NuGet.Commands.RestoreRunner.<ExecuteAsync>d__7.MoveNext()
2019-01-29T12:56:32.0554543Z --- End of stack trace from previous location where exception was thrown ---
2019-01-29T12:56:32.0554582Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-01-29T12:56:32.0554620Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-29T12:56:32.0554693Z    at NuGet.Commands.RestoreRunner.<ExecuteAndCommitAsync>d__6.MoveNext()
2019-01-29T12:56:32.0983042Z ##[error]The nuget command failed with exit code(1) and error(Could not find a part of the path 'C:\Windows\ServiceProfiles\NetworkService\AppData\Local\NuGet\plugins-cache\7dfd0fa0c00db55241517876f045626154b6f02c$CredentialProvider.Microsoft.exe\https_comerco.pkgs.visualstudio.com_packaging_ea8caa50-9cf8-4ed7-b410-5bca3b71ec1c_nuget_v3_index.json.dat-new'.)
2019-01-29T12:56:32.0991341Z ##[error]Packages failed to restore
2019-01-29T12:56:32.1010797Z ##[section]Finishing: NuGet restore $/Pueblo/Main/Comerco.Pueblo.BuildServer.sln

SEE LOG
[log.txt](https://github.com/Microsoft/azure-pipelines-tasks/files/2829633/log.txt)

**Comment by apluche** [comment] 2019-01-29 23:05
Hello, thank you for your feedback. In order to better diagnose the problem, could you provide screen shots of the build definition and a copy of the complete log?

**Comment by sveinungf** [comment] 2019-01-31 14:53
We are having the same problem with version 2.146.0.
`The nuget command failed with exit code(1) and error(Could not find a part of the path 'C:\Users\ContainerAdministrator\AppData\Local\NuGet\plugins-cache\c50444a6546e4527f65494b9ee653f38383e5351$CredentialProvider.Microsoft.exe\https_norskbyggtjeneste.pkgs.visualstudio.com_packaging_7b7c9cda-b0dc-4a0a-afee-249a132ad756_nuget_v3_index.json.dat-new'.)`

A workaround is to downgrade the NuGet task to version 1.0.9.

**Comment by OneCyrus** [comment] 2019-02-03 11:31
same issue here. the problem looks like the generated filename (for the cache file) is too long and not valid for NTFS.

**Comment by maboulianne** [comment] 2019-02-04 19:58
>           Hello, thank you for your feedback. In order to better diagnose the problem, could you provide screen shots of the build definition and a copy of the complete log with system.debug set to true?

The log was added to the post.

**Comment by maboulianne** [comment] 2019-02-04 20:00
Same issue using 2.146.1

**Comment by zarenner** [comment] 2019-02-06 02:59
@OneCyrus I agree that MAX_PATH type issues would seem to be a likely culprit, especially since the plugin cache dat-new file path is exactly 260 in both examples above.

That said, I've thoroughly tried to reproduce this with plugin cache sizes of various lengths and I haven't been able to on my machine.

Could you please try setting the environment variable NUGET_PLUGINS_CACHE_PATH to a shorter path, and see if that resolves the issue? If so, I can report this issue on https://github.com/NuGet/Home and hopefully they can spot the difference.

**Comment by zarenner** [comment] 2019-02-06 03:39
Filed an issue with NuGet. Once @maboulianne confirms that setting NUGET_PLUGINS_CACHE_PATH to a shorter path is a viable workaround, I'd like to close this issue and continue discussion in the NuGet issue, since this is an issue in NuGet itself.

**Comment by maboulianne** [comment] 2019-02-06 20:35
@zarenner Yes when I set the variable NUGET_PLUGINS_CACHE_PATH to C:\NugetCache it's working. 

It's a viable workaround for me.

**Comment by zarenner** [comment] 2019-02-06 20:47
Great, thanks for confirming.

We're also investigating rolling out a hotfix to automatically set NUGET_PLUGINS_CACHE_PATH to a shorter path when appropriate.

Since this is a NuGet issue, and there's a viable workaround, let's continue discussion of this issue on the NuGet issue https://github.com/NuGet/Home/issues/7770. I'm going to close this issue.

**Closed by zarenner** 2019-02-06 20:47 UTC
Labels: Area: Packaging
