### ISSUE TITLE
Dotnet pack automatic package versioning build number clarification

### ISSUE THREAD

**Issue by anoordende** [Microsoft/azure-pipelines-tasks#5655] opened 2017-10-17 07:19 UTC
## Environment
Server: VSTS
Agent: Hosted VS 2017

Task: .NET Core (Preview)
Version: 2.* (preview)
Command: pack

## Issue Description

When setting the "Automatic package versioning" to "Use the build number", I had expected the package version to be exactly as set in "Options" => "Build number format". However, the package was versioned as "1.0.0".

The following format was set in "Build number format":
``1.0.0-$(Build.SourceBranchName)$(Rev:.r)``

This is not necessarily a defect, as I believe that rather than using this value literally, the task attempts to extract a version number from this value.

However, this should be clarified in the tooltip or the option should be renamed (e.g. "Extract from build number"). In this last case, perhaps the option of "Use the build number" could be re-purposed to use the literal build number.

### Workaround

_Anyone faced with the same issue and looking for a workaround:_

Set "Automatic package versioning" to "Use an environment variable" and "Environment variable" to ``Build.BuildNumber``

**Comment by rddesmit** [comment] 2018-06-29 08:03
I created a ticket for the same issue on User Voice before seeing this one.

https://developercommunity.visualstudio.com/content/problem/283259/dotnet-pack-automatic-package-versioning-doesnt-wo.html

**Comment by alexmullans** [comment] 2019-04-01 22:43
Closing this as a duplicate of #6136 , as both the NuGet and dotnet tasks use the same underlying shared versioning code.

**Closed by alexmullans** 2019-04-01 22:43 UTC
Labels: Area: Artifacts, bug
