### ISSUE TITLE
CacheBeta: Skipping because the job status was not 'Succeeded'

### ISSUE THREAD

**Issue by ivailop** [microsoft/azure-pipelines-tasks#11457] opened 2019-09-27 20:01 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CacheBeta

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://s2technologies.visualstudio.com/testspace/_build/results?buildId=1101

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Ubuntu 16.04

## Issue Description

Task defined as:
```
- task: CacheBeta@0
  inputs:
    key: bundle | $(Agent.OS) | Gemfile.lock
    path: $(BUNDLE_PATH)
  displayName: Cache bundle gems
```

"Post-job: Cache bundle gems" does nothing, simply saying `Skipping because the job status was not 'Succeeded'.`.

The purpose of caching is to reduce the build time related to dependencies and should not be affected by the outcome of other steps, e.g. tests failure. 

### Task logs

```
##[section]Starting: Cache bundle gems
==============================================================================
Task         : Cache (Beta)
Description  : Cache files between runs
Version      : 0.1.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key `bundle | Linux | Gemfile.lock`...
File hashes summarized as `hTIqJ3fX2+6SXJd6UpzXFnYQqQATflNFows4Jkh5BZc=` from BASE64(SHA256(`
SHA256(s/Gemfile.lock)=[15008]0DBAA318817D73F39C93650B7E988CD82747B05B005D252DC1B3B5BD74200106`))
Resolved to `bundle|Linux|hTIqJ3fX2+6SXJd6UpzXFnYQqQATflNFows4Jkh5BZc=`.
##[warning]Skipping because the job status was not 'Succeeded'.
##[section]Finishing: Cache bundle gems
```

**Comment by n1ckyb** [comment] 2019-09-30 13:24
I'm facing a similar issue to the one mentioned above.

I think it would make sense if this was configurable with some option like 
```
skipOnFailure: true | false
```

Does this option already exist?

**Comment by johnterickson** [comment] 2019-11-04 21:08
Duplicate of #11388

**Closed by johnterickson** 2019-11-04 21:08 UTC
Labels: Area: ArtifactsCore, Area: PipelineCaching, enhancement
