### ISSUE TITLE
Variable build.artifactstagingdirectory  undefined for the release pipeline

### ISSUE THREAD

**Issue by VarunChopraAccolite** [Microsoft/azure-pipelines-tasks#9691] opened 2019-02-26 09:05 UTC
## Troubleshooting
Using the variable `agent.TempDirectory` instead of `build.artifactstagingdirectory`

## Environment
- Server - Azure Pipelines or TFS on-premises
    - TFS 2018
    - Azure DevOps 

- Agent - Private:
    - Windows 10 OS of the machine running the agent and the agent version: 2.1.44

## Issue Description
The variable `build.artifactstagingdirectory`  undefined for the release pipelines and works for the build

### Error logs
Error "Path must be a string. Received undefined"

**Comment by kmkumaran** [comment] 2019-02-28 07:33
Release does not have a staging directory. If you are looking for artifacts you can use the System.ArtifactsDirectory. 

You can refer the below link for supported variables.
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#default-variables

**Comment by gykuma** [comment] 2019-03-12 09:52
Closing this issue as it's not a bug. Please let know us if you have any further queries.

**Closed by gykuma** 2019-03-12 09:52 UTC
Labels: Area: Release
