### ISSUE TITLE
Warnings about Resource file already set when using AzureKeyVault v1.212.0

### ISSUE THREAD

**Issue by jsloan117** [microsoft/azure-pipelines-tasks#17127] opened 2022-11-03 17:07 UTC
## Required Information

*Type*: Bug

**Enter Task Name**: AzureKeyVault

## Environment
- Agent - Private: 
  - OS: RHEL7
  - Version: 2.211.1

## Issue Description

Dozens of warnings about "Resource file already set". This started today, from what I can tell.

```text
##[warning]Resource file has already set to: /opt/buildagent/_work/_tasks/AzureKeyVault_1e244d32-2dd4-4165-96fb-b7441ca9331e/1.212.0/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json
```

**Comment by jdaugherty** [comment] 2022-11-03 22:18
For us, this started happening in a build done on Nov 1st at 1:51 PM.  It did not occur in the previous build that ran on Oct 26 at 6:01 PM.  It's happening in the pre-job task for us, where it transfers secrets from the keyvault to populate the library values.

**Comment by Poovamma** [comment] 2022-11-04 06:37
+1 . 
We are facing issues with the same. We are seeing multiple warnings while fetching secrets from Azure Key vault using the task 
- task: AzureKeyVault@1 

Error 

` ##[warning]Resource file has already set to: /azp/agent/_work/_tasks/AzureKeyVault_1e244d32-2dd4-4165-96fb-b7441ca9331e/1.212.0/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json`

**Comment by IanMoroney** [comment] 2022-11-04 11:11
This just started happening for us too, and i get 12+ warnings in some pipelines.

**Comment by IanMoroney** [comment] 2022-11-04 11:17
@chshrikh , @thesattiraju , @tauhid621 could someone get this bug assigned and resolved? It's causing too many false positives and devs have now started ignoring warnings altogether in the pipelines.

**Comment by fmck** [comment] 2022-11-04 15:28
We are seeing the same issue, multiple warnings per build all on a pre-job to grab secrets from key vault.

**Comment by Turbofroggy** [comment] 2022-11-04 17:18
We are seeing this in our pipelines as well.

**Comment by schrx1964** [comment] 2022-11-07 11:44
we are seeing this in our buil pipelines again since a couple of days. Last Tuesday everything was still ok.

**Comment by gpkrieger** [comment] 2022-11-07 15:17
We are seeing this in our build pipelines as well, the pipelines finish successfully, but it doesn't seem to be actually updating with values from the keyvault.  to test, I deleted one of my keys used in the pipeline, and the pipeline still finished successfully, and the app still used the old key value.

**Comment by JagadeeshVenkatesan** [comment] 2022-11-08 05:37
+1 
I started seeing these warnings from Friday onwards and still see them in all my pipelines(100+), can anyone help me with it?

**Comment by gorziza** [comment] 2022-11-08 20:07
We have the same problem!

**Comment by at-besa** [comment] 2022-11-09 09:24
+1 We also started seeing this issue in our pipelines about a week ago. This also turned out that most of the people ignore the warnings now.

**Comment by AnkitPathak41** [comment] 2022-11-09 09:25
+1 We are also facing the same issue more than 300 warnings for keyvault task in Azure DevOps pipeline

**Comment by jcontti-axa** [comment] 2022-11-09 12:34
+ 1 same problem here, more than 200 warnings :(

**Comment by v-mohithgc** [comment] 2022-11-09 13:32
Task version has been rolled back to 1.211.2

**Comment by jwikman** [comment] 2022-11-09 14:14
We've got AzureKeyVault auto updated to v1.212.0 on a lot of our self-hosted server agents.

Is there any easy way to revert all those to v1.211.2?

**Comment by v-mohithgc** [comment] 2022-11-09 16:11
> We've got AzureKeyVault auto updated to v1.212.0 on a lot of our self-hosted server agents.
> 
> Is there any easy way to revert all those to v1.211.2?

Hi, you can try to clean agent tasks cache.

Example path:
<agentname>\_work\_tasks\*

**Comment by at-besa** [comment] 2022-11-09 17:08
> > We've got AzureKeyVault auto updated to v1.212.0 on a lot of our self-hosted server agents.
> > Is there any easy way to revert all those to v1.211.2?
> 
> Hi, you can try to clean agent tasks cache.
> 
> Example path: {agentname}\ _work \ _tasks *

I already tried that and it does not help, these warnings appear immediatly with the first run after cleaning.

**Comment by That1Guy007** [comment] 2022-11-09 18:55
We are also running into this issue. Any resolution so far? It is for our download secrets task from a variable group that is linked to an azure key vault.

**Comment by v-mohithgc** [comment] 2022-11-10 06:32
https://github.com/microsoft/azure-pipelines-tasks/pull/17151 revert is completed, will take time to roll out 213

**Comment by hilari0n** [comment] 2022-11-14 17:38
We're using Azure DevOps and Hosted Agents and we're not directly referencing this task in our pipelines, but we are using variable groups, defined based on Azure KeyVault, which probably causes implicit use of this task. This basically translates to all of our pipelines being affected by this issue, with no way to address it, without remaking all our pipelines to explicitly use the task in a corrected version.

**Comment by abatishchev** [comment] 2022-11-14 17:43
@v-mohithgc can you please share the status of the rollout? namely when the new version is expected to land on `msazure`?

**Comment by hilari0n** [comment] 2022-11-14 17:59
The issue is also being [raised on the StackOverflow](https://stackoverflow.com/questions/74288802).

**Comment by jwikman** [comment] 2022-11-15 06:42
I'm having the same setup as @hilari0n, on hosted agents with variable groups.
My agents are still downloading 1.212.0 of AzureKeyVault... 
I've tried to delete the 1.212.0 folder and files from the `[agent folder]\_work\_tasks\AzureKeyVault_1e244d32-2dd4-4165-96fb-b7441ca9331e` folder, but 1.212.0 is downloaded as soon as I start a pipeline. The agent is running version 2.213.2.

When can we expect that 1.213.0 is in use when variable groups are used?
I've got more than a hundred pipelines affected by this, so refactoring from variable groups to explicit use of the AzureKeyVault task isn't appealing.

**Comment by tomaustin700** [comment] 2022-11-15 08:22
Like others have said; this happens when a pipeline references a variable group linked to a Key Vault. It doesn't seem to cause any actual issues but I've got 252 warnings thrown in one of my largest pipelines.

**Comment by IanMoroney** [comment] 2022-11-16 09:45
it's fixed for me after the revert

**Comment by andrii-lundiak** [comment] 2022-11-17 16:22
**BAD**
At first I used variables group defined in AzureDevOps Library section with reusing dedicated (filtered out) KeyVault values (via KeyVault Connection) and as turned out AzureKeyVault was `1.212.0` was in usage and the the issue flow is almost exactly as @hilari0n described. 

```
##[warning]Resource file has already set to: 
/home/vsts/work/_tasks/AzureKeyVault_***244*****33**
/1.212.0/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json
```

I tried different combinations with library and KeyVault, but issue still was happening.

**OK**
I then detached from using Library entry, and I configured `AzureKeyVault` task in my YAML file directly as such:

```
 - task: AzureKeyVault@1 # expected 1.212.0 as latest version. Try later to hardcode version to 1.211.2
    inputs:
      azureSubscription: $(myAzureSubscription)
      KeyVaultName: $(myKeyVaultName)
      runAsPreJob: false
      SecretsFilter: 'MYSECRETKEY'
```

Actual version got as `1.211.2` WHICH IS with NO issues (no warnings).

**OK**
But this way I ALSO realize, that I really narrow down filtered out number of secrets, which is OK but still doesn't answer why that warning wasn't there and then appeared.

**WEIRD but OK**
Anyway I got from above comments and mentioned PRs, that official version for `azure-pipelines-tasks-azure-arm-rest-v2` package got reverted, and now I decided to also TRY using `AzureKeyVault@2`, which got me ` 2.211.1` actual version. BUT then that task did NOT get my KeyVault secret was NOT shown as "downloaded" in logs. I suspected something bad will happen w my code. But whole YAML and code flow was OK.

**OK vs. OK**
So looks like, for now it's either 
- OK/safe for me to hardcode version `1.211.2`... But it's a pity I should do it.
- Or use latest `AzureKeyVault@2` version

**Comment by bdbvb** [comment] 2022-11-18 14:15
> #17151 revert is completed, will take time to roll out 213

@v-mohithgc 

When I run a YAML pipeline with a build stage and a deployment stage, the build stage gets the offending version (1.212.0), whereas the deployment stage gets the reverted version (1.211.2).

Steps to reproduce:

- In Azure Devops create a project with a Git repo and a YAML pipeline. The YAML is listed below.
- In Azure, create a Key Vault with a secret named “a-secret” with an arbitrary value.
- In the Azure DevOps project, under Pipelines > Library, create a variable group called BuildSecrets, link that to the Key Vault mentioned above, and select “a-secret” as one of the variables.
- Run the pipeline.
- Look in the execution logs and see warnings.

```
name: $(Build.DefinitionName)_$(Year:yy)$(DayOfYear)$(Rev:.r)

trigger:
- main

pool:
  vmImage: windows-2022

stages:
- stage: Build
  displayName: Build
  variables:
    - group: BuildSecrets
    # mapped standard variables for secrets
    - name: my-secret
      value: $(a-secret)
  jobs:
  - job: MyJob
    steps:
    - script: echo '$(my-secret)'

- stage: ReleaseDev
  displayName: Release-Dev
  dependsOn: Build
  condition: succeeded()
  variables:
    - group: BuildSecrets
    # mapped standard variables for secrets
    - name: my-secret
      value: $(a-secret)
  jobs:
  - deployment: Release
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - pwsh: echo '$(my-secret)'
```

The same sort of thing happens for me with a single on-prem build agent.

**Comment by ArPharazon** [comment] 2022-11-20 07:38
I'm still seeing keyvault version 1.212.0 in our hosted build agent logs.

`2022-11-20T07:05:34.5946940Z ##[section]Starting: Download secrets: xxxxxxxxxxxxxxxxxx
2022-11-20T07:05:34.6201738Z ==============================================================================
2022-11-20T07:05:34.6202822Z Task         : Azure Key Vault
2022-11-20T07:05:34.6203471Z Description  : Download Azure Key Vault secrets
2022-11-20T07:05:34.6203782Z Version      : **1.212.0**
2022-11-20T07:05:34.6204541Z Author       : Microsoft Corporation
2022-11-20T07:05:34.6205170Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-key-vault
2022-11-20T07:05:34.6205611Z ==============================================================================
2022-11-20T07:05:35.1724980Z ##[warning]Resource file has already set to: /home/vsts/work/_tasks/AzureKeyVault_1e244d32-2dd4-4165-96fb-b7441ca9331e/1.212.0/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json
2022-11-20T07:05:35.1737798Z ##[warning]Resource file has already set to: /home/vsts/work/_tasks/AzureKeyVault_1e244d32-2dd4-4165-96fb-b7441ca9331e/1.212.0/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json
2022-11-20T07:05:35.1740612Z ##[warning]Resource file has already set to: /home/vsts/work/_tasks/AzureKeyVault_1e244d32-2dd4-4165-96fb-b7441ca9331e/1.212.0/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json
2022-11-20T07:05:35.1850162Z ##[section]Finishing: Download secrets: xxxxxxxxxxxxxxxxxx`

How do we get the fixed version ?

**Comment by skkulla** [comment] 2022-11-23 09:39
I am running into the same issue using Variable group, is there a way to define Azure Key Vault version to use when defining the variable group in pipelines.

**Comment by swenkeratmicrosoft** [comment] 2022-11-23 17:27
@chshrikh , @thesattiraju , @tauhid621 - my team is completely ignoring all warnings in pipelines until this is fixed because it's showing us so many false alarms - hundreds per day.

I'm a Microsoft internal FTE, so whomever owns this in Azure can feel free to contact me directly for a repro, logs, anything you need to get this resolved.

**Comment by v-mohithgc** [comment] 2022-11-24 09:05
Hi all, Quick update: Azure KV version 213 (both task and variable group) which fixes the warning issue, has been rolled out to south Brazil and EUS2 region for now. There is a slight delay, but version 213 will be rolled out to all regions and users by end of December 1st week.

**Comment by cdcadman** [comment] 2022-12-05 17:32
Starting with version 1.213.0, this warning is showing up in the PipAuthenticate@1 task.  The task seems to be working correctly aside from the warning.  Previously, we were using version 1.206.0.

**Comment by DanielGoehler** [comment] 2022-12-05 19:09
With version 213 the warning is gone on our side.

**Comment by hilari0n** [comment] 2023-06-04 19:59
Can someone confirm if this is addressed and where (which tasks) have this addressed?
Companies are paying a crap ton of money for MSDN subscriptions/licenses, which cover the Azure DevOps, plus another crap ton of money for additional services on Azure DevOps (like hosted agents) and we can't even get an update on if an issue is resolved or not. Do we need to pay for that separately? Is it like with Apple products, that you have to pay for each and every feature separately?

**Comment by v-mohithgc** [comment] 2023-06-12 06:43
> Can someone confirm if this is addressed and where (which tasks) have this addressed? Companies are paying a crap ton of money for MSDN subscriptions/licenses, which cover the Azure DevOps, plus another crap ton of money for additional services on Azure DevOps (like hosted agents) and we can't even get an update on if an issue is resolved or not. Do we need to pay for that separately? Is it like with Apple products, that you have to pay for each and every feature separately?

Hi, in which task are you experiencing these warnings.?

**Comment by timtucker-dte** [comment] 2023-06-13 21:33
We're seeing it in AzureAppServiceSettings tasks every time that they run.
Version: 1.223.0

Looking at old logs, I doesn't look like it was happening in 1.215.0, but it was happening in 1.221.102

**Comment by v-mohithgc** [comment] 2023-06-21 10:03
Warning issue related to AzureAppServiceSetting and AzureResourceGroupDeployment has been addressed. 
The fix will be rolled out soon in version 224.

**Comment by fvilches17** [comment] 2023-07-26 00:14
At time of writing (26 Jul 2023):
I'm getting this issue with task `AzureWebApp@1` version `1.225.0`

``` log
2023-07-25T23:57:44.8421143Z ##[section]Starting: Deploy WebApp
2023-07-25T23:57:44.8426147Z ==============================================================================
2023-07-25T23:57:44.8426279Z Task         : Azure Web App
2023-07-25T23:57:44.8426357Z Description  : Deploy an Azure Web App for Linux or Windows
2023-07-25T23:57:44.8426450Z Version      : 1.225.0
2023-07-25T23:57:44.8426514Z Author       : Microsoft Corporation
2023-07-25T23:57:44.8426596Z Help         : https://aka.ms/azurewebapptroubleshooting
2023-07-25T23:57:44.8426682Z ==============================================================================
2023-07-25T23:57:45.2901880Z ##[warning]Resource file has already set to: /home/vsts/work/_tasks/AzureWebApp_18bde28a-8172-45cb-b204-5cef1393dbb1/1.225.0/node_modules/azure-pipelines-tasks-azure-arm-rest-v2/module.json
2023-07-25T23:57:45.2941925Z Got service connection details for Azure App Service:'<app>'
2023-07-25T23:57:52.0968295Z Package deployment using ZIP Deploy initiated.
2023-07-25T23:58:12.6896647Z Deploy logs can be viewed at <link>
2023-07-25T23:58:12.6897019Z Successfully deployed web package to App Service.
2023-07-25T23:58:19.8789852Z Successfully updated deployment History at <link>
2023-07-25T23:58:20.5368868Z App Service Application URL: <url>
2023-07-25T23:58:22.6338825Z ##[section]Finishing: Deploy WebApp
```

**Comment by v-mohithgc** [comment] 2023-07-26 05:08
@fvilches17 version 1.225.1 will contain the fix.

**Comment by ThomasArdal** [comment] 2023-07-26 11:51
I'm seeing this on both 1.x and 2.x of the _Azure Functions Deploy_ task on a Hosted agent.

**Comment by v-mohithgc** [comment] 2023-07-26 12:12
> I'm seeing this on both 1.x and 2.x of the _Azure Functions Deploy_ task on a Hosted agent.

Hi @ThomasArdal , version 224 of Azure Function Deploy V2 and version 225.1 of V1 task will contain the fix for this issue.

Version 224 of Azure Function Deploy V2 should be out to all region by now, please rerun and confirm.
Thanks

**Comment by ThomasArdal** [comment] 2023-07-26 12:39
Seems like it is still an issue:

![image](https://github.com/microsoft/azure-pipelines-tasks/assets/563206/c446ec64-f20f-4d85-ba1a-ed06ed50225e)

**Comment by v-mohithgc** [comment] 2023-07-26 12:48
> Seems like it is still an issue:
> 
> ![image](https://user-images.githubusercontent.com/563206/256232731-c446ec64-f20f-4d85-ba1a-ed06ed50225e.png)

apologies, version 2.225.0 will contain the fix. Here is the PR https://github.com/microsoft/azure-pipelines-tasks/pull/18592.

**Comment by v-mohithgc** [comment] 2023-08-09 09:17
This issue is now resolved, feel free to reopen if the issue still persist. 
Thanks

**Closed by v-mohithgc** 2023-08-09 09:17 UTC
Labels: Area:RM
