### ISSUE TITLE
[REGRESSION]: AzureFileCopy@6 no longer works with "Workload identity federation" service connection

### ISSUE THREAD

**Issue by Mikkelcv** [microsoft/azure-pipelines-tasks#19767] opened 2024-04-12 13:02 UTC
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureFileCopy

### Breaking task version

6.238.1

### Last working task version

6.237.5

### Regression Description

Using a WIF Service connection from Azure DevOps to Azure
Storage account in Azure.

When the task runs the copy command then earlier I would see:

> Uploading files from source path: 'D:\a\1\a\xxx.zip' to storage account: 'storage_xyz' in container: 'container_xyz' with blob prefix: ''
>  & azcopy copy "D:\a\1\a\xxx.zip" "https://storage_xyz.blob.core.windows.net/container_xyz/" --log-level=INFO --recursive
> INFO: Scanning...
> INFO: Login with Powershell context succeeded
> INFO: Authenticating to destination using Azure AD

however from yesterday when the new task was live in our tenant then:

> Uploading files from source path: 'D:\a\1\a\xxx.zip' to storage account: 'storage_xyz' in container: 'container_xyz' with blob prefix: ''
>  & "AzCopy\AzCopy.exe" copy "D:\a\1\a\xxx.zip" "https://storage_xyz.blob.core.windows.net/container_xyz/"  --log-level=INFO --recursive
> INFO: Scanning...
> To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code xxxxxxx to authenticate.

Then the task just blocks and fails after 1-2 minutes

**Work-a-round**,
I have now removed the AzureFileCopy task and replaced it with a AzureCLI@2 task using the same service connection and calling:

> az storage blob upload --account-name $Env:StorageAccountName -c $Env:ContainerName -f $Env:File --overwrite true --auth-mode login --only-show-errors

which is working, so I believe it is not the service connection.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

windows-2022

### Relevant log output

```shell
Uploading files from source path: 'D:\a\1\a\xxx.zip' to storage account: 'storage_xyz' in container: 'container_xyz' with blob prefix: ''
 & "AzCopy\AzCopy.exe" copy "D:\a\1\a\xxx.zip" "https://storage_xyz.blob.core.windows.net/container_xyz/"  --log-level=INFO --recursive
INFO: Scanning...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code xxxxxxx to authenticate.
```

### Full task logs with system.debug enabled

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
trigger: none

pool:
  vmImage: windows-2022

steps:
- task: ArchiveFiles@2
  displayName: "Zip Doc"
  inputs:
    rootFolderOrFile: $(Agent.BuildDirectory)/s/doc
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/doc.zip'
    replaceExistingArchive: true

- task: AzureFileCopy@6
  displayName: "Upload Doc to Blob"
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/doc.zip'
    azureSubscription: 'Az Subscription'
    Destination: 'AzureBlob'
    storage: 'storage_xyz'
    ContainerName: 'container_xyz'
    BlobPrefix: 'test'
```

**Comment by weznellxrm** [comment] 2024-04-12 13:47
experiencing the same issue as well. Reverted service connection and still the same issue with device login

**Comment by m-soltani** [comment] 2024-04-12 13:56
We are encountering the same issue in our production pipelines. Could you please prioritize resolving this matter? We depend greatly on this task's functionality.

**Comment by m-soltani** [comment] 2024-04-12 14:15
yeah, we can't though. We have switched our storage account to use only Entra ID authentication schema. We have done many changes that we can't revert back. Our service connection is converted to use federated authentication which means we need to create a new one which works with secrets, .... 👎🏻. I would expect that the changes are fully tested before rolling out.

**Comment by joe-cisar** [comment] 2024-04-12 14:24
Having the same issue I thought it was something I had done. Glad to see I'm not going crazy.

**Comment by weznellxrm** [comment] 2024-04-12 14:42
look like they bumped it up to azcopy 10.24 yesterday from 10.12. [here](https://github.com/microsoft/azure-pipelines-tasks/pull/19756/files#diff-11b7ac2e9f588d7b4853cb5e8af968dd1b4ef9aeea234075178043d0681024fb)

**Comment by m-soltani** [comment] 2024-04-12 14:47
> look like they bumped it up to azcopy 10.24 yesterday from 10.12. [here](https://github.com/microsoft/azure-pipelines-tasks/pull/19756/files#diff-11b7ac2e9f588d7b4853cb5e8af968dd1b4ef9aeea234075178043d0681024fb)

But the version has changed from `6.238.4` to `6.238.6` however, this task is however failing since `6.238.1` which means the issue has been introduced in earlier versions. This is of course my understanding.

**Comment by m-soltani** [comment] 2024-04-12 15:05
> > look like they bumped it up to azcopy 10.24 yesterday from 10.12. [here](https://github.com/microsoft/azure-pipelines-tasks/pull/19756/files#diff-11b7ac2e9f588d7b4853cb5e8af968dd1b4ef9aeea234075178043d0681024fb)
> 
> But the version has changed from `6.238.4` to `6.238.6` however, this task is failing since `6.238.1` which means the issue has been introduced in earlier versions. This is of course my understanding.

I found [this PR](https://github.com/microsoft/azure-pipelines-tasks/pull/19715/files) which introduced the `6.238.1` version. In release notes property, they mention to use azcopy 10.24 as mentioned above. Somehow things got convoluted. The user can't enforce the version of azcopy being used in `AzureFileCopy` pipeline task. Ah such a mess 👎🏻

**Comment by m-soltani** [comment] 2024-04-12 16:55
This task version employs an outdated version of azcopy, which contains a bug resolved in version 10.24. The fix has already been implemented in [this pull request](https://github.com/microsoft/azure-pipelines-tasks/pull/19756), which updates the underlying azcopy command. However, this patched version still needs to be deployed to the MS-hosted agents. Is there an estimated timeline for when this update will be rolled out?

**Comment by rkoumans** [comment] 2024-04-15 06:20
Is there a update on this? We are experiencing the same

**Comment by DevTestUser123** [comment] 2024-04-16 04:35
Facing same issue can somebody pls help ?

**Comment by MarksPoint** [comment] 2024-04-16 07:18
Same issue at our end! 
We've got release pipelines using AzCopy v6 with a standard (non workflow identity) service connection and we see the same message, asking to go to the device login page and provide a code.

**Comment by DevTestUser123** [comment] 2024-04-16 09:57
Yes it's working, thank you!

**Comment by MarksPoint** [comment] 2024-04-16 12:30
I can confirm as well that it's working correctly now.
Working version was **6.238.9**, where version 6.238.1 was the last one I noticed failing.

**Comment by m-soltani** [comment] 2024-04-16 12:50
Yes, it's working fine now. Thank you 👍🏻

**Closed** 2024-04-16 12:55 UTC
Labels: bug, regression, Area:RM
