### ISSUE TITLE
[Question]: Self hosted agent can't find java environment variable: JAVA_HOME_17_x64

### ISSUE THREAD

**Issue by ser789654** [microsoft/azure-pipelines-tasks#19050] opened 2023-10-02 13:31 UTC
### Task name

Maven@3

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

azul/zulu-openjdk

### Question

```shell
Im using self hosted agent with image: azul/zulu-openjdk where is java openJDK 17 preinstalled and environment variables already set:

JAVA_HOME_17_x64=/usr/lib/jvm/zulu17-ca-amd64/
JAVA_HOME=/usr/lib/jvm/zulu17-ca-amd64/

My task looks like this:

    - task: Maven@3
      displayName: 'sonarAnalysis'
      inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx1024m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          jdkArchitectureOption: 'x64'
          goals: sonar:sonar ............

and it gives me this error:

##[error]Unhandled: Failed to find the specified JDK version. Please ensure the specified JDK version is installed on the agent and the environment variable 'JAVA_HOME_17_X64' exists and is set to the location of a corresponding JDK or use the [Java Tool Installer](https://go.microsoft.com/fwlink/?linkid=875287) task to install the desired JDK.

but the variable JAVA_HOME_17_X64 is already set. What could be wrong?
```

**Comment by ivanduplenskikh** [comment] 2023-10-02 18:09
@ser789654, could you check please that the env variable `JAVA_HOME_17_x64` is set?
I noticed that only `JAVA_HOME` variable is set in [Dockerfile](https://github.com/zulu-openjdk/zulu-openjdk/blob/master/ubuntu/17-latest/Dockerfile#L21)

Can you add a step with variable printing?
```powershell
- task: PowerShell@2
  displayName: Display the environment variable JAVA_HOME_17_X64 value
  inputs:
    targetType: 'inline'
    script: echo $env:JAVA_HOME_17_X64
```

**Comment by Siedlerchr** [comment] 2023-10-04 09:38
Create a file .env in the root directory of the runner and add the variable there:
JAVA_HOME_17_X64=/usr/lib/jvm/java-17-openjdk-amd64

I had the same problem with our runners

**Comment by ivanduplenskikh** [comment] 2023-10-16 09:38
@ser789654, could you confirm whether the issue is resolved or not?

**Comment by ivanduplenskikh** [comment] 2023-10-25 09:52
I'm closing the issue, feel free to open it if it's still relevant to you.

**Closed by ivanduplenskikh** 2023-10-25 09:52 UTC
Labels: Area: Release
