### ISSUE TITLE
Nothing will be added to build artifact 'drop'

### ISSUE THREAD

**Issue by theharpretsingh** [microsoft/azure-pipelines-tasks#16813] opened 2022-08-29 03:41 UTC
I am trying to host a simple java maven "hello world project" but i am encountering the error:##[warning]Directory '/home/azureuser/myagent/_work/3/a' is empty. Nothing will be added to build artifact 'drop'.
![image](https://user-images.githubusercontent.com/110823944/187118400-4deff099-730d-404a-8aff-6dc7a9b4c6ee.png)

These are the parameters i have set:
![image](https://user-images.githubusercontent.com/110823944/187118562-a32a978f-b9ef-44b7-ae0a-14bc665ac67a.png)
![image](https://user-images.githubusercontent.com/110823944/187118600-52caf900-e059-4750-baec-196a941384d1.png)
![image](https://user-images.githubusercontent.com/110823944/187118638-7bef07b9-8fd6-43d1-9742-2cb462044f08.png)

**Comment by DmitriiBobreshev** [comment] 2022-08-29 09:17
Hello @theharpretsingh! Thank you for the feedback. Initially, the problem is that $(Build.ArtifactStagingDirectory) are empty, 
so as I see you try to copy .jar file by mask **/*.jar and this is fine and should work, but could you please check that maven compiled the project successfully and that you have jar file as the result(like no warnings or errors)?

Also, I created [a sample repo](https://github.com/DmitriiBobreshev/azure-simple-maven-package-artifact) for you as an example of how it works, maybe it might be helpful.

**Comment by theharpretsingh** [comment] 2022-08-29 09:26
hello @DmitriiBobreshev , Thank you for your response. There is this particular warning:
![image](https://user-images.githubusercontent.com/110823944/187169733-ff05fdbf-09ff-4d1b-afdb-78a331a73f96.png)


thank you i will check out the repo.

**Comment by DmitriiBobreshev** [comment] 2022-08-29 11:27
Hello @theharpretsingh , the first warning was fixed [here](https://github.com/microsoft/azure-pipelines-tasks/commit/5278cb5c9e77d0d363a7fde07150a41e02d6b9ca) and will fix after release task version to 2.209.
The second one just saying that the directory from publishing task is empty, that's why we need to put jar/project files in it through CopyFiles Task, so could you please check/provide us [debugging logs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops) if repo will not help you. Thanks.

**Comment by DmitriiBobreshev** [comment] 2022-09-08 07:25
Hi @theharpretsingh, please tell me if it worked out for you and if we can close the ticket?

**Comment by DmitriiBobreshev** [comment] 2022-09-12 07:41
Hi @theharpretsingh closing this one as external - feel free to ask any other questions or let us know if it's still relevant for you.

**Closed by DmitriiBobreshev** 2022-09-12 07:41 UTC
Labels: question, Area: Release, Task: PublishBuildArtifacts
