### ISSUE TITLE
[BUG]: AppCenter Distribute task failed after latest release - 20 04

### ISSUE THREAD

**Issue by jjnanthakumar** [microsoft/azure-pipelines-tasks#18148] opened 2023-04-20 14:00 UTC
### Task name

AppCenterDistribute Task V3

### Task version

3.221.1

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

2017

### Operation system

Mac/Windows

### Task log

```shell
2023-04-20T13:54:43.1060550Z ##[debug]Evaluating condition for step: 'Distribute to Visual Studio App Center - Dev'
2023-04-20T13:54:43.1075620Z ##[debug]Evaluating: succeeded()
2023-04-20T13:54:43.1077240Z ##[debug]Evaluating succeeded:
2023-04-20T13:54:43.1082620Z ##[debug]=> True
2023-04-20T13:54:43.1086280Z ##[debug]Result: True
2023-04-20T13:54:43.1087830Z ##[section]Starting: Distribute to Visual Studio App Center - Dev
2023-04-20T13:54:43.1240300Z ==============================================================================
2023-04-20T13:54:43.1240700Z Task         : App Center distribute
2023-04-20T13:54:43.1240930Z Description  : Distribute app builds to testers and users via Visual Studio App Center
2023-04-20T13:54:43.1241270Z Version      : 3.221.1
2023-04-20T13:54:43.1241310Z Author       : Microsoft Corporation
2023-04-20T13:54:43.1241350Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/app-center-distribute
2023-04-20T13:54:43.1241380Z ==============================================================================
2023-04-20T13:54:43.7481830Z ##[error]/Users/admin/myagent/_work/_tasks/AppCenterDistribute_71ef4996-b8d7-410d-8604-65030b29b134/3.221.1/node_modules/@azure/storage-blob/dist/index.js:13909
async function delay(timeInMs, aborter, abortError) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/admin/myagent/_work/_tasks/AppCenterDistribute_71ef4996-b8d7-410d-8604-65030b29b134/3.221.1/azure-blob-upload-helper.js:13:24)
2023-04-20T13:54:43.7482880Z ##[debug]Processed: ##vso[task.issue type=error;]/Users/admin/myagent/_work/_tasks/AppCenterDistribute_71ef4996-b8d7-410d-8604-65030b29b134/3.221.1/node_modules/@azure/storage-blob/dist/index.js:13909%0Aasync function delay(timeInMs, aborter, abortError) {%0A      ^^^^^^^^%0ASyntaxError: Unexpected token function%0A    at createScript (vm.js:56:10)%0A    at Object.runInThisContext (vm.js:97:10)%0A    at Module._compile (module.js:542:28)%0A    at Object.Module._extensions..js (module.js:579:10)%0A    at Module.load (module.js:487:32)%0A    at tryModuleLoad (module.js:446:12)%0A    at Function.Module._load (module.js:438:3)%0A    at Module.require (module.js:497:17)%0A    at require (internal/module.js:20:19)%0A    at Object.<anonymous> (/Users/admin/myagent/_work/_tasks/AppCenterDistribute_71ef4996-b8d7-410d-8604-65030b29b134/3.221.1/azure-blob-upload-helper.js:13:24)
2023-04-20T13:54:43.7605580Z ##[section]Finishing: Distribute to Visual Studio App Center - Dev
```

### Relevant log output

```shell
async function delay(timeInMs, aborter, abortError) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/admin/myagent/_work/_tasks/AppCenterDistribute_71ef4996-b8d7-410d-8604-65030b29b134/3.221.1/azure-blob-upload-helper.js:13:24)
```

**Comment by jjnanthakumar** [comment] 2023-04-20 14:03
Most of the pipelines started failing - Not able to distribute in AppCenter. Please help us ASAP

**Comment by geertbleyen** [comment] 2023-04-21 09:03
Having the same issue :(

**Comment by lucen-ms** [comment] 2023-04-21 15:23
New version with the fix has been published - 3.221.3

**Comment by lucen-ms** [comment] 2023-04-21 16:11
What node version do you use? We expect node 16.

**Comment by jjnanthakumar** [comment] 2023-04-22 06:16
We haven't installed the node explicitly in the agent machine. In the old version it worked properly in the same agent machine without any issues.

Do you think it is related to the node version?

If possible could you please let me know how I can install the 0.0.4 version from the marketplace?

**Comment by lucen-ms** [comment] 2023-04-24 08:42
@jjnanthakumar could you please check what node is used?
The task is built for Node 16 and previously errors were caused because it was built for Node 10.

**Comment by jjnanthakumar** [comment] 2023-04-24 10:10
@lucen-ms When I checked via the command line it throws an Unrecognized command error.

**Comment by vbtrek** [comment] 2023-04-24 13:06
We're also seeing the same error that @jjnanthakumar is seeing with our DevOps 2019 self hosted build agents:
Unhandled: globalThis is not defined

**Comment by afranz33** [comment] 2023-04-24 15:41
Seeing same issue as @jjnanthakumar  and @vbtrek self hosted 2020 Devops, happened within a week. Any new ticket?

**Comment by andreas-nesheim** [comment] 2023-04-25 08:04
We are experiencing the same problem as @jjnanthakumar. We are running Azure DevOps Server 2020. Our build agents, where this task is running on, has explicitly installed Node version 18.15.0.

> Fix does not work for DevOps 2019/2020

Does this mean that there is a fix in progress, but that it will not be shipped to 2019/2020?

**Comment by afranz33** [comment] 2023-04-25 14:47
@Oleg-Karoza 

Mac Agent

- Agent version: 2.181.2
- macOS Big Sur 11.3
- Not sure what is runner image as well.

More Agent info below, thanks in advance.

![agentinfo](https://user-images.githubusercontent.com/7128754/234314567-b47ddcfa-b611-4ebb-a8f6-b55fc131f36d.png)

**Comment by jjnanthakumar** [comment] 2023-04-25 15:14
![image](https://user-images.githubusercontent.com/46053893/234322473-cf20a17a-bcc8-44ac-a6d5-620f75f9db8b.png)

**Comment by samaraluyza** [comment] 2023-04-25 20:09
We are facing the same issue:

Azure Devops Server 2019


![image](https://user-images.githubusercontent.com/17437411/234363651-d5c7acca-b6ea-42fd-969d-392bfa9012af.png)


Error: 
```
Unhandled: globalThis is not defined
ReferenceError: globalThis is not defined
    at Object.<anonymous> (E:\Agentes\a2\_work\_tasks\AppCenterDistribute_71ef4996-b8d7-410d-8604-65030b29b134\3.221.3\node_modules\@azure\core-util\dist\index.js:241:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (E:\Agentes\a2\_work\_tasks\AppCenterDistribute_71ef4996-b8d7-410d-8604-65030b29b134\3.221.3\node_modules\@azure\core-http\dist\index.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
```

I believe it uses the node version in <agent_install_directory>/externals/node/bin/node  or <agent_install_directory>/externals/node/bin/node10 - So if you agent is older it will have as default the node 6/10 version.  

To make the task work again I copied node's new version (18) to myagent/externals/node/bin/node10. After I changed it my task worked again.

The real way to fix is update azure devops server and agent to newest version.

**Comment by andreas-nesheim** [comment] 2023-04-26 06:49
> We have tested the task `0.0.7` with the different Node versions (`10.24.1`, `14.21.3`, `16.20.0`, `18.15.0`, `18.16.0`) and it works correctly on our environment @andreas-nesheim @jjnanthakumar @afranz33 @vbtrek please share
> 
> * Current agent version
> * Operating System
> * Runner Image
> 
> You will find these details in your pipeline logs the step is "Initialize job"

- Agent version: 2.181.2
- Operating system: Windows Server 2012 R2
- Runner image: ??

**Comment by Oleg-Karoza** [comment] 2023-04-26 13:33
We need some time to reproduce this behaviour on the specific agent versions, I will keep this issue updated

**Comment by Oleg-Karoza** [comment] 2023-04-28 14:58
New version with the fix has been published - 3.221.4
@andreas-nesheim @jjnanthakumar @afranz33 @vbtrek @samaraluyza please confirm it works on your agent

**Comment by vbtrek** [comment] 2023-04-28 15:45
I'm still getting the same error:
![image](https://user-images.githubusercontent.com/26403480/235193286-76097759-f53a-4fd0-b960-54efd84720e9.png)

But looking at the log in details it's still running 3.221.3
[log_64_44504.zip](https://github.com/microsoft/azure-pipelines-tasks/files/11355179/log_64_44504.zip)

I tried restarting the agent service, then ran another build. How do we trigger the agent to download the new version?

**Comment by vbtrek** [comment] 2023-05-02 10:06
Retested again today and all working perfectly, must have jut needed time to propagate the new build.

Thanks

**Comment by lucen-ms** [comment] 2023-05-04 11:00
Thank you @vbtrek for confirmation - I close the issue as fixed.

**Closed by lucen-ms** 2023-05-04 11:00 UTC
Labels: bug, Area: Release, triage
