### ISSUE TITLE
Xamarin.iOS task fails when using C# features of minor language version (C# 7.1)

### ISSUE THREAD

**Issue by TechWatching** [microsoft/azure-pipelines-tasks#10829] opened 2019-07-05 06:45 UTC
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: XamariniOS

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: Hosted macOS

## Issue Description

Xamarin.iOS task fails as C# 7.1 features are used in the code. The csproj of the solution are properly configured to use the latest minor version of the language but build fails anyway.

### Error logs

error CS8107: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.
[error]Xamarin.iOS task failed with error Error: /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild failed with return code: 1. For guidance on setting up the build pipeline, see https://go.microsoft.com/fwlink/?LinkId=760847.

**Comment by TechWatching** [comment] 2019-07-05 07:28
Specifying the latest Mono SDK does not solve the issue.

**Comment by garie** [comment] 2019-08-23 12:16
I was able to work around this by updating the language version to 7.3. This is not an ideal solution as it means you'll need to watch for new versions to be released in order to be updated, but it'll allow you to use the newer features.

In Visual Studio for Mac, right-click your project, choose Options, Build > General, Language Options > C# Language Version.

<img width="960" alt="Screen Shot 2019-08-23 at 8 15 25 AM" src="https://user-images.githubusercontent.com/236433/63591914-322ef480-c57e-11e9-9607-9f3876957c98.png">

**Comment by ryanbuening** [comment] 2019-10-22 19:20
I'm also getting this error when running my Xamarin pipeline. Is there a way to specify the C# version in the YAML?

**Comment by mdobric** [comment] 2019-11-19 22:17
I tried this as well as setting the language version value to "latest" but neither worked in the pipeline.

> I was able to work around this by updating the language version to 7.3. This is not an ideal solution as it means you'll need to watch for new versions to be released in order to be updated, but it'll allow you to use the newer features.
> 
> In Visual Studio for Mac, right-click your project, choose Options, Build > General, Language Options > C# Language Version.
> 
> <img alt="Screen Shot 2019-08-23 at 8 15 25 AM" width="960" src="https://user-images.githubusercontent.com/236433/63591914-322ef480-c57e-11e9-9607-9f3876957c98.png">

**Comment by egor-bryzgalov** [comment] 2020-05-06 12:43
@TechWatching @mdobric  Could you please provide us with contents of your .csproj file? If not please check if 'LangVersion' 7.0 or less is not specified explicitly in the property group related to the aimed build configuration in the .csproj file. You can do it by following steps:
1. Open .csproj file with any text editor (e.g. Visual Studio Code, Notepad etc.);
2.  Find 'PropertyGroup' tag which condition attribute matches build configuration specified in YAML file ('buildForSimulator' and 'configuration' inputs) e.g. 'Release|iPhone'; 
3. Find 'LangVersion' tag and verify if it is not explicitly set to 7;
4. Change it to 7.1 if it is set to 7 or completely delete 'LangVersion' tag.

You may also check all other property groups just to be on the safe side. We look forward to hearing from you!

**Comment by TechWatching** [comment] 2020-05-06 13:09
I won't be able to answer as I don't work on the project where I had the problem and have no access to the code anymore. From what I remember it was not explicitely set to 7 lang version but to the "latest" value. Setting to a specific version like 7.1 would work however I think. But "latest" should have work. Sorry no be able to help more, it has been a while since I created this issue. The easier to reproduce would be to create blank Xamarin project, add a csharp piece of code that use a C# 7.1 feature like default litteral (I think it is what I used) and add an Azure pipeline on that.

**Comment by egor-bryzgalov** [comment] 2020-05-06 13:51
@TechWatching Thank you for the response! We didn't manage to reproduce the issue by testing the task the way you described until the wrong C# version was specified explicitly.

@mdobric @ryanbuening Could you please let us know if the issue is still reproduced?

**Comment by ryanbuening** [comment] 2020-05-06 21:33
@egor-bryzgalov Sorry, I am scrapped my Xamarin pipeline for the time being so I cannot tell you if it is still happening for me.

**Comment by egor-bryzgalov** [comment] 2020-05-18 11:11
@mdobric Could you please confirm that the issue is still reproduced? Thank you!

**Comment by egor-bryzgalov** [comment] 2020-05-21 11:29
Closing the issue due to lack of information, please feel free to reopen it.

**Closed by egor-bryzgalov** 2020-05-21 11:29 UTC
Labels: Area: ABTT, bug
