### ISSUE TITLE
AzureFunctionApp@1 ERROR: Invalid connection string - The "AzureWebJobsStorage" connection string configured is invalid

### ISSUE THREAD

**Issue by phil000** [microsoft/azure-pipelines-tasks#17093] opened 2022-10-26 00:00 UTC
**Type**: Bug
**Task Name**: AzureFunctionApp@1
**Environment**: Azure DevOps, Hosted Agent

The AzureFunctionApp@1 deployment task has upgraded itself today and we now get this ERROR logged as a warning:

**##[warning]ERROR: Invalid connection string - The "AzureWebJobsStorage" connection string configured is invalid (e.g. missing some required elements). Please check the value of the app setting "AzureWebJobsStorage".**

With task version: **1.211.1**

We are using Key Vault References for the 'AzureWebJobsStorage' connection string.
e.g.
```@Microsoft.KeyVault(SecretUri=https://blah)```

The previous task version 1.209.0 did not report this issue and there has been no change on our end.

Replacing the Key Vault Reference with the actual connection string and the ERROR goes away.
e.g.
``` DefaultEndpointsProtocol=https;AccountName=xxxx;AccountKey=yyyy==;EndpointSuffix=core.windows.net```

**Comment by phil000** [comment] 2022-10-26 07:04
There's also this other new weird error logged as a warning.

**##[warning]ERROR: Function app is NOT VNet integrated.**

Whoever said we needed our function app to be VNet integrated. Hardly an ERROR.

**Comment by HenrikSommer-eng** [comment] 2022-11-28 10:45
We have the same problem any update on this?

**Comment by Shuvajyoti** [comment] 2022-11-28 18:41
Facing similar issue with function app using keyvault reference.

**Comment by HenrikSommer-eng** [comment] 2022-11-29 08:03
The same problem seem to be here:
https://github.com/MicrosoftDocs/azure-docs/issues/27555
And it contains a workaround how ever it will give some downtime.

**Comment by AltusBaard** [comment] 2022-11-30 03:05
Having the exact same issue, everything works fine, just one giant error showing as a warning on the pipeline

> The same problem seem to be here: [MicrosoftDocs/azure-docs#27555](https://github.com/MicrosoftDocs/azure-docs/issues/27555) And it contains a workaround how ever it will give some downtime.

Don't think that is the same issue, our connection string resolves fine in the keyvault reference, only error is in the deployment pipeline. I did try set the specific version as they mentioned, but no joy

**Comment by phil000** [comment] 2022-11-30 03:12
We are also not having any issue at runtime. 
Our issue is that the deployment task reports phoney errors as warnings.
1. _"Invalid connection string"_ -> The connection string is not invalid, as a key vault reference is perfectly valid.
2. _"Function app is NOT VNet integrated"_ -> We don't have to do that. This is informational at best.

**Comment by AltusBaard** [comment] 2022-11-30 03:15
I am starting to think that the pipeline somehow needs permission to see the keyvault secret, or at least if its seeing a keyvault reference it should not try to see if its in a connection string format.

We do make use of vnets, but as soon as I set the actual connection string, it deploys perfect with no mention of the vnet issue

**Comment by phil000** [comment] 2022-11-30 03:17
These phoney warnings\errors do not affect our deployments. The deployment succeeds with "2 warnings".

**Comment by AltusBaard** [comment] 2022-11-30 03:20
Yes, ours deploys fine as well, but seeing those warning/errors is not a very nice experience when viewing some of our larger pipelines, especially if there are actual errors that you need to concern yourself with

**Comment by AltusBaard** [comment] 2022-11-30 03:47
Had a look into the source now and I think I can see where the issue is coming from.
In AzureAppServiceUtility there is a method isAzureWebJobsStorageAccessible which has a call to AzureAppService method getConnectionStringValidation in there it calls of a service client with a connectionstringvalidation url.
Now I assume in that call it fails validation, returns a MalformedConnectionString status and then bubbles up that error.
So I am not sure if this issue would be solved in this repo or at the endpoint that is being called

**Comment by FinVamp1** [comment] 2022-11-30 16:53
Hello, we will look into this and will work on resolving this. @AltusBaard thanks for looking into this a bit further and this could be related to the Validation methods.

**Comment by patelchandni** [comment] 2022-12-28 20:00
This issue is addressed in PR: https://github.com/microsoft/azure-pipelines-tasks/pull/17544 and it will be out in next release. Thank you for reporting.

**Comment by FinVamp1** [comment] 2023-01-25 18:21
This should be resolved in the 216 task version for both v1 and v2. Closing this and please re-open if this issue re-occurs.

**Closed** 2023-03-17 17:26 UTC
Labels: Area: Release, Task: AzureFunction
