### ISSUE TITLE
Argument textbox from the .NET Core 2.* (Preview) Restore is missing

### ISSUE THREAD

**Issue by cilerler** [Microsoft/azure-pipelines-tasks#5462] opened 2017-09-26 00:15 UTC
It looks like you removed **Argument** textbox from the **.NET Core 2.* (Preview) Restore** but it is needed to pass `version`, `configuration` etc.

![image](https://user-images.githubusercontent.com/385958/30836429-3083176e-a22c-11e7-8b4a-2f6b49a72ddd.png)

**Comment by satbai** [comment] 2017-09-27 23:01
Thank you for the feedback. The Arguments textbox was removed to avoid conflicts with the parameters that the version 2 task provides. Could you help us understand why those arguments are necessary in the restore step in your scenario? Thanks.

**Comment by cilerler** [comment] 2017-09-28 00:35
I simply add code below into project files and unless I pass `/p:Configuration=$(BuildConfiguration) /p:BuildNumber=$(Build.BuildNumber)` through **Arguments** it restores dependent projects in DEBUG configuration regardless of the build configuration setting.

```xml
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

   <PropertyGroup>
    <BuildNumber Condition=" '$(BuildNumber)' == '' ">0.0.0</BuildNumber>
    <VersionPrefix>$(BuildNumber)</VersionPrefix>
    <VersionSuffix Condition=" '$(Configuration)' == 'Debug' ">dev</VersionSuffix>
    <Company>SmartProcure</Company>
    <Authors>Cengiz Ilerler</Authors>
    <Product>SmartProcure.Services.Usps</Product>
    <RepositoryUrl>https://github.com/smartprocure/darkseid</RepositoryUrl>
  </PropertyGroup>
```

**Comment by satbai** [comment] 2017-09-29 21:55
Thanks @cilerler. To make your scenario work, please use the Custom command in the NuGet task. That way you can provide all of the parameters you need. The Arguments option was removed to avoid conflicts between the parameters the task provides and any custom parameters the user may provide. Please let us know if you still experience issues after switching to the Custom command.

**Comment by cilerler** [comment] 2017-09-29 22:08
So you are suggesting to me to add additional **Nuget** task and use that one instead of `.NetCore Restore`, please confirm.

**Comment by satbai** [comment] 2017-09-29 22:53
Thanks for replying. I meant the custom command in the .NET task, not NuGet task. Sorry for the confusion.

**Comment by cilerler** [comment] 2017-09-30 02:55
So you are suggesting to add **.NetCore Custom** task and add the command `restore` with the arguments of `/p:Configuration=$(BuildConfiguration) /p:BuildNumber=$(Build.BuildNumber)`.  If that is correct, it will not solve the issue I'm pointing because it needs to be able access the private feed.  

If I'm missing something here, would you please send me a screenshot that demonstrates what I'm missing.  

Thanks in advance.

![image](https://user-images.githubusercontent.com/385958/31041783-0366d42e-a569-11e7-8685-3f1e5792bcea.png)

**Comment by satbai** [comment] 2017-10-02 21:27
Hi @cilerler, I can see the problem with accessing the private feed with the .NET Core custom task. Unfortunately, the .NET Core task doesn't support your scenario today, but we are planning on adding a feature to the .NET Core custom task that allows to add feed credentials. Thank you for reporting the issue! I'm leaving this issue open until the issue is fixed.

Since NuGet restore is slightly different from .NET restore, I cannot guarantee that this will work, but if you're using Windows, as a workaround I would suggest trying the NuGet custom task. The NuGet custom task allows arguments, and the feeds from the same account/collection will be automatically authenticated.

**Comment by cilerler** [comment] 2017-10-02 22:25
I wouldn't use _**.Net Core** Custom Task_ if you didn't remove it from the _**.Net Core** Restore Task_

You are taking away a feature that already exist without providing a replacement.

I would understand if you would taking away all the `Arguments` from _**.NET Core** tasks_ but just from _Restore_ doesn't seem correct.

**Comment by keithrob** [comment] 2017-10-02 23:08
@cilerler,
Is it correct to assume that you have recently changed your build task to use an authenticated feed?  I am asking because earlier versions of the restore task (i.e. neither 0.* nor 1.*) did not support authenticated feeds.
Keith

**Comment by cilerler** [comment] 2017-10-04 12:02
@keithrob sorry about delayed response.  

No, I was always using it through _**Nuget** task_ for feed.  Just a reminder issue here is `Arguments` textbox, 

If you link 2 projects together and restore them through _**.Net Core** Restore Task_, you will see that linked library will be called in `Debug` configuration even you are actually calling the entry library in `Release` configuration.

**Comment by azooinmyluggage** [comment] 2019-01-21 04:11
Closing this issue. The 2.0 version of the task is live now. Let us know if you are facing any issues with it.

**Closed by azooinmyluggage** 2019-01-21 04:11 UTC
Labels: Area: Packaging, Area: Release, feature request

**Comment by cilerler** [comment] 2019-01-21 12:01
@azooinmyluggage please re-open it, the issue is still there since no one done anything about it
