### ISSUE TITLE
Command Options Escaped

### ISSUE THREAD

**Issue by Phrayzur** [microsoft/azure-pipelines-tasks#12651] opened 2020-04-07 21:36 UTC
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: GradleV2

## Environment
Azure Pipelines
Agent - Hosted

## Issue Description

I have a task description:

```
- task: Gradle@2
            displayName: 'Publish jar to artifacts feed'
            inputs:
              gradleWrapperFile: 'modules/IntegrationShared/ServerIntegration/gradlew.bat'
              workingDirectory: 'modules/IntegrationShared/ServerIntegration'
              options: -PazurePAT=$(azurePAT)
              tasks: 'publish'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              sonarQubeRunAnalysis: false
```

I would expect the command ran from this to be:

`gradlew.bat -PazurePAT=abcdef publish`

however, instead I get:

`C:\windows\system32\cmd.exe /D /S /C "d:\a\1\s\modules\IntegrationShared\ServerIntegration\gradlew.bat "-PazurePAT=" options: "'-PazurePAT=abcdef'" publish"`

Notice the escaping quotation marks as well as the rogue `options`. Because of this I then get:

`Project 'options' not found in root project 'ServerIntegration'.`

**Comment by alexander-prozorov** [comment] 2020-09-11 11:00
Hello @Phrayzur,
Is this issue still relevant? 
Currently, run shows arguments without unnecessary "options=".

**Comment by alexander-prozorov** [comment] 2020-09-21 07:24
Hello @Phrayzur, is it still actual for you?

**Comment by alexander-prozorov** [comment] 2020-09-24 07:00
Closing the ticket. Feel free to reopen this ticket if the problem is still reproducible.

**Closed by alexander-prozorov** 2020-09-24 07:00 UTC
Labels: Area: ABTT, Task: Gradle, bug
