### ISSUE TITLE
Gradle@2 publishJUnitResults fails with Failed find: ENOENT: no such file or directory, stat '/home/vsts/work/1/s/xxxx'

### ISSUE THREAD

**Issue by henryju** [microsoft/azure-pipelines-tasks#14816] opened 2021-05-07 09:26 UTC
## Required Information

*Type*: Bug

**Enter Task Name**: Gradle  

## Environment

- [Azure Pipelines](https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=31710&view=logs&j=a26a64ae-104b-5839-d5b0-a28bc5f0b563&t=2a693003-2f18-558f-f96a-63f5ece7a93f&l=4985)
- Agent - Hosted

## Issue Description

The Gradle build ends successfully, but then an error occurred, and I guess this is during the lookup of JUnit test reports.

### Task logs

```
> Task :its:check
Skipping task ':its:check' as it has no actions.
:its:check (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 11m 1s
18 actionable tasks: 16 executed, 2 up-to-date
##[error]Error: Failed find: ENOENT: no such file or directory, stat '/home/vsts/work/1/s/its/build/idea-sandbox/system/port'

```

Might be similar to https://github.com/microsoft/azure-pipelines-tasks/issues/11018, except that the file `its/build/idea-sandbox/system/port` is not a symlink, but a regular file that is created/deleted during the build.

This error is not consistently reproducible.

**Comment by anatolybolshakov** [comment] 2021-05-12 13:20
Hi @henryju could you please share your yaml file and logs in debug mode?

**Comment by henryju** [comment] 2021-05-17 07:55
Hi @anatolybolshakov 

The project is public: https://github.com/SonarSource/sonarlint-intellij/blob/master/azure-pipelines.yml

The problem only appeared once so far, so I can't easily produce debug logs, sorry (I don't want to run all builds with debug logs enabled).

**Comment by anatolybolshakov** [comment] 2021-05-17 08:55
@henryju ENOENT is a general error which could happen for different reasons - please share pipeline logs once you reproduce it again - so we could investigate it.

**Comment by damien-urruty-sonarsource** [comment] 2021-06-02 14:13
Hello,

We were able to reproduce the problem a couple times since we raised this issue but I was not able to get logs.

My 2 cents: just at the end of our Gradle `test` task,  we asynchronously trigger the shutdown of our test environment (an IntelliJ instance) which in turn results in `its/build/idea-sandbox/system/port` file to be deleted. In some cases, the deletion happens while the publishJUnitResults is running. Is there any reason why the pipeline task needs to access this file ?

**Comment by anatolybolshakov** [comment] 2021-06-03 16:12
@damien-urruty-sonarsource thanks for additional info here!
Gradle tasks uses task-lib findMatch method - this method scans files in build directory and applies some filtering. If there is some file removed between scanning and filtering phases - it will fail. 
So currently it's not prefferable to any files in build directory be changed during tests publishing - but let us take a look how we could improve it to be more resilient (specifically in [line](https://github.com/microsoft/azure-pipelines-task-lib/blob/21dac986b4c7478eb2ed8ffbd60e4fad62904438/node/task.ts#L900))

**Comment by DenisRumyantsev** [comment] 2021-07-13 07:55
[Related Pull Request](https://github.com/microsoft/azure-pipelines-task-lib/pull/774)

**Comment by DenisRumyantsev** [comment] 2021-07-29 14:07
The changes that fix this issue were provided, and they are currently awaiting deployment.

**Comment by DenisRumyantsev** [comment] 2021-08-24 14:44
@henryju @damien-urruty-sonarsource let me close this issue since the provided fix was deployed.

**Closed by DenisRumyantsev** 2021-08-24 14:44 UTC
Labels: bug, Area: ABTT, awaiting deployment, Task: Gradle

**Comment by henryju** [comment] 2021-08-31 07:12
Thanks @DenisRumyantsev we will come back if the problem appear again :)
