### ISSUE TITLE
AzureResourceFilterUtility should filter on /sites (lowercase s)

### ISSUE THREAD

**Issue by franck-schmidlin** [microsoft/azure-pipelines-tasks#13695] opened 2020-10-12 14:04 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: 
AzureFunctionApp

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines : https://dev.azure.com/BizSysAndOps/Swan%20Comms%20Automation

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Task fails to identify existing resource.
logs read as follow:

```
2020-10-12T12:26:05.7253258Z ##[debug][GET]https://management.azure.com/subscriptions/0e0f0076-599e-4622-bdea-20ab7f46dbab/resources?$filter=resourceType EQ 'Microsoft.Web%2FSites' AND name EQ 'func-gbgplc-bso-dolphin-dolphincommstest02'&api-version=2016-07-01
2020-10-12T12:26:05.8351905Z ##[debug]Correlation ID from ARM api call response : 9373ea83-b7e1-4c98-91ad-c01aa738af3f
2020-10-12T12:26:05.8353876Z ##[debug]Deployment Failed with Error: Error: Resource 'func-gbgplc-bso-dolphin-dolphincommstest02' doesn't exist. Resource should exist before deployment.
2020-10-12T12:26:05.8356744Z ##[debug]task result: Failed
2020-10-12T12:26:05.8408021Z ##[error]Error: Resource 'func-gbgplc-bso-dolphin-dolphincommstest02' doesn't exist. Resource should exist before deployment.
2020-10-12T12:26:05.8427385Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Resource 'func-gbgplc-bso-dolphin-dolphincommstest02' doesn't exist. Resource should exist before deployment.
```

Testing the same call to the REST API:
```
GET https://management.azure.com/subscriptions/0e0f0076-599e-4622-bdea-20ab7f46dbab/resources?$filter=resourceType EQ 'Microsoft.Web%2FSites' AND name EQ 'func-gbgplc-bso-dolphin-dolphincommstest02'&api-version=2016-07-01
```
returns an empty list.
[Response-withUpperS.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5365566/Response-withUpperS.txt)

Same call but filtering on `resourceType EQ 'Microsoft.Web%2Fsites'` with a lowercase `sites`, fixes the issue.
```
GET https://management.azure.com/subscriptions/0e0f0076-599e-4622-bdea-20ab7f46dbab/resources?$filter=resourceType EQ 'Microsoft.Web%2Fsites' AND name EQ 'func-gbgplc-bso-dolphin-dolphincommstest02'&api-version=2016-07-01
```
[Response-with_lowerS.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5365555/Response-with_lowerS.txt)

This error appears in a few places in the code base that call `AzureResourceFilterUtils.getResourceGroupName()`, I suspect it affects several tasks.
The unit test themselves seem to use the correct lowercase `sites` value.

### Task logs

[task_log.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5365541/task_log.txt)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by AmrutaKawade** [comment] 2020-11-04 08:17
I am not able to repro this issue. for me its working with capital S as well. Are you still facing this issue?

**Comment by AmrutaKawade** [comment] 2020-11-05 05:44
`AzureResourceFilterUtils.getResourceGroupName()` this function is being used in many tasks and we haven't received  any issue for this. Even I am not able to reproduce this. I am closing this issue. Feel free to reopen if issue still persists.

**Closed by AmrutaKawade** 2020-11-05 05:44 UTC
Labels: Area: Release, Task: AzureFunction, bug, environment:bug

**Comment by franck-schmidlin** [comment] 2020-11-05 10:39
Apologies for the delay in coming back - I have rerun my test calls direct to the REST API and cannot reproduce this either.
Might have been a transient error - just my luck.
Thanks for looking into it
