### ISSUE TITLE
Deployment to slot bug

### ISSUE THREAD

**Issue by Karamorf** [Microsoft/azure-pipelines-tasks#8264] opened 2018-09-06 20:59 UTC
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
VSTS, general task usage

N/A

## Issue Description
If you are deploying containers to an Application Service as a WebApp, using deployment slots and using Azure Container Registry (ACR) then using the "--configuration-source" flag is required when creating a deployment slot.

During the creation of a deployment slot, you must specify it to use ACR or it will default to us Docker Hub. This is then confusing when you are configuring a release task to use a deployment because you can't select ACR in that UI. I feel like this setting should default to using the settings from the production slot unless otherwise specified. Otherwise in the UI for the deploy task, I should be able to select the image source in addition to the image name and whatnot.

This is just a bad user experience, not necessarily a bug.

### Error logs

[Insert error from the logs here]

**Comment by vincentdass** [comment] 2018-10-09 06:48
@Karamorf , thanks for sharing the feedback.
ACR support for App Service Deploy task is not yet added into task.
Wil mark this thread as enhancement for the same.

**Comment by vincentdass** [comment] 2019-01-08 03:35
duplicate of #7654

**Closed by vincentdass** 2019-01-08 03:35 UTC
Labels: Area: AzureAppService, Area: Release, enhancement
