### ISSUE TITLE
"Failed to find api location for area: nuget id"

### ISSUE THREAD

**Issue by WeihanLi** [microsoft/azure-pipelines-tasks#10893] opened 2019-07-15 03:00 UTC
## Required Information

**Question**  

**Enter Task Name**: `dotnet nuget push`/ `dotnet restore`

## Environment

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version:  Centos with agent version 1.148.1

## Agent Version and Platform

Version of your agent? 2.148.1

## Azure DevOps Type and Version

https://mvn11.visualstudio.com

## What's not working?

get error when try to restore packages or push packages, error as as follows:

```
Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3
```

dotnet restore error:

```
##[section]Starting: dotnet restore
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.153.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
==============================================================================
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
##[error]Error: Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3
##[error]Packages failed to restore
##[section]Finishing: dotnet restore

```

dotnet push error:

```
##[section]Starting: dotnet push
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.153.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
==============================================================================
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
##[warning]Can\'t find loc string for key: Warning_SessionCreationFailed
##[warning]Warning_SessionCreationFailed {}
##[error]Error: Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3
##[error]Packages failed to publish
##[section]Finishing: dotnet push
```

**Comment by WeihanLi** [comment] 2019-07-15 03:04
copied from https://github.com/microsoft/azure-pipelines-agent/issues/2345

**Comment by bryanmacfarlane** [comment] 2019-07-15 03:09
@johnterickson - can you route?

**Comment by jmyersmsft** [comment] 2019-07-15 21:59
We have seen this issue before and are actively working on a solution

**Comment by shubham90** [comment] 2019-07-15 23:24
@WeihanLi Is this happening all the time or is it a transient failure?

**Comment by WeihanLi** [comment] 2019-07-16 01:53
@shubham90 it happened sometimes, sometimes I had to retry more than ten times, sometimes it works normal.

![image](https://user-images.githubusercontent.com/7604648/61260049-5d6c3a00-a7af-11e9-8961-1c40fea59e31.png)

**Comment by shubham90** [comment] 2019-07-16 23:03
Thanks for the clarification @WeihanLi . We are still looking into this. Can you please send me a detailed log of the failure by setting "System.debug" variable to "true"? You can send it to me at "shbhawsi at microsoft dot com".

**Comment by WeihanLi** [comment] 2019-07-17 07:48
[log_13_3343.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3400692/log_13_3343.zip)

**Comment by slandsaw** [comment] 2019-07-17 14:49
Just started encountering this issue as well.

**Comment by shubham90** [comment] 2019-07-18 01:13
Thanks for the logs @WeihanLi . We are working on adding a fix for this now.

**Comment by osariel** [comment] 2019-07-26 13:02
any update on this?

`##[error]Error: Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3
##[debug]Processed: ##vso[task.issue type=error;]Error: Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3`

**Comment by shubham90** [comment] 2019-07-26 21:03
@osariel We have made a code fix which should alleviate this issue and/or provide some additional logging if it happens again. The fix itself should be deployed to all the accounts by next week.

**Comment by shubham90** [comment] 2019-08-08 20:54
The fix is now deployed across all accounts. This issue should be resolved now. If it's still happening, feel free to re-open the issue with updated debug logs.

**Closed by shubham90** 2019-08-08 20:54 UTC
Labels: Area: Artifacts, Area: ArtifactsPackages, bug

**Comment by kovaliovsg** [comment] 2019-08-15 16:58
Hello. We still experience this issue in our account. 
See the attached log. It happens randomly and we cannot reproduce or get rid of this error.
[1_Build Job.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3506448/1_Build.Job.txt)

Thank you !

**Comment by WeihanLi** [comment] 2019-08-16 04:51
new issue found sometimes, not sure if the same problem

![image](https://user-images.githubusercontent.com/7604648/63144210-71ac8c80-c024-11e9-9a28-9f34130e9870.png)

**Comment by shubham90** [comment] 2019-08-16 18:44
@WeihanLi I think this is a different problem and related to network issue on the agent.

**Comment by shubham90** [comment] 2019-08-16 18:47
> Hello. We still experience this issue in our account.
> See the attached log. It happens randomly and we cannot reproduce or get rid of this error.
> 1_Build Job.txt
> Thank you !

@kovaliovsg This looks like a different issue but with similar error message. Can you please open a separate issue for this?

**Comment by dhilgarth** [comment] 2020-05-04 06:56
I am seeing this today:
![image](https://user-images.githubusercontent.com/1180105/80942480-29691080-8de5-11ea-9193-c9b2504369d3.png)

**Comment by vhhughes** [comment] 2020-05-04 15:03
We've never seen this error before, and we're just now seeing it intermittently begin happening for a number of our builds. It's intermittent. All our builds run on private agents hosted on-prem. There should be no proxy involved for HTTP calls to Azure DevOps from our servers.

**Comment by dhilgarth** [comment] 2020-05-04 15:07
Same here: never saw it before, running on-prem agents

**Comment by zimmale** [comment] 2020-05-12 14:25
@dhilgarth @vhhughes  I notice the same thing, it started a couple of days ago.
As well we are using on-premise agents (behind corporate proxy) and Azure DevOps Services (cloud)
Any suggestions? Report Microsoft?
This is super annoying, to retry 3-5 times... :-(

**Comment by zimmale** [comment] 2020-05-12 17:34
FYI I've reported the issue here: https://developercommunity.visualstudio.com/content/problem/1027334/pipeline-nuget-push-error-failed-to-find-api-locat.html

**Comment by temelj** [comment] 2020-06-29 05:31
This is still happening for me.
```
##[warning]Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3
##[debug]Processed: ##vso[task.issue type=warning;]Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3
##[debug]Error: Failed to find api location for area: nuget id: 9D3A4E8E-2F8F-4AE1-ABC2-B461A51CB3B3
    at beginGetLocation.then (D:\PRVAGENT_v1\_work\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.171.3\node_modules\azure-devops-node-api\VsoClient.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:109:7)

```
