### ISSUE TITLE
[UseDotNetV2] Cache is not used. Failure on unpacking verison 2.2.300 

### ISSUE THREAD

**Issue by borysl** [microsoft/azure-pipelines-tasks#11887] opened 2019-12-04 09:46 UTC
**Type**: **Bug**  
**Task Name**: UseDotNetV2

## Steps to reproduce
Create .Net Core build with UseDotNet task in azure-pipeline.xml
```
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.300'
    installationPath: $(Agent.ToolsDirectory)/dotnet
```

## Environment
- Server - Azure Pipelines
- account name: uniperteamservices
- team project name: ADAM
- build definition: 564
- build number: 22738
- Agent - Hosted: 
- Agent queue name: Azure Pipelines 2

## Issue Description

Suddenly I've got error below. It took place in the past [here](https://github.com/microsoft/azure-pipelines-tasks/issues/9064) and I have never seen it before. After investigation I found that actually cache is never used regardless of the installationPath: $(Agent.ToolsDirectory)/dotnet
which could have avoid this issue - instead of downloading package it would have just reused from cache.
After further research I was surprised to find [this change](https://github.com/dotnet/core/commit/67687594b0f967a5a65183b40ae80f853ed743a7). For some reason latest-sdk's where changed from: "latest-sdk": "2.2.402"
to: "latest-sdk": "2.2.207",
and from
            "latest-sdk": "2.1.802",
to
            "latest-sdk": "2.1.607",

Downgrading to version 2.2.207 actually solved build failure, but not fact that cache is still unused. Pls advise!

### Error logs

```
Starting: UseDotNet
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.0.24
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 2.2.300.
Found version 2.2.300 in channel 2.2 for user specified version spec: 2.2.300
Version 2.2.300 was not found in cache.
Getting URL to download .NET Core sdk version: 2.2.300.
Detecting OS platform to find correct download package for the OS.
C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'd:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.0.24\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Downloading: https://download.visualstudio.microsoft.com/download/pr/4d8d4bfe-00d8-4347-9786-7027117694bb/86385dc7a0d79d5d14c45bee3038a1c4/dotnet-sdk-2.2.300-win-x64.zip
Extracting downloaded package d:\a\_temp\5127ce1f-8d8e-47cd-afe1-bd029d8f9a0d.
Extracting archive
C:\windows\system32\chcp.com 65001
Active code page: 65001
C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('d:\a\_temp\5127ce1f-8d8e-47cd-afe1-bd029d8f9a0d', 'd:\a\_temp\80ae')"
Exception calling "ExtractToDirectory" with "2" argument(s): "End of Central Directory record could not be found."
At line:1 char:111
+ ... catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('d:\a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidDataException
 
##[error]Failed while installing version: 2.2.300 at path: C:/hostedtoolcache/windows/dotnet with error: Failed while extracting downloaded package with error: Error: The process 'C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
Finishing: UseDotNet
```

**Comment by borysl** [comment] 2019-12-04 09:48
I will also write to MS DevOps support, perhaps cache doesn't work because of the local settings

**Comment by issacnitin** [comment] 2019-12-12 10:17
@borysl As updated by Ming in the Developer Community, version 2.2.300 seems working now. Hosted agent gets recycled after each pipeline job, that must be the reason why the cache is not being hit. Cache can work, if for example, you have two UseDotNetCoreV2 tasks in the same pipeline with same version, or if you're using a private agent.

Hope this clarifies your issue. If you need more help/clarifications please feel free to post here.

**Comment by bishal-pdMSFT** [comment] 2019-12-24 14:19
Closing this issue - as mentioned by @issacnitin this is by design

**Closed** 2019-12-24 14:19 UTC
Labels: Area: Release
