### ISSUE TITLE
Using pipeline variables in Azure CLI task

### ISSUE THREAD

**Issue by erikcartman** [Microsoft/azure-pipelines-tasks#9416] opened 2019-01-25 08:25 UTC
Hello, in Azure Devops pipeline  i am using Azure CLI task with inline script  on Hosted Ubuntu 1604 agent, is there any way to pass pipeline variables to scipt? as example i want to use this command with variable az resource list -g MYVARIABLE --query "[].name" -o tsv? if so could you provide example. Thanks.

**Comment by FireDrunk** [comment] 2019-01-28 08:23
```az storage account keys list --account-name $(accountName)```
Works fine?

**Comment by dikhakha** [comment] 2019-01-29 07:20
You can use pipeline variables in the script by passing them as arguments. Example:
Arguments input : $(MYVARIABLE)
Inline script: az resource list -g $1 --query "[].name" -o tsv

where MYVARIABLE is your pipeline variable. Please let me know if this helps.

**Comment by dikhakha** [comment] 2019-02-01 04:54
@erikcartman Did you get a chance to try out the above suggestion ?

**Comment by erikcartman** [comment] 2019-02-02 22:05
nope, i changed my aproach, but thanks anyway

**Comment by tomasaschan** [comment] 2019-02-05 17:00
@dikhakha FWIW, I had a working inline script that made use of pipeline variables that worked fine. When I moved the script, unchanged, to a file in the source repository, exposed it as a build artifact and reconfigured the Azure CLI task to use a script path instead, it didn't do variable substitution anymore.

The script uses some 20-ish variables (most of them to set app settings) so I would _really_ like to avoid having to specify them all as script arguments.

**Comment by dikhakha** [comment] 2019-02-06 11:31
@tomasaschan you should be able to access the pipeline variables in the script as well. All pipeline variables are made available to the script as environment variables, except secret variables. I am wondering if you changed the Job Agent by any chance ? This is because variable names are converted to UPPER CASE and stored so if you are using Ubuntu agent, you might not be getting the values due to case sensitivity. Can you please tell me which job agent are you using ?

**Comment by tomasaschan** [comment] 2019-02-06 12:25
@dikhakha It's running on Ubuntu 16.04. The variables have names like `$(WebApp.Name)` - what would that translate to as an environment variable name?

Also, a majority of the variables are imported from Azure KeyVault. They are not marked as secret in the pipeline variables configuration, but they do get masked when included in log outputs. Are they made available as well?

**Comment by dikhakha** [comment] 2019-02-06 12:59
WebApp.Name will be available as WEBAPP_NAME (' ' and '.' is converted to '_'). You can refer to this [doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&viewFallbackFrom=vsts&tabs=batch) about custom variables. 

I did not completely understand the second scenario. If a variable is not marked as secret, it will be available. however, it could be getting masked in the logs because those variables might contain values which are considered as secret like your Azure service connection details.

**Comment by tomasaschan** [comment] 2019-02-06 13:58
The second scenario is basically this:

I have a variable group that is linked to an Azure KeyVault, and the secrets from there are imported as variables.

I then have pipeline variables that refer to the variables from the variable group, in order to map the secret names in Key Vault to something that makes sense for the pipeline, and to handle scopes.

So, for example, say the Key Vault has two secrets; `foo-bar-test` and `foo-bar-prod`. They are made available under the same names in the variable group. In the pipeline, I have a pipeline variable `Foo.Bar` with the value `$(foo-bar-test)` scoped to `Test`, and `Foo.Bar` with the value `$(foo-bar-prod)` scoped to `Prod`. In the pipeline variable configuration, `Foo.Bar` is not marked secret.

So, given the following statement:

> All pipeline variables are made available to the script as environment variables, except secret variables.

the question was whether I will have a `FOO_BAR` environment variable available in the script, or if being imported from Key Vault counts as being a "secret variable".

**Comment by dikhakha** [comment] 2019-02-06 16:17
You can refer to [this doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&viewFallbackFrom=vsts&tabs=yaml) for using variables imported from KeyVault. Secret variables and variables from key vault are considered as secrets therefore they will not be available in the scripts.

**Comment by dikhakha** [comment] 2019-02-12 10:30
Closing this issue. Please feel free to reopen if you need more help.

**Comment by mydiemho** [comment] 2019-03-08 01:13
@dikhaka I am having the same issues.  I cannot access pipeline variable from my script, I have tried everything you mentioned in this issue.   

I have had no issues when doing this in a bash task

**Comment by mydiemho** [comment] 2019-03-08 03:28
> You can use pipeline variables in the script by passing them as arguments. Example:
> Arguments input : $(MYVARIABLE)
> Inline script: az resource list -g $1 --query "[].name" -o tsv
> 
> where MYVARIABLE is your pipeline variable. Please let me know if this helps.

I probably misunderstood you but your instruction didn't work when I try to add the variable in the `Arguments` sections.  It did work when I reference it directly when calling the script

<img width="844" alt="clitaskvariable" src="https://user-images.githubusercontent.com/1634185/54005657-23a76a80-410f-11e9-9411-01aeb63c202a.png">

**Comment by bishal-pdMSFT** [comment] 2019-03-08 07:10
@mydiemho in the task UI, you should use the same name as pipeline variable name(without changing case and '.' etc). 
Only when accessing the variables as environment variable inside a script you should transform the name.

**Comment by uniquelau** [comment] 2019-03-09 13:58
I'd like to add that I'd also experienced some issues with variables in inline scripts.
I am seeing unreliable behaviour in one pipeline out of many that I have logged here:
https://github.com/Azure/azure-cli/issues/8722#event-2188784135

**Comment by mydiemho** [comment] 2019-03-11 17:53
> @mydiemho in the task UI, you should use the same name as pipeline variable name(without changing case and '.' etc).
> Only when accessing the variables as environment variable inside a script you should transform the name.

I am using the same case.  My variable name is all capitalize

**Comment by issacnitin** [comment] 2019-03-12 10:44
@mydiemho @uniquelau  It seems to be a problem when Azure CLI task is used in Release pipeline. Things should work out just fine when used in Build Pipeline though. Rest assured we'll update as soon as the issue is fixed! Thanks

**Comment by issacnitin** [comment] 2019-03-12 15:54
@mydiemho I stumbled upon something similar, it happened because of trying to reference argument by $1 while running the task in a windows machine. Could you confirm if it's the same case with you? 
In windows it should work when you use %1 to reference the argument supplied to Inline script.

**Comment by mydiemho** [comment] 2019-03-12 17:15
> @mydiemho I stumbled upon something similar, it happened because of trying to reference argument by $1 while running the task in a windows machine. Could you confirm if it's the same case with you?
> In windows it should work when you use %1 to reference the argument supplied to Inline script.

I am running this on a Linux agent.

**Comment by issacnitin** [comment] 2019-03-13 12:39
@mydiemho Could you share the logs with system.debug variable set to true? You can share them here or at RM_Customer_Queries@microsoft.com

**Comment by mydiemho** [comment] 2019-03-14 04:35
@issacnitin here you go
https://dev.azure.com/msft-vott/VoTT/_build/results?buildId=1637

**Comment by issacnitin** [comment] 2019-03-14 06:36
@mydiemho Looks like the account value is getting printed correctly when $1 is used. The issue is with azcopy asking for user input when script is ran. You could use --quiet argument along with azcopy to suppress user inputs. Let us know in case of more queries!

**Comment by mydiemho** [comment] 2019-03-18 17:06
@issacnitin I don't think we're talking about the same thing.  I know $1 works (but only when I pass the variable to the script). $1 doesn't work when I set it in the `Arguments` sections

**Comment by issacnitin** [comment] 2019-03-21 06:36
@mydiemho 

From my understanding, you're referring to $1 in your script. 
If that's the case then you need to explicitly pass an argument to your script if "Inline" mode is used. You can do that by: 
1. Directly passing $(AZURE_STORAGE_ACCOUNT) in Inline script, 
OR 
2. Passing $(AZURE_STORAGE_ACCOUNT) in the Arguments section and then passing reference further on to your script using $1 

So your script would look like:
```
./scripts/push-report.sh $1 $2
Arguments: $(AZURE_STORAGE_ACCOUNT) $(AZURE_STORAGE_KEY)
```

Alternately, you can use **"Script Path" mode** and avoid passing argument explicitly.

Please refer to the images below, these are the working versions of the task:

**Passing directly in Inline script**
![2](https://user-images.githubusercontent.com/4218887/54736267-5d2cab00-4bd0-11e9-9350-cf4935960a19.PNG)

**Passing through Arguments in Inline script**
![1](https://user-images.githubusercontent.com/4218887/54736264-5b62e780-4bd0-11e9-9f45-d539c10eb2f4.PNG)

**Using Script Path**
![3](https://user-images.githubusercontent.com/4218887/54736269-5ef66e80-4bd0-11e9-8230-c9fb90ae1fe8.PNG)

Let me know if this solves your problem. If you're having more trouble, could you post the release logs for the failure case (with system.debug mode set to True)? And if possible, do share a screenshot of your task as well.

Thanks!

**Comment by amaljg** [comment] 2019-04-04 10:10
@mydiemho - I assume your issue is resolved using @issacnitin's suggestions above. If you still face the issue, feel free to reopen the issue or open a new one.

**Closed by amaljg** 2019-04-04 10:10 UTC
Labels: Area: Release

**Comment by sagarkul** [comment] 2019-07-15 06:12
Using Script Path does not work, any suggestion?

**Comment by sachinma** [comment] 2019-07-15 07:26
@sagarkul can you provide additional details on the error that you got and how were you accessing variables in the script? Consider opening a new issue if you are not able to resolve with the comments from this thread.

**Comment by sagarkul** [comment] 2019-07-16 16:50
> @sagarkul can you provide additional details on the error that you got and how were you accessing variables in the script? Consider opening a new issue if you are not able to resolve with the comments from this thread.

Below is code snippit from deploy.sh

```
#!/bin/bash

resourceGroupName=$(customerName)-$(platformName)-RG-$(envName)

echo $resourceGroupName
```

and below is my task screenshot

![image](https://user-images.githubusercontent.com/9719341/61313202-9fc96180-a817-11e9-8b46-a383bb0904f4.png)

**Comment by sagarkul** [comment] 2019-07-16 16:59
> > @sagarkul can you provide additional details on the error that you got and how were you accessing variables in the script? Consider opening a new issue if you are not able to resolve with the comments from this thread.
> 
> Below is code snippit from deploy.sh
> 
> ```
> #!/bin/bash
> 
> resourceGroupName=$(customerName)-$(platformName)-RG-$(envName)
> 
> echo $resourceGroupName
> ```
> 
> and below is my task screenshot
> 
> ![image](https://user-images.githubusercontent.com/9719341/61313202-9fc96180-a817-11e9-8b46-a383bb0904f4.png)

Do I need to use $1 $2 ... to get values?
I don't want that, as arguments can grow to 15-18

**Comment by sachinma** [comment] 2019-07-17 04:01
The arguments that you have in  "Arguments" parameter will be accessible to the shell script as normal shell variables like $1 $2 . You should access them like that.

**Comment by UmairSyed** [comment] 2019-10-01 06:47
Can we have an if condition in inline script to be able to run az network command only if the environment is dev etc?

**Comment by pvasek** [comment] 2021-07-02 09:19
I am adding this as a reference for possible usages of pipeline variables. There are the following options:
- argument
- variable
- built-in variable (or any variable with '.')

In this example below the goal was to pass `Build.BuildId` to the Azure CLI script:
```yaml
name: "build"
variables:
  - name: "VERSION"
    value: $(Build.BuildId)
stages:
  - stage: test
    pool:
      vmImage: 'ubuntu-20.04'
    jobs:
      - job:
        steps:
          - task: AzureCLI@2
            displayName: "variables test"
            inputs:
              azureSubscription: '...'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              arguments: $(VERSION)
              inlineScript: |
                echo "argument"
                echo $1         
                echo "variable" 
                echo $VERSION
                echo "build-in variable"
                echo $BUILD_BUILDID
```

**Comment by Hipster74** [comment] 2022-06-27 11:00
Ok, how am I supposed to pass a secret stored in my Azure DevOps library to my bicep deployment in an AzureCli@2 task?

With inlinescript of scriptType 'pscore' and variable group secret added to arguments I get: 

>  The term 'CONNSTRDEMO' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

My argument parameter looks like this:

` arguments: $(CONNSTRDEMO)`

And then referenced with $1 in my inlinescript.

There must be a way to achieve this, what am I doing wrong?

**Comment by pievalentin** [comment] 2023-08-09 14:56
I still run into this issue. Does someone have a work around this?
