### ISSUE TITLE
[BUG]: AzureRmWebAppDeployment@4 throws 401 after disabling the basicPublishingCredentialsPolicies/scm in App Services

### ISSUE THREAD

**Issue by OnsetM** [microsoft/azure-pipelines-tasks#18941] opened 2023-09-11 10:36 UTC
### Task name

AzureRmWebAppDeployment@4

### Task version

4

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows

### Task log

```shell
Scope: All App Services based deployments (Functions, App Services and its containerized equivalent)

After disabling the basicPublishingCredentialsPolicies/scm, task is unable to deploy the content due to the authentication error.

It would be great if it uses credentials from the service connection instead of downloading publish profile local account credentials.
```

### Relevant log output

```shell
##[error]Error: Error Code: ERROR_USER_UNAUTHORIZED

More Information: Connected to the remote computer ("sample.scm.azurewebsites.net") using the Web Management Service, but could not authorize. Make sure that you are using the correct user name and password, that the site you are connecting to exists, and that the credentials represent a user who has permissions to access the site. Learn more at: https://go.microsoft.com/fwlink/?LinkId=221672#ERROR_USER_UNAUTHORIZED
```

**Comment by v-mohithgc** [comment] 2023-09-12 08:44
duplicate of https://github.com/microsoft/azure-pipelines-tasks/issues/18942

**Closed by v-mohithgc** 2023-09-12 08:44 UTC
Labels: bug, Area: Release, triage
