### ISSUE TITLE
Copy Files Over SSH: Cannot parse privateKey: Unsupported key format

### ISSUE THREAD

**Issue by SuperDuperOne** [microsoft/azure-pipelines-tasks#12962] opened 2020-05-21 09:08 UTC
Hi, 
I'm experiencing the same issue with the Azure Copy SSH Task,
where do I actually use ssh-keygen -t rsa -m PEM when i'm simply trying to copy over files via SSH?
do I need an additional task for this?

![image](https://user-images.githubusercontent.com/23457220/82434553-e799c480-9a8a-11ea-87f7-ce24cd95b9a5.png)

**Comment by anatolybolshakov** [comment] 2020-06-29 18:47
Hi @SuperDuperOne, could you please tell what version of TFS do you use? I can't reproduce this issue with the last task version

**Comment by SuperDuperOne** [comment] 2020-06-30 07:43
Hi @anatolybolshakov 
thanks for getting back to me -- we're currently using the azure devops services (cloud) and unfortunately i'm not the org admin.
is there anything else you might need from me?
I dont believe our internal firewall is blocking port 21.

last time i ran the above i got the following error message below

2020-06-08T12:32:20.6075859Z connecting to: uatservername01:21
2020-06-08T12:32:21.4679819Z ##[error]Error: getaddrinfo ENOTFOUND uatservername01 uatservername01:21 (control socket)
2020-06-08T12:32:21.4691063Z ##[debug]Processed: ##vso[task.issue type=error;]Error: getaddrinfo ENOTFOUND uatpublicapache01 uatpublicapache01:21 (control socket)
2020-06-08T12:32:21.4691428Z ##[debug]task result: Failed
2020-06-08T12:32:21.4691669Z ##[error]Ftp Upload failed
2020-06-08T12:32:21.4691919Z ##[debug]Processed: ##vso[task.issue type=error;]Ftp Upload failed
2020-06-08T12:32:21.4707384Z ##[debug]Processed: ##vso[task.complete result=Failed;]Ftp Upload failed
2020-06-08T12:32:21.4727555Z ##[section]Finishing: FTP Upload: content/content 

I have added both my public and private key to azure devops to authenticate but, its not liking the task above sadly...

**Comment by anatolybolshakov** [comment] 2020-06-30 08:54
This error seems to indicate that hostname is unreachable for some reason... Could you please check if it is reachable for you, and port is not blocked by firewall?

**Comment by SuperDuperOne** [comment] 2020-06-30 11:28
let me check and will update here again shortly.
thanks!

**Comment by SuperDuperOne** [comment] 2020-06-30 15:08
i've been told that, we've been trying to connected to a server which is not within azure devops/portal, but looking SSH into the server. The SSH port is enabled however connecting to it via azure devops pipelines/task is not actually making the connections.

I have the service connection setup, the pub/priv keys setup 

![image](https://user-images.githubusercontent.com/23457220/86142948-b8e02680-baeb-11ea-97c3-0b63839aa227.png)

the uatpublicapache01 server is not within the azure,

so my questions, is it even possible to make that connection?

**Comment by anatolybolshakov** [comment] 2020-07-01 13:37
@SuperDuperOne yes it should be possible if this server is reachable outside, and there's no any firewall settings blocking it

**Comment by anatolybolshakov** [comment] 2020-07-01 15:05
@SuperDuperOne Could you try to establish connection by running Bash task and using ssh command like utility? Or maybe just have another way to check if is possible to establish SSH connection to remote server?

**Comment by SuperDuperOne** [comment] 2020-07-01 16:26
Hi, @anatolybolshakov, 
so from running a simple SSH task, it would seem that the on-prem server we're looking to connect to isnt accepting port 22 access:

![image](https://user-images.githubusercontent.com/23457220/86267786-25782580-bbbf-11ea-86cc-7919504b6e1e.png)

`2020-07-01T16:17:32.6984858Z ##[debug]Evaluating condition for step: 'Run shell commands on remote machine'
2020-07-01T16:17:32.6986582Z ##[debug]Evaluating: succeeded()
2020-07-01T16:17:32.6987134Z ##[debug]Evaluating succeeded:
2020-07-01T16:17:32.6988406Z ##[debug]=> True
2020-07-01T16:17:32.6988930Z ##[debug]Result: True
2020-07-01T16:17:32.6989508Z ##[section]Starting: Run shell commands on remote machine
2020-07-01T16:17:32.7004785Z ==============================================================================
2020-07-01T16:17:32.7005298Z Task         : SSH
2020-07-01T16:17:32.7006584Z Description  : Run shell commands or a script on a remote machine using SSH
2020-07-01T16:17:32.7007050Z Version      : 0.171.0
2020-07-01T16:17:32.7007647Z Author       : Microsoft Corporation
2020-07-01T16:17:32.7008480Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/ssh
2020-07-01T16:17:32.7009071Z ==============================================================================
2020-07-01T16:17:32.8194230Z ##[debug]agent.TempDirectory=/home/vsts/work/_temp
2020-07-01T16:17:32.8212513Z ##[debug]loading inputs and endpoints
2020-07-01T16:17:32.8214997Z ##[debug]loading INPUT_SSHENDPOINT
2020-07-01T16:17:32.8222937Z ##[debug]loading INPUT_RUNOPTIONS
2020-07-01T16:17:32.8225517Z ##[debug]loading INPUT_COMMANDS
2020-07-01T16:17:32.8226122Z ##[debug]loading INPUT_SCRIPTPATH
2020-07-01T16:17:32.8226847Z ##[debug]loading INPUT_INLINE
2020-07-01T16:17:32.8227396Z ##[debug]loading INPUT_FAILONSTDERR
2020-07-01T16:17:32.8227945Z ##[debug]loading INPUT_INTERACTIVESESSION
2020-07-01T16:17:32.8228490Z ##[debug]loading INPUT_READYTIMEOUT
2020-07-01T16:17:32.8229605Z ##[debug]loading ENDPOINT_AUTH_xxxxxxxxxxxxxxxxxxxxxx
2020-07-01T16:17:32.8230418Z ##[debug]loading ENDPOINT_AUTH_SCHEME_xxxxxxxxxxxxxxxxxxxxxx
2020-07-01T16:17:32.8231206Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_xxxxxxxxxxxxxxx_USERNAME
2020-07-01T16:17:32.8232007Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_xxxxxxxxxxxxxxxxxxx_PASSWORD
2020-07-01T16:17:32.8232674Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2020-07-01T16:17:32.8233246Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2020-07-01T16:17:32.8233873Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2020-07-01T16:17:32.8235612Z ##[debug]loaded 15
2020-07-01T16:17:32.8248376Z ##[debug]Agent.ProxyUrl=undefined
2020-07-01T16:17:32.8249283Z ##[debug]Agent.CAInfo=undefined
2020-07-01T16:17:32.8249838Z ##[debug]Agent.ClientCert=undefined
2020-07-01T16:17:32.8250368Z ##[debug]Agent.SkipCertValidation=undefined
2020-07-01T16:17:32.9637743Z ##[debug]check path : /home/vsts/work/_tasks/SSH_xxxxxxxxxxxxxxxxxx/0.171.0/task.json
2020-07-01T16:17:32.9639280Z ##[debug]adding resource file: /home/vsts/work/_tasks/SSH_xxxxxxxxxxxxxxxxxx/0.171.0/task.json
2020-07-01T16:17:32.9640133Z ##[debug]system.culture=en-US
2020-07-01T16:17:32.9652841Z ##[debug]sshEndpoint=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2020-07-01T16:17:32.9656725Z ##[debug]xxxxxxxxxxxxxxxxxxxxxxxxx auth param username = ***
2020-07-01T16:17:32.9657801Z ##[debugxxxxxxxxxxxxxxxxxxxxxxxxxx auth param password = ***
2020-07-01T16:17:32.9658609Z ##[debug]xxxxxxxxxxxxxxxxxxxxxxxxx data host = xx.xx.xxx.xx
2020-07-01T16:17:32.9659337Z ##[debug]xxxxxxxxxxxxxxxxxxxxxxxxx data port = 22
2020-07-01T16:17:32.9659923Z ##[debug]interactiveSession=false
2020-07-01T16:17:32.9660461Z ##[debug]readyTimeout=20000
2020-07-01T16:17:32.9660964Z ##[debug]Using private key for ssh connection.
2020-07-01T16:17:32.9671716Z ##[debug]runOptions=commands
2020-07-01T16:17:32.9672611Z ##[debug]commands=who
ls -Slah
netstat -tpln
2020-07-01T16:17:32.9673095Z ##[debug]failOnStdErr=true
2020-07-01T16:17:32.9711595Z Trying to establish an SSH connection to ***@xx.x.xxx.xx:22
2020-07-01T16:17:36.0546446Z ##[debug]task result: Failed
2020-07-01T16:17:36.0579216Z ##[error]Failed to connect to remote machine. Verify the SSH service connection details. Error: Error: connect EHOSTUNREACH xx.x.xxx.xx:22.
2020-07-01T16:17:36.0590252Z ##[debug]Processed: ##vso[task.issue type=error;]Failed to connect to remote machine. Verify the SSH service connection details. Error: Error: connect EHOSTUNREACH xx.x.xxx.xx:22.
2020-07-01T16:17:36.0598218Z ##[debug]Processed: ##vso[task.complete result=Failed;]Failed to connect to remote machine. Verify the SSH service connection details. Error: Error: connect EHOSTUNREACH xx.x.xxx.xx:22.
2020-07-01T16:17:36.0601282Z ##[section]Finishing: Run shell commands on remote machine`

i guess I will need to contact the network guys..

it there another type of test i can do to double confirm?

**Comment by anatolybolshakov** [comment] 2020-07-02 14:40
@SuperDuperOne yes, I almost sure that it's related with connection... It would be great also if you have ability to try to establish ssh connection from another computer. Probably it could also make sense to check if ssh service is running on remote host, if it is possible

**Comment by anatolybolshakov** [comment] 2020-07-13 09:17
Hi @SuperDuperOne, do you have any updates?

**Comment by anatolybolshakov** [comment] 2020-07-14 08:22
I'm closing it due to inactivity at the moment, please feel free to reopen it

**Comment by SuperDuperOne** [comment] 2020-07-14 08:29
Hi @anatolybolshakov 
apologies for the late reply, 
I did what you suggested from another computer and got the same error connection, so I believe, we will need to allow access to/from azure devops to our on-premise servers via SSH.

I am however, still confused to why having the Priv and Pub key + password to server didn't even let me run and commands on box....

**Comment by SuperDuperOne** [comment] 2020-07-14 09:28
will the network guys need to whitelist azure devops or just enable SSH port access to the server?

will this link be useful for them to enable SSH access from ADevops to Server

https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops

**Comment by anatolybolshakov** [comment] 2020-07-14 16:57
@SuperDuperOne yes, could you please share these [steps ](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#ssh-connections) from this instruction with them?

**Comment by anatolybolshakov** [comment] 2020-07-27 08:13
Hi @SuperDuperOne is this issue still actual for you? Do you have any updates about network check?

**Comment by SuperDuperOne** [comment] 2020-07-27 09:01
Hey @anatolybolshakov 

apologies for the delay, i guess for now, you can close this ticket.
The network team arent going to open up SSH ports due to security reasons and with their own testing, however, we can rule out the CopyFilesOverSSH being faulty since we have tested the task locally (outside of company network) and it works perfectly.
I guess I will just need to present a business case to why the above is essential for our deployment.

thanks for following up!

**Comment by anatolybolshakov** [comment] 2020-07-28 13:52
Thanks @SuperDuperOne! I'm closing it at the moment

**Closed by anatolybolshakov** 2020-07-28 13:52 UTC
Labels: Area: ABTT, Task: CopyFilesOverSSH, question
