### ISSUE TITLE
File Transform - does not replace empty applicationSettings values

### ISSUE THREAD

**Issue by gunars-skangals** [microsoft/azure-pipelines-tasks#13296] opened 2020-07-15 13:00 UTC
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: File transform

## Environment
- Server - Azure Pipelines
- Agent - Windows Server 2019 Datacenter

## Issue Description

App.config settings with an empty value element are not replaced (task version 1).

 - File format: XML
 - parent stage has a linked variable group with a key for each setting name

relevant config file part:
```
...
<applicationSettings>
    <ProjectName.Properties.Settings>
      <setting name="Setting1" serializeAs="String">
        <value>foobar</value>
      </setting>
      <setting name="Setting2" serializeAs="String">
        <value></value>
      </setting>
      <setting name="Setting3" serializeAs="String">
        <value> </value>
      </setting>
      <setting name="Setting4" serializeAs="String">
        <value/>
      </setting>
   </ProjectName.Properties.Settings>
</applicationSettings>
```

Values for `Setting2`, `Setting3`, `Setting4` are not updated and are changed to `<value/>`, which might cause other issues, e.g., setting value changing from empty string or whitespace to null.

For values that are updated, task log contains 2 rows when a setting is replaced - is repeated after  `Processing substitution for xml node : configSections`. `configSections` does not contain these keys

### Task logs

Task logs don't contain rows for the "empty" settings, would look like:
```
Processing substitution for xml node : applicationSettings
Updating value for key= Setting1 with token value: CONFIG_FILE_SETTINGS_TOKEN(Setting1)
Processing substitution for xml node : connectionStrings
Processing substitution for xml node : configSections
Updating value for key= Setting1 with token value: CONFIG_FILE_SETTINGS_TOKEN(Setting1)
```

**Comment by AmrutaKawade** [comment] 2020-08-31 09:28
I tried to reproduce this issue. value for settings3 replaced for me. Yes other 2 cases are not handled.

**Comment by 20shivangi** [comment] 2020-09-11 09:56
@gunars-skangals We do not support the scenario of Settings 2 and settings 4 with empty value to be replaced.

**Comment by gunars-skangals** [comment] 2020-09-15 10:29
that would be the same as not supporting transformations in JSON for keys like
```
{
  "key1": null,
  "key2": ""
}
```
otherwise - this is for the .NET Framework setting format which will be irrelevant soon enough and meanwhile i can deal with this by having dummy values everywhere

**Comment by 20shivangi** [comment] 2020-09-16 15:07
@gunars-skangals Can we close this issue ?

**Comment by 20shivangi** [comment] 2020-09-18 07:07
Since we do not support these scenarios, please feel free to re-open if you face any other issue.

**Closed by 20shivangi** 2020-09-18 07:07 UTC
Labels: Area: Release, bug
