### ISSUE TITLE
IIS Web App Manage: Error when Enable IIS is checked

### ISSUE THREAD

**Issue by Tiberriver256** [Microsoft/azure-pipelines-tasks#9336] opened 2019-01-16 03:02 UTC
## Environment
- Server - Azure Pipelines

## Issue Description

The code is here: 

https://github.com/Microsoft/azure-pipelines-tasks/blob/1d75fa8f66aa1cf7a9cb62946939f30f087b2969/Tasks/IISWebAppManagementOnMachineGroupV0/IISWebAppManagementOnMachineGroup.ps1#L84-L89

On a Windows 2012 R2 server the -IncludeAllSubfeatures switch will require .Net 3.5 to be installed prior to the task being able to run successfully and will error out asking for a source path.

Is there a good way to avoid having to do some pre-work (i.e. install .Net 3.5)?

**Comment by SumiranAgg** [comment] 2019-01-30 09:07
@Tiberriver256 I tried to reproduce the issue. i.e. I ran below commands
Import-Module servermanager 
Add-WindowsFeature web-server -includeallsubfeature
on win 2012 r2 machine. It worked for me. Could you share the exact error message from the task? Also can you try these commands locally on the machine and share result.

**Comment by SumiranAgg** [comment] 2019-02-27 03:57
Closing the issue due to lack of information. please feel free to reopen if required.

**Closed by SumiranAgg** 2019-02-27 03:57 UTC
Labels: Area: Release
