### ISSUE TITLE
It would help to include some paths to exclude from the cache

### ISSUE THREAD

**Issue by dchristSC** [microsoft/azure-pipelines-tasks#11255] opened 2019-08-30 18:14 UTC
I'm caching some build dependencies but it would be nice to include some paths to exclude from the cache. 

Thanks,
Dan

**Comment by johnterickson** [comment] 2019-11-04 21:18
Thanks for the feedback! 

I think this could be a good candidate for contribution should anyone want to take it up

**Comment by johnterickson** [comment] 2019-11-04 21:19
Dupe of #11219

**Closed by johnterickson** 2019-11-04 21:19 UTC
Labels: Area: ArtifactsCore, Area: PipelineCaching, enhancement, help wanted
