### ISSUE TITLE
Transient like failures while using DotNetCoreInstaller@2 Task

### ISSUE THREAD

**Issue by chidozieononiwu** [microsoft/azure-pipelines-tasks#12613] opened 2020-04-01 20:35 UTC
**Question, Bug, or Feature?**  
*Type*: Question, Bug

**Enter Task Name**: DotNetCoreInstaller

## Environment
- Server - Azure Pipelines
Account Name: azure-sdk

## Issue Description
Transient failures while using DotNetCoreInstaller@2 task.
The task seems to have been renamed to UseDotNet@2, could that be the cause of the bug?

### Error logs
``` 
##[error]Failed while installing version: 2.1.10 at path: C:/hostedtoolcache/windows/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/abe669cc-b824-41d4-89c0-3c27d4511800/765d9236495bb6a2196389ec8221c4f8/dotnet-runtime-2.1.10-win-x64.zip Error: Error: certificate has expired
```

**Comment by vineetmimrot** [comment] 2020-04-03 06:48
@chidozieononiwu Thanks for reporting the issue. We will have a look at it soon.

**Comment by staff0rd** [comment] 2020-04-11 14:05
Just got this on linux agent;

```
2020-04-11T14:02:56.1076653Z ##[section]Starting: Use .NET Core sdk
2020-04-11T14:02:56.1084928Z ==============================================================================
2020-04-11T14:02:56.1085736Z Task         : Use .NET Core
2020-04-11T14:02:56.1086504Z Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
2020-04-11T14:02:56.1087387Z Version      : 2.165.0
2020-04-11T14:02:56.1089244Z Author       : Microsoft Corporation
2020-04-11T14:02:56.1089894Z Help         : https://aka.ms/AA4xgy0
2020-04-11T14:02:56.1090545Z ==============================================================================
2020-04-11T14:02:59.5225814Z Tool to install: .NET Core sdk version 3.1.201.
2020-04-11T14:03:01.5191920Z Found version 3.1.201 in channel 3.1 for user specified version spec: 3.1.201
2020-04-11T14:03:01.5785842Z Version 3.1.201 was not found in cache.
2020-04-11T14:03:01.5786623Z Getting URL to download .NET Core sdk version: 3.1.201.
2020-04-11T14:03:01.5787640Z Detecting OS platform to find correct download package for the OS.
2020-04-11T14:03:01.5791473Z [command]/home/vsts/work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.165.0/externals/get-os-distro.sh
2020-04-11T14:03:01.5792385Z Primary:linux-x64
2020-04-11T14:03:01.5793012Z Legacy:ubuntu.16.04-x64
2020-04-11T14:03:01.5793677Z Detected platform (Primary): linux-x64
2020-04-11T14:03:01.5794738Z Detected platform (Legacy): ubuntu.16.04-x64
2020-04-11T14:03:01.5796642Z Downloading: https://download.visualstudio.microsoft.com/download/pr/f65a8eb0-4537-4e69-8ff3-1a80a80d9341/cc0ca9ff8b9634f3d9780ec5915c1c66/dotnet-sdk-3.1.201-linux-x64.tar.gz
2020-04-11T14:03:01.7055401Z ##[error]Failed while installing version: 3.1.201 at path: /opt/hostedtoolcache/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/f65a8eb0-4537-4e69-8ff3-1a80a80d9341/cc0ca9ff8b9634f3d9780ec5915c1c66/dotnet-sdk-3.1.201-linux-x64.tar.gz Error: Error: certificate has expired
2020-04-11T14:03:01.7088843Z ##[section]Finishing: Use .NET Core sdk
```

**Comment by issacnitin** [comment] 2020-06-03 09:49
Duplicate of https://developercommunity.visualstudio.com/content/problem/979557/expired-certificate-on-dotnet-install-httpsdotnetc.html 
@chidozieononiwu @staff0rd 
We reported this issue to our CDN team and they have cleaned up some servers which had certificate issue. 
I'm closing this issue for now, please feel free to re-open in case of any queries or concerns
Thanks

**Closed by issacnitin** 2020-06-03 09:49 UTC
Labels: Area: Release, bug, question
