### ISSUE TITLE
Cancelling the build does not kill the maven process

### ISSUE THREAD

**Issue by sarod** [microsoft/azure-pipelines-tasks#14229] opened 2021-01-14 15:15 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Maven

## Environment
- Server - Azure Pipelines       
   https://dev.azure.com/semarchy/Build Project/_build/results?buildId=3799

- Agent - Hosted agent Agent Pool: "Azure Pipelines" https://dev.azure.com/semarchy/Build%20Project/_settings/agentqueues?queueId=9&view=jobs

## Issue Description

Cancelling the build does not kill the maven task which runs until the timeout kills it

### Task logs

Not available

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

No log available

**Comment by egor-bryzgalov** [comment] 2021-01-14 16:11
Closed as duplicate of #14228

**Closed by egor-bryzgalov** 2021-01-14 16:11 UTC
Labels: Area: ABTT, Task: Maven, bug, triage

**Comment by sarod** [comment] 2021-01-14 17:01
Sorry about the duplicate I thought github didn't create the first one because I received a 404 when I clicked "create"
