### ISSUE TITLE
File Transform (JSON) same name different shape across files

### ISSUE THREAD

**Issue by staff0rd** [microsoft/azure-pipelines-tasks#11344] opened 2019-09-15 04:54 UTC
**Question, Bug, or Feature?**  
*Type*: Question/Feature
**Enter Task Name**: FileTransform
## Environment
Azure Pipelines
    
- staff0rd/5
- Hosted/ubuntu-latest

## Issue Description

A tfx extension for Azure Pipelines requires a manifest.json with a `version: "1.0.0"` format and a taskName/task.json with a `version: { Major: 1, Minor: 0, Patch: 0}` format.

I can define the following;
```yaml
variables:
- group: my-group
- name: version.Major
  value: 1
- name: version.Minor
  value: 1
- name: version.Patch
  value: $(Build.BuildId)
- name: version
  value: $(Build.BuildNumber)
```
But the result after running FileTransform is:
**EXPECTED**: manifest.json has `version: "1.0.0"` and task.json has `version: { Major: 1, Minor: 0, Patch: 0}`
**ACTUAL**:  manifest.json has `version: "1.0.0"` and task.json has `version: "1.0.0"` 

[Example yaml](https://github.com/staff0rd/tfx-cloudflare-purge/blob/87a062d98d2ff68efa7b82a5a139a9ac4ff05a08/azure-pipelines.yml)

**Comment by SumiranAgg** [comment] 2019-09-16 07:30
This is happening because you have a variable 'version' defined. This key is present in both manifest.json and task.json. In manifest.json it substitutes the value of version key which is desirable, when it does the same for task.json it causes an issue in this case. As a workarounf you can configure two jobs with file transform tasks, and define job level varibales. Ref doc: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch

**Comment by SumiranAgg** [comment] 2019-09-18 08:26
Closing the issue, since it is by design. please feel free to re-open if required.

**Closed by SumiranAgg** 2019-09-18 08:26 UTC
Labels: Area: Release
