### ISSUE TITLE
FTP Upload task cannot delete files with french accents in filename

### ISSUE THREAD

**Issue by jmgodin** [microsoft/azure-pipelines-tasks#7514] opened 2018-06-19 14:38 UTC
## Troubleshooting

FTP Upload task has Clean the remote directory content selected but can't delete files with french accents in filename.

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 2018

- Agent - Hosted or Private: 
    
    - Private

### Error logs

2018-06-17T23:27:40.1328221Z connected: Microsoft FTP Service
2018-06-17T23:27:40.1800885Z removing remote directory contents: /MyPath
2018-06-17T23:27:40.4559143Z FTP upload failed: "Error cleaning remote path: Unable to remove remote folder: \MyPath error: Error: The system cannot find the file specified.". FTP log: "[connection] > 'DELE \\MyPath\\Formation/pdf/Skype/Aide-Mémoire Skype - Audio.pdf',[connection] < '550 The system cannot find the file specified. \r\n',[parser] < '550 The system cannot find the file specified. \r\n',[parser] Response: code=550, buffer='The system cannot find the file specified.'".
2018-06-17T23:27:40.4627424Z ##[error]Error cleaning remote path: Unable to remove remote folder: \MyPath\Formation error: Error: The system cannot find the file specified.

**Comment by yacaovsnc** [comment] 2019-07-05 16:35
I couldn't repro this with latest FTPUpload v2:
```
============================================================================== |  
-- | --
  | Task         : FTP upload |  
  | Description  : Upload files using FTP |  
  | Version      : 2.154.0 |  
  | Author       : Microsoft Corporation |  
  | Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/ftp-upload |  
  | ============================================================================== |  
  | 53dc2219-5ab5-436f-891d-f688ae705de0 exists true |  
  | connecting to: waws-prod-sn1-057.ftp.azurewebsites.windows.net:21 |  
  | connected: 220 Microsoft FTP Service |  
  | removing remote directory contents: /upload/492535/unicode |  
  | files uploaded: 0, directories processed: 1, total: 1, remaining: 2, remote directory successfully created/verified: /upload/492535/unicode |  
  | File: /upload/492535/unicode/Aide-Mémoire.txt Type: upload Transferred: 0 |  
  | File: /upload/492535/unicode/Aide-Mémoire.txt Type: upload Transferred: 7 |  
  | files uploaded: 1, directories processed: 1, total: 2, remaining: 1, successfully uploaded: D:\a\1\s\unicode characters\Aide-Mémoire.txt to: /upload/492535/unicode/Aide-Mémoire.txt |  
  | File: /upload/492535/unicode/German umlauts-äöü.txt Type: upload Transferred: 0 |  
  | File: /upload/492535/unicode/German umlauts-äöü.txt Type: upload Transferred: 44 |  
  | files uploaded: 2, directories processed: 1, total: 3, remaining: 0, successfully uploaded: D:\a\1\s\unicode characters\German umlauts-äöü.txt to: /upload/492535/unicode/German umlauts-äöü.txt |  
  | FTP upload successful |  
  | host: waws-prod-sn1-057.ftp.azurewebsites.windows.net |  
  | path: /upload/492535/unicode |  
  | files uploaded: 2 |  
  | directories processed: 1 |  
  | disconnecting from: waws-prod-sn1-057.ftp.azurewebsites.windows.net |  
  | Finishing: FTP Upload: unicode characters

```

This new task is released on hosted service already, and will be included in the next Azure DevOps 2019 update.

**Comment by yacaovsnc** [comment] 2019-07-09 18:41
Please open new issue against FtpUpload V2 task if the problem is still there.

**Closed** 2019-07-09 18:41 UTC
Labels: Area: CrossPlatform
