### ISSUE TITLE
GitHub Release task has incorrect tip for the release title

### ISSUE THREAD

**Issue by heaths** [Microsoft/azure-pipelines-tasks#9397] opened 2019-01-24 07:05 UTC
## Environment
- Server: [Azure Pipelines](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=238138)

- Agent: Hosted VS2017

## Issue Description

Seems an update to the GitHub Release task was just pushed out and the release title was not only the build number (the GitHub tag), but also the last comment. This does not correspond to the tooltip for the Release title field, which reads, "Specify the title of the GitHub release. If left empty, the tag will be used as the release title.". I left it blank, but the release still has a commit title (not consistent with our [past releases](https://github.com/Microsoft/vswhere/releases/tag/2.6.3%2B7446fa5c48)).

### Task logs

See [release](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=238138).

### Error logs

No error.

**Comment by mdmdakbar** [comment] 2019-01-25 02:02
@heaths I am not able to reproduce this behavior. Not sure why it happened. We do not have any change like this. Release title should be tag only if it is left empty.

Not sure if its related to GitHub api. I think we should wait for the next occurrence of this behavior. Please let us know if it happen again.

**Comment by prativen** [comment] 2019-02-20 03:52
Closing for now as we are not able to reproduce this

**Closed by prativen** 2019-02-20 03:52 UTC
Labels: Area: Release

**Comment by heaths** [comment] 2019-02-20 17:02
I think you're right: this is probably GitHub API-related. When multiple commits are associated with a release I don't see this - only with releases with one commit.
