### ISSUE TITLE
Azure Powershell Long running operation failed with status 'NotFound'

### ISSUE THREAD

**Issue by denaliwhite** [microsoft/azure-pipelines-tasks#10085] opened 2019-04-10 21:21 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShellV2

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: PicoBrewInc / PicoBrew.com / Live Release / Live Release 20190404.1

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted VS2017

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Intermittent failures of Azure Powershell V2.* release step performing an Azure SQL Database copy, failing with ##[error]Long running operation failed with status 'NotFound'. The actual database copy is completed successfully and is verified on portal.azure.com.

### Task logs

Can provide privately to protect proprietary info.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
Scrubbed log
[tasklog_7.log](https://github.com/Microsoft/azure-pipelines-tasks/files/3065897/tasklog_7.log)

**Comment by ggirard07** [comment] 2019-04-12 18:07
Same issue here, any update on the issue?

**Comment by denaliwhite** [comment] 2019-04-12 18:51
Still happening very regularly for us, absolutely debilitating for our production and development pipelines. An open support request has been going nowhere for about a week (they keep asking for fiddler captures of local client data which has nothing to do with Hosted Agent to Azure communication issues).

**Comment by ggirard07** [comment] 2019-04-12 19:32
I don't know for you, but in our case it happens for resources we delete then recreate right away.
By deleting the resource upfront (few minutes prior to start the actual release pipeline), issue seems to does not occur for now. Still need a few more run to confirm this behavior.

Here is yet another issue impacting us due to too quick resource deletion then re-creation https://github.com/MicrosoftDocs/azure-docs/issues/26382.

**Comment by denaliwhite** [comment] 2019-04-18 18:09
We moved resource deletion to earlier in the process to band-aid the issue. Still looking for a more elegant solution. Support ticket still unresolved (incident 119040426002744).

**Comment by Ajay-MS** [comment] 2019-05-15 04:00
@denaliwhite 

What cmdlet are you running for the Azure SQL database copy in PowerShell?

Are you facing this issue only with version 2.* ? Can you please try with the latest version of the task.

**Comment by dominikfoldi** [comment] 2019-05-15 07:26
We are facing this issue with Azure PowerShell task 4.* because that is the only version of the task that is using the new Az PowerShell 2.0.0.

**Comment by Ajay-MS** [comment] 2019-05-21 11:03
Are you facing this issue with AzureDevOps only ?

I think this issue is relevant even if you try to run cmdlet locally. In that case you can report this issue with Azure PS team - https://github.com/azure/azure-powershell

**Comment by 20shivangi** [comment] 2019-06-03 06:06
We are closing this issue as of now as we didn't get any response. If the issue reproduces, please feel free to reopen the issue.

**Closed by 20shivangi** 2019-06-03 06:06 UTC
Labels: Area: Core, Area: Release, bug

**Comment by motowilliams** [comment] 2020-05-26 16:53
Please re-open. This happens with the new Az cmdlets. `Remove-AzResourceGroup : Long running operation failed with status 'Conflict'.`
