### ISSUE TITLE
Jenkins Queue Job does not pass parameter to Jenkins Job  

### ISSUE THREAD

**Issue by YogeshBandiwadekar** [Microsoft/azure-pipelines-tasks#5119] opened 2017-08-25 02:12 UTC
Hi All

**Configuration I have is below** 

1) TFS 2017 Update 2 
2) Added Jenkins Service End Point 
3) Jenkins Server & Many Slaves Running CI & CD pipelines. **( No Plugin installed to  sync with TFS)**

**TFS Build** 
Created wrapper build just to trigger Jenkins parametric job, which can be only triggered manually.
I have passed parameter with key=value pair format in TFS build  but looks like it does not pass those to Jenkins job.

**Question are below** 

Am i missing anything in configuration?
Is any configuration changes to be done at Jenkins side too make it work?

**_Any help is appreciated here._**

Thanks
Yogesh

**Comment by Semant1ka** [comment] 2017-08-25 10:53
I was going to file exactly the same issue two days ago but I solved the problem by referencing parameters like this in Jenkins pipeline "${params.BRANCH}", all other references are not working.

**Comment by jpricketMSFT** [comment] 2018-01-08 16:21
@YogeshBandiwadekar - does the solution provided by Semant1ka work for you?

**Comment by Phillips57** [comment] 2018-04-23 09:40
I've Tried the solution provided by Semant1ka, and can confirm that it did not work for me !

**Comment by madshall** [comment] 2018-05-07 13:28
It didn't work for me either.

**Comment by madshall** [comment] 2018-05-07 18:04
I'm using TFS(not sure what version). The "Parameterized job" is checked and the params are:
```
BUILD_ID=222
```
From log:
```
jobQueuePostData = {"url":"https://jenkins.***.com/job/***/job/***/buildWithParameters?delay=0sec","formData":{"BUILD_ID":"222"},"strictSSL":true}
...
parsedBody for: https://jenkins.***.com/queue/item/295771/api/json: {"actions":[{"parameters":[{"name":"BUILD_ID","value":""}]},{"causes":[{"shortDescription":"Started by user ***","userId":"***","userName":"***"}]}],"blocked":false,"buildable":false,"id":295771,"inQueueSince":1525715473420,"params":"\nBUILD_ID=","stuck":false,"task":{"name":"***","url":"https://jenkins.***.com/job/***/job/***/","color":"red_anime"},"url":"queue/item/295771/","why":null,"cancelled":false,"executable":{"number":32,"url":"https://jenkins.***.com/job/***/job/***/32/"}}
getting job task URL:https://jenkins.***.com/job/***/job/***/api/json
(0:***:32) debug: created
getting job task URL:https://jenkins.***.com/job/***/job/***/api/json
jobQueue.start()
parsedBody for: https://jenkins.***.com/job/***/job/***/api/json: {"actions":[{},{"parameterDefinitions":[{"defaultParameterValue":{"value":""},"description":"","name":"BUILD_ID","type":"StringParameterDefinition"}]},{},{},{},{},{},{},{},{},{},{}],"description":""
...
```
The task version is 2.*

**Comment by pjquirk** [comment] 2018-05-07 19:04
Thanks @madshall.  It looks like the `BUILD_ID` parameter is being posted to Jenkins as seen in the `jobQueuePostData` debug string, but doesn't appear when it's queued.  Some more questions:

- What version of Jenkins are you using? 
- What type of job parameter is `BUILD_ID` and does it have a default value?  
- Do you have the [Team Foundation Server plugin](https://plugins.jenkins.io/tfs) installed? What version if so?
- Have you tried using a REST client (Postman, Insomnia, etc) to queue a build with a parameter?  The task makes a POST request to `{server}/job/{jobName}/buildWithParameters?delay=0sec` and adds form data for each parameter.

I could not reproduce using Jenkins 2.73.3 and a build with a string parameter. I also tried with and without the [Team Foundation Server plugin](https://plugins.jenkins.io/tfs), and it worked both ways.

**Comment by madshall** [comment] 2018-05-07 19:14
It's a string parameter with no default value. Jenkins v 1.650, no TFS plugin installed. I haven't tried postman. I think it's jenkins version.. Is the task of version 1.* supposed to be used with jenkins 1.*?

**Comment by pjquirk** [comment] 2018-05-07 20:13
@madshall Yeah I looks to be differences in Jenkins versions.  The 1.650 API expects a (application/x-www-form-urlencoded) payload of the form:

    name=BUILD_ID&value=456

And the 2.73.3 API expects this payload:

    BUILD_ID=456

I don't think the chances of getting this fixed are big since Jenkins v1 has been marked end-of-life for almost two years at this point.

@Phillips57 and @YogeshBandiwadekar, what versions of Jenkins are you using?

**Comment by Phillips57** [comment] 2018-06-26 15:13
Jenkins is Version 1.643, but I can confirm that Passing parameters works when I use Jenkins versions 2.89.3

**Comment by brcrista** [comment] 2018-10-23 16:48
Sounds like this is fixed by using the supported version of Jenkins, so I'm going to mark this as closed.

**Closed by brcrista** 2018-10-23 16:48 UTC
Labels: Area: CrossPlatform
