### ISSUE TITLE
AzureFileCopy to VM copies temp container

### ISSUE THREAD

**Issue by HughDevlin** [microsoft/azure-pipelines-tasks#12542] opened 2020-03-17 17:29 UTC
Task: AzureFileCopy V4 

Environment: Azure pipeline in windows-latest pool

Bug: When destination is VM, AzureFileCopy creates a temporary intermediary blob container, as stated in the documentation, but the _container_ is copied to the VM, instead of the specified source file.

```
- task: AzureFileCopy@4
  displayName: 'Copy secure file to VM'
  inputs:
    sourcePath: $(myfile.secureFilePath)
    azureSubscription: $(subscriptionName)
    storage: $(storageAccount)
    destination: 'AzureVMs'
    resourceGroup: $(resourceGroup)
    resourceFilteringMethod: 'machineNames'
    machineNames: 'MyVM'
    vmsAdminUserName: 'username'
    vmsAdminPassword: '****'
    targetPath: 'Downloads'
    enableCopyPrerequisites: true
```
Expected:

C:\Users\username\Documents\Downloads\myfile.txt

Actual:

C:\Users\username\Documents\Downloads\92293b49-0de6-400b-8b75-7a9c72bfd512\myfile.txt

Tried specifying blob prefix, container name, and adding a wildcard to sourcePath, same result.

**Comment by HughDevlin** [comment] 2020-03-19 19:14
Perhaps this behavior of AzureFileCopy is related to using AzureFileCopy to copy a secure file, and \92293b49-0de6-400b-8b75-7a9c72bfd512\ is the secure file path, not the temporary blob container, and AzureFileCopy is incorrectly copying the secure directory, and thereby exposing the secure path.

**Comment by 20shivangi** [comment] 2020-03-23 11:59
@HughDevlin I think the issue is with new exe of AzureFileCopy only. We will confirm this with Azure Storage team and let you know

**Comment by HughDevlin** [comment] 2020-03-24 20:20
v3 works as expected

**Comment by 20shivangi** [comment] 2020-03-24 20:21
yeah , I checked it

**Comment by HughDevlin** [comment] 2020-03-24 20:47
tried it on a source file that was not a secure file, same unexpected result (extra dir)

**Comment by 20shivangi** [comment] 2020-03-24 21:02
@HughDevlin Will fix the issue as soon as possible.

**Comment by 20shivangi** [comment] 2020-03-26 07:55
@HughDevlin The issue has been fiexd in PR : https://github.com/microsoft/azure-pipelines-tasks/pull/12582 . It will take at least 6-8 weeks to get deployed. Thanks for your patience. 
Thereby, closing this issue

**Closed by 20shivangi** 2020-03-26 07:55 UTC
Labels: Area: Release, bug
