### ISSUE TITLE
XamarinAndroid@1 replaces target project with wildcards when using secret variables.

### ISSUE THREAD

**Issue by bakerhillpins** [microsoft/azure-pipelines-tasks#13334] opened 2020-07-22 23:42 UTC
**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: 
XamarinAndroid@1

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/XamarinAndroidV1

## Environment
- Server - Azure Pipelines

## Issue Description
Linking a Variable Group that contains Secret variables to a Pipeline causes the XamarinAndroid@1 task to replace the project specified on the MSBuild.exe command line with wildcards.  So `"d:\a\1\s\Hylink\Hylink.Android\Hylink.Android.csproj"` becomes `"D:\a\1\s\Hylink\***\***.csproj`.

1. Construct a classic pipeline using the prepackaged Xamarin.Android template to build a Xamarin.Forms project.
2. Create a new variable group
3. Add (in our case we have 2 variables) secret variables and values, such as keystore.password and keystore.alias.
4. Link that variable group to the pipeline. The variables need not be used by the pipeline.
5. Save and Run the build.

If the pipeline is executed **without** the linked variables the output from the XamarinAndroid@1 task will be as follows:
`2020-07-22T22:38:45.2820750Z ##[command]"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" "d:\a\1\s\Hylink\Hylink.Android\Hylink.Android.csproj" /nologo /nr:false /t:"Clean" /dl:CentralLogger,`

If you link the variable group previously created to the pipeline the project path and name is replaced with a set of wildcards:
`2020-07-22T22:48:32.3241088Z ##[command]"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" "D:\a\1\s\Hylink\***\***.csproj" /nologo /nr:false /t:"Clean" /dl:CentralLogger,`

In our situation both builds complete with output that seems to be correct and similar. Assuming that it is actually using wildcards (and building all .csproj files) our build would probably fail if not for the fact that some projects are disabled in the configuration manager.

### Task logs
[BuildwithSecretVariables_logs_749.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4963225/BuildwithSecretVariables_logs_749.zip)
[BuildwithoutSecretVariables_logs_750.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4963226/BuildwithoutSecretVariables_logs_750.zip)

**Comment by v-kyljon** [comment] 2020-07-23 01:48
#13314 appears to be similar

**Comment by alexander-prozorov** [comment] 2020-08-15 07:40
Hello @bakerhillpins,
Thank you for the complete description and logs. Could you please also confirm if you use a full path without wildcards as Project value in both cases?

**Comment by bakerhillpins** [comment] 2020-08-17 11:37
@alexander-prozorov  I'm sorry, I don't understand what you're asking me to confirm. Can you please be explicit about the changes you are looking to test. Thanks.

**Comment by alexander-prozorov** [comment] 2020-08-18 09:48
@bakerhillpins Sorry, the question was about input values for the project property. They are different in the logs:

```
Without secret variables: ##[debug]INPUT_PROJECT: 'D:\a\1\s\Hylink\Hylink.Android\Hylink.Android.csproj'
With secret variables:  ##[debug]INPUT_PROJECT: 'D:\a\1\s\Hylink\***\***.csproj'
```

It turned out that the problem is with logger masking. It happens when the content of one of the secrets in the variable group is “Hylink.Android” so it is replaced with "***" everywhere in the logs.

@leantk Since this isn't related to the tasks and task-lib, where should this issue be forwarded?

**Comment by bakerhillpins** [comment] 2020-08-18 11:26
@alexander-prozorov   To answer the original question: The input values were not changed between runs. 

But it seems you have answered that yourself and you have discovered what the problem is.

**Comment by leantk** [comment] 2020-08-18 13:46
This is by design unfortunately. When secret variables are used, we scan the logs for every occurrence of the secret and replace the string with *** so we aren't printing secrets out in the logs. We have no way to tell when a string in a log is referencing a secret or it's just a string. For example, if your secret variable is "the" then every time "the" appears in the logs, it will be replaced with *** not matter if the line is "login -pw **the**" or "**the** script is complete". 

In your case I'm guessing that the strings that are being replaced with *** are also the secret values and so this is what is happening.

**Comment by bakerhillpins** [comment] 2020-08-18 14:31
@leantk 
Your description was a bit unclear to me and I had to read it several times to understand. However, I understand now... The **values** of secret variables are scrubbed from the log output using a simple string search algo.

Thus all pipeline output is subject to a search and replace operation, where any linked secret variable's **value** is replaced with "***" in the output.

In this case a secret variable used had it's value set to the name of a project, "Hylink.Android", and thus anytime that string exists in the output it was scrubbed.

Thanks for clarifying this. Might be worth an update to the documentation.

**Comment by leantk** [comment] 2020-08-18 14:45
Yep that's a good suggestion on the docs. I'll take note of making an update. I'm going to close this out then but if you have more questions, please feel free to comment

**Closed by leantk** 2020-08-18 14:45 UTC
Labels: Area: ABTT, Task: XamarinAndroid, bug
