### ISSUE TITLE
[REGRESSION]: DeleteFiles fails with no such file or directory with filename containing emoji

### ISSUE THREAD

**Issue by mlaurencin** [microsoft/azure-pipelines-tasks#19395] opened 2023-12-19 21:15 UTC
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

DeleteFiles

### Breaking task version

1.231.1

### Last working task version

1.231.0

### Regression Description

Expected: DeleteFiles to scan through all files without issue
Actual: DeleteFiles error when trying to parse one specific file within [this Node directory](https://github.com/nodejs/node/tree/main/deps/v8/test/message). It states that [this file](https://github.com/nodejs/node/blob/main/deps/v8/test/message/unicode-filename-%F0%9F%8E%85%F0%9F%8E%84.js) does not exist. (We noted that this was the first file that contained emojis).

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows 2019

### Relevant log output

```shell
2023-12-15T22:49:49.6680312Z ##[section]Starting: DeleteFiles
2023-12-15T22:49:49.6780409Z ==============================================================================
2023-12-15T22:49:49.6780526Z Task         : Delete files
2023-12-15T22:49:49.6780582Z Description  : Delete folders, or files matching a pattern
2023-12-15T22:49:49.6780674Z Version      : 1.231.1
2023-12-15T22:49:49.6780726Z Author       : Microsoft Corporation
2023-12-15T22:49:49.6780789Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/delete-files
2023-12-15T22:49:49.6780897Z ==============================================================================
2023-12-15T22:50:16.9547428Z ##[error]Unhandled: Failed find: ENOENT: no such file or directory, lstat 'D:\a\_work\1\b\src\third_party\electron_node\deps\v8\test\message\unicode-filename-🎅🎄.js'
2023-12-15T22:50:16.9550552Z ##[error]Error: Failed find: ENOENT: no such file or directory, lstat 'D:\a\_work\1\b\src\third_party\electron_node\deps\v8\test\message\unicode-filename-🎅🎄.js'
    at Object.find (D:\a\_work\_tasks\DeleteFiles_b7e8b412-0437-4065-9371-edc5881de25b\1.231.1\node_modules\azure-pipelines-task-lib\task.js:1000:15)
    at D:\a\_work\_tasks\DeleteFiles_b7e8b412-0437-4065-9371-edc5881de25b\1.231.1\deletefiles.js:29:25
    at Object.<anonymous> (D:\a\_work\_tasks\DeleteFiles_b7e8b412-0437-4065-9371-edc5881de25b\1.231.1\deletefiles.js:101:3)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47
2023-12-15T22:50:16.9860863Z ##[section]Finishing: DeleteFiles
```

### Repro steps

```yml
# Some files and directories should not be published.
    - task: DeleteFiles@1
      inputs:
        SourceFolder: ${{ parameters._workingDirectory }}
        Contents: |
          **/.azure-devops
          **/.git
          **/.npmrc
          **/.sdl
          src/microsoft/README.md
          src/third_party/depot_tools/win_toolchain/vs_files
```

**Comment by ivanduplenskikh** [comment] 2023-12-20 14:30
@mlaurencin, thanks for reporting!
The error is reproduced due to an [issue](https://github.com/nodejs/node/issues/48673) in node itself. As soon as we are able to update the dependency to include this fix, I will notify you.

**Comment by ivanduplenskikh** [comment] 2024-02-20 11:33
@mlaurencin DeleteFilesV1 v1.235.0 is already available.
Could you confirm the fix?

**Comment by ivanduplenskikh** [comment] 2024-03-05 11:20
I'm closing this issue for now.
Feel free to reopen if it's still relevant for you.

**Closed by ivanduplenskikh** 2024-03-05 11:20 UTC
Labels: bug, Area: Artifacts, regression

**Comment by carstencodes** [comment] 2025-05-20 14:49
Hi @ivanduplenskikh,

we are currently experiencing this issue again with DeleteFilesV1 and CopyFilesV2 when a file contains a unicode character.

We are using DeleteFilesV1 @ 1.255.0 and CopyFilesV2 @ 2.246.0 on agent version 4.251.0 

Our operating system is Windows. Is there anything we can do about it, e.g. start agents with another encoding or something similar?

Regards

Carsten

**Comment by carstencodes** [comment] 2025-05-20 14:57
One correction: The agent was a linux agent.

We are using node 20.1 as runtime.
