### ISSUE TITLE
Azure App Service Deploy overwrites content of wwwroot with old version of application

### ISSUE THREAD

**Issue by shoter** [microsoft/azure-pipelines-tasks#13946] opened 2020-11-21 23:16 UTC
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure App Service deploy (v4.*)

## Environment
Azure DevOps (hosted agent)
Agent - Private Windows NT 2.170.1
## Issue Description

Issue is very similar and started as this one https://github.com/microsoft/azure-pipelines-tasks/issues/11661

When I started developing pipeline for our project I needed to deploy 2 web apps on 1 app service in Azure. My starting options for 2 deployments were as follows:

```
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy ${{ parameters.projectName}} '
  inputs:
    azureSubscription: ${{ parameters.azureSubscription }}
    WebAppName: $(Deploy.App1.WebAppName)
    packageForLinux: '$(Pipeline.Workspace)/backend/${{ parameters.projectName }}'
    VirtualApplication: '/' # /app1 for app1
    AppSettings: >-
      -- redacted --
```

First i was deploying app to wwwroot and then I was publishing second app to different dir. I had noticed that my first app is being wiped out from the earth after second publish so I changed order of publishing and everything seemed ok up to Friday this week - so it was publishing in this order:
```
app1 - \app1
app2 - \
```

I had this super weird issue where my code was acting like code from few weeks ago. i had some initialization logic that I changed recently and the change were not visible on remote. It turned out that during deployment of `app1` it was somehow deploying **old** content of my code to `\` and it was long enough so all initialization logic for this app was running and it was giving me wrong results.

Chronology of events:
- app1 starts deployment
- during deployment of app1 I see that dll of app2 is being changed to one from 6th november
- app2 old dll is doing unwanted changes to db.
- app1 completes deployment
- app1 is being deployed with newest version
- app1 crashes due to changes made by old dlls of app1 that app2 created.

### Task logs

I would rather not disclose logs atm.

### Fix attemps

- I added     UseWebDeploy: true to deploy files per this [comment](https://github.com/microsoft/azure-pipelines-tasks/issues/11661#issuecomment-592321168)  
    - Nothing changed. I still got old app that is doing old stuff.
- I did simple recurse search on D:/home
    - I did not find old version of my app. Searching on D:/ resulted on error.
    - I found only new dll that is correct.
- I decompiled compiled code
    - it was new code - that's correct behaviour.
- I checked if app1 published directory contains app2
   - there was no sight of app2 files in app1.
- I checked if I have any old files in checked source code
    - 1:1 match with kdiff3
- I will list all files in publish directory for my job
    - Everything looks normal. That dll is only in 1 place and it's new one and it is in app2 directory.
- I tried to use `RemoveAdditionalFilesFlag`
    - Problem was not resolved.
- I changed task version to 3
    - This resolved the problem. Old version of app2 is no longer running during deploy of app1.
    - This is only workaround for me. It is not real solution.

### Workaround

Change task version to 3.
(There is 1 important change between 3<->4 - packageForLinux for version 3 is not alias for Package as it is in v4)

input json (it is not clear from readme what are inputs names): https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV3/task.json
readme: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV3/README.md

**Comment by czerwinskilukasz1** [comment] 2020-12-20 18:17
Hello @chshrikh and @arjgupta , it's been a while since we submitted this issue.
Are there any updates?

I wish you Happy Holidays soon.
Best,
Łukasz

**Comment by AmrutaKawade** [comment] 2020-12-30 10:09
@czerwinskilukasz1 Are you deploying both of your apps with UseWebDeploy option?

**Comment by shoter** [comment] 2020-12-30 11:05
> 
> 
> @czerwinskilukasz1 Are you deploying both of your apps with UseWebDeploy option?

@AmrutaKawade please read the issue. Information to answer this question and other fix attempts is inside. Thank you.

**Comment by czerwinskilukasz1** [comment] 2021-01-07 14:42
Hello @arjgupta and @nadesu , it is been more than a month since we submitted this issue and we still have not heard from anybody from Microsoft team.
What are the next steps?

**Comment by AmrutaKawade** [comment] 2021-01-07 17:58
@czerwinskilukasz1 can you share debug logs for both v3 and v4.

**Comment by czerwinskilukasz1** [comment] 2021-01-07 20:53
Hello @AmrutaKawade , thank you for getting back to us.
As for logs, we would need to look through them and make sure we don't share any sensitive information from our client. Sadly, at this point of our project, we cannot allocate more time for this bug. We might be able to get back to you with logs in 1-2 months, or if the workaround stops working for us and we need to fix the issue. Anyways, we will be very happy to send you the logs via email then.

**Comment by AmrutaKawade** [comment] 2021-01-08 06:13
I have sent you mail on your gmail id. You can reply back on same with logs. If you can provide sample app with minimal code which will reproduce this issue that will also help.

**Comment by 20shivangi** [comment] 2021-02-11 05:34
Is the issue still being faced ?

**Comment by shoter** [comment] 2021-02-11 09:26
I do not know. We did not go back to version 4 after we found workaround. Too much hassle. There is a chance that it might still be happening.

**Comment by 20shivangi** [comment] 2021-02-15 05:48
We are closing the issue. Please feel free to reopen the issue if it is still being faced. Thanks :)

**Closed by 20shivangi** 2021-02-15 05:48 UTC
Labels: Area: Release, Task: AzureRmWebAppDeployment, bug, environment:under-investigation

**Comment by tjohnson314** [comment] 2022-04-06 18:29
Hi, my team is now hitting this same issue repeatedly.

Our app service includes a frontend that is deployed to the root, and a backend that is deployed to a /backend virtual path. We used the AzureRmWebAppDeployment@1 task with the VirtualApplication: 'backend' argument, and everything worked fine until last week.

Then we migrated the backend from .NET Core to .NET Framework. Now every time the backend pipeline runs the AzureRmWebAppDeployment task, it deploys to the root and overwrites our frontend. The argument VirtualApplication argument seems to be ignored.

We've tried other versions of the AzureRmWebAppDeployment task (@1, @2, @4), but none of them have worked. As a temporary workaround, I was able to deploy the backend by publishing directly from Visual Studio instead. But that's not a satisfactory long-term solution.

Feel free to reach out internally, and I can send you the logs. My alias is tijohnso.

**Comment by sunkarakamal** [comment] 2022-06-14 16:01
> y alias is tijohnso.

Hi I also have same issue. Did you get any solution for the same

**Comment by ruben0909** [comment] 2023-03-23 14:02
me too with v4

**Comment by riosengineer** [comment] 2023-11-27 16:03
Same issue for me with v4 can this be reopened?

**Comment by gavillal** [comment] 2023-12-29 22:14
> Same issue for me with v4 can this be reopened?

What type of applications are you trying to deploy? It is important to know that depending on the type of application, it may require some special configuration, such as in the case of React. I remain attentive.

**Comment by riosengineer** [comment] 2023-12-29 22:31
> > Same issue for me with v4 can this be reopened?
> 
> Hi, What type of applications are you trying to deploy? It is important to know that depending on the type of application, it may require some special configuration, such as in the case of React. I remain attentive.

Main web app is a ASP NET 4.6 and the virtual application was net core I believe. I’ve moved it from a traditional Windows IIS box to Azure Web Apps.

As a workaround I reverted to the v3 task which worked perfectly. With no changes or config to the app or its code. But when trying v4 it seems to present the issue described in this GH issue. 

Happy to provide any more info, logs, configs etc if you ever need it.
