### ISSUE TITLE
Copy Files enumerates all sub directories

### ISSUE THREAD

**Issue by centreboard** [microsoft/azure-pipelines-tasks#10279] opened 2019-05-01 11:26 UTC
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Copy Files

## Environment
- Server - Azure Pipelines or TFS on-premises?
    TFS 16.131.28601.4

## Issue Description

Copy Files V2 unnecessarily enumerates all sub directories, when the pattern match can only match files, causing a big performance hit with lot of sub directories (e.g. node_modules)

I have a build definition with two website projects, one of which uses npm.
For each site we then run Copy Files to match files at the top level with
```
Web*.config
SetParameters*.xml
```
It correctly copies only matching files from the top level, taking 0 seconds on the project without node_modules but 30 seconds in the project with node_modules.

Turning on System.Debug the log has 30 seconds of listing files
2019-04-30T09:44:09.8411001Z ##[debug]findOptions.followSymbolicLinks: 'true'
2019-04-30T09:44:09.8415682Z ##[debug]  C:\Agent\_work\170\s\ANALYSE (directory)
...
2019-04-30T09:44:17.0576222Z ##[debug]  C:\Agent\_work\170\s\ANALYSE\node_modules\@angular\forms\esm5\src\directives (directory)
2019-04-30T09:44:17.0590875Z ##[debug]  C:\Agent\_work\170\s\ANALYSE\node_modules\@angular\forms\esm5\src\directives\abstract_control_directive.js (file)
2019-04-30T09:44:17.0594802Z ##[debug]  C:\Agent\_work\170\s\ANALYSE\node_modules\@angular\forms\esm5\src\directives\abstract_form_group_directive.js (file)
...
2019-04-30T09:44:47.1528957Z ##[debug]  C:\Agent\_work\170\s\ANALYSE\Web.Test.config (file)
2019-04-30T09:44:47.1529236Z ##[debug]74913 results

From https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/CopyFilesV2/copyfiles.ts 
It unconditionally uses `tl.Find(sourceFolder)` so there is no way to exclude the node_modules

Is my best option to just use inline powershell?

**Comment by alexpomsft** [comment] 2019-10-15 10:08
+1.  copyfiles.ts first does a ts.find(sourceFolder), which will pull in all folders recursively, and then applies a tl.match(...).  This is a significantly worse performing algorithm than something like glob or fast-glob which can evaluate, at each directory, whether it should continue or not.  It's unclear to me if CopyFiles could move to glob or if there are special pattern matching reasons why this couldn't be done.  @damccorm can you comment on the feasibility of moving to glob?

**Comment by damccorm** [comment] 2019-11-20 16:30
This is a dupe of the issues we have in the task-lib and also is probably not a bug - there was no performance degradation. I'd say lets follow up in https://github.com/microsoft/azure-pipelines-task-lib/issues/517 and https://github.com/microsoft/azure-pipelines-task-lib/issues/516

**Closed by damccorm** 2019-11-20 16:30 UTC
Labels: Area: Core, bug
