### ISSUE TITLE
Maven@3 task: warning emitted when code coverage not enabled.

### ISSUE THREAD

**Issue by pcaravelli-sr** [microsoft/azure-pipelines-tasks#16520] opened 2022-07-01 18:21 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Maven@3  

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/blob/bd9a0614642be5d471c3fa03905be8fdbd8a190a/Tasks/MavenV3/maventask.ts#L664

## Environment
- Server - Azure Pipelines

## Issue Description
Recent addition of `function replaceImageSourceToBase64()` in Maven@3 task causes irrelevant warning to be emitted when code coverage is not enabled.

I believe this function _should_ only run when code coverage is enabled, but runs regardless; see this code:
https://github.com/microsoft/azure-pipelines-tasks/blob/bd9a0614642be5d471c3fa03905be8fdbd8a190a/Tasks/MavenV3/maventask.ts#L305-L306

The promise returned by `publishCodeCoverage(isCodeCoverageOpted)` is successful even when `isCodeCoverageOpted` is `false`, so `replaceImageSourceToBase64()` will run regardless.

When `replaceImageSourceToBase64()` runs, it calls `path.join(reportDirectory, filename)`, which fails since `reportDirectory` is `null` when code coverage is not enabled.

The root issue seems to be that this `replaceImageSourceToBase64()` function should simply not be executing when code coverage is not asked for.

### Error logs
```
##[warning]Fail to replace images source to base64TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
```

**Comment by hakdogan** [comment] 2022-07-04 14:22
I have same issue,

After using Maven 3.8.3 with JDK 18 in agent, I started seeing the following warning

> ##[warning]Fail to replace images source to base64TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

I temporarily disabled sonarqube analysis, I'm not sure because I didn't try by enabling it but this issue might be related to it.

**Comment by pubudu91** [comment] 2022-07-08 09:59
Getting the same issue when using the `PublishCodeCoverageResults` task for publishing coverage details instead of enabling coverage in the `Maven@3` task. When publishing through the Maven task itself, not getting this warning. Using Maven 3.8.6 and JDK 11.

**Comment by Umutayb** [comment] 2022-07-12 10:07
+

**Comment by anunaykb** [comment] 2022-07-13 06:03
Hello Guys, good morning.
In my case, code coverage is happening through Maven Task itself but getting these warning messages.
Any idea on how to get rid of these warning messages.

**Comment by sanit4u** [comment] 2022-07-13 16:33
#

**Comment by CarlosSaavedra** [comment] 2022-07-13 22:25
following

**Comment by brunojus** [comment] 2022-07-14 05:55
I'm also having this problem and the test pipeline cannot go through. Do you have any news about this bug?

**Comment by fbuser1** [comment] 2022-07-14 07:30
same for me
![image](https://user-images.githubusercontent.com/36403476/178926868-6841845d-ec7a-4c71-b4b7-4e090e72b3e2.png)

**Comment by aparnams1999** [comment] 2022-07-18 08:05
I am also having the same issue.

**Comment by jdantasl** [comment] 2022-07-18 12:25
Complementing..
![image](https://user-images.githubusercontent.com/15002632/179510698-0e950da8-69e6-41a8-a423-263b70115ce9.png)

**Comment by MarkvanOsch** [comment] 2022-07-18 14:07
Same here, using maven task version 3.206.0:
- Maven@3

![image](https://user-images.githubusercontent.com/41586088/179528331-86f32797-4ce5-42be-94b6-7e27e879333b.png)

![image](https://user-images.githubusercontent.com/41586088/179528646-79d188e6-3d7a-4585-ad5f-526e0b89ddce.png)

**Comment by MarkvanOsch** [comment] 2022-07-18 14:25
Confirmed that this issue did not occur in the maven task version 3.205.1. You can use this as a temporary workaround, by pinning the task version:

      - task: Maven@3.205.1

![image](https://user-images.githubusercontent.com/41586088/179532938-011cdfb3-8ddf-4d25-a9ba-dd8f372bdeaa.png)

**Comment by MarkvanOsch** [comment] 2022-07-18 14:26
This pinpoints the issue caused by a change in the Maven task from version 3.205.1 to 3.206.0.

**Comment by fab66m** [comment] 2022-07-21 08:35
I use following workaround: setting codeCoverageToolOption: jaCoCo in the Maven Task seems to suppress the warning. Hope this helps.

**Comment by MarkvanOsch** [comment] 2022-07-21 09:31
Thanks, but that is not working for us as a workaround. With adding codeCoverageToolOption: jaCoCo the code coverage is enabled. And we want to use Maven tasks without code coverage. The issue is the warning for the Maven task when code coverage is not enabled.

**Comment by hakdogan** [comment] 2022-07-21 10:03
Hi @MarkvanOsch, 

> Confirmed that this issue did not occur in the maven task version 3.205.1.

I also confirmed that.

When I explicitly included version 3.205.1  in the pipeline.yaml file, the pipeline did not display the warning.

**Comment by MarkvanOsch** [comment] 2022-07-21 10:41
[max-zaytsev](https://github.com/max-zaytsev) how can this be picked-up? Can we contribute?

I think it could be solved as follows:

```
            publishCodeCoverage(isCodeCoverageOpted).then(function() {
                if (isCodeCoverageOpted) {
                  replaceImageSourceToBase64()
                }
                tl.debug('publishCodeCoverage userRunFailed=' + userRunFailed);

                // 6. If #3 or #4 above failed, exit with an error code to mark the entire step as failed.
                if (userRunFailed || codeAnalysisFailed || codeCoverageFailed) {
                    tl.setResult(tl.TaskResult.Failed, "Build failed."); // Set task failure
                }
                else {
                    tl.setResult(tl.TaskResult.Succeeded, "Build Succeeded."); // Set task success
                }
            })
```

**Comment by jdantasl** [comment] 2022-07-26 20:48
> Confirmed that this issue did not occur in the maven task version 3.205.1. You can use this as a temporary workaround, by pinning the task version:
> 
> ```
>   - task: Maven@3.205.1
> ```
> 
> ![image](https://user-images.githubusercontent.com/41586088/179532938-011cdfb3-8ddf-4d25-a9ba-dd8f372bdeaa.png)

This solution solved it for me!

**Comment by MarkvanOsch** [comment] 2022-07-28 09:49
Waiting for a reviewer to review and approve the PR to fix this issue. #16652

**Comment by max-zaytsev** [comment] 2022-07-29 13:47
Thanks, @MarkvanOsch!
PR was merged. We'll update the thread when this change is deployed.

**Comment by MarkvanOsch** [comment] 2022-07-29 21:08
@max-zaytsev @alexander-smolyakov  thanks for the quick review and approval. Happy I could contribute! 🙂

**Comment by partnerrajshekhar** [comment] 2022-08-05 16:19
-task: Maven@3.205.1 works properly and there is no warning observed. This task is part of normal job.
jobs
-job: 'Build'

But the same task Maven@3.205.1 throws pipeline compilation error "Invalid Task Reference Maven@3.205.1" when used inside **deployment** job

Please suggest any workaround and any timeline update when fix for the same would be availabel so that we use standard task reference Maven@3 .

**Comment by krenson** [comment] 2022-08-10 09:36
Hi everyone, first of all many thanks for the fix provided along 3.209.0 :-)

For a reason I ignore, **maven@3** is still poiting to 3.206.0 and using **maven@3.209.0** does not work. Azure devops is not in a position to retrieve the latest version task ( 3.209.0) despite the fix is part of master branch.

Thank you so much.

**Comment by MarkvanOsch** [comment] 2022-08-10 10:45
I think it's still waiting for deployment? I don't know the timelines or process for that.

https://github.com/microsoft/azure-pipelines-tasks/labels/awaiting%20deployment

**Comment by krenson** [comment] 2022-08-10 10:49
Thank you @MarkvanOsch.

Would somebody know more about that? If it is a matter of 1 or 2 weeks then I'll leave our CI template as they are. Otherwise, I'll go for the temporary suggested workaround. Many thanks!

**Comment by MarkvanOsch** [comment] 2022-08-10 11:15
> max-zaytsev

Hi Max, can you help us by explaining how/when releasing works?

**Comment by max-zaytsev** [comment] 2022-08-10 14:44
Hi @MarkvanOsch , @krenson 

Yes, this will take some time (3-5 weeks)
We'll update this ticket when the fix is deployed.

**Comment by dhamo-pk** [comment] 2022-08-16 13:50
If anyone need a immediate fix, I just downgraded to maven version 2 and it worked (no warning or error). 

Syntax: `- task: Maven@2`

**Comment by cicorias** [comment] 2022-08-31 11:57
What's a simple way to suppress the warning - clearly?

**Comment by MarkvanOsch** [comment] 2022-09-06 15:20
The task version 3.209.0 with the fix should be released anytime now. :-)

If you still need a workaround you can pin the maven task to the last version without this issue:

-task: Maven@3.205.1

**Comment by MarkvanOsch** [comment] 2022-09-11 09:11
@max-zaytsev just wondering if this is the normal lead time? After fix (26 jul) until this is released into production, now waiting almost 7 weeks. Is something special blocking this?

**Comment by MarkvanOsch** [comment] 2022-09-12 18:36
@max-zaytsev
Hi Max, not yet for us. We are using West-Europe.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/41586088/189730325-bb68ee54-d56b-4f71-9ce3-f34c60fd39b8.png">

**Comment by max-zaytsev** [comment] 2022-09-14 09:24
@MarkvanOsch, 
This should be fully deployed. Could you check now?

**Comment by MarkvanOsch** [comment] 2022-09-14 09:37
[max-zaytsev](https://github.com/max-zaytsev) Yes! Confirmed that we are now using 3.209.0 ánd that the issue is fixed!

![image](https://user-images.githubusercontent.com/41586088/190119004-9683627f-d88f-435a-b4ba-e81adc2e7f84.png)

Thanks for you help with this.

**Comment by max-zaytsev** [comment] 2022-09-14 09:51
@MarkvanOsch Thank you for confirmation! I'm closing this issue 😊

**Closed by max-zaytsev** 2022-09-14 09:51 UTC
Labels: bug, Area: ABTT, Task: Maven
