### ISSUE TITLE
Docker json_key gets logged

### ISSUE THREAD

**Issue by LanceSandino** [microsoft/azure-pipelines-tasks#14322] opened 2021-02-01 17:12 UTC
Environment: Azure DevOps Cloud 

``` - task: Docker@2
    displayName: 'Docker Login'
    inputs:
      containerRegistry: 'gcr'
      command: 'login'
      addPipelineData: false
    condition: eq(variables.isDeployable, true)
```

JSON key is logged verbose
![image](https://user-images.githubusercontent.com/1300195/106493002-3737e900-647e-11eb-8ac3-0560c3cf9394.png)

Happens on other commands like `buildAndPush` as well

**Comment by LanceSandino** [comment] 2021-02-25 19:58
bump

**Comment by chshrikh** [comment] 2021-03-17 04:13
@ds-ms please route this

**Comment by LanceSandino** [comment] 2021-05-03 19:42
bump

**Comment by LanceSandino** [comment] 2021-09-30 01:58
Bump

**Comment by rovangju** [comment] 2022-02-15 16:21
Bump....

**Comment by TomasHubelbauer** [comment] 2022-04-05 14:42
Hi @LanceSandino, can you please provide details of the way the Docker service connection is set up in Azure DevOps? Are you using `_json_key` for Docker ID and the contents of `azure-pipelines-publisher-oneline.json` for the Docker password to log in to GCR? I am looking at removing the logs that end up printing the subsequent lines of the secret other than the first by reopening and merging @ryanhatfield's PR, but first I want to make sure I understand the issue here fully. Thank you

**Comment by TomasHubelbauer** [comment] 2022-04-13 13:08
I was not able to reproduce creating a SC with a multi-line password through the UI or the API and I see that GCR now offer the single-line version by default, but I still merged the PR which removes the logs that print the secrets. That should solve this.

**Closed by TomasHubelbauer** 2022-04-13 13:08 UTC
Labels: Area: Release, triage
