### ISSUE TITLE
Download Pipeline Artifact - wrong match pattern

### ISSUE THREAD

**Issue by arek-avanade** [microsoft/azure-pipelines-tasks#10197] opened 2019-04-24 09:36 UTC
**Type**: bug

**Enter Task Name**: Download Pipeline Artifact uses wrong match pattern  

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description
When the build pipeline produces multiple artifacts and we want to choose just a few of them in the release pipeline, the artifact is not downloaded because of a wrong file match pattern. In the sample below out of 3 artifacts we chose 2: IPA and dSYM. Observe how the minimatch pattern tries to filter files which are ALREADY filtered when downloading IPA artifact from the build pipeline:

```
2019-04-24T07:39:45.4941191Z ##[section]Starting: Download artifact - xxx-CI - IPA
2019-04-24T07:39:45.7521007Z ====================================================================
2019-04-24T07:39:45.7521146Z Task         : Download Pipeline Artifact
2019-04-24T07:39:45.7521213Z Description  : Download Pipeline Artifact
2019-04-24T07:39:45.7521253Z Version      : 1.1.0
2019-04-24T07:39:45.7521292Z Author       : Microsoft Corporation
2019-04-24T07:39:45.7521799Z Help         : Download named artifact from a pipeline to a local path.
2019-04-24T07:39:45.7521847Z ====================================================================
2019-04-24T07:39:47.0049211Z Download artifact to: d:\a\r1\a/xxx-CI/IPA
2019-04-24T07:39:47.7342021Z Information, Minimatch patterns: [IPA/**,dSYM/**]
2019-04-24T07:39:48.1065063Z Information, Filtered 0 files from the Minimatch filters supplied.
2019-04-24T07:39:48.1842303Z Information, Could not initialize dataport.
2019-04-24T07:39:48.2058422Z Information, Downloaded 0.0 MB out of 0.0 MB (100%).
2019-04-24T07:39:48.2744416Z Information, Downloaded 0.0 MB out of 0.0 MB (100%).
2019-04-24T07:39:48.2745688Z Information, Download completed.
```

Here's an example when ALL artifacts are selected for download. Note the minimatch pattern correctly assumes ** pattern here:

```
2019-04-24T09:22:23.4140803Z ##[section]Starting: Download artifact - xxx-CI - IPA
2019-04-24T09:22:23.9883092Z ====================================================================
2019-04-24T09:22:23.9883237Z Task         : Download Pipeline Artifact
2019-04-24T09:22:23.9883289Z Description  : Download Pipeline Artifact
2019-04-24T09:22:23.9883350Z Version      : 1.1.0
2019-04-24T09:22:23.9883397Z Author       : Microsoft Corporation
2019-04-24T09:22:23.9883447Z Help         : Download named artifact from a pipeline to a local path.
2019-04-24T09:22:23.9883955Z ====================================================================
2019-04-24T09:22:25.0558180Z Download artifact to: d:\a\r1\a/xxx-CI/IPA
2019-04-24T09:22:25.9683139Z Information, Minimatch patterns: [**]
2019-04-24T09:22:28.3661439Z Information, Filtered 1 files from the Minimatch filters supplied.
2019-04-24T09:22:28.4508002Z Information, Could not initialize dataport.
2019-04-24T09:22:28.4763131Z Information, Downloaded 0.0 MB out of 29.4 MB (0%).
2019-04-24T09:22:33.4876794Z Information, Downloaded 11.9 MB out of 29.4 MB (40%).
2019-04-24T09:22:38.4879766Z Information, Downloaded 28.1 MB out of 29.4 MB (95%).
2019-04-24T09:22:38.7073250Z Information, Downloaded 29.4 MB out of 29.4 MB (100%).
2019-04-24T09:22:38.7073579Z Information, Download completed.
```

**Comment by mitchdenny** [comment] 2019-04-25 04:15
@fadnavistanmay

**Comment by fadnavistanmay** [comment] 2019-04-25 19:21
Ack. So @arek-avanade , you are trying to download just a single artifact, right? And you need all the files in that artifact ( IPA ), the you don't need to give any minimatch pattern. @owenhuynMSFT - FYI. From what I understand, the minimatch pattern will be applicable to all the artifacts.

**Comment by arek-avanade** [comment] 2019-04-26 07:12
@fadnavistanmay In the first case I chose 2 artifacts in the DevOps UI: IPA and dSYM. Here's how it looks like:
![Screenshot 2019-04-26 at 09 09 00](https://user-images.githubusercontent.com/35216537/56789762-02a3f180-6803-11e9-9207-90ee76a4ee7b.png)
I haven't provided any match patterns myself, but each artifact is downloaded individually in the pipeline and it uses the pattern [IPA/**,dSYM/**]. I think the problem is that even though the artifacts are downloaded one-by-one, the pattern tries to filter them out based on my selection even though we are already downloading them individually based on my selection.

**Comment by Rzpeg** [comment] 2019-05-02 14:30
We are hitting the same issue.
Is there any ETA for fix ?

**Comment by fadnavistanmay** [comment] 2019-05-03 00:06
@Rzpeg , sorry for the delay, we are looking into the issue. @omeshp - Could you help here please. Looks like, when the user is selecting a particular artifact to download in RM, the itemPattern (minimatch ) is being set a <artifactName>/** for each artifact, instead of just **. This scenario works in build pipelines (multidownload). Are we adding artifactName to the minimatchPattern in RM?

**Comment by omeshp** [comment] 2019-05-03 05:28
@fadnavistanmay Yes, we are adding the artifactname to item patterns at injection time. But I don't see why that should break the download if task is handling the patterns correctly.

**Comment by Rzpeg** [comment] 2019-05-03 11:39
@Rzpeg thanks for the followup.

**Comment by fadnavistanmay** [comment] 2019-05-03 16:32
Hello @omeshp , basically, the minimatch pattern is going in as "<artifactname>/**" instead of "**" -> so the logic is searching for files that match "<artifactName>/**" instead of "**", hence it's failing. Could you please remove adding the artifactname logic in the injection. 
Thanks,
Tanmay

**Comment by omeshp** [comment] 2019-05-06 05:54
@fadnavistanmay The issue here isn't adding artifactname at injection time, we do the same thing for server build artifact. The issue is how the pattern is handled in the download task. If a pattern like artifactname/** is sent to "Download Pipeline Artifacts" task it skips downloading all the files, on the other hand same pattern works with "Download Build Artifacts" task. Below are the snapshots where it works for one task and not the other:

Working: https://panditaomesh.visualstudio.com/Project1/_build/results?buildId=15101&_a=summary&view=logs
![image](https://user-images.githubusercontent.com/11783897/57208288-b6219880-6ff0-11e9-811b-4321cb316c30.png)

Not Working: https://panditaomesh.visualstudio.com/Project1/_build/results?buildId=15100 
![image](https://user-images.githubusercontent.com/11783897/57208327-e36e4680-6ff0-11e9-8312-bf664a955e04.png)

**Comment by Rzpeg** [comment] 2019-05-09 09:45
@omeshp @fadnavistanmay
Is there any progress on the issue ?
Downloading all artifacts is, for some reason, is very slow on Azure Pipelines, the first 5-6 artifacts are downloaded fast (3-10 seconds per 100-200 mb artifact) and the rest take up to 2-4 minutes each, with constant errors (below). The issue is causing the deployment process to take close to 30 minutes instead of 5-6 for all our artifacts.
```
2019-05-07T13:49:01.0066053Z Warning, [https://nu4vsblobprodsu6weus57.blob.core.windows.net/dbe63b98307635479db31e89f778704d55/033FF830F3465DF12ADDC8425DEB5CAFE8532A99D76DF502EC98D4F5756AA15201?sv=2017-04-17&sr=b&sig=tKvyEytyCaGn6QxFf4wrTuX24sltRHXqmgy%2FvsuRBJA%3D&spr=https&se=2019-05-07T16%3A01%3A33Z&sp=r&rscl=x-e2eid-7190cd7e-d8ed40c3-90c41c74-43c0bf4a-session-fbcd7455-c21842f0-9e2e7d15-31d925a5] Try 1/5, retryable exception caught. Retrying in 00:00:01. Details:
2019-05-07T13:49:01.0066512Z Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called? System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The operation timed out'.
2019-05-07T13:49:01.0066733Z    at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
2019-05-07T13:49:01.0066819Z    at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state)
2019-05-07T13:49:01.0066920Z    --- End of inner exception stack trace ---
2019-05-07T13:49:01.0067015Z    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-05-07T13:49:01.0067195Z    at Microsoft.VisualStudio.Services.Common.TaskCancellationExtensions.EnforceCancellation[TResult](Task`1 task, CancellationToken cancellationToken, Func`1 makeMessage, String file, String member, Int32 line)
2019-05-07T13:49:01.0067341Z    at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreHttpClient.<>c__DisplayClass56_0.<<GetRedirectResponseAsync>b__0>d.MoveNext()
2019-05-07T13:49:01.0067435Z --- End of stack trace from previous location where exception was thrown ---
2019-05-07T13:49:01.0067547Z    at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
```

**Comment by omeshp** [comment] 2019-05-09 10:04
@Rzpeg Sorry for the inconvenience, we are working on the fix and will get it deployed to your account by next week.

**Comment by Rzpeg** [comment] 2019-05-09 10:06
@omeshp Thanks for the ETA.
I have created another issue for the timeouts during artifact download: #10343

**Comment by Rzpeg** [comment] 2019-05-23 14:02
@omeshp has it been fixed in production yet ?

**Comment by omeshp** [comment] 2019-05-23 14:08
Hi @Rzpeg , Yes the fix has been deployed to the production. Let us know if you are still facing the issue.

**Comment by Rzpeg** [comment] 2019-05-23 14:23
@omeshp seems to be working now! Deployment time reduced by the whoping 70%.
Thanks!

**Comment by omeshp** [comment] 2019-05-25 09:15
@Rzpeg Thanks for the confirmation!

**Closed by omeshp** 2019-05-25 09:15 UTC
Labels: Area: Artifacts, bug
