### ISSUE TITLE
Unable to Connect to AzureUSGovernment using an MSI

### ISSUE THREAD

**Issue by zamasiel** [microsoft/azure-pipelines-tasks#14673] opened 2021-03-31 19:50 UTC
## Required Information

**Question, Bug, or Feature?**  
Bug

**Enter Task Name:**  
Common/VstsAzureHelpers_/InitializeAzModuleFunctions

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/VstsAzureHelpers_/InitializeAzModuleFunctions.ps1

## Environment
Azure Pipelines

- Agent - Private: 
Agent Version: 2.182.1
Agent OS Version: 10.0.17763

## Issue Description

When using an MSI to connect to AzureUSGovernment it fails as the command doesn't have the Environment Flag

### Task logs
Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
Clear-AzContext -Scope Process
Connect-AzAccount -Identity @processScope
Set-AzContext -SubscriptionId *** -TenantId ***
##[error]Please provide a valid tenant or a valid subscription.
##[error]PowerShell exited with code '1'.

**Comment by AmrutaKawade** [comment] 2021-04-06 10:57
Its duplicate of this issue https://github.com/microsoft/azure-pipelines-tasks/issues/14176 and there is already PR raised for this https://github.com/microsoft/azure-pipelines-tasks/pull/14533 hence closing this issue

**Closed by AmrutaKawade** 2021-04-06 10:57 UTC
Labels: Area: Release, environment:need-to-triage, triage
