### ISSUE TITLE
Allow passing --allow-no-subscriptions to AzureCLIV2

### ISSUE THREAD

**Issue by a-vishar** [microsoft/azure-pipelines-tasks#12338] opened 2020-02-11 21:59 UTC
**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: AzureCLI

## Environment
Azure Pipelines - Feature Request, so no specifics of my pipelines required

- Agent - Hosted or Private: 
Hosted - Feature Request, so no specifics of my pipelines required

## Issue Description

I use a service principal which is an Azure Management Group.  This works great for my needs (cross subscription infra management), however, it fails transiently...

### Task logs

This is a transient failure, so full task logs with debugging enabled are difficult to come by.

### Error logs

`2020-02-11T20:45:51.1033867Z ##[section]Starting: Add SQL Firewall Exception
2020-02-11T20:45:51.1159270Z ==============================================================================
2020-02-11T20:45:51.1159396Z Task         : Azure CLI
2020-02-11T20:45:51.1163799Z Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/Powershell Core/Batch script when running on Windows agent.
2020-02-11T20:45:51.1163958Z Version      : 2.0.5
2020-02-11T20:45:51.1164028Z Author       : Microsoft Corporation
2020-02-11T20:45:51.1164127Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
2020-02-11T20:45:51.1164231Z ==============================================================================
2020-02-11T20:45:51.5499272Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2020-02-11T20:46:12.5295562Z WARNING: You have 2 updates available. Consider updating your CLI installation. Instructions can be found at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
2020-02-11T20:46:12.5295985Z azure-cli                         2.0.80 *
2020-02-11T20:46:12.5296621Z 
2020-02-11T20:46:12.5296891Z command-modules-nspkg              2.0.3
2020-02-11T20:46:12.5297188Z core                              2.0.80 *
2020-02-11T20:46:12.5297376Z nspkg                              3.0.4
2020-02-11T20:46:12.5297571Z telemetry                          1.0.4
2020-02-11T20:46:12.5297717Z 
2020-02-11T20:46:12.5297891Z Extensions:
2020-02-11T20:46:12.5298192Z azure-devops                      0.17.0
2020-02-11T20:46:12.5298353Z 
2020-02-11T20:46:12.5298539Z Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
2020-02-11T20:46:12.5298773Z Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'
2020-02-11T20:46:12.5298945Z 
2020-02-11T20:46:12.5299160Z Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
2020-02-11T20:46:12.5299338Z 
2020-02-11T20:46:12.5338134Z Legal docs and information: aka.ms/AzureCliLegal
2020-02-11T20:46:12.5411519Z 
2020-02-11T20:46:12.5433304Z 
2020-02-11T20:46:12.5776052Z 
2020-02-11T20:46:12.8130199Z 
2020-02-11T20:46:12.8153854Z Please let us know how we are doing: https://aka.ms/clihats
2020-02-11T20:46:12.8161347Z Setting AZURE_CONFIG_DIR env variable to: d:\a\_temp\.azclitask
2020-02-11T20:46:12.8161980Z Setting active cloud to: AzureCloud
2020-02-11T20:46:12.8164997Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n AzureCloud"
2020-02-11T20:46:19.8051081Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u *** -p *** --tenant ***"
2020-02-11T20:46:22.9638827Z ERROR: No subscriptions were found for '***'. If this is expected, use '--allow-no-subscriptions' to have tenant level access
2020-02-11T20:46:22.9728798Z ##[error]Error Code: [1]
2020-02-11T20:46:22.9739460Z ##[error]Error: Azure login failed
2020-02-11T20:46:22.9739972Z ##[error]Script failed with error: ERROR: No subscriptions were found for '***'. If this is expected, use '--allow-no-subscriptions' to have tenant level access

2020-02-11T20:46:22.9775929Z ##[section]Finishing: Add SQL Firewall Exception`

**Comment by mbrancato** [comment] 2020-02-11 22:59
Duplicate of #11846

**Closed** 2020-05-01 20:15 UTC
Labels: Area: Release, enhancement
