### ISSUE TITLE
DotNetCoreCLI@2: Zip after publish doesn't work for solution

### ISSUE THREAD

**Issue by monnecc** [microsoft/azure-pipelines-tasks#12449] opened 2020-02-28 16:32 UTC
In the task DotNetCoreCLI@2, zipping of publish output only works if you provide a project (csproj) as an argument and not with the solution. If I provide the solution as an argument only one of my published projects gets zipped.

See dotnetcore.ts, function zipAfterPublishIfRequired. There is no iteration through projects or publish folders.

**Comment by anuragc617** [comment] 2020-03-02 10:34
Hi @monnecc, have you selected `Publish Web Projects` checkbox? If yes,  then the task will zip and publish all the projects . If not, then you will have to specify the path for desired csproj like `**/*.csproj` in the `Path to project(s)` input not the solution as this input is used as pattern to find out the projects. Can you try this out?

**Comment by monnecc** [comment] 2020-03-02 13:37
Hi, it works indeed with the **/*.csproj pattern. I have to set Publish Web Projects to false by the way. It would be better though if it worked with the solution as an argument just like all other operations with the dotnet command.

**Comment by anuragc617** [comment] 2020-03-03 05:43
Hi @monnecc setting Publish Web Projects to true and without passing solution as an argument should also work. Where are you giving the solution argument?

**Comment by monnecc** [comment] 2020-03-03 08:55
Hi, I’m giving the solution as an argument to the ‘projects’ parameter as described in the documentation of dotnet.cmd.

**Comment by anuragc617** [comment] 2020-03-03 12:45
@monnecc by design of the task, inputs you pass in the arguments field are not used to search for the projects. Also we don't support **\*.sln  in projects input. 
I am closing this issue as you are unblocked on this.

**Closed by anuragc617** 2020-03-03 12:45 UTC
Labels: Area: Release, triage
