### ISSUE TITLE
[DTS 1716250] DTS [Pipelines]: Task CopyFilesOverSSH SSH service connection Unsupported key format

### ISSUE THREAD

**Issue by leantk** [microsoft/azure-pipelines-tasks#12905] opened 2020-05-14 18:48 UTC
Please look at DTS 1716250 that has been opened here:
https://dev.azure.com/mseng/_workitems/edit/1716250

**Comment by anatolybolshakov** [comment] 2020-05-28 08:51
Duplicate of #12

**Closed by anatolybolshakov** 2020-05-28 08:51 UTC
Labels: Area: ABTT, P1
