### ISSUE TITLE
Support of openapi is missing in Azure PowerShell task

### ISSUE THREAD

**Issue by aleksey-korolev** [microsoft/azure-pipelines-tasks#10887] opened 2019-07-12 22:15 UTC
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  Azure PowerShell

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/esl-digest/digest-dev/_build/results?buildId=79

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: Hosted Windows 2019 with VS2019

## Issue Description

I'm using Azure PowerShell task v 4.* to import API defined using openapi format.
I know this format is supported in most recent Az versions, see [PsApiManagementApiFormat ](https://github.com/Azure/azure-powershell/blob/2bddfe5bed625db30e8b0c2d67efb825accf5258/src/ApiManagement/ApiManagement.ServiceManagement/Models/PsApiManagementApiFormat.cs) enumeration.

Possible solution to this issue would be installation of most recent release of Az Powershell module at the beginning of this task. At least this is the workaround solution we had to go with using regular "Powershell Script" task.

### Error logs

>Starting: Azure PowerShell script: FilePath import-api
> ==============================================================================
> Task         : Azure PowerShell
> Description  : Run a PowerShell script within an Azure environment
> Version      : 4.154.3
> Author       : Microsoft Corporation
> Help         : [Learn more about this task](https://go.microsoft.com/fwlink/?LinkID=613749)
> ==============================================================================
> ##[command]Import-Module -Name C:\Modules\az_1.6.0\Az.Accounts\1.5.0\Az.Accounts.psd1 -Global
> ##[warning]Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide
> ##[command]Clear-AzContext -Scope Process
> ##[command]Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
> ##[command]Connect-AzAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud
> ##[command] Set-AzContext -SubscriptionId cd4553fc-0d76-408c-85d3-3427721ef749 -TenantId ***
> ##[command]& 'd:\a\1\s\misc\api-management\import-api.ps1' 
> ##[command]Disconnect-AzAccount -Scope Process -ErrorAction Stop
> ##[command]Clear-AzContext -Scope Process -ErrorAction Stop
> ##[error]Cannot bind parameter 'SpecificationFormat'. Cannot convert value "openapi" to type "Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Models.PsApiManagementApiFormat". Error: "Unable to match the identifier name openapi to a valid enumerator name. Specify one of the following enumerator names and try again:
> Wadl, Swagger, Wsdl"

**Comment by kmkumaran** [comment] 2019-07-14 11:20
The [PR ](https://github.com/microsoft/azure-pipelines-image-generation/pull/1075) updates the script for installing latest Az module (2.3.2). This will be made available as part of the next hosted image roll-out.

+ @20shivangi for further queries on this regard.

**Comment by ramosjacc** [comment] 2019-07-17 00:52
@20shivangi is there any information on when the update to the hosted images is going to be rolled out?

**Comment by 20shivangi** [comment] 2019-07-17 04:42
@ramosjacc Update to the hosted image will get rolled out within 3 weeks

**Comment by aleksey-korolev** [comment] 2019-07-17 16:15
> This PR  updates the script for installing latest Az module (2.3.2) in hosted agents. This will be made available as part of the next hosted image roll-out.
> 
> @20shivangi for further queries on this regard.

Could you let me know when is the next hosted image roll-out planned?

**Comment by 20shivangi** [comment] 2019-07-18 03:59
@aleksey-korolev Update to the hosted image will get rolled out within 3 weeks. Please wait for three weeks.

**Comment by rajatagrawal-dev** [comment] 2019-07-23 05:51
Closing as the the issue is fixed and will roll out with next scheduled release.
Please reopen if the issue is not resolved in the expected time (2-3 weeks)

**Closed by rajatagrawal-dev** 2019-07-23 05:51 UTC
Labels: Area: Release, bug
