### ISSUE TITLE
Jenkins V2 Task through's 403 for job completion status

### ISSUE THREAD

**Issue by karann-jain** [Microsoft/azure-pipelines-tasks#9072] opened 2018-12-13 08:48 UTC
## Environment
- Server - Azure Pipelines
- Agent - Private (linux): 

## Issue Description

We started seeing these errors yesterday. Job is being queued fine but while it waits for completion status the steps are failing.
### Task logs

Job progress tracking failed to read job progress
[error]Job progress tracking failed to read job progress
HttpResponse.statusCode=403
HttpResponse.statusMessage=Forbidden
[error]Job progress tracking failed to read job progress
Job progress tracking failed to read job progress
[error]Job progress tracking failed to read job progress
HttpResponse.statusCode=403
HttpResponse.statusMessage=Forbidden
[error]Job progress tracking failed to read job progress
Job progress tracking failed to read job progress
[error]Job progress tracking failed to read job progress
HttpResponse.statusCode=403
HttpResponse.statusMessage=Forbidden
[error]Job progress tracking failed to read job progress

I suspect the code changes here are causing issue https://github.com/Microsoft/azure-pipelines-tasks/commit/9bd433aac23f6ea29411c6dda6334a0e73115154

**Comment by gandhiprachi** [comment] 2018-12-14 00:47
Seeing the same issue in our pipelines. Things were fine until y'day.

**Comment by JSRunning** [comment] 2018-12-14 04:14
Our pipelines experienced this issue starting this morning as well. I've reverted our usage of the Jenkins Queue Job task to 1.x for the time being, and that seems to be working as expected.  Hopefully this issue will be addressed soon.

**Comment by gandhiprachi** [comment] 2018-12-14 04:16
Yea its annoying especially if theres a lot of pipelines using this task.

**Comment by SwanseaUniveristy** [comment] 2018-12-17 11:13
@kelliejos  Thanks for the fix, do you know when this is going to be released as it's causing a lot of issues for us and can't revert back to version 1 as we need the output variable included in version 2. 
Thanks

**Comment by madhurig** [comment] 2018-12-18 14:14
Fix was deployed over the weekend, please let us know if you still see issues.

**Closed by madhurig** 2018-12-18 14:14 UTC
Labels: Area: Release

**Comment by gandhiprachi** [comment] 2018-12-18 15:09
@madhurig  - is there a way of figuring out that a fix was deployed from github?

**Comment by madhurig** [comment] 2018-12-18 15:31
@gandhiprachi - Sorry we don't have a way of tracking that on GitHub or externally today. We apologize for the inconvenience but are constantly looking to have more transparency in our process. 

Thanks,
Madhuri

**Comment by JSRunning** [comment] 2018-12-18 16:19
I tested this yesterday and I can confirm that it is indeed fixed.
