### ISSUE TITLE
npm Authenticate task failing TypeError: Cannot read property 'retrieveSecret' of undefined

### ISSUE THREAD

**Issue by justinmwarner** [microsoft/azure-pipelines-tasks#6854] opened 2018-04-02 14:25 UTC
## Troubleshooting
Done

## Environment
- Server - VSTS or TFS on-premises?
    
N/A

- Agent - Hosted or Private: 
    
N/A

## Issue Description

Running npm authenticate finds the npmrc file but fails to run saying ```TypeError: Cannot read property 'retrieveSecret' of undefined```

As a note, this worked without any changes on Friday. 

### Error logs

> 
> 2018-04-02T14:00:59.7935943Z ##[debug]Evaluating condition for step: 'npm Authenticate'
> 2018-04-02T14:00:59.7935943Z ##[debug]Evaluating: succeeded()
> 2018-04-02T14:00:59.7935943Z ##[debug]Evaluating succeeded:
> 2018-04-02T14:00:59.7935943Z ##[debug]=> (Boolean) True
> 2018-04-02T14:00:59.7935943Z ##[debug]Expanded: True
> 2018-04-02T14:00:59.7935943Z ##[debug]Result: True
> 2018-04-02T14:00:59.7935943Z ##[section]Starting: npm Authenticate
> 2018-04-02T14:00:59.7935943Z ==============================================================================
> 2018-04-02T14:00:59.7935943Z Task         : npm Authenticate (for task runners)
> 2018-04-02T14:00:59.7935943Z Description  : Don't use this task if you're also using the npm task. Provides npm credentials to an .npmrc file in your repository for the scope of the build. This enables npm task runners like Gulp and Grunt to authenticate with private registries.
> 2018-04-02T14:00:59.7935943Z Version      : 0.0.1
> 2018-04-02T14:00:59.7935943Z Author       : Microsoft Corporation
> 2018-04-02T14:00:59.7935943Z Help         : 
> 2018-04-02T14:00:59.7935943Z ==============================================================================
> 2018-04-02T14:01:00.0436262Z ##[debug]agent.workFolder=F:\agent\_work
> 2018-04-02T14:01:00.0436262Z ##[debug]loading inputs and endpoints
> 2018-04-02T14:01:00.0436262Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
> 2018-04-02T14:01:00.0436262Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
> 2018-04-02T14:01:00.0436262Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
> 2018-04-02T14:01:00.0436262Z ##[debug]loading INPUT_WORKINGFILE
> 2018-04-02T14:01:00.0436262Z ##[debug]loading SECRET_TSBLOBKEY
> 2018-04-02T14:01:00.0436262Z ##[debug]loaded 5
> 2018-04-02T14:01:00.2623836Z ##[debug]check path : F:\agent\_work\_tasks\npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788\0.0.1\task.json
> 2018-04-02T14:01:00.2623836Z ##[debug]set resource file to: F:\agent\_work\_tasks\npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788\0.0.1\task.json
> 2018-04-02T14:01:00.2623836Z ##[debug]system.culture=en-US
> 2018-04-02T14:01:00.2623836Z ##[debug]workingFile=<FILE_PATH>\.npmrc
> 2018-04-02T14:01:00.2623836Z Adding authentication to the .npmrc file at F:\agent\_work\40\s\<FILE_PATH>\.npmrc
> 2018-04-02T14:01:00.2623836Z ##[debug]SAVE_NPMRC_PATH=undefined
> 2018-04-02T14:01:00.2623836Z ##[debug]Agent.BuildDirectory=F:\agent\_work\40
> 2018-04-02T14:01:00.2623836Z ##[debug]testing directory 'F:\agent\_work\40\npmAuthenticate'
> 2018-04-02T14:01:00.2623836Z ##[debug]set SAVE_NPMRC_PATH=F:\agent\_work\40\npmAuthenticate\zI982M
> 2018-04-02T14:01:00.2623836Z ##[debug]Processed: ##vso[task.setvariable variable=SAVE_NPMRC_PATH;issecret=false;]F:\agent\_work\40\npmAuthenticate\zI982M
> 2018-04-02T14:01:00.2623836Z ##[debug]set NPM_AUTHENTICATE_TEMP_DIRECTORY=F:\agent\_work\40\npmAuthenticate
> 2018-04-02T14:01:00.2623836Z ##[debug]Processed: ##vso[task.setvariable variable=NPM_AUTHENTICATE_TEMP_DIRECTORY;issecret=false;]F:\agent\_work\40\npmAuthenticate
> 2018-04-02T14:01:00.2779842Z ##[warning]Resource file haven\'t set, can\'t find loc string for key: SavingFile
> 2018-04-02T14:01:00.2779842Z ##[debug]Processed: ##vso[task.issue type=warning;]Resource file haven\'t set, can\'t find loc string for key: SavingFile
> 2018-04-02T14:01:00.2779842Z ##[debug]SavingFile F:\agent\_work\40\s\<FILE_PATH>\.npmrc
> 2018-04-02T14:01:00.2779842Z ##[debug]customEndpoint=null
> 2018-04-02T14:01:00.2779842Z ##[debug]Npm.PackagingCollectionUrl=undefined
> 2018-04-02T14:01:00.2779842Z ##[debug]System.TeamFoundationCollectionUri=https://<VSTS_URL>.visualstudio.com/
> 2018-04-02T14:01:00.2936119Z ##[warning]Resource file haven\'t set, can\'t find loc string for key: FoundLocalRegistries
> 2018-04-02T14:01:00.2936119Z ##[debug]Processed: ##vso[task.issue type=warning;]Resource file haven\'t set, can\'t find loc string for key: FoundLocalRegistries
> 2018-04-02T14:01:00.2936119Z ##[debug]FoundLocalRegistries 1
> 2018-04-02T14:01:00.2936119Z ##[debug]Agent.BuildDirectory=F:\agent\_work\40
> 2018-04-02T14:01:00.2936119Z ##[debug]testing directory 'F:\agent\_work\40\npm'
> 2018-04-02T14:01:00.2936119Z ##[debug]testing directory 'F:\agent\_work\40'
> 2018-04-02T14:01:00.2936119Z ##[debug]mkdir 'F:\agent\_work\40\npm'
> 2018-04-02T14:01:00.2936119Z ##[debug]rm -rf F:\agent\_work\40\npm
> 2018-04-02T14:01:00.2936119Z ##[debug]removing directory
> 2018-04-02T14:01:00.2936119Z ##[debug]task result: Failed
> 2018-04-02T14:01:00.2936119Z ##[error]TypeError: Cannot read property 'retrieveSecret' of undefined
> 2018-04-02T14:01:00.2936119Z ##[debug]Processed: ##vso[task.issue type=error;]TypeError: Cannot read property 'retrieveSecret' of undefined
> 2018-04-02T14:01:00.2936119Z ##[debug]Processed: ##vso[task.complete result=Failed;]TypeError: Cannot read property 'retrieveSecret' of undefined
> 2018-04-02T14:01:00.2936119Z ##[section]Finishing: npm Authenticate

**Comment by justinmwarner** [comment] 2018-04-03 13:23
Just an update, this is no longer repro this morning.

Feel free to close and take any action if investigation is worthwhile.

**Comment by justinmwarner** [comment] 2018-04-03 15:13
Another update, we're seeing this again.  So disregard my previous message.

**Comment by jmyersmsft** [comment] 2018-04-03 16:32
@bryanmacfarlane it looks from this log that the state of the task lib is getting cleared out somehow.
* The log says "Resource file haven't set", but that's the first thing the task does at Tasks\NpmAuthenticate\npmauth.ts:12 (and there's a corresponding "set resource file to" line in the log)
* The stack where the TypeError is coming from is most likely (reasoned out by inspection):
  * task.getEndpointAuthorization at [vsts-task-lib/node/task.ts:376](https://github.com/Microsoft/vsts-task-lib/blob/6c3c61d845b45024a4057bd88168ef6a87d617d0/node/task.ts#L376)
  * util.getSystemAcessToken at [vsts-tasls/Tasks/Common/npm-common/util.ts:151](https://github.com/Microsoft/vsts-tasks/blob/cff88e57e2b593da9a060a1faf3ebc3eb52d4fe3/Tasks/Common/npm-common/util.ts#L151)
  * util.getFeedRegistryUrl at [vsts-tasks/Tasks/Common/npm-common/util.ts:178](https://github.com/Microsoft/vsts-tasks/blob/cff88e57e2b593da9a060a1faf3ebc3eb52d4fe3/Tasks/Common/npm-common/util.ts#L178)
  * npmregistry.NpmRegistry.FromFeedId at [vsts-tasks/Tasks/Common/npm-common/npmregistry.ts:99](https://github.com/Microsoft/vsts-tasks/blob/cff88e57e2b593da9a060a1faf3ebc3eb52d4fe3/Tasks/Common/npm-common/npmregistry.ts#L99)
  * util.getLocalNpmRegistries at [vsts-tasks/Tasks/Common/npm-common/util.ts:51](https://github.com/Microsoft/vsts-tasks/blob/cff88e57e2b593da9a060a1faf3ebc3eb52d4fe3/Tasks/Common/npm-common/util.ts#L51)
  * main at [vsts-tasks/Tasks/NpmAuthenticate/npmauth.ts:65](https://github.com/Microsoft/vsts-tasks/blob/cff88e57e2b593da9a060a1faf3ebc3eb52d4fe3/Tasks/NpmAuthenticate/npmauth.ts#L65)
  * [vsts-tasks/Tasks/NpmAuthenticate/npmauth.ts:107](https://github.com/Microsoft/vsts-tasks/blob/cff88e57e2b593da9a060a1faf3ebc3eb52d4fe3/Tasks/NpmAuthenticate/npmauth.ts#L107)

The variable with the undefined value is the task lib's secrets vault. The string retrieveSecret does not exist within the NpmAuthenticate task (or anywhere in the vsts-tasks repo except .d.ts files for that matter)

**Comment by justinmwarner** [comment] 2018-04-03 20:07
We're seeing this on another repo as well.  Same error message.

**Comment by charleszipp** [comment] 2018-10-18 16:48
I fought with this issue quite a bit today and i think i figured out what caused it @jmyersmsft and @justinmwarner 

If you import the vsts-task-tool-lib/tool before vsts-task-lib/task then this error is reproduced. If i switch the order to load vsts-task-lib/task first then the error goes away.

I noticed that the vsts-task-tool-lib/tool module takes a dependency on vsts-task-lib. Since there is some global state being kept within the vsts-task-lib module (global['_vsts_task_lib_loaded']) then i suspected this may be causing the state data to not get loaded properly if another dependency invoked the module. To test this, i flipped the import order and it resolved the issue.

**Comment by estatic** [comment] 2019-04-12 08:34
We have the same problem on all our repositories

**Comment by steevegldev** [comment] 2019-04-12 14:26
Seems to be a regression, was working few days ago. Noticed it happening this morning.

**Comment by grantal** [comment] 2019-04-12 20:05
Yep also happened to me. Build succeeded on 4/2 and then today it failed with no change to the repo.

**Comment by jpenniman** [comment] 2019-04-12 21:02
Same here. It has been working for us, and started receiving this error this afternoon.

**Comment by steevegldev** [comment] 2019-04-12 21:03
In my case I'm using Twine authentication for python but the issue is the same.

I tried to:
- Clear and recreate Azure Agent
- Recreate the task (thru the UI)
- Manual authentication

As this issue is **major**, it would be appreciate a faster investigation or point-out the right place to raise that. 

A workaround is required ASAP, because uploading artifact is broken!

**Comment by tkrick** [comment] 2019-04-12 21:53
Can one of you who started seeing this recently @steevegldev @jpenniman @grantal can you give a detailed log? We'll take a prompt look.

**Comment by tkrick** [comment] 2019-04-12 22:32
FYI to folks. We have a fix for the above task. Will be trying to hotfix that now. Also verifying which other tasks this might be affecting. Stay tuned.

**Comment by AddonContributor** [comment] 2019-04-13 13:32
The Azure Pipeline task "Package and deploy Helm charts" [1] is also affected. It fails in the pre-job phase with `TypeError: Cannot read property 'retrieveSecret' of undefined`.

[1] https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops

**Comment by 32technologies** [comment] 2019-04-13 14:23
I'm seeing this with "Package and deploy Helm charts" as well.

**Comment by tkrick** [comment] 2019-04-13 17:33
fyi TwineAuthenticate task has been hotfixed and should be GTG. @AddonContributor @32technologies Artifacts folks don't own this the "Package and deploy Helm charts" task so the cause is likely different even though symptom might be the same. I also ran a query against that task and did not see it systemically failing across scale units. But I will still share this thread with some folks who own that task and ask them to take a look.

**Comment by steevegldev** [comment] 2019-04-13 17:51
I confirm the issue has been fixed. Thanks @tkrick

**Comment by michaelbpalmer** [comment] 2019-04-15 06:52
I am also seeing the issue with Helm charts. It appears to be related to having TLS enabled for communication between Helm and Tiller. If this isn't the right place to post this, can someone please point me in the right direction? This is currently block deployments for us. Thanks!

**Comment by estatic** [comment] 2019-04-15 07:34
Confirming, the problem with Twine Auth has been fixed.

**Comment by rigerosa** [comment] 2019-04-17 18:00
Same as @michaelbpalmer , all our Helm based pipelines are not working, we have TLS enabled.
This is blocking our deployment.

**Comment by rigerosa** [comment] 2019-04-17 20:48
Update on my previous comment: I guess it has been fixed? seems to be working now

**Comment by 32technologies** [comment] 2019-04-17 20:52
Working for me now as well.

**Comment by tkrick** [comment] 2019-04-17 23:48
hi @rigerosa , @michaelbpalmer. i reached out to a contact internally that works on those helm tasks. He asked that you file a new issue and put the info there. it will be more easy to route if it says helm in the title/etc. so if one of you could do that that would be great. sorry for the delay.

**Comment by rigerosa** [comment] 2019-04-18 00:16
thanks @tkrick but the problem seems to be solved now

**Comment by michaelbpalmer** [comment] 2019-04-18 20:38
Yes, fixed for me as well. Thanks!

**Comment by elbatk** [comment] 2019-05-15 22:32
Closing this as it looks resolved :)

**Closed by elbatk** 2019-05-15 22:32 UTC
Labels: Area: Artifacts

**Comment by shelmobd** [comment] 2023-01-10 15:19
The issue seems to be occurring again on the VSTS pipeline I am getting 
##[error]TypeError: Cannot read properties of undefined (reading 'retrieveSecret')

**Comment by SESA18621** [comment] 2023-01-10 16:10
Same here. Failing since this morning.

**Comment by a-gagnon** [comment] 2023-01-10 16:11
@shelmobd @SESA18621 I found another thread in the developer community, seems the issue is being investigated. https://developercommunity.visualstudio.com/t/npmAuthenticate0-Failing-for-version--0/10249182?q=npmauthenticate

**Comment by Faizahamed-dev** [comment] 2023-01-10 16:15
##[debug]TypeError: Cannot read properties of undefined (reading 'retrieveSecret')
    at Object.getEndpointAuthorization (D:\a\_tasks\npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788\0.214.2\node_modules\azure-pipelines-tasks-packaging-common\node_modules\azure-pipelines-task-lib\task.js:449:26)
    at getSystemAccessToken (D:\a\_tasks\npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788\0.214.2\node_modules\azure-pipelines-tasks-packaging-common\locationUtilities.js:111:21)
    at Object.<anonymous> (D:\a\_tasks\npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788\0.214.2\node_modules\azure-pipelines-tasks-packaging-common\locationUtilities.js:88:29)
    at Generator.next (<anonymous>)
    at D:\a\_tasks\npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788\0.214.2\node_modules\azure-pipelines-tasks-packaging-common\locationUtilities.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\a\_tasks\npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788\0.214.2\node_modules\azure-pipelines-tasks-packaging-common\locationUtilities.js:4:12)
    at Object.getPackagingUris (D:\a\_tasks\npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788\0.214.2\node_modules\azure-pipelines-tasks-packaging-common\locationUtilities.js:77:12)
    at D:\a\_tasks\npmAuthenticate_ad884ca2-732e-4b85-b2d3-ed71bcbd2788\0.214.2\npmauth.js:76:56
    at Generator.next (<anonymous>)
##[debug]NPM_AUTHENTICATE_TEMP_DIRECTORY=D:\a\1\npmAuthenticate
##[debug]NPM_AUTHENTICATE_TEMP_DIRECTORY=D:\a\1\npmAuthenticate
##[debug]rm -rf D:\a\1\npmAuthenticate
##[debug]removing directory D:\a\1\npmAuthenticate
##[debug]set SAVE_NPMRC_PATH=
##[debug]Processed: ##vso[task.setvariable variable=SAVE_NPMRC_PATH;isOutput=false;issecret=false;]
##[debug]set NPM_AUTHENTICATE_TEMP_DIRECTORY=
##[debug]Processed: ##vso[task.setvariable variable=NPM_AUTHENTICATE_TEMP_DIRECTORY;isOutput=false;issecret=false;]
##[debug]task result: Failed
##[error]TypeError: Cannot read properties of undefined (reading 'retrieveSecret')
##[debug]Processed: ##vso[task.issue type=error;]TypeError: Cannot read properties of undefined (reading 'retrieveSecret')
##[debug]Processed: ##vso[task.complete result=Failed;]TypeError: Cannot read properties of undefined (reading 'retrieveSecret')
Finishing: npm Authenticate MULTIORG/FE/AGFE/.npmrc

I am getting above error in my pipeline .please help me to resolve

**Comment by alexz01** [comment] 2023-01-10 16:44
I've fixed my build pipeline's task to npmAuthenticate@0.208.1 until this is fixed

**Comment by Faizahamed-dev** [comment] 2023-01-10 17:05
<img width="248" alt="image" src="https://user-images.githubusercontent.com/74110630/211613363-639f8a21-fddc-4a29-a0a8-dfe147765689.png">

i am using MS hosted agent with task version  with classic  pipeline .now my pipeline is working now with authenticator version of 0.2081 in earlier it was used "0.214.2"
