### ISSUE TITLE
Cache node_modules return error "A potentially dangerous Request.Path"

### ISSUE THREAD

**Issue by fabianpittroff** [microsoft/azure-pipelines-tasks#10906] opened 2019-07-16 14:32 UTC
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CacheBeta/Cache  

## Environment
- Agent - Hosted and Private

### Private

- macOS Mojave
- Current agent version: '2.154.1'

## Issue Description

The Post-job: CacheBeta for our node_modules produces this error message.
`##[error]A potentially dangerous Request.Path value was detected from the client (:).`
The running pipeline therefore fails.

Implemented the npm scenario like described [here](https://github.com/microsoft/azure-pipelines-yaml/pull/113#issuecomment-511499810_).

![image](https://user-images.githubusercontent.com/39737699/61301250-dc7b6580-a7e3-11e9-9bc7-2a682ff90244.png)

Tested with hosted (Hosted VS2017) and private agents (osx 2.154.1), both with the same result. Also to mention, we use an external git connection (Bitbucket Server - Public). Also also, the cache task is defined inside of a task group.

Unfortunately, I haven't tested whether continue on error helps inside of a post-job or not.

### Task logs

```bash
  | Information, Processed 87263 files from /Users/slave/workspace/vsts-agent-1/vsts-agent-osx-x64-2.149.2/_work/21/s/node_modules successfully. |  
  | Information, Uploading 87263 files from: /Users/slave/workspace/vsts-agent-1/vsts-agent-osx-x64-2.149.2/_work/21/s/node_modules |  
  | Information, Uploaded 0.0 MB out of 696.5 MB. |  
  | Information, Uploaded 584.7 MB out of 696.5 MB. |  
  | Information, Uploaded 634.9 MB out of 696.5 MB. |  
  | Information, Uploaded 696.5 MB out of 696.5 MB. |  
  | Information, Upload completed. |  
  | Information, |  
  | Upload statistics: |  
  | Total Content: 696.5 MB |  
  | Physical Content Uploaded: 0.4 MB |  
  | Logical Content Uploaded: 0.9 MB |  
  | Compression Saved: 0.6 MB |  
  | Deduplication Saved: 695.5 MB |  
  | Number of Chunks Uploaded: 23 |  
  |   |  
  | Information, Using the following fingerprint argument (/Users/slave/workspace/vsts-agent-1/vsts-agent-osx-x64-2.149.2/_work/21/s/package-lock.json) as a file. |  
  | Information, Generated fingerprint: 2FEB4E6C02D1B4FB42BB73619F17C6E246491535CF64816DC194B0175AE0834200 |  
  | Information, Creating a pipeline cache artifact with the following fingerprint: 2FEB4E6C02D1B4FB42BB73619F17C6E246491535CF64816DC194B0175AE0834200 |  
  | ##[error]A potentially dangerous Request.Path value was detected from the client (:). |  
  | Finishing: CacheBeta node_modules
```

## Troubleshooting
\-/\-

### Error logs

`##[error]A potentially dangerous Request.Path value was detected from the client (:).`

**Comment by willsmythe** [comment] 2019-07-16 15:03
Can you provide us a sample project that demonstrates the problem? Easiest option for us would be a public repo that has a package.json, package-lock.json, and azure-pipelines.yml (can be a subset of your existing files -- just enough for us to fork, run, and see the problem).

This is likely caused by a specific Node module, or a file produced when the Node module was installed, so having a sample project that we can run locally would really help.

**Comment by johnterickson** [comment] 2019-07-16 15:41
Thanks for reporting this @fabianpittroff.  This is quite odd as we hash the key so any "weird" characters should disappear... 🤔

**Comment by johnterickson** [comment] 2019-07-16 16:01
Getting a public repo & project we could fork would be ideal, but maybe a retry with system.debug=true could get us the needed info? Apologies as I'm not seeing the request in any of our server-side logs.

**Comment by johnterickson** [comment] 2019-07-16 16:04
Nevermind - I was able to find what we need in our logs.  Nothing needed from you at this point @fabianpittroff !

**Comment by fabianpittroff** [comment] 2019-07-16 17:22
nice - if you need more information, I could provide a test repo, hopefully with the same issue. Another thought, maybe our private npm registry (nexus) is the problem. We load some scoped npm packages from there.

**Comment by johnterickson** [comment] 2019-07-17 14:40
We found the issue and fixed it. This should be cleared up in the next hotfix rollout.

**Comment by fabianpittroff** [comment] 2019-07-17 17:34
very nice. I will test and report back as soon as the hotfix gets to our org ring.
Is it possible to see if the task has been updated with the api url of the cache task?
`https://dev.azure.com/{org}/_apis/distributedtask/tasks/d53ccab4-555e-4494-9d06-11db043fb4a9`
So maybe when the version changes?

**Comment by willsmythe** [comment] 2019-07-17 19:34
@fabianpittroff - the version of the task won't change, so using this API isn't a good way to see if the fix has rolled out. @johnterickson should be able to provide a general timeline for the hot fix ..

**Comment by johnterickson** [comment] 2019-07-17 21:51
The next few days - I've asked my devs to ping this issue when it hits your ring.

**Comment by fadnavistanmay** [comment] 2019-07-23 16:41
The fix was deployed. Closing the issue.

**Closed by fadnavistanmay** 2019-07-23 16:41 UTC
Labels: Area: PipelineCaching, bug
