### ISSUE TITLE
Code coverage results is empty (except for download link)

### ISSUE THREAD

**Issue by TekuSP** [microsoft/azure-pipelines-tasks#12727] opened 2020-04-21 06:34 UTC
![image](https://user-images.githubusercontent.com/13198444/79832992-d8035f00-83aa-11ea-87c7-ecdd61ab2560.png)

Code coverage tab is empty. Expected behaviour like in #9954 (https://github.com/microsoft/azure-pipelines-tasks/issues/9954#issuecomment-572450388)

Please fix it, or add our organization to closed beta. This is critical feature for us.

**Comment by zingaroo** [comment] 2020-04-22 15:59
Any update on when this will be released?

**Comment by ankit-arora12** [comment] 2020-05-08 08:06
@TekuSP @zingaroo 
Thank you for expressing interest in trying the new feature.
Due to some unforeseen circumstances, we are unable to enroll new customers for the private preview at this time. 
Right now, we don’t have an ETA to share on when we can roll this out more broadly for customers to try. Sorry !

**Comment by anshii03** [comment] 2020-10-14 06:27
@TekuSP @zingaroo 
As of now we will not be able to roll out this new feature. 

For better viewing of coverage information you can use  -

1.PCC task for coverage information stored in cobertura or jacoco format : 
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops

2.Use report generator tool in the pipeline to generate the HTML report (which support good number of coverage formats as input) 💯 
https://github.com/danielpalme/ReportGenerator

3.Furthermore, to convert .coverage format to .xml fromat :
https://github.com/danielpalme/ReportGenerator/wiki/Visual-Studio-Coverage-Tools#vstestconsoleexe

**Comment by ShreyasRmsft** [comment] 2020-11-16 06:18
Closing this based on the comment above.

**Closed by ShreyasRmsft** 2020-11-16 06:18 UTC
Labels: Area: Test, question

**Comment by TekuSP** [comment] 2020-11-16 09:10
Bug is not resolved, close this bug when you finish your code coverage tab.
Until then, let it be red, bad number in your dashboard.

**Comment by TekuSP** [comment] 2020-11-17 10:03
@anshii03 @ShreyasRmsft @ankit-arora12  Reopen the issue, or give me migration path to other service, like TeamCity and Jira, for our whole organization.
This is everything wrong

1. It's open from spring, promising feature
2. Feature is not there, but tab is
3. Marking bug as a question
4. Closing this issue, so you have clean agile plan
5. Almost no communication

Reopen the issue, and close it when you fixed it, not sooner.
If you have problem with that, give me email to your manager, and I will gladly write them long email explaining the situation. I am sure they would be happy to hear about no communication and half year long reported bug, closed.

**Comment by shashban** [comment] 2020-11-17 15:02
@TekuSP 
We had tried a closed preview of the capability to view code coverage details for a build. Based on the feedback and monitoring of the limited usage, we have now taken it back.
The behavior you are observing above is not a bug, it is the by design behavior as of now. @anshii03 shared the available alternatives earlier on this thread.

We don't have a timeline to share for when we may be working on this issue again.

Thanks

**Comment by TekuSP** [comment] 2020-11-18 17:11
Okay, then why TAB IS STILL THERE?
![image](https://user-images.githubusercontent.com/13198444/99563341-726f6380-29c9-11eb-804d-8e2929e38835.png)
If this is a feature which is not implemented, remove the whole TAB.
@shashban

**Comment by hxibrahim** [comment] 2022-03-13 16:32
I am not sure why this issue is closed. IMHO, this is a problem and a solution should be provided. As you can see below, using the [PublishCodeCoverageResultsV1](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishCodeCoverageResultsV1) and following the documentation, the artifact generated is a ".coverage" file which can be downloaded but no results are shown.
I kindly ask you to reopen this issue and provide a feedback or solution if available.

<img width="462" alt="Screenshot 2022-03-13 at 17 29 23" src="https://user-images.githubusercontent.com/87394871/158069325-5115a0c4-e629-4a08-a02f-cf2277a9f93a.png">
