### ISSUE TITLE
Azure App Service Deploy - Deploying to virtual directory wipes contents of site\wwwroot

### ISSUE THREAD

**Issue by brettkc** [microsoft/azure-pipelines-tasks#11661] opened 2019-10-30 16:05 UTC
**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**:  Azure App Service deploy (v4.*)

## Environment
Azure DevOps (hosted agent)
Agent Specified: windows-2019

## Issue Description
In Azure we've got an Azure App Service resource setup with the following path mappings:
/ => site\wwwroot  (Type: Application)
/foo => site\foo (Type: Application)

Basically a static web client is hosted at the root and a .NET core 3.0 API being hosted at /foo. The client is deploying fine to the root but anytime we deploy the .NET core project to virtual directory /foo it also completely wipes the contents of site\wwwroot. Note that deploying the client does NOT wipe site\foo.

The `dotnet` command being run to package the .NET core project is:
`--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --runtime win-x86 --self-contained true`

The output from that is what is used as the source folder for the task in question `Azure App Service Deploy`.

** Note: Publishing to app service from Visual Studio doesn't wipe the root for what it's worth **

Task Settings:
![image](https://user-images.githubusercontent.com/808673/67875122-e8c1cf00-fb03-11e9-8be2-0938bff76166.png)

### Task logs

Log (some obfuscation where necessary):
[3_Azure App Service Deploy Dev.log](https://github.com/microsoft/azure-pipelines-tasks/files/3789970/3_Azure.App.Service.Deploy.Dev.log)

**Comment by brettkc** [comment] 2019-11-11 16:58
I'll add that after trying many things to get this to work as expected, reverting this task to the previous version appears to work as intended. Issue appears to only exist in the latest version of the task.

**Comment by eaarora-ms** [comment] 2019-11-26 09:42
@brettkc  Can you please confirm if it's still happening with the latest version. My assumption is that the latest changes should have fixed the problem.

**Comment by eaarora-ms** [comment] 2019-12-16 09:03
@brettkc  Can you please confirm if you're still facing this issue?

**Comment by eaarora-ms** [comment] 2019-12-16 11:11
We are working on a potential fix. Will let you know the updates.

**Comment by arjgupta** [comment] 2020-01-29 05:28
We have discovered while making certain app settings, kudu package handling can misbehave. We are under discussion with app service team and will update this thread as and when the fix is made.

**Comment by eaarora-ms** [comment] 2020-02-03 08:42
This is an issue with one of the REST APIs (Update App Settings API to be specific) and we are working with the App service team to get this resolved. 

Sorry that this is taking longer than expected.

**Comment by HansOlavS** [comment] 2020-02-10 18:27
@eaarora-ms, This might be an important clue:
I'm seeing this error consistently on a new Azure Functions app I made today, but not on older Azure Functions apps. In my deploy pipeline everything checks out on the old Azure Function apps, but on the new one I created today I'm not able to get the deploy to work. And the SitePackages folder is empty and I get the same wwwroot "FAILED TO INITIALIZE RUN FROM PACKAGE.txt" file.

**Comment by eaarora-ms** [comment] 2020-02-11 06:26
@HansOlavS We figured out it is happening for the new apps and the older ones are not creating problems but the version thing is new. Thanks for the help!

**Comment by HansOlavS** [comment] 2020-02-11 07:20
@eaarora-ms Cool. FYI, the first thing I checked was to see if the runtime versions in Kudu were different, but they're exactly the same - even the commit hash.

**Comment by HansOlavS** [comment] 2020-02-18 19:16
I have to report that one of my Azure Function apps which is version ~2 is now showing issues with deployment where the "Run From Package"-deployment isn't deploying any zip-file and not changing anything at all. Everything is green and looks fine in Azure DevOps, but when I check the actual site content and SitePackages folder nothing had changed. So I guess the version thing might have been a fluke, after all.

**Comment by SumiranAgg** [comment] 2020-02-26 06:35
@HansOlavS Can you please open new issue for this. Looks like we are digressing from the main thread about wiping up wwwroot on deployment to virtual directory.

@brettkc The issue is happening since the first deployment to root (site/wwwroot) is done via Run From Package and deployment to virtual directory is done via Web Deploy. Can you try deploying first time using Web Deploy as well and share results. You can go to "Additional Deployment Options" section and select Web Deploy and continue.

**Comment by SumiranAgg** [comment] 2020-02-28 05:27
We have confirmed above workaround with app service team as well. The recommendation is to not mix RunFromPackage deployment technique with others. We follow below auto-detect logic in our task:
![image](https://user-images.githubusercontent.com/8316321/75512841-bcb64c00-5a18-11ea-9939-23d8afadbc69.png)
Ref: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/README.md#deployment

For now multiple app deployment on a single app service is not supported via Kudu. hence, we suggest doing both deployments through web deploy. You can select the option in task as under:
![image](https://user-images.githubusercontent.com/8316321/75512941-0dc64000-5a19-11ea-8491-1c17b002e8fd.png)

We are closing the issue for now. Please feel free to comment/ re-open if required.

**Closed by SumiranAgg** 2020-02-28 05:27 UTC
Labels: Area: AzureAppService, Area: Release

**Comment by enriquin** [comment] 2020-10-08 11:02
Hi,
I'm suffering the same issue:

Both deployments are being done using ZipDeploy (ths contents are static websites created with Jekyll), If I deploy to the "root" site  everything works OK (no files from other virtual apps are deleted), but if I deploy the app in the child virtual application (hosted in "/help") the contents of the main site are erased.

Any update on this?
