### ISSUE TITLE
Copy via bash on windows hosted agent not copying as expected

### ISSUE THREAD

**Issue by psibi** [microsoft/azure-pipelines-tasks#9158] opened 2018-12-23 14:58 UTC
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
Using Azure Pipelines. You can find the environment here: https://dev.azure.com/commercialhaskell/stack/_build/results?buildId=143

- Agent - Hosted or Private: 
    
Agent name: vs2017-win2016

## Issue Description

Something like this doesn't seem to work for Windows agent (although works fine for Linux and MacOS):

```
  - bash: |
      cp somefile $(Build.ArtifactStagingDirectory)
    displayName: Copy
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: some-artifact-name
```

The actual build pipeline replicating the issue: https://dev.azure.com/commercialhaskell/stack/_build/results?buildId=143

No build artifacts are published for the Windows environment.

You can see in the above build that the same thing works for both Linux and OSX.

**Comment by psibi** [comment] 2018-12-23 16:43
Replacing the same logic of `bash` with `powershell` makes it work.

**Comment by madhurig** [comment] 2019-02-26 17:38
@bryanmacfarlane - Looks like an issue with bash on windows not copying the files.

**Comment by bryanmacfarlane** [comment] 2019-02-26 17:45
@psibi - we may need more details on the repro.  What is `somefile` in your case?  Is it a relative or full path?  Just a file name?

**Comment by psibi** [comment] 2019-02-27 01:41
@bryanmacfarlane IIRC, it was just a file name in the current path.

**Comment by stephenmichaelf** [comment] 2019-08-19 15:47
@jtpetty Can you take a look.

**Comment by jtpetty** [comment] 2019-08-20 19:37
@psibi Are you still having this issue? I tried to repro on my end, but was unsuccessful. If you are still having this issue, can you point me to a recent build that is exhibiting this behavior?

**Comment by psibi** [comment] 2019-08-22 10:53
@jtpetty I workaround-ed the issue that time. Can I see your repro code (so that I can easily test it once more) ?

**Comment by jtpetty** [comment] 2019-08-22 13:39
@psibi - I had a very simple test case. I had this task defined in my pipeline:
```
 - bash: |
    cp README.md /mnt/d/
```
I am running the agent on Windows 10 with bash on WSL using Ubuntu. 
If there are any error logs or warnings you can point me to, I would be happy to take a look.

**Comment by psibi** [comment] 2019-08-22 15:40
@jtpetty The problem above is that when I use bash inside  the windows hosted agent - the variable `$(Build.ArtifactStagingDirectory)` doesn't work. But it will work for cases like `/mnt/d` or other paths. My guess was that for bash environment - the variable itself was not set. I can try reproducing the same, but it may take some time (two weeks) for me to get back to you as I'm going on a vacation.

**Comment by jtpetty** [comment] 2019-08-22 16:04
@psibi I think I see the problem. Since the agent is running on Windows, $(Build.ArtifactStagingDirectory) is set with a Windows-style path, in my case it is C:\agent\_work\1\a, which when used in a bash context, becomes "C:agent_work1a", which is not what we want.

There is a command 'wslpath' in bash for WSL that will translate a windows path to a unix style path. I have confirmed that this works:

```
bash: |
    cp README.md `wslpath "$(Build.ArtifactStagingDirectory)"`
```
Note, you will need to surround $(Build.ArtifactStagingDirectory) with double quotes to prevent the shell from prematurely evaluating the backslashes.

**Comment by psibi** [comment] 2019-08-22 16:10
Ah, I see. Thanks for the workaround! Updating this with the documentation would be helpful as otherwise I would have never known of `wslpath`. Thanks!

**Comment by jtpetty** [comment] 2019-08-22 16:16
No problem. I didn't know about `wslpath` either until I was trying to figure out a proper way to convert the Windows-style path to a bash-friendly path. Let me look into updating the docs or figure out way to automatically fix it.

**Comment by jtpetty** [comment] 2019-08-22 17:51
@psibi - I found a better solution. Use this instead:

```
bash: |
     cp README.md $BUILD_ARTIFACTSTAGINGDIRECTORY
```
This is an environment variable that is set to the same value as $(Build.ArtifactStagingDirectory) but is already translated to unix style path.

**Comment by jtpetty** [comment] 2019-09-05 13:40
@psibi - Can you confirm this fixes your issue?

**Comment by psibi** [comment] 2019-09-05 14:35
@jtpetty It fixes, but can we document these intricacies in the yaml reference or whatever page you see fit ?

**Comment by jtpetty** [comment] 2019-09-05 14:37
sure, let me find out the best place to do that. @vtbassmatt - do you have any thoughts on the best place to put this very important nugget of information?

**Comment by vtbassmatt** [comment] 2019-09-05 15:58
@jtpetty hmm... maybe a new heading in [this doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)? @steved0x might have an opinion.

**Comment by jtpetty** [comment] 2019-09-13 13:38
Closing this issue now that we have the docs updated to point this out explicitly.

**Closed by jtpetty** 2019-09-13 13:38 UTC
Labels: Area: Core
