### ISSUE TITLE
.NET Core SDK/runtime Installer - The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by frankkilcommins** [microsoft/azure-pipelines-tasks#12584] opened 2020-03-26 11:41 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: .NET Core SDK/runtime installer

## Environment
Server: Azure Pipelines, Account Name: DLLGroup, Project Name: DLLGroup, Build Def: API-DUPS-Web-Api-Branches-and-topics

- Agent - Hosted or Private: 
Hosted VS2017

## Issue Description

We get sporadic build failure related to this task with the following error:
`Exception calling "ExtractToDirectory" with "2" argument(s): "The process cannot access the file 
'D:\a\_temp\a898b499-2079-446a-952e-26b06054db5c' because it is being used by another process."
At line:1 char:111
+ ... catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : IOException
 
##[error]C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe failed with return code: 1
`

Similar to issue reported within [Issue 7692](https://github.com/microsoft/azure-pipelines-tasks/issues/7692) albeit the issue reported in link is for On-Premise Agent.

### Task logs
`Starting: Use .NET Core sdk 2.1.500
==============================================================================
Task         : .NET Core SDK/runtime installer
Description  : Acquire a specific version of the .NET Core SDK from the internet or local cache and add it to the PATH
Version      : 0.2.7
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer
==============================================================================
Tool to install: .NET Core sdk version 2.1.500.
C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_tasks\DotNetCoreInstaller_b0ce7256-7898-45d3-9cb5-176b752bfea6\0.2.7\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Checking if a cached copy exists for this version...
The cache does not contain the requested version of .NET Core. Downloading and installing it now.
Getting URL to download .NET Core sdk version: 2.1.500.
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4472) Warning: Use Cipheriv for counter mode of aes-256-ctr
Downloading: https://download.visualstudio.microsoft.com/download/pr/2a508a9d-91e8-4126-904c-f7a515f8a33b/24ff5fe2610ce1ce76370ed053b14094/dotnet-sdk-2.1.500-win-x64.zip
Extracting downloaded package D:\a\_temp\a898b499-2079-446a-952e-26b06054db5c.
Extracting archive
C:\windows\system32\chcp.com 65001
Active code page: 65001
C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\a898b499-2079-446a-952e-26b06054db5c', 'D:\a\_temp\5c123c0e-45d4-462a-9a52-e686608cefae')"
Exception calling "ExtractToDirectory" with "2" argument(s): "The process cannot access the file 
'D:\a\_temp\a898b499-2079-446a-952e-26b06054db5c' because it is being used by another process."
At line:1 char:111
+ ... catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : IOException
 
##[error]C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe failed with return code: 1
Finishing: Use .NET Core sdk 2.1.500
`
`

**Comment by vineetmimrot** [comment] 2020-03-30 06:23
@frankkilcommins Thanks for reporting the issue. We will have a look at it soon.

**Comment by vineetmimrot** [comment] 2020-03-30 07:40
@frankkilcommins Can you try using version 2 of the task?

**Comment by frankkilcommins** [comment] 2020-03-30 15:55
@vineetmimrot I've made the changes to most of our pipelines. Will monitor today and tomorrow to see if the behaviour is consistent.

**Comment by vineetmimrot** [comment] 2020-04-01 06:47
Have you got the chance to check?

**Comment by frankkilcommins** [comment] 2020-04-01 08:11
@vineetmimrot we had about 100 build runs yesterday where this task is active and none failed for the _file in use_ error. Saying that the task 0.* worked fine for months before I posted this issue :-) 

So make of the results what you will.

**Comment by vineetmimrot** [comment] 2020-04-01 08:17
There is a drastic difference in the design of ver 0 and ver 2 of the task. Let's wait for a week and reply to us if you face this issue again.

**Comment by anuragc617** [comment] 2020-04-07 14:53
Hi @frankkilcommins we are closing this, feel free to re-open if the issue is not resolved.

**Closed by anuragc617** 2020-04-07 14:53 UTC
Labels: Area: Release, bug
