### ISSUE TITLE
Phantom errors on AzureResourceManagerTemplateDeployment@3  

### ISSUE THREAD

**Issue by stas-sultanov** [microsoft/azure-pipelines-tasks#13797] opened 2020-10-28 22:12 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: **Bug**

**Enter Task Name**: AzureResourceManagerTemplateDeployment@3  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

**vavacars / Solution / pipelineId=71 / #TR-DEV-DEV-19**

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: **Agent: Azure Pipelines 2**

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Phantom errors are generated

Here you can see many errors
[Include task name(s), screenshots and any other relevant details]

![image](https://user-images.githubusercontent.com/6907759/97501117-6c153b00-1979-11eb-88ad-4ca70637b8c2.png)

But in reality when you navigate to logs there is no errors
![image](https://user-images.githubusercontent.com/6907759/97501218-9bc44300-1979-11eb-80f3-640d14674c71.png)

### Task logs
[logs_1259.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5455076/logs_1259.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by rikat-ms** [comment] 2020-10-30 06:36
Same issue: https://developercommunity.visualstudio.com/content/problem/1224035/no-message-found-for-this-issue-error-in-azure-dev.html

**Comment by rikat-ms** [comment] 2020-11-02 15:24
As 'Andre 365' said in the forum, the cause of the error looks that 'MissingSubscription' is reported as an error, but it isn't translated. This error occurs at GET request to this URL in GetServicePrincipal method.
- URL: 'https://management.azure.com/<tenantId>/servicePrincipals?$filter=appId%20eq%20'<applicationId>'. (both <tenantId> and <applicationId> are obtained from service connection setting.) The line is here.
- Source: https://github.com/microsoft/azure-pipelines-tasks/blob/6e24f3b285397073443f29db64e654e578f885db/common-npm-packages/azure-arm-rest-v2/azure-graph.ts#L51

We can see this error when we access this URL from browser directly.
![image](https://user-images.githubusercontent.com/37922646/97885185-626d4800-1d6a-11eb-80d9-c761616d0c65.png)

If this error can be ignored, to stop reporting it as an error can be a resolution.  Or, if this URL isn't valid to get service principal's information, URL should be changed.

**Comment by anuragc617** [comment] 2020-11-03 12:58
Yes @rikat-ms you are right this is happening because GetServicePrincipal is failing due to wrong endpoint. We are working on the fix on high priority.

**Comment by RobertoBorges** [comment] 2020-11-18 21:08
Sample problem here, the ARM deployment happens fine, no errors detected.

**Comment by tiwarishub** [comment] 2020-12-22 09:25
hi @stas-sultanov / @RobertoBorges , we have merged and deployed. Please let us know, if you are still seeing this issue

**Comment by tiwarishub** [comment] 2020-12-23 12:41
Closing this thread as issue  is fixed. Feel free to open a new ticket if you see this error again

**Comment by tiwarishub** [comment] 2020-12-24 08:57
Closing as issue  is fixed and deployed

**Closed by tiwarishub** 2020-12-24 08:57 UTC
Labels: Area: Release, bug
