### ISSUE TITLE
Caching from and restoring to multiple locations

### ISSUE THREAD

**Issue by flyingUnderTheRadar** [microsoft/azure-pipelines-tasks#11692] opened 2019-11-05 00:04 UTC
Ref: Azure build pipeline caching - https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops

Usecase - Mono Repo

A mono repo will have dependencies at the root level as well as at the sub repo levels as well. 

Example -  https://github.com/Microsoft/accessibility-insights-service
When a yarn install is run on this project it will create a node_modules directory under 
`./` as well as `./packages/azure-storage/node_modules`.

A way to cache from multiple folders will be great for such use cases.

**Comment by fadnavistanmay** [comment] 2019-11-11 18:06
Hi @flyingUnderTheRadar - Can you have 2 caching tasks to cache 2 different folders, and then restore both?

**Comment by flyingUnderTheRadar** [comment] 2019-11-11 22:04
I thought of using different but we have multiple modules in there and having a task for each of those seemed cumbersome and meant that it would require future maintenance when we added or removed a module so I did not try this out.

**Comment by johnterickson** [comment] 2019-12-02 22:29
I am now realizing this is a dupe of https://github.com/microsoft/azure-pipelines-tasks/issues/11219

**Closed by johnterickson** 2019-12-02 22:29 UTC
Labels: Area: ArtifactsCore, Area: PipelineCaching, enhancement
