### ISSUE TITLE
InstallAppleCertificateV2 and InstallAppleProvisioningProfileV1 often fails to download secure files

### ISSUE THREAD

**Issue by maxim-lobanov** [microsoft/azure-pipelines-tasks#13468] opened 2020-08-26 06:00 UTC
## Required Information

**Question, Bug, or Feature?**  Bug

**Task Name**: InstallAppleCertificateV2 and InstallAppleProvisioningProfileV1

## Environment
- Azure pipelines
- Hosted MacOS images

## Issue Description

These tasks are used to download secure files from Azure DevOps to VM during build. We have noticed that these tasks are unstable and often fail randomly (see errors below) and pass on retry.
Context: We run builds that contains a lot of jobs (~about 32 jobs) to validate Hosted images quality. Pass rate of this build is ~60%. In every second build, at least one job from 32 fails (about 2% of total number of jobs fail with issue for us). It produces a lot of noise.

### Task logs
InstallAppleCertificateV2:
```
##[error]Error: Invalid Resource
```
InstallAppleProvisioningProfileV1:
```
##[error]Error: connect ETIMEDOUT 13.107.42.18:443
```

Example of failed builds: 
- [Link 1](https://buildcanary.visualstudio.com/PipelineCanary/_build/results?buildId=1045786&view=logs&j=5439f50a-355e-5e3b-53c8-8a2ab2b00259&t=c7c268c4-17d9-444d-bfe7-74a313fc6244)
- [Link 2](https://buildcanary.visualstudio.com/PipelineCanary/_build/results?buildId=1039380&view=logs&j=5d6d3fdb-1da0-5537-bdfc-899d7af9b662&t=e8bd860f-623a-4df5-9359-9bea80e16d4f)
- [Link 3](https://buildcanary.visualstudio.com/PipelineCanary/_build/results?buildId=1038886&view=logs&j=bf815176-2569-5c26-3bfb-e1028de577da&t=9ff99e64-7306-4a0b-93d8-d9f7be140056)

## Possible solution
I propose implementation of retry logic on task level. So if downloading fails, wait a few seconds and try one more time.

**Comment by alexander-prozorov** [comment] 2020-09-03 07:21
Hello @maxim-lobanov,

It looks like we already have the retry logic at the azure-devops-node-api level. By default we have 5 retries already:

```
const maxRetries = retryCount && retryCount >= 0 ? retryCount : 5;
...
let options: IRequestOptions = {
     allowRetries: true,
     maxRetries
};
...
this.serverConnection = new WebApi(serverUrl, authHandler, options);
```

Where WebApi passes this options object to the HttpClient [here](https://github.com/microsoft/azure-devops-node-api/blob/master/api/WebApi.ts#L163).

As far as I can see, this issue has not occurred since August 20th. Is it still relevant?

**Comment by alexander-prozorov** [comment] 2020-09-07 06:56
Hi @maxim-lobanov, 

Could you please confirm that we need the retry logic at the task level since we already have it in the node api?

**Comment by maxim-lobanov** [comment] 2020-09-07 07:51
Unfortunately, this issue still reproduces sometimes. [Example](https://buildcanary.visualstudio.com/PipelineCanary/_build/results?buildId=1084050&view=logs&j=2a76672d-928d-5404-2031-2a96851d5b43&t=1c275fed-b058-4156-841a-6dcbd9198a23)

Any ideas why retry logic doesn't help in this case? How can we check that retry logic is really used in that failed task?

**Comment by alexander-prozorov** [comment] 2020-09-08 15:42
I wasn't able to reproduce this issue locally having 80 secure file downloads per job. But logging on the local agent shows that HttpClient has exactly 6 tries (Logging this value: https://github.com/microsoft/typed-rest-client/blob/master/lib/HttpClient.ts#L242 : 5 passed and + 1). 
HttpClient has no logging by default so I can only guess using the time taken to complete this step. The failed step takes 3s, the succeded ones take 1-2s. All 6 attempts are about 1.3 seconds (https://github.com/microsoft/typed-rest-client/blob/master/lib/HttpClient.ts#L594). So it seems that all of them were executed.

**Comment by alexander-prozorov** [comment] 2020-09-09 12:04
@maxim-lobanov 

I found two more tickets related to this issue:

- https://github.com/microsoft/azure-devops-node-api/issues/345
- https://github.com/rfennell/AzurePipelines/issues/648

And it seems like sometimes increasing retries helps with this problem. In any case, this only applies to the ms-hosted machines. No one can reproduce this issue using a local agent (see my message up above).

What do you think, does it make sense to implement this logic additionally at the task level? Or it is better to increase maxRetries value in the securefiles-common module?

**Comment by maxim-lobanov** [comment] 2020-09-09 12:06
@alexander-prozorov , I suggest starting with increase the number of retries / socket timeout because it is simpler solution.

**Comment by alexander-prozorov** [comment] 2020-09-11 11:35
Created PR: https://github.com/microsoft/azure-pipelines-tasks/pull/13534

**Comment by anatolybolshakov** [comment] 2020-10-12 15:18
Hi @maxim-lobanov 😃 Related changes has been rolled out, I'm closing it at the moment - please feel free to reopen it if this issue appears again

**Closed by anatolybolshakov** 2020-10-12 15:18 UTC
Labels: Area: ABTT, Area: Release, Task: InstallAppleCertificate, bug
