### ISSUE TITLE
Error CODE 504

### ISSUE THREAD

**Issue by thedoupub** [microsoft/azure-pipelines-tasks#11109] opened 2019-08-12 10:03 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  Azure Function App Deploy

This happens out of nowhere. Nothing practically changed in the Azure  Pipelines from my side.

### Error logs

[Insert error from the logs here for a quick overview]

Error: Failed to update App service 'name-of-service' application settings. Error: The gateway did not receive a response from 'Microsoft.Web' within the specified time period. (CODE: 504)
--

**Comment by abij** [comment] 2019-08-13 08:47
We are experiencing the same issue.

The function artifact (zip) is uploaded and loaded into the Function. When you look in the Azure Portal you can see the function / new code.

But the task in 'hanging' and resulting in a timeout after 5+ minutes.

**Comment by thedoupub** [comment] 2019-08-15 11:57
Just as an update this error is still active. Sometimes even reporting a false 400 error of the function app being unsuccessfully synced. 

I tested in both cases the deployed app and it worked like a charm.

**Comment by vincentdass** [comment] 2019-09-06 04:18
Duplicate of #11121

**Closed by vincentdass** 2019-09-06 04:18 UTC
Labels: Area: AzureAppService, Area: Release, bug
