### ISSUE TITLE
Intermittent quote failure in bash task/variable substitution

### ISSUE THREAD

**Issue by Korijn** [microsoft/azure-pipelines-tasks#14408] opened 2021-02-17 14:01 UTC
Given:

```yaml
  parameters:
    image: 'myorganization.azurecr.io/project/system'
```

The following **_sometimes_** fails. I can't explain it. Retrying usually works.

```yaml
  steps:
  - task: Bash@3
    displayName: Set vars
    name: setVars
    inputs:
      targetType: inline
      script: |
        set -ex
        export GIT_REV=$(git rev-parse --short $(Build.SourceVersion))
        echo "##vso[task.setvariable variable=GIT_REV]$GIT_REV"
  - task: Bash@3
    displayName: Docker pull
    inputs:
      targetType: inline
      script: |
        set -ex
        docker pull ${{ parameters.image }}:dev-$(GIT_REV)
```

Like so:

```
Starting: Set vars
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/cf264bb2-704a-4b52-b55c-68922e8b64c9.sh
++ git rev-parse --short 464c86960599671cd35e0d3b87cb17baffeed09a
+ export GIT_REV=464c8696
+ GIT_REV=464c8696
Finishing: Set vars
```

```
Starting: Docker pull
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/bf0524ed-7aa5-4b38-bcfa-33ce8d1a6ac5.sh
/home/vsts/work/_temp/bf0524ed-7aa5-4b38-bcfa-33ce8d1a6ac5.sh: line 2: unexpected EOF while looking for matching `''
##[error]Bash exited with code '2'.
Finishing: Docker pull
```

**Comment by Korijn** [comment] 2021-02-17 14:36
Another data point, this also sometimes happens in another location in the script, with a different error:

```yaml
    - task: Bash@3
      displayName: Push Docker images
      inputs:
        targetType: inline
        script: |
          set -ex
          docker push ${{ parameters.image }}:dev-$(GIT_REV)
          docker push ${{ parameters.image }}:$(GIT_REV)
```

```
Starting: Push Docker images
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/25f0fe4d-9876-49dc-ab65-e8c8c5b39c62.sh
+ docker push '***/project/system:dev-ee9e0f3a
docker push ***/project/system:ee9e0f3a'
invalid reference format
##[error]Bash exited with code '1'.
Finishing: Push Docker images
```

Notice that dangling quote at the end of the line which has seemingly appeared out of nowhere: `docker push ***/project/system:ee9e0f3a'`

**Comment by anatolybolshakov** [comment] 2021-03-23 12:13
Hi @Korijn does it happen only when you use interpolation in bash script? Do you have some example of script for which it is constantly reproducible?

**Comment by Korijn** [comment] 2021-03-23 12:41
> does it happen only when you use interpolation in bash script?

Yes.

> Do you have some example of script for which it is constantly reproducible?

I do not, which is why I came here to ask for help. It literally just happens every now and then. If I retry the same build a bunch of times it sometimes fails and sometimes passes.

**Comment by anatolybolshakov** [comment] 2021-03-30 08:20
@Korijn do you use cloud or on-premise product version?

**Comment by Korijn** [comment] 2021-03-30 10:43
Cloud!

**Comment by anatolybolshakov** [comment] 2021-04-06 13:40
@Korijn I tried to run it several times but it's still not reproducible - looks like something could go wrong at the stage of variable substitution. Since Bash pipeline task doesn't handle this - could you please create ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it?

**Comment by Korijn** [comment] 2021-04-06 14:56
Sure, here it is: https://developercommunity.visualstudio.com/t/intermittent-quote-failure-in-bash-taskvariable-su/1391412

**Comment by anatolybolshakov** [comment] 2021-05-04 15:38
Hi @Korijn I'm closing this ticket at the moment since this issue doesn't seem to be related to the task itself - please feel free to share additional info in related developer community ticket.

**Closed by anatolybolshakov** 2021-05-04 15:38 UTC
Labels: Area: ABTT, Task: Bash, bug

**Comment by Korijn** [comment] 2021-05-04 17:49
Sure. I am a little sour about the whole affair though because my ticket at the other site got closed because I can't provide an example to reproduce. But my pipeline keeps exhibiting the issue every now and then.

**Comment by bigjonroberts** [comment] 2021-08-17 12:55
We hit the same error today consistently.  I guess that azure pipelines really just doesn't support this feature with bash right now?
If so, the docs should be updated to reflect that.

**Comment by bigjonroberts** [comment] 2021-08-17 19:39
Well what do you know, the docs do address aspects of this issue:
https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/troubleshooting?view=azure-devops#variables-having--single-quote-appended

**Comment by Korijn** [comment] 2021-08-18 05:49
Wow! That's a great find, thanks for sharing!
