### ISSUE TITLE
Latest AzurePowershell@4 (4.159.3) returns error Run Connect-AzAccount to login.

### ISSUE THREAD

**Issue by NickGraham101** [microsoft/azure-pipelines-tasks#11672] opened 2019-10-31 14:25 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: BUG

**Enter Task Name**: AzurePowershell@4 (4.159.3)

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines:
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: sfa-gov-uk.visualstudio.com, Digital First Careers, releaseId=9219

- Agent - Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Server 2016 Datacentre, 2.159.2

## Issue Description

This issue presents similar symptoms to issue [11621](https://github.com/microsoft/azure-pipelines-tasks/issues/11621)

When running a script in a Release using the AzurePowershell@4 task with the Advance > Use Powershell Core box ticked the script runs until it reaches a cmdlet that requires authentication with Azure, in this case Get-AzApiManagementApi.  At that point the script returns the following error:

##[error]Get-AzApiManagementApi : Run Connect-AzAccount to login.

![image](https://user-images.githubusercontent.com/34914709/67953837-c903d700-fbe7-11e9-81fa-6949e6873ab4.png)

If the release is edited and the  Use Powershell Core box is unticked the release succeeds (in this case the script uses AzureRm cmdlets rather than Az cmdlets, there is logic in the script to check the version of PS in use)

### Task logs

[tasklog_13.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3794189/tasklog_13.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by brushwood24** [comment] 2019-11-08 20:57
I am seeing this same issue using a private agent

**Comment by 20shivangi** [comment] 2019-11-11 09:31
@NickGraham101 I am working on fixing this issue and will let you know once it is done.

**Comment by brushwood24** [comment] 2019-11-11 15:39
@20shivangi Is there an ETA for the fix or a workaround in the mean time?

**Comment by 20shivangi** [comment] 2019-11-19 09:13
@brushwood24
The issue has been fixed in PR : https://github.com/microsoft/azure-pipelines-tasks/pull/11778
It has been merged and it is fixed in new azure powershell version i.e. 5.162.0
It will take at least 3-4 weeks for the change to get deployed.

**Comment by eaarora-ms** [comment] 2019-11-25 11:41
Closing this since the issue is fixed and merged.

**Comment by eaarora-ms** [comment] 2019-12-16 08:00
The issue should have been fixed by now. It might take some time to mitigate though. Please comment if you're still facing it.

**Comment by jeremytbrun** [comment] 2020-06-25 17:32
@eaarora-ms Bumping this thread. See above comments.

**Comment by eaarora-ms** [comment] 2020-06-25 17:58
@20shivangi  To look into it.

**Comment by Roshan-Kumar-Microsoft** [comment] 2020-07-02 20:02
Already made azurepowershell V5 as GA https://github.com/microsoft/azure-pipelines-tasks/commit/0110e09085e7c04df636b9e759cb35f1c69b40ee#diff-0dd11361cc3202525e07443994b339ed But deployment is going ring by ring ...It will reflect most probably by this weeks .
![image](https://user-images.githubusercontent.com/57892372/86404259-e637fa80-bccc-11ea-9e9a-73f9608a2ee1.png)

**Closed by Roshan-Kumar-Microsoft** 2020-07-02 20:02 UTC
Labels: Area: Release, bug
