### ISSUE TITLE
PublishCodeCoverageResults has misleading warning and documentation?

### ISSUE THREAD

**Issue by Kurtz1993** [microsoft/azure-pipelines-tasks#13091] opened 2020-06-09 19:44 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: **Question**

**Enter Task Name**: Publish Code Coverage

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Issue Description

Is the documentation misleading for this particular task? I've found that it says that if you provide multiple reports for this task it won't merge them (See here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops#faq)
Even there's a warning when the task is executed with multiple files.
But in reality, I'm seeing this:
![image](https://user-images.githubusercontent.com/5412470/84192367-7d5bba80-aa5f-11ea-83be-cf40252df123.png)
[...]netcoreapp2.0\ReportGenerator.dll -reports:tests/**/coverage.cobertura.xml -targetdir:d:\Agent2\_work\_temp\cchtml -reporttypes:HtmlInline_AzurePipelines
![image](https://user-images.githubusercontent.com/5412470/84192421-95cbd500-aa5f-11ea-9b84-7629fb62d7cd.png)

It seems that under the hood, the tasks uses the ReportGenerator package, which is actually merging my reports.

So, the questions are:
- **Is the warning misleading?**
- **Is there a need to update the docs somehow to let the users know that their reports are actually being merged?**

I'm asking this, because this is a **desired behaviour**.

Thanks!

**Comment by hvinett** [comment] 2020-10-29 11:05
hey @Kurtz1993 , can you provide complete debug logs(enable system.debug = true) for the run?

**Comment by hvinett** [comment] 2020-12-02 07:56
@Kurtz1993 , closing this issue. if you still facing the issue, please feel to reopen this.

**Comment by drdamour** [comment] 2021-01-13 19:09
@Kurtz1993 it's kidna confusing...the report generator tool that generates the html has no problem with multiple files...the only thing that has a problem is the task itself when it tells devops the coverage summary value which shows here
![image](https://user-images.githubusercontent.com/1514496/104497789-1f182c80-5598-11eb-9a0f-ce3e7e83d0fe.png)

if you have multiple coverage files then this value will be from the first one it picks..and will not match the full html file it generates...so yes misleading a BIT but still true.  If they publish the v2 #13257 then we can just use that and NOT have to merge the reports ourself

**Closed** 2021-02-25 08:38 UTC
Labels: Area: CodeCoverage, Area: Test, question

**Comment by IvanAlekseev** [comment] 2021-02-25 09:15
@nishantms can you provide some comments for closing it? Have you implemented merging in v1 or published v2?

**Comment by nishantms** [comment] 2021-02-25 11:41
@IvanAlekseev This is by design of task. Quoting the comment of @drdamour , this is already marked for enhancement. Following are the other tickets already kept opened: 
https://github.com/microsoft/azure-pipelines-tasks/issues/10353 
https://github.com/microsoft/azure-pipelines-tasks/issues/13448

**Comment by IvanAlekseev** [comment] 2021-02-25 13:00
@nishantms cool, thanks. Are there any updates for v2?
