### ISSUE TITLE
Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll does not always find all warnings and fails the build

### ISSUE THREAD

**Issue by DutchBlackOp** [microsoft/azure-pipelines-tasks#16301] opened 2022-05-10 14:21 UTC
### Issue Description

When running builds in azure devops server 2020 Update 1.1 the build sometime fails with the following error.
- ##[error]Value cannot be null. (Parameter 'Parent timeline record has not been created for this new timeline record.')

### Expected Behavior

MSBuild/azure-pipelines-agent to correctly report all warnings that occurred during a build and doesn't fail the build.

### Actual Behavior

Build reported failing build because of:
- ##[error]Value cannot be null. (Parameter 'Parent timeline record has not been created for this new timeline record.')

### Analysis

- The azure-pipelines-tasks MSBuild Task uses the Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll to process MSBuild events (like errors/warnings) and does a Console.WriteLine($"##vso[task.logissue on receving of certain MSBuild messages.
- This ##vso[task.logissue console output gets process by the azure-pipelines-agent so the errors are nicely reported in the AzureDevOps Server
- The logger matches certain warnings to parent ID's

After re-running the binlog locally the logger misses 404 warnings
-  "msbuild.exe" "test.binlog" /nologo /nr:false /dl:CentralLogger,"Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";
    "enableOrphanedProjectsLogs=true"*ForwardingLogger,"Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /v:diag 
    /clp:Verbosity=m /nr:false /t:Build /p:platform="Any CPU" /p:configuration="Release" /m
- binlog viewer: 4494 warnings
- ##vso[task.logissue type=Warning: 4090

The command above can be run every time on the binlog and will show the same result. This seems to give some consistency to this issue.

### Versions
Build Servers are running Windows Server 2016
Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll 5.0
azure devops server 2020 Update 1.1

### Attach a binlog

I'll provide a binlog privately in the developer community: https://developercommunity.visualstudio.com/t/MicrosoftTeamFoundationDistributedTask/10036125?space=22&entry=problem

### Previous issue 
Issue: #14863

**Comment by KirillOsenkov** [comment] 2022-05-10 21:32
@anatolybolshakov

**Comment by anatolybolshakov** [comment] 2022-05-11 17:21
Hi @DutchBlackOp could you please share which MSBuild task version do you use? This issue has been fixed in MSBuild task v1.197.0 - usually on-prem server releases receive tasks updates with some delay

**Comment by japj** [comment] 2022-05-12 06:48
I believe we are currently using v1.198.0 of the MSBuild task, since we needed to have VS2022 support on AzureDevOps 2020 server, but @DutchBlackOp can confirm what exactly are using.

It might not be entirely clear from the issue text, but we did reproduce this issue (using MSBuild replay binlog) on the latest Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll (v5) as referred to from https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/MSBuildHelpers/make.json

**Comment by DutchBlackOp** [comment] 2022-05-12 07:17
> Hi @DutchBlackOp could you please share which MSBuild task version do you use? This issue has been fixed in MSBuild task v1.197.0 - usually on-prem server releases receive tasks updates with some delay

We are currently using v1.198.0. And like @japj mentioned we also tested the issue on the latest Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll (v5)

**Comment by DutchBlackOp** [comment] 2022-05-16 07:52
Hello @anatolybolshakov, I only have the raw logging of the pipeline. Because this error does not occur 100% of the time I cannot reproduce it easily with extra logging commands. I've added the raw logging privately to my [developercommunity post](https://developercommunity.visualstudio.com/t/MicrosoftTeamFoundationDistributedTask/10036125?space=22&entry=problem&viewtype=all)
Let me know if this is insuficient and diagnostic mode logging is needed. Then I will see what I can do to reproduce the error with more logging.

**Comment by anatolybolshakov** [comment] 2022-05-16 16:18
@DutchBlackOp yes, I've already examined raw logs, but haven't found this error here - so it would be very helpful to check pipeline logs. I'm not sure if this is the same issue as in  https://github.com/microsoft/azure-pipelines-tasks/issues/14863 - (although it's probably similar)

**Comment by kirill-ivlev** [comment] 2022-11-03 10:40
@DutchBlackOp could you please confirm that problem is still actual for you?

**Comment by DutchBlackOp** [comment] 2022-11-03 11:52
This is still an issue for us.
The release of Azure Devops Server 2022 is releasing soon. And we are going to be moving to that version.
I don't if this would have any impact because I have not checked if the new version also comes with a new version of the Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll > v5

**Comment by sergey-koryshev** [comment] 2022-11-25 13:37
@DutchBlackOp can you please provide a log of affected pipeline since it seems the log file you mentioned above is not available anymore?

**Comment by sergey-koryshev** [comment] 2023-01-05 09:10
@DutchBlackOp, I close the issue due to inactivity, please feel free to reactivate it or create new one

**Closed by sergey-koryshev** 2023-01-05 09:10 UTC
Labels: bug, Area: ABTT, Task: MSBuild

**Comment by KirillOsenkov** [comment] 2023-12-18 02:45
I think that logger just needs to be rewritten from scratch. There are too many bugs there.

Here's how I would do it:
https://github.com/KirillOsenkov/MSBuildTools/tree/main/src/ErrorLogger
