### ISSUE TITLE
Failing PowerShell on Remote Machine task based on exit codes

### ISSUE THREAD

**Issue by DynConcepts** [microsoft/azure-pipelines-tasks#6042] opened 2017-12-14 11:25 UTC
I can not find a way to have a the PowerShell on Remote Machine Task Fail the Step (and thus Build or Release) based on the exit conditions of the remote PS script...

Attempting to determine if this is a limitation or just obscurity of documentation [at 30+ minutes of web searching revealed nothing concrete]

NOTE: This happens to be in a TFS-2017 RTM environment.

**Comment by bryanmacfarlane** [comment] 2017-12-14 23:19
I think this needs more details and repro steps.

**Comment by DynConcepts** [comment] 2017-12-15 00:54
Just create a simple PS1 file with an "exit 1". The step passes.

**Comment by rajatagrawal-dev** [comment] 2017-12-15 08:12
@DynConcepts 
If you execute exit 1 locally, it just exits the process without throwing any error. "exit" statements only set the exit codes which you can get by using the variable $LastExitCode. They don't give any error and are not considered failure statements.
To actually make the script throw an error, you should use Write-Error or throw statements. "throw" statements actually set the exit code to 1 and throw an error.

**Comment by DynConcepts** [comment] 2017-12-15 10:29
That is going to be a problem. In this scenario we are executing *pre-existing* scripts on the target machine. Modification of these scripts is not in scope, neither is deploying additional material directly to the machine (the existing scripts "pull" content that originated in a build).

Is there any way to back propagate $LastExitCode back into the agent "context" so that it can be checked?

**Comment by rajatagrawal-dev** [comment] 2017-12-15 12:53
I am not sure I understand your scenario completely. If you are using Powershell on Target Machines task, you must be specifying one main script to be executed. Can't you create a powershell script that calls the current main script which you are executing and make this new script your main script? In this way you can access your error code in the new main script.

**Comment by DynConcepts** [comment] 2017-12-15 13:06
I must specify an existing and unaltered script on the target. If I follow your suggestion, the PowerShell script that I create would have to be deployed (I did not se an option for inline script)

**Comment by rajatagrawal-dev** [comment] 2017-12-18 06:28
True. I do not see how we'll be able to read a variable from target machine without doing something on the target machine. I would have suggested deployment groups feature to you as well which would have allowed you to execute normal powershell task (with inline script support) on the server, but we don't have that feature in TFS 2017 and even that would require installing a deployment agent on the target server, which is not allowed in your scenario.

**Comment by DynConcepts** [comment] 2017-12-18 10:49
Not talking about a variable in genereal, but an exit code specifically... I believe the following should work at the lower level:

$result=invoke-command -computer PC2 -credential $cred -scriptblock { ...} -argumentlist '...'
$result

But what is missing (or at least I am missing it) is the ability to make use of that return code when using the "PowerShell on Remote" Task....

This issue is compounded by the fact that if one chooses to "throw" rather than "exit 1" the TFS (2017 RTM) logs appear to just get the exception trace and NO sign of the output that was generated before the exception was thrown [this is related to the other Issue I had open, which was closed by rajatagrawal-dev]

**Comment by rajatagrawal-dev** [comment] 2017-12-18 16:26
If you use "Write-Verbose -Verbose" with "throw", things should work fine, with the logs visible. 
If you want to show error in powershell then using "exit" statements is not the right way. You should use "throw" statement. If you are using "exit" command and want to show the meaning of that exit code then you can use "net helpmsg <exit_code>" command. "Powershell on Target Machine" will not give you the exit code.

If you are running Invoke-Command using a Powershell task (and not using "Powershell on Target Machine" task), then returning $LastExitCode in your scriptblock argument should give you the exit code, which you can then make use of as described above. 

$result = Invoke-Command -ScriptBlock { C:\DynConceptPowershell.ps1; return $LastExitCode} -ComputerName $computerName -Credential $cred
$result

This gave all the logs as well as the exit code when I ran locally. Will running it this way work for you?

**Comment by DynConcepts** [comment] 2017-12-18 16:33
As per https://github.com/Microsoft/vsts-tasks/issues/6018...

Write-Verbose does not properly flush even under normal circumstances. So that is not an option.

You are correct, If I use "Invoke-Command" then things will "work".... My specific question was how to accomplish the SAME capability using an OOB task [aka "Powershell on Target Machine" ]. My expectation would be to have the task either store the $LastExitCode in a Release Variable, or [nicer, in this case] have a checkbox to say "Fail on Non-Zero Exit Code".

**Comment by rajatagrawal-dev** [comment] 2017-12-19 14:59
1. Write-Verbose will not work if you are using some particular IIS commands which, as you mentioned, you are. I gave a workaround in #6018 for this but since you can't edit the scripts it might not be applicable to you. 

2. Write-Output is also misbehaving, apparently when there is something written to the error stream also. So we don't recommend Write-Output for now.

3. Incorrect order of logs can also happen if you are writing to multiple streams like Verbose and Output streams.

4. Exit codes are not returned by the "Powershell on target machines" task and the task does not give the option to fail the task on non-zero exit code. Since this is a feature that is available in the normal Powershell task but not on the "Powershell on target machines", we'll take this enhancement request and  try to provide a way to fail based on exit codes for this task.

Please use the available workaround for now. I'll update when any of the above issues gets fixed.

**Comment by DynConcepts** [comment] 2017-12-19 15:01
I will re-run the tests, but a script of just

Write-Verbose “1”
Write-Verbose “2”
…
Write-Verbose “500”

Only generates partial output.

**Comment by rajatagrawal-dev** [comment] 2017-12-19 16:36
Worked fine for me. Let me know what output you get.

**Comment by DynConcepts** [comment] 2017-12-19 17:11
I will be back in that environment tomorrow and will test. Can you confirm you are using the tasks that ship with 2017 RTM and with PowerShell 4.0.....

**Comment by JamieO53** [comment] 2018-07-17 05:46
I am experiencing the same problem with the local PowerShell task.

My expectation is that a powershell task consisting of `exit 1` should behave the same way as a Command task consisting of `powershell -C "exit 1", which is the same as a Command task consisting of `exit 1`. This is normal behaviour for Windows command shells.

The second fails, as expected, while the first does not.

**Comment by JamieO53** [comment] 2018-07-17 05:52
This is a serious issue, as I am publishing NuGet packages after my regression tests fail.

**Comment by rajatagrawal-dev** [comment] 2019-05-22 06:07
@JamieO53 Sorry for the very late reply. If you are facing this issue on the basic PowerShell task, then I request you to open another issue specifically mentioning that since that is a different task.
Also give details about which product version you are using as well as the task version. Debug logs/repro steps will be helpful too.

**Comment by rajatagrawal-dev** [comment] 2019-05-22 06:07
Closing this for now. Please reopen if required.

**Closed by rajatagrawal-dev** 2019-05-22 06:07 UTC
Labels: Area: Release, enhancement
