### ISSUE TITLE
Nodejs download step broken

### ISSUE THREAD

**Issue by gerhardcit** [microsoft/azure-pipelines-tasks#12632] opened 2020-04-06 16:14 UTC
```
Starting: Use Node 12.16
==============================================================================
Task         : Use Node.js ecosystem
Description  : Set up a Node.js environment and add it to the PATH, additionally providing proxy support
Version      : 1.165.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
==============================================================================
Downloading: https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.gz
Extracting archive
/bin/tar xzC /home/vsts/work/_temp/5af9cb94-dc10-4f38-ac52-0e23f8626c0d -f /home/vsts/work/_temp/fcbb2481-d593-4486-9255-b0469da20434

gzip: stdin: unexpected end of file
/bin/tar: Unexpected EOF in archive
/bin/tar: Unexpected EOF in archive
/bin/tar: Error is not recoverable: exiting now
##[error]/bin/tar failed with return code: 2
Finishing: Use Node 12.16
```

**Comment by gerhardcit** [comment] 2020-04-06 16:17
And then 5 minutes later its fine?
```
=============================================================================
Task         : Use Node.js ecosystem
Description  : Set up a Node.js environment and add it to the PATH, additionally providing proxy support
Version      : 1.165.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
==============================================================================
Downloading: https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.gz
Extracting archive
/bin/tar xzC /home/vsts/work/_temp/b29f55c4-023f-4400-a8dc-79573876ca17 -f /home/vsts/work/_temp/d9414b6e-04a7-4e59-b25c-e849a4827a0a
Caching tool: node 12.16.1 x64
Prepending PATH environment variable with directory: /opt/hostedtoolcache/node/12.16.1/x64/bin
Finishing: Use Node 12.16
```

**Comment by andwilr** [comment] 2020-04-06 17:46
I too am having this issue after having run it successfully many times since February.

```
Starting: Install Node.js
==============================================================================
Task         : Node.js tool installer
Description  : Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
Version      : 0.166.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/node-js
==============================================================================
Downloading: https://nodejs.org/dist/v13.7.0/node-v13.7.0-linux-x64.tar.gz
Extracting archive
/bin/tar xzC /home/vsts/work/_temp/c390c20f-3f52-451e-b447-f01087ae2c78 -f /home/vsts/work/_temp/78470d9f-1335-44d5-be90-6fc12b2b22cf

gzip: stdin: unexpected end of file
/bin/tar: Unexpected EOF in archive
/bin/tar: Unexpected EOF in archive
/bin/tar: Error is not recoverable: exiting now

##[error]The process '/bin/tar' failed with exit code 2
```

**Comment by damccorm** [comment] 2020-04-06 19:11
This is caused by the same underlying issue as #12627 (an external node service issue). I'm closing here, lets follow up there as needed

**Closed by damccorm** 2020-04-06 19:11 UTC
Labels: route, triage
