### ISSUE TITLE
Azure PowerShell Script Task: Please provide a valid tenant or a valid subscription 

### ISSUE THREAD

**Issue by iambernics** [microsoft/azure-pipelines-tasks#13087] opened 2020-06-09 13:23 UTC
Sorry, this issue was not resolved:
#13038 
I just informed us on my last comment that the issue is not related with the Service Connections.

**Comment by asranja** [comment] 2020-06-11 22:21
Apologies if I interpreted it incorrectly. You mentioned that "The problem is solving when I restart the Agent service and try again the Pipeline." . Are you still blocked ?

**Comment by iambernics** [comment] 2020-06-12 08:31
Yes, this workaround is not acceptable on prod environments.
We could not restart the Agent process when it's running and working on / waiting for a Job.

**Comment by asranja** [comment] 2020-06-15 08:57
I believe that the restart should be a one time operation. Mostly it is required to restart the agent if you install any new service, module on it. 

Currently do you have to restart your agent every time your pipeline runs?

**Comment by iambernics** [comment] 2020-06-19 12:58
This is not possible: you introduced the --once argument for the ADO Agent, the Agent process will be stopped automatically when a Job completed if you are using this flag.
Our VM revert service will be triggered when a VM is stopped.
(You are using same way on Azure Pipelines Agent)

So, we could not restart the Agent anytime.

**Comment by AmrutaKawade** [comment] 2020-08-19 13:07
Are you still facing issue? In previous issue you had mentioned that its working with Az Module Task version 4.0. is it breaking for this module as well?

**Comment by iambernics** [comment] 2020-08-19 18:38
There is no relation with the AZ or Azure RM versions. The issue is still exists.

```
##[debug]At D:\build\V1\_w\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\3.171.2\ps_modules\VstsAzureHelpers_\InitializeFunctions.ps1:372 char:17
##[debug]+ ...     $null = Select-AzureRMSubscription -SubscriptionId $SubscriptionI ...
##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : CloseError: (:) [Set-AzureRmContext], ArgumentEx    ception
##[debug]    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.SetAzureRMConte    xtCommand
##[debug] 
##[debug]Script stack trace:
##[debug]at Set-CurrentAzureRMSubscription, D:\build\V1\_w\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\3.171.2\ps_modules\VstsAzureHelpers_\InitializeFunctions.ps1: line 372
##[debug]at Initialize-AzureSubscription, D:\build\V1\_w\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\3.171.2\ps_modules\VstsAzureHelpers_\InitializeFunctions.ps1: line 248
##[debug]at Initialize-Azure, D:\build\V1\_w\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\3.171.2\ps_modules\VstsAzureHelpers_\VstsAzureHelpers_.psm1: line 59
##[debug]at <ScriptBlock>, D:\build\V1\_w\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\3.171.2\AzurePowerShell.ps1: line 86
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.ArgumentException: Please provide a valid tenant or a valid subscription.
##[debug]   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.SetCurrentContext(String subscriptionNameOrId, String tenantId, String name)
##[debug]   at Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand.<>c__DisplayClass37_1.<ExecuteCmdlet>b__2(AzureRmProfile profile, RMProfileClient client, String name)
##[debug]   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
##[debug]   at Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
##[debug]   at Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand.ExecuteCmdlet()
##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()

```

**Comment by AmrutaKawade** [comment] 2020-08-31 06:08
Can you share snapshots how your pipeline is configured?

**Comment by 20shivangi** [comment] 2020-09-07 06:40
We are unable to repro this issue at our end. Can you please answer above question : how the pipeline is configured and which az/azurerm module are you using ?

**Comment by 20shivangi** [comment] 2020-09-09 05:59
@iambernics Are you still facing the issue ?

**Comment by 20shivangi** [comment] 2020-09-11 09:57
@iambernics Are you still blocked ? If yes, let us know.

**Comment by 20shivangi** [comment] 2020-09-16 17:54
We are closing the issue since we did not get any response from long time. Please feel free to re-open it if you are facing the issue with attached above details.

**Closed by 20shivangi** 2020-09-16 17:54 UTC
Labels: Area: Release, question
