### ISSUE TITLE
project.json doesn't have a runtimes section, add '“runtimes”: { “win”: { } }' to project.json

### ISSUE THREAD

**Issue by PrasadSudama** [Microsoft/azure-pipelines-tasks#5931] opened 2017-11-28 04:48 UTC
## Environment
- Server - VSTS 
- Agent -  Private:     
    
## Issue Description
Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.

### Error logs
2017-11-28T02:43:50.4396191Z ##[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(178,5): Error : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.
2017-11-28T02:43:50.4396191Z C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(178,5): error : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore. [F:\_agent\_work\7\s\src\test\***.Api.Tests.Functional\***.Tests.Functional.csproj]

**Comment by PrasadSudama** [comment] 2017-11-28 09:12
I have resolved the issue. I have to change the project build template. There was a migration from project.json to csproj (VS2015 to VS2017) but that was going fine for quite some time now but some how it started breaking recently.

I changed the project build template as below:
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <RuntimeIdentifier>x64</RuntimeIdentifier>
    <AssemblyName>SomeAPI.Api.Tests.Functional</AssemblyName>
    <PackageId>SomeAPI.Api.Tests.Functional</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
    <None Update="HSBC.MIP.Servicing.ApplicationUpload.Api.Tests.Functional.dll.config.MIP-02-DV1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="HSBC.MIP.Servicing.ApplicationUpload.Api.Tests.Functional.dll.config.MIP-02-DV2">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="HSBC.MIP.Servicing.ApplicationUpload.Api.Tests.Functional.dll.config.MIP-02-ST2">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="HSBC.MIP.Servicing.ApplicationUpload.Api.Tests.Functional.dll.config.MIP-02-ST3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="HSBC.MIP.Servicing.ApplicationUpload.Api.Tests.Functional.dll.config.MIP-02-ST4">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="HSBC.MIP.Servicing.ApplicationUpload.Api.Tests.Functional.dll.config.MIP-02-ST5">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="InvalidMessages\ApplicationUpload-Invalid-Residence-Type-Message.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="InvalidMessages\ApplicationUpload-Invalid-Type-Of-Buyer-Message.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Valid Messages\ApplicationUpload-Request_Message.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ValidMessages\ApplicationUpload-Request-Message.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>`

**Comment by pekkah** [comment] 2018-01-12 08:39
I'm hitting this same issue. Builds have been working just fine but during the past two weeks something has changed which has made this issue appear. Upgrading to new CSPROJ format fixes it but for some of our projects that is not an option as they contain Entity Framework edmx files.

**Comment by pekkah** [comment] 2018-01-12 08:50
Here's the logs
```
6>EntityDeployNonEmbeddedResources:
       Skipping target "EntityDeployNonEmbeddedResources" because it has no outputs.
       EntityDeployEmbeddedResources:
         Processing 1 EDMX files.
         Starting to process input file 'Model1.edmx'.
    10>EntityDeployEmbeddedResources:
         Finished processing input file 'Model2.edmx'.
         Finished processing 1 EDMX files.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(186,5): Error : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.
````

**Comment by HeinzmeierDornbuschFeldhausen** [comment] 2018-01-23 08:35
All of a sudden I had this error even when using the old (non-sdk) project format for a f# project.

References didn't show up even though the project file included them. Cleaning bin and obj folders helped. Just in case someone stumbles on the same problem. Very weird.

**Comment by huanlin** [comment] 2018-04-15 13:28
I had the same issue today. Then I found this post:[MSBuild Your project.json doesn't have a runtimes section](https://social.msdn.microsoft.com/Forums/vstudio/en-US/0fe54fd3-9511-4c27-a746-9dd4338345a5/msbuild-your-projectjson-doesnt-have-a-runtimes-section?forum=msbuild)

And adding the following section solved my problem:
```
<PropertyGroup>
    <RuntimeIdentifiers>win;osx.10.11-x64;ubuntu.16.04-x64</RuntimeIdentifiers>
</PropertyGroup>
```

**Comment by nullpainter** [comment] 2018-04-18 01:17
Funnily enough, _removing_ the `<RuntimeIdentifier>` from a troublesome project resolved this issue.

**Comment by shurane** [comment] 2018-05-21 09:06
For me, I had a `projects.assets.json` generated in the `obj/` directory, cleaning that out resolved the issue. Anyone know the root of this problem?

**Comment by misterspeedy** [comment] 2018-06-13 15:46
@shurane Your solution fixed it for me too.

**Comment by ConnorChristie** [comment] 2018-07-30 19:03
Yes, it seems to be the `projects.assets.json` file that is causing the problem. If you have a large amount of sub-projects, you can use `rm -rf ./**/*/obj` in the solution dir to delete all the obj folders

**Comment by replaysMike** [comment] 2018-08-02 00:35
For me I've been unable to resolve it as of yet, cleaning bin/obj didn't remove the error. For me it only happens using msbuild and does not occur using VS2017.

**Comment by rajkishor09** [comment] 2019-02-01 07:33
this SO answer helped to fix the issue https://stackoverflow.com/a/36211569/173613.

**Comment by alexmullans** [comment] 2019-04-01 22:40
Closing this as it's not a bug with the build tasks. Please see the SO answer shared above this comment.

**Closed by alexmullans** 2019-04-01 22:40 UTC
Labels: Area: Artifacts
