### ISSUE TITLE
[BUG]: DockerCompose@1 not running on linux system

### ISSUE THREAD

**Issue by p-hlp** [microsoft/azure-pipelines-tasks#20368] opened 2024-08-29 12:09 UTC
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

DockerCompose

### Task version

1.243.1

### Issue Description

We've been getting the docker compose v1 deprecation warning for a while (using `DockerCompose@0`) and wanted to swap over to the new `DockerCompose@1` task, but ran into the following issue when testing:

>The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

The [docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/docker-compose-v1?view=azure-pipelines) for the `DockerCompose@1` don't say anything about windows only, so I'm kinda surprised.

Environment:
- OS: 20.04.6 LTS
- Compose Version: `1.25.5` and `2.18.1` are both available

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

20.04.6 LTS

### Relevant log output

```shell
2024-08-29T07:06:33.6402445Z ##[section]Starting: Compose Up
2024-08-29T07:06:33.6411241Z ==============================================================================
2024-08-29T07:06:33.6411585Z Task         : Docker Compose
2024-08-29T07:06:33.6411761Z Description  : Build, push or run multi-container Docker applications. Task can be used with Docker or Azure Container registry.
2024-08-29T07:06:33.6412086Z Version      : 1.243.1
2024-08-29T07:06:33.6412230Z Author       : Microsoft Corporation
2024-08-29T07:06:33.6412416Z Help         : https://aka.ms/azpipes-docker-compose-tsg
2024-08-29T07:06:33.6412616Z ==============================================================================
2024-08-29T07:06:33.6547697Z ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
2024-08-29T07:06:33.6559695Z ##[section]Finishing: Compose Up
```

### Repro steps

```yml
jobs:
  - deployment: ${{ parameters.jobName }}
    displayName: ${{ parameters.displayName }}
    environment:
      name: ${{ parameters.environmentName }}
      resourceName: ${{ parameters.resourceName }}
      resourceType: ${{ parameters.resourceType }}
    strategy:
      runOnce:
        preDeploy:
          steps:
            - checkout: self
              clean: true
        deploy:
          steps:
            - download: none
            - task: DockerCompose@1
              inputs:
                containerregistrytype: 'Azure Container Registry'
                azureSubscription: 'ExampleSubscription'
                azureContainerRegistry: '{"loginServer":"example.azurecr.io", "id" : "/subscriptions/example"}'
                dockerComposeFile: ${{ parameters.dockerComposeFile }}
                action: 'Run a Docker Compose command'
                dockerComposeCommand: 'up -d'
                projectName: ${{ parameters.dockerProjectName }}
              displayName: Compose Up
              env:
                # Some secrets
```

**Comment by v-schhabra** [comment] 2024-09-02 05:57
Hi @p-hlp 
Thanks for reporting this issue. Will check and update here.

**Comment by chamindu** [comment] 2024-09-03 05:25
I am facing the same issue.

**Comment by tomdess** [comment] 2024-09-12 08:18
hello, same issue here, is it required powershell even on linux now?

**Comment by ndege7** [comment] 2024-09-13 07:47
gettig the same error any update

**Comment by p-hlp** [comment] 2024-09-17 13:04
@v-schhabra any updates on this?

**Comment by v-schhabra** [comment] 2024-09-23 04:48
Hi, apologies for replying late. Our team was occupied with some high priority issues. We have started investigation on this issue now.

**Comment by v-schhabra** [comment] 2024-09-25 10:09
Hi @p-hlp @chamindu @tomdess @ndege7 
Could you please let us know which agent version you are using in your task?

**Comment by tomdess** [comment] 2024-09-25 12:39
hello, i'm having the error "2024-09-25T12:29:46.9383033Z ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell." running a release pipeline (classic) in which the DockerCompose@0 tasks are replaced with DockerCompose@1 tasks (the pipeline works fine with DockerCompose@0 tasks). The pipeline is running on a Deployment group target with agent version "3.230.0" (self-hosted agent), docker release installed 24.0.6, Debian 10.

**Comment by v-schhabra** [comment] 2024-09-25 18:24
For DockerComposeV1 task we are using Node20_1 executor (https://github.com/microsoft/azure-pipelines-tasks/blob/c79a3c71c8ce5df6d5982ead885e6369216ab0bd/Tasks/DockerComposeV1/task.json#L338C6-L338C14) and this handler support minimum agent version 3.232.1.([azure-pipelines-tasks/docs/migrateNode20.md at c79a3c71c8ce5df6d5982ead885e6369216ab0bd · microsoft/azure-pipelines-tasks (github.com)](https://github.com/microsoft/azure-pipelines-tasks/blob/c79a3c71c8ce5df6d5982ead885e6369216ab0bd/docs/migrateNode20.md#specify-minimumagentversion))
Could you please upgrade your agent and check if the issue is still occurring or not?

**Comment by tomdess** [comment] 2024-09-25 21:15
bingo! after agent upgrade (to release 3.244.1) the issue is solved, thank you.

The agent auto-update is not working on this machine, maybe because behind a proxy, but this is another story....

**Comment by v-schhabra** [comment] 2024-09-26 06:58
Hi @tomdess 
Could you please add variable system.debug to "true" and share the complete pipeline failed logs?

**Comment by tomdess** [comment] 2024-09-27 15:00
sorry but i have no other agents with old version (< 3.232.1), it was the only one

**Comment by p-hlp** [comment] 2024-10-02 11:59
@v-schhabra Sorry for the late reply. Our agents are on version `3.241.0`. Here's a failed run with diagnostics on / `system.debug = true`.

```shell
2024-10-02T11:47:38.3225580Z ##[debug]Evaluating condition for step: 'Compose Up'
2024-10-02T11:47:38.3228334Z ##[debug]Evaluating: SucceededNode()
2024-10-02T11:47:38.3229274Z ##[debug]Evaluating SucceededNode:
2024-10-02T11:47:38.3231131Z ##[debug]=> True
2024-10-02T11:47:38.3231909Z ##[debug]Result: True
2024-10-02T11:47:38.3232498Z ##[section]Starting: Compose Up
2024-10-02T11:47:38.3242444Z ==============================================================================
2024-10-02T11:47:38.3242838Z Task         : Docker Compose
2024-10-02T11:47:38.3243024Z Description  : Build, push or run multi-container Docker applications. Task can be used with Docker or Azure Container registry.
2024-10-02T11:47:38.3243346Z Version      : 1.243.1
2024-10-02T11:47:38.3243521Z Author       : Microsoft Corporation
2024-10-02T11:47:38.3243719Z Help         : https://aka.ms/azpipes-docker-compose-tsg
2024-10-02T11:47:38.3244194Z ==============================================================================
2024-10-02T11:47:38.3391633Z ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
2024-10-02T11:47:38.3405157Z ##[debug]System.InvalidOperationException: The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync() in /home/vsts/work/1/s/src/Agent.Worker/TaskRunner.cs:line 168
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken) in /home/vsts/work/1/s/src/Agent.Worker/StepsRunner.cs:line 223
2024-10-02T11:47:38.3407252Z ##[section]Finishing: Compose Up
``` 

Doesn't really provide any extra information, but we're at least on a higher version than `3.232.1` which you mentioned the minimum.

**Comment by v-schhabra** [comment] 2024-10-07 06:43
Hi @p-hlp 
Could you pls share complete pipeline logs not just this task logs?

**Comment by v-schhabra** [comment] 2024-10-13 17:53
Closing this issue as we didnt received complete debugged logs to continue our investigation.

**Closed by v-schhabra** 2024-10-13 17:54 UTC
Labels: bug, Area: Release, triage

**Comment by felipeavilis** [comment] 2024-11-12 12:13
The problem persists. I'm still using  `DockerCompose@0`.

**Comment by v-schhabra** [comment] 2024-11-13 05:18
Hi @felipeavilis 
Could you pls let us know which agent version you are using?

**Comment by felipeavilis** [comment] 2024-11-13 14:25
> Hi [@felipeavilis](https://github.com/felipeavilis) Could you pls let us know which agent version you are using?

Sure! Here ar some info.

```
Agent Version: v3.230.0 (commit 38c1c98)
OS: CentOS Stream 9
```
