### ISSUE TITLE
Info_DownloadingArtifactTool

### ISSUE THREAD

**Issue by FrancescElies** [microsoft/azure-pipelines-tasks#11588] opened 2019-10-18 08:49 UTC
## Required Information

**Type**: Bug (maybe)
**Task Name**: DownloadPackage

## Environment
Azure Piepelines.

## Issue Description
When I use `DownloadPackage@1`, even though everything seems to be fine I always get the following warning:
![image](https://user-images.githubusercontent.com/6558089/67078895-7f040580-f192-11e9-9d4d-e23dc313f7bb.png)

I only found `Info_DownloadingArtifactTool` [here](https://github.com/microsoft/azure-pipelines-tasks/blob/775cd939144c2c8bb03596a148358bcb223fdd9f/Tasks/Common/packaging-common/universal/ArtifactToolUtilities.ts#L83) but it's a debug statement not a warning.

What does this warning mean?

**Comment by salvmd** [comment] 2019-11-13 18:01
Thanks for bringing this up. This is a bug in the task. This key is used to look up a localized string, which should be defined in the task configuration. The problem is that [this code](https://github.com/microsoft/azure-pipelines-tasks/blob/775cd939144c2c8bb03596a148358bcb223fdd9f/Tasks/Common/packaging-common/universal/ArtifactToolUtilities.ts#L83) is used in two tasks: UniversalPackages and DownloadPackage, but only UniversalPackages has the string defined in its configuration. Whenever this is run from DownloadPackage, the task fails to find the localized string and displays the warning.

We will get this fixed. Other than not being able to display that particular debug message, this issue should not have any other impact.

**Comment by salvmd** [comment] 2019-11-13 19:47
The issue has been fixed in code. It will get released in the next deployment of Azure Pipelines Tasks

**Closed by salvmd** 2019-11-13 19:47 UTC
Labels: Area: ArtifactsPackages, bug

**Comment by FrancescElies** [comment] 2019-11-18 11:45
@salvmd Wouldn't it have been better to close the issue after the next deployment? When is it going to take place?
