### ISSUE TITLE
AzureResourceManagerTemplateDeployment and weird sas token encoding

### ISSUE THREAD

**Issue by nulltoken** [microsoft/azure-pipelines-tasks#14197] opened 2021-01-08 13:34 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceManagerTemplateDeployment 

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Issue Description

`AzureResourceManagerTemplateDeployment@3` and `AzureResourceGroupDeployment@2` seem to behave slightly differently when it comes to retrieving armOutputs of sas tokens.

It looks like using `AzureResourceManagerTemplateDeployment@3` to deploy a storage account adds some kind of additional layer of url encoding to the generated sas token.

Given an ARM template which generates the following output:

```
{
 [...]
  "outputs": {
    "test": {
      "type": "string",
      "value": "[listServiceSas(parameters('storageName'), '2018-02-01', variables('routingContainerSas')).serviceSasToken]"
    }
  }
}
```

Produced outputs are slightly different depending on the task that's been used to proceed with the ARM deployment:
**AzureResourceGroupDeployment@2**:
`sv=2015-04-05&sr=c&spr=https&se=2050-01-01T00%3A00%3A00.0000000Z&sp=r&sig=8KzSP7ccfvKqI8h%2FdARyajbZCTkxi3%2BEiN%2Fcxsa7eOA%3D`
**AzureResourceManagerTemplateDeployment@3**:
`sv=2015-04-05&sr=c&spr=https&se=2050-01-01T00%253A00%253A00.0000000Z&sp=r&sig=8KzSP7ccfvKqI8h%252FdARyajbZCTkxi3%252BEiN%252Fcxsa7eOA%253D`

The acute eye will notice that `%3A` turns into `%253A`, for instance.

The sas tokens retrieved through `AzureResourceManagerTemplateDeployment` aren't accepted when trying to access the blob storage.
Using the ones retrieved through `AzureResourceGroupDeployment` works ok though.

**Comment by bishal-pdMSFT** [comment] 2021-01-08 14:20
This issue could be due to encoding changes in newer task lib

**Comment by nulltoken** [comment] 2021-01-08 14:54
@bishal-pdMSFT For information,, below the version number of the tasks that have been used.

AzureResourceManagerTemplateDeployment (3.179.1)
AzureResourceGroupDeployment (2.179.0)

**Comment by bishal-pdMSFT** [comment] 2021-01-08 17:55
@nulltoken this is change in the pipeline agent behavior and not a bug with task. Agent is not decoding encoded `%`. Please see [here](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md) for more details. To enable decoding, please set an environment variable DECODE_PERCENTS to true for the task.

**Comment by nulltoken** [comment] 2021-01-09 11:45
@bishal-pdMSFT Thanks for the feedback. However your answer raises a ton of additional questions. I'd be very grateful if you could help me further understand by answering them.

Additional context info:
- Both tests have been run on the same agent on my side
- Agent version was 2.179.0

Questions (on-topic):
- My current understanding is that the execution of `AzureResourceGroupDeployment@2` and `AzureResourceManagerTemplateDeployment@3` on that agent didn't honor this `DECODE_PERCENTS` agent knob in the same way. Am I correct? Is that expected?
- The linked documentation about percent encoding isn't very clear to me (sorry if I may be a little thick :-/):
  - Should it be read as "By default, env variable `DECODE_PERCENTS` will be set to `true` sometime in January 2021", which would allow sas token outputs processed by `AzureResourceManagerTemplateDeployment@3` to not contain this `%25`?
  - It refers to some "warnings" (of which I can find traces in https://github.com/microsoft/azure-pipelines-agent/blob/9b7f41f1e5710f37610208d8a9aca970cceaa379/src/Agent.Worker/WorkerCommandManager.cs#L136). However, in the two builds that I've run (one with each task), I haven't been able to find any warnings. Neither in the arm deployment task, nor in the powershell task I use to extract data out of the ARM outputs. Is that expected?

Additional off-topic question:
- There seems to be (at least) two (competing?) ways to create or update resources in an existing resource group through ARM templates (through the two tasks mentioned above). Is there one which should be favored?

**Comment by nulltoken** [comment] 2021-01-19 10:47
@bishal-pdMSFT Kind bump?

**Comment by nulltoken** [comment] 2021-01-22 10:19
@bishal-pdMSFT It looks like version `AzureResourceGroupDeployment` 2.180 is now being used on our release agents. And the encoding issue is now back.

Could you please check my previous comment and the questions and help me understand how to properly deal with this?

**Comment by nulltoken** [comment] 2021-01-22 13:28
@bishal-pdMSFT I've tried to move the thing a little bit further.

I've updated the task we use to extract the outputs from the ARM to explicitly set the env variable `DECODE_PERCENTS`

**Comment by kikisaeba** [comment] 2021-01-22 15:59
Hello @bishal-pdMSFT,

We meet the same issue in our pipeline. Our production delivery is impacted.
Could you help us to understand and fix it ?

Thanks

**Comment by bishal-pdMSFT** [comment] 2021-02-09 18:58
Sorry this went under radar. Adding @damccorm who can answer your [questions](https://github.com/microsoft/azure-pipelines-tasks/issues/14197#issuecomment-757137629) better.

**Comment by ddivanshu** [comment] 2021-02-10 16:28
@nulltoken 
As suggested by [here](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md)
could you set job variable DECODE_PERCENTS to true either in workflow or through UI instead of environment variable.That will work for you
```jobs:
- job:
  variables:
  - name: DECODE_PERCENTS
    value: true

  steps:
  - powershell: Write-Host '##vso[task.setvariable variable=test]a%AZP25'
    displayName: 'Set Variable'

  # This will print the a% correctly as the value of test
  - powershell: 'Get-ChildItem env:'
    displayName: 'printenv'
```

**Comment by ddivanshu** [comment] 2021-05-24 20:54
Closing this .
Feel free to reopen if issue persists again

**Closed by ddivanshu** 2021-05-24 20:54 UTC
Labels: Area: Release, bug
