### ISSUE TITLE
Artifacts can't be found if artifactname and containerfolder aren't the same

### ISSUE THREAD

**Issue by Duracell1989** [microsoft/azure-pipelines-tasks#14170] opened 2021-01-04 14:44 UTC
# Required Information
I'm not sure if this is a _bug_ or that I'm doing something wrong (_question_).

## Environment
- Server - Azure Pipelines
- Agent - Private
  - Agent.Version: 2.175.2
  - Agent.OS: Windows_NT
  - Agent.OSArchitecture: X64
  - Agent.OSVersion: 10.0.17763

## Issue Description
I'm trying to move my Azure pipeline (yaml) build towards Nuke.
Via Nuke; we're uploading artifacts so that these can be used later on.
After the (successful) build; the output states: 1 artifact produced; and when you click this link, the artifact (zip-file) is visible and can even be downloaded. So, this works.
But, when looking for the linked artifact inside the (Azure DevOps) Release=>Pipeline=>Stage - I get the error: `Artifact Staging was not found for build xxxx`.
![Package not found](https://user-images.githubusercontent.com/18702736/103545021-43da1900-4ea1-11eb-8fe9-9f590c5baed5.png)

So, after investigating [the documentation](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md)
Looking at the (old) debug output from our build:
```
ORIGINAL
##[debug]Processed: ##vso[artifact.upload
artifacttype=container;
artifactname=FOO.zip;
containerfolder=FOO.zip;
localpath=F:\BldVM01\Agent01\3\s\Staging\FOO.zip;
]F:\BldVM01\Agent01\3\s\Staging\FOO.zip
```
Looking at my new code:
### FAILS
```
##[debug]Processed: ##vso[artifact.upload
artifactname=FOO.zip;
containerfolder=Staging;
artifacttype=container;
localpath=F:\BldVM01\Agent01\1\s\artifacts\Staging\FOO.zip
]F:\BldVM01\Agent01\1\s\artifacts\Staging\FOO.zip
```
### WORKS
```
##[debug]Processed: ##vso[artifact.upload
artifactname=FOO.zip;
containerfolder=FOO.zip;
artifacttype=container;
localpath=F:\BldVM01\Agent01\1\s\artifacts\Staging\FOO.zip
]F:\BldVM01\Agent01\1\s\artifacts\Staging\FOO.zip
```

This is only with 1 artifact; what I want to achieve is having multiple artifacts inside the same (parent) folder - but that isn't possible if the folder name should be the same as the name of the artifact for it to be visible/select-able in the Release=>Pipeline=>Stage.

So, the question here is:
Is is a bug that the _artifactname_ and _containerfolder_ should be the same or is there something I'm doing wrong?

**Comment by Duracell1989** [comment] 2021-01-20 09:19
Any update on this?

**Comment by egor-bryzgalov** [comment] 2021-02-03 13:13
@Duracell1989 Hi! We've managed to reproduce the issue and it seems to be related to Azure DevOps. Could you please open an issue at https://developercommunity.visualstudio.com/ at the Azure DevOps tab?
Closing this issue since it's not related to tasks.
Thank you!

**Closed by egor-bryzgalov** 2021-02-03 13:13 UTC
Labels: Area: Artifacts, bug, question
