### ISSUE TITLE
[Question]: Keep getting "Error: Npm failed with return code: 217" while installing Angular CLI using the NPM task when building using our self hosted build agent. The only solution I've found is to remote in and delete the _work directory for the agent. Any suggestions?

### ISSUE THREAD

**Issue by edgariscoding** [microsoft/azure-pipelines-tasks#18416] opened 2023-05-31 17:08 UTC
### Task name

NPM

### Task version

1.221.0

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04

### Question

<img width="1567" alt="Screenshot 2023-05-31 at 10 16 44 AM" src="https://github.com/microsoft/azure-pipelines-agent/assets/12093243/a8edfec8-2159-4163-99e9-f8443ee66e1b">

We have two separate agents on the same server. Sometimes this happens to only one of the agents, sometimes it's both. Regardless, the only solution is to delete the _work directory for the agent having issues.

I've tried enabling the "Clean Build Directories" option in the build pipeline and it doesn't seem to make a difference because the issue is with the _work/_tool directory at the agent level.

Should I add a build task that runs 'rm -rf _work'? Thats what I've been having to do every time this happens. Is there any built in automated way of doing this?

Or I more than anything... any suggestions as to why this is failing in the first place? It succeeds for a few weeks then this will happen and I have to manually delete the work folder.

**Comment by kirill-ivlev** [comment] 2023-06-02 08:40
@edgariscoding thank you for reporting this,
this issue is a duplicate of https://github.com/microsoft/azure-pipelines-agent/issues/4302.
If you don't mind let's keep all discussion in one place.

**Closed by kirill-ivlev** 2023-06-02 08:40 UTC
Labels: Area: Release, triage, Area: Artifacts
