### ISSUE TITLE
Unable to use AzureKeyVault Secrets with hyphens in the name

### ISSUE THREAD

**Issue by FISHMANPET** [microsoft/azure-pipelines-tasks#10525] opened 2019-05-29 20:37 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureKeyVault

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted VS2017

## Issue Description

I'm not sure if this is a bug in the task or a bug with the documentation, but I can't seem to figure out how to use a secret from Azure Key Vault if the name of the secret has a hyphen in it.  According to documentation for secret variables, I can use `$(variablename)` or define an environment variable for the task with a value of `$(variablename)`.  Both of these methods work when the variable does not have a hyphen in it.  But when it does have a hyphen (say `variable-name`), the first method, calling it as `$(variable-name) in a powershell script does not work.  The following error is thrown:
`Exception: The term 'variable-name' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`
However setting an environment variable and using `$(variable-name) does work, however it's cumbersome as I have to define each variable in every task that needs it.

This behavior doesn't present itself when using variables I define directly as Pipeline variables, which is what leads me to believe it's something to do with The KeyVault task.  I'm not sure if there's some kind of transformation the task is doing to these variables that's causing them to behave differently.  If there's some kind of limitation in the task it should be well documented.

**Comment by rohit-batra** [comment] 2019-06-07 04:40
Hello Peter, 

Please correct me if i am missing something in my test setup but i used following .

1. I added a Key Vault task to fetch secrets from my test Keyvault and then i added another powershell task to refer them successfully

![image](https://user-images.githubusercontent.com/21075522/59081304-056a2a00-890b-11e9-8f3c-be1f6dac9d1d.png)

![image](https://user-images.githubusercontent.com/21075522/59081314-16b33680-890b-11e9-8025-49622233abc6.png)


My Release went successfully as you can see in this snapshot 

![image](https://user-images.githubusercontent.com/21075522/59081335-27fc4300-890b-11e9-8ede-ee20e2f91338.png)


2. Other thing which can be done is to create a variable group in Library and link it to the key vault and select desired secrets which you want to use. All these will become part of this variable group.
Now you can use this variable group in whichever release definition you want.

![image](https://user-images.githubusercontent.com/21075522/59081473-e8822680-890b-11e9-971b-b74a3c357e7c.png)

![image](https://user-images.githubusercontent.com/21075522/59081482-f768d900-890b-11e9-98c1-ea39bfb20f17.png)

![image](https://user-images.githubusercontent.com/21075522/59081552-5cbcca00-890c-11e9-823c-a5c26bb7aee9.png)



These two are the ways in which we can use Key vaults . Second method will allow you not to have Key vault task in different releases. Just link your release definition to the Variable group and all the variables in that variable group will be made available to the definition. 

As for the error message you are encountering , i was able to reproduce it by referring it to a non existent variable name 

Can you please verify if this is the case 

![image](https://user-images.githubusercontent.com/21075522/59081436-b2dd3d80-890b-11e9-85cb-df96607ce857.png)

**Comment by FISHMANPET** [comment] 2019-06-17 14:12
My scenario is using secrets from a variable group in a script, not inline.

I'm able to reproduce your success if I put similar commands in an inline script, but if I copy those exact commands into a ps1 file that I'm executing I get a failure.

These commands work:
![image](https://user-images.githubusercontent.com/7810151/59610478-166f2400-90df-11e9-86a2-68d83b2370b3.png)
They print out what I expect to the output (just `*`s).

This is my actual code, copy-pasted from the inline script into my ps1 file:
```
write-host $(AzureRunbooksCINoDash)
write-host $(AzureRunbooksCI-TenantID)
$(AzureRunbooksCI-TenantID)
$(AzureRunbooksCINoDash)
"$(hyphen-public)"
"$(hyphen-secret)"
```
That fails:
```
AzureRunbooksCINoDash : The term 'AzureRunbooksCINoDash' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At D:\a\1\s\Build\build.ps1:20 char:14
+ write-host $(AzureRunbooksCINoDash)
+              ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AzureRunbooksCINoDash:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Though this reveals something I thought I'd tested before I made this report but I apparently didn't, my variable with no dashes also fails.

Maybe this is intended behavior with secrets in general, but it's all very confusing.  If this is a bug with using secrets in a script then it's a bug.

If this is by design, then 1) it's stupid (why would it behave different for in-line scripts vs executing a file) and 2) that difference needs to be better documented.

**Comment by rohit-batra** [comment] 2019-06-18 04:47
Hello Peter,

This is not an issue with Key Vault variables, hyphenated or otherwise. This is how variables behave with inline and file based PS.
How this works is when we have inline script , the script is expanded with variables , then sent for processing. 
In case of PS file, its sent to processing as is and thus it will have visibility only of env variables and Variables passed as Argument to the script.  Not the regular variables or linked variables of variable groups. 

![image](https://user-images.githubusercontent.com/21075522/59653537-02dfbe00-91b0-11e9-9389-af700374b6e1.png)


In case you want to use Key Vault Variables inside the script which is not inline , i suggest you to use like 

![image](https://user-images.githubusercontent.com/21075522/59652511-9f539180-91ab-11e9-8752-75df21d3faa9.png)

![image](https://user-images.githubusercontent.com/21075522/59653040-0d00bd00-91ae-11e9-842a-fcd08e399089.png)

Or pass them as arguments. 

Regarding difference in behavior , it is allowed in inline  because that passes through our expansion engine/logic and thus we get to see variables getting expanded without having to add them in env variables.

This is the same behavior with regular pipeline variables as well. 
![image](https://user-images.githubusercontent.com/21075522/59653829-674f4d00-91b1-11e9-8003-19725adba483.png)
![image](https://user-images.githubusercontent.com/21075522/59653843-759d6900-91b1-11e9-8579-3121a168c484.png)
![image](https://user-images.githubusercontent.com/21075522/59653897-9b2a7280-91b1-11e9-97f6-2e74f0e243d2.png)


PS :: Env Variables , like shell variable support ASCII alphabet, numbers and _ (And other restriction like should start with alphabet etc)
Its not like you cannot use them , but they will not be realized like 
![image](https://user-images.githubusercontent.com/21075522/59653478-cad87b00-91af-11e9-8de5-19ad6e384471.png)

Adding @shashban to make sure documentation is correct here.

**Comment by bansalaseem** [comment] 2019-07-29 12:04
Closing this issue as per @rohit-batra's above comment.

**Closed by bansalaseem** 2019-07-29 12:04 UTC
Labels: Area: Release, bug

**Comment by craigmpeters** [comment] 2019-08-20 10:07
So close! How do you get a variable inside a PS File? I have tried but get nothing, no variables, no environment variables, no linked variables, totally 100% impossible to get any variables.

**Comment by choukimasri** [comment] 2021-06-14 11:12
Hello !, we're still having this issue despite the task promising a global scope on the prejob flag, and failing to deliver variables in file scripts, any updates ?

Thank you !

**Comment by artemkozlenkovvzug** [comment] 2022-11-25 13:25
this is a bug withing the Azure Keyvault, in which it requires to use hypen pattern when dotnet app consumes only undescored environment variables. Breaking change between native services.
