### ISSUE TITLE
*Feature Request*  PublishBuildArtifact - Filtering folder content

### ISSUE THREAD

**Issue by CasperWSchmidt** [microsoft/azure-pipelines-tasks#10220] opened 2019-04-25 06:54 UTC
We are running Azure Pipelines and earlier the build pipeline used the tasks "DotNet Publish" and "Publish Artifact" to zip and publish the build artifacts from ```$(Build.ArtifactStagingDirectory)```. Then, in the release pipeline, the "Azure App Service Deploy" task deployed the zip file and the Azure Function ran directly from it ("Run from package" option).
Because we need to access some of the files in the artifact during the release pipeline (DbUp task executing sql scripts against a database) we unchecked the zip option in "Dotnet Publish" task and switched to "Web Deploy" in "Azure App Service Deploy". However as part of the build artifact we have a GitflowBranchGate.ReportSummary.md that I do not want to be deployed.

A nice feature would be, to be able to make filtering on the selected folder (either in "Publish Artifact" or "Azure App Service Deploy" or maybe both?) so that all .md files are excluded.

Also, "Web Deploy" option is not automatically detected ("Zip Deploy" is used by default) when I select a folder and have "Select deployment method" unchecked. Perhaps this should be made into a seperate issue?

**Comment by vincentdass** [comment] 2019-04-29 05:02
@CasperWSchmidt , thanks for reaching out.
For the feature request, I ll let @Lovakumar and @omeshp  to comment and track the feature request.


`Also, "Web Deploy" option is not automatically detected ("Zip Deploy" is used by default) when I select a folder and have "Select deployment method" unchecked. Perhaps this should be made into a seperate issue?`
This is by design.  Zip Deploy is the recommended way by App Service team to deploy the web package.

**Comment by CasperWSchmidt** [comment] 2019-04-29 06:18
"This is by design. Zip Deploy is the recommended way by App Service team to deploy the web package." 
It's fair to have a recommended way, but not finding a zip file in the folder should still fall back to web deploy instead doing nothing. 
BTW. Any recommendations for doing zip deployment with the mentioned need for individual files in the release pipeline?

**Comment by vincentdass** [comment] 2019-04-29 08:17
@CasperWSchmidt , if a folder is provided, it is compressed to a zip file and then deployed using `zip deploy`.
For deploying only the required files, I could think of using a `copy file(s)` task to copy the artifact (with filters to eliminate MD files) and then publish that as an artifact. or use a `cmd` task to scrub all MD files from the artifact directory before publishing.

**Comment by omeshp** [comment] 2019-04-29 09:48
Since we are moving to pipeline based artifacts adding @mitchdenny for the ask of pattern based filtering in publish artifacts.

**Comment by mitchdenny** [comment] 2019-10-02 06:11
@elbatk could you help route this to the right folks? Not sure who is looking after this now.

**Comment by fadnavistanmay** [comment] 2019-10-02 16:53
Hi @CasperWSchmidt , for the "Publish Artifact" - Can you try using "Publish Pipeline Artifact" task. And in your publish directory, you can use the .artifactignore option to filter, which files you don't want to publish. - https://docs.microsoft.com/en-us/azure/devops/artifacts/reference/artifactignore?view=azure-devops

**Comment by CasperWSchmidt** [comment] 2019-10-02 19:57
@fadnavistanmay I'm sorry but I'm no longer assigned to that project. The .artifactignore approach looks promising though. I will keep that in mind for the new project I'm working on.

**Comment by fadnavistanmay** [comment] 2019-10-02 20:00
Hi @CasperWSchmidt - sounds good. I'll close this issue.
Feel free to reach out for any future requests.

**Closed by fadnavistanmay** 2019-10-02 20:00 UTC
Labels: Area: ArtifactsCore, Area: ArtifactsPackages
