### ISSUE TITLE
ParserError for AzurePowerShell@5 on Ubuntu

### ISSUE THREAD

**Issue by HansMusterWhatElse** [microsoft/azure-pipelines-tasks#15471] opened 2021-11-03 10:08 UTC
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  AzurePowerShell@5

## Environment

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: **_(can provide on request)_**

## Issue Description

On one of our live environments we currently receive the following error which leaks parts of our secrets in plain text to the console:

![image](https://user-images.githubusercontent.com/12280659/140037872-21ed4f87-9e1f-44f3-ae64-e13f1e98a268.png)

As part of our deployment pipeline we currently run a very simple inline Powershell script to disable some triggers in our data factory (shouldn't be relevant for this bug).

```
 - task: AzurePowerShell@5
    displayName: Disable Datafactory Pipeline triggers
    inputs:
      ScriptType: 'InlineScript'
      azureSubscription: $(azureSubscription)
      azurePowerShellVersion: 'LatestVersion'
      Inline: |
        $triggersADF = Get-AzDataFactoryV2Trigger -DataFactoryName '$(dataFactoryName)' -ResourceGroupName '$(applicationResourceGroup)' -ErrorAction SilentlyContinue
        if ($triggersADF -ne $null) {
          $triggersADF | ForEach-Object { Stop-AzDataFactoryV2Trigger -ResourceGroupName '$(applicationResourceGroup)' -DataFactoryName '$(dataFactoryName)' -Name $_.name -Force }
        }
```

### When does this task fail?

- If we run it with  `ubuntu-latest` and we use a `secret `/ `servicePrincipalKey` with an opening bracket character.

### When does this task pass?

- If we run it with  `windows-2019`  (even with any `( `characters)
- If we run it with  `ubuntu-latest`   (without any `( `characters)

```
{
....
"subscriptionID": "xxxxxxxxxxxxxxxxxxxxx",
"subscriptionName": "xxxxxxxxxxxxxxxxxxxx",
"servicePrincipalKey": "xxxxxxxxxxxxx(xxxxxxxxxxxxxx",
....
"secret": "xxxxxxxxxxxxx(xxxxxxxxxxxxx",
....

}
```

### Error logs

Below you can find a sanitized extract of our logs for the corresponding task:

The secrets which get leaked out (only on the live environment which uses a `(` character) were replaced with `xxxxxxxxxxxxxxxxxxxxxxxxxxxxx`.

At the point where the parsing errors happens, only parts of the secret are being displayed.

```
....
2021-11-02T14:35:46.5819847Z ##[debug]ScriptArguments=undefined
2021-11-02T14:35:46.5820655Z ##[debug]FailOnStandardError=false
2021-11-02T14:35:46.5821513Z ##[debug]TargetAzurePs=LatestVersion
2021-11-02T14:35:46.5822315Z ##[debug]CustomTargetAzurePs=undefined
2021-11-02T14:35:46.5823350Z ##[debug]ConnectedServiceNameARM=02d49462-c212-4198-9499-a349714c4a19
2021-11-02T14:35:46.5826483Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 auth scheme = ServicePrincipal
2021-11-02T14:35:46.5827826Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 data subscriptionid = DummySubscriptionGUID
2021-11-02T14:35:46.5829034Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 data subscriptionname = DummySubscriptionName
2021-11-02T14:35:46.5830824Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 auth param serviceprincipalid = ***
2021-11-02T14:35:46.5832102Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 data environmentAuthorityUrl = https://login.windows.net/
2021-11-02T14:35:46.5833477Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 auth param tenantid = ***
2021-11-02T14:35:46.5834684Z ##[debug]02d49462-b712-4198-9499-a348714c4f19=https://management.azure.com/
2021-11-02T14:35:46.5835823Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 data environment = AzureCloud
2021-11-02T14:35:46.5836943Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 auth scheme = ServicePrincipal
2021-11-02T14:35:46.5838047Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 data msiclientId = undefined
2021-11-02T14:35:46.5839273Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 data activeDirectoryServiceEndpointResourceId = https://management.core.windows.net/
2021-11-02T14:35:46.5841531Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 data AzureKeyVaultServiceEndpointResourceId = https://vault.azure.net
2021-11-02T14:35:46.5843108Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 data AzureKeyVaultDnsSuffix = vault.azure.net
2021-11-02T14:35:46.5844125Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 data ScopeLevel = Subscription
2021-11-02T14:35:46.5845157Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 auth param authenticationType = ***
2021-11-02T14:35:46.5845951Z ##[debug]credentials spn endpoint
2021-11-02T14:35:46.5846988Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 auth param serviceprincipalkey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2021-11-02T14:35:46.5848361Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 data EnableAdfsAuthentication = false
2021-11-02T14:35:46.5849359Z ##[debug]02d49462-b712-4198-9499-a348714c4f19 auth param apitoken = undefined
2021-11-02T14:35:46.5852947Z ##[debug]{"subscriptionID":"DummySubscriptionGUID","subscriptionName":"DummySubscriptionName","servicePrincipalClientID":"***","environmentAuthorityUrl":"https://login.windows.net/","tenantID":"***","url":"https://management.azure.com/","environment":"AzureCloud","scheme":"ServicePrincipal","activeDirectoryResourceID":"https://management.azure.com/","azureKeyVaultServiceEndpointResourceId":"https://vault.azure.net","azureKeyVaultDnsSuffix":"vault.azure.net","scopeLevel":"Subscription","authenticationType":"***","servicePrincipalKey":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxx","isADFSEnabled":false,"applicationTokenCredentials":{"clientId":"***","domain":"***","baseUrl":"https://management.azure.com/","authorityUrl":"https://login.windows.net/","activeDirectoryResourceId":"https://management.azure.com/","isAzureStackEnvironment":false,"authType":"***","secret":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxx","isADFSEnabled":false}}
2021-11-02T14:35:46.5855638Z ##[debug]workingDirectory=/home/vsts/work/1/s
2021-11-02T14:35:46.5856351Z ##[debug]check path : /home/vsts/work/1/s
2021-11-02T14:35:46.5856935Z Generating script.
2021-11-02T14:35:46.5857458Z ##[debug]Agent.Version=2.194.0
2021-11-02T14:35:46.5858129Z ##[debug]agent.tempDirectory=/home/vsts/work/_temp
2021-11-02T14:35:46.5858816Z ##[debug]check path : /home/vsts/work/_temp
2021-11-02T14:35:46.5925590Z ##[debug]which 'pwsh'
2021-11-02T14:35:46.5934528Z ##[debug]found: '/usr/bin/pwsh'
2021-11-02T14:35:46.5935699Z ##[debug]which '/usr/bin/pwsh'
2021-11-02T14:35:46.5936798Z ##[debug]found: '/usr/bin/pwsh'
2021-11-02T14:35:46.5937852Z ##[debug]/usr/bin/pwsh arg: -NoLogo
2021-11-02T14:35:46.5938877Z ##[debug]/usr/bin/pwsh arg: -NoProfile
2021-11-02T14:35:46.5939911Z ##[debug]/usr/bin/pwsh arg: -NonInteractive
2021-11-02T14:35:46.5940966Z ##[debug]/usr/bin/pwsh arg: -ExecutionPolicy
2021-11-02T14:35:46.5941851Z ##[debug]/usr/bin/pwsh arg: Unrestricted
2021-11-02T14:35:46.5942797Z ##[debug]/usr/bin/pwsh arg: -Command
2021-11-02T14:35:46.5943897Z ##[debug]/usr/bin/pwsh arg: . '/home/vsts/work/_temp/5cb72b91-a7b5-49ef-930a-35fff6ac879d.ps1'
2021-11-02T14:35:46.5945019Z ##[debug]exec tool: /usr/bin/pwsh
2021-11-02T14:35:46.5945806Z ##[debug]arguments:
2021-11-02T14:35:46.5946772Z ##[debug]   -NoLogo
2021-11-02T14:35:46.5947887Z ##[debug]   -NoProfile
2021-11-02T14:35:46.5948847Z ##[debug]   -NonInteractive
2021-11-02T14:35:46.5949795Z ##[debug]   -ExecutionPolicy
2021-11-02T14:35:46.5950613Z ##[debug]   Unrestricted
2021-11-02T14:35:46.5951510Z ##[debug]   -Command
2021-11-02T14:35:46.5952526Z ##[debug]   . '/home/vsts/work/_temp/5cb72b91-a7b5-49ef-930a-35fff6ac879d.ps1'
2021-11-02T14:35:46.5953804Z [command]/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/home/vsts/work/_temp/5cb72b91-a7b5-49ef-930a-35fff6ac879d.ps1'
2021-11-02T14:35:46.6004670Z Saved!
2021-11-02T14:35:47.4518551Z [91mParserError: [0m/home/vsts/work/_temp/5cb72b91-a7b5-49ef-930a-35fff6ac879d.ps1:4
2021-11-02T14:35:47.4519237Z [96mLine |
2021-11-02T14:35:47.4520249Z [96m   4 | [0m … kEnvironment":false,"authType":"***","secret":"xxxxxxxxxxxxxxxxxx…
2021-11-02T14:35:47.4520986Z [96m     | [91m                                                                ~
2021-11-02T14:35:47.4521580Z [91m[96m     | [91mMissing closing ')' in expression.
2021-11-02T14:35:47.4522272Z [0m
2021-11-02T14:35:47.4659566Z ##[debug]Exit code 1 received from tool '/usr/bin/pwsh'
2021-11-02T14:35:47.4665033Z ##[debug]STDIO streams have closed for tool '/usr/bin/pwsh'
2021-11-02T14:35:47.4675599Z ##[debug]task result: Failed
2021-11-02T14:35:47.4720320Z ##[error]PowerShell exited with code '1'.
2021-11-02T14:35:47.4730019Z ##[debug]Processed: ##vso[task.issue type=error;]PowerShell exited with code '1'.
2021-11-02T14:35:47.4738469Z ##[debug]Processed: ##vso[task.complete result=Failed;]PowerShell exited with code '1'.
2021-11-02T14:35:47.4753057Z ##[section]Finishing: Disable Datafactory Pipeline triggers
```

**Comment by v-jkarri** [comment] 2021-12-09 07:12
Can you please share us the complete logs of both windows-2019 and ubuntu-latest for this task?

**Comment by v-jkarri** [comment] 2021-12-24 06:13
We are closing this issue since we didn't get info. Please feel free to reopen the issue still facing the issue.

**Closed by v-jkarri** 2021-12-24 06:13 UTC
Labels: Task: AzurePowerShell, environment:under-investigation

**Comment by jshall** [comment] 2022-04-07 21:14
@v-jkarri I have a similar issue. I believe in my case it is because my subscription name contains an `'` which is not escaped in the stringified endpointObject.
I am willing to share my complete log directly, but like the OP I am hesitant to publish the full endpoint data on a public issue.

**Comment by anjagusev** [comment] 2022-04-08 14:00
I am also facing this issue. I simplified my PowerShell inline script to simply output "test" and it's still failing. 

Here is my pipeline 

```
trigger:
  branches:
    exclude:
      - main

variables:
- name: "ResourceGroup"
  value: "think-week-pr"

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true


  - task: AzurePowerShell@5
    displayName: 'Print'
    enabled: true
    inputs:
      azureSubscription: ThinkWeekPRService 
      ScriptType: 'InlineScript'
      Inline: |
        Write-Output test
      TargetAzurePs: latestVersion
      pwsh: true
```

Here is my service connection 
![image](https://user-images.githubusercontent.com/3604461/162450532-dbcb85f4-11e3-4363-b2f9-ad7ddd9173d7.png)

And here are my exceptions 
![image](https://user-images.githubusercontent.com/3604461/162450950-c3420093-5982-4795-b64b-8f0f4dfd0fe1.png)

**Comment by antonGritsenko** [comment] 2022-08-03 09:13
@v-jkarri can you re-opn that one? Really annoying to close live tickets.

**Comment by antonGritsenko** [comment] 2022-08-03 09:18
The problem is very simple: if any of the connection string's element (secret, subscription name, any in the long line) have special characters that can be treated as separators (breakets, single quote, double quote etc) - the powershell failed. 
Shame, guys, really shame. Student's mistake.
