### ISSUE TITLE
Expose Connect-AzAccount error details in Azure PowerShell v4 task

### ISSUE THREAD

**Issue by johncrim** [microsoft/azure-pipelines-tasks#10207] opened 2019-04-24 20:02 UTC
## Required Information

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: AzurePowershellV4

## Environment
Azure Pipelines - Private - Hosted Ubuntu 16.04

## Issue Description
Problems connecting to Azure are excessively difficult to troubleshoot, b/c the error details are swallowed, and aren't even exposed when debug is true.

Here's an example:
https://developercommunity.visualstudio.com/content/problem/523218/azure-powershell-script-new-error-there-was-an-err.html

The root cause was a file permissions issue on Linux agents. In order to figure this out, I had to reproduce the task's logic in powershell and strip out the error handling.

Earlier, I had a different issue that was also extremely difficult to troubleshoot due to the lack of diagnostic information that's provided when connect fails. Better error reporting would have saved me days of lost work.

### Task logs

```
##[section]Starting: Azure PowerShell script: InlineScript
==============================================================================
Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 4.0.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613749)
==============================================================================
##[warning]Can\'t find loc string for key: GeneratingScript
GeneratingScript
[command]/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/home/vsts/work/_temp/3d5f20fb-a02b-45ef-907f-92c36cfcc86b.ps1'
##[command]Import-Module -Name /home/vsts/.local/share/powershell/Modules/Az.Accounts/1.5.0/Az.Accounts.psd1 -Global
##[command]Clear-AzContext -Scope Process
##[command]Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
##[command]Connect-AzAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud
There was an error with the service principal used for the deployment.
At /home/vsts/work/_tasks/AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62/4.0.3/InitializeAz.ps1:69 char:9
+         throw (New-Object System.Exception("There was an error with t ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], Exception
+ FullyQualifiedErrorId : There was an error with the service principal used for the deployment.
 
##[error]PowerShell exited with code '1'.
##[section]Finishing: Azure PowerShell script: InlineScript
```

**Comment by Ajay-MS** [comment] 2019-05-14 12:03
@johncrim 

As per the logs, task failed during `Connect-AzAccount` cmdlet but it didn't printed actual cause of the error. 

Can you please check if you are still encountering this issue. If yes, run below mentioned script from PS task instead of Azure PS task. 

[Script to validate subscription](https://github.com/Ajay-MS/UtilityScripts/blob/master/Subscription/ValidateSPNWithAzModule.ps1)

**Comment by johncrim** [comment] 2019-05-14 19:41
I was able to find the root cause of the issue (and a previous issue) by recreating the logic to sign in to Az in pure powershell (using a plain powershell core task, not using the Azure powershell task). After doing that, I was able to uncover the error message that Azure Powershell is hiding.

The fix I'm looking for here is to report the inner error, not swallow it.

**Comment by Ajay-MS** [comment] 2019-05-18 14:55
@johncrim 

Thanks for your valuable feedback. I agree with you completely.  We will update task for printing out to root cause of the issue.

**Comment by 20shivangi** [comment] 2019-06-11 04:25
@johncrim 

The issue has been fixed in PR : https://github.com/microsoft/azure-pipelines-tasks/pull/10609
It will be deployed within 5-6 weeks.

**Closed by 20shivangi** 2019-06-11 04:25 UTC
Labels: Area: Release
