### ISSUE TITLE
Job preparation parameters displays sensitive information from previous stage passed values

### ISSUE THREAD

**Issue by bluedog13** [microsoft/azure-pipelines-tasks#17169] opened 2022-11-12 00:18 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: task.setvariable  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I have a secret variable in stage A that gets passed to stage B

Stage A
```
echo "##vso[task.setvariable variable=SECRET;isOutput=true;issecret=false]$_API_SECRET"
```

Stage B
```
variables:
      CLOUD_API_KEY: $[stageDependencies.stageValidatePlan.TerraformJobs.outputs['setvar.API_SECRET']]
```

But this displays in the Job preparation parameters for Stage B
```
Job preparation parameters
Variables:
  API_SECRET:
    Parsing expression: <stageDependencies.stageValidatePlan.TerraformJobs.outputs['API_SECRET']>
    Evaluating: stageDependencies['stageValidatePlan']['TerraformJobs']['outputs']['setvar.API_SECRET']
    Result: '[redacted]'
```

if I pass it from Stage A as secret, the value being read is **** in stage B and not the actual value
```
echo "##vso[task.setvariable variable=SECRET;isOutput=true;issecret=true]$_API_SECRET"
```

How do I pass the value form Stage A to Stage B and the value not be displayed in the Job preparation parameters deails?

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by sergey-koryshev** [comment] 2022-11-23 14:07
@bluedog13 if you don't want to expose value of variable in logs so you need to operate it as secret. I don't understand exactly your problem around actual value of secret in second stage. I created a simple pipeline to reproduce it:

```yaml
stages:
  - stage: A
    pool: default
    jobs:
      - job: Job1
        steps:
          - script: echo "##vso[task.setvariable variable=NOTSECRET;isOutput=true;issecret=false]NotSecret"
            name: setNotSecret
            displayName: Setting non-Secret
          - script: echo "##vso[task.setvariable variable=SECRET;isOutput=true;issecret=true]SomeSecret"
            name: setSecret
            displayName: Setting secret
  - stage: B
    variables: 
      NotSecret: $[stageDependencies.A.Job1.outputs['setNotSecret.NOTSECRET']]
      Secret: $[stageDependencies.A.Job1.outputs['setSecret.SECRET']]
    pool: default
    jobs:
      - job: Job2
        steps:
          - script: |
              echo "Non-secret: $NotSecret"
              echo "Secret: $Secret"
              SecretFirstPart=${Secret::-2}
              SecretSecondPart=${Secret: -2}
              echo "Exposed secret: $SecretFirstPart-$SecretSecondPart"
            env:
              NotSecret: $(NotSecret)
              Secret: $(secret)
```

In last script you can see that value of each variable is correct (to expose value of secret I had to split it into two parts because `ADO` always masks secrets in output)

```
Non-secret: NotSecret
Secret: ***
Exposed secret: SomeSecr-et
```

Can you please show example of YAML-pipeline which reproduces your issue?

**Comment by bluedog13** [comment] 2022-11-29 15:51
Thank you very much for the example and the solution.  What you have illustrated above works and I have verified this on our end as well. 

My concern in regards to YAML pipeline are (our use case)

1. In the initial stage, the secrets are being read from azure key vault and in that stage, the secrets are maintained by the pipeline because they are being read from key vault.
2. However, if they have to be used in the following stages, as you have illustrated above, they need to be passed as secrets.

But since the development team has access to modify the YAML pipelines, they can easily uncover the secrets by removing the **issecret=true** condition.  When you have 1000+ pipelines in an organization and the individual teams have access to modify the pipeline, how safe are the secrets?

My assumption would have been, anything that has been read from the key vault and is identified as secret in a stage, why does it's characteristics (in this case secret) change (to a non secret) when it gets passed?

Are YAML pipelines really safe with this hack? 

Thanks

**Comment by sergey-koryshev** [comment] 2022-12-02 10:24
@bluedog13 

> why does it's characteristics (from secret) change (to non-secret) when it gets passed

This happens because you pass value of secret as string in follow line which doesn't contain information that it's secret value:

```bash
echo "##vso[task.setvariable variable=SECRET;isOutput=true;issecret=false]$_API_SECRET"
```

I think you can avoid this step by using [variable group linked to Azure KeyVault](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-secret-variables?view=azure-devops&tabs=yaml%2Cbash#set-a-secret-variable-in-a-variable-group) in every steps which need the secret.

**Comment by sergey-koryshev** [comment] 2022-12-20 12:21
@bluedog13 do you have additional questions? Can I close the issue?

**Comment by bluedog13** [comment] 2022-12-20 15:34
I don't have any more questions and sorry for the late response. 

Once again, thank you for your time and the example solution.

**Closed** 2022-12-20 21:55 UTC
Labels: bug, route, Area: ABTT
