### ISSUE TITLE
UseDotNet@2 sometimes doesn't download .NET

### ISSUE THREAD

**Issue by badsyntax** [microsoft/azure-pipelines-tasks#15085] opened 2021-07-26 09:24 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

*Type*: Bug

**Enter Task Name**: UseDotNet@2  

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines

- Agent - Hosted or Private:  Hosted

## Issue Description

The UseDotNet tasks does not download the .NET SDK.

I'm using the following config in my `azure-piplines.yml`:

```yml
steps:
  - task: UseDotNet@2
    displayName: "Install .NET 5.0 SDK"
    inputs:
      version: "5.0.x"
      installationPath: $(Agent.ToolsDirectory)/dotnet
```

Sometimes the tasks succeeds, sometimes it fails. The error is "Unexpected HTTP response: 404" but I can successfully download the file to my local machine, so not sure what the issue is.

### Task logs

```console
Starting: Install .NET 5.0 SDK
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.184.0
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 5.0.x.
Found version 5.0.302 in channel 5.0 for user specified version spec: 5.0.x
Version 5.0.302 was not found in cache.
Getting URL to download .NET Core sdk version: 5.0.302.
Detecting OS platform to find correct download package for the OS.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.184.0\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Downloading: https://download.visualstudio.microsoft.com/download/pr/2881a25e-f265-43ee-a095-3a05b0466771/45959c837217c768a3b8171edc6607b3/dotnet-sdk-5.0.302-win-x64.zip
##[error]Failed while installing version: 5.0.302 at path: C:\hostedtoolcache\windows/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/2881a25e-f265-43ee-a095-3a05b0466771/45959c837217c768a3b8171edc6607b3/dotnet-sdk-5.0.302-win-x64.zip Error: Error: Unexpected HTTP response: 404
```

**Comment by badsyntax** [comment] 2021-07-26 09:27
Same issue as https://github.com/microsoft/azure-pipelines-tasks/issues/15082 I believe. Feel free to close as a duplicate.

**Comment by markevych** [comment] 2021-07-26 09:39
The same issue was reproduced. Maybe related to Azure services.

> Pipelines in your region may be impacted by a live site incident, resulting in possible pipeline delays. (Azure Status Popup)

**Comment by badsyntax** [comment] 2021-07-26 09:45
Thanks. (I'm not seeing any message about a live site incident in pipelines nor on the main status page btw.)

**Comment by EzzhevNikita** [comment] 2021-07-26 10:37
I am closing this ticket as a duplicate of this one https://github.com/microsoft/azure-pipelines-tasks/issues/15082

**Closed by EzzhevNikita** 2021-07-26 10:37 UTC
Labels: Area: Release, bug
