### ISSUE TITLE
Artifacts do not download on multi stage yaml build using DownloadPipelineArtifactV2

### ISSUE THREAD

**Issue by giggio** [microsoft/azure-pipelines-tasks#11267] opened 2019-09-03 16:34 UTC
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: `DownloadPipelineArtifactV2`

## Environment
- Server - Azure Pipelines
  - account name: `lambda3`
  - team project name: `sdk`
  - build definition name: `template`
  - build number: buildid: `12494`

- Agent - Hosted:     
    - agent queue name: `Default`
    - OS of the machine running the agent and the agent version: Windows, agent version `2.155.1`

## Issue Description

When you try to download the artifacts on a multi stage build definition using the `DownloadPipelineArtifactV2` task it will only download the artifacts from the first stage. In my scenario I have 3 stages, and I product the artifacts on the second stage, while the first stage only has a code coverage artifact. What I've seen is that the code coverage artifacts (1st stage) download, while the ones from the 2nd stage don't.

**Note**: I am using a self hosted agent, and I noted that the artifacts were not being removed between each build, which created problems, as leftover artifacts from previous builds were still around. So, I had the idea of downloading the artifacts to the `Agent.TempDirectory`, so it would be removed for sure.

This was all on a deployment stage.

If you let the download happen naturally, it **will** download all the artifacts, the problem only happens when you use the `DownloadPipelineArtifactV2` task directly.

I also noticed that the Build Summary shows no artifacts for the second stage, it only shows one artifact for the 1st stage. But the artifacts tab does show all 3 artifacts.

### Task logs

These are the partial logs for the download of the last two artifacts, named `vsix` and `nupkg`:

````
Information, Start downloading artifact - vsix
Information, Minimatch patterns: [**]
Information, Filtered 1 files from the Minimatch filters supplied.
Information, Could not initialize dataport.
Information, Downloaded 0.0 MB out of 0.1 MB (0%).
Information, Downloaded 0.1 MB out of 0.1 MB (100%).
Information, 
Download statistics:
Total Content: 0.1 MB
Physical Content Downloaded: 0.1 MB
Compression Saved: 0.0 MB
Local Caching Saved: 0.0 MB
Chunks Downloaded: 1
Nodes Downloaded: 0

Information, Start downloading artifact - nupkgs
Information, Minimatch patterns: [**]
Information, Filtered 1 files from the Minimatch filters supplied.
Information, Could not initialize dataport.
Information, Downloaded 0.0 MB out of 0.0 MB (0%).
Information, Downloaded 0.0 MB out of 0.0 MB (100%).
Information, 
Download statistics:
Total Content: 0.0 MB
Physical Content Downloaded: 0.0 MB
Compression Saved: 0.0 MB
Local Caching Saved: 0.0 MB
Chunks Downloaded: 1
Nodes Downloaded: 0
````

**Comment by StephenLarkin** [comment] 2019-09-25 15:32
I'm seeing what I can only imagine is the same problem.

```yaml
- download: current
  displayName: 'Download Scripts'
  artifact: Topic
  patterns: '@(SetBranchName|StopAppPool).ps1'
```

In this case the new version of `StopAppPool.ps1` included a bug that was picked up in code review, but somehow succeeded in the build pipeline. I determined that this was because the file had already been downloaded by a previous run to the agent, and when downloaded again it was not replaced.

This seems like a fairly serious problem if older files could be run or referenced by newer builds.

Logs:
```
Download from the specified build: #31512
Download artifact to: D:\_work\2/Topic
Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session dd19eddf-ef99-4fe8-a1d0-95af501bf76f
Information, Minimatch patterns: [@(SetBranchName|StopAppPool).ps1]
Information, ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodsu6weu.vsblob.visualstudio.com/A5fa85633-6985-41ba-aea7-07750da8fd2b/_apis/dedup/chunks/9AAB181E66DF90A0E055E64EAA06683EB5FBD773FF7B59357A6760E31B7BEFB101 attempt 1/6 failed with StatusCode RedirectMethod, IsRetryableResponse False
Information, Filtered 2 files from the Minimatch filters supplied.
Information, Could not initialize dataport.
Information, Downloaded 0.0 MB out of 0.0 MB (0%).
Information, Downloaded 0.0 MB out of 0.0 MB (100%).
Information, 
Download statistics:
Total Content: 0.0 MB
Physical Content Downloaded: 0.0 MB
Compression Saved: 0.0 MB
Local Caching Saved: 0.0 MB
Chunks Downloaded: 2
Nodes Downloaded: 0
```

**Comment by jahsu-MSFT** [comment] 2019-12-05 00:04
@giggio I cannot repro the issue you mentioned. In my pipeline, I have stage 1 with build and pipeline artifacts published, in the stage 2, I have another build and pipeline artifact published and in the stage 3, I have a download pipeline artifact V2 task and it will download both build artifacts and pipeline artifacts if the multi-download  mode is selected. 
One thing to note is that, The jobs by default does NOT run in order, you will need to select dependencies. For in example, in this case, in the stage 3, I need to specify that the stage 1 and 2 are the dependencies. 
![image](https://user-images.githubusercontent.com/45610531/70192138-b03b8500-16af-11ea-996b-d384604fde7a.png)

**Comment by GarethOates** [comment] 2019-12-09 13:32
I've been experiencing this problem today as well. If an artifact has previously been downloaded by the agent, it is used in the subsequent stages instead of the latest being downloaded.  Even though when you view the artifact in Azure DevOps, it shows the files as they should be.

In my case, I had renamed 2 files.  The artifact in Azure DevOps looked ok, with the 2 new filenames being present, but when the job was running, it was using the older artifact version with the 2 old filenames.  The solution for me was to log into each agent's work folder and delete the cached version.

**Comment by jahsu-MSFT** [comment] 2019-12-12 23:45
@giggio Are you still seeing the issue after adding dependencies? If so, can you provide your sample build def/yaml schema?

@TabithaLarkin @giggio 
Regarding the old artifacts not being deleted in the agent, In the DPA V2 task, the default download directory is working directory and by design it won't get cleaned up when running a new build.

**Comment by jahsu-MSFT** [comment] 2019-12-12 23:46
@GarethOates I'm not sure I understand the scenario you described. Can you provide a sample build definition/ yaml schema of the issue you ran into?

**Comment by GarethOates** [comment] 2019-12-16 14:39
Sorry, I should have been a bit clearer about what my particular scenario is with regards to the 'build' and 'deploy' steps.

```
name: $(BuildDefinitionName).$(Build.SourceBranchName)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
    - master

stages:
- stage: BUILD
  jobs:
  - job: GetFiles
    displayName: Fetch the Template Files
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - publish: $(System.DefaultWorkingDirectory)
      artifact: documents

- stage: TEST
  displayName: Deploy to TEST
  variables:
    SiteUrl: 'http://oursharepointarea.com/dokumenter'
    InnholdLibrary: 'DokumentMaler'
    FMLibrary: 'DokumentmalerFM'
  jobs:
  - deployment: TEST
    pool: TEST-Vera
    environment: TEST - SharePoint
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: documents
            
            - task: PowerShell@2
              displayName: 'Upload Innhold Documents'
              inputs:
                targetType: filePath
                filePath: '$(Pipeline.Workspace)/documents/Scripts/UploadDokument.ps1'
                arguments: '$(SiteUrl) $(InnholdLibrary) $(Pipeline.Workspace)/documents/Innhold'
                failOnStderr: true

            - task: PowerShell@2
              displayName: 'Upload DocumentMalerFM Documents'
              inputs:
                targetType: filePath
                filePath: '$(Pipeline.Workspace)/documents/Scripts/UploadDokument.ps1'
                arguments: '$(SiteUrl) $(FMLibrary) ''$(Pipeline.Workspace)/documents/FM Templates'''
                failOnStderr: true

- stage: QA
  displayName: Deploy to QA
  variables:
    SiteUrl: 'http://oursharepointarea.com/dokumenter'
    InnholdLibrary: 'DokumentMaler'
    FMLibrary: 'DokumentmalerFM'
  jobs:
  - deployment: QA
    pool: QA-Vera
    environment: QA - SharePoint
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: documents
            - task: PowerShell@2
              displayName: 'Upload Innhold Documents'
              inputs:
                targetType: filePath
                filePath: '$(Pipeline.Workspace)/documents/Scripts/UploadDokument.ps1'
                arguments: '$(SiteUrl) $(InnholdLibrary) $(Pipeline.Workspace)/documents/Innhold'
                failOnStderr: true

            - task: PowerShell@2
              displayName: 'Upload DocumentMalerFM Documents'
              inputs:
                targetType: filePath
                filePath: '$(Pipeline.Workspace)/documents/Scripts/UploadDokument.ps1'
                arguments: '$(SiteUrl) $(FMLibrary) ''$(Pipeline.Workspace)/documents/FM Templates'''
                failOnStderr: true

- stage: PROD
  displayName: Deploy to PROD
  variables:
    SiteUrl: 'http://oursharepointarea.com/dokumenter'
    InnholdLibrary: 'DokumentMaler'
    FMLibrary: 'DokumentmalerFM'
  jobs:
  - deployment: PROD
    pool: PROD-Vera
    environment: PROD - SharePoint
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: documents
            
            - task: PowerShell@2
              displayName: 'Upload Innhold Documents'
              inputs:
                targetType: filePath
                filePath: '$(Pipeline.Workspace)/documents/Scripts/UploadDokument.ps1'
                arguments: '$(SiteUrl) $(InnholdLibrary) $(Pipeline.Workspace)/documents/Innhold'
                failOnStderr: true

            - task: PowerShell@2
              displayName: 'Upload DocumentMalerFM Documents'
              inputs:
                targetType: filePath
                filePath: '$(Pipeline.Workspace)/documents/Scripts/UploadDokument.ps1'
                arguments: '$(SiteUrl) $(FMLibrary) ''$(Pipeline.Workspace)/documents/FM Templates'''
                failOnStderr: true
```

I have a git repo which contains a collection of .docx and .pdf files.  The yaml file I have here describes the process by which we upload those documents to our different SharePoint environments, using a simple Powershell script.  This script loops over each .docx or .pdf file in the pipeline artifact directory and attempts to upload that file to SharePoint.

What I noticed when I updated the git repository to either include new files, or rename existing files, was that in deploy stages of my pipeline, the list of files being looped over and uploaded did not reflect the latest changes made to the repository, but instead was looping over an out of date collection of files.

I discovered that what was happening was, the 'download' task was not downloading the latest pipeline artifact produced in the previous stage, but was instead using a previously downloaded (and now old) cached version of the artifact.

So when my script was looping round all the files in the directory, those that were changed, added or renamed were not being included in this process.

I worked around this, by connecting to each agent and deleting the 'documents' artifact from the working directory.  This then forced the download step to fetch the latest version of the documents artifact, which contained the correct files.

**Comment by jahsu-MSFT** [comment] 2019-12-16 18:37
@GarethOates Thanks for the additional info. Can you please try adding dependsOn input field in the yaml schema and assign the stage name it's dependent on to the value and see if it works? 
For example: 
dependsOn: 
  - Build
  - Test
  - QA

For reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema

**Comment by GarethOates** [comment] 2019-12-18 10:22
I'm afraid that didn't fix the problem.

**Comment by jahsu-MSFT** [comment] 2019-12-18 18:34
@GarethOates Thanks for the updates. I think that goes back to the scenario where old artifacts are not being deleted in the agent. In the DPA V2 task, the default download directory is working directory and by design, it won't get cleaned up when running a new build
I think you can try specifying $(System.ArtifactsDirectory) as the download directory, files inside of that folder should get cleaned up when the agent is running a new build/pipeline. 

In the meantime, we will evaluate to see if it makes sense to set the default download directory to some folder that gets cleaned at the beginning of each run.

**Comment by GarethOates** [comment] 2019-12-18 22:32
Ok, so does that mean I can’t use the shortcut version of those tasks like - download: current and must instead define the tasks fully, specifying the directory myself?

If so, I’ll do that. It might make sense to mention this caveat (if you can call it that) in the docs somewhere.  I’ll have a go at updating them and submitting a PR tomorrow CET, unless you beat me to it, or don’t agree that it needs mentioning. 😊

**Comment by jahsu-MSFT** [comment] 2019-12-18 23:28
@GarethOates Sorry for the inconvenience. Fro the download keyword, unfortunately the target input field is currently not exposed but it should have the capability for users to specify a custom download directory very soon. 
For now if you'd like to use a different download directory, yes, you will need to define the task fully.

**Comment by jahsu-MSFT** [comment] 2020-01-17 22:00
The issue should be resolved after adding dependent stages and regarding the default download directory not being cleaned up, it's currently by design. I'm closing the ticket for now and we can reopen it if you are still seeing the issue.

**Comment by GarethOates** [comment] 2020-01-22 15:19
It was resolved by switching to using the DownloadPipelineArtifact task instead of the download keyword.  Setting dependent stages did not resolve the issue, however I have been able to work around it.

**Comment by jahsu-MSFT** [comment] 2020-01-22 16:57
@fadnavistanmay who will be looking into PA related issues. If this is download keyword related, the RM team can help look into it.

**Closed** 2020-03-11 20:47 UTC
Labels: Area: ArtifactsCore, Area: PipelineArtifact

**Comment by trajano** [comment] 2020-05-28 13:03
Referenced in https://stackoverflow.com/questions/62042095/how-do-you-download-all-pipeline-resources-in-a-job/62056385#62056385

**Comment by cawoodm** [comment] 2020-06-11 05:44
If the solution is using the "DownloadPipelineArtifact task instead of the download keyword" then @microsoft you need to update your docs - this is driving folks crazy.

**Comment by Arnaud-FELTZ** [comment] 2025-02-14 09:57
This seems still be active in 2025, even using `DownloadPipelineArtifact@2` :

Here is the content of the download tasks that shows `Verbose, Downloaded /coverage.xml` while still showing 0.0MB downloaded and indeed it's not present in my target directory.

`Download artifact to: /home/vsts/work/1
Using default max parallelism.
Verbose, ArtifactHttpClientFactory.CreateVssHttpClient: ClientSettingsHttpClient with BaseUri: https://vsblobprodweu2.vsblob.visualstudio.com/Ab45b9838-7c65-4606-8bfb-a893d24654eb/, MaxRetries:5, SendTimeout:00:05:00
Using default max parallelism.
Max dedup parallelism: 192
DomainId: 0
Verbose, ArtifactHttpClientFactory.CreateVssHttpClient: DedupStoreHttpClient with BaseUri: https://vsblobprodweu2.vsblob.visualstudio.com/Ab45b9838-7c65-4606-8bfb-a893d24654eb/, MaxRetries:5, SendTimeout:00:05:00
Information, ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 3c45d276-29b5-4c0c-96e6-28c58b02a76a
Verbose, Started ITelemetrySender BlobStoreApplicationInsightsTelemetrySender.
Hashtype: Dedup1024K
Verbose, PipelineArtifact.DownloadMultipleArtifactsAsync starting
Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session 3c45d276-29b5-4c0c-96e6-28c58b02a76a
Information, Start downloading artifact - coverage-report
Information, Minimatch patterns: [**]
Information, Filtered 1 files from the Minimatch filters supplied.
Verbose, Could not initialize dataport: Dataport will not be used as it is only currently available on Windows.
Information, Downloaded 0.0 MB out of 0.0 MB (0%).
Verbose, Downloaded /coverage.xml
Information, Downloaded 0.0 MB out of 0.0 MB (100%).
Information, 
Download statistics:
Total Content: 0.0 MB
Physical Content Downloaded: 0.0 MB
Compression Saved: 0.0 MB
Local Caching Saved: 0.0 MB
Chunks Downloaded: 1
Nodes Downloaded: 0
`
