### ISSUE TITLE
How to set secret variable for command line task version 1 in classic editor?

### ISSUE THREAD

**Issue by prathyusha-mandala** [microsoft/azure-pipelines-tasks#16612] opened 2022-07-20 13:42 UTC
Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
bug

**Enter Task Name**:  Command Line Task Version 1  

## Environment
- Server - Azure Pipelines - Azure DevOps Services
  
- Agent - Private 
  
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
    - Agent version: 2.188.4 OS: Windows_NT

## Issue Description

Task Name : Command Line Task Version 1
We have a secret variable which we wanted to pass it in the batch file execution, we are using cmdtask@1 as version 2 is not working on our agent. We want to set "Dep_password" variable as secret password. As per the [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/set-secret-variables?view=azure-devops&tabs=yaml%2Cbash) to use secret variables we have to set it as an environment variable, but I do not see such option in version 1 of the Task, Can you please help us in achieving this?
<img width="505" alt="cmdtask" src="https://user-images.githubusercontent.com/69055347/179997133-30004211-ef7d-4ba2-85a6-82c67c9e5980.PNG">

Thanks

**Comment by prathyusha-mandala** [comment] 2022-07-21 07:49
Hi @KonstantinTyukalov 
We are getting the below error if we are using the Command Line Task version 2
##[error]Cannot bind argument to parameter 'LiteralPath' because it is an empty string.
##[debug]Processed: ##vso[task.logissue type=error]Cannot bind argument to parameter 'LiteralPath' because it is an empty string

Can you please suggest a way to use secret varaibles in cmdline task version 1?

Thanks

**Comment by KonstantinTyukalov** [comment] 2022-07-21 11:15
@prathyusha-mandala in the first version of the CmdLine task you cannot use environment variables. At this time we do not support the first version of the task and we cannot update it.

Could you provide more pipeline logs for CmdLineV2 task, we will take a look at issue with second version of the task.
You can retrieve them by following [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#view-and-download-logs) .
To set up debug (verbose) mode - you can use options described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs)

You can send pipeline logs to my email: v-ktyukalov@microsoft.com

As a workaround, you could try using the powershell task, would that work in your case?

thank you

**Comment by prathyusha-mandala** [comment] 2022-07-21 11:30
Hi @KonstantinTyukalov 
We are executing batch files using command line task, we prefer using cmd over powershell to execute Batch files.

Please find the logs below

**Comment by prathyusha-mandala** [comment] 2022-07-21 11:32
Hi @KonstantinTyukalov 
We are using this task to execute batch files, We prefer CMD over Powershell to execute Batch files.

Please find the logs below
2022-07-20T12:40:21.0556928Z ##[debug]Evaluating condition for step: 'TEST AUTO'
2022-07-20T12:40:21.0564306Z ##[debug]Evaluating: and(ne(variables['TEST_START'], '0'), ne(variables['TEST_STOP'], '0'))
2022-07-20T12:40:21.0565005Z ##[debug]Evaluating and:
2022-07-20T12:40:21.0572909Z ##[debug]..Evaluating ne:
2022-07-20T12:40:21.0574696Z ##[debug]....Evaluating indexer:
2022-07-20T12:40:21.0588424Z ##[debug]......Evaluating variables:
2022-07-20T12:40:21.0593118Z ##[debug]......=> Object
2022-07-20T12:40:21.0594599Z ##[debug]......Evaluating String:
2022-07-20T12:40:21.0595809Z ##[debug]......=> 'TEST_START'
2022-07-20T12:40:21.0600274Z ##[debug]....=> '1'
2022-07-20T12:40:21.0601167Z ##[debug]....Evaluating String:
2022-07-20T12:40:21.0601597Z ##[debug]....=> '0'
2022-07-20T12:40:21.0604704Z ##[debug]..=> True
2022-07-20T12:40:21.0605502Z ##[debug]..Evaluating ne:
2022-07-20T12:40:21.0605885Z ##[debug]....Evaluating indexer:
2022-07-20T12:40:21.0606333Z ##[debug]......Evaluating variables:
2022-07-20T12:40:21.0606668Z ##[debug]......=> Object
2022-07-20T12:40:21.0607267Z ##[debug]......Evaluating String:
2022-07-20T12:40:21.0607612Z ##[debug]......=> 'TEST_STOP'
2022-07-20T12:40:21.0608113Z ##[debug]....=> '2'
2022-07-20T12:40:21.0608563Z ##[debug]....Evaluating String:
2022-07-20T12:40:21.0608844Z ##[debug]....=> '0'
2022-07-20T12:40:21.0609147Z ##[debug]..=> True
2022-07-20T12:40:21.0609553Z ##[debug]=> True
2022-07-20T12:40:21.0612688Z ##[debug]Expanded: and(ne('1', '0'), ne('2', '0'))
2022-07-20T12:40:21.0613219Z ##[debug]Result: True
2022-07-20T12:40:21.0613842Z ##[section]Starting: TEST AUTO
2022-07-20T12:40:21.0768521Z ==============================================================================
2022-07-20T12:40:21.0768901Z Task         : Command line
2022-07-20T12:40:21.0769241Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2022-07-20T12:40:21.0769614Z Version      : 2.201.1
2022-07-20T12:40:21.0769857Z Author       : Microsoft Corporation
2022-07-20T12:40:21.0770479Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2022-07-20T12:40:21.0770939Z ==============================================================================
2022-07-20T12:40:22.1500816Z ##[debug]VstsTaskSdk 0.9.0 commit 6c48b16164b9a1c9548776ad2062dad5cd543352
2022-07-20T12:40:22.3645176Z ##[debug]Entering D:\AzureWorkspace\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.201.1\cmdline.ps1.
2022-07-20T12:40:22.3812671Z ##[debug]Loading resource strings from: D:\AzureWorkspace\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.201.1\task.json
2022-07-20T12:40:22.4113116Z ##[debug]Loaded 6 strings.
2022-07-20T12:40:22.4212740Z ##[debug]SYSTEM_CULTURE: 'en-US'
2022-07-20T12:40:22.4293864Z ##[debug]Loading resource strings from: D:\AzureWorkspace\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.201.1\Strings\resources.resjson\en-US\resources.resjson
2022-07-20T12:40:22.4533254Z ##[debug]Loaded 6 strings.
2022-07-20T12:40:22.4913573Z ##[debug]INPUT_FAILONSTDERR: 'false'
2022-07-20T12:40:22.5003754Z ##[debug] Converted to bool: False
2022-07-20T12:40:22.5092398Z ##[debug]INPUT_SCRIPT: 'C:\ANT\apache-ant-1.10.7\bin\TEST_AUTO.bat'
2022-07-20T12:40:22.5168647Z ##[debug]INPUT_WORKINGDIRECTORY: 'D:\AzureWorkspace\3\s'
2022-07-20T12:40:22.5390956Z ##[debug]Asserting container path exists: 'D:\AzureWorkspace\3\s'
2022-07-20T12:40:22.5477620Z Generating script.
2022-07-20T12:40:22.5585290Z Script contents: shell
2022-07-20T12:40:22.5596988Z C:\ANT\apache-ant-1.10.7\bin\TEST_AUTO.bat
2022-07-20T12:40:22.5816780Z ##[debug]AGENT_VERSION: '2.188.4'
2022-07-20T12:40:22.5983377Z ##[debug]AGENT_TEMPDIRECTORY: 'D:\AzureWorkspace\_temp'
2022-07-20T12:40:22.6045333Z ##[debug]Asserting container path exists: 'D:\AzureWorkspace\_temp'
2022-07-20T12:40:22.6331201Z ##[debug]Leaving D:\AzureWorkspace\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.201.1\cmdline.ps1.
2022-07-20T12:40:22.6435548Z ##[debug]Caught exception from task script.
2022-07-20T12:40:22.6511873Z ##[debug]Error record:
2022-07-20T12:40:22.7917028Z ##[debug]D:\AzureWorkspace\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.201.1\cmdline.ps1 : Cannot bind argument to parameter 'LiteralPath' because it is an empty string.
2022-07-20T12:40:22.7954260Z ##[debug]At line:1 char:1
2022-07-20T12:40:22.7989895Z ##[debug]+ . 'D:\AzureWorkspace\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2 ...
2022-07-20T12:40:22.8025049Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-07-20T12:40:22.8056115Z ##[debug]    + CategoryInfo          : InvalidData: (:) [cmdline.ps1], ParameterBinding    ValidationException
2022-07-20T12:40:22.8095984Z ##[debug]    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAl    lowed,cmdline.ps1
2022-07-20T12:40:22.8140581Z ##[debug] 
2022-07-20T12:40:22.8215042Z ##[debug]Script stack trace:
2022-07-20T12:40:22.8323735Z ##[debug]at <ScriptBlock><Process>, D:\AzureWorkspace\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.201.1\cmdline.ps1: line 54
2022-07-20T12:40:22.8356805Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-07-20T12:40:22.8389117Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-07-20T12:40:22.8424812Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-07-20T12:40:22.8455887Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-07-20T12:40:22.8516330Z ##[debug]Exception:
2022-07-20T12:40:22.8740484Z ##[debug]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'LiteralPath' because it is an empty string.
2022-07-20T12:40:22.8914910Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2022-07-20T12:40:22.8916983Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2022-07-20T12:40:22.8918587Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-07-20T12:40:22.8942750Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-07-20T12:40:22.9012719Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2022-07-20T12:40:22.9172960Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2022-07-20T12:40:22.9227704Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2022-07-20T12:40:22.9362743Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
2022-07-20T12:40:22.9365751Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
2022-07-20T12:40:22.9751957Z ##[error]Cannot bind argument to parameter 'LiteralPath' because it is an empty string.
2022-07-20T12:40:22.9767161Z ##[debug]Processed: ##vso[task.logissue type=error]Cannot bind argument to parameter 'LiteralPath' because it is an empty string.
2022-07-20T12:40:22.9779030Z ##[debug]Processed: ##vso[task.complete result=Failed]
2022-07-20T12:40:23.0139151Z ##[section]Finishing: TEST AUTO

Thanks

**Comment by KonstantinTyukalov** [comment] 2022-07-21 11:45
@prathyusha-mandala thank you for provided logs.
Could please also share the problem Batch file for reproducing this issue?

if it contains any private information, you can send it to my e-mail: v-ktyukalov@microsoft.com

thank you

**Comment by prathyusha-mandala** [comment] 2022-07-21 11:56
@KonstantinTyukalov Just suppose a simple batch file(file1.bat) contains these three lines
@echo %Username%
@echo %Password%
C:\Users\software\force login -i=test -u=%Username% -p=%Password%

As no value is passed to the password, the login fails

When variable **Password** is set as secret in pipeline, No value for **Password** is passed to the Batch file.
But Username value is visible, as it is not set as secret

**Comment by KonstantinTyukalov** [comment] 2022-12-28 16:26
@prathyusha-mandala I cannot reproduce the issue with the CmdLine@2 task,
could you try specifying the 'Working Directory' parameter as "$(Build.SourcesDirectory)"?

Also please take a look at description [how to run batch script files through this task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/cmd-line-v2?view=azure-pipelines#running-batch-and-cmd-files)

Also note that you can use environment variables with the suffix "SECRET_" to access secret values, e.g. "SECRET_TEST".

For batch files you can also use the [BatchSript@1](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/batch-script-v1?view=azure-pipelines) task.

**Comment by KonstantinTyukalov** [comment] 2023-03-01 17:42
@prathyusha-mandala do you have any questions? Can we close this work item?

**Comment by kirill-ivlev** [comment] 2023-08-08 09:26
Hi @prathyusha-mandala, we will close this item since we didn't receive any feedback from you. Please feel free to reopen it, in case if you have any questions

**Closed by kirill-ivlev** 2023-08-08 09:26 UTC
Labels: question, Area: ABTT, Task: CmdLine
