### ISSUE TITLE
AzurePowerShellV3 doesn't show write-host output from the script file

### ISSUE THREAD

**Issue by lecamarade** [microsoft/azure-pipelines-tasks#10535] opened 2019-05-30 14:29 UTC
## Required Information

When running a powershell script file all that is shown in the Azure Release pipeline console is "Waiting for console output from an agent...". Write-Host outputs form the script are ignored.

**Question, Bug, or Feature?**  
*Type*: Question/Bug.

**Enter Task Name**: AzurePowerShell

## Environment
- Server - Azure Pipelines

**Comment by Ajay-MS** [comment] 2019-05-31 09:48
@lecamarade 

I am not able to repro this issue. 

Can you please share debug logs. Debugs logs can be enabled by adding release definition variable `system.debug` with value `true`

**Comment by ArieHein** [comment] 2019-05-31 14:18
there were some issues with the service yesterday, if it fits your region:
https://status.dev.azure.com/_history

**Comment by lecamarade** [comment] 2019-05-31 14:24
Well, probably it is a limitation of the Azure Powershell task.
The output is available in the logs after the task runs. However, it is not
shown while it is running.
Is it expected?

**Comment by 20shivangi** [comment] 2019-06-03 06:23
@lecamarade Console has a refresh cycle of 5 sec. So, whatever commands you are executing, please try to put some sleep commands in between and see if the write-host command works properly.
We are not able to reproduce the issue from our side.

**Comment by 20shivangi** [comment] 2019-06-06 12:11
@lecamarade Any update ?

**Comment by lecamarade** [comment] 2019-06-06 13:25
Same story.
I've added a simple test.ps1 to be run the task.

Write-Host "START: Sleeping for 10min"
Start-Sleep -Seconds 600
Write-Host "END"

I don't see any output while the script is running. In 10 min I see
everything in the logs.

**Comment by 20shivangi** [comment] 2019-06-07 11:20
@lecamarade
Please share your email id so that we can schedule a call to kook into the issue.

**Comment by lecamarade** [comment] 2019-06-07 14:19
Sorry, it doesn't bother me that much.
If you can't reproduce it, let's close it.

**Comment by 20shivangi** [comment] 2019-06-07 16:44
Unable to reproduce the issue thereby closing it

**Closed by 20shivangi** 2019-06-07 16:44 UTC
Labels: Area: Release, bug, question
