### ISSUE TITLE
task: AzureAppServiceSettings@1 - false error while validating JSON

### ISSUE THREAD

**Issue by ukhan262** [microsoft/azure-pipelines-tasks#12919] opened 2020-05-18 09:13 UTC
Question, Bug, or Feature?
Type: Bug

Enter Task Name: AzureAppServiceSettings@1 Task

## Environment
- Server - Azure Pipelines
    - Account Name: Wedgewoodco
    - Team Project: Fortress
    - BuildId: 57

- Agent - Private: 
    - OS: Windows Server 2016  

## Issue Description

This task is reporting false positive related to json being not valid. I would like to have this checked out. I have validated my JSON as well. Please check out the screenshots below.

### Task Logs
<img width="1071" alt="Screen Shot 2020-05-18 at 1 54 49 AM" src="https://user-images.githubusercontent.com/37010344/82195369-0e9a9f80-98ad-11ea-88f6-17f6e36fb408.png">

```
2020-05-18T10:24:17.7519891Z ##[debug]Evaluating condition for step: 'Azure App Service Settings: wecdata-iBuyer-dev'
2020-05-18T10:24:17.7528326Z ##[debug]Evaluating: SucceededNode()
2020-05-18T10:24:17.7531207Z ##[debug]Evaluating SucceededNode:
2020-05-18T10:24:17.7535221Z ##[debug]=> True
2020-05-18T10:24:17.7537837Z ##[debug]Result: True
2020-05-18T10:24:17.7541157Z ##[section]Starting: Azure App Service Settings: wecdata-iBuyer-dev
2020-05-18T10:24:17.8139155Z ==============================================================================
2020-05-18T10:24:17.8140662Z Task         : Azure App Service Settings
2020-05-18T10:24:17.8142025Z Description  : Update/Add App settings an Azure Web App for Linux or Windows
2020-05-18T10:24:17.8143268Z Version      : 1.163.5
2020-05-18T10:24:17.8144241Z Author       : Microsoft Corporation
2020-05-18T10:24:17.8145554Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
2020-05-18T10:24:17.8147006Z ==============================================================================
2020-05-18T10:24:18.4142792Z ##[debug]agent.TempDirectory=D:\build_agent-03\_work\_temp
2020-05-18T10:24:18.4239280Z ##[debug]loading inputs and endpoints
2020-05-18T10:24:18.4259637Z ##[debug]loading ENDPOINT_AUTH_9cf4098e-1634-42b6-93d3-f4321fcfc2c7
2020-05-18T10:24:18.4303929Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_9cf4098e-1634-42b6-93d3-f4321fcfc2c7_AUTHENTICATIONTYPE
2020-05-18T10:24:18.4317482Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_9cf4098e-1634-42b6-93d3-f4321fcfc2c7_SERVICEPRINCIPALID
2020-05-18T10:24:18.4327068Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_9cf4098e-1634-42b6-93d3-f4321fcfc2c7_SERVICEPRINCIPALKEY
2020-05-18T10:24:18.4334795Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_9cf4098e-1634-42b6-93d3-f4321fcfc2c7_TENANTID
2020-05-18T10:24:18.4342270Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2020-05-18T10:24:18.4350500Z ##[debug]loading ENDPOINT_AUTH_SCHEME_9cf4098e-1634-42b6-93d3-f4321fcfc2c7
2020-05-18T10:24:18.4357831Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2020-05-18T10:24:18.4365296Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2020-05-18T10:24:18.4379869Z ##[debug]loading INPUT_APPNAME
2020-05-18T10:24:18.4388003Z ##[debug]loading INPUT_APPSETTINGS
2020-05-18T10:24:18.4396806Z ##[debug]loading INPUT_CONNECTEDSERVICENAME
2020-05-18T10:24:18.4405723Z ##[debug]loading INPUT_RESOURCEGROUPNAME
2020-05-18T10:24:18.4414657Z ##[debug]loading INPUT_SLOTNAME
2020-05-18T10:24:18.4431584Z ##[debug]loading SECRET_APPINSIGHT_KEY_DEV
2020-05-18T10:24:18.4441481Z ##[debug]loading SECRET_AZURE_APP_INSIGHTS_INSTRUMENTATION_KEY
2020-05-18T10:24:18.4452040Z ##[debug]loading SECRET_AZURE_APP_SERVICE_KUDU_PRODUCTION_PASSWORD
2020-05-18T10:24:18.4464471Z ##[debug]loading SECRET_AZURE_FORTRESS_STORAGE_CONNECTIONSTRING_DEV
2020-05-18T10:24:18.4468415Z ##[debug]loading SECRET_AZURE_SEARCH_KEY_DEV
2020-05-18T10:24:18.4472117Z ##[debug]loading SECRET_AZURE_SIGNALR_CONNECTIONSTRING_DEV
2020-05-18T10:24:18.4475706Z ##[debug]loading SECRET_AZURE_WECSVC_STORAGE_CONNECTIONSTRING_DEV
2020-05-18T10:24:18.4479012Z ##[debug]loading SECRET_FORTRESS_SQL_CONTEXT_DEV
2020-05-18T10:24:18.4483625Z ##[debug]loading SECRET_GOOGLEMAPS_JS_KEY_DEV
2020-05-18T10:24:18.4486796Z ##[debug]loading SECRET_GOOGLE_MAPS_JAVASCRIPT_API_KEY
2020-05-18T10:24:18.4491695Z ##[debug]loading SECRET_IDA_APPKEY_DEV
2020-05-18T10:24:18.4495008Z ##[debug]loading SECRET_IDA_CLIENTID_DEV
2020-05-18T10:24:18.4499065Z ##[debug]loading SECRET_OPENDOOR_AUTH_KEY_DEV
2020-05-18T10:24:18.4504856Z ##[debug]loading SECRET_REDIS_CACHE_CONNECTIONSTRING_DEV
2020-05-18T10:24:18.4509231Z ##[debug]loading SECRET_SQL_PASSWORD_DEV
2020-05-18T10:24:18.4514236Z ##[debug]loading SECRET_SQL_PASSWORD_PROD
2020-05-18T10:24:18.4517669Z ##[debug]loading SECRET_SQL_PASSWORD_QA
2020-05-18T10:24:18.4524235Z ##[debug]loading SECRET_SQL_PASSWORD_STG
2020-05-18T10:24:18.4528738Z ##[debug]loading SECRET_SQL_PASSWORD_UAT
2020-05-18T10:24:18.4532603Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2020-05-18T10:24:18.4536256Z ##[debug]loading SECRET_WEDGEWOODLOGS_CONNECTIONSTRING_DEV
2020-05-18T10:24:18.4544606Z ##[debug]loaded 35
2020-05-18T10:24:18.4572676Z ##[debug]Agent.ProxyUrl=undefined
2020-05-18T10:24:18.4576456Z ##[debug]Agent.CAInfo=undefined
2020-05-18T10:24:18.4577610Z ##[debug]Agent.ClientCert=undefined
2020-05-18T10:24:19.3194101Z ##[debug]Agent.SkipCertValidation=undefined
2020-05-18T10:24:19.3207314Z ##[debug]agent.proxyurl=undefined
2020-05-18T10:24:19.3209417Z ##[debug]VSTS_ARM_REST_IGNORE_SSL_ERRORS=undefined
2020-05-18T10:24:19.3211682Z ##[debug]AZURE_HTTP_USER_AGENT=VSTS_6e7764da-243d-4d61-a088-13e7e04a23c6_build_57_0
2020-05-18T10:24:19.3218464Z ##[debug]Agent.TempDirectory=D:\build_agent-03\_work\_temp
2020-05-18T10:24:19.3221402Z ##[debug]check path : D:\build_agent-03\_work\_tasks\AzureAppServiceSettings_3eeea460-bffa-11e9-9cb5-2a2ae2dbcce4\1.163.5\task.json
2020-05-18T10:24:19.3225611Z ##[debug]adding resource file: D:\build_agent-03\_work\_tasks\AzureAppServiceSettings_3eeea460-bffa-11e9-9cb5-2a2ae2dbcce4\1.163.5\task.json
2020-05-18T10:24:19.3228726Z ##[debug]system.culture=en-US
2020-05-18T10:24:19.3231083Z ##[debug]check path : D:\build_agent-03\_work\_tasks\AzureAppServiceSettings_3eeea460-bffa-11e9-9cb5-2a2ae2dbcce4\1.163.5\node_modules\azurermdeploycommon\module.json
2020-05-18T10:24:19.3234697Z ##[debug]adding resource file: D:\build_agent-03\_work\_tasks\AzureAppServiceSettings_3eeea460-bffa-11e9-9cb5-2a2ae2dbcce4\1.163.5\node_modules\azurermdeploycommon\module.json
2020-05-18T10:24:19.3237115Z ##[debug]system.culture=en-US
2020-05-18T10:24:19.3238630Z ##[debug]ConnectedServiceName=9cf4098e-1634-42b6-93d3-f4321fcfc2c7
2020-05-18T10:24:19.3240141Z ##[debug]appName=wecdata-iBuyer-dev
2020-05-18T10:24:19.3241536Z ##[debug]resourceGroupName=FortressDEV
2020-05-18T10:24:19.3242945Z ##[debug]slotName=production
2020-05-18T10:24:19.3255404Z ##[debug]appSettings=[
  {"name":"APPINSIGHTS_INSTRUMENTATIONKEY","value":"***","slotSetting":true},
  {"name":"AzureWebJobsDashboard","value":"***","slotSetting":false},
  {"name":"AzureWebJobsStorage","value":"***","slotSetting":false},
  {"name":"FUNCTIONS_EXTENSION_VERSION","value":"~1","slotSetting":false},
  {"name":"WEBSITE_CONTENTAZUREFILECONNECTIONSTRING","value":"***","slotSetting":false},
  {"name":"WEBSITE_CONTENTSHARE","value":"wecdata-iBuyer-dev","slotSetting":false}
]
2020-05-18T10:24:19.3260587Z ##[debug]generalSettings=null
2020-05-18T10:24:19.3261882Z ##[debug]connectionStrings=null
2020-05-18T10:24:19.3263875Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 auth scheme = ServicePrincipal
2020-05-18T10:24:19.3266239Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 data subscriptionid = 118247e6-80ef-4a95-a9cc-3c656affb9ea
2020-05-18T10:24:19.3268473Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 data subscriptionname = Wedgewood - Azure Open
2020-05-18T10:24:19.3271567Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 auth param serviceprincipalid = ***
2020-05-18T10:24:19.3274572Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 data environmentAuthorityUrl = https://login.windows.net/
2020-05-18T10:24:19.3277605Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 auth param tenantid = ***
2020-05-18T10:24:19.3279626Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7=https://management.azure.com/
2020-05-18T10:24:19.3281531Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 data environment = AzureCloud
2020-05-18T10:24:19.3284391Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 auth scheme = ServicePrincipal
2020-05-18T10:24:19.3286387Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 data msiclientId = undefined
2020-05-18T10:24:19.3288684Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 data activeDirectoryServiceEndpointResourceId = https://management.core.windows.net/
2020-05-18T10:24:19.3292415Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 data AzureKeyVaultServiceEndpointResourceId = https://vault.azure.net
2020-05-18T10:24:19.3295105Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 data AzureKeyVaultDnsSuffix = vault.azure.net
2020-05-18T10:24:19.3300564Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 auth param authenticationType = ***
2020-05-18T10:24:19.3302305Z ##[debug]credentials spn endpoint
2020-05-18T10:24:19.3305781Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 auth param serviceprincipalkey = ***
2020-05-18T10:24:19.3307962Z ##[debug]9cf4098e-1634-42b6-93d3-f4321fcfc2c7 data EnableAdfsAuthentication = false
2020-05-18T10:24:19.3322336Z ##[debug]{"subscriptionID":"118247e6-80ef-4a95-a9cc-3c656affb9ea","subscriptionName":"Wedgewood - Azure Open","servicePrincipalClientID":"***","environmentAuthorityUrl":"https://login.windows.net/","tenantID":"***","url":"https://management.azure.com/","environment":"AzureCloud","scheme":"ServicePrincipal","activeDirectoryResourceID":"https://management.azure.com/","azureKeyVaultServiceEndpointResourceId":"https://vault.azure.net","azureKeyVaultDnsSuffix":"vault.azure.net","authenticationType":"***","servicePrincipalKey":***,"isADFSEnabled":false,"applicationTokenCredentials":{"clientId":"***","domain":"***","baseUrl":"https://management.azure.com/","authorityUrl":"https://login.windows.net/","activeDirectoryResourceId":"https://management.azure.com/","isAzureStackEnvironment":false,"authType":"***","secret":***,"isADFSEnabled":false}}
2020-05-18T10:24:19.3404460Z Got service connection details for Azure App Service:'wecdata-iBuyer-dev'
2020-05-18T10:24:19.3407140Z ##[debug]Resource Group: FortressDEV
2020-05-18T10:24:19.4607378Z ##[debug]Processed: ##vso[telemetry.publish area=TaskEndpointId;feature=AzureRmWebAppDeployment]{"endpointId":"9cf4098e-1634-42b6-93d3-f4321fcfc2c7"}
2020-05-18T10:24:19.4617084Z Trying to update App Service Application settings. Data: {"APPINSIGHTS_INSTRUMENTATIONKEY":"***","AzureWebJobsDashboard":"***","AzureWebJobsStorage":"***","FUNCTIONS_EXTENSION_VERSION":"~1","WEBSITE_CONTENTAZUREFILECONNECTIONSTRING":"***","WEBSITE_CONTENTSHARE":"wecdata-iBuyer-dev"}
2020-05-18T10:24:19.4619940Z ##[debug][POST]https://login.windows.net/***/oauth2/token/
2020-05-18T10:24:19.6901505Z ##[debug][POST]https://management.azure.com/subscriptions/118247e6-80ef-4a95-a9cc-3c656affb9ea/resourceGroups/FortressDEV/providers/Microsoft.Web/sites/wecdata-iBuyer-dev/config/appsettings/list?api-version=2016-08-01
2020-05-18T10:24:20.7018810Z ##[debug]Correlation ID from ARM api call response : 72a70ce7-47b5-45f5-88fd-e82d05e1e7f8
2020-05-18T10:24:20.7022453Z ##[debug]APPINSIGHTS_INSTRUMENTATIONKEY is already present.
2020-05-18T10:24:20.7024754Z ##[debug]AzureWebJobsDashboard is already present.
2020-05-18T10:24:20.7026679Z ##[debug]AzureWebJobsStorage is already present.
2020-05-18T10:24:20.7028513Z ##[debug]FUNCTIONS_EXTENSION_VERSION is already present.
2020-05-18T10:24:20.7030594Z ##[debug]WEBSITE_CONTENTAZUREFILECONNECTIONSTRING is already present.
2020-05-18T10:24:20.7032530Z ##[debug]Value of WEBSITE_CONTENTSHARE has been changed to "wecdata-iBuyer-dev"
2020-05-18T10:24:20.7064122Z ##[debug][PUT]https://management.azure.com/subscriptions/118247e6-80ef-4a95-a9cc-3c656affb9ea/resourceGroups/FortressDEV/providers/Microsoft.Web/sites/wecdata-iBuyer-dev/config/appsettings?api-version=2016-08-01
2020-05-18T10:24:22.0312617Z ##[debug]Correlation ID from ARM api call response : 420244f2-450a-419a-8b85-effb72c619ae
2020-05-18T10:24:22.0337986Z ##[debug]task result: Failed
2020-05-18T10:24:22.0445295Z ##[error]Error: Application Settings object is not a valid JSON.
2020-05-18T10:24:22.0483272Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Application Settings object is not a valid JSON.
2020-05-18T10:24:22.0520878Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Application Settings object is not a valid JSON.
2020-05-18T10:24:22.0595997Z ##[section]Finishing: Azure App Service Settings: wecdata-iBuyer-dev

```

## Troubleshooting
<img width="1120" alt="Screen Shot 2020-05-18 at 1 58 43 AM" src="https://user-images.githubusercontent.com/37010344/82195312-f9be0c00-98ac-11ea-85fc-c2b1c0fd53ae.png">

### Error logs
<img width="633" alt="Screen Shot 2020-05-18 at 1 55 19 AM" src="https://user-images.githubusercontent.com/37010344/82195398-1c502500-98ad-11ea-9fd9-f5487ea18c0c.png">

**Comment by eaarora-ms** [comment] 2020-05-19 05:37
@ukhan262 The issue is not with the JSON being invalid. It is actually failing at updating the app settings part: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureAppServiceSettingsV1/azurewebappsettings.ts#L62

We will resolve the error logs issue, however, to find out the actual reason why your pipeline is failing can you please attach your release debug logs here after setting "system.debug" as true in your release pipeline.

**Comment by ukhan262** [comment] 2020-05-19 06:11
@eaarora-ms please check out full logs in the pipeline in the zipped folder. The logs for the specific function app deployment are attached separately as well in the text file.
[logs_4398.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4648515/logs_4398.zip)
[Deploy_FunctionApps_Project.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4648517/Deploy_FunctionApps_Project.txt)

**Comment by eaarora-ms** [comment] 2020-05-19 07:01
@ukhan262  Hi I see from the logs that you are updating the app service settings immediately after deploying it. Can you please try adding a sleep of about 15-20 seconds after the deployment and before the app service settings task and let us know the results?

**Comment by ukhan262** [comment] 2020-05-19 08:18
@eaarora-ms still facing the same issue. I added a ps command after the azure function deployment and before the AzureAppServiceSettings task to sleep the thread for 20 seconds.
`sleep -s 20`
please check out the logs in the attachment.
[deploy logs with sleep.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4649074/deploy.logs.with.sleep.txt)

**Comment by eaarora-ms** [comment] 2020-05-19 08:48
PR for updating error logs: https://github.com/microsoft/azure-pipelines-tasks/pull/12931

**Comment by eaarora-ms** [comment] 2020-05-19 08:58
Please confirm :
1. If you are able to update the app settings from the Azure portal
2. If you are able to successfully run the tasks with all the other tasks disabled.

**Comment by eaarora-ms** [comment] 2020-05-19 08:59
@ukhan262 Please confirm :
1. If you are able to update the app settings from the Azure portal (if not. please tell us the error which you are seeing there).
2. If you are able to successfully run the tasks with all the other tasks disabled.
3. You app service is up and running.

**Comment by ukhan262** [comment] 2020-05-19 19:24
@eaarora-ms thanks for fixing the error log. Do you know when would that be rolled out?

**Comment by ukhan262** [comment] 2020-05-19 20:54
> @ukhan262 Please confirm :
> 
> 1. If you are able to update the app settings from the Azure portal (if not. please tell us the error which you are seeing there).
> 2. If you are able to successfully run the App service settings task with all the other tasks disabled.
> 3. You app service is up and running.
for #1, I was able to update on Azure portal.
for #2, running my builds now. I will share the results.
for #3, the app service is up and running.

**Comment by eaarora-ms** [comment] 2020-05-20 05:28
@ukhan26 It will take around 4-5 weeks for the changes to reach all the accounts.

**Comment by ukhan262** [comment] 2020-05-22 07:30
@eaarora-ms thanks for the update.. Did you see my above comments?

**Comment by andmig-ilty** [comment] 2020-05-25 09:40
@eaarora-ms We are suffering the same issue rised by @ukhan262 . I also confirm that the Setting step fails even if it's the only task in the job and target App Service normally up&running.
We haven't identified a pattern. Eg. we have two "twin" app services and the configuration settings is failing only in one of the two. If i retry few hours later, everything may work fine...

**Comment by raswinraaj** [comment] 2020-05-27 08:55
I have the same issue as well.

**Comment by Roshan-Kumar-Microsoft** [comment] 2020-07-02 19:49
Closing this issue as this fix get deployed ..If you still face same issue please let us know

**Closed by Roshan-Kumar-Microsoft** 2020-07-02 19:49 UTC
Labels: Area: Release, bug

**Comment by jasric89** [comment] 2021-06-03 12:48
Did this get fixed? As I am having the exact same issue on the smallest amount of App Setting information being applied.

**Comment by A139954** [comment] 2024-10-17 02:01
I am getting the same issue, did anyone find the resolution for the same?
 
##[error]Error: Application Settings object is not a valid JSON.

**Comment by retealcom** [comment] 2024-10-18 12:46
I am also receiving the same issue

**Comment by retealcom** [comment] 2024-10-21 06:42
I found my issue: I had a password in my variable group which contained a character which was not escaped. Because the password was hidden it was hard to find...

**Comment by mickey-stringer** [comment] 2025-04-22 16:06
For anyone else who lands here and is trying to pass a variable to the appSettings argument, [this SO](https://stackoverflow.com/a/73472750/11870335) post helped me resolve the issue by ensuring the JSON content of the variable is a single line with no white space. E.g. in a powershell script, use `ConvertTo-Json` with the `-Compress` switch.
