### ISSUE TITLE
JenkinsQueueJob: Job progress tracking failed to read job progress

### ISSUE THREAD

**Issue by Nekto89** [microsoft/azure-pipelines-tasks#13014] opened 2020-05-27 17:05 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: JenkinsQueueJob

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - TFS on-premise Version Dev17.M153.5

- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Windows 10.0.18363,  Agent.Version 2.153.1

## Issue Description

Sometimes task loses connection to Jenkins server temporarily. But it continues to wait until job finishes on Jenkins side. 
![image](https://user-images.githubusercontent.com/4276548/83050189-d76a8200-a054-11ea-8321-48bb86759a9c.png)
Task fails, build fails. At the same time info is available that Jenkins job has finished successfully on Summary tab.
![image](https://user-images.githubusercontent.com/4276548/83050286-01bc3f80-a055-11ea-8487-5659de840865.png)

### Task logs
In the log there may be errors like this in the middle:
"
##[error]Job progress tracking failed to read job progress
Job progress tracking failed to read job progress
HttpResponse.statusCode=500
HttpResponse.statusMessage=Server Error
##[error]Job progress tracking failed to read job progress
"

**Comment by ericstrongDevOps** [comment] 2021-01-20 09:36
any update on this issue? TIA

**Comment by walliski** [comment] 2021-05-31 08:58
I am also still seeing this issue now and then, very inconvenient.

**Comment by anatolybolshakov** [comment] 2021-05-31 17:15
Hi @Nekto89 @ericstrongDevOps @walliski could you please share the logs with this error - for us to understand better how we could fix this? We could add retry logic - but we need to determine where exactly this issue happens.

**Comment by walliski** [comment] 2021-06-02 11:55
@anatolybolshakov 

I managed to reproduce the problem with debug on, by queuing a job in Jenkins that simply had a `sleep` step, and following the (non-existent) console output.

This is what I got in the logs in AzDo:
```
...

##[debug](2:Test Stuff:167) debug: Tracking progress of job URL: https://jenkins.int/job/Test%2520Stuff/167/logText/progressiveText/?start=3827
##[debug]streamConsole().requestCallback()

##[debug](2:Test Stuff:167) debug: Tracking progress of job URL: https://jenkins.int/job/Test%2520Stuff/167/logText/progressiveText/?start=3827
Job progress tracking failed to read job progress

##[debug]streamConsole().requestCallback()
HttpResponse.statusCode=500

##[debug]task result: Failed
HttpResponse.statusMessage=Server Error

##[error]Job progress tracking failed to read job progress
##[debug]Processed: ##vso[task.issue type=error;]Job progress tracking failed to read job progress
##[debug]Processed: ##vso[task.complete result=Failed;]Job progress tracking failed to read job progress

##[debug](2:Test Stuff:167) debug: Tracking progress of job URL: https://jenkins.int/job/Test%2520Stuff/167/logText/progressiveText/?start=3827
##[debug]streamConsole().requestCallback()

...
```

Before and after this was a long list of debug messages for the tracking. So it seems like even if it sets the build as failed, it still continues to poll and run the task in Jenkins (which finished successfully).

The reason why Jenkins threw a random 500 was a "Socket timeout" for the authentication plugin that we are using.

**Comment by anatolybolshakov** [comment] 2021-06-03 17:43
@Nekto89 @walliski thanks! Let us take a look - probably it make sense to add some retry logic for these requests - to avoid intermittent issues.

**Comment by cmwiebe24** [comment] 2021-07-21 15:58
Any update on this issue? Or is there a work around?

**Comment by walliski** [comment] 2021-09-03 06:47
@anatolybolshakov Sorry to be annoying, but any progress on this? This is an issue that we keep seeing almost daily.

**Comment by kuleshovilya** [comment] 2021-09-06 10:58
Hello @walliski We've already implemented this feature, and awaiting for deployment now, it will take few weeks, we will notify you when it's done

**Comment by kuleshovilya** [comment] 2021-10-01 08:55
Feature has been merged, you can check this out now, closing the issue

**Comment by walliski** [comment] 2021-10-13 15:38
The run did not run in debug mode, so what I posted above is the only log output I can see that would be outside of our own scripts output, unless there is something that you are clearly missing? I could try to reproduce the issue again in debug mode though and see if that would bring some more clarity. IIRC I saw some 500 error before in Jenkins logs, but I cannot seem to find that now, so not really sure either what's going on...

**Comment by kuleshovilya** [comment] 2021-10-13 15:42
@walliski Yes, can you please try to reproduce and send logs?

**Comment by anatolybolshakov** [comment] 2021-11-10 14:31
Hi @walliski sorry for the delay - we've added new inputs for JenkinsQueueJob task v2.192.1 - 'retryCount' and 'delayBetweenRetries' (you can find more info in [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/jenkins-queue-job?view=azure-devops)) in [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15211) - could you please check it now? As I see there is a 2.192.0 task version in the last logs - which does not have a fix.

**Comment by walliski** [comment] 2021-11-10 16:35
Will take a look. I saw that the task was updated compared to previous jobs, so I assumed it would have had the changes in it. Now I see that we are on 2.193.0. I'll get back to you if I see more issues, thanks!

**Closed** 2021-11-15 12:20 UTC
Labels: bug, Area: ABTT, Task: JenkinsQueueJob
