### ISSUE TITLE
[BUG]: InstallAppleCertificateV2 could not read certificate from <stdin>

### ISSUE THREAD

**Issue by gildor7** [microsoft/azure-pipelines-tasks#18746] opened 2023-08-01 13:33 UTC
### Task name

InstallAppleCertificateV2

### Task version

2.220.0

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

MacOS

### Task log

```shell
Starting: Install Apple certificate
==============================================================================
Task         : Install Apple certificate
Description  : Install an Apple certificate required to build on a macOS agent machine
Version      : 2.220.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/install-apple-certificate
==============================================================================
/usr/local/bin/openssl pkcs12 -in /Users/runner/work/_temp/DistributionCertificates.p12 -nokeys -passin pass:*** | /usr/local/bin/openssl x509 -sha1 -noout -fingerprint -subject -dates -nameopt utf8,sep_semi_plus_space
Error outputting keys and certificates
00D7294CF87F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:341:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
Could not read certificate from <stdin>
##[error]Error: /usr/local/bin/openssl failed with return code: 1
Finishing: Install Apple certificate
```

### Relevant log output

```shell
Error outputting keys and certificates
00D7294CF87F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:341:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
Could not read certificate from <stdin>
##[error]Error: /usr/local/bin/openssl failed with return code: 1
```

### Aditional info

```shell
Agent name: 'Hosted Agent'
Agent machine name: 'Mac-1690895095778'
Current agent version: '3.224.1'
Operating System
Runner Image
Runner Image Provisioner
Current image version: '20230731.2'
Agent running as: 'runner'

I noticed that the MacOS runner image has just been updated, and before, it was working with the following path "/usr/bin/openssl pkcs12...", but now it's /usr/local/bin/openssl, and it fails.
```

**Comment by ivanduplenskikh** [comment] 2023-08-01 19:51
Hi @gildor7 thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by valosip** [comment] 2023-08-01 19:59
https://github.com/actions/runner-images/issues/8017

**Comment by Cheesebaron** [comment] 2023-08-01 20:03
Related to: https://github.com/microsoft/azure-pipelines-tasks/issues/18560 and possibly a duplicate of this.

**Comment by ivanduplenskikh** [comment] 2023-08-02 12:56
Since it was fixed in this [PR](https://github.com/actions/runner-images/pull/8021) I'm closing this issue for now, feel free to ask any other questions or let us know if it's still relevant for you.

**Closed by ivanduplenskikh** 2023-08-02 12:56 UTC
Labels: bug, Area: Release
