### ISSUE TITLE
CopyFilesOverSSHV0 0.174 adds on a network target path an additional ./ which then fails the build

### ISSUE THREAD

**Issue by inforithmics** [microsoft/azure-pipelines-tasks#13477] opened 2020-08-28 10:03 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CopyFilesOverSSHV0

list here (V0.174 not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/CopyFilesOverSSHV0

## Environment
Azure Pipelines

Agent - Private: 
Agent on MacOs Copy Files to a Windows Machine (Network Path).   
    
## Issue Description

With Update 0.174 it added an additional ./ in front of the Target Path which caused the Build to fail 

### Task logs

0.172
Working:
Copying file 

[Path of Ipa File] to \\\\[Network Path] on remote machine.

0.174
Not Working:
[Path of Ipa File] to ./\\\\[Network Path] on remote machine.

### Checkin causing change
https://github.com/microsoft/azure-pipelines-tasks/commit/872607391d8e3242c2e7cbd3580b2eab0da95196#diff-4c4cee916c8efc058426c4fb2a742ccf

Tasks/CopyFilesOverSSHV0/copyfilesoverssh.ts 
Change from:
```
const targetPath = path.posix.join(targetFolder, relativePath);
```

To:
```
let targetPath = path.posix.join(targetFolder, relativePath);

if (!path.isAbsolute(targetPath)) {
         targetPath = `./${targetPath}`;
}
```
the path.IsAbsolute will say false because it is a windows Path with \\\\ instead of / like for unix

**Comment by inforithmics** [comment] 2020-08-28 10:50
Workaround. Make two Agent Jobs.

1. Agent Job:
On Mac:
    Job Compile and Copy to Remote Machine

2. Agent Job:
On Remote Machine:
    Copy Files from Local Folder to Network Path

**Comment by egor-bryzgalov** [comment] 2020-08-31 14:36
Hi, @inforithmics!

Thank you for opening this issue!
We tried to reproduce the issue but found no cases a UNC path is considered as not absolute by `isAbsolute` method:
`path.isAbsolute(targetPath)`
For us to investigate the issue further, could you please share the following information:
- pipeline logs;
- part of YAML definition containing this task;
- node.js version used on your local machine.

We’re looking forward to hearing from you!

**Comment by egor-bryzgalov** [comment] 2020-09-01 12:49
Hi, @inforithmics!

We managed to find the root cause of the issue. I'll let you know once we prepare a solution.

**Comment by inforithmics** [comment] 2020-09-01 21:18
Great, if you need more info I'll can give it to you tommorrow

**Comment by egor-bryzgalov** [comment] 2020-09-04 14:38
Hi, @inforithmics 

The fix for that issue has been merged. I'll let you know once it's deployed. Thanks!

**Comment by egor-bryzgalov** [comment] 2020-09-28 08:09
Hi, @inforithmics 

I'm closing this issue since the fix is deployed at the moment. Please feel free to reopen it if there are any issues.

**Closed by egor-bryzgalov** 2020-09-28 08:09 UTC
Labels: Area: ABTT, Task: CopyFilesOverSSH, awaiting deployment, bug

**Comment by inforithmics** [comment] 2020-09-28 11:41
Thanks for the fix

**Comment by anatolybolshakov** [comment] 2020-09-28 17:40
@inforithmics sure 😄 please feel free to create another issue or reopen current if you will face any issues again
