### ISSUE TITLE
PublishCodeCoverageResults Fails to Generate HTML Report

### ISSUE THREAD

**Issue by trangevi** [microsoft/azure-pipelines-tasks#13914] opened 2020-11-18 00:42 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishCodeCoverageResultsV1

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishCodeCoverageResultsV1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    Azure Pipelines

- Agent - Hosted or Private: 
    
    Private Ubuntu 16.04

## Issue Description

The PublishCodeCoverageResults task in our build has recently been unable to generate the HTML report, which I believe is what is causing us to be unable to view the CodeCoverage tab we are used to. It seems to be an issue with finding ReportGenerator, but I've included the task logs as I'm unclear what specifically to be looking for.

It seems like it could be introduced in the newest version of the task, as it was working on version 1.175.0, but is now failing on 1.175.2 (I don't have any runs on patch version 1). Nothing else has changed on our pipeline between the two, however it's possible some assumption of ours on how to use the task is no longer valid.

I've attached full debug logs for the failed run. Please let me know if I can provide any further information. Thanks in advance.

### Task logs

[PublishCodeCoverageResults_failed.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5557014/PublishCodeCoverageResults_failed.zip)

### Error logs
```
/usr/bin/dotnet "/agent/_work/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.175.2/netcoreapp2.0/ReportGenerator.dll" -reports:"/agent/_work/4/s/CodeCoverage/Cobertura.xml" -targetdir:"/agent/_work/_temp/cchtml" -reporttypes:HtmlInline_AzurePipelines
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-"/agent/_work/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.175.2/netcoreapp2.0/ReportGenerator.dll" does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
##[warning]Failed to generate Html report. Error: 1
```

**Comment by aressler38** [comment] 2020-11-19 20:49
This is happening to me too. I confirm, it is also happening with the 1.175.2 version. I have a previous run on version 1.175.1 that *worked*, so something broke in 1.175.2. 



```
2020-11-19T18:06:45.7947136Z ##[section]Starting: PublishCodeCoverageResults
2020-11-19T18:06:45.7960861Z ==============================================================================
2020-11-19T18:06:45.7961182Z Task         : Publish code coverage results
2020-11-19T18:06:45.7961460Z Description  : Publish Cobertura or JaCoCo code coverage results from a build
2020-11-19T18:06:45.7961731Z Version      : 1.175.2
2020-11-19T18:06:45.7961923Z Author       : Microsoft Corporation
2020-11-19T18:06:45.7962259Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results
2020-11-19T18:06:45.7962957Z ==============================================================================
2020-11-19T18:06:46.2875879Z [command]/usr/bin/dotnet "/home/vsts/work/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.175.2/netcoreapp2.0/ReportGenerator.dll" -reports:"/home/vsts/work/1/s/coverage/cobertura-coverage.xml" -targetdir:"/home/vsts/work/_temp/cchtml" -reporttypes:HtmlInline_AzurePipelines
2020-11-19T18:06:46.3910421Z 
2020-11-19T18:06:46.3977683Z Welcome to .NET Core 3.1!
2020-11-19T18:06:46.3978839Z ---------------------
2020-11-19T18:06:46.3979176Z SDK Version: 3.1.404
2020-11-19T18:06:46.3979312Z 
2020-11-19T18:06:46.3979436Z Telemetry
2020-11-19T18:06:46.3979733Z ---------
2020-11-19T18:06:46.3980683Z The .NET Core tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
2020-11-19T18:06:46.3981229Z 
2020-11-19T18:06:46.3981825Z Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
2020-11-19T18:06:46.3982079Z 
2020-11-19T18:06:46.3982324Z ----------------
2020-11-19T18:06:46.3982686Z Explore documentation: https://aka.ms/dotnet-docs
2020-11-19T18:06:46.3983022Z Report issues and find source on GitHub: https://github.com/dotnet/core
2020-11-19T18:06:46.3983502Z Find out what's new: https://aka.ms/dotnet-whats-new
2020-11-19T18:06:46.3984010Z Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
2020-11-19T18:06:46.3984586Z Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
2020-11-19T18:06:46.3985111Z Write your first app: https://aka.ms/first-net-core-app
2020-11-19T18:06:46.3985612Z --------------------------------------------------------------------------------------
2020-11-19T18:06:46.5702865Z Could not execute because the specified command or file was not found.
2020-11-19T18:06:46.5703268Z Possible reasons for this include:
2020-11-19T18:06:46.5704049Z   * You misspelled a built-in dotnet command.
2020-11-19T18:06:46.5705187Z   * You intended to execute a .NET Core program, but dotnet-"/home/vsts/work/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.175.2/netcoreapp2.0/ReportGenerator.dll" does not exist.
2020-11-19T18:06:46.5706019Z   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
2020-11-19T18:06:46.5857030Z ##[warning]Failed to generate Html report. Error: 1
2020-11-19T18:06:46.5900205Z Reading code coverage summary from '/home/vsts/work/1/s/coverage/cobertura-coverage.xml'
2020-11-19T18:06:46.6990361Z ##[section]Async Command Start: Publish code coverage
2020-11-19T18:06:46.6990675Z Publishing coverage summary data to TFS server.
2020-11-19T18:06:46.6991076Z  Lines- 438 of 1231 covered.
2020-11-19T18:06:46.6991281Z  Branches- 162 of 654 covered.
2020-11-19T18:06:47.1937909Z Modifying Cobertura Index file
2020-11-19T18:06:47.1938306Z Publishing code coverage files to TFS server.
2020-11-19T18:06:47.1938485Z Uploading 1 files
2020-11-19T18:06:47.1938636Z File upload succeed.
2020-11-19T18:06:47.3472690Z Published '/tmp/Code Coverage Report_816' as artifact 'Code Coverage Report_816'
2020-11-19T18:06:47.3473077Z ##[section]Async Command End: Publish code coverage
2020-11-19T18:06:47.3474335Z ##[section]Finishing: PublishCodeCoverageResults
```

**Comment by MatthiasNistl** [comment] 2020-11-19 22:10
Can confirm this issue with version 1.175.2. Earlier pipeline runs with version 1.175.0 worked fin, now I'm running into the same error messages.

**Comment by adamconnelly** [comment] 2020-11-20 08:21
I can confirm this as well. I've managed to work around the problem by explicitly pinning the task to an older version, like this:

```
PublishCodeCoverageResults@1.175.0
```

I can also confirm that both 1.175.0 and 1.175.1 work correctly, but 1.175.2 doesn't. The strange thing about it is that from looking at the commit history, it looks like the only thing that changed between 1.175.1 and 1.175.2 was the version number being bumped, so I don't quite understand how 1.175.1 is working. Maybe I'm just not understanding how the build / publishing process for these tasks works.

Here's the two PRs corresponding to those new version:

- 1.175.1: https://github.com/microsoft/azure-pipelines-tasks/pull/13814
- 1.175.2: https://github.com/microsoft/azure-pipelines-tasks/pull/13862

And here's the issue relating to the changes: https://github.com/microsoft/azure-pipelines-tasks/issues/13062. It seems to have been trying to solve a problem where the task would fail if there were spaces in the path to the report generator dll by quoting the path. My guess is that the quoting is fine on Windows but causes issues on Linux.

This corresponds with what I can see from the build logs. Here's an example of the command run by 1.175.0:

```shell
/usr/bin/dotnet /home/vsts/work/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.175.1/netcoreapp2.0/ReportGenerator.dll -reports:"/home/vsts/work/_temp/*/coverage.cobertura.xml" -targetdir:"/home/vsts/work/_temp/cchtml" -reporttypes:HtmlInline_AzurePipelines
```

And here's an example of the command run by 1.175.2:

```shell
/usr/bin/dotnet "/home/vsts/work/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.175.2/netcoreapp2.0/ReportGenerator.dll" -reports:"/home/vsts/work/_temp/*/coverage.cobertura.xml" -targetdir:"/home/vsts/work/_temp/cchtml" -reporttypes:HtmlInline_AzurePipelines
```

I'll add a comment to the issue that this change was introduced for asking for it to be reverted until it can be fixed properly.

**Comment by knom** [comment] 2020-11-20 09:18
+1 one!
I'm hitting this as well - on several of my projects...

Pinning of minor version wasn't something I was aware of..
So a good workaround for now..

Looking forward to a bugfix on this..

**Comment by ShreyasRmsft** [comment] 2020-11-20 09:49
We will try and patch this immediately.

**Comment by dkstringer** [comment] 2020-11-20 09:49
I have observed the same bug. Most of my pipelines are using vmIImage: ubuntu-latest, and they all have the same error.

I have just seen a pipeline using vmImage: windows-latest work correctly with the exact same PublicCodeCoverageResults@1 (v1.175.2) task.
It successfully located the file D:\a\_tasks\PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97\1.175.2\netcoreapp2.0\ReportGenerator.dll in the run log.

The failing ubuntu runs are trying to locate the file /home/vsts/work/_tasks/PublishCodeCoverageResults_2a7ebc54-c13e-490e-81a5-d7561ab7cd97/1.175.2/netcoreapp2.0/ReportGenerator.dll,

**Comment by egor-bryzgalov** [comment] 2020-11-20 13:40
@dkstringer @adamconnelly @knom @MatthiasNistl @aressler38 @trangevi 
Hi everyone!

Thank you for the information you've provided!
The fix was applied. Could you please confirm that it works fine for you at the moment?
The fixed version is `1.178.0`.
Thank you!

**Comment by aressler38** [comment] 2020-11-20 15:09
Thanks @egor-bryzgalov. I can see it working now in 1.178.0.

**Comment by egor-bryzgalov** [comment] 2020-11-20 15:10
@aressler38 
Thank you! 
Closed this issue as resolved. Please feel free to reopen if you have any issues.

**Closed by egor-bryzgalov** 2020-11-20 15:10 UTC
Labels: Area: ABTT, Area: CodeCoverage, Area: Test, bug

**Comment by trangevi** [comment] 2020-11-20 16:26
I confirmed it's working for me now as well. Thank you for the quick turn around!

**Comment by adamconnelly** [comment] 2020-11-20 18:39
Me too - thanks for getting it sorted so quickly!
