### ISSUE TITLE
Azure devops. AzureCLI extension. az login command fails

### ISSUE THREAD

**Issue by marcosfriasraet** [microsoft/azure-pipelines-tasks#13899] opened 2020-11-16 10:47 UTC
HI All.

We have a self-managed pool that PD teams use for different build processes. These servers make use
of the azure devops azure cli extension. We've had this random error for ane week back.
I have tried updating the agents but we keep getting this error. 

##[error]Error Code: [1]
##[error]Error: Azure login failed
##[error]Script failed with error: Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /***/oauth2/token (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x021ECF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)))

We're using this ymal:
- task: AzureCLI@2
      inputs:
        azureSubscription: ${{ variables.subscription }}
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |       
          $storageKey=$(az storage account keys list -g $(resourceGroup) --account-name $(storageAccountName) --query "[0].value" --output tsv)        
          Write-Host "##vso[task.setvariable variable=storageKey;]$storageKey"
      displayName: 'Get Storage Account Key'

Could you guide us to the cause of it?

**Comment by tiwarishub** [comment] 2020-12-22 08:44
Hi @marcosfriasraet,
  Apologies for late reply, this seems to be connection issue. Is your machine able to connect to  https://login.microsoftonline.com ?

**Comment by tiwarishub** [comment] 2020-12-30 18:11
Hi @marcosfriasraet , any update on this

**Comment by bishal-pdMSFT** [comment] 2020-12-31 21:55
The error mostly looks to be a proxy issue: `(Caused by ProxyError('Cannot connect to proxy.'`
@marcosfriasraet 
1. If your proxy setup is new, you can configure the ADO agent to use the proxy when running tasks
2. If the proxy settings were already there, I would suggest you to get in touch with your networking team to ensure that proxy is not issue, Also, ensure that credentials specified in ADO agent settings are still valid.

**Comment by tiwarishub** [comment] 2021-01-04 04:33
closing this as we have not received any response. Please feel free to open a issue, if you face this issue

**Closed by tiwarishub** 2021-01-04 04:33 UTC
Labels: Area: Release, triage

**Comment by marcosfriasraet** [comment] 2021-01-11 07:41
Hi .
Sorry a lot for late reply.. i was on holidays. The issue is solved..
Thanks a lot for your time.
