### ISSUE TITLE
Unable to locate executable file: 'bash'. 

### ISSUE THREAD

**Issue by AndreiBarbuOz** [microsoft/azure-pipelines-tasks#12631] opened 2020-04-06 15:10 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Command line

## Environment
- Server - Azure Pipelines 

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/andreibarbu0946/UiPathGoodPractices 
pipeline AndreiBarbuOz.uipath-doc-manipulation
buildId=475

- Agent - hosted
Azure Pipelines 10, Agent version: 2.165.2

## Issue Description
2020-04-06T14:41:31.4556994Z ##[section]Starting: Build artifact
2020-04-06T14:41:31.4698083Z ==============================================================================
2020-04-06T14:41:31.4698855Z Task         : Command line
2020-04-06T14:41:31.4699464Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2020-04-06T14:41:31.4700029Z Version      : 2.164.0
2020-04-06T14:41:31.4700473Z Author       : Microsoft Corporation
2020-04-06T14:41:31.4701058Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2020-04-06T14:41:31.4701717Z ==============================================================================
2020-04-06T14:41:32.3211213Z Generating script.
2020-04-06T14:41:32.3239876Z Script contents:
2020-04-06T14:41:32.3242191Z c:\my_prog.exe -pack C:\__w\1\s\project.json -o C:\__w\1\a\ -v 1.0.475
2020-04-06T14:41:32.3251114Z ========================== Starting Command Output ===========================
2020-04-06T14:41:32.3397439Z ##[error]Unable to locate executable file: 'bash'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

2020-04-06T14:41:32.3639089Z ##[section]Finishing: Build artifact

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by damccorm** [comment] 2020-04-06 19:13
This is a dupe of https://github.com/microsoft/azure-pipelines-tasks/issues/12537 - lets follow up there as needed

**Closed by damccorm** 2020-04-06 19:13 UTC
Labels: bug, route
