### ISSUE TITLE
PublishCodeCoverageResults@1 makes Deploy stage fail in a YAML release pipeline

### ISSUE THREAD

**Issue by nulltoken** [microsoft/azure-pipelines-tasks#10391] opened 2019-05-16 11:16 UTC
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PublishCodeCoverageResults@1 (v1.151.2)

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
account name: _See note below_
team project name: _See note below_
build number: Failing -> `118668` / Passing (with the task commented out) -> `118671`

_**Note:**_  Is there a way for me to send those requested informations without publicly publishing them ?

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: `vmImage: windows-2019`

## Issue Description

This issue _might_ be a duplicate of #10336 
Similarly we're running a multi stages yaml pipeline.
When the publishcodecoverage  task is defined, the Deploy Stage is marked as Failed and the Stage job as Canceled
![image](https://user-images.githubusercontent.com/92363/57849270-28f1f700-77db-11e9-98b6-ac0dcb907c4a.png)
![image](https://user-images.githubusercontent.com/92363/57849312-47f08900-77db-11e9-9028-2986f2f00a4c.png)

Running another build with the task commented out makes everything pass
![image](https://user-images.githubusercontent.com/92363/57849390-79695480-77db-11e9-890f-4adfa80709b5.png)
![image](https://user-images.githubusercontent.com/92363/57849408-8423e980-77db-11e9-961a-a0f80048c73a.png)

There is no downloadable log for the Deploy Stage when it fails.

### Task logs

Is there a way for me to send those logs without publicly publishing them ?

**Comment by timker** [comment] 2019-05-18 21:50
I had the same issue, I believe it's due to a " " (space) in the code coverage report folder.
Actually looks more like a bug in release pipelines, than the PublishCodeCoverageResults task itself.

the automatic template has two spaces "Code Coverage Report_$(Build_ID)"

Is there a place we can raise bugs directly for pipeline issues?

**Comment by timker** [comment] 2019-05-18 21:53
#10336 could be a duplicate

**Comment by nulltoken** [comment] 2019-05-20 03:11
>Is there a way for me to send those logs without publicly publishing them ?

@ankit-nitd As proposed in #10336, I've tried to send the build logs to "devops_tools AT microsoft DOT com" but received a reply saying 

"The group sa[REDACTED] only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list."

**Comment by prawalagarwal** [comment] 2019-05-20 08:33
@nulltoken We have received the logs. We will get back with the analysis.

**Comment by ankit-nitd** [comment] 2019-05-21 08:08
@ericsciple On investigating this issue, we found that publish code coverage task is able to generate/publish the code coverage results. Its getting uploaded to the artifactory and we are able to see the code coverage tab as well. However, in the deploy stage, it's trying to download the artifacts where this error occurs. Ideally, this should have come in the publish step itself where we try to upload files with invalid names or if uploading is allowed, downloading should also be allowed. Can you please look into this?

Here is the repro build where this is occurring: https://dev.azure.com/testPipelineTasks/testPipeline/_build/results?buildId=48&view=results

**Comment by ericsciple** [comment] 2019-05-21 16:43
@kasubram it sounds like this may be a download task that is injected? You might need to use the NameValidation.Sanitize function to strip invalid chars from the ref name. Check w/ Zach if that's the right function.

**Comment by nulltoken** [comment] 2019-06-14 12:24
@ankit-nitd Thanks a lot for the repro!

Have you agrred on an approach to solve this?

**Comment by bryanmacfarlane** [comment] 2019-07-11 12:43
@kasubram for download task injection question above.

**Comment by kasubram** [comment] 2020-01-17 18:36
We auto inject only download build artifact or download pipeline artifact task, that too only deployment job.
While we auto inject, we append the artifact name in the display name, the ref name of the task will not contain the artifact name in it. So not sure if this is relevant to auto injection of the task.

If you still see this issue, please give me a build where its reproduced. I can probably help redirecting to the right owner. I am closing this for now. Please reopen if you are still facing this.

**Closed by kasubram** 2020-01-17 18:36 UTC
Labels: Area: Release, bug
