### ISSUE TITLE
[Universal Download] Fails with "Package not found" while the package is certainly there.

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-tasks#12810] opened 2020-05-01 11:00 UTC
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UniversalPackages

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://unit4.visualstudio.com/SME/_build/results?buildId=107376&view=logs&j=fd896be6-bf06-5b3e-7230-2613a03eac3c&t=1e8b92dc-94e5-5063-acc7-303b93b41912&l=15

- Agent - Hosted or Private: 
    - If using Hosted agent, provide agent queue name:
Azure Pipelines

Starting: Initialize job
Agent name: 'Azure Pipelines 2'
Agent machine name: 'fv-az74'
Current agent version: '2.166.4'
Current image version: '20200426.1'

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

In one job the download fails:

```
2020-05-01T10:53:09.3675521Z ##[section]Starting: Universal download psqlex-11.70
2020-05-01T10:53:09.3776434Z ==============================================================================
2020-05-01T10:53:09.3776749Z Task         : Universal packages
2020-05-01T10:53:09.3777803Z Description  : Download or publish Universal Packages
2020-05-01T10:53:09.3778074Z Version      : 0.166.2
2020-05-01T10:53:09.3778300Z Author       : Microsoft Corporation
2020-05-01T10:53:09.3778584Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
2020-05-01T10:53:09.3778935Z ==============================================================================
2020-05-01T10:53:09.8905693Z SYSTEMVSSCONNECTION exists true
2020-05-01T10:53:10.0982355Z Found tool in cache: artifacttool 0.2.128 x64
2020-05-01T10:53:10.1408589Z SYSTEMVSSCONNECTION exists true
2020-05-01T10:53:10.3244959Z Downloading package: 42ec5789-44a9-4961-bc66-87ccc7fb6a84, version: 11.70.* using feed id: bfb9cf27-0789-47a4-ab3a-1fe21f9035b7, project: 81dea1dd-cac5-4d61-81a3-b2e7ff0c64bf
2020-05-01T10:53:10.3306868Z [command]C:\hostedtoolcache\windows\artifacttool\0.2.128\x64\ArtifactTool.exe universal download --feed bfb9cf27-0789-47a4-ab3a-1fe21f9035b7 --service https://unit4.visualstudio.com/ --package-name 42ec5789-44a9-4961-bc66-87ccc7fb6a84 --package-version 11.70.* --path c:\deps\redist\psqlex-11.70 --patvar UNIVERSAL_DOWNLOAD_PAT --verbosity None --project 81dea1dd-cac5-4d61-81a3-b2e7ff0c64bf
2020-05-01T10:53:11.4619471Z {"@t":"2020-05-01T10:53:11.4313495Z","@m":"Cannot find the package '42ec5789-44a9-4961-bc66-87ccc7fb6a84' in feed 'Venice'","@i":"2f38f111","@l":"Error","SourceContext":"ArtifactTool.Program","UtcTimestamp":"2020-05-01 10:53:11.431Z"}
2020-05-01T10:53:11.5020172Z ##[error]Error: An unexpected error occurred while trying to download the package. Exit code(18) and error({"@t":"2020-05-01T10:53:11.4313495Z","@m":"Cannot find the package '42ec5789-44a9-4961-bc66-87ccc7fb6a84' in feed 'Venice'","@i":"2f38f111","@l":"Error","SourceContext":"ArtifactTool.Program","UtcTimestamp":"2020-05-01 10:53:11.431Z"})
2020-05-01T10:53:11.5031146Z ##[error]Packages failed to download
2020-05-01T10:53:11.5034212Z ##[section]Finishing: Universal download psqlex-11.70
```

In another job (MultiConfiguration)  in the same build it succeeds:

```
2020-05-01T10:53:09.0196066Z ##[section]Starting: Universal download psqlex-11.70
2020-05-01T10:53:09.0299920Z ==============================================================================
2020-05-01T10:53:09.0300187Z Task         : Universal packages
2020-05-01T10:53:09.0300405Z Description  : Download or publish Universal Packages
2020-05-01T10:53:09.0300673Z Version      : 0.166.2
2020-05-01T10:53:09.0300855Z Author       : Microsoft Corporation
2020-05-01T10:53:09.0301096Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
2020-05-01T10:53:09.0301378Z ==============================================================================
2020-05-01T10:53:09.5141571Z SYSTEMVSSCONNECTION exists true
2020-05-01T10:53:09.8785753Z Found tool in cache: artifacttool 0.2.128 x64
2020-05-01T10:53:09.9225161Z SYSTEMVSSCONNECTION exists true
2020-05-01T10:53:10.3148916Z Downloading package: psqlex, version: 11.70.* using feed id: bfb9cf27-0789-47a4-ab3a-1fe21f9035b7, project: 81dea1dd-cac5-4d61-81a3-b2e7ff0c64bf
2020-05-01T10:53:10.3210665Z [command]C:\hostedtoolcache\windows\artifacttool\0.2.128\x64\ArtifactTool.exe universal download --feed bfb9cf27-0789-47a4-ab3a-1fe21f9035b7 --service https://unit4.visualstudio.com/ --package-name psqlex --package-version 11.70.* --path c:\deps\redist\psqlex-11.70 --patvar UNIVERSAL_DOWNLOAD_PAT --verbosity None --project 81dea1dd-cac5-4d61-81a3-b2e7ff0c64bf
2020-05-01T10:53:12.6442440Z {"@t":"2020-05-01T10:53:11.3969417Z","@m":"ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 472f0d67-aa61-4877-918e-d93e8fd31e72","@i":"521fe2c2","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-05-01 10:53:11.396Z"}
2020-05-01T10:53:12.6444512Z {"@t":"2020-05-01T10:53:11.5657745Z","@m":"Found matching version: 11.70.0","@i":"0fbde3f2","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-05-01 10:53:11.565Z"}
2020-05-01T10:53:12.6445506Z {"@t":"2020-05-01T10:53:11.6146749Z","@m":"Obtained package metadata","@i":"ae648446","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-05-01 10:53:11.614Z"}
2020-05-01T10:53:12.6446587Z {"@t":"2020-05-01T10:53:11.6216317Z","@m":"DedupManifestArtifactClient will correlate http requests with X-TFS-Session 472f0d67-aa61-4877-918e-d93e8fd31e72","@i":"20b5e8be","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-05-01 10:53:11.621Z"}
2020-05-01T10:53:12.6448082Z {"@t":"2020-05-01T10:53:11.6714752Z","@m":"ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodsu6weu.vsblob.visualstudio.com/Aa1bc788c-dfe4-4175-bb3e-43efa6fc79d4/_apis/dedup/chunks/A4104379CF1FE0C7E99126B55E5011583CE786E8FB320672570955A5DA474B8A01 attempt 1/6 failed with StatusCode RedirectMethod, IsRetryableResponse False","@i":"62035b14","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-05-01 10:53:11.671Z"}
2020-05-01T10:53:12.6449410Z {"@t":"2020-05-01T10:53:11.8588551Z","@m":"Could not initialize dataport.","@i":"62e541c0","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-05-01 10:53:11.858Z"}
2020-05-01T10:53:12.6450409Z {"@t":"2020-05-01T10:53:11.8620093Z","@m":"Downloaded 0,0 MB out of 0,8 MB (0%).","@i":"61dba2c1","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-05-01 10:53:11.862Z"}
2020-05-01T10:53:12.6451346Z {"@t":"2020-05-01T10:53:12.5996569Z","@m":"Downloaded 0,8 MB out of 0,8 MB (100%).","@i":"71c1b2f3","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-05-01 10:53:12.599Z"}
2020-05-01T10:53:12.6453205Z {"@t":"2020-05-01T10:53:12.6007783Z","@m":"\r\nDownload statistics:\r\nTotal Content: 0,8 MB\r\nPhysical Content Downloaded: 0,3 MB\r\nCompression Saved: 0,5 MB\r\nLocal Caching Saved: 0,0 MB\r\nChunks Downloaded: 12\r\nNodes Downloaded: 0\r\n","@i":"b6df556f","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-05-01 10:53:12.600Z"}
2020-05-01T10:53:12.6456729Z {"@t":"2020-05-01T10:53:12.6073767Z","@m":"Download completed.","@i":"a846a6db","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-05-01 10:53:12.607Z"}
2020-05-01T10:53:12.6459617Z {"@t":"2020-05-01T10:53:12.6074563Z","@m":"Download complete","@i":"4e25de8d","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-05-01 10:53:12.607Z"}
2020-05-01T10:53:12.6460486Z {"@t":"2020-05-01T10:53:12.6213796Z","@m":"Success","@i":"1d9af52f","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-05-01 10:53:12.621Z"}
2020-05-01T10:53:12.6461314Z {"Version":"11.70.0","SuperRootId":"A4F3D85ADE488C42581B6CC1832AAD80CA5A212ECFE55E0604D9605A0FC0DB7E02","ManifestId":"A4104379CF1FE0C7E99126B55E5011583CE786E8FB320672570955A5DA474B8A01"}
2020-05-01T10:53:12.6481530Z ##[section]Finishing: Universal download psqlex-11.70
```

**Comment by slawekww** [comment] 2020-05-29 13:46
Is it any plan to fix this issue? 

It prevents to use UniversalPackages task in Azure YAML pipelines where vstsPackageVersion is not concrete/fixed version (for example * or 1.*).

**Comment by phil-hodgson** [comment] 2020-09-16 17:24
In the failing case, is there a reason that the package name is specified with a GUID, whilst in the succeeding case it has the package name?

**Comment by slawekww** [comment] 2020-09-18 10:04
@phil-hodgson Per my tests, package name/GUID must be concrete value and it is unrelated to version.
If version is not fixed, it is impossible to download using UniversalPackages.

Note: it is possible to get the latest version of UniversalPackage via API, as example bash script:

       echo "ORGANIZATION: $ORGANIZATION"
       echo "FEEDNAME    : $FEEDNAME"
       echo "PACKAGENAME : $PACKAGENAME"

       ALL_PACKAGES=`curl -u :$TOKEN https://feeds.dev.azure.com/${ORGANIZATION}/_apis/packaging/Feeds/${FEEDNAME}/packages?api-version=5.1-preview.1`
       
       for pack in `jq '.value | keys | .[]' <<< $ALL_PACKAGES`; do
         value=`jq -r ".value[$pack]" <<< $ALL_PACKAGES`;
         found_package_name=`jq -r '.name' <<< "$value"`;
         if [[ $found_package_name == $PACKAGENAME ]]; then
            for version in `jq '.versions | keys | .[]' <<< "$value"`; do
               ver_value=`jq -r ".versions[$version]" <<< "$value"`;
               isLatest=`jq -r '.isLatest' <<< "$ver_value"`;
               if [[ $isLatest == "true" ]]; then
                  latestVersion=`jq -r '.version' <<< "$ver_value"`;
                  echo "latestVersion: $latestVersion"
                  return
               fi
            done
         fi
       done

**Comment by omokoh** [comment] 2020-09-30 17:11
Hi,
We are currently investigating this issue, we will let you know when we have more updates. 
Thanks

**Comment by zhenghao104** [comment] 2020-10-05 23:46
Hello,

Can you try using package name instead of GUID to see if it works?

Using az cli instead of artifacttool directly is the recommended approach: https://www.1eswiki.com/wiki/Azure_Artifacts_ArtifactTool#Using_ArtifactTool_on_Universal_Packages

**Comment by slawekww** [comment] 2020-10-22 08:03
Used az command and package name to download universal artifact:

`az artifacts universal download   --organization "https://dev.azure.com/myorg/"   --feed "myfeed"   --name "myname"   --version "1.*"   --path .
`
`
Did not find any versions of 'myname' that matched the pattern '348.*' (Pre-release versions are not currently matched by wildcard patterns)
`

Universal packages are used by Azure YAML pipeline to be validated and marked released if tests passed.
Now API must be used to retrieve the latest version which should be taken by pipeline for testing.

**Comment by zhenghao104** [comment] 2020-10-22 17:47
Hello,

Thanks for your feedback. I tried to reproduce the error and using wild card works for me. I have a feed with version 0.0.1 and 0.02 and specifying the version to 0.* using az artifacts universal download get me the latest version of the feed successfully.

 Can you provide a screenshot of your feed versions, your YAML and also the full log?

See here for similar issue regarding wild card: https://github.com/microsoft/azure-pipelines-tasks/issues/12572

**Comment by slawekww** [comment] 2020-10-23 07:38
Yes, it may work for released versions. I have pre-release versions and per statement in error log:
`
Did not find any versions of 'myname' that matched the pattern '1.*' (Pre-release versions are not currently matched by wildcard patterns)
`

It means that wildcards do not work for pre-release versions.
Do you plan to fix it?

**Comment by magleaso** [comment] 2020-10-23 17:33
Hi @slawekww. Our response is the same as when this issue was discussed in issue #12572. We don't have any near term plans to implement wildcard matching for pre-release versions in UPack. You can use [pre-release and release views](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops) in your feed for differentiating between released and pre-release packages. For storing strings in the version number, you can use [build metadata](https://semver.org/#spec-item-10) as defined in the semver v2 spec.

I'm closing this issue because the original request is not related to pre-release matching. If you are having trouble implementing the solution I recommended, please feel free to create a new github issue with any specific errors you're running into along the way.

@omokoh can you make sure we have a feature request logged somewhere for wildcard matching on pre-release versions in UPack?

**Closed by magleaso** 2020-10-23 17:33 UTC
Labels: Area: Artifacts, aa-backlog, bug

**Comment by hansmbakker** [comment] 2022-01-24 12:14
Please upvote for wildcards for pre-releases at https://developercommunity.visualstudio.com/t/Support-wildcards-for-prereleases-when-i/1645572
