### ISSUE TITLE
Azure Resource Group Deployment fails to deploy to new resource group

### ISSUE THREAD

**Issue by JoeGaggler** [microsoft/azure-pipelines-tasks#10673] opened 2019-06-17 18:44 UTC
## Required Information

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: AzureResourceGroupDeploymentV2

## Environment
- Server - Azure Pipelines (private)
    
- Agent - Private, Windows 10.0.14393, Agent 2.153.2
    
## Issue Description

Deployments that involve creating a new Resource Group tend to fail. The logs indicate that the resource group was created, but subsequently cannot find it when attempting to create the resources inside of it. Retrying the deployment succeeds.

![image](https://user-images.githubusercontent.com/27233871/59628269-da9b8500-9105-11e9-8784-4463dd15e2e5.png)

**Comment by vinodkumar3** [comment] 2019-06-18 07:54
I'm not able to reproduce the issue. Please provide the minimalist ARM template where you hit the issue.

**Comment by vinodkumar3** [comment] 2019-06-19 11:20
@JoeGaggler 
One more thing, are you facing this issue intermittently or every time when the task creates new Resource Group?

**Comment by JoeGaggler** [comment] 2019-06-19 16:40
@vinodkumar3 it is not happening every time. I am setting up a deployment where I can repeatedly deploy this ARM template to attempt to repro.

Template attached:
[failing-arm-template.txt](https://github.com/microsoft/azure-pipelines-tasks/files/3307088/failing-arm-template.txt)

**Comment by JoeGaggler** [comment] 2019-06-26 19:33
This has occurred several times, but I have been unable to repro this in an ad-hoc deployment. Our team does not often need to create new resource groups at this point, and so we will work-around this issue by retrying the deployment when the error occurs.

**Comment by vinodkumar3** [comment] 2019-07-01 04:50
Fix has been merged and will be available in next deployment in few weeks.

**Closed** 2019-07-01 10:36 UTC
Labels: Area: Release
