### ISSUE TITLE
The new validation from pull #11979 is logging plain text secrets if validation fails

### ISSUE THREAD

**Issue by nbowes24** [microsoft/azure-pipelines-tasks#12380] opened 2020-02-19 10:02 UTC
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceGroupDeploymentV2  

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Using azure pipelines

- Agent - Hosted or Private: 

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows_NT, 2.164.8   

## Issue Description

With the validation changes to this task found here: https://github.com/microsoft/azure-pipelines-tasks/pull/11979/files we have found a secret variable being passed to the arm template is failing validation. This secret is then traced out in the logs of this task as plain text.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
The secret variable in plain text is logged as below:

2020-02-07T16:06:41.5654387Z There were errors in your deployment. Error code: InvalidTemplate.
2020-02-07T16:06:41.5719214Z ##[error]Deployment template language expression evaluation failed: 'The language expression ' { "EncodingType": "XXX", "Salt": "XXX", "MinHashLength": 6, "Alphabet": "XXX" }, { "EncodingType": "XXX", "Salt": "XXX", "MinHashLength": 6, "Alphabet": "XXX" }, { "EncodingType": "XXX", "Salt": "XXX", "MinHashLength": 6, "Alphabet": "XXX" }, { "EncodingType": "XXX", "Salt": "XXX", "MinHashLength": 6, "Alphabet": "XXX" }, { "EncodingType": "XXX", "Salt": "XXX", "MinHashLength": 6, "Alphabet": "XXX" } ' is not valid: the string character '{' at position '1' is not expected.'. Please see https://aka.ms/arm-template-expressions for usage details.

**Comment by issacnitin** [comment] 2020-02-20 08:41
@nbowes24 Thanks a lot for reporting the issue! We're actively working on the issue. Will give you a solution/fix it ASAP

**Comment by issacnitin** [comment] 2020-02-27 12:07
@nbowes24 There's a type "securestring" for the ARM Template parameters section. Could you confirm if the secrets you're passing in are passed through a parameter defined as type "securestring"? This will let ARM know not to show in the logs.

**Comment by nbowes24** [comment] 2020-02-28 08:49
@issacnitin I have tried with securestring and secureobject. Here's the ARM template for reference and the DasEncodings parameter that's coming back in the logs.

https://github.com/SkillsFundingAgency/das-recruit/blob/241a54c6d9c50198e527accf34588b7889a738da/azure/template.json#L236

**Comment by bishal-pdMSFT** [comment] 2020-02-28 09:26
@nbowes24 the change in the PR you linked above was to do an explicit validation before doing ARM template deployment. But even without this explicit validation, the deployment itself should fail with same error. Were you not getting deployment error prior to this change?
Also, the actual error containing secret is being thrown by ARM validation logic and hence ideally it should be fixed by the ARM resource provider.
Also if you pass the secret in the task as a secure pipeline variable then the secret should get masked in task logs. Can you please point us to task yaml or screenshot which you are using.

**Comment by issacnitin** [comment] 2020-02-28 09:35
@nbowes24 I see that you're using nested template. In the nested template 'app-service.json', have you marked the parameter "Encodings" which consumes "DasEncodings" as a securestring? If not, could you try that as well and let us know?

**Comment by nbowes24** [comment] 2020-02-28 09:48
@bishal-pdMSFT The deployment still passes successfully, its now just the validation fails which logs the secret out.

Below is the log from the task.

`2020-02-25T13:36:42.9350117Z Starting template validation.
2020-02-25T13:36:42.9351813Z Deployment name is das-recruit-test
2020-02-25T13:36:43.3772229Z There were errors in your deployment. Error code: InvalidTemplate.
2020-02-25T13:36:43.3825260Z ##[error]Deployment template language expression evaluation failed: 'The language expression ' { *secret removed* } ' is not valid: the string character '{' at position '1' is not expected.'. Please see https://aka.ms/arm-template-expressions for usage details.
2020-02-25T13:36:43.3840482Z ##[warning]Validation errors were found in the Azure Resource Manager template. This can potentially cause template deployment to fail. Task failed while creating or updating the template deployment.. Please follow https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-syntax
2020-02-25T13:36:43.3842630Z Starting Deployment.
2020-02-25T13:36:43.3843039Z Deployment name is das-recruit-test
2020-02-25T13:39:32.6310705Z Successfully deployed the template.`

So this logging was introduced on the 4th Feb 2020 when the template validation logic was added.

@issacnitin Good point! The nested template passes it all into:
    "appServiceAppSettings": {
      "type": "array",
      "defaultValue": []
    },
Is this the reason it is tracing out? as its a now become a value in this array it will no longer be a secure string?

**Comment by issacnitin** [comment] 2020-02-28 10:27
@nbowes24 As far as ARM is considered, the value you're passing is a normal array and not a secure one. You can use secureObject instead of array :)
Reference: https://github.com/Azure/azure-quickstart-templates/tree/master/201-key-vault-secret-create

Let us know if this works out.

**Comment by anuragc617** [comment] 2020-03-04 12:37
@nbowes24 have you tried the secureObject solution?

**Comment by nbowes24** [comment] 2020-03-04 13:23
@anuragc617 Our building blocks ARM Template it is passed too needs to stay as an array. I'm still trying to come up with a solution to pass this through so that it doesn't fail validation.

**Comment by anuragc617** [comment] 2020-03-06 10:12
@nbowes24 you can try wrapping the array in the object and then pass it as secureObject. It should work.

**Comment by anuragc617** [comment] 2020-03-11 05:51
Closing this issue as this is not a bug in task. @nbowes24 if you want array should be treated as secret then pass it as secureObject.

**Closed by anuragc617** 2020-03-11 05:51 UTC
Labels: Area: Release, bug
