### ISSUE TITLE
Download universal package - error because node.exe cannot be found

### ISSUE THREAD

**Issue by makuhn** [microsoft/azure-pipelines-tasks#15013] opened 2021-07-01 13:13 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**:  Download or publish Universal Package

## Environment
- Azure Pipelines
- Self Hosted Agent, version 2.188.0
 

## Issue Description

Task **Download universal package** raises the error _This step requires a node version that does not exist in the agent filesystem. Path: C:\agent\externals\node\bin\node.exe_. Checking the path I recognized that this path does not exist but path _C:\agent\externals\node10_. If I rename folder _node10_ to _node_ then other tasks fail. It seems that node folder was not changed for this task.

### Task logs

```
2021-07-01T12:52:07.2311761Z ##[debug]Evaluating condition for step: 'Download Artifacts'
2021-07-01T12:52:07.2314153Z ##[debug]Evaluating: SucceededNode()
2021-07-01T12:52:07.2314598Z ##[debug]Evaluating SucceededNode:
2021-07-01T12:52:07.2315764Z ##[debug]=> True
2021-07-01T12:52:07.2316255Z ##[debug]Result: True
2021-07-01T12:52:07.2316857Z ##[section]Starting: Download Artifacts
2021-07-01T12:52:07.2431774Z ==============================================================================
2021-07-01T12:52:07.2432200Z Task         : Universal packages
2021-07-01T12:52:07.2432388Z Description  : Download or publish Universal Packages
2021-07-01T12:52:07.2432556Z Version      : 0.182.0
2021-07-01T12:52:07.2432723Z Author       : Microsoft Corporation
2021-07-01T12:52:07.2432978Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks
2021-07-01T12:52:07.2433235Z ==============================================================================
2021-07-01T12:52:07.2505008Z ##[debug]Using node path: C:\agent\externals\node\bin\node.exe
2021-07-01T12:52:07.2627810Z ##[error]This step requires a node version that does not exist in the agent filesystem. Path: C:\agent\externals\node\bin\node.exe
2021-07-01T12:52:07.2639643Z ##[debug]System.IO.FileNotFoundException: This step requires a node version that does not exist in the agent filesystem. Path: C:\agent\externals\node\bin\node.exe
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2021-07-01T12:52:07.2641953Z ##[section]Finishing: Download Artifacts
```

**Comment by alexander-smolyakov** [comment] 2021-07-01 14:29
Hi @makuhn, It looks like you downloaded the pipeline agent build that doesn't include Node 6. 

Could you please try to download the version of the pipeline agent with included Node 6, configure it and re-run the pipeline?

**Links to the builds**: [Windows x64](https://vstsagentpackage.azureedge.net/agent/2.188.3/vsts-agent-win-x64-2.188.3.zip), [Windows x86](https://vstsagentpackage.azureedge.net/agent/2.188.3/vsts-agent-win-x86-2.188.3.zip)

**Comment by makuhn** [comment] 2021-07-02 13:22
I tried to update the agent from agent pool site to version 2.188.3. This does not work. Actual version is 2.188.0 (see screenshot below).
![image](https://user-images.githubusercontent.com/38248390/124280521-12d55b00-db49-11eb-97dc-6bef1b11757c.png)

**Comment by alexander-smolyakov** [comment] 2021-07-05 12:04
@makuhn, updating the agent from the agent pool page will not fix the problem with missing Node 6 because you are using a pipeline agent's build that doesn't contain Node 6.

To be able to run pipeline tasks via Node 6 handler you need to download a pipeline agent build **that contains** Node 6 and configure the new agent.

You could download the agent [directly from Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#download-and-configure-the-agent) or as an alternative, you could download the latest release from the [azure-pipeline-agent](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.188.3) repo (_from **Agent Downloads** section_).

**Comment by makuhn** [comment] 2021-07-05 15:39
How can I recognize whether a specific agent build contains node 6 or not? I downloaded the agent that is installed in the past directly from Azure DevOps. That's why I expect that updating the agent would update to a new version containing node 6.

What if I get a version downloaded with a minor version higher than 188? Does this version then contain node 6 or not? Or does it depend on the build version of this agent (3 = node 6 included)?

**Comment by alexander-smolyakov** [comment] 2021-07-06 09:07
@makuhn 

> How can I recognize whether a specific agent build contains node 6 or not? 

You can recognize it from the agent's archive name. For the builds with `Node 6`, we use the `vsts` prefix (e.g. `vsts-agent-win-x64-2.188.3.zip`) and for the builds, with only `Node 10` we use the `pipelines` prefix (e.g. `pipelines-agent-win-x64-2.188.3.zip`).  You may also check the `externals` folder in the agent archive. In the build with `Node 6`, you can see the folders `Node` and `Node10`, and in the build, with only `Node 10` you can see only the `Node10` folder.

> What if I get a version downloaded with a minor version higher than 188? Does this version then contain node 6 or not? Or does it depend on the build version of this agent (3 = node 6 included)?

As you can see from the [agent release page](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.188.3) all builds use the same version the only difference is the build packaging.

![image](https://user-images.githubusercontent.com/14060121/124567592-d35e8580-de4c-11eb-8701-aa0cfcfb7957.png)
![image](https://user-images.githubusercontent.com/14060121/124567482-b75ae400-de4c-11eb-81ab-ba905d009585.png)

**Comment by makuhn** [comment] 2021-07-06 10:14
Thanks. This clarifies.

**Comment by alexander-smolyakov** [comment] 2021-07-08 13:29
@makuhn, Сould you please let us know if switching to agent build with included Node 6 helped resolve the problem?

**Comment by makuhn** [comment] 2021-07-09 07:36
I already resolved the problem by copying folder `node` to folder `node10`. I now updated agent to version 2.188.3.0.

**Comment by alexander-smolyakov** [comment] 2021-07-09 15:37
@makuhn got it, let me close this issue since the problem is resolved.

**Closed by alexander-smolyakov** 2021-07-09 15:37 UTC
Labels: Area: ABTT, bug
