### ISSUE TITLE
Issue building with VS 2015

### ISSUE THREAD

**Issue by dorlandode** [microsoft/azure-pipelines-tasks#15305] opened 2021-09-20 23:29 UTC
VsBuildV1 started failing today when targeting Visual Studio 2015.  We are getting this warning in the logs:

##[warning]Please enter one of the versions 15.0, 16.0, 17.0
##[warning]Visual Studio version '14.0' not found. Falling back to version '16.0'.

Visual Studio 2015 is installed on our build agent.  This started happening on September 17, 2021.

This powershell was modified recently and appears to have remove any version below 15 from the tests:

azure-pipelines-tasks/Tasks/VSBuildV1/Tests/Get-VSPath-Use-VsWhere.ps1

**Comment by EzzhevNikita** [comment] 2021-09-21 07:21
@dorlandode This is a known issue, it should be fixed by VSBuildV1 with version 1.192.3. Deployment of this task version should be completed today.
As a temporary workaround, you can pin the previous task version in your YAML file like this:
`- task: VSBuild@1.187.0`

**Comment by EzzhevNikita** [comment] 2021-09-22 05:33
@dorlandode Deployment of VSBuildV1 of version 1.192.3 completed. Could you please recheck and confirm if everything is working for you now?

**Comment by EzzhevNikita** [comment] 2021-09-29 07:00
@dorlandode Let me close this item since the fixed task version has been deployed. Please let me know if the issue is still actual for you.

**Closed by EzzhevNikita** 2021-09-29 07:00 UTC
Labels: bug, Area: ABTT
