### ISSUE TITLE
AzureMySqlDeployment task update broke Windows agent deployments

### ISSUE THREAD

**Issue by mattboothman** [microsoft/azure-pipelines-tasks#14352] opened 2021-02-07 09:12 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureMysqlDeployment

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment

Azure Pipelines

Hosted, WIndows Server 2019, agent version 2.181.1

MySQL Client v8
    
## Issue Description

A recent update to the AzureMysqlDeployment task was recently deployed to UK South. Our MySQL deployments broke emitting error `ERROR at line 1: Unknown command '\a'.`

Here's the PR that broke the task: https://github.com/microsoft/azure-pipelines-tasks/pull/14183

There's a link to a thorough description of the problem: https://github.com/microsoft/azure-pipelines-tasks/pull/14183#issuecomment-774638144

Comment if you would like me to copy/paste the description from the PR to this issue.

**Comment by mattboothman** [comment] 2021-02-07 09:14
I'm not sure why Task: SqlDacpacDeployment is tagged. I've not looked at it, not reporting an issue with that task.

**Comment by 20shivangi** [comment] 2021-02-08 10:59
@mattboothman You are confirmed that this [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/14183) broke yout task?
cc: @AmrutaKawade

**Comment by mattboothman** [comment] 2021-02-08 11:01
@20shivangi yes

**Comment by 20shivangi** [comment] 2021-02-08 11:11
Will check with Amruta and update the same. Thanks @mattboothman for confirming

**Comment by mattboothman** [comment] 2021-02-08 11:15
Thanks @20shivangi. Please don't just roll back, it'll break the other guys pipeline.

**Comment by mattboothman** [comment] 2021-02-08 11:27
Can it be sorted so we can work around the issue, too. The task doesn't really need to check if the file exists, mysql can do and emit its own error:

```
##[error]Error: No package found with specified pattern C:\agent\_work\12\s\DatabaseScripts\ApplicationDbContext.sql
```

Similarly, when I do find the right relative path:

```
-e "source C:\agent\_work\12\DatabaseScripts\ApplicationDbContext.sql;"
```

Back to square 1!

Can the task jsut not check the path, let MySQL figure out if the file exists, or not, and also not mess with the parameters passed into the task?

Here's what I'm passing into it now:

```
SqlFile: '../DatabaseScripts/ApplicationDbContext.sql'
```

The task then mangles the path to what it _thinks_ the path should be,

**Comment by mattboothman** [comment] 2021-02-08 11:38
Even using `SqlInline`, the task interferes with:

```
sqlInline: 'source ../DatabaseScripts/ApplicationDbContext.sql;'
```

It mangles to:

```
-e "source C:\agent\_work\12\s;"
```

**Comment by 20shivangi** [comment] 2021-02-08 11:47
We will check on this for sure and get back to you.
Also, if you have any code changes in mind, you can surely raise PR against master and we will be happy to review that one :)

**Comment by mattboothman** [comment] 2021-02-08 11:52
@20shivangi thank you.

Unfortunately, i've no idea what I'm doing with TS. If I went poking around, I'm sure I'd break it even more than it is now.

Forgive me for being frank, guys, but this task is a bit pickled. I think what is needed is a V2, get someone who understands MySQL client, and Typescript to do it from scratch. Don't mutate parameters being send it, don't do any checking to see if files exist, just let mysql emit its own errors if we get stuff wrong.

**Comment by mattboothman** [comment] 2021-02-08 12:53
Ok, I have my workround working. There are more issues to look at with this task and its documentation:

The workaround is this:

```
taskNameSelector: 'InlineSqlTask'
sqlInline: 'source ../DatabaseScripts/ApplicationDbContext.sql;'
```

The workaround involves _not_ following the documentation for `taskNameSelector`:

![image](https://user-images.githubusercontent.com/2004173/107221412-85fbfa80-6a0b-11eb-990e-92710f9bad13.png)

...by passing what it says is the option for inline scripts for the `taskNameSelector` (`inlineSqlTask`) parameter because the ts does a case-sensitive comparison:

```
sql/MysqlClient.ts:        if( this._azureMysqlTaskParameter.getTaskNameSelector() === 'InlineSqlTask' ) {
```

The documentation for the `taskNameSelector` further down the page is also no help:

![image](https://user-images.githubusercontent.com/2004173/107221813-0ae71400-6a0c-11eb-9cfa-2e86bd7aac04.png)

But essentially the workaround succeeds in adding the correct, unmodified `-e` parameter value (albeit a strangely formatted one):

```
"-esource ../DatabaseScripts/ApplicationDbContext.sql;"
```

MySQL client successfully finds the script and executes it.

**Comment by 20shivangi** [comment] 2021-02-09 06:28
@mattboothman Is the workaround working for you ? If that is the case, can we close the issue ? :D

**Comment by mattboothman** [comment] 2021-02-09 06:33
@20shivangi I suppose that depends. Are you guys, and Microsoft, happy with this task being broken and the documentation being wrong/incomplete

I'm happy to submit a PR to fix the documentation if you could let me know where/how to do that.

Otherwise, IMO, this ought to be fixed. It's ruined for Windows agents at the moment. Although we can happily work around the break, all that'll happen is someone else'll raise another issue.

**Comment by mattboothman** [comment] 2021-02-09 08:44
@20shivangi I'm not sure if this comment on the docs PR helps to clarify the problem: https://github.com/MicrosoftDocs/azure-devops-docs/pull/10160#issuecomment-775768980

**Comment by 20shivangi** [comment] 2021-02-10 07:34
@N-Usha Can you have a look at the documentation PR : https://github.com/MicrosoftDocs/azure-devops-docs/pull/10160/files

**Comment by 20shivangi** [comment] 2021-02-16 05:58
Closing the issue since PR for [bug fix](https://github.com/microsoft/azure-pipelines-tasks/pull/14372) and for [documentation](https://github.com/MicrosoftDocs/azure-devops-docs/pull/10160/files) have been merged. Deployment usually takes 3-4 weeks for rollout.

**Closed by 20shivangi** 2021-02-16 05:58 UTC
Labels: Area: Release, Task: MysqlDeployment, environment:documentation
