### ISSUE TITLE
AzureResourceManagerTemplateDeployment@3 runtime variable in input section

### ISSUE THREAD

**Issue by lecamarade** [microsoft/azure-pipelines-tasks#12412] opened 2020-02-25 04:02 UTC
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AzureResourceManagerTemplateDeployment@3

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Issue Description

It is not possible to use runtime variables as the input parameter for the task.
Scenario: I want to create a template that deploys into multiple environments (dev, test, prod, etc).
Instead of hardcoding those values I want to create a step in a template that sets the variable values based on environment name, and then pass those variables to the task.

I want to pass the subscription and the ConnectedServiceName as a parameter:
- task: AzureResourceManagerTemplateDeployment@3
      inputs:
        azureResourceManagerConnection: '$[ variables.azureConnection ]'
        subscriptionId: '$[ variables.subscriptionId ]'

This fails with the error:

There was a resource authorization issue: "The pipeline is not valid. Job Deploy: Step AzureResourceManagerTemplateDeployment input ConnectedServiceName references service connection $[ variables.azureConnection ] which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

Is there any way around this?

**Comment by JodyPetroni** [comment] 2020-03-02 00:24
did you solve this? - facing exact same issue

**Comment by JodyPetroni** [comment] 2020-03-02 00:34
actually found workaround this will work ${{ variables.azureConnection }}

**Comment by lecamarade** [comment] 2020-03-02 19:51
Nope, looks like it's by design...

In my case instead of compose custom variables (subscriptions, resource name, etc) based on the environment (staing/prod), I hardcoded all the various values I needed in variables and reference those variables as a template.

**Comment by graphicsxp** [comment] 2020-07-11 22:36
I'm trying to get subscriptionId from Azure Keyvault secret and I'm facing the same issue. At runtime I usually manage to download  keyvault secrets into variables but here the pipeline won't even start :  


`There was a resource authorization issue: "The pipeline is not valid. Job deploymentjob: Step input azureSubscription references service connection PROJ ( ) which could not be found. The service connection does not exist or has not been authorized for use.`

**Comment by WaitingForGuacamole** [comment] 2020-07-14 20:26
> actually found workaround this will work ${{ variables.azureConnection }}

This may depend on where you declare that variable. It seems that if the variable is declared in a template (job or stage template, or variable template), I don't get access to it with ${{ }} template expressions, rather I have to use macro $( ) syntax.

Did you declare your variable in azure-pipelines.yml, or another template?

**Comment by WaitingForGuacamole** [comment] 2020-07-14 20:29
Also note that I can use variables for the other inputs, it only seems to be the connected service name that doesn't accept this?

**Comment by Kolky** [comment] 2020-12-23 14:21
> actually found workaround this will work ${{ variables.azureConnection }}

Thanks, that solved it for me!

**Comment by Kolky** [comment] 2020-12-23 16:43
Would love to see this resolved. Does not work for me with any kind of variable or parameter. Tried it all :(

**Comment by Kolky** [comment] 2020-12-23 16:56
Same thing happens with; task AzureResourceGroupDeployment btw.

**Comment by andreacapriplexure** [comment] 2021-03-24 01:11
I still run into this issue, has this been looked at

**Comment by tejasd1990** [comment] 2021-03-25 11:08
@lecamarade @andreacapriplexure  ,
as suggested by @JodyPetroni , `${{ variables.azureConnection }}` should work, i had explained this in an [earlier issue](https://github.com/microsoft/azure-pipelines-tasks/issues/11555#issuecomment-542980569).
What error are you getting when using the expression? Can you attach full debug logs for us to investigate?

**Comment by andreacapriplexure** [comment] 2021-03-25 20:09
And here is the error I get when I configure it at the stage level

**Comment by bishal-pdMSFT** [comment] 2021-03-27 18:19
Assigning to @nadesu as the issue is with how yaml pipeline platform handles azure service connection variables.

**Comment by AmrutaKawade** [comment] 2021-04-05 11:55
@lecamarade can you try setting global variables as suggested here https://github.com/microsoft/azure-pipelines-tasks/issues/14365

**Comment by AmrutaKawade** [comment] 2021-04-12 05:09
@andreacapriplexure please check above solution if it works

**Comment by andreacapriplexure** [comment] 2021-04-12 05:18
So while I wouldn't call that a solution, more like an attempt at a workaround for the real issue. Using this would not be feasible for anything less than 5 different subscriptions. I'm not sure there is much point hacking everything to avoid fixing the issue in the first place.
I'll try do that but it is a bug and should not be the solution for this ticket. @AmrutaKawade

**Comment by AmrutaKawade** [comment] 2021-04-12 05:53
There is already issue opened for this, will close this issue and track with https://github.com/microsoft/azure-pipelines-tasks/issues/14365

**Closed by AmrutaKawade** 2021-04-12 05:53 UTC
Labels: Area: Release, environment:under-investigation, question
