### ISSUE TITLE
Cannot log a normal variable

### ISSUE THREAD

**Issue by 928PJY** [microsoft/azure-pipelines-tasks#9664] opened 2019-02-22 06:47 UTC
## Environment
- Server - Azure Pipelines
- Agent - Hosted VS2017

## Issue Description
![image](https://user-images.githubusercontent.com/17958546/53217911-dc43c780-3694-11e9-8077-47f03b3de79b.png)
as you can see, the account has been replaced with `*`, but `account` is just a normal variable, what is your display rules about what kind of variable should be replaced with `*`

**Comment by joshmgross** [comment] 2019-02-22 16:44
@928PJY Do you have your variable set as secret? Any variable marked as secret will be masked out, but other variables will not.

This page might give you some more info: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables

**Comment by 928PJY** [comment] 2019-02-25 01:52
No, it is not a secret variable, it is just a variable I created from code in Nodejs. here is a sample
```
const config = require('config.json');
console.log(config.account);
```

**Comment by 928PJY** [comment] 2019-02-28 02:50
@joshmgross any update?

**Comment by joshmgross** [comment] 2019-02-28 22:50
@928PJY Is the variable the same value as another secret variable? 

Any variable marked as secret will be masked from the logs

**Comment by 928PJY** [comment] 2019-03-01 02:15
Thanks @joshmgross, That's a good point, it has the same value with the variable restored from Azure key vault, which will be automatically set as a secret variable, right? so this is a by-design behavior? is there any workaround for this or I have to remove it from key vault if I want to output the value.

**Comment by moswald** [comment] 2019-03-02 12:55
@928PJY Yeah, it's by design. If a value is found in KeyVault (or is otherwise marked secret), it will get masked from the logs, regardless.

**Closed** 2019-05-20 15:31 UTC
Labels: Area: Build
