### ISSUE TITLE
Error when using task Cache@2 and PublishPipelineArtifact@1 tasks in YAML pipeline on self-hosted agent

### ISSUE THREAD

**Issue by bc443e** [microsoft/azure-pipelines-tasks#13379] opened 2020-07-31 15:38 UTC
**Type**: Question

**Task Name**: Cache@2 and PublishPipelineArtifact@1

## Environment

**Server** - Azure Pipelines
    
*Account name*: repo-scanner-org
*Project name*: 30553-eastus2-eisapi
*Build definition name / build number*: 14 / 133

**Agent** - Private
    
*OS*: Linux
*Agent version*: 2.165.2

## Issue Description

I'm running a cache task that was working fine when using the default Azure hosted agents, but when using on a self-hosted agent, I get an error. My YAML pipeline is below:

```yaml
variables:
    - group: 'all'
    - name: 'npm_cache'
      value: $(Pipeline.Workspace)/.npm
    - name: 'pipeline_triggered_by_pull_request'
      value: $[eq(variables['Build.Reason'], 'PullRequest')]

trigger: none

pool:
    name: 'RepoScannerAgentPool'
    demands:
        - npm

stages:
    - stage: Install
      displayName: Setup cache and install npm packages
      condition: eq(variables['pipeline_triggered_by_pull_request'], true)
      jobs:
          - job: install
            steps:
                - task: Cache@2
                  continueOnError: true
                  inputs:
                      key: 'npm | "$(Agent.OS)" | package-lock.json'
                      restoreKeys: |
                          npm | "$(Agent.OS)"
                          npm
                      path: $(npm_cache)
                - script: npm ci --cache $(npm_cache) --quiet
    - stage: Lint
      displayName: Lint typescript
      condition: and(succeeded(), variables['pipeline_triggered_by_pull_request'])
      jobs:
          - job: lint
            steps:
                - script: npm ci --cache $(npm_cache) --quiet
                - script: npm run lint
    - stage: Build
      displayName: Build and publish dist folder
      condition: and(succeeded(), variables['pipeline_triggered_by_pull_request'])
      jobs:
          - job: build
            steps:
                - script: npm ci --cache $(npm_cache) --quiet
                - script: npm run build
                - publish: $(System.DefaultWorkingDirectory)/dist
                  artifact: dist
    - stage: Test
      displayName: Run unit tests
      condition: and(succeeded(), variables['pipeline_triggered_by_pull_request'])
      jobs:
          - job: test
            steps:
                - script: npm ci --cache $(npm_cache) --quiet
                - script: npm run test
```

### Task logs

```
##[debug]Evaluating condition for step: 'Cache'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Cache
==============================================================================
Task         : Cache
Description  : Cache files between runs
Version      : 2.0.1
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key:
 - npm               [string]
 - "Linux"           [string]
 - package-lock.json [file] --> 8CAEE341009CA72FE6289320FFACAF5BB1AC19CE3B197B66CD1A4974F476ECB3
Resolved to: npm|"Linux"|8scaaX+bQdtHyrEzJpUHNekCJjUCUD1e7c+Ei9IGz/g=
##[debug]Processed: ##vso[task.settaskvariable variable=RESTORE_STEP_RAN;issecret=False;]true
##[debug]Processed: ##vso[task.settaskvariable variable=RESTORE_STEP_RESOLVED_FINGERPRINT;issecret=False;]npm|"Linux"|8scaaX+bQdtHyrEzJpUHNekCJjUCUD1e7c+Ei9IGz/g=
Resolving restore key:
 - npm     [string]
 - "Linux" [string]
Resolved to: npm|"Linux"|**
Resolving restore key:
 - npm [string]
Resolved to: npm|**
##[error]An error occurred while sending the request.
##[debug]Processed: ##vso[task.logissue type=error;]An error occurred while sending the request.
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.CreateDataProviderAsync(String location, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.ResolveLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.ResolveLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.GetLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientInstanceAsync(Type managedType, Guid serviceIdentifier, CancellationToken cancellationToken, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientServiceImplAsync(Type requestedType, Guid serviceIdentifier, Func`4 getInstanceAsync, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientAsync[T](CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.TaskExtensions.SyncResult[T](Task`1 task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClient[T]()
   at Agent.Plugins.PipelineArtifact.DedupManifestArtifactClientFactory.CreateDedupManifestClient(AgentTaskPluginExecutionContext context, VssConnection connection, CancellationToken cancellationToken, BlobStoreClientTelemetry& telemetry)
   at Agent.Plugins.PipelineCache.PipelineCacheServer.DownloadAsync(AgentTaskPluginExecutionContext context, Fingerprint[] fingerprints, String path, String cacheHitVariable, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineCache.RestorePipelineCacheV0.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, Fingerprint fingerprint, Func`1 restoreKeysGenerator, String path, CancellationToken token)
   at Agent.Plugins.PipelineCache.PipelineCacheTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
Finishing: Cache
```

## EDIT (8-3-20)

I'm also getting the same error for my PublishPipelineArtifact@1 task, as shown below:

### Task logs

```
##[debug]Evaluating condition for step: 'PublishPipelineArtifact'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: PublishPipelineArtifact
==============================================================================
Task         : Publish Pipeline Artifacts
Description  : Publish (upload) a file or directory as a named artifact for the current run
Version      : 1.2.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact
==============================================================================
Artifact name input: dist
Uploading pipeline artifact from /home/jd195m/agent2/_work/9/s/dist for build #143
##[error]An error occurred while sending the request.
##[debug]Processed: ##vso[task.logissue type=error;]An error occurred while sending the request.
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.CreateDataProviderAsync(String location, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.ResolveLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.ResolveLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.GetLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientInstanceAsync(Type managedType, Guid serviceIdentifier, CancellationToken cancellationToken, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientServiceImplAsync(Type requestedType, Guid serviceIdentifier, Func`4 getInstanceAsync, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientAsync[T](CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.TaskExtensions.SyncResult[T](Task`1 task)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClient[T]()
   at Agent.Plugins.PipelineArtifact.DedupManifestArtifactClientFactory.CreateDedupManifestClient(AgentTaskPluginExecutionContext context, VssConnection connection, CancellationToken cancellationToken, BlobStoreClientTelemetry& telemetry)
   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.UploadAsync(AgentTaskPluginExecutionContext context, Guid projectId, Int32 pipelineId, String name, String source, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.PublishPipelineArtifactTaskV1.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
Finishing: PublishPipelineArtifact
```

**Comment by samuelkoppes** [comment] 2020-08-24 21:58
Please add more detailed logs and confirm that the issue is still happening.

**Comment by herenhuang** [comment] 2020-08-31 21:37
Closing, pls reopen if needed!

**Closed by herenhuang** 2020-08-31 21:37 UTC
Labels: Area: Artifacts, aa-triaged, question
