### ISSUE TITLE
KubernetesManifest@0 is not deploying baked kustomize files

### ISSUE THREAD

**Issue by Eossu** [microsoft/azure-pipelines-tasks#13173] opened 2020-06-24 12:27 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: KubernetsManifest@0

list here (V# not needed):  
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    Azure Pipelines

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: free tier

## Issue Description

When baking kustomize files as seen here we are getting an error fomr kubectl as seen in Task Logs

```
  - task: KubernetesManifest@0
    displayName: Create K8S manifest files
    name: bake
    inputs:
      action: bake
      renderType: kustomize
      kustomizationPath: ${{parameters.KustomizePath}}

  - task: KubernetesManifest@0
    displayName: Deploy K8s manifests
    inputs:
      action: deploy
      manifests: $(bake.manifestsBundle)
      containers: |
        ###.azurecr.io/${{parameters.DockerImage}}:${{parameters.Tag}}
```

### Task logs

```
Starting: Deploy K8s manifests
==============================================================================
Task         : Deploy to Kubernetes
Description  : Use Kubernetes manifest files to deploy to clusters or even bake the manifest files to be used for deployments using Helm charts
Version      : 0.169.3
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-k8s-manifest-tsg
==============================================================================
==============================================================================
			Kubectl Client Version: v1.18.3
			Kubectl Server Version: v1.15.11
==============================================================================
/usr/bin/kubectl apply -f  --namespace some-namespace
error: must specify one of -f and -k
##[error]error: must specify one of -f and -k
Finishing: Deploy K8s manifests
```

**Comment by shigupt202** [comment] 2020-07-02 12:41
@Eossu Can you run a command line task after the bake step and do `cat $(bake.manifestsBundle)` to validate whether the bake step generated manifests or not?

**Comment by Eossu** [comment] 2020-07-02 12:52
@shigupt202 I did print the environment when i run the job last time and got this variable: 
BAKE_MANIFESTSBUNDLE=/home/vsts/work/_temp/baked-template-26794a75-6b8f-4022-bec9-a0b04a33e6e6.yaml

Do you still want to see the cat? then i can prepare the pipeline again to test.

**Comment by shigupt202** [comment] 2020-07-02 14:01
Yes it would be helpful in identifying the problem, I want to see all the resources present in the `kustomize.yaml`.

**Comment by Eossu** [comment] 2020-07-02 14:26
@shigupt202 I got this result:

Starting: CmdLine
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
cat /home/vsts/work/_temp/baked-template-c8e09340-a557-4120-bedd-bf95890a306c.yaml
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/5fe48b41-d6a8-4adb-a287-71845989945e.sh

Finishing: CmdLine

**Comment by shigupt202** [comment] 2020-07-02 14:38
So, there's no resource specified in the kustomize file? I believe the KubernetesManifest task is working fine. Could you please verify the kustomize file once?

**Comment by Eossu** [comment] 2020-07-02 18:54
So it is working now.

I tested the kustomize logic locally by using the "kustomize cli" and everything worked perfectly, but "kubectl kustomize" as i see now beeing used in devops failed locally. Tough locally i get an error message, but in devops you continue as normal. Are you silencing erros from the baking command?

needed to do some adjustments in the overlay kustomize files and now it works.

**Comment by shigupt202** [comment] 2020-07-03 03:45
Yes, all the bake commands are run silently by the task (as it prints out the baked manifests). Now that the issue is resolved, can we close it?

**Comment by ds-ms** [comment] 2020-07-03 04:13
@shigupt202 do we print out the logs of the run in debug mode?

**Comment by shigupt202** [comment] 2020-07-03 04:44
No, we don't print the logs in debug mode either.

**Closed** 2020-07-07 17:06 UTC
Labels: Area: Release, bug
