### ISSUE TITLE
Azure SQL Database Deployment - Issue - Task failure

### ISSUE THREAD

**Issue by bonettebueno** [microsoft/azure-pipelines-tasks#10479] opened 2019-05-24 16:35 UTC
Hi,

I'm trying to execute a simple SQL file and always the task is throwing the following error:

`
Invalid deployment action: Script. For SQL query operations, deployment actions should be set to value `Publish`.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
`

However, as you can see on the attachment, on there's no option available to set as action as 'Publish'.

![sql_devops_issue](https://user-images.githubusercontent.com/4702006/58343057-03ec2c80-7e4a-11e9-900f-72778e7550d9.PNG)

Also I've tried to execute command, but the agent fails and throw the same error.

On my case, is not option to execute as dacpac extension.

**Comment by Ajay-MS** [comment] 2019-05-27 04:26
It is expected behavior and we have consciously added this error message in order to handle back-ward compatibility. 

1.	Earlier in-order,  action I/P used to come before Deploy Type I/P.  (Let’s say it at Time A)
2.	Now deploy type I/P action comes before action input.  ( Let’s say It at Time B )

**Example :** 

**At Time A**
1.	User added a task for deployed of a SQL script. So, inputs will be
a.	Action : Publish
b.	Deploy Type: Inline SQL Script
2.	Now Customer want task to perform export action. Now inputs will be 
a.	Action: Export
b.	Deploy Type: Inline SQL Script ( This input will be hidden. Because it was visible under publish action ) 

**At Time B** 
1.	In the task, automatically input got switched as 
a.	Deploy Type: Input SQL Script
b.	Action: Export
2.	Task that user supposed to execute export action started executing SQL scripts. ( Wrong behavior ) 

In order to prevent above issue, we added error check as we assume failure with right error message is better than wrong deployment. 

In order to fix your above issue
- Select deploy type to `Dacpac`
- Now select action as `publish`
- Now change deploy type to `SQL script file`.

As this will solve your issue, so closing this issue. If you have further any question or doubts feel free to reopen the issue.

**Closed by Ajay-MS** 2019-05-27 04:26 UTC
Labels: Area: Release

**Comment by bonettebueno** [comment] 2019-05-29 16:45
Hi Ajay,

I've applied the changes as you mentioned, like deploy as DACPAC within Publish option and save it. Later, I've changed the to SQL Script file.

So ... the workardound is working!

Thanks,

Marcio Bueno

**Comment by eavonius** [comment] 2020-08-27 18:57
I ran into this today and it's incredibly frustrating. This shouldn't be closed, but should be fixed!!

**Comment by kmkumaran** [comment] 2020-08-28 04:52
@nadesu / @chshrikh  - Can you review the feedback and take this further.

**Comment by rzeq** [comment] 2021-03-09 08:33
This functionality is confusing and looks more like bug than feature.

**Comment by sanoraya** [comment] 2021-11-27 00:25
Is this ever going to be fixed? The proposed "workaround" quite frankly left me speechless. Why don you place the explanation and proposed "workaround" into the official documentation, so that all dev community can have a good laugh? 
Right in here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment?view=azure-devops

**Comment by AlexandreCZK** [comment] 2022-06-03 21:24
Can you fix this, it's frustrating ?

**Comment by miveydev4** [comment] 2022-06-06 15:35
Ditto, that ^^^ 
This is absolutely ridiculous that this issue has been dropped by the wayside since first reported here back in 2019. 3 years later and this convoluted suggestion for a workaround is totally laughable.

Come on guys!!

**Comment by DominicHarvey01** [comment] 2022-06-24 01:02
Come on guys!! I wasted half a day on this before finding this post.  It's frustrating.  3 years and your PO didn't prioritize the bug yet, you need to talk asap.

**Comment by sechabamot** [comment] 2022-07-26 16:29
If you are reading this I was as frustrated as you probably are right now. If you have done everything else right, simply removing the task and adding a new one with the same information should have you up and going again. 

The proposed workaround did not work for me at all.

**Comment by evandcombs** [comment] 2023-05-02 22:41
Ran into this issue today.... The workaround seems to have worked, but as others have said this is a stupid workaround, and seems like it would be pretty easy to fix.

**Comment by sgabler** [comment] 2023-07-27 08:52
I just also lost quite a bit of time due to this bug, so I opened another issue for this bug: https://github.com/microsoft/azure-pipelines-tasks/issues/18711
