### ISSUE TITLE
FTP upload task fails with 553 Prohibited file name: .ftpquota

### ISSUE THREAD

**Issue by Daisyyj** [microsoft/azure-pipelines-tasks#11250] opened 2019-08-30 09:44 UTC
When using the FtpUpload task with the parameter "clean" set to "true" the tasks first issues a warning and then fails after the third attempt.
- task: FtpUpload@2
      displayName: FTP upload
      inputs:
        serverEndpoint: $(ServerEndpoint)
        rootDirectory: Source/$(RootDirectory)
        remoteDirectory: /
        clean: true
        preservePaths: true

Error messages : 
connected: 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 2 of 50 allowed.
220-Local time is now 12:24. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
removing remote directory: /
##[warning]FTPError: 553 Prohibited file name: .ftpquota

##[error]FTPError: 553 Prohibited file name: .ftpquota

host: example.org
path: /
files uploaded: 0
directories processed: 0
unprocessed files & directories: 11
##[error]Ftp Upload failed
disconnecting from: example.org
Finishing: FTP upload

If a file cannot be removed during cleaning, the warning should remain, but not fail the task as the behavior is expected.

**Comment by paulpce** [comment] 2019-09-19 22:53
+1 I've also just hit this problem

**Comment by damccorm** [comment] 2020-02-25 19:59
> If a file cannot be removed during cleaning, the warning should remain, but not fail the task as the behavior is expected.

I don't think I agree with this, I think this is actually the correct behavior. If you can't clean successfully, it might lead to other more insidious issues, and I think failing the build is the safest thing to do here.

**Comment by damccorm** [comment] 2020-03-06 20:01
Closing since this is acting as designed

**Closed by damccorm** 2020-03-06 20:01 UTC
Labels: Area: Core, enhancement
