### ISSUE TITLE
NuGetCommand@2 2.164.0 Restores fails when using nugetConfigPath:

### ISSUE THREAD

**Issue by zeppelin4x** [microsoft/azure-pipelines-tasks#12309] opened 2020-02-06 16:43 UTC
*Type*: Bug

NuGetCommand@2 Restore 
Environment
- Server - Azure Pipelines 
- Account name: Deloitte-Fintech
- build number: 20494
- https://dev.azure.com/Deloitte-FinTech/Solvas/_build/results?buildId=20494&view=results
- Agent Private:    
- agent queue name: Cooperative-High
- Agent version: 2.164.7
- Agent OS: Windows 2016
  
## Issue Description
Nuget fails to restore packages since update 2.164.0 when specifying .config path. Restores work by removing feedsToUse: config as a temporary work around.

Error:
##[error]The nuget command failed with exit code(1) and error(NuGet.Config is not valid XML. Path: 'J:\Agent\Solvas-Cooperative-High\_work\1\Nuget\tempNuGet_20537.config'.
  Reference to undeclared entity 'Zc'. Line 67, position 53.) **Line 67 and Zc does not exist in the file, not sure where it is coming from**

YAML:
- task: NuGetCommand@2
  displayName: NuGet restore
  inputs:
    restoreSolution: 'Codebase/$(Solvas.SolutionName).sln'
    feedsToUse: config
    nugetConfigPath: 'Codebase/.nuget/nuget.config'
    externalFeedCredentials: 'Solvas-FTBin-NuGet'
    restoreDirectory: packages
    verbosityRestore: Normal

### Error logs
[Error.log](https://github.com/microsoft/azure-pipelines-tasks/files/4166389/Error.log)
[Full.logs.txt](https://github.com/microsoft/azure-pipelines-tasks/files/4166402/Full.logs.txt)

**Comment by scottfavre** [comment] 2020-02-10 20:29
I'm also seeing this. Pipeline worked last week, today I get:

```
##[error]The nuget command failed with exit code(1) and error(NuGet.Configuration.NuGetConfigurationException: NuGet.Config is not valid XML. Path: 'c:\agent\_work\19\Nuget\tempNuGet_158989.config'. ---> System.Xml.XmlException: An error occurred while parsing EntityName. Line 13, position 48.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.Configuration.XmlUtility.GetDocument(String fullPath)
   at NuGet.Configuration.XmlUtility.GetOrCreateDocument(XDocument content, String fullPath)
   at NuGet.Configuration.Settings.<>c__DisplayClass20_0.<.ctor>b__0()
   at NuGet.Configuration.Settings.<>c__DisplayClass66_0.<ExecuteSynchronized>b__0()
   --- End of inner exception stack trace ---
   at NuGet.Configuration.Settings.<>c__DisplayClass66_0.<ExecuteSynchronized>b__0()
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLocked(String filePath, Action action)
   at NuGet.Configuration.Settings..ctor(String root, String fileName, Boolean isMachineWideSettings)
   at NuGet.Configuration.Settings.ReadSettings(String root, String settingsPath, Boolean isMachineWideSettings)
   at NuGet.Configuration.Settings.LoadUserSpecificSettings(List`1 validSettingFiles, String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean useTestingGlobalPath)
   at NuGet.Configuration.Settings.LoadDefaultSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean loadAppDataSettings, Boolean useTestingGlobalPath)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args))
```

The credentials for the private nuget repo have not changed.

**Comment by scottfavre** [comment] 2020-02-11 16:01
I suspect the issue is with handling xml-escaped characters such as `&`, `<` or `>` (which our credentials contain).

This code just does a string replace without escaping the actual password for XML.

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/Common/packaging-common/nuget/NuGetExeXmlHelper.ts#L60

**Comment by zeppelin4x** [comment] 2020-02-11 16:11
I switched to a command line task. Not waiting for Microsoft to fix the task. Created a read only account to the private feed and set the credentials during the CI build.

**Comment by scottfavre** [comment] 2020-02-11 16:51
We got things working by putting an XML-escaped version of the password in the credentials for the service connection to our private nuget feed.

**Comment by herenhuang** [comment] 2020-08-10 21:22
Hey all, thanks for all the comments and ideas. We suggest using the [NugetAuthenticate ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget-authenticate?view=azure-devops)task and scripting whatever other functionality you need moving forward. Closing this issue for now, let us know if you have any further issues!

**Closed by herenhuang** 2020-08-10 21:22 UTC
Labels: Area: Artifacts, bug
