### ISSUE TITLE
Secret variables sometimes leaking in logs.

### ISSUE THREAD

**Issue by alennartz** [microsoft/azure-pipelines-tasks#9633] opened 2019-02-19 16:15 UTC
## Environment
Hosted agents on Azure pipelines. Tested with:
- Hosted Ubuntu 1604
- Hosted VS2017

## Issue Description
Variables marked as secrets are not always obfuscated in log output. Based on my experimentation it has to do with the presence of a quotation mark character (") inside of the secret text. I am using a release pipeline with the following Task.

### Task details
**Name:** _Deploy To Kubernetes_ 
**Version(s):** 0.\*, 1.\*
#### Configuration:
Leave as much of it blank as you can (based on version) and just use the Secrets section as follows:
**type of secret:** generic
**Arguments:** --from-literal="key=$(secretVar)"
**Secret name:** test-secret
**Force update secret:** yes

Where $(secretVar) is a pipeline scoped variable marked as a secret. Depending on the contents of the variable and the type of agent the secret is sometimes obfuscated with \*\*\* or sometimes in plaintext. below is a summary of my findings.

**Secret** | **Hosted Ubuntu 1604** | **Hosted VS2017**
-- | -- | --
plain-old-secret | Obfuscated | Obfuscated
secret string with spaces | Obfuscated | Obfuscated
secret-with-"quotes"-and-stuff | Plain Text | Plain Text
secret-with-escaped-\\"quotes\\"-and-stuff | Plain Text | Obfuscated
{\\"secret as\\":   \\"json\\", \\"with multiple\\": \\"fields\\"} | Plain Text | Obfuscated

### Task logs
Attached are debug logs of the json formatted secret from an Ubuntu hosted agent
[Ubuntu-jsonsecret-debug-logs.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2880839/Ubuntu-jsonsecret-debug-logs.zip)
Feel free to ignore the fact that there is an error result, I am using v0 of the task and did not configure a cluster to connect to.

**Comment by ericsciple** [comment] 2019-02-20 19:47
It looks like the quotes are getting eaten.

Here is what I did to reproduce the issue:
1. Add a secret variable `mysecret` with the value `my"secret"value`
2. Create a pipeline:

```yaml
pool: Hosted VS2017
steps:
- task: Kubernetes@0
  displayName: 'kubectl '
  inputs:
    secretType: generic
    secretArguments: '--from-literal=key1="$(mysecret)"'
    secretName: mysecret
    versionSpec: 1.13.2
```

In the log I see:

```
[debug]exec tool: D:\a\_temp\kubectlTask\1550690717716\kubectl.exe
[debug]Arguments:
[debug]   --kubeconfig
[debug]   D:\a\_temp\kubectlTask\1550690717716\config
[debug]   create
[debug]   secret
[debug]   generic
[debug]   mysecret
[debug]   --from-literal=key1=mysecretvalue
```

It looks like the quotes are getting eaten by the [line](https://github.com/Microsoft/azure-pipelines-tasks/blob/48d29c1eb90750cae317f46a6e3bab2488ee4f04/Tasks/KubernetesV0/src/kubernetessecret.ts#L88) function.

I don't see an easy fix here. The behavior of the `line` function is to eat double quotes, unless they are escaped. Due to the nature of the [secretArguments](https://github.com/Microsoft/azure-pipelines-tasks/blob/48d29c1eb90750cae317f46a6e3bab2488ee4f04/Tasks/KubernetesV0/task.json#L134) input, I don't see an easy way to distinguish the unescaped quotes that came from macro replacement, from the quotes intended for arg-boundary markers only.

This is one of the challenges with passing secrets on the command line, and getting command line escaping correct.

Does kubectl allow secrets to be passed via env vars? That is a better security practice anyway, and avoids this class of issue altogether. If we could push customers in that direction, it would be good.

Assigning the issue to @bansalaseem for now. It's unclear to me what the best approach forward is, but I have provided my assessment. Let me know what you think.

**Comment by ds-ms** [comment] 2019-02-25 06:16
I have tested out parsing secrets via variables on my powershell window, it seemed to be working fine. 
```powershell
kubectl create secret generic newsecret --from-literal key="$secretInEnv"
```
So, I thought it should work out the same way from the task if I exposed the `showEnvironmentVariables` and used them in the task. I managed to keep the quotes by having a pipeline like this: 
```yaml
steps:
- task: Kubernetes@1
  displayName: 'kubectl '
  inputs:
    secretType: generic
    secretArguments: '"--from-literal=key=\"$secretInEnv\""'
    secretName: newsecret
  env:
    secretInEnv: $(secretInVariables)
```

In my logs I noticed that the command which was being executed was exactly how I expected it to be 
```
[command]/opt/hostedtoolcache/kubectl/1.13.2/x64/kubectl create secret generic newsecret --from-literal=key="$secretInEnv"
```
where I expected `$secretInEnv` to be replaced with the value in $(secretInVariables) (I noticed that the `processs.env` had the desired value), but the value of that end up being `"$secretInEnv"` instead of the actual value. 

Is the `child.spawn` expected to parse these, or `kubectl` tool have explicit parsing capabilities of these environment variables?

**Comment by alennartz** [comment] 2019-02-25 14:37
I can see why un-escaped quotes would be problematic, and since you need to escape them anyway if you actually want them in your secret I feel that this case is not that much of an issue. The scenario that actually caused me the problem initially was that even escaped quotes cause the secret to leak when the build agent is an Ubuntu machine.

for example using the following task
```steps:
- task: Kubernetes@0
  displayName: 'Create Secret'
  inputs:
    secretType: generic
    secretArguments: '--from-literal="key=$(secretVar)"'
    secretName: 'test-secret'
```

where $(secretVar) is: `with-\"escaped\"-quotes`

I get this in the logs on Hosted Ubuntu 1604:

`2019-02-25T14:30:52.9431559Z [command]/usr/bin/kubectl --kubeconfig /home/vsts/work/_temp/kubectlTask/1551105046635/config create secret generic test-secret --from-literal=key=with-"escaped"-quotes`

and this on Hosted VS2017:
`2019-02-25T14:35:04.0127476Z [command]D:\a\_temp\kubectlTask\1551105299012\kubectl.exe --kubeconfig D:\a\_temp\kubectlTask\1551105299012\config create secret generic test-secret "--from-literal=key=***"`

**Comment by ajinkya599** [comment] 2019-03-20 13:54
Hi @ericsciple, I explored the Kubernetes docs and did not find a way to use environment variables for creation of secrets using --from-literal.

As @alennartz mentioned, the scenario with double quotes that is actually important is when the double quotation is escaped.
i.e., in the repro that you suggested, if the value of `mysecret` is `my\"secret\"value`.

In this case the behavior of task logging is different for Windows and non-Windows platforms.

In case of Windows, the command printed in the logs contains the escape character `\` as is provided in the variable:
`[command]D:\AGENTS\agent1\_work\_temp\kubectlTask\1553019364872\kubectl.exe --kubeconfig D:\AGENTS\agent1\_work\_temp\kubectlTask\1553019364872\config create secret generic mysecret --from-literal=key=my\"secret\"val`

Hence, it is getting masked correctly (when marked as secret):
`[command]D:\AGENTS\agent1\_work\_temp\kubectlTask\1553019364872\kubectl.exe --kubeconfig D:\AGENTS\agent1\_work\_temp\kubectlTask\1553019364872\config create secret generic mysecret --from-literal=key=***`


But in case of non-Windows, the command that is logged does not have `\` character. Hence, it is not getting masked:
`[command]/home/aj/agents/agent4/_work/_temp/kubectlTask/1553019332168/kubectl --kubeconfig /home/aj/agents/agent4/_work/_temp/kubectlTask/1553019332168/config create secret generic mysecret --from-literal=key=my"secret"val`

While the actual execution contains `\"` in both the cases. I verified that the Kubernetes secret that is created contains `my"secret"value` as is intended for both the platforms.

I see that there is  a special case handling for `"` and `\` characters in case of windows in the [_getCommandString ](https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/node/toolrunner.ts#L163)method.

I have raised a [draft pull request](https://github.com/Microsoft/azure-pipelines-task-lib/pull/511) to handle the `"` character for OSX/Linux.
@ericsciple - Your thoughts on taking this fix ?

**Comment by bansalaseem** [comment] 2019-03-26 12:58
@ericsciple, I am assuming that you will take this up and no more action is required from @ajinkya599 on it.

**Comment by ajinkya599** [comment] 2019-12-24 14:13
It is a limitation of the Kubernetes task - _"Escaped quotes in a secret variable passed as argument to kubectl do not get masked, when the task is run on OSX/Linux agents"_.

The reason this is happening is because of the behavior of a azure-pipelines-task-lib [code](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/toolrunner.ts#L146) that is being used for tool execution. The fix in that code is not straight-forward, and may take some time (needs to be carefully done to ensure that multiple use cases are covered, and existing use cases are not broken).

As a **work-around**, one can create a Kubernetes secret as following:
- Add a Kubernetes login step using the Kubernetes (kubectl) task.
- Add an inline Powershell script step to invoke kubectl with the required parameters -
`kubectl create secret generic mysecret --from-literal=key=$env:mySecretEnvVar`
Here, `mySecretVar` is passed as `mySecretEnvVar` environment variable to the Powershell step.
- Add a Kubernetes logout step using the Kubernetes (kubectl) task. (Optional, but recommended).

Here is a yaml snippet of the same:
```
- task: Kubernetes@1
  displayName: 'kubectl login'
  inputs:
    kubernetesServiceEndpoint: myClusterConnection
    command: login

- powershell: 'kubectl create secret generic mysecret --from-literal=key=$env:mySecretEnvVar'
  displayName: 'PowerShell - kubectl create secret'
  env:
    mySecretEnvVar: $(mySecretVar)

- task: Kubernetes@1
  displayName: 'kubectl logout'
  inputs:
    command: logout
```

**Comment by ericsciple** [comment] 2020-02-28 19:06
@zachariahcox to help assign

**Comment by zachariahcox** [comment] 2020-02-28 20:26
@damccorm , do we have a good recommendation for this use-case? Thanks!

**Comment by damccorm** [comment] 2020-02-28 20:31
@ajinkya599 and I had some conversation about this in https://github.com/microsoft/azure-pipelines-task-lib/pull/511. Right now, our recommendation is explicitly masking escaped versions of secrets in the task code. That gets you everything you need in terms of masking.

I also have a work item on my end to more aggressively mask secrets and catch situations like this. I've already completed the server side work and plan on doing the agent side work soon, I'd guess that will roll in the next month or so.

**Comment by damccorm** [comment] 2020-03-06 20:00
We're now doing this, the fix should roll out over the next couple of weeks

**Closed by damccorm** 2020-03-06 20:00 UTC
Labels: Area: Build
