### ISSUE TITLE
 Azure File copy WinRM cannot complete the operation. 

### ISSUE THREAD

**Issue by greengumby** [microsoft/azure-pipelines-tasks#11158] opened 2019-08-20 15:33 UTC
Hi,

Not sure what I am doing wrong...

2019-08-13T14:47:17.3599547Z ##[debug]System.Management.Automation.RuntimeException: The remote session query failed for xxx.xxx.xxx.xxx with the following error message: WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet.  ---> System.InvalidOperationException: <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859046" Machine="fv-az130"><f:Message>WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. </f:Message></f:WSManFault>
2019-08-13T14:47:17.3613064Z ##[debug]   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2019-08-13T14:47:17.3625879Z ##[debug]   --- End of inner exception stack trace ---
2019-08-13T14:47:17.3680330Z ##[error]The remote session query failed for xxx.xxxx.xxxx with the following error message: WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. 
2

**Comment by chshrikh** [comment] 2019-08-21 03:55
@greengumby could see if you select the option of "Enable Copy Prerequisites" option in task and re-run it

![image](https://user-images.githubusercontent.com/11972852/63401612-94102280-c3f5-11e9-9312-f39cc36b2313.png)

**Comment by greengumby** [comment] 2019-08-21 04:06
Hi,

Yes, Enable Copy Prerequisites is already selected.

Thanks

[cid:image002.jpg@01D55818.D7E2EBD0]
Jeremy Martin | Software Development Manager
T +61 8 9211 8675 | M +61 448 811 535
Level 6, 130 Stirling Street, Perth WA 6000 | www.snowdengroup.com
FOLLOW SNOWDEN ON LINKEDIN<https://www.linkedin.com/company/snowden?trk=nmp_rec_act_company_photo>

**Comment by greengumby** [comment] 2019-08-27 06:59
Any more information on this or alternatives? Currently I cannot copy my artifacts to my Azure VM's for testing.

Thanks

**Comment by coin8086** [comment] 2019-09-05 06:20
I have the same issue and here's my yaml snippet:

```yaml
    - task: AzureFileCopy@3
      inputs:
        SourcePath: '$(Pipeline.Workspace)/SomeArtifact'
        azureSubscription: $(Subscription)
        resourceGroup: $(ResourceGroup)
        storage: $(StorageAccount)
        Destination: 'AzureVMs'
        ResourceFilteringMethod: machineNames
        MachineNames: $(TargetHosts)
        vmsAdminUserName: $(TargetHosts.AdminUserName)
        vmsAdminPassword: $(TargetHosts.AdminPassword)
        TargetPath: $(TargetHosts.Path)
        CleanTargetBeforeCopy: true
        enableCopyPrerequisites: true
      displayName: 'Deploy to $(TargetHosts)'
```

And here's the error for that:

```
The remote session query failed for xxx.xxx.xxx.xxx with the following error message: WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. 
```

Please help!

**Comment by greengumby** [comment] 2019-09-06 17:08
@coin8086 The lack of support for these pipeline components is really concerning. So much so I am considering jumping off the Azure train.

**Comment by coin8086** [comment] 2019-09-07 14:10
> 
> 
> The lack of support for these pipeline components is really concerning. So much so I am considering jumping off the Azure train.

I agree. Sometimes I have to pull a local copy of the source code of the Pipeline tasks and enable diagnostic info from the Pipeline to figure out why an error comes out, and sometimes I do this just because the document is rather confused or even misleading! That's really annoying!

**Comment by arjgupta** [comment] 2019-09-09 08:01
@greengumby can you try running a powershell task and try to run the invoke-command cmdlet and see if you can make a connection to the target machine.

**Comment by arjgupta** [comment] 2019-09-18 10:30
@greengumby i am closing this issue. Feel free to reopen if you are still facing this issue.

**Closed by arjgupta** 2019-09-18 10:30 UTC
Labels: Area: Release, bug

**Comment by greengumby** [comment] 2019-09-20 13:08
I don't know why this is closed as the issue still exists.

**Comment by greengumby** [comment] 2019-09-24 04:31
@coin8086 Did you solve/workaround this issue?

**Comment by coin8086** [comment] 2019-09-24 08:23
> @coin8086 Did you solve/workaround this issue?

No, I suspend my deployment with it. I have a lot of work to do and can't afford days trying and diagnosing for their problem. But it seems they don't work on it.

**Comment by RajGogri** [comment] 2020-02-04 10:01
<img width="626" alt="Screenshot 2020-02-04 at 12 31 30 PM" src="https://user-images.githubusercontent.com/30289220/73734223-4f8a0080-4763-11ea-8a30-af7f49a8b7d8.png"/>
Try running WinRM quickconfig in cmd and check if WinRM service is running and enabled for remote connection. Enjoy !

**Comment by MohanaRanjan** [comment] 2020-04-09 14:26
The same Problem i faced for Azure File Copy, Windows File Copy Tasks.

The following steps has resolved the above issue.

1. Make a deployment group under the Pipeline --> New Deployment Group. 
2. A Powershell Script will be generated . Make sure to check "Use a personal access token in the script for authentication"
3. Execute that script using PowerShell in Administrator Privilege in the VM you want to make File Copy Tasks or the Task that uses WinRM Protocol.
4. The VM will get added to the deployment Group.
5. Now the tweak here is when selecting the Empty Job in Azure Release Pipeline by default it will add a "Agent Job". But this will not work.
6. Select the Stage and Click "Add Phase Options" ( three dots ...) to choose the "Add Deployment Group Job"
7. This will have the option to link the VM you have already added to Deployment Group in Step 4.
8. Now when you add a New Azure File Copy or Power shell script tasks or any thing that uses the WinRM will work.

This resolved the issue for me. Hope this helps.

My another suggestion would be to add a Step in Azure Release Pipeline to check for the Deployment Group Job be mandatory while choosing the Tasks that uses the WinRM. Or this step should be documents in the Tasks Documentation as Note.

**Comment by placidseven** [comment] 2021-03-22 13:33
This issue needs to be reopened. These "work arounds" either don't work or are unacceptable.

**Comment by placidseven** [comment] 2021-03-22 13:36
> > @coin8086 Did you solve/workaround this issue?
> 
> No, I suspend my deployment with it. I have a lot of work to do and can't afford days trying and diagnosing for their problem. But it seems they are not working on it. @arjgupta

Unbelievable. This is unacceptable. Question. Did you open a support case with Microsoft? I'm opening one, RIGHT NOW. I've been using Azure File Copies in my build pipeline (though it is still a huge pain), but can't get them working in the release.

I've confirmed that WinRM is enabled, and my SP has the correct permissions. I'm not going through my release to put everything in a deplpoyment group. This is NOT what deployment groups should be used for.
