### ISSUE TITLE
Anonymous Web Hook for Build Trigger with external git source

### ISSUE THREAD

**Issue by neurospeech** [microsoft/azure-pipelines-tasks#6219] opened 2018-01-13 05:08 UTC
For external git source, the only way to setup build trigger is pull git source at regular interval. 

External git providers such as gitlab.com and even self hosted git repositories provide simple web hooks. If there is a unique url to trigger build for external git source, it will be helpful. 

Currently there are long workarounds to setup azure function, use vsts API with personal access token to login and submit build, but that is all maintenance overhead.

**Comment by leantk** [comment] 2020-07-07 02:49
This issue is stale because it has been open for a year with no activity. Remove the stale label or comment on the issue otherwise this will be closed in 5 days

**Comment by mathstuf** [comment] 2020-07-07 11:59
Webhook support for triggering builds would still be appreciated.

**Comment by theBNT** [comment] 2020-08-27 16:02
@mathstuf please see the [comment i just made](https://github.com/microsoft/azure-pipelines-tasks/issues/10360#issuecomment-682039151) on #10360 (which could be seen as duplicate of this), triggering builds (which in turn can trigger other things) is now possible via webhooks

**Comment by damccorm** [comment] 2020-11-25 16:33
I'm going to close this since it seems like the initial ask has been addressed. If there are further issues, please open a ticket at https://developercommunity.visualstudio.com/spaces/21/index.html since this isn't a directly tasks related issue

**Closed by damccorm** 2020-11-25 16:33 UTC
Labels: Area: CrossPlatform, enhancement
