### ISSUE TITLE
XamariniOS@2 task fails finding Mono when selecting specific xamarin/xcode version

### ISSUE THREAD

**Issue by bgaprogrammer** [microsoft/azure-pipelines-tasks#12759] opened 2020-04-24 14:04 UTC
## Required Information

**Question, Bug, or Feature?**  
*Type*: **ISSUE**

**Enter Task Name**: XamariniOS@2  

## Environment
- Server - Azure Pipelines or TFS on-premises?: **Azure Pipelines**

- Agent - Hosted or Private:  **HOSTED**

## Issue Description

I'm trying to build a Xamarin.iOS app using the latest mono/xamarin/xcode version, setting them in a explicit way, this because the current default version does not allow me to build my project, I need the latest.

When setting the version, the XamariniOS@2 task fails because it's not able to find mono.
I've tried also setting it using an Environment Variable but seems the build tools are not in the directory.

This is my current YML:

`trigger:
- develop

pool:
  vmImage: 'macOS-10.15'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:

- task: NuGetToolInstaller@1
  inputs:
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- script: /bin/bash -c "sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_8_0_123"
  displayName: 'Select the Xamarin SDK version 6.8.0.123'

- script: /bin/bash -c "echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_11.4.1.app;sudo xcode-select --switch /Applications/Xcode_11.4.1.app/Contents/Developer"
  displayName: 'Updating xcode version to 11.4.1'

- script: | 
    SYMLINK=6_8_0_123 
    MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
    echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
    echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
    echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
    echo "##vso[task.setvariable variable=MONOPATH]$MONOPREFIX/bin"
  name: monopathstep
  displayName: 'Setting Mono path to target version 6.8.0.123'

- task: XamariniOS@2
  inputs:
    solutionFile: '**/*iOS.csproj'
    configuration: '$(buildConfiguration)'
    buildToolLocation: '$(MONOPATH)'
    buildForSimulator: true
    packageApp: false`

This is the task result:

`Starting: XamariniOS

==============================================================================

Task         : Xamarin.iOS

Description  : Build an iOS app with Xamarin on macOS

Version      : 2.167.0

Author       : Microsoft Corporation

Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/xamarin-ios

==============================================================================

##[error]Xamarin.iOS task failed with error Error: Not found build tool: /Library/Frameworks/Mono.framework/Versions/6_8_0_123/bin. For guidance on setting up the build pipeline, see https://go.microsoft.com/fwlink/?LinkId=760847.

Finishing: XamariniOS`

**Comment by alexander-smolyakov** [comment] 2020-05-06 11:15
Hello, @bgaprogrammer!

Thanks for your patience. 

As I can see you use the virtual image with macOS-10.15- this image already uses the latest version of xamarin, mono, and xcode by default, so you don't need to manually set versions for your pipeline. Furthermore, this image frequently updated so you always can get the latest versions of tools by default.

As far as I know symlink doesn't intended to be changed manually, and 6_8_0_123 values seems to refer to not existing folder, so it causes "Not found build tool" error. Probably there's some other thing that causes the issue.

Could you please try to run pipeline without setting versions explicitly?

If you still have some questions about how to set up specific versions of xamarin, mono, and xcode, you can provide your questions to [virtual environments](https://github.com/actions/virtual-environments) team. They are working on images for the Microsoft-hosted agents and able to provide more transparency for these types of questions.

**Comment by bgaprogrammer** [comment] 2020-05-06 13:05
Hello @alexander-smolyakov 

Regarding the reason of changing manually the versions, It was because at the time I created the pipeline the build was throwing and error rsaying my app was intended to be compiled with a version of xcode (iOS in fact) not available in the macOS-10.15 image, so I decided to target it manually (because the image documentation said the tools were there).

It seems that per today the image is working for real with the latest versions because now my code compiles and builds sucessfully (I just removed the script steps from the pipeline, and ran it). So I guess the image was updated behind the scenes in the las minutes/hours/days.

It would be great to have a way to know when the image was updated, perhaps a suscription email or something similar.

**Comment by alexander-smolyakov** [comment] 2020-05-06 14:14
Hello, @bgaprogrammer!

Glad to hear that's all works now.

Regarding images update notifications - for now, there's no mechanism that sends notifications about images update, but you can check actual information about macOS images in [this file](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.15-Readme.md).

If you will find some issues about toolkits versions in docs, as I mentioned earlier, please provide your questions to the [virtual environments](https://github.com/actions/virtual-environments) team.

**Comment by alexander-smolyakov** [comment] 2020-05-12 10:25
@bgaprogrammer, closing this since the issue is resolved.

**Closed by alexander-smolyakov** 2020-05-12 10:25 UTC
Labels: Area: ABTT, Area: CrossPlatform, bug
