### ISSUE TITLE
[UseDotNet@2] - wrong path set with tool cache

### ISSUE THREAD

**Issue by hbuckle** [microsoft/azure-pipelines-tasks#13107] opened 2020-06-12 08:03 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: UseDotNet@2

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  https://dev.azure.com/cbinfrastructure/cbi/_build/results?buildId=168062

- Agent - Hosted or Private: Private
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows 2019, 2.170.1

## Issue Description

On my private agent image I am populating the tool cache like so

```powershell
gci "$env:AGENT_TOOLSDIRECTORY\dotnet\sdk" -Recurse -Depth 1


    Directory: C:\tools_cache\dotnet\sdk

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          12/06/2020    07:27                3.1.301
-a---          12/06/2020    07:27              0 3.1.301.complete

    Directory: C:\tools_cache\dotnet\sdk\3.1.301

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          12/06/2020    07:26                host
d----          12/06/2020    07:27                packs
d----          12/06/2020    07:26                sdk
d----          12/06/2020    07:27                shared
d----          12/06/2020    07:26                templates
-a---          20/05/2020    20:59         149904 dotnet.exe
-a---          20/05/2020    20:49           9519 LICENSE.txt
-a---          20/05/2020    20:49          31961 ThirdPartyNotices.txt
```

And adding the task like so

```yaml
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 3.1.x
  displayName: dotnet install
```

When the task runs it detects the required version is in the cache, but it updates DOTNET_ROOT and PATH to point to `$env:AGENT_TOOLSDIRECTORY\dotnet`, instead of pointing to `$env:AGENT_TOOLSDIRECTORY\dotnet\sdk\3.1.301`

### Task logs

[8.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4769500/8.zip)

**Comment by issacnitin** [comment] 2020-06-12 10:45
@hbuckle This is by design. If your project have a global.json or the csproj targets the correct SDK version, dotnet CLI will detect and it will be used.

**Comment by hbuckle** [comment] 2020-06-16 06:16
That seems to go against how the tool installer lib is supposed to work?

```
An installer task will:

    Advertise common or well known versions of a tool (LTS or common) via a combo dropdown
    Find that version in a tools cache or acquires it on demand
    Prepend the path with the path to that instance of the tool.
```
[overview](https://github.com/microsoft/azure-pipelines-tool-lib/blob/master/docs/overview.md)

How can I populate the cache to avoid having to download the sdk each time?

**Comment by anuragc617** [comment] 2020-06-21 10:33
@hbuckle since you have specified version input as 3.1.x, the task tries to find out the latest version in 3.1 channel and if the latest version is not in your agent tool directory it will download it. If you have only 3.1.301 in your tool cache and you don't want the task to download the latest then use 3.1.301 in task input instead of 3.1.x. 
In your case, I saw the logs and find out that the task is not downloading any SDK and using 3.1.301 found in the tool directory. It is doing so because the latest-SDK version for channel 3.1 is 3.1.301.

**Comment by anuragc617** [comment] 2020-06-24 05:11
@hbuckle closing this as all your questions are answered and there is no bug in task. Feel free to comment if you have any other question.

**Closed by anuragc617** 2020-06-24 05:11 UTC
Labels: Area: Release, bug

**Comment by hbuckle** [comment] 2020-07-09 10:24
There is a bug, because the latest SDK is 3.1.301, and this version is present in the cache, but the task incorrectly updates DOTNET_ROOT and PATH, so subsequent tasks can not find the dotnet exe

**Comment by StingyJack** [comment] 2021-07-23 21:30
> @hbuckle This is by design

@issacnitin, @bishal-pdMSFT, and @anuragc617  - why is it by design that this task does not work properly with the MSFT hosted agent images that it typically is executed on?
