### ISSUE TITLE
Gradle v2 Jacoco code coverage is broken

### ISSUE THREAD

**Issue by websolut** [microsoft/azure-pipelines-tasks#12593] opened 2020-03-29 00:53 UTC
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Gradle v2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 
    
Pipeline: https://dev.azure.com/sis-cat-com/sis2-ws-all/_build/results?buildId=24337&view=results

- Agent - Hosted : 
Windows 2019

## Issue Description

When running a gradle.build with enabled code coverage the following error is thrown for jacoco:

Build file 'D:\a\1\s\build.gradle' line: 215

* What went wrong:
A problem occurred evaluating root project '*****'.
> Could not set unknown property 'append' for extension 'jacoco' of type org.gradle.testing.jacoco.plugins.JacocoTaskExtension.

**Comment by melakonda** [comment] 2020-04-02 15:09
I am seeing the same issue.. anyone has solution for this. Please update

**Comment by chevarria** [comment] 2020-04-14 14:58
I'm having the same problem. Please update

**Comment by macromania** [comment] 2020-05-09 02:24
I have just tried this task on Azure Pipelines and getting the same error.

pipeline:

```yml
pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: '$(System.DefaultWorkingDirectory)/XXXXX/gradlew'
      workingDirectory: '$(System.DefaultWorkingDirectory)/XXXXX/'
      tasks: 'test'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      codeCoverageToolOption: 'JaCoCo'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      sonarQubeRunAnalysis: false

```

the error message from build logs

```
BUILD SUCCESSFUL

.....


Could not set unknown property 'append' for extension 'jacoco' of type org.gradle.testing.jacoco.plugins.JacocoTaskExtension.

```

**Comment by ryyaeg** [comment] 2020-05-25 02:34
I have also confirmed that this Issue will reproduce.

- This issue occurs when using Gradle 6.0 or higher and JDK 11.
- It does not occur with Gradle 5.6.4 or lower and with JDK 1.8.
- Therefore, this Issue is a Gradle and JDK version-dependent issue.

The following repositories do not generate an Issue, but the image of the code coverage is broken.
https://github.com/ryyaeg/pipelines-java

**Comment by luigi2004** [comment] 2020-05-25 13:29
This is a gradle 6.0 issue append was removed and the task directly setting it

**Comment by kingwang-git** [comment] 2020-06-08 19:43
> * This issue occurs when using Gradle 6.0 or higher and JDK 11.

I am seeing the same issue on Gradle 6.0.1 and jdk 8 (OpenJDK).
Still believe this is Azure-related as we only hit the issue when running on DevOps pipeline.
Is there a work around?

**Comment by ekaterina-tatanova** [comment] 2020-07-14 16:05
@kingwang-git It seems to be related to Gradle update. As mentioned [here](https://docs.gradle.org/current/userguide/upgrading_version_5.html#other_deprecated_behaviors_and_apis), the 'append' property on JacocoTaskExtension has been removed. Could you please share build.gradle and gradle.properties files of your project to make sure that there's no issue with Gradle version?

**Comment by therottman** [comment] 2020-07-15 09:52
I'm having the same issue.

One workaround is to remove `codeCoverageToolOption` from the Gradle@2 task and add a new task after:
```
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(Build.SourcesDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'
    reportDirectory: '$(Build.SourcesDirectory)/build/reports/jacoco/test/html'
```

**Comment by ekaterina-tatanova** [comment] 2020-07-22 06:24
@therottman The solution to use PublishCodeCoverageResults task does not work because there is no generated file with code coverage statistics.

**Comment by therottman** [comment] 2020-07-22 09:26
@ekaterina-tatanova hmn, maybe it's because I've this in build.gradle:

```
test {
	useJUnitPlatform()
	finalizedBy jacocoTestReport // report is always generated after tests run
}

jacocoTestReport {
	dependsOn test // tests are required to run before generating the report
}

jacocoTestReport {
	reports {
		xml.enabled true
	}
}
```

**Comment by glazzari** [comment] 2020-08-05 17:26
I'm facing the same issue on Azure pipelines.

**Comment by ekaterina-tatanova** [comment] 2020-08-06 09:23
@glazzari What version of Gradle do you use? Could you please share build.gradle and gradle.properties files of your project?

**Comment by glazzari** [comment] 2020-08-09 15:48
@ekaterina-tatanova It's a Micronaut app created with `mn create-app com.example.myapp --lang=kotlin --test=kotlintest`. I downgraded gradle from 6.5.1 to 5.6.2 with OpenJDK 8 in my Dockerfile and it's working now. Interesting, because the version with gradle 6.5.1 and OpenJDK 14 works on my laptop.

**gradle.properties**

micronautVersion=2.0.1
kotlinVersion=1.3.72

**build.gradle** - I've just added the following configs to the generated file.

```
jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.25
            }
        }
    }
}

jacocoTestReport {
    reports {
        xml.enabled = true
        html.enabled = true
    }
}

check.dependsOn(jacocoTestReport)
```

**Comment by frenchf** [comment] 2020-08-25 07:58
I am having the same problem. 
JDK 11
Gradle 6.5
Works fine locally but fails when run in Azure.
Based on all the above I think it's safe to say this is an Azure problem.
Any idea when this might be fixed?

**Comment by ebcFlagman** [comment] 2020-08-28 07:25
I am having the same problem.
JDK 11
Gradle 6.0
Works fine locally but fails when run in Azure.

**Comment by anatolybolshakov** [comment] 2020-09-10 13:24
Hi @glazzari @frenchf @ebcFlagman could you please try to specify JDK version using JavaToolInstaller task and Gradle version in gradle-wrapper.properties file (distributionUrl property)?

**Comment by ebcFlagman** [comment] 2020-09-11 05:59
@anatolybolshakov 
I've defined the java version with the JavaToolInstaller to use Java 11 and in the gradle-wrapper.properties i've defined the url to the gradle 6 download. But I became the same error

**Comment by anatolybolshakov** [comment] 2020-09-18 13:26
Hi @ebcFlagman @frenchf @glazzari @therottman @websolut - thanks for provided info? We prepared a fix and going to deploy it soon, will let you know once it's deployed

**Comment by adsurg** [comment] 2020-09-22 07:54
> Hi @ebcFlagman @frenchf @glazzari @therottman @websolut - thanks for provided info? We prepared a fix and going to deploy it soon, will let you know once it's deployed

Would you be kind enough to let me know too, please?

**Comment by anatolybolshakov** [comment] 2020-10-12 15:25
Hi @ebcFlagman @frenchf @glazzari @therottman @websolut @adsurg - the fix for this issue has been rolled out - I'm closing it at the moment, but please let us know if issue still appears

**Comment by simsibimsiwimsi** [comment] 2020-10-15 16:07
Hi @anatolybolshakov 

I am still experiencing the issue getting the following error.. We are using the following parameterisation in Gradle@2 Task:

    codeCoverageTool: 'JaCoCo'
    codeCoverageClassFilesDirectories: 'build/classes/java/main/'
    codeCoverageFailIfEmpty: true

and the task utilised by the pipeline is:

Task         : Gradle
Description  : Build using a Gradle wrapper script
Version      : 2.176.0

which as far as I could see is the task version which should contain the fix.

Nevertheless I get 

Could not set unknown property 'append' for extension 'jacoco' of type org.gradle.testing.jacoco.plugins.JacocoTaskExtension

I have checked back and forth that our code is not setting the "append" anywhere and the build runs fine if I execute the jacocoTestReport task using gradle directly (in which case I don't get the helpful configuration defaults )

**Comment by ebcFlagman** [comment] 2020-10-16 06:27
Same here, I've also still the issue

```
Task         : Gradle
Description  : Build using a Gradle wrapper script
Version      : 2.176.0
```

FAILURE: Build failed with an exception.

* Where:
Build file '/home/vsts/work/1/s/build.gradle' line: 155

* What went wrong:
A problem occurred evaluating root project 'coffeelink-master-data-service'.
> Could not set unknown property 'append' for extension 'jacoco' of type org.gradle.testing.jacoco.plugins.JacocoTaskExtension.

**Comment by anatolybolshakov** [comment] 2020-10-16 10:53
Hi @simsibimsiwimsi @ebcFlagman I can't reproduce it at the moment - could you please share your build.gradle file or provide minimal project - so we could reproduce it on our side?

**Comment by ebcFlagman** [comment] 2020-10-16 11:11
I've uploaded the build.gradle and the pipeline script. When you need additional information please ask

[build.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5391096/build.zip)

**Comment by anatolybolshakov** [comment] 2020-10-22 11:00
Hi everyone, we just prepared a fix for another issue here and going to roll out these changes during next sprint

**Comment by glazzari** [comment] 2020-11-12 14:22
Hey @anatolybolshakov do you have any update on this?

**Comment by anatolybolshakov** [comment] 2020-11-12 14:25
Hi @glazzari we prepared a fix here and going to roll it out- usually it takes about 3 weeks to be done

**Comment by sudheeranguluri** [comment] 2020-11-16 21:33
Having the same issue. Following

**Comment by J3remyD** [comment] 2020-11-18 19:04
Same here ! It's really blocking us for quality monitoring :(

**Comment by SqueedWalz** [comment] 2020-11-26 07:00
Will you also update the task to supoport the new spotBugs parameter (previously "findBugs")?
In the yaml task it is called findBugsRunAnalysis.

**Comment by anatolybolshakov** [comment] 2020-11-26 12:45
@SqueedWalz could you please create a separate issue for it? It seems like an enhancement we could implement also

**Comment by SqueedWalz** [comment] 2020-11-26 13:12
@anatolybolshakov Will do!

**Comment by J3remyD** [comment] 2020-11-30 10:59
> Hi @glazzari we prepared a fix here and going to roll it out- usually it takes about 3 weeks to be done

Any news on this @anatolybolshakov ?

**Comment by anatolybolshakov** [comment] 2020-12-02 12:58
Hi everyone! We have rolled out the fix for this issue - please let us know if it's still actual for you.

**Comment by anatolybolshakov** [comment] 2020-12-08 09:06
Closing this at the moment since we have rolled out the fix - please let us know if there are still any issues

**Closed by anatolybolshakov** 2020-12-08 09:06 UTC
Labels: Area: ABTT, Task: Gradle, bug

**Comment by PrateekAgarwal1908** [comment] 2021-08-04 08:30
Hello Team, I can see get the same issue - 
could not get unknown property 'jacocotestreport' for project 'PROJ_NAME' of type org.gradle.api.Project

I am using sonarqube and gradle

**Comment by scientificCommunity** [comment] 2021-09-11 10:57
Hello Team, I have got the same issue. If anyone has the solution for this. Please update. Thanks!

`Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'enabled' for extension 'jacoco' of type org.gradle.testing.jacoco.plugins.JacocoPluginExtension.`

**Comment by anatolybolshakov** [comment] 2021-09-13 14:40
Hi @PrateekAgarwal1908 @scientificCommunity which task version do you use?

**Comment by scientificCommunity** [comment] 2021-09-15 06:09
> Hello Team, I have got the same issue. If anyone has the solution for this. Please update. Thanks!
> 
> `Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'enabled' for extension 'jacoco' of type org.gradle.testing.jacoco.plugins.JacocoPluginExtension.`

 It's expected, just because I use it in a wrong way. thanks for your answer! @anatolybolshakov

**Comment by nort3x** [comment] 2023-03-28 20:17
hi @anatolybolshakov ,
i still have this issue in `Gradle@3`,
you mentioned you had been rolled out a fix for this

i'm still using a monkey patch like this (thanks to  @pduartee  )

```kotlin
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(Build.SourcesDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'
    reportDirectory: '$(Build.SourcesDirectory)/build/reports/jacoco/test/html'
```

but shouldn't this really be solved? or at least be documented well enough to be understood in 5 minutes rather 10 failed tests?
