### ISSUE TITLE
Index Sources & Publish Symbols (v2.*) - Unable to Step into Indexed Source Files using VS2017

### ISSUE THREAD

**Issue by csturm83** [microsoft/azure-pipelines-tasks#7728] opened 2018-07-13 16:02 UTC
## Environment

- TFS 2018 on-premise
- Private Agent
   - Agent.OS  Windows_NT  
   - Agent.OSVersion  10.0.14393
   - Agent.Version  2.122.2

## Issue Description

**TFS Build Task:** Index Sources & Publish Symbols Task (v2.*)

I am having difficulties getting a File Share Symbol Server working with VS2017. I believe it may have to do with my TFS collection name having spaces in it (means the default URL of my TFS Collection has spaces in it too).

I have a Symbol file location set in Tools -> Options -> Debugging -> Symbols. I start a Debug session and attempt to step into a .dll/.pdb built on my build server. Below error message is what I am seeing in VS2017 debug output (redacted a bit). 

It looks as though the TF.exe **/server:** command line argument URL string is not being wrapped in quotations. This has the effect of truncating my server URL which has spaces in it.  I noticed such in the TF31002 error message.

### Error logs

Observed in VS2017 (v15.7.5) Debug Output
- Debug -> Options...
   - Print source server diagnostic messages to the Output window (enabled)
   - Enable source server support (enabled)
   - Enable Just My Code (disabled)

SRCSRV:  "CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe" view /version:{VERSION} /noprompt "$/{TFS_PROJECT}/{FILEPATH}.cs" /server:{**SERVER_URL_WITH_SPACES**} /output:"C:\Users\{USER}\AppData\Local\SOURCE~1\VSTFSSERVER\{TFS_PROJECT}\{FILEPATH}.cs" /prompt
         TF31002: Unable to connect to this Team Foundation Server: {**TRUNCATED_SERVER_URL!!**}.
         Team Foundation Server Url: {**TRUNCATED_SERVER_URL!!**}.
           
         Possible reasons for failure include:
         - The name, port number, or protocol for the Team Found         ation Server is incorrect.
         - The Team Foundation Server is offline.
         - The password has expired or is incorrect.
         
         Technical information (for administrator):
         The remote server returned an error: (404) Not Found.
SRCSRV: Source server cannot retrieve the source code for file '{BUILD_SERVER_PATH}.cs' in module '{WORKSPACE_PATH}.dll'. The system cannot find the file specified.

### Additional Info

Downgrading the Index Sources & Publish Symbols Task to (v1.*) made the build fail outright with the following Error Log:

2018-07-13T17:19:31.4744701Z ##[section]Starting: Publish symbols path
2018-07-13T17:19:31.4744701Z ==============================================================================
2018-07-13T17:19:31.4744701Z Task         : Index Sources & Publish Symbols
2018-07-13T17:19:31.4744701Z Description  : Index your source code and publish symbols to a file share
2018-07-13T17:19:31.4744701Z Version      : 1.0.39
2018-07-13T17:19:31.4744701Z Author       : Microsoft Corporation
2018-07-13T17:19:31.4744701Z Help         : Indexing enables you to use your .pdb symbol files to debug an app on a machine other than the one you used to build the app. For example, you can debug an app built by a build agent from a dev machine that does not have the source code.<br/>[More Information](https://go.microsoft.com/fwlink/?LinkID=613722)
2018-07-13T17:19:31.4744701Z ==============================================================================
**2018-07-13T17:19:34.5529007Z ##[error]Exception calling "IsPathRooted" with "1" argument(s): "Illegal characters in path."**
2018-07-13T17:19:34.5994908Z ##[section]Finishing: Publish symbols path

**Comment by csturm83** [comment] 2018-07-14 02:39
My PowerShell skills are lacking, but is a potential fix to change [this line](https://github.com/Microsoft/vsts-tasks/blob/c69e130ac4b9c6e7bbd106a488140e2368d9aa80/Tasks/PublishSymbolsV2/IndexHelpers/SrcSrvIniContentFunctions.ps1#L119) to something like:

```powershell
'TFS_EXTRACT_CMD=tf.exe view /version:%var4% /noprompt "$%var3%" /server:"$%fnvar%(%var2%)" /output:%SRCSRVTRG%'
```
Or should the Collection URI be UrlEncoded elsewhere in the code?

**Comment by fadnavistanmay** [comment] 2019-08-23 19:52
This is by design. Closing.

**Closed by fadnavistanmay** 2019-08-23 19:52 UTC
Labels: Area: ArtifactsCore, Area: Symbols
