### ISSUE TITLE
Azure App Service Deploy (Preview) failing consistently - An unknown error has occurred

### ISSUE THREAD

**Issue by jameshowe** [microsoft/azure-pipelines-tasks#9118] opened 2018-12-18 23:30 UTC
## Environment
- Server - Azure Pipelines
   
    - Account: `tagdat`
    - Project Name: `Geodis`
    - Build Name: `Geodis Portal`
    - Build No: `20181218.1`

- Agent - Hosted 
    
    - Queue: `Hosted Ubuntu 1604`

## Issue Description

Azure App Service Deploy task has started to fail consistently with a very obscure error:

> An unknown error has occurred. Check the diagnostic log for details.

Seems to occur during the KuduSync operation. The task is set to Version 4.* (Preview), and the same build is successfully deployed to a different app in another region.

### Task logs

[Verbose log](https://github.com/Microsoft/azure-pipelines-tasks/files/2692616/tasklog.log)

### Error logs

```
2018-12-18T22:54:34.7692805Z Running deployment command...
2018-12-18T22:54:34.7696500Z ##[debug][GET]https://tagdat-geodis-staging.scm.azurewebsites.net/api/deployments/3f6f829eeb8048cea583fc5dd6f33428/log/e22354db-ed0b-4b84-91d8-3d895ddfd12d
2018-12-18T22:54:35.3857645Z ##[debug]getDeploymentLogs. Data: {"statusCode":200,"statusMessage":"OK","headers":{"cache-control":"no-cache","pragma":"no-cache","content-length":"9708","content-type":"application/json; charset=utf-8","expires":"-1","server":"Apache/2.4.10 (Debian)","x-ms-request-id":"83e79cf8-f05c-4c32-b062-1883c0c0a455","x-aspnet-version":"4.0.30319","set-cookie":["ARRAffinity=bbac118ea40eb06b116eaac88fd897566cba73cdb4989f7d0ef3701ed25abfc4;Path=/;HttpOnly;Domain=xxxxxxxx.scm.azurewebsites.net"],"date":"Tue, 18 Dec 2018 22:54:35 GMT","connection":"close"},"body":[{"log_time":"2018-12-18T22:45:49.037206Z","id":"","message":"Command: \"/home/site/deployments/tools/deploy.sh\"","type":0,"details_url":null},{"log_time":"2018-12-18T22:45:52.125203Z","id":"","message":"Handling Basic Web Site deployment.","type":0,"details_url":null},{"log_time":"2018-12-18T22:45:53.594532Z","id":"","message":"Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'","type":0,"details_url":null},{"log_time":"2018-12-18T22:45:54.369152Z","id":"","message":"Ignoring: .git","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:22.472726Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/co/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:23.234219Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/code-point-at/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:23.3177Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/combined-stream/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:23.464639Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/concat-map/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:23.525274Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/console-control-strings/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:23.561161Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/core-util-is/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:23.614025Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/cryptiles/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:23.866086Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/dashdash/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:23.926445Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/dashdash/node_modules/assert-plus/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:23.973135Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/debug/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:24.352248Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/deep-extend/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:24.458699Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/delayed-stream/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:24.603689Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/delegates/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:24.743875Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/ecc-jsbn/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:24.802912Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/extend/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:24.859008Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/extsprintf/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:24.913534Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/forever-agent/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:24.944825Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/form-data/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:25.006872Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/fs.realpath/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:25.055961Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/fstream/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:25.33966Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/fstream-ignore/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:25.385578Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/gauge/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:25.560814Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/getpass/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:25.647191Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/getpass/node_modules/assert-plus/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:25.758473Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/glob/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:25.788569Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/graceful-fs/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:25.81719Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/har-schema/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:26.070155Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/har-validator/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:26.170574Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/has-unicode/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:26.214252Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/hawk/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:26.407629Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/hoek/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:26.756216Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/http-signature/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:26.827713Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/inflight/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:26.878718Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/inherits/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:26.910427Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/ini/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:26.934959Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/is-fullwidth-code-point/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:26.961699Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/is-typedarray/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:26.984314Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/isarray/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:27.025406Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/isstream/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:27.057622Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/jodid25519/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:27.119936Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/jsbn/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:27.230928Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/json-schema/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:27.596629Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/json-stable-stringify/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:27.884724Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/json-stringify-safe/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:27.933925Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/jsonify/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:28.190172Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/jsprim/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:28.302305Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/jsprim/node_modules/assert-plus/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:28.395106Z","id":"","message":"Copying file: 'node_modules/fsevents/node_modules/mime-db/package.json'","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:28.446101Z","id":"","message":"Omitting next output lines...","type":0,"details_url":null},{"log_time":"2018-12-18T22:47:48.95341Z","id":"","message":"Processed 220 files...","type":0,"details_url":null},{"log_time":"2018-12-18T22:48:09.254737Z","id":"","message":"Processed 377 files...","type":0,"details_url":null},{"log_time":"2018-12-18T22:48:29.374029Z","id":"","message":"Processed 508 files...","type":0,"details_url":null},{"log_time":"2018-12-18T22:48:49.411063Z","id":"","message":"Processed 545 files...","type":0,"details_url":null},{"log_time":"2018-12-18T22:49:11.29873Z","id":"","message":"Processed 554 files...","type":0,"details_url":null},{"log_time":"2018-12-18T22:49:39.481539Z","id":"","message":"Processed 658 files...","type":0,"details_url":null},{"log_time":"2018-12-18T22:49:59.552229Z","id":"","message":"Processed 685 files...","type":0,"details_url":null},{"log_time":"2018-12-18T22:50:22.173303Z","id":"","message":"Processed 690 files...","type":0,"details_url":null},{"log_time":"2018-12-18T22:50:42.834369Z","id":"","message":"Processed 701 files...","type":0,"details_url":null}]}
2018-12-18T22:54:35.3865392Z Command: "/home/site/deployments/tools/deploy.sh"
2018-12-18T22:54:35.3865494Z Handling Basic Web Site deployment.
2018-12-18T22:54:35.3865912Z Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
2018-12-18T22:54:35.3865987Z Ignoring: .git
2018-12-18T22:54:35.3866250Z Copying file: 'node_modules/fsevents/node_modules/co/package.json'
2018-12-18T22:54:35.3866508Z Copying file: 'node_modules/fsevents/node_modules/code-point-at/package.json'
2018-12-18T22:54:35.3866780Z Copying file: 'node_modules/fsevents/node_modules/combined-stream/package.json'
2018-12-18T22:54:35.3867023Z Copying file: 'node_modules/fsevents/node_modules/concat-map/package.json'
2018-12-18T22:54:35.3867308Z Copying file: 'node_modules/fsevents/node_modules/console-control-strings/package.json'
2018-12-18T22:54:35.3867559Z Copying file: 'node_modules/fsevents/node_modules/core-util-is/package.json'
2018-12-18T22:54:35.3867826Z Copying file: 'node_modules/fsevents/node_modules/cryptiles/package.json'
2018-12-18T22:54:35.3868066Z Copying file: 'node_modules/fsevents/node_modules/dashdash/package.json'
2018-12-18T22:54:35.3868363Z Copying file: 'node_modules/fsevents/node_modules/dashdash/node_modules/assert-plus/package.json'
2018-12-18T22:54:35.3868621Z Copying file: 'node_modules/fsevents/node_modules/debug/package.json'
2018-12-18T22:54:35.3868865Z Copying file: 'node_modules/fsevents/node_modules/deep-extend/package.json'
2018-12-18T22:54:35.3869128Z Copying file: 'node_modules/fsevents/node_modules/delayed-stream/package.json'
2018-12-18T22:54:35.3869553Z Copying file: 'node_modules/fsevents/node_modules/delegates/package.json'
2018-12-18T22:54:35.3869816Z Copying file: 'node_modules/fsevents/node_modules/ecc-jsbn/package.json'
2018-12-18T22:54:35.3870074Z Copying file: 'node_modules/fsevents/node_modules/extend/package.json'
2018-12-18T22:54:35.3870338Z Copying file: 'node_modules/fsevents/node_modules/extsprintf/package.json'
2018-12-18T22:54:35.3870594Z Copying file: 'node_modules/fsevents/node_modules/forever-agent/package.json'
2018-12-18T22:54:35.3871352Z Copying file: 'node_modules/fsevents/node_modules/form-data/package.json'
2018-12-18T22:54:35.3871844Z Copying file: 'node_modules/fsevents/node_modules/fs.realpath/package.json'
2018-12-18T22:54:35.3872155Z Copying file: 'node_modules/fsevents/node_modules/fstream/package.json'
2018-12-18T22:54:35.3872446Z Copying file: 'node_modules/fsevents/node_modules/fstream-ignore/package.json'
2018-12-18T22:54:35.3872749Z Copying file: 'node_modules/fsevents/node_modules/gauge/package.json'
2018-12-18T22:54:35.3873029Z Copying file: 'node_modules/fsevents/node_modules/getpass/package.json'
2018-12-18T22:54:35.3873361Z Copying file: 'node_modules/fsevents/node_modules/getpass/node_modules/assert-plus/package.json'
2018-12-18T22:54:35.3873664Z Copying file: 'node_modules/fsevents/node_modules/glob/package.json'
2018-12-18T22:54:35.3873966Z Copying file: 'node_modules/fsevents/node_modules/graceful-fs/package.json'
2018-12-18T22:54:35.3874251Z Copying file: 'node_modules/fsevents/node_modules/har-schema/package.json'
2018-12-18T22:54:35.3874701Z Copying file: 'node_modules/fsevents/node_modules/har-validator/package.json'
2018-12-18T22:54:35.3874929Z Copying file: 'node_modules/fsevents/node_modules/has-unicode/package.json'
2018-12-18T22:54:35.3875169Z Copying file: 'node_modules/fsevents/node_modules/hawk/package.json'
2018-12-18T22:54:35.3875925Z Copying file: 'node_modules/fsevents/node_modules/hoek/package.json'
2018-12-18T22:54:35.3876201Z Copying file: 'node_modules/fsevents/node_modules/http-signature/package.json'
2018-12-18T22:54:35.3876449Z Copying file: 'node_modules/fsevents/node_modules/inflight/package.json'
2018-12-18T22:54:35.3876835Z Copying file: 'node_modules/fsevents/node_modules/inherits/package.json'
2018-12-18T22:54:35.3877083Z Copying file: 'node_modules/fsevents/node_modules/ini/package.json'
2018-12-18T22:54:35.3877331Z Copying file: 'node_modules/fsevents/node_modules/is-fullwidth-code-point/package.json'
2018-12-18T22:54:35.3877588Z Copying file: 'node_modules/fsevents/node_modules/is-typedarray/package.json'
2018-12-18T22:54:35.3877830Z Copying file: 'node_modules/fsevents/node_modules/isarray/package.json'
2018-12-18T22:54:35.3878077Z Copying file: 'node_modules/fsevents/node_modules/isstream/package.json'
2018-12-18T22:54:35.3878487Z Copying file: 'node_modules/fsevents/node_modules/jodid25519/package.json'
2018-12-18T22:54:35.3878728Z Copying file: 'node_modules/fsevents/node_modules/jsbn/package.json'
2018-12-18T22:54:35.3878954Z Copying file: 'node_modules/fsevents/node_modules/json-schema/package.json'
2018-12-18T22:54:35.3879208Z Copying file: 'node_modules/fsevents/node_modules/json-stable-stringify/package.json'
2018-12-18T22:54:35.3879454Z Copying file: 'node_modules/fsevents/node_modules/json-stringify-safe/package.json'
2018-12-18T22:54:35.3879697Z Copying file: 'node_modules/fsevents/node_modules/jsonify/package.json'
2018-12-18T22:54:35.3879921Z Copying file: 'node_modules/fsevents/node_modules/jsprim/package.json'
2018-12-18T22:54:35.3880188Z Copying file: 'node_modules/fsevents/node_modules/jsprim/node_modules/assert-plus/package.json'
2018-12-18T22:54:35.3880427Z Copying file: 'node_modules/fsevents/node_modules/mime-db/package.json'
2018-12-18T22:54:35.3880506Z Omitting next output lines...
2018-12-18T22:54:35.3880558Z Processed 220 files...
2018-12-18T22:54:35.3880624Z Processed 377 files...
2018-12-18T22:54:35.3880765Z Processed 508 files...
2018-12-18T22:54:35.3881006Z Processed 545 files...
2018-12-18T22:54:35.3881064Z Processed 554 files...
2018-12-18T22:54:35.3882939Z Processed 658 files...
2018-12-18T22:54:35.3883022Z Processed 685 files...
2018-12-18T22:54:35.3883101Z Processed 690 files...
2018-12-18T22:54:35.3883176Z Processed 701 files...
2018-12-18T22:54:35.3883519Z An unknown error has occurred. Check the diagnostic log for details.
2018-12-18T22:54:35.3948334Z ##[error]Failed to deploy web package to App Service.
2018-12-18T22:54:35.3957448Z ##[debug]Processed: ##vso[task.issue type=error;]Failed to deploy web package to App Service.
2018-12-18T22:54:35.3957711Z ##[debug]Deployment Failed with Error: Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
2018-12-18T22:54:35.3958034Z ##[debug]task result: Failed
2018-12-18T22:54:35.3958342Z ##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
2018-12-18T22:54:35.3958584Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
2018-12-18T22:54:35.3959421Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
```

**Comment by jameshowe** [comment] 2018-12-19 11:10
Workaround - switching Azure App Service Deploy to v3.* works.

**Comment by SumiranAgg** [comment] 2018-12-20 06:12
@jameshowe Can you share complete debug logs at RM_Customer_Queries@microsoft.com.
Set variable System.debug with value 'true' in the release and deploy again. Share logs generated.

**Comment by jameshowe** [comment] 2018-12-20 09:41
@SumiranAgg the verbose log I included is the log for that task action with `system.debug=true` enabled. What other logs are you looking for?

**Comment by jacemw08** [comment] 2018-12-21 07:18
Stay off my shit u pussy

**Comment by SumiranAgg** [comment] 2018-12-21 09:14
@jameshowe Sorry I missed it somehow. 
Can you share kudu trace. Visit kudu Url: https://tagdat-geodis-staging.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace
Try to find a file around below timestamp as per the logs shared:
"log_time":"2018-12-18T22:50:42.834369Z"
This might have more information about the failure. Please share that trace if possible.

**Comment by jameshowe** [comment] 2018-12-21 12:44
@SumiranAgg unfortunately I can't see any file for that date, I think the logging may only be enabled for last 24 hours as I can only see logs for today. FWIW I've had problems before deploying on Linux via Kudu Sync using v4.* (Preview), now that it's been fixed switching to v3 I'll switch back to v4 and post report back if it starts failing again.

**Comment by kmkumaran** [comment] 2019-05-10 12:47
@ian-a-anderson - can you please share the logs to RM_Customer_Queries at microsoft.com

**Comment by SumiranAgg** [comment] 2019-05-10 12:50
@ian-a-anderson Can you share more information? What package type are you deploying, which runtime stack is selected, what is the error message you see?

**Comment by ian-a-anderson** [comment] 2019-05-10 13:35
K, shared

**Comment by ian-a-anderson** [comment] 2019-05-10 13:40
@SumiranAgg We are deploying a PHP Zip file to Azure App Service for Linux on a Premium (P1V2) Linux App Service Plan. It fails during the Kudu Sync step while processing files: 

2019-05-08T04:06:36.2389539Z Command: "/home/site/deployments/tools/deploy.sh"
2019-05-08T04:06:36.2389838Z Handling Basic Web Site deployment.
2019-05-08T04:06:36.2390093Z Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot’
…
….
2019-05-08T04:06:36.2403894Z Processed 11560 files...
2019-05-08T04:06:36.2404111Z Processed 14025 files...
2019-05-08T04:06:36.2404338Z An unknown error has occurred. Check the diagnostic log for details.
2019-05-08T04:06:36.2478968Z ##[error]Failed to deploy web package to App Service.

Note that we deploy this exact same Zip file to identical (Premium P1V2) Windows instances without issue. This problem is intermittent, and specific to App Service For Linux deployments. We have seen this occur in multiple Azure Regions - so this isn't a flaky instance or zone-specific issue. It seems like a bug in the Azure App Service Deploy task itself, which only occurs on App Service For Linux deployments. Azure Support staff have mentioned that it appears to be causing a Docker Container restart, which is killing the deployment process.

**Comment by SumiranAgg** [comment] 2019-05-17 06:26
@ian-a-anderson  this seems like an issue on app service side. I have created a bug with Kudu team to investigate further #2972

**Comment by 20shivangi** [comment] 2019-06-13 05:25
@ian-a-anderson
Since this issue is being tracked on Kudu side, so closing this one.?
Also, if some other info is to added, the customer can directly add it here only projectkudu/kudu#2972

**Closed** 2019-06-13 05:25 UTC
Labels: Area: AzureAppService, Area: Release

**Comment by chtourou-youssef** [comment] 2021-07-09 08:38
i face the same error now

**Comment by nadesu** [comment] 2022-02-08 04:20
@PhilipsonJoseph @v-nagarajku - pls follow up with Product to prioritise this on AppService team

**Comment by trapgar** [comment] 2022-02-11 00:57
Reproduction Steps:
1. Create a new React app with `npx create-react-app my-app`
2. Add a GitHub actions workflow using the sample [node.js-webapp-on-azure.yml](https://github.com/Azure/actions-workflow-samples/blob/master/AppService/node.js-webapp-on-azure.yml)
3. Run the workflow to deploy to a Linux F1 Azure App Service

Unfortunately it does not seem to fail consistently - so I am unsure what causes it.

**Comment by dligthart** [comment] 2023-01-18 15:53
Experiencing a similar issue

**Comment by Tallies** [comment] 2023-02-07 07:32
Ditto. Consistently failing. :-(

**Comment by macgayverrosa** [comment] 2023-08-21 02:04
Facing the same issue... I tried to deploy a default Next js to azure web app
