### ISSUE TITLE
Powershell task copy-item command fails to copy subdirectory

### ISSUE THREAD

**Issue by veepee78** [microsoft/azure-pipelines-tasks#13456] opened 2020-08-21 09:34 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PowerShell  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
mediamaestro, maestrong, MaestroUK Devel

- Agent - Hosted or Private: 
    Private

    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Windows server 2019, 1809, ...1282

## Issue Description
Powershell task, copy-item command dismisses subdirectory. I captured temporary powershell file from agents temp directory containing the command, and it worked normally when run manually.
![image](https://user-images.githubusercontent.com/3069770/90874368-49c6d600-e3a8-11ea-823f-1b6e5e51e050.png)

source directory has structure ./assets/icons, assets directory can be seen in source, but not in destination in copy-item command verbose results

.
[Include task name(s), screenshots and any other relevant details]

### Task logs
[logs_107090.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5107971/logs_107090.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

When **run by agent, assets folder missing** from destination:
....
VERBOSE: Performing the operation "Copy Directory" on target "Item: 
E:\agent\_work\1\s\Maestro.NG.Web.TimeBooking\Maestro.NG.Web.TimeBooking.UI\dist\timebooking\assets Destination: 
\\mdevslweb\e$\devel\devel-uk.maestro.xo-timebooking\timebooking".
VERBOSE: Performing the operation "Create Directory" on target "Destination: 
\\mdevslweb\e$\devel\devel-uk.maestro.xo-timebooking\timebooking".
VERBOSE: Performing the operation "Copy Directory" on target "Item: 
E:\agent\_work\1\s\Maestro.NG.Web.TimeBooking\Maestro.NG.Web.TimeBooking.UI\dist\timebooking\assets\icons Destination: 
\\mdevslweb\e$\devel\devel-uk.maestro.xo-timebooking\timebooking\icons".
VERBOSE: Performing the operation "Create Directory" on target "Destination: 
\\mdevslweb\e$\devel\devel-uk.maestro.xo-timebooking\timebooking\icons".
VERBOSE: Performing the operation "Copy File" on target "Item: 
E:\agent\_work\1\s\Maestro.NG.Web.TimeBooking\Maestro.NG.Web.TimeBooking.UI\dist\timebooking\assets\icons\add.svg 
Destination: \\mdevslweb\e$\devel\devel-uk.maestro.xo-timebooking\timebooking\icons\add.svg".
....

**Manual run from powershell prompt:**

 .\f552c128-5a66-4cdc-8c19-226380b1c180.ps1
VERBOSE: Performing the operation "Copy Directory" on target "Item:
E:\agent\_work\1\s\Maestro.NG.Web.TimeBooking\Maestro.NG.Web.TimeBooking.UI\dist\timebooking\assets Destination:
\\mdevslweb\e$\devel\devel-uk.maestro.xo-timebooking\timebooking\assets".
VERBOSE: Performing the operation "Create Directory" on target "Destination:
\\mdevslweb\e$\devel\devel-uk.maestro.xo-timebooking\timebooking\assets".
VERBOSE: Performing the operation "Copy Directory" on target "Item:
E:\agent\_work\1\s\Maestro.NG.Web.TimeBooking\Maestro.NG.Web.TimeBooking.UI\dist\timebooking\assets\icons Destination:
\\mdevslweb\e$\devel\devel-uk.maestro.xo-timebooking\timebooking\assets\icons".
VERBOSE: Performing the operation "Create Directory" on target "Destination:
\\mdevslweb\e$\devel\devel-uk.maestro.xo-timebooking\timebooking\assets\icons".
VERBOSE: Performing the operation "Copy File" on target "Item:
E:\agent\_work\1\s\Maestro.NG.Web.TimeBooking\Maestro.NG.Web.TimeBooking.UI\dist\timebooking\assets\icons\add.svg
Destination: \\mdevslweb\e$\devel\devel-uk.maestro.xo-timebooking\timebooking\assets\icons\add.svg".
VERBOSE: Performing the operation "Copy File" on target "Item:
E:\agent\_work\1\s\Maestro.NG.Web.TimeBooking\Maestro.NG.Web.TimeBooking.UI\dist\timebooking\assets\icons\administratio
n.svg Destination: \\mdevslweb\e$\devel\devel-uk.maestro.xo-timebooking\timebooking\assets\icons\administration.svg".
VERBOSE: Performing the operation "Copy File" on target "Item:
E:\agent\_work\1\s\Maestro.NG.Web.TimeBooking\Maestro.NG.Web.TimeBooking.UI\dist\timebooking\assets\icons\back.svg
Destination: \\mdevslweb\e$\devel\devel-uk.maestro.xo-timebooking\timebooking\assets\icons\back.svg".
....

**Comment by ekaterina-tatanova** [comment] 2020-09-02 09:10
@veepee78 It seems like it's an [external](https://github.com/PowerShell/PowerShell/issues/7005) issue. What version of PowerShell do you use? Are you able to check if this issue is reproducible on MS-hosted agent?

**Comment by veepee78** [comment] 2020-09-02 15:05
powershell 5.1

Seems similar, but my command is much simplier. And as I told it works when run manually on the agent but not with the task.
Not sure, we have not used hosted agents.

**Comment by ekaterina-tatanova** [comment] 2020-09-03 10:49
@veepee78 It works correctly when the destination folder already exists both when you run manually and with the task. But when there's no destination folder, it misses the sub-directory 'assets' in both cases. Have you had the destination folder before running manually?

**Comment by veepee78** [comment] 2020-09-10 17:59
I'm pretty sure situation was same in both cases, no destination. I'd need to confirm that, but I already "fixed" the issue with copy task, it works as it should. Sorry for late reply, got the notification today..

**Comment by ekaterina-tatanova** [comment] 2020-09-11 09:04
@veepee78 Could you please confirm that situation was the same in both cases i.e. the destination folder has not been created before copy-item command?

**Comment by ekaterina-tatanova** [comment] 2020-09-22 11:40
@veepee78 Is it still actual for you? Could you confirm that this is reproducible when situation is the same in both cases?

**Comment by veepee78** [comment] 2020-09-23 07:13
@ekaterina-tatanova Hi, so this happens in both cases when the destination directory 'timebooking' does not exists. With powershell build task and directly with powershell command.

Confirmed working if only timebooking directory exists. (no subfolders)

**Comment by ekaterina-tatanova** [comment] 2020-09-23 09:12
Hi @veepee78, it looks like this is an external issue related to Powershell, and not related to pipeline task - since the behavior of the command is the same directly with powershell and via task. Here's also the related [issue](https://github.com/PowerShell/PowerShell/issues/7005) for Powershell - you can track progress about it here.
I'm going to close this issue currently since it's external. Please ping if you have any questions.

**Closed by ekaterina-tatanova** 2020-09-23 09:12 UTC
Labels: Area: ABTT, Task: PowerShell, bug
