### ISSUE TITLE
Consider re-using the evaluated key from the restore step in the save step instead of re-evaluating the key

### ISSUE THREAD

**Issue by svickers** [microsoft/azure-pipelines-tasks#11286] opened 2019-09-04 19:04 UTC
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Task Name**: CacheBeta@0

## Environment
- Azure Pipelines
- Account: Headset
- Team: Headset
- Build: Headset.POS
- Agent: Hosted
- Pool: Azure Pieplines
    
## Issue Description

Trying to use the cache task to help our nuget restore time but the logs always reflects a cache miss.  When checking the task at the beginning of the build vs. the one at the end, the cache keys are reporting different values.  The build task is configured like this:
```
- task: CacheBeta@0
  inputs:
    key: nuget | **/packages.lock.json
    path: $(NUGET_PACKAGES)
  displayName: Cache NuGet packages
```

#### Task: Cache Nuget Packages
```
Resolving key `nuget | **/packages.lock.json`...
File hashes summarized as `z0w2YHkCqjkbB2ltL7e9GwAD6bx01dqfPt6hVh9j11Y=` from BASE64(SHA256(`
SHA256(s\src\Adilas\packages.lock.json)=[40220]713FC01F5392BDB255D3A04617E7602F248A9C98B903C7E5E309D4E9231078E9
SHA256(s\src\BioTrackCloud.Adapter\packages.lock.json)=[41243]3DFD3C1A3EB383DDA126DDBAD01EA0FC82310827E3B51379FB9887F113B8EB3C

... <snip> ...
Resolved to `nuget|z0w2YHkCqjkbB2ltL7e9GwAD6bx01dqfPt6hVh9j11Y=`.
Information, Getting a pipeline cache artifact with one of the following fingerprints:
Information, Fingerprint: `nuget|z0w2YHkCqjkbB2ltL7e9GwAD6bx01dqfPt6hVh9j11Y=`
Information, There is a cache miss.

```

#### Task: Post-job Cache Nuget Packages
```
Resolving key `nuget | **/packages.lock.json`...
File hashes summarized as `SCSOreLx/rK7ttCrEPdodQXUx1dv6Keo38/hpsKpVxI=` from BASE64(SHA256(`
SHA256(s\src\Adilas\packages.lock.json)=[40220]713FC01F5392BDB255D3A04617E7602F248A9C98B903C7E5E309D4E9231078E9
SHA256(s\src\BioTrackCloud.Adapter\packages.lock.json)=[41243]3DFD3C1A3EB383DDA126DDBAD01EA0FC82310827E3B51379FB9887F113B8EB3C

... <snip> ...
Information, Creating a pipeline cache artifact with the following fingerprint: `nuget|SCSOreLx/rK7ttCrEPdodQXUx1dv6Keo38/hpsKpVxI=`
Information, Cache item created.
Information, Saved under the following scope: 46;d3c93ff9-ba7f-4eb7-bc0c-98a29bc7cee5;refs/heads/master;4d45157e-804a-444b-9e87-e5b8f20e21af
Saved item.

```

**Comment by johnterickson** [comment] 2019-11-04 21:16
@svickers thanks for the report! Are you able to extend the minimatch pattern with excludes? 
e.g.
```
**/packages.lock.json,!**/publish/packages.lock.json
```

**Comment by davidje13** [comment] 2019-11-05 08:36
from your reply on the other thread:

> It's more about being cautious/conservative. Imagine a build:
>
> 1. git clone pulls down packages.lock.json with hash X
> 2. cache task checks for cache key X based on packages.lock.json
> 3. package lock file is updated to Y
> 4. package restore happens
> 5. cache post-step runs; packages for lockfile Y are stored at key X 😨
> By evaluating the key at the same time as storing the cache entry we avoid the mismatch.

I disagree completely. The problem is that you are considering the hash as representing the contents of the cache, but the contents of the cache are not (and cannot) be known in advance when restoring. The hash *must* represent the state which created the contents.

Your current approach:

```
function pipeline(state):
  hash1 := selective_hash(state)
  if load_cache(hash1, state):
    continue(state)
  else
    prepare(state)
    continue(state)
    hash2 := selective_hash(state)
    save_cache(hash2, state)
```

This makes a lot of assumptions! You assume that both `prepare` (representing any build steps which are conditional on the cache restore not succeeding) and `continue` (representing the later build steps) not making any changes to the hashable part of the state. That means that `hash1` will not be correct unless those assumptions are met.

But if you change your view of what the hash represents, to instead be the state which generates a particular cached state, this becomes the more familiar (almost exactly matching a memoized function) and useful:

```
function pipeline(state):
  hash := selective_hash(state)
  if load_cache(hash, state):
    continue(state)
  else
    prepare(state)
    continue(state)
    save_cache(hash, state)
```

Even better (but perhaps not possible with the current architecture of pipelines) would be:

```
function pipeline(state):
  hash := selective_hash(state)
  if not load_cache(hash, state):
    prepare(state)
    save_cache(hash, state)
  continue(state)
```

since this represents exactly a memoized function.

**Comment by fadnavistanmay** [comment] 2019-11-06 18:49
Hi @svickers and @davidje13 - this was a design decision made to have a post-job for the cache step. Probably, the thing you are looking for is restoreKeys, something like.

```
> key: nuget | $(Agent.OS) | **package-lock.json
> restoreKeys: nuget | $(Agent.OS)
```
So, even though the package-lock.json hash has changed, you can do the restore, and then instead of skipping the nuget restore entirely, may be run the nuget restore step, but that should be super quick as most of the packages are already present.

Does this resolved the issue?

**Comment by davidje13** [comment] 2019-11-07 21:06
@fadnavistanmay for me, no. But the workaround johnterickson gave in the other thread already resolves my issue in a fairly acceptable way (though a proper fix would be better).

The problem with your proposed solution is that removed packages would remain present, so there is a chance for errors (either due to intentionally removed packages still being included or due to unintentionally removed packages not being detected as missing). Of course whether this is a problem depends on the particular package manager (npm / yarn / nuget / maven / etc. etc.), and whether the cache is of a shared system-level cache, or of the actual resolved dependencies for a project. It also has the disadvantage that unless pruned occasionally, it will grow indefinitely in size, eventually slowing builds down due to the sheer size of the download / processing.

Since this is a design decision you've already made I don't expect to change your mind, though I think it could be significantly more useful and easier to use (and applicable to more situations) if switched.

**Comment by johnterickson** [comment] 2019-11-07 22:10
@davidje13 I am glad you are unblocked and I also want to call out that I really appreciate the thought and thorough description you've provided in this issue.  

I'm pretty busy at the moment, but I want to leave this issue open so I can come back and read through it carefully.

**Comment by fadnavistanmay** [comment] 2020-03-12 21:02
The change which throws a warning when the key is post job task has been merged. IIRC we decided against making change in the behavior. John, we can re-evaluate this if need be, closing the issue as of now.

**Closed by fadnavistanmay** 2020-03-12 21:02 UTC
Labels: Area: ArtifactsCore, Area: PipelineCaching, enhancement

**Comment by stuartdga** [comment] 2020-09-01 12:24
I agree with @davidje13. I have also found your approach to be extremely frustrating. For one thing, it just isn't documented. For another, it's counter-intuitive. @fadnavistanmay & @johnterickson I would like the cache to be created and to be resolved correctly to what is brought down from git initially. All that I am doing between the cache step and the post-cache step is just a restore and build. There is no way that I can ascertain to ever get rid of this warning. @johnterickson I tried the pattern matching string to exclude the publish folder but that didn't seem to work.

key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/publish/packages.lock.json'

**Comment by rkm** [comment] 2021-01-09 17:53
Hello, I'm facing the same issue at the moment. From the docs: "The contents of any file identified by a file path or file pattern is hashed to produce a dynamic cache key. This is useful when your project has file(s) that uniquely identify what is being cached." -- when the opposite is true though (i.e. no file that uniquely identifies the cache contents), then updating the cache contents for a given key doesn't seem possible.

Specifically, I'm following the suggested pattern for caching [docker images](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#docker-images). I have a docker-compose file as part of the hash key, but this is static since I'm using `foo:latest` for all my images. In order to always test against the latest images, I have a task after the cache restore which pulls any newer image versions and re-creates `cache.tar` if needed. Currently though, I'm not sure how I can indicate to the "save cache" step that the data restored from the **initial cache key** have changed.

Any suggestions?

**Comment by davidje13** [comment] 2021-01-09 19:26
@rkm I don't believe such a thing would be possible; neither with the current caching strategy nor with the proposed change. You would need a system which is able to update/replace an existing non-expired cache item, which isn't the intent of this task.

In general, using `:latest` is not recommended for docker images because it makes it harder to distinguish which version was used in a build (i.e. it makes them non-repeatable). Suppose you need to re-run an old build (for rollback, diagnostic, audit, etc.); if it is using a docker image of `:latest` you will pull in a more recent version of that dependency than the original build expected. At best a discrepancy and at worst a breaking change. For similar reasons this also means teams working on different branches simultaneously are more likely to encounter problems where they pull in each other's builds by mistake.

My personal recommendation to you would be to look in to some automated system for updating your docker-compose image versions and making a commit to the codebase. Then you will get repeatable builds and correct caching (again with both the existing and proposed system here). In my experience this is a pretty common setup (often with images tagged according to their Git SHA rather than semantic versions).

If you really must use `:latest`, you could always just build your own cache system by uploading results into any file storage and downloading them at the start of the next build. The situation is much simpler because you don't need most of the usual caching logic. I don't recommend doing this but it is an option.

**Comment by rkm** [comment] 2021-01-09 20:46
Thanks for the quick reply. I see your point about this task not updating existing caches, so looks like I'll have to change my workflow. I'm aware of the pitfalls of `latest` - you're correct that the best solution would be to pin versions and have an auto-update process.
