### ISSUE TITLE
Configure SQL Server Auditing using ARM templates 

### ISSUE THREAD

**Issue by Naidul** [Microsoft/azure-pipelines-tasks#8984] opened 2018-12-03 13:13 UTC
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by vineetmimrot** [comment] 2018-12-04 07:31
@Naidul : You should see the operation progress bar in Azure Portal under the _resource group -> deployment_. Make sure the template you are using is in good state or you can get the template from azure portal itself under _Automation Options_. If the process ends in Azure, and the task doesn’t stop – let us know.

**Comment by Naidul** [comment] 2018-12-04 08:00
Hi Vineet,

Thanks for your response
By using azure portal we are able to enable that sql auding option. 

while deploying through ARM template we are getting this issue.
Please find the below  template what we are using
Template

{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "serverName": {
            "type": "string",
			"defaultValue": "dbservername",
            "metadata": {
                "description": "The name of the new database server to create."
            }
        },
        "serverLocation": {
            "type": "string",
			"defaultValue": "server location",
            "metadata": {
                "description": "The location of the database server."
            }
        },
        "administratorLogin": {
            "type": "string",
			"defaultValue": "dbuser",
            "metadata": {
                "description": "The account name to use for the database server administrator."
            }
        },
        "administratorLoginPassword": {
            "type": "securestring",
			"defaultValue": "password",
			"metadata": {
                "description": "The password to use for the database server administrator."
            }
        },
        "databaseName": {
            "type": "string",
			"defaultValue": "databaseName",
            "metadata": {
                "description": "The name of the new database to create."
            }
        },
        "collation": {
            "type": "string",
            "defaultValue": "SQL_Latin1_General_CP1_CI_AS",
            "metadata": {
                "description": "The database collation for governing the proper use of characters."
            }
        },
        "edition": {
            "type": "string",
            "defaultValue": "Basic",
            "metadata": {
                "description": "The type of database to create. The available options are: Web, Business, Basic, Standard, and Premium."
            }
        },
        "maxSizeBytes": {
            "type": "string",
            "defaultValue": "1073741824",
            "metadata": {
                "description": "The maximum size, in bytes, for the database"
            }
        },
        "requestedServiceObjectiveName": {
            "type": "string",
            "defaultValue": "Basic",
            "metadata": {
                "description": "The name corresponding to the performance level for edition. The available options are: Shared, Basic, S0, S1, S2, S3, P1, P2, and P3."
            }
        },
        "eventTypesToAudit": {
            "type": "string",
            "defaultValue":"All",
            "metadata": {
                "description": "The event type to audit."
            }
        }
    },
    "resources": [
        {
            "name": "[parameters('serverName')]",
            "type": "Microsoft.Sql/servers",
            "location": "[parameters('serverLocation')]",
            "apiVersion": "2014-04-01-preview",
            "properties": {
                "administratorLogin": "[parameters('administratorLogin')]",
                "administratorLoginPassword": "[parameters('administratorLoginPassword')]",
                "version": "12.0"
            },
            "resources": [
                {
                    "name": "[parameters('databaseName')]",
                    "type": "databases",
                    "location": "[parameters('serverLocation')]",
                    "apiVersion": "2014-04-01-preview",
                    "dependsOn": [
                        "[concat('Microsoft.Sql/servers/', parameters('serverName'))]"
                    ],
                    "properties": {
                        "edition": "[parameters('edition')]",
                        "collation": "[parameters('collation')]",
                        "maxSizeBytes": "[parameters('maxSizeBytes')]",
                        "requestedServiceObjectiveName": "[parameters('requestedServiceObjectiveName')]"
                    },
					 "resources": [
					 {
                    "apiVersion": "2014-04-01-preview",
                    "type": "auditingPolicies",
                    "name": "Defaultauditing",
					"dependsOn": [
                        "[concat('Microsoft.Sql/servers/', parameters('serverName'))]",
                        "[concat('Microsoft.Sql/servers/', parameters('serverName'), '/databases/',parameters('databaseName'))]"
					      
                    ],
                    "properties": {
                        "auditingState": "Enabled",
                        "storageAccountName": "storageaccountName",
                        "storageAccountKey": "< storageAccountKey >",
                        "storageAccountResourceGroupName": "resource group name",
                        "storageAccountSubscriptionId": "subscription ID",
                        "eventTypesToAudit": "parameters('eventTypesToAudit')"
                    }
                }
				]
                },
				                {
                    "apiVersion": "2014-04-01-preview",
                    "dependsOn": [
                        "[concat('Microsoft.Sql/servers/', parameters('serverName'))]"
                    ],
                    "location": "[parameters('serverLocation')]",
                    "name": "AllowAllWindowsAzureIps",
                    "properties": {
                        "endIpAddress": "0.0.0.0",
                        "startIpAddress": "0.0.0.0"
                    },
                    "type": "firewallrules"
                }
                
            ]
        }
    ]
}


Regards,
Naidu

**Comment by vineetmimrot** [comment] 2018-12-04 08:30
@Naidul Have you tried to deploy the same arm template schema using Azure Portal _Automation Option_?

**Comment by Naidul** [comment] 2018-12-04 09:16
NO

**Comment by vineetmimrot** [comment] 2018-12-04 09:35
Please try it there first as it will confirm if there is any error in ARM template. Or better get the sample ARM template under automation option. The AzureResourceGroupDeployment task has responsibility for just deploying the ARM template. If you found any issue with the ARM template, please check with SQL team.

**Comment by Naidul** [comment] 2018-12-04 10:54
while deploying the ARM Template trough Azure Portal Automation  Option, 
we are getting the below error

{
  "code": "InternalServerError",
  "message": "An error has occurred while saving Auditing settings, please try again later",
  "target": null,
  "details": [],
  "innererror": []
}

Please suggest me

**Comment by vineetmimrot** [comment] 2018-12-04 12:31
I may not be the right person to help for this error. Better you try again or can check with Azure/SQL team.

**Comment by vineetmimrot** [comment] 2018-12-06 08:53
I think this issue is related to Azure Template, thus I am closing this issue. Please revert back in case you found template deployment is working fine but the issue is happening with AzureResourceGroupDeployment Task.

**Closed by vineetmimrot** 2018-12-06 08:53 UTC
Labels: Area: Release
