### ISSUE TITLE
HelmInstaller: Support Helm 3

### ISSUE THREAD

**Issue by bkaid** [microsoft/azure-pipelines-tasks#11316] opened 2019-09-11 02:52 UTC
Helm 3 is now in [beta](https://helm.sh/blog/helm-v3-beta/). Specifying `helmVersionToInstall: 3.0.0-beta.3` properly installs Helm 3 as expected, but since `helm init` (and Tiller) have been deprecated in v3, I get an error: `Error: unknown flag: --client-only`.  My current workaround is to do `continueOnError: true` but it leaves every build result marked as Warning. It would be great to get proper Helm 3 support.  Perhaps Helm could be verified inside [helmtooinstaller.ts](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/HelmInstallerV1/src/helmtoolinstaller.ts#L21) using `helm version` instead (though that may cause issues with Helm 2 if `--client-only` isn't specified).

## Required Information

**Question, Bug, or Feature?**  
*Type*: Bughancement

**Enter Task Name**: HelmInstaller@1

## Environment
- Server: Azure Pipelines
    
- Agent: Hosted (ubuntu-16.04)

### Task logs
```
Starting: Helm install
==============================================================================
Task         : Helm tool installer
Description  : Install Helm on an agent machine
Version      : 1.155.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/helm-installer
==============================================================================
Downloading: https://get.helm.sh/helm-v3.0.0-beta.3-linux-amd64.zip
Extracting archive
sr/bin/unzip /home/vsts/work/_temp/helm-v3.0.0-beta.3-e253d2bf-3c0f-46bd-8297-a3e7764250ab.zip
Archive:  /home/vsts/work/_temp/helm-v3.0.0-beta.3-e253d2bf-3c0f-46bd-8297-a3e7764250ab.zip
   creating: linux-amd64/
  inflating: linux-amd64/LICENSE     
  inflating: linux-amd64/helm        
  inflating: linux-amd64/README.md   
Caching tool: helm 3.0.0-beta.3 x64
Prepending PATH environment variable with directory: /opt/hostedtoolcache/helm/3.0.0-beta.3/x64/linux-amd64
Verifying helm installation...
pt/hostedtoolcache/helm/3.0.0-beta.3/x64/linux-amd64/helm init --client-only
Error: unknown flag: --client-only
##[error]Error: The process '/opt/hostedtoolcache/helm/3.0.0-beta.3/x64/linux-amd64/helm' failed with exit code 1
Finishing: Helm install

```

**Comment by shashankbarsin** [comment] 2019-10-04 16:56
Valid feedback. @Anumita let's address this

**Comment by spowser** [comment] 2019-11-06 20:08
I see this listed as an enhancement but the expected behavior vs actual behavior feels more like a bug.  If the task is to install the Helm Client version 3, the expected behavior is to install and mark the step as passed.

**Comment by jldeen** [comment] 2019-11-13 04:42
@spowser and @bkaid I just pushed PR #11735 to hopefully resolve this issue ASAP. However, while we wait, I wrote a [blog post](https://jessicadeen.com/using-helm-3-with-azure-devops/) about a work around, if it helps at all.

@shashankbarsin and @Anumita can we get a review of the PR when you have free moment? Thanks!

**Comment by shashankbarsin** [comment] 2019-11-15 13:43
@jldeen during testing we found that there was a minor issue with https://github.com/microsoft/azure-pipelines-tasks/pull/11735 because of which the task was timing out. The missing 'v' before 2 in the condition check was causing that issue.

@Anumita has fixed this in https://github.com/microsoft/azure-pipelines-tasks/pull/11769/files. This has been tested. She's merged this to m160 as well via https://github.com/microsoft/azure-pipelines-tasks/pull/11771. Waiting for the changes to be deployed.

**Closed by shashankbarsin** 2019-11-15 13:43 UTC
Labels: Area: Release, enhancement

**Comment by jldeen** [comment] 2019-11-15 14:09
@shashankbarsin Thank you for the update! Good catch on the `v` - I made an assumption the code had `v` baked in and the task just used the numbers. Thanks @Anumita for fixing this and getting this pushed into m160 ASAP. Will keep posted until the changes are live in all rings.

**Comment by azooinmyluggage** [comment] 2019-11-15 16:19
Thanks @jldeen

**Comment by tanwarsatya** [comment] 2019-11-16 13:52
Looks like it’s fixed now
