### ISSUE TITLE
Azure CLI task - "Fail on Standard Error" issue

### ISSUE THREAD

**Issue by cielakm** [microsoft/azure-pipelines-tasks#12143] opened 2020-01-14 15:46 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureCLIV2

## Environment
Azure DevOps Hostes, Self-hosted
Local laptop

## Issue Description

Issue when running Azure CLI v.2
When running powershell script with az cli commands and selecting "Fail on Standard Error" the task will always fail.

The issue is with cmd.exe running powershell az command as this will always give strerr stream even if the command is successfull.

Refer to this link for more info
https://github.com/microsoft/knack/issues/166#issuecomment-542644809

### Task logs

command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'F:\DHOpsAgent2\_work\_temp\azureclitaskscript1579009614399.ps1'"
2020-01-14T13:47:10.4101529Z 
2020-01-14T13:48:23.0578599Z ##[error]Script failed with error: Error: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed because one or more lines were written to the STDERR stream

### Error logs

az : 
At line:1 char:1
+ az aks update -n aks -g IaC --attach-acr acr1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
AAD role propagation done[############################################]  100.0000%

**Comment by hiyadav** [comment] 2020-01-16 08:54
@cielakm for such commands, should you uncheck `Fail on Standard Error` as the script will then fail only if the exit code of script is non zero.

**Comment by cielakm** [comment] 2020-01-16 10:58
@hiyadav if I uncheck `Fail on Standard Error` task will always be successful even when `az cli` command will fail.

**Comment by hiyadav** [comment] 2020-01-16 11:00
If a command is unsuccessful, it should return a non zero exit code. If a command isn't following this convention, we should raise a concern there, as we expect a failed script/command to exit with non zero exit code.

**Comment by cielakm** [comment] 2020-01-16 11:08
If I use a batch inline rather then powershell or powershell core the behaviour is correct of the az cli command. This is not an issue with az cli but rather how the error stream is interpreted. As this is Azure Cli task it should handle this correctly. The Az command is written in python and it's behaviour is to produce an output to strout and strerr regardless of success or failure of the command. This is why it is causing an issue with a Azure DevOps task

**Comment by cielakm** [comment] 2020-02-03 17:13
As a workaround to the issue this can be resolved by adding
`if (!$?){Throw}` strait after az command. This will look at the last success or failure of previous command and throws error if it fails.

Basted on the article https://rajbos.github.io/blog/2019/07/12/Azure-CLI-PowerShell

**Comment by jalajmsft** [comment] 2020-02-04 04:54
Hey @cielakm, thank you for pointing this issue out and for providing the workaround.

The following az command `az aks update -n aks -g IaC --attach-acr acr1` writes the progress to stderr hence `Fail on Standard Error` will always result in failure of the task. 

For such commands present in the script, the ideal way is to rely on the exit code. Unfortunately, the exit code of the last command executed was not surfaced back for PowerShell scenarios and this resulted in success of the task. We have made a fix for the same.

**Comment by jalajmsft** [comment] 2020-02-04 13:19
This is fixed and will be deployed to all rings by next week.

Closing this for now. Feel free to re-open for further queries.

**Closed by jalajmsft** 2020-02-04 13:19 UTC
Labels: Area: Release, bug

**Comment by ronnetzer** [comment] 2021-03-03 07:24
@jalajmsft Hi,
Im experiencing the same issue when running AzureCli@2 with an inline bash script that uses `az storage copy`
Recently I had authentication issues caused by some expired keys of my service principal and the copy failed with the error:
```
failed to perform copy command due to error: Login Credentials missing. No SAS token or OAuth token is present and the resource is not public
ERROR: Failed to perform copy operation.
```

but the task completed successfully without any error

**Comment by bpred754** [comment] 2021-06-21 20:34
@ronnetzer I am experiencing the same thing. Did you find a solution?
