### ISSUE TITLE
New function apps not appearing in Azure devops pipeline release under App Service name

### ISSUE THREAD

**Issue by benwarrick** [microsoft/azure-pipelines-tasks#17216] opened 2022-11-16 15:17 UTC
I'm seeing this issue: https://developercommunity.visualstudio.com/t/cant-find-App-Service-name-azure-devops/1651959?q=app+service+name

I add a function app to a Resource Group, but when I create the release pipeline, using "Deploy Azure Function App", the new function app doesn't appear in the "App service name" list. Sometimes it appears later, like after an hour. But right now I have one I created yesterday, and it still hasn't appeared, 12 hours later. I can see the other function apps in the Resource Group, just not the new one.

**Comment by FinVamp1** [comment] 2022-12-07 03:24
Hello, we have seen a number of reports of this issue but have not been able to track down this issue. If there are more details you can provide privately then let me know and we can arrange a communication?

**Comment by FinVamp1** [comment] 2023-01-25 18:17
Update - I think I have a way to repro this and I will investigate changes that will help.

**Comment by raydexis** [comment] 2023-02-17 10:03
I am also having the issue for a long time with app services as well. Steps to reproduce:
- Make sure there is an existing release definition with app service (e.g. windows)
- Create a new app service (linux)
- Try to edit release via selecting proper values from dropdowns
- You won't be able to see the lately created linux app service right away. 
- If you wait a period of time, you will be seeing the new app service in the list

**Comment by FinVamp1** [comment] 2023-03-17 17:33
Hello, I am checking with the Azure Resource Manager team on this issue. This is a duplicate of https://github.com/microsoft/azure-pipelines-tasks/issues/16729 so I will close this one and please follow the discussion there.

**Closed by FinVamp1** 2023-03-17 17:33 UTC
Labels: Area: Release, triage, Task: AzureFunction
