### ISSUE TITLE
Build Definition can not work anymore after its task group is being deleted.

### ISSUE THREAD

**Issue by Itfly** [Microsoft/azure-pipelines-tasks#6847] opened 2018-04-02 04:32 UTC
## Environment
- Server - VSTS 
        
account name: businessai.visualstudio.com
build definiton name: "Produce Cdssm sdk"

## Issue Description

One of my team member deleted the task group "Producing Nuget Packge" by accident. So all the referenced build definition can not work because of the missing task group. I created a new task group and replace it in these build definitons. However the build definitons can not be saved with the below error:

`Task group aa39d96b-bf5d-49ba-b090-f4099f2e37ed not found.
`
This is the deleted task group, but i think i just remove all the reference with this task group. Why the build definition still does not work?

### Error logs

Task group aa39d96b-bf5d-49ba-b090-f4099f2e37ed not found.

**Comment by michVSTS** [comment] 2018-04-03 17:28
Hello Itfly,

Are you still seeing this issue? I started looking at the build definition in question ("Produce Cdssm sdk"), and it looks like it has been changed as of this morning. That being said, I did not see reference to the Task Group in question in its history, I have found reference to that task group in two other definitions, Are you still encountering issues with those definitions as well, or have you just not changed them yet? Also, the ID provided seems to be referring to a task related to testing something, not "Producing Nuget Package" as far as I can tell. That Task Group (aa39d96b-bf5d-49ba-b090-f4099f2e37ed) was deleted however. I did not find any definition references to a task group labeled "Producing Nuget Packge." It's possible that I am missing something, or the data is just deleted however, so can you confirm if you still are seeing this issue with your definitions, and if so, which definitions are still causing the issues?

Thank you for your time.

**Comment by Itfly** [comment] 2018-04-04 09:04
@michVSTS We just removed that build definition. But this can be reproductive.

**Comment by harshil93** [comment] 2018-04-04 12:07
I can confirm this is a regression. It used to work earlier in this scenario but something has changed in our side. We will fix it soon.

**Comment by moswald** [comment] 2018-11-15 23:01
This was fixed at some point since last April. Closing.

**Closed by moswald** 2018-11-15 23:01 UTC
Labels: Area: Build
