### ISSUE TITLE
CacheBeta task should use same hash for writing as reading

### ISSUE THREAD

**Issue by davidje13** [microsoft/azure-pipelines-tasks#11535] opened 2019-10-09 13:51 UTC
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Pipeline caching

## Environment
- Server - Azure Pipelines

- Agent - Hosted 
    - If using Hosted agent, provide agent queue name: Hosted Ubuntu 1604

## Issue Description

I have the following task:

```
- task: CacheBeta@0
  inputs:
    key: '"nuget" | $(Agent.OS) | api/**/packages.lock.json'
    path: $(NUGET_PACKAGES)
    cacheHitVar: NUGET_CACHE_RESTORED
    displayName: Load cached NuGet packages
```

But I observe that the read reports the following:

> ```
> Resolving key: "nuget"|Linux|api/**/packages.lock.json
> - "nuget" [string] - Linux [string]
> - api/**/packages.lock.json [file pattern; matches: 4]
> - s/api/API.Tests/packages.lock.json --> A8CAB4F0AD7479BCB9EFE8C66E84BF82F05D17DD0896BC00D3F7420D5C47056E
> - s/api/API/packages.lock.json --> 206EFEDBFF07BC6F936B70FF68BAF0960F666F71F74727FE67EF6EAC11A6BFB0
> - s/api/Extra.Tests/packages.lock.json --> E77DA7DD8471D16FC891281BD10E6F7CB646E6E154FF073115DD9DD23E422F8A
> - s/api/Extra/packages.lock.json --> 7EDEE1E7FA28AC65E4AAD79FAD03E0D392A1A4F2DB145708F95481AA2B2F7A2F
> Resolved to: "nuget"|Linux|OqFzAm/ugg5kvG7GKzb1lJvFLAMwMOSaNBsKAmcZW4M=
> Information, Getting a pipeline cache artifact with one of the following fingerprints:
> Information, Fingerprint: `"nuget"|Linux|OqFzAm/ugg5kvG7GKzb1lJvFLAMwMOSaNBsKAmcZW4M=`
> Information, There is a cache miss.
> ```

Whereas write discovers extra package.lock.json files, since it runs after a build has happened:

> ```
> Resolving key: "nuget"|Linux|api/**/packages.lock.json
> - "nuget" [string]
> - Linux [string]
> - api/**/packages.lock.json [file pattern; matches: 8]
> - s/api/API.Tests/packages.lock.json --> A8CAB4F0AD7479BCB9EFE8C66E84BF82F05D17DD0896BC00D3F7420D5C47056E
> - s/api/API/bin/Release/netcoreapp2.2/publish/packages.lock.json --> 206EFEDBFF07BC6F936B70FF68BAF0960F666F71F74727FE67EF6EAC11A6BFB0
> - s/api/API/bin/e2e/packages.lock.json --> 206EFEDBFF07BC6F936B70FF68BAF0960F666F71F74727FE67EF6EAC11A6BFB0
> - s/api/API/packages.lock.json --> 206EFEDBFF07BC6F936B70FF68BAF0960F666F71F74727FE67EF6EAC11A6BFB0
> - s/api/Extra.Tests/packages.lock.json --> E77DA7DD8471D16FC891281BD10E6F7CB646E6E154FF073115DD9DD23E422F8A
> - s/api/Extra/bin/Release/netcoreapp2.2/publish/packages.lock.json --> 7EDEE1E7FA28AC65E4AAD79FAD03E0D392A1A4F2DB145708F95481AA2B2F7A2F
> - s/api/Extra/bin/e2e/packages.lock.json --> 7EDEE1E7FA28AC65E4AAD79FAD03E0D392A1A4F2DB145708F95481AA2B2F7A2F
> - s/api/Extra/packages.lock.json --> 7EDEE1E7FA28AC65E4AAD79FAD03E0D392A1A4F2DB145708F95481AA2B2F7A2F
> Resolved to: "nuget"|Linux|aIu4eLjJkbtgu4nrS5izpJJozGhDs3bgtPnU2ntdpAA=
> Information, Getting a pipeline cache artifact with one of the following fingerprints:
> Information, Fingerprint: `"nuget"|Linux|aIu4eLjJkbtgu4nrS5izpJJozGhDs3bgtPnU2ntdpAA=`
> ```

Obviously this leads to cache misses every time.

I have tried to change the key to `'"nuget" | $(Agent.OS) | api/*/packages.lock.json'`, but this fails (no files match the path). This is a valid query when I run it using bash's globbing, but seems to fail here for some reason (maybe just not supported syntax? I see in the code that globbing support has been hand-crafted)

The hash calculated when checking the cache should be re-used when writing it. It does not make sense to recalculate the hash after changes have been made, since the point of caching is to snapshot the results of a pure function (in this case installing dependencies).

Originally raised [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops)

**Comment by johnterickson** [comment] 2019-11-04 21:03
@davidje13 - thanks for your feedback. I think you'll want something along the lines of:
```
api/**/packages.lock.json,!api/**/publish/packages.lock.json
```

@fadnavistanmay Can you point to the docs for the minimatch we used?

**Comment by johnterickson** [comment] 2019-11-04 21:15
Dupe of #11286

**Closed by johnterickson** 2019-11-04 21:15 UTC
Labels: Area: ArtifactsCore, Area: PipelineCaching, bug

**Comment by davidje13** [comment] 2019-11-04 21:36
Good to know about the option for removing some files from the match. Is that mentioned in the documentation? I don't remember seeing it (or a reference to another page which lists the full syntax if it's shared)

I think it is an important feature for a cache to base itself on the initial state, rather than the final state, for consistency. I can see this being a problem in many other use cases. The workaround you mention is good here, but I expect it will catch out many users and may not always be viable (e.g. if part of the build process changes one of the files, as `npm` used to do until recently).

Is there some technical reason why it isn't using a consistent hash at both stages of the build?

**Comment by johnterickson** [comment] 2019-11-04 22:52
@davidje13 It's more about being cautious/conservative. Imagine a build:

1. git clone pulls down packages.lock.json with hash X
2. cache task checks for cache key X based on packages.lock.json
3. package lock file is updated to Y
4. package restore happens
5. cache post-step runs; packages for lockfile Y are stored at key X 😨

By evaluating the key at the same time as storing the cache entry we avoid the mismatch.

On thing we have considered is a having an optional mode where the user has to manually add both restore and save steps to the YAML.  With such an option it could be possible to have another option to inherit the evaluated cache key from the first step.

@fadnavistanmay note: we should probably have a warning if the cache key changes for the above reasons - people will wonder why they are getting misses.

**Comment by johnterickson** [comment] 2019-11-04 22:52
Oops @davidje13  let's move the conversation over to https://github.com/microsoft/azure-pipelines-tasks/issues/11286 which is still open
