### ISSUE TITLE
Publish multiple code coverage files results in wrong code coverage summary sometimes

### ISSUE THREAD

**Issue by nigurr** [microsoft/azure-pipelines-tasks#9581] opened 2019-02-14 09:41 UTC
https://github.com/Microsoft/vstest/issues/981#issuecomment-433896495

**Comment by acesiddhu** [comment] 2019-05-21 15:12
Latest on this one is that we are re architecture the coverage merge. Most of the code changes are done and there are few changes that are currently pending before we can role out that broadly. I will update this thread once done

**Comment by RamiSh** [comment] 2019-06-05 12:32
Hey, any updates on the roll out?

**Comment by steinmr** [comment] 2019-06-05 16:31
Also, in what version of DevOps/TFS Server will this be available?

**Comment by RamiSh** [comment] 2019-06-19 00:10
Hi -- any updates on the release?

**Comment by acesiddhu** [comment] 2019-06-19 03:37
Hi all
the update is in progress. In the meantime can share the response of this rest api
https://<accountName>.visualstudio.com/CCI/_apis/test/CodeCoverage?buildId=<buildId>&flags=1

**Comment by RamiSh** [comment] 2019-07-01 14:04
> https://.visualstudio.com/CCI/_apis/test/CodeCoverage?buildId=&flags=1

Fyi -- Page not found

**Comment by acesiddhu** [comment] 2019-07-01 14:12
Rami

Can u add account name before .visualstudio.com

And try

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by acesiddhu** [comment] 2019-07-01 14:51
All,

Thanks for the patience. we actually rolled out the new arch job to few scale units and found some issues because of which this took time. the latest on this is that we have rolled out the new merge to more than half of the scale units with all the fixes (including top three scale units which use the code coverage merge job the most). The rollout to remaining scale units should complete mostly by this week

If folks are interested to know if this has reached their account please do mail me the the account name at this address "devops_tools AT microsoft DOT com" and i will confirm over email.

The reason why i asked about rest apis output is because we also fixed a small issue recently which we wanted to confirm is the latest most of the folks are hitting.

Also do let me know if any of you have stopped seeing this issue since sometime last week (or even today). That would help us validate the changes.

**Comment by MaciejWierzchowski** [comment] 2019-07-01 14:56
Will those fixes be available to on premise TFS Server?

**Comment by acesiddhu** [comment] 2019-07-01 15:02
@MaciejWierzchowski these changes wont make to TFS 2019 Update 1 given that we need baked time with these big changes in AzureDevops first. Once this is enabled everywhere and we have gotten sufficient baked time with the changes we will push this to next release of on prem. Can you reach out to me "devops_tools AT microsoft DOT com" I have few workarounds which we can try even now.

**Comment by acesiddhu** [comment] 2019-07-08 09:36
Hi folks
the new merge is enabled on all scale units. do let us know if the issue is fixed now. if the issue still persist please drop me a mail (devops_tools AT microsoft DOT com) with account name, build id where it occurred

**Comment by steinmr** [comment] 2019-07-09 09:31
With the help of Siddhartha Pandey at Microsoft, I have create a task group that works around the problem (see attached file)

In short, first publish code coverage for a fake/irrelevant test (using this task group) and then do your normal publishing using "dotnet test" on your normal tests. Please let me know if there are any feedback on this task group.

[Build_ Publish mock test to workaround bug in TFS 2018.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3372262/Build_.Publish.mock.test.to.workaround.bug.in.TFS.2018.zip)

**Comment by acesiddhu** [comment] 2019-07-10 04:13
Hi all
I am resolving the issue now. let me know if you are still hitting the issue. you can reach us at devops_tools AT microsoft DOT com with account name and build id where this issue reproed.

**Closed by acesiddhu** 2019-07-10 04:13 UTC
Labels: Area: Test, bug

**Comment by gremlm** [comment] 2019-07-10 17:22
Will this fix work under _vstest.console.exe /Enablecodecoverage_  ?
We need to create .coverage file  for solution with multiple projects and later translate it to xml.
Execution of the _vstest.console.exe /Enablecodecoverage_  creates a new _.coverage_ file in random directory, so this _.coverage_ file  is impossible to specify as argument for _CodeCoverage analyze_.
We have tried to start _vstest.console.exe_ under CodeCoverage, like the following 
_CodeCoverage collect /output:.\TestOut\VisualStudio4.coverage  /vstest.console.exe test1.dll test2.dll /ResultsDirectory:.\TestOut_.
This create VisualStudio4.coverage file in directory .\TestOut, but execution of the 
_CodeCoverage analyze /output:.\TestOut\VisualStudio4.coverage.xml_ generate an empty output  like

> \<?xml version="1.0" encoding="UTF-8" ?>
\<results>
\</results>
>
Some interesting observation: size of the file generated through _vstest.console.exe /Enablecodecoverage_  _.coverage_ file is much bigger than than _.coverage_ file generated through _CodeCoverage collect ..._ (3,111Kb vs 54Kb)
