### ISSUE TITLE
PR jobs failed to Extract Files because of rmRF: rm: could not remove directory error

### ISSUE THREAD

**Issue by rghodki** [microsoft/azure-pipelines-tasks#11297] opened 2019-09-05 22:00 UTC
Extract files task failed because of following error. PR details - https://dev.azure.com/dynamicscrm/OneCRM/_build/results?buildId=5203044

##[section]Starting: Extract files 
==============================================================================
Task         : Extract files
Description  : Extract a variety of archive and compression files such as .7z, .rar, .tar.gz, and .zip
Version      : 1.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/extract-files
==============================================================================
Found: 1 files to extract:
C:\Agents\BuildAgent\_workap\1\a\CDSBinaries\CDSBinaries.zip
Cleaning destination folder before extraction: C:\Agents\BuildAgent\_workap\1\s\bin
rm: could not remove directory (code EBUSY): C:\Agents\BuildAgent\_workap\1\s\bin/Debug/Microsoft.Crm.Extensibility.IntegrationTests.ODataV4

rm: could not remove directory (code EBUSY): C:\Agents\BuildAgent\_workap\1\s\bin/Debug/Microsoft.Crm.Extensibility.IntegrationTests.ODataV4
rm: could not remove directory (code ENOTEMPTY): C:\Agents\BuildAgent\_workap\1\s\bin/Debug

rm: could not remove directory (code EBUSY): C:\Agents\BuildAgent\_workap\1\s\bin/Debug/Microsoft.Crm.Extensibility.IntegrationTests.ODataV4
rm: could not remove directory (code ENOTEMPTY): C:\Agents\BuildAgent\_workap\1\s\bin/Debug
rm: could not remove directory (code ENOTEMPTY): C:\Agents\BuildAgent\_workap\1\s\bin

rm: could not remove directory (code ENOTEMPTY): C:\Agents\BuildAgent\_workap\1\s\bin/Debug
rm: could not remove directory (code ENOTEMPTY): C:\Agents\BuildAgent\_workap\1\s\bin

Error: Failed rmRF: rm: could not remove directory (code EBUSY): C:\Agents\BuildAgent\_workap\1\s\bin/Debug/Microsoft.Crm.Extensibility.IntegrationTests.ODataV4
rm: could not remove directory (code ENOTEMPTY): C:\Agents\BuildAgent\_workap\1\s\bin/Debug
rm: could not remove directory (code ENOTEMPTY): C:\Agents\BuildAgent\_workap\1\s\bin

##[error]Failed rmRF: rm: could not remove directory (code EBUSY): C:\Agents\BuildAgent\_workap\1\s\bin/Debug/Microsoft.Crm.Extensibility.IntegrationTests.ODataV4
rm: could not remove directory (code ENOTEMPTY): C:\Agents\BuildAgent\_workap\1\s\bin/Debug
rm: could not remove directory (code ENOTEMPTY): C:\Agents\BuildAgent\_workap\1\s\bin

rm: could not remove directory (code ENOTEMPTY): C:\Agents\BuildAgent\_workap\1\s\bin/Debug
rm: could not remove directory (code ENOTEMPTY): C:\Agents\BuildAgent\_workap\1\s\bin

##[section]Finishing: Extract files

**Comment by damccorm** [comment] 2019-11-20 17:52
Hey @rghodki - it looks like another process has a lock on some of the things in your destination folder so we're not able to remove it. Could you make sure that no other processes are doing this? Antivirus systems often behave similarly to this.

Another thing you could try is running `rm -rf` on your destination folder in a previous step. Right now, I think this is as designed - we don't force delete things that are being used by other processes.

**Comment by damccorm** [comment] 2020-01-02 21:52
I'm going to close this since it looks like its working as designed

**Closed by damccorm** 2020-01-02 21:52 UTC
Labels: Area: Core, bug
