### ISSUE TITLE
NuGet task 2.167.4 breaks with `##[error]Invalid Version: null`

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/azure-pipelines-tasks#12658] opened 2020-04-08 09:43 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  Bug
**Enter Task Name**: NuGet 2.167.4

## Environment
Azure Pipelines, Windows Hosted Agents: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=71481&view=logs&j=ef19874c-dd89-559a-7822-f5a414b01ba4&t=4896892c-c3d0-5a70-c160-70c47766e990&l=5

## Issue Description

NuGet v2.167.4 breaks our build when restoring NuGet packages from a private source:

![image](https://user-images.githubusercontent.com/22350/78769491-b9a26a00-798d-11ea-86d1-ee22cc9c422f.png)

It worked yesterday when it was on v2.167.2:

![image](https://user-images.githubusercontent.com/22350/78769523-c3c46880-798d-11ea-88d3-93e9fc1fc648.png)

Here's the task usage: https://github.com/microsoft/vscode/blob/master/build/azure-pipelines/win32/product-build-win32.yml#L224:L231

### Task logs

```
2020-04-08T09:20:38.6561215Z ##[section]Starting: Install ESRPClient.exe
2020-04-08T09:20:38.6694108Z ==============================================================================
2020-04-08T09:20:38.6694896Z Task         : NuGet
2020-04-08T09:20:38.6695872Z Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
2020-04-08T09:20:38.6696854Z Version      : 2.167.4
2020-04-08T09:20:38.6697358Z Author       : Microsoft Corporation
2020-04-08T09:20:38.6697991Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/nuget
2020-04-08T09:20:38.6698682Z ==============================================================================
2020-04-08T09:20:39.4512022Z Caching tool: NuGet 4.1.0 x64
2020-04-08T09:20:39.4962154Z Found tool in cache: NuGet 4.1.0 x64
2020-04-08T09:20:39.5017267Z Resolved from tool cache: 4.1.0
2020-04-08T09:20:39.5018685Z Using version: 4.1.0
2020-04-08T09:20:39.5464301Z ##[error]Invalid Version: null
2020-04-08T09:20:39.6523428Z ##[section]Finishing: Install ESRPClient.exe
```

**Comment by joaomoreno** [comment] 2020-04-08 09:45
Oh. We have a green build with v2.167.5. Could it be already fixed in that version?

**Comment by Atavuli** [comment] 2020-04-08 15:11
Also seeing this error in version 0.167.4

![image](https://user-images.githubusercontent.com/8538904/78800327-2b6bbb00-7970-11ea-8358-1b14658e0797.png)

`
2020-04-08T14:50:10.8951080Z ##[section]Starting: Use NuGet 4.4.1
2020-04-08T14:50:10.9108380Z ==============================================================================
2020-04-08T14:50:10.9108440Z Task         : NuGet tool installer
2020-04-08T14:50:10.9108487Z Description  : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this task to change the version of NuGet used in the NuGet tasks.
2020-04-08T14:50:10.9108538Z Version      : 0.167.4
2020-04-08T14:50:10.9108568Z Author       : Microsoft Corporation
2020-04-08T14:50:10.9108615Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=852538)
2020-04-08T14:50:10.9108645Z ==============================================================================
2020-04-08T14:50:11.4097415Z Found tool in cache: NuGet 4.4.1 x64
2020-04-08T14:50:11.4164301Z Resolved from tool cache: 4.4.1
2020-04-08T14:50:11.4164420Z Using version: 4.4.1
2020-04-08T14:50:11.4273216Z ERR:Invalid Version: null
2020-04-08T14:50:11.4347948Z ##[section]Finishing: Use NuGet 4.4.1 
`

**Comment by jrsavs21** [comment] 2020-04-08 16:01
1.167.4 as well...

**Comment by apluche** [comment] 2020-04-08 16:35
HI @jrsavs21 , @joaomoreno,

We have been dealing with an ongoing issue. To get these errors to stop, please add the Nuget Tool Installer task (docs here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=azure-devops) before running the restore to update the nuget version that the task is using.

I will continue to work on investigating what changes caused this error.

Please let me know if this unblocks you.

**Comment by mjhovanes** [comment] 2020-04-09 23:15
Also getting an error with NuGet task version 2.167.5.

As suggested by @apluche, I have added the NuGet tool installer task, specifying NuGet version 5.5.1. 

Any other suggestions to get past this?

### NuGet tool installer task log

![image](https://user-images.githubusercontent.com/44307054/78948217-d7062f80-7a84-11ea-8d07-f80000204ec2.png)

### NuGet task log: 

![image](https://user-images.githubusercontent.com/44307054/78947928-0b2d2080-7a84-11ea-839b-59a158778401.png)

### NuGet task debug-level logging

2020-04-09T22:20:39.1753201Z ##[debug]Evaluating condition for step: 'NuGet restore'
2020-04-09T22:20:39.1753201Z ##[debug]Evaluating: succeeded()
2020-04-09T22:20:39.1753201Z ##[debug]Evaluating succeeded:
2020-04-09T22:20:39.1753201Z ##[debug]=> (Boolean) True
2020-04-09T22:20:39.1753201Z ##[debug]Expanded: True
2020-04-09T22:20:39.1753201Z ##[debug]Result: True
2020-04-09T22:20:39.1753201Z ##[section]Starting: NuGet restore
2020-04-09T22:20:39.1753201Z ==============================================================================
2020-04-09T22:20:39.1753201Z Task         : NuGet
2020-04-09T22:20:39.1753201Z Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
2020-04-09T22:20:39.1753201Z Version      : 2.167.5
2020-04-09T22:20:39.1753201Z Author       : Microsoft Corporation
2020-04-09T22:20:39.1753201Z Help         : [Learn more about this task](https://go.microsoft.com/fwlink/?LinkID=613747) or [see the NuGet documentation](https://docs.microsoft.com/nuget/)
2020-04-09T22:20:39.1753201Z ==============================================================================
2020-04-09T22:20:39.8628605Z ##[debug]agent.TempDirectory=C:\agent\_work\_temp
2020-04-09T22:20:39.8628605Z ##[debug]loading inputs and endpoints
2020-04-09T22:20:39.8628605Z ##[debug]loading ENDPOINT_AUTH_$/
2020-04-09T22:20:39.8628605Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_$/_ACCESSTOKEN
2020-04-09T22:20:39.8628605Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2020-04-09T22:20:39.8628605Z ##[debug]loading ENDPOINT_AUTH_SCHEME_$/
2020-04-09T22:20:39.8628605Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2020-04-09T22:20:39.8628605Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_ALLOWPACKAGECONFLICTS
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_COMMAND
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_CONFIGURATIONTOPACK
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_DISABLEPARALLELPROCESSING
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_INCLUDENUGETORG
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_INCLUDEREFERENCEDPROJECTS
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_INCLUDESYMBOLS
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_NOCACHE
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_NUGETCONFIGPATH
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_NUGETFEEDTYPE
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_OUTPUTDIR
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_PACKTIMEZONE
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_PUBLISHPACKAGEMETADATA
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_REQUESTEDMAJORVERSION
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_REQUESTEDMINORVERSION
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_REQUESTEDPATCHVERSION
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_SEARCHPATTERNPACK
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_SEARCHPATTERNPUSH
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_SELECTORCONFIG
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_SOLUTION
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_TOOLPACKAGE
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_VERBOSITYPACK
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_VERBOSITYPUSH
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_VERBOSITYRESTORE
2020-04-09T22:20:39.8628605Z ##[debug]loading INPUT_VERSIONINGSCHEME
2020-04-09T22:20:39.8628605Z ##[debug]loaded 31
2020-04-09T22:20:39.8628605Z ##[debug]Agent.ProxyUrl=undefined
2020-04-09T22:20:39.8628605Z ##[debug]Agent.CAInfo=undefined
2020-04-09T22:20:39.8628605Z ##[debug]Agent.ClientCert=undefined
2020-04-09T22:20:39.8628605Z ##[debug]Agent.SkipCertValidation=undefined
2020-04-09T22:20:39.8628605Z ##[debug]Agent.ProxyUrl=undefined
2020-04-09T22:20:39.8628605Z ##[debug]Agent.CAInfo=undefined
2020-04-09T22:20:39.8628605Z ##[debug]Agent.ClientCert=undefined
2020-04-09T22:20:39.8628605Z ##[debug]check path : C:\agent\_work\_tasks\NuGetCommand_333b11bd-d341-40d9-afcf-b32d5ce6f23b\2.167.5\node_modules\azure-pipelines-tool-lib\lib.json
2020-04-09T22:20:39.8628605Z ##[debug]adding resource file: C:\agent\_work\_tasks\NuGetCommand_333b11bd-d341-40d9-afcf-b32d5ce6f23b\2.167.5\node_modules\azure-pipelines-tool-lib\lib.json
2020-04-09T22:20:39.8628605Z ##[debug]system.culture=en-US
2020-04-09T22:20:39.8628605Z ##[debug]task result: Failed
2020-04-09T22:20:39.8628605Z ##[error]Unhandled: Unexpected token =
2020-04-09T22:20:39.8628605Z ##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Unexpected token =
2020-04-09T22:20:39.8628605Z ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Unexpected token =
2020-04-09T22:20:39.8628605Z ##[debug]task result: Failed
2020-04-09T22:20:39.8628605Z ##[error]Unhandled: Unexpected token =
2020-04-09T22:20:39.8628605Z ##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Unexpected token =
2020-04-09T22:20:39.8628605Z ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Unexpected token =
2020-04-09T22:20:39.8628605Z ##[section]Finishing: NuGet restore

**Comment by apluche** [comment] 2020-04-10 16:38
Hi @mjhovanes , 
What kind of agents is your build using? (VS2017, VS2019)

I am investigating on my end and context will help us find the root cause.

**Comment by mjhovanes** [comment] 2020-04-10 18:11
@apluche Thanks for the reply. Upgrading my self-hosted agent to 2.165.2 fixed the issue for me.

**Comment by apluche** [comment] 2020-04-10 18:56
@mjhovanes,
I'm glad that you are now unblocked. What agents were you using previously?

**Comment by mjhovanes** [comment] 2020-04-10 19:08
@apluche I'm embarrassed to say that we had not updated the agent in a while - we were on 2.116.5

**Comment by apluche** [comment] 2020-04-14 00:32
@mjhovanes , thank you for the information! Glad to hear you are unblocked.

@jrsavs21 , @joaomoreno , @Atavuli are you still seeing issues?

**Comment by joaomoreno** [comment] 2020-04-14 11:48
@apluche As mentioned in my last comment v2.167.5 fixed it for us.

**Comment by apluche** [comment] 2020-04-14 21:12
Since the original issue is fixed, I'm closing this out. Please feel free to reach out with any questions or concerns!

**Closed by apluche** 2020-04-14 21:12 UTC
Labels: Area: Artifacts, triage
