### ISSUE TITLE
JenkinsQueueJob: jenkins job is pending while Jenkins job finished 20 minutes ago

### ISSUE THREAD

**Issue by mskoczylas** [microsoft/azure-pipelines-tasks#15148] opened 2021-08-11 18:28 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: JenkinsQueueJobV2

## Environment
TFS on-premises
    
    - Version Dev18.M170.8
    - Agent - Private: Windows_NT 10.0.17763   Version 2.170.0

## Issue Description

There is a 20 minute delay after the Jenkins job was complete with the Queue Jenkins job task
2021-08-11T17:41:25.3751623Z ##[debug]markdown location: C:\windows\SERVIC~1\NETWOR~1\AppData\Local\Temp\JenkinsJob_PullRequest.Validation.-.Application.Build_8596.md
2021-08-11T18:01:59.8844069Z ##[debug]writeFinalMarkdown().writeFile().callback()

### Task logs
2021-08-11T17:41:25.1010249Z ******************************************************************************
2021-08-11T17:41:25.1011030Z Jenkins job finished: PullRequest.Validation.-.Application.Build
2021-08-11T17:41:25.1011944Z http://xxxxxxx/job/PullRequest.Validation.-.Application.Build/8596 
2021-08-11T17:41:25.1012863Z ******************************************************************************
2021-08-11T17:41:25.1014231Z ##[debug](8:PullRequest.Validation.-.Application.Build:8596) debug: state changed from: 3
2021-08-11T17:41:25.1732607Z ##[debug]downloadResults(), url:http://xxxxxxx/job/PullRequest.Validation.-.Application.Build/8596/team-results/zip
2021-08-11T17:41:25.2967580Z ##[debug]downloadResults(), url:http://xxxxxxx/job/PullRequest.Validation.-.Application.Build/8596/team-results/zip , response.statusCode: 404, response.statusMessage: Not Found
2021-08-11T17:41:25.2968974Z ##[debug]no results to download
2021-08-11T17:41:25.2969436Z ##[debug](4:PullRequest.Validation.-.Application.Build:8596) debug: state changed from: 8
2021-08-11T17:41:25.3709989Z ##[debug]jobQueue.stop()
2021-08-11T17:41:25.3721924Z ##[debug]writing summary markdown
2021-08-11T17:41:25.3751623Z ##[debug]markdown location: C:\windows\SERVIC~1\NETWOR~1\AppData\Local\Temp\JenkinsJob_PullRequest.Validation.-.Application.Build_8596.md
2021-08-11T18:01:59.8844069Z ##[debug]writeFinalMarkdown().writeFile().callback()
2021-08-11T18:01:59.8873678Z ##[debug]Processed: ##vso[task.addattachment type=Distributedtask.Core.Summary;name=Jenkins Results;]C:\windows\SERVIC~1\NETWOR~1\AppData\Local\Temp\JenkinsJob_PullRequest.Validation.-.Application.Build_8596.md
2021-08-11T18:01:59.8874631Z ##[debug]task result: Succeeded
2021-08-11T18:01:59.8887372Z ##[debug]Processed: ##vso[task.complete result=Succeeded;]Jenkins pipeline complete
2021-08-11T18:01:59.8991968Z ##[section]Finishing: Queue Jenkins job: PullRequest.Validation.-.Application.Build

**Comment by anatolybolshakov** [comment] 2021-08-13 15:35
Hi @mskoczylas this is the time agent spent writing markdown to the file on your environment for some reason...

**Comment by mskoczylas** [comment] 2021-08-17 14:53
OK how can I improve it?

Sometimes markdown are written in less then 1 second. (Debug is off, but it completed quickly)
2021-08-16T23:18:55.4109121Z Finished: SUCCESS
2021-08-16T23:18:55.4110119Z 
2021-08-16T23:18:55.6306465Z ******************************************************************************
2021-08-16T23:18:55.6307617Z Jenkins job finished: PullRequest.Validation.-.Application.Build
2021-08-16T23:18:55.6308608Z http://xxxxxxxxx/job/PullRequest.Validation.-.Application.Build/8672 
2021-08-16T23:18:55.6309528Z ******************************************************************************
2021-08-16T23:18:56.1787594Z ##[section]Finishing: Queue Jenkins job: PullRequest.Validation.-.Application.Build

**Comment by anatolybolshakov** [comment] 2021-08-18 14:25
@mskoczylas it seems to be related to something on your local system.
Do you run agent interactively or as a service? I would suggest to re-check if agent process has enough priority, and there is no file system related errors.

**Comment by anatolybolshakov** [comment] 2021-08-30 12:55
@mskoczylas have you updated the agent version also? What is the difference between agent version for last successful run and run which contains the issue?

**Comment by mskoczylas** [comment] 2021-08-30 20:46
All agents are the same version. The same agent will stall for 20 minutes at times and run without stalling at other times.

After upgrading DEVOPS, I noticed the issue. Then I upgraded all agents but it did not solve the issue.

**Comment by anatolybolshakov** [comment] 2021-08-31 18:55
@mskoczylas could you please share the JenkinsQueueJobV2 task version for last successful ran and failed?

**Comment by mskoczylas** [comment] 2021-09-01 15:34
When successful 2.167.2
When failed 2.167.2

**Comment by anatolybolshakov** [comment] 2021-09-02 10:48
@mskoczylas since there is the same task and agent version - I'm not sure how DevOps server could affect... Is there something else which changed in your configuration?
We are also unable to reproduce this issue - so it does not looks like common issue.

**Comment by anatolybolshakov** [comment] 2021-09-16 10:00
Hi @mskoczylas do you have any updates?

**Comment by mskoczylas** [comment] 2021-09-16 19:05
I'm not sure what more info you want. It's still not working. All I did was upgrade devops and now we have big issue that's holding up pull request validation.

When trying to reproduce:
Are you using a Jenkins pipeline job with multiple stages?

There is 2 options: 
Capture console output and wait for completion
Capture pipeline output and wait for pipeline completion

It seems that one of them stops after the first stage and the other continue to wait until all stages are complete.

I'm using a scripted pipeline with multiple stages
and another build is using declarative pipeline with multiple stages.

**Comment by kuleshovilya** [comment] 2021-09-21 11:05
@mskoczylas From what we've gathered, there's no issue with code in that part. Judging by the place it hangs, it can either hang on generating reports, which is parsing a JSON boyd received from Jenkins, or writing to file. Both issues seem to be local.
We can recommend to check for any strange symbols sent by jenkins in a request body or check file system on worker.
Due to it not being global or reproducible issue, we will close it now.
If there will be new details or you'll find a way to reproduce it, please, feel free to ping me at v-ikuleshov@microsoft.com or reopen the ticket.

**Closed by kuleshovilya** 2021-09-21 11:05 UTC
Labels: bug, Area: ABTT, Task: JenkinsQueueJob
