### ISSUE TITLE
VSTS not showing correct Test result count compare to published test result and TRX file

### ISSUE THREAD

**Issue by fforjan** [Microsoft/azure-pipelines-tasks#8817] opened 2018-11-10 03:34 UTC
## Environment
- Server - TFS on-premises : 15.117.27024.0
- Agent -  Private :  Windows 10 / 2.117.2

## Issue Description
When running unit tests, we discovered that the number of tests displayed in the test result web part:
![image](https://user-images.githubusercontent.com/601810/48297084-20e48380-e455-11e8-95ff-ca61ba743ce0.png)

Is not matching what was send by the test task:
![image](https://user-images.githubusercontent.com/601810/48297089-3d80bb80-e455-11e8-925b-efce7ee905f6.png)

if we download the TRX file and open it in visual studio, the TRX contains the right number:
![image](https://user-images.githubusercontent.com/601810/48297109-bf70e480-e455-11e8-834d-c9eb15800ecd.png)

### Task logs
We only notice that because we were comparing our results with a build from a month ago - **same agent, same changeset, same machine,** the only different between the 2 builds was a Visual Studio update applied on the build agent.

wmic datafile where "name='C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe'" get Version /Value
With Version=15.0.27924.0 the number doesnt match
When Version was 15.0.27128.1 the number matches

(FYI we notice between those 2 version that MSTest/VSTest is now reporting the test method as passed when using Data driven test so yes, we compare the list of test from the test task log file and the list is the same)

**Comment by fforjan** [comment] 2018-11-27 04:52
I could share the TRX file but not publicly as it may contain some logs and other things.

Let me know

**Comment by SadagopanRajaram** [comment] 2018-11-27 09:07
Please use the developer community and you can attach the trx visible only to Microsoft
https://developercommunity.visualstudio.com/ 
I believe the issue is related to the data driven tests you have in the trx file which are being aggregated and reported as a single test pass/failure.

**Comment by fforjan** [comment] 2018-11-29 19:50
Thanks.
So what's the rule/usage of github issues vs developer community ?

**Comment by bryanmacfarlane** [comment] 2018-11-29 20:46
Issues in this repo should be for the tasks in this repo ( /Tasks)

If it’s an issue with the service or web that goes to dev comm

**Comment by SadagopanRajaram** [comment] 2018-12-05 10:12
@fforjan - can you please let us know if you were able to open a developer community issue? My hypothesis is that you have data driven tests and we aggregate the data rows into a single result when reporting which is why you see the discrepancy. I want to have a look at the trx file to make sure that the number matches my hypothesis. You can search for the test name which has data rows in the report to confirm this hypothesis also.

**Comment by SadagopanRajaram** [comment] 2018-12-11 10:21
@fforjan - I am currently closing this issue assuming that this is related to the documentation below. Please do reactivate if not the case. 
https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=vsts
See the section on "View summarized test results"

**Closed by SadagopanRajaram** 2018-12-11 10:21 UTC
Labels: Area: Test
