### ISSUE TITLE
Error: Npm failed with return code: 4294963248

### ISSUE THREAD

**Issue by jrmcdona** [microsoft/azure-pipelines-tasks#11697] opened 2019-11-06 02:48 UTC
Hello,
So many NPM failures across our web apps.

https://microsoft.visualstudio.com/Xbox.Ambassadors/_build?definitionId=43109&_a=summary

If I trigger it manually, it will pass but sometimes takes 1 or 2 or 3 manual triggers.

I see the issue was closed:
https://github.com/Microsoft/azure-pipelines-tasks/issues/6657

But given the amount of trouble this causes I am hoping there is something coming through

Thanks

**Comment by StefanoVuerich** [comment] 2019-12-18 09:15
Also I'm experiencing this issue. The fix is to relaunch the build and pray.

Any other work around here?

Thanks

**Comment by jrmcdona** [comment] 2019-12-18 15:56
None that I know.   Usually takes 1-4 tries to get it to build.

**Comment by timendez** [comment] 2020-02-18 18:58
I still experience this issue as well. It feels like it's a coinflip every time I rebuild to get it to build correctly.

**Comment by LukaszGrela** [comment] 2020-03-26 12:14
I have the same problem with Pipeline for our React (TypeScript) app. During `npm install` (npm task v1.*) this problem appears not 100% runs fail, but enough to annoy some people... retrying the task with following solution: https://stackoverflow.com/questions/60819191/task-control-option-custom-condition-run-task-when-previous-failed-or-timed doesnt seems to help for that issue. Retrying the Job solves but it may take more than one attempt. This problem for this pipeline started on 14/3/2020.

**Comment by tessawiedmann** [comment] 2020-04-02 22:04
I am also seeing these issues still as @LukaszGrela described. Workaround is just trying again- have you figured anything else out?

**Comment by LukaszGrela** [comment] 2020-04-03 18:07
![image](https://user-images.githubusercontent.com/7643591/78391162-be59cd80-75dd-11ea-8eae-00ca328f6a77.png)

```PS
# Test "npm install" task
# Adjust this to be the name of the previous task (task we want to check status)
$taskName = "npm install"

$url = "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_apis/build/builds/$(Build.BuildId)/timeline?api-version=5.1"

$result = Invoke-RestMethod -Uri $url -Headers @{authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"} -ContentType "application/json" -Method get

#Get the previous task's result  
$taskResult = $result.records | where {$_.name -eq "npm install"} | select result  

echo "${taskName} result: $($taskResult.result)"

#set the Task B's taskResult to variable taskStatus
echo "##vso[task.setvariable variable=taskStatus]$($taskResult.result)"
```

Then 2nd line npm install task has the Custom Control Options test
`and(not(canceled()), ne(variables.taskStatus, 'succeeded'))`

I also have the `npm cache clean --force` task with the same control options

This doesnt solve all the failures, but it reduces the number of job fails:)

**Comment by P-de-Jong** [comment] 2020-04-23 18:52
This problem is popped up for us since yesterday. Now almost all our builds are failing :(

**Comment by brunorenn** [comment] 2020-04-23 22:57
I had this problem and solved returning my npm version to 6.13.0.

**Comment by codecramm3r** [comment] 2020-04-24 13:34
I'm getting exactly the same error since yesterday. If you keep re-trying it eventually succeeds. Around three failed builds before you manage to get a success through the pipeline. No issues on local dev machine when running ng serve, npm install, or npm update.

**Comment by IngressoDev** [comment] 2020-04-27 06:37
Same error here.
NPM Version: 6.13.4

**Comment by Strzyzyk** [comment] 2020-04-27 08:58
The same for me.
npm: 6.14.4

**Comment by danielagg** [comment] 2020-04-27 11:14
Same here as well (6.14.4), ever since the 23th of April, about 80% of our CIs failed - last Friday not a single one succeeded. Changing from npm to yarn didn't help either.

**Comment by Strzyzyk** [comment] 2020-04-27 11:17
@danielagg The same for me - from Thursday all builds failed.

**Comment by danielagg** [comment] 2020-04-27 12:08
@brunorenn thanks for that, I just added a new step (Node.js tool installer) in our pipeline to roll back the version, and it successfully run two times already:

npm info using npm@6.13.7
npm info using node@v13.11.0

![image](https://user-images.githubusercontent.com/10685257/80370511-9124d600-8890-11ea-9f14-b65daf093c87.png)

**Comment by devsh4** [comment] 2020-05-09 01:41
Yes, this happened a couple months ago. I added in `npm cache clean --force` and it reduced the number of failed builds substantially, however didn't treat the root cause. FYI, it looks like it's a npm race condition issue.

**Comment by jmyersmsft** [comment] 2020-07-01 18:15
Closing as this is an issue with npm and/or node itself, not with the Pipelines task

**Closed by jmyersmsft** 2020-07-01 18:15 UTC
Labels: Area: Artifacts, bug

**Comment by timendez** [comment] 2020-10-07 23:12
@jmyersmsft When using the same node version locally, I experience no failures on `npm install`, while it's an intermittent failure on the pipeline job

**Comment by leeebaljith** [comment] 2020-10-10 06:32
Hi all,i am  a newbie to react native,2 days ago ,i stucked while solving the issue,issue is same as @LukaszGrela LukaszGrela said ,same  exact issue on that image i am facing,issue came while installing the this expo cmd "npm i -g expo-cli",i tried several solutions like *npm cache clean --force* ,replace the npm v.6.13.7,,node version t,13.11.0,and delete the node_modules,package-lock.json but still i didn't solve that issue.some buddy help me to solve this isssue,Thank you guys.

**Comment by tanmayghosh2507** [comment] 2023-01-31 17:18
I got it fixed by upgrading Node version used in the pipeline from v11 to v16.
