### ISSUE TITLE
npmrc - Could not find a part of the path 'U:\'

### ISSUE THREAD

**Issue by PrakashRajanSakthivel** [microsoft/azure-pipelines-tasks#12382] opened 2020-02-19 11:33 UTC
I have downloaded the vsts-npm-auth package [here](https://www.npmjs.com/package/vsts-npm-auth#install-and-run-the-tool) and followed the instructions 

`npm install -g vsts-npm-auth` -- This is successful
`vsts-npm-auth -config .npmrc` - This is throwing the error saying "Could not find a part of the path 'U:\'" Where I don't have any drive named 'U:\' locally.

This is the first time I am running, I was expecting a credential probe window. but instead I was getting this error.

**Comment by M198** [comment] 2020-02-20 18:45
Who cares
________________________________

**Comment by michalrobaszewski** [comment] 2020-04-06 08:29
+1

**Comment by Crispried** [comment] 2020-05-12 13:58
Hello,

Any information about this? I got same problem on my machine.

**Comment by Crispried** [comment] 2020-05-12 14:35
Hello again,

The problem is that probably you have you HOMEDRIVE variable set to U

you can check it by executing echo %HOMEDRIVE% in your cmd

you have to set it to proper system drive (in my case it's C:)
To do it execute in cmd (don't forget to run it as admin) SET HOMEDRIVE=C:

Then just execute vsts-npm-auth -config .npmrc once again

**Comment by TONYFECTEAU** [comment] 2020-05-12 14:35
We recently had to troubleshoot this... it is caused the the environment HOMEDRIVE being set incorrectly.

PS> $env:HOMEDRIVE=c:

You can set the environment variable to C:, and check if this fixes the issue for you.

**Comment by herenhuang** [comment] 2020-08-10 21:18
Thanks everyone for the suggestions. @PrakashRajanSakthivel - are you still having issues here?

**Comment by PrakashRajanSakthivel** [comment] 2020-08-18 11:11
we were able to make that work by using this command: `vsts-npm-auth -config .npmrc -TargetConfig ~/.npmrc` This actually creates the token in the workspace then we were utilizing this at the userlevel token.

I will try to do the above approach and check.

**Comment by herenhuang** [comment] 2020-08-24 20:50
Thanks! Going to close this for now, though please do reopen this issue (or a new one) if you have problems. :)

**Closed by herenhuang** 2020-08-24 20:50 UTC
Labels: Area: Artifacts, aa-triaged, question
