### ISSUE TITLE
CacheBeta task not working with forked PR builds

### ISSUE THREAD

**Issue by mitchdenny** [microsoft/azure-pipelines-tasks#10979] opened 2019-07-23 17:34 UTC
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: 
CacheBeta

## Environment
Azure Pipelines
https://dev.azure.com/azure-sdk/public/_build/results?buildId=72591&view=logs&j=572c5e49-83d5-5271-390a-e6dc77f89c6b

- Agent - Hosted or Private: 
Hosted - Ubuntu

## Issue Description
CacheBeta task does not appear to be working with forked PR builds.

### Task logs
See link above.

**Comment by willsmythe** [comment] 2019-08-02 13:09
Closing as a duplicate of #11013

**Closed by willsmythe** 2019-08-02 13:09 UTC
Labels: Area: PipelineCaching, bug, duplicate, route
