### ISSUE TITLE
Unexpected token warning on password with backslash

### ISSUE THREAD

**Issue by UnoSD** [microsoft/azure-pipelines-tasks#10147] opened 2019-04-17 13:02 UTC
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure Resource Group Deployment Task

## Environment
- Server - Azure Pipelines
- Agent - Private
    
## Issue Description

When a password in Key Vault uses the backslash (in my case it contained [...]**\K**[...]) then is passed as argument to an ARM template in the task, you get the following warning:

> There was an error while overriding 'xxxxxx' parameter because of 'SyntaxError: Unexpected token K in JSON at position 17', make sure it follows JavaScript Object Notation (JSON)

The deployment seems fine and the password is passed correctly, though.

The variable is fetched from KV and then passed with double quotes to the template task.

Not causing issues for now beside flagging the warning.

Thank you.

**Comment by anuragc617** [comment] 2019-04-30 09:42
Hi @UnoSD, this is expected behavior as per the design of the task. For special characters, the user has to escape them by using the escape character ('\').  For example, if you want to pass a value 'hello " world', then you should pass it like "hello \" world".  There is not much we can do here.

**Comment by UnoSD** [comment] 2019-04-30 09:52
Hi @anuragc617,

did you mean: "hello \" world"?

In this case then, should I raise an issue for the Key Vault task to escape the `\` character?

Although I do not know what impact this would have as the password would now passed correctly escaped and my guess is that it would then duplicate the \ unless a change in DevOps un-escapes then the output of the variable.

Fetching a password from Key Vault and then using it for an ARM template seems like a quite common scenario and avoiding the '\' in passwords doesn't feel like the right solution.

Possibly this is one for Azure DevOps to escape it when passed? Not entirely sure about that.

How would you approach this in the current system?

**Comment by anuragc617** [comment] 2019-05-01 16:11
@UnoSD yes I meant: `"hello \" world"`.
No, you shouldn't raise this issue to Key Vault task,  also there should be no restrictions of characters in the password. We expect this kind of parsing failure because of the current design of the task. Therefore, we are not failing on parsing errors instead we are ignoring such failures and letting the task to pass.

**Comment by UnoSD** [comment] 2019-05-02 17:57
OK, thanks for the explanation. Would still be nice to remove the warnings, but I appreciate the effort may not be worth it.

**Comment by anuragc617** [comment] 2019-05-07 08:42
Closing this, please reopen if you have any other comment.

**Closed by anuragc617** 2019-05-07 08:42 UTC
Labels: Area: Release, bug
