### ISSUE TITLE
Azure PowerShell Task v4 errors out with "A task was cancelled" exception.

### ISSUE THREAD

**Issue by senthilkungumaraj** [microsoft/azure-pipelines-tasks#11287] opened 2019-09-04 20:16 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure PowerShell Task v4.

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzurePowerShellV4

## Environment
- Server - Azure Pipelines or TFS on-premises?

Azure Pipelines
   
- If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Server: Azure Pipelines 
Account Name: https://azurecat.visualstudio.com/vdc
Team Project Name: VDC

- Agent - Hosted or Private: 

Agent Type: Self-Hosted / Private Agent 
OS: Linux Ubuntu 18.04
Agent Version: 2.155.1

## Issue Description

Azure PowerShell Task v4 intermittently errors out with the exception - "A task was cancelled". There is no consistent way to reproduce this exception. This error is noticed only in Azure PowerShell Task and not any other tasks like PowerShell v2.

Couple of behaviors witnessed include:
1. Sometimes fails before the Azure PowerShell Task bootstraps with the login and context information for the user.
2. Sometimes fails after the bootstrap process, while running the script. The exception happens at different code blocks / statements in the script.

### Task logs

[Worker_20190904-184014-utc.log.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3576643/Worker_20190904-184014-utc.log.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Worker_20190904-184014-utc.log:[2019-09-04 18:40:18Z ERR  StepsRunner] Caught cancellation exception from step: System.OperationCanceledException: The operation was canceled.
Worker_20190904-184014-utc.log:   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
Worker_20190904-184014-utc.log:   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
Worker_20190904-184014-utc.log:[2019-09-04 18:40:18Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
Worker_20190904-184014-utc.log:[2019-09-04 18:40:18Z ERR  BuildJobExtension] Caught exception from log plugin finalization: System.OperationCanceledException: The operation was canceled.
Worker_20190904-184014-utc.log:   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
Worker_20190904-184014-utc.log:   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)

**Comment by RoopeshNair** [comment] 2019-09-05 03:33
@20shivangi / @niadak

**Comment by SumiranAgg** [comment] 2019-09-06 05:31
I am unable to repro the issue. Can you please try to reproduce the issue in build as well and share agent worker logs. You can find them inside agent under _diag folder.

**Comment by arjgupta** [comment] 2019-09-17 04:54
@senthilkungumaraj since you are using azure powershell task on a linux agent, you must be using powershell core. what is the version of powershell core that you are using ? What is the version of Az PowerShell modules that you installed on your local machine ?

**Comment by senthilkungumaraj** [comment] 2019-09-18 20:12
@arjgupta The version of PowerShell Core is 6.2.0. Az PowerShell module version is 2.1.0.

**Comment by eaarora-ms** [comment] 2019-11-18 08:42
@senthilkungumaraj  Are you still facing this issue?

**Comment by eaarora-ms** [comment] 2019-11-20 08:26
Closing. Please re-open if you face any further issues.

**Closed by eaarora-ms** 2019-11-20 08:26 UTC
Labels: Area: Release, bug
