### ISSUE TITLE
Docker task output variable has no value

### ISSUE THREAD

**Issue by jcfiorenzano** [microsoft/azure-pipelines-tasks#14537] opened 2021-03-05 04:06 UTC
## Required Information
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DockerV1(1.181.0) , DockerV2 (2.182.0)

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure Pipelines
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines

## Issue Description

My team is using the content of the output variable "Docker.Output" to do further processing with its content, we have face cases where the value of this variable is empty even though the execution was successful

For example
![image](https://user-images.githubusercontent.com/5582507/110064222-8abd8100-7d21-11eb-83b8-e58accc95189.png)
![image](https://user-images.githubusercontent.com/5582507/110064177-76798400-7d21-11eb-8dbd-7809fa68849b.png)

Looking at that build telemetry we found that the Docker.Output variable was empty

![image](https://user-images.githubusercontent.com/5582507/110064340-c22c2d80-7d21-11eb-8142-3b0f689fd5d3.png)

**Comment by ajinkya599** [comment] 2021-03-05 08:01
Hi @jcfiorenzano,
In the build you shared, I see that `ReferenceName` is not set for the Docker tasks.
Can you please verify whether the task `ReferenceName` is set correctly in the pipelines? [[Reference](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cbatch#use-outputs-in-the-same-job-1)]

**Comment by ajinkya599** [comment] 2021-03-18 08:57
Summary from offline discussion -

- Short: This is expected for `DockerV0` and `DockerV1`. Waiting for @jcfiorenzano to share the debug logs with `DockerV2`.
- Long: 
    - The behaviour of output variable was different for older versions of the Docker task (`DockerV0` and `DockerV1`). It stored the output of the Docker command in the variable (and not a file path). Also, they didn’t support all commands (Docker build/push etc would output empty) and skip writing the variable if the output is too large (env variable max length).
    - This was changed in `DockerV2`. In `DockerV2`, we started writing the output to a file and set the `DockerOutput` as the output file path.
    - The logs shared (offline) were for `DockerV1`. To investigate further, need debug logs where `DockerV2` is being used and the issue is happening.

**Comment by ajinkya599** [comment] 2021-03-30 09:58
This is expected behavior for `DockerV0` and `DockerV1`.
Closing as confirmed offline that this is not happening for `DockerV2`.

**Closed by ajinkya599** 2021-03-30 09:58 UTC
Labels: Area: Release, bug
