### ISSUE TITLE
Provide mechasnism to opt-out of DotNetCoreCLIV2 deprecation warnings

### ISSUE THREAD

**Issue by jpobst** [microsoft/azure-pipelines-tasks#13249] opened 2020-07-09 15:57 UTC
## Required Information

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: DotNetCoreCLIV2

## Environment
- Server - Azure Pipelines

- Agent - Hosted

## Issue Description

Every time the `DotNetCoreCLIV2` task is used it now outputs this warning:

```
##[warning].NET Core SDK/runtime 2.2 and 3.0 are now End of Line(EOL) and have been removed from all agents. If you're using these SDK/runtimes, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the requied version.
```

This warning is displayed even if you aren't using 2.2 or 3.0, and there doesn't seem to be any way to opt out of this message.  We are using:
```
- task: UseDotNet@2
  inputs:
    version: 3.1.300
```

This task needs to either:
* Ideally, detect the version of .NET Core in use and not display this warning
* Allow us to set an environment variable (or something) to not display the warning

This message spams our logs and hides warnings that may be actual problems:
![image](https://user-images.githubusercontent.com/179295/87062245-6df09e00-c1d2-11ea-82ab-529325167666.png)

**Comment by bishal-pdMSFT** [comment] 2020-07-12 13:37
@tejasd1990

**Comment by mconnew** [comment] 2020-07-13 20:08
Detecting the version being used isn't going to work across the board. Some commands don't have a version specified. For example, I have the following in my pipeline and it still emits that warning:
```yaml
      - task: DotNetCoreCLI@2
        displayName: 'Install gitversion'
        inputs:
          command: 'custom'
          custom: 'tool'
          arguments: 'install -g gitversion.tool --version 5.3.7'
```

**Comment by krokofant** [comment] 2020-07-14 00:05
Related thread https://developercommunity.visualstudio.com/content/problem/1108547/irrelevant-build-warning-about-eol-net-core-sdks-b.html

**Comment by ChristopherHaws** [comment] 2020-07-14 19:50
It would be nice if the task detected the runtime version in the `global.json` and didnt show the warning if you are on a supported runtime

**Comment by bishal-pdMSFT** [comment] 2020-07-14 19:59
Detection is going to be difficult and may well be wrong at times. Hence we will not do that.

We are moving this message from warning to be an Info. It will still be printed in all cases, but will not show up in pipeline warnings.

**Comment by mconnew** [comment] 2020-07-15 03:18
Would it be worth emitting the warning for UseDotNet@2 if an unsupported version is specified?

**Comment by tejasd1990** [comment] 2020-07-15 05:17
@mconnew UseDotNet task will use whichever version is specified(eol or not), for subsequent tasks. The deprecation message is for DotNetCoreCLI task on hosted agents, not UseDotNet. Not sure I got the question.

**Comment by cremor** [comment] 2020-07-15 06:53
> The deprecation message is for DotNetCoreCLI task on hosted agents

The message should only be shown on hosted agents? That's not the case, I also get it on a self-hosted agent.

**Comment by mconnew** [comment] 2020-07-15 17:14
@tejasd1990, if the idea is to warn people when they are using an older EOL version of .NET Core, then I was suggesting adding the warning message to the UseDotNet task instead where you do know exactly which version has been specified.

**Comment by ChristopherHaws** [comment] 2020-07-15 19:22
@mconnew If I am understanding correctly, it seems like this warning (not info) message is really warning the user that .NET Core 2.2 and 3.0 are no long installed by default on hosted agents, which happens to be because they are EoL'ed, not that you are using an EoL'ed version of .NET Core. I do think that the latter (warning if you are using an EoL'ed version of .NET Core) would be more meaningful however. For example, how long are you going to display the info message? For the rest of time? Will there be additional messages added later when another version is EoL'ed? It seems like there should be a warning if, and only if, you are actually using an EoL'ed version of the framework.

**Comment by mconnew** [comment] 2020-07-15 19:34
@ChristopherHaws I misunderstood the purpose of the message. I would think that the build output is the wrong place to communicate about a change in the hosts configuration which is why I didn't connect the dots correctly. Re-reading the message I can see that the intention was about the host configuration.

**Comment by bishal-pdMSFT** [comment] 2020-08-02 11:26
Yes the intention is to communicate about hosted agents. The intention was necessiated due to a lot of folks not able to understand why their pipeline started failing after we removed EOL version from hosted agent.
I agree that this is not a very elegant solution as it shows up even if you use a current version. But detecting the version which is in use for a command is not really straightforward, and we chose not to venture into that complexity as it could potentially result into unexpected behaviour. 
We however are looking into how to bubble hosted agent changes in a more discoverable and pleasant manner. Post that we can definitely think about removing this message from task log.

**Comment by bishal-pdMSFT** [comment] 2020-08-02 11:28
We should however clearly call out 'hosted agent' in the message. @vineetmimrot can you please change this?

**Comment by bishal-pdMSFT** [comment] 2020-08-03 07:26
> We should however clearly call out 'hosted agent' in the message. @vineetmimrot can you please change this?
> `.NET Core SDK/runtime 2.2 and 3.0 are now End of Line(EOL) and have been removed from all agents`

I see that this has already been fixed by @tejasd1990

**Closed by bishal-pdMSFT** 2020-08-03 07:26 UTC
Labels: Area: Release
