### ISSUE TITLE
AzureAppServiceManage - Enable Continuous Monitoring fails with code 400 due to outdated API use

### ISSUE THREAD

**Issue by mkennten** [microsoft/azure-pipelines-tasks#15171] opened 2021-08-18 14:25 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureAppServiceManage

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description
1. Creating a ASP.NET app service, Application Insights enabled, using the default workspace
2. Running a pipeline with "Enable Continuous Monitoring" fails with the following error:
2021-08-18T12:32:35.6340925Z ##[error]Error: Failed to enable continuous monitoring. Error: Error: Failed to update Application Insights 'pulcanarytest17171' Resource. Error: BadRequest - WorkspaceResourceId can be set only on api-version 2020-02-02 (CODE: 400)

It seems that the task is referencing api-version=2015-05-01 instead of the latest version api-version=2020-02-02.
[CE-error.txt](https://github.com/microsoft/azure-pipelines-tasks/files/7007957/CE-error.txt)

**Comment by AmrutaKawade** [comment] 2021-08-24 09:51
Duplicate of https://github.com/microsoft/azure-pipelines-tasks/issues/15188. Closing this issue

**Closed by AmrutaKawade** 2021-08-24 09:51 UTC
Labels: Area: Release, Task: AzureAppService, environment:under-investigation
