### ISSUE TITLE
Helm tasks runs kubectl cluster-info for which it may not have sufficient priviledges

### ISSUE THREAD

**Issue by vaclavbroz** [microsoft/azure-pipelines-tasks#13421] opened 2020-08-13 10:15 UTC
Now the helm task will run kubectl cluster-info which will result in a forbidden warning because cluster-info may not be accessible for the given service connection, e.g. Error from server (Forbidden): services is forbidden: User "system:serviceaccount:xxx-sa:xxx cannot list resource "services" in API group "" in the namespace "kube-system"

_Originally posted by @vaclavbroz in https://github.com/microsoft/azure-pipelines-tasks/pull/13189#issuecomment-673392164_

**Comment by vaclavbroz** [comment] 2020-08-13 10:17
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/HelmDeployV0/src/helm.ts#L173

**Comment by shigupt202** [comment] 2020-08-13 10:18
@vaclavbroz Is this affecting the status of the task (success/failure) or is it just a warning?

**Comment by vaclavbroz** [comment] 2020-08-13 10:22
So far no, but that can be related to the fact that the Helm task apparently redirects stderr to stdout (did not verify). So it's a ticking bomb maybe.

**Comment by shigupt202** [comment] 2020-08-13 10:27
We are sorry for the inconvenience, but this step was added in the task to collect some information which would be used to enhance overall experience for the customers while using these tasks. Thanks for pointing out this issue. I'll get in touch with the right people to decide what needs to be done about it.

**Comment by vaclav-dvorak** [comment] 2020-08-13 10:32
Hi
This is happening to us too. It seems the complaining starts this morning (13th Aug). Was there some release?
From code it seems that `kubectl cluster-info` was executed previously on different place and maybe it never run for us before today.

**Comment by shigupt202** [comment] 2020-08-13 11:16
@vaclav-dvorak This code was not reachable earlier due to a code bug, which was rectified recently. But looks like, its creating some new issues now. (Although that  warning is an expected behavior, because not all the service principals would have required permissions for running that command). If it's not affecting the state of the task, please continue to use the pipelines the way you were using previously while we decide whether any further changes have to be done.

cc: @ammohant @ds

**Comment by vaclav-dvorak** [comment] 2020-08-13 11:43
@shigupt202 pipeline is working fine (well except for the warning). Just wanted to add my two cents :)

**Comment by shigupt202** [comment] 2020-08-13 12:28
Discussed this with the team. Since the issue is not affecting any of the customer scenarios and is only appearing in the logs to inform that the service account is not having enough permissions to perform that operation, I think we can continue with it for now. 
@vaclavbroz This is a kubectl command, and not a helm command. So, we don't need to worry about it getting written in stderr or stdout. Closing the issue for now. Feel free to reopen if it affects your pipelines in any way.

**Closed by shigupt202** 2020-08-13 12:28 UTC
Labels: Area: Release, triage

**Comment by vaclavbroz** [comment] 2020-08-13 12:47
> Discussed this with the team. Since the issue is not affecting any of the customer scenarios and is only appearing in the logs to inform that the service account is not having enough permissions to perform that operation, I think we can continue with it for now.
> @vaclavbroz This is a kubectl command, and not a helm command. So, we don't need to worry about it getting written in stderr or stdout. Closing the issue for now. Feel free to reopen if it affects your pipelines in any way.

Fine for me.

Once the kubectl command run within the HelmDeploy task will somehow start putting the warning in stderr the pipeline task HelmDeploy will start being marked as failed. Given the fact you did not discover the issue with logging before releasing this pull-request I guess you do not have any automated integration tests covering this scenario. From that I understand there is a non-null probability you will have an incident later with the root cause described here.

I would suggest running a simple tests prior querying the specific namespace, e.g. with `kubectl auth can-i` and not executing the command if not authorised.
