### ISSUE TITLE
[ExtractFiles]: Do not delete archives if they are in destinationFolder and searched in archiveFilePatterns

### ISSUE THREAD

**Issue by Saibamen** [microsoft/azure-pipelines-tasks#12505] opened 2020-03-10 08:45 UTC
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ExtractFiles

## Environment
- Server - Azure Pipelines

- Agent - Hosted

## Issue Description

Do not delete archives if they are in destinationFolder and searched in archiveFilePatterns

```
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '**/X/Y/Z/.TestIntegrationData.zip'
    destinationFolder: 'X/Y/Z'
    cleanDestinationFolder: true
```

### Task logs

IMHO not needed full debug logs. Please see below.

### Error logs

```
Searching for: **\X\Y\Z\.TestIntegrationData.zip under directory: d:\a\1\s
Found: 1 files to extract:
d:\a\1\s\X\Y\Z\.TestIntegrationData.zip
Cleaning destination folder before extraction: d:\a\1\s\X\Y\Z
Creating destination folder: d:\a\1\s\X\Y\Z
Error: ENOENT: no such file or directory, stat 'd:\a\1\s\X\Y\Z\.TestIntegrationData.zip'
```

**Comment by Saibamen** [comment] 2020-03-10 08:49
Need to change this line: https://github.com/microsoft/azure-pipelines-tasks/blob/cf3e2e421794888ea5a285b92efee866dace4272/Tasks/ExtractFilesV1/extractfilestask.ts#L311

**Comment by damccorm** [comment] 2020-06-16 14:55
I think I disagree with the behavior you're suggesting. I think given the scenario you've described there are 3 options:
1) Delete the folder first and ignore the zip in question
2) Don't delete a zip if its going to be extracted. An open question here is what happens to the zip after it is extracted (is it then deleted?)
3) Throw an error (current behavior)

I actually tend to lean towards the 3rd option being the best option because the behavior is silently ambiguous, and I'd argue you shouldn't try to clean a folder that has something you're trying to extract.

**Comment by Saibamen** [comment] 2020-06-16 19:33
`Don't delete a zip if its going to be extracted. An open question here is what happens to the zip after it is extracted (is it then deleted?)`

Don't delete of ZIP file. If we want to extract `A/B/text.zip` into `A/B/C` folder, we don't delete it, so why we should automatically delete zip file when we extect it into `A/B` folder?

If we want have more free space (for example for Docker image), we should delete this file manually (by command of course ;)) after `ExtractFiles@1` task

**Comment by damccorm** [comment] 2020-06-16 19:45
> If we want have more free space (for example for Docker image), we should delete this file manually (by command of course ;)) after ExtractFiles@1 task

Its not about having more free space, the issue is that we've said we're going to clean the target folder.

**Comment by Saibamen** [comment] 2020-06-16 20:21
Yes, but this is not logical IMHO. Why we should want to clean destination folder with file to extract inside it in this same command. This is forcing end users to change path and adds additional folders just because `ExtractFiles` deleting my archive file *before* extracting it.

My understanding to `cleanDestinationFolder` is: Clean destination folder, but first check if `destinationFolder` is this same as founded files with `archiveFilePatterns` and if yes, delete all files except those founds by `archiveFilePatterns`

**Comment by damccorm** [comment] 2020-06-16 20:43
My point is that its not a logical request to begin with and because the behavior is ambiguous its probably better to just error out (instead of silently doing something that may not be the intended behavior)

**Comment by Saibamen** [comment] 2020-06-16 22:08
Yeah, the log is pretty clear to understand that end user should do something with command or change path to folders (not a really bug itself):
```
Found: x files to extract: path_to_archive
Cleaning destination folder before extraction: dest_path
(...)
no such file 'path_to_archive'
```

**Comment by damccorm** [comment] 2020-06-18 14:58
Closing since I think this is a no-op

**Closed by damccorm** 2020-06-18 14:58 UTC
Labels: Area: Core, enhancement

**Comment by Saibamen** [comment] 2020-06-18 15:05
no-op?

**Comment by damccorm** [comment] 2020-06-18 15:08
Sorry, should've been clearer - I don't think we're going to make a change here (no-op is short for no operation).

**Comment by Saibamen** [comment] 2020-06-18 15:54
Thanks for clarification
