### ISSUE TITLE
Syntax Error when running Azure CLI in Azure Pipeline

### ISSUE THREAD

**Issue by jasric89** [microsoft/azure-pipelines-tasks#14677] opened 2021-04-01 09:31 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

When running az webapp create --resource-group $(RG) --plan $(azureSubscription) --name %1 
I keep getting syntax error no matter what I do with the command. 

**Question, Bug, or Feature?**  
I believe there is a bug in Azure CLI within Azure Pipelines when passing a runtime variable value in. Happens in 1.0 and 2.0 

*Type*: here

**Enter Task Name**: here  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

I keep getting the following error: /home/vsts/work/_temp/azureclitaskscript1617268666546.sh: line 1: syntax error near unexpected token `('

This is when I run this set of code from my YAML file that essentially runs an Azure CLI Command: 

 - task: AzureCLI@1
    displayName: 'Create Web App in $(appservicename)'
    inputs:
      azureSubscription: $(azureSubscription)
      scriptLocation: inlineScript
      Arguments input: $(webappname)
      inlineScript: |
        az webapp create --resource-group $(RG) --plan $(azureSubscription) --name %1

The webapp name variable is a runtime variable. That has been set correctly and works else where in the yaml file. Yet for azure cli I get this syntax error. 

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

I have tried the following things

Settings the Variable as an ENV variable using echo 
Wrapping the variable in %% or {} 
Quoting around the variable "$(webappname)"'
Dollaring the variable $($webappname)

Nothing seems to work and I get the same error. 

### Error logs

Main error: /home/vsts/work/_temp/azureclitaskscript1617268666546.sh: line 1: syntax error near unexpected token `('

Whole Log: 

##[debug]   set
##[debug]   --subscription
##[debug]   --subscription
##[debug]   237bc9da-22ad-49ea-8411-6cf6a190c18f
##[debug]   237bc9da-22ad-49ea-8411-6cf6a190c18f
/usr/bin/az account set --subscription 237bc9da-22ad-49ea-8411-6cf6a190c18f
##[debug]addSpnToEnvironment=false
##[debug]exec tool: /bin/bash
##[debug]arguments:
##[debug]   /home/vsts/work/_temp/azureclitaskscript1617268666546.sh
/bin/bash /home/vsts/work/_temp/azureclitaskscript1617268666546.sh
/home/vsts/work/_temp/azureclitaskscript1617268666546.sh: line 1: syntax error near unexpected token `('
/home/vsts/work/_temp/azureclitaskscript1617268666546.sh: line 1: `az webapp create --resource-group ClassroomInTheCloud --plan Visual Studio Professional Subscription (237bc9da-22ad-49ea-8411-6cf6a190c18f) --name %1'
##[debug]Exit code 2 received from tool '/bin/bash'
##[debug]STDIO streams have closed for tool '/bin/bash'
##[debug]task result: Failed
##[error]Script failed with error: Error: The process '/bin/bash' failed with exit code 2
##[debug]Processed: ##vso[task.issue type=error;]Script failed with error: Error: The process '/bin/bash' failed with exit code 2
##[debug]Processed: ##vso[task.complete result=Failed;]Script failed with error: Error: The process '/bin/bash' failed with exit code 2
##[debug]which 'az'
##[debug]found: '/usr/bin/az'
##[debug]/usr/bin/az arg:  account clear
##[debug]/usr/bin/az arg:  account clear
##[debug]exec tool: /usr/bin/az
##[debug]exec tool: /usr/bin/az
##[debug]arguments:
##[debug]arguments:
##[debug]   account
##[debug]   account
##[debug]   clear
##[debug]   clear
/usr/bin/az account clear
Finishing: Create Web App in appserviceplan-dgyn27h2dfoyo

[Insert error from the logs here for a quick overview]

**Comment by papagalu** [comment] 2021-04-01 16:09
subscribe, i have the same issue, when using the bash step, the expansion seems to be done wrong, sometimes i get EOF when using $(variable), sometimes it fails when using the az cli --name $(variable)

**Comment by jasric89** [comment] 2021-04-06 08:18
Any Update on this please? When I put actual values the task runs but when putting variabeles in I get syntax error.

**Comment by anuragc617** [comment] 2021-04-07 17:44
@jasric89 for referencing the command line arguments in bash script you should use $1 instead %1. Can you please try that?

**Comment by anuragc617** [comment] 2021-04-13 16:43
@jasric89 Have you got the chance to try above suggestion?

**Comment by papagalu** [comment] 2021-04-13 18:50
@anuragc617 the issue is not related to %1 or $1

if you pay attention to the debug log you can see an extra quote( ' ) the weird thing is that it gets there at "compile" time, when azure devops replaces variables/secretes, etc with actual values, and passes the script to an actual bash shell

those extra ' are breaking everyones build

**Comment by anuragc617** [comment] 2021-04-15 03:54
@papagalu, sorry for confusion. I already mentioned this`it is giving error there because of '(' in subscription name`. It should be a valid app service plan name not a subscription name here. 
@papagalu Can you provide more details and provide logs for your issue, so that we can have a look at it.

**Comment by jasric89** [comment] 2021-04-15 13:42
You guys seriously don't work together or read, posts properly do you.... You have an open bug see PR12922 that If I specify a management group/ service plan you get an error stating that CLI can not find the Azure Subscription.... Therefore you then go down the road of referencing the Azure Subscription and you get this bug that you are replying too, a syntax error. Please can you all work as a team or at least keep up to date on your latest PR's

**Comment by anuragc617** [comment] 2021-04-19 07:40
@jasric89 I am not sure which PR12922 you are referring to, can you please share the link. The issue you have posted here is happening because you are passing Azure subscription instead App service plan to web app create command. As azure subscription is expanded to `Visual Studio Professional Subscription (237bc9da-22ad-49ea-8411-6cf6a190c18f)` which contains `(` , the Azure CLI is failing with unexpected  unexpected token `(`.  
Please replace $(azureSubscription) to $(appserviceplan) it will work 
az webapp create --resource-group $(RG) --plan $(**azureSubscription**) --name %1
I have tried this and it is working fine. Also when I used azureSubscription there, I got the same error which you are facing.
```
- task: AzureCLI@1
  displayName: 'Create Web App in $(RG)'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: 'inlineScript'
    arguments: $(webAppName)
    inlineScript: az webapp create --resource-group $(RG) --plan $(appserviceplan) --name $1
```

**Comment by jasric89** [comment] 2021-04-23 13:24
I did that and it didn't work, I got the same syntax error.

**Comment by anuragc617** [comment] 2021-04-24 16:23
@jasric89 Can you please share the latest logs with the suggested changes in task? Are you seeing this line in logs `az webapp create --resource-group ClassroomInTheCloud --plan Visual Studio Professional Subscription (237bc9da-22ad-49ea-8411-6cf6a190c18f) --name %1'`. ?

**Comment by NinadKavimandan** [comment] 2021-05-03 05:22
Hi @jasric89 can you please share the latest logs for investigation?

**Comment by ddivanshu** [comment] 2021-05-19 09:46
Closing this since user didn't reply.
Feel free to open incase of issue.

**Closed by ddivanshu** 2021-05-19 09:46 UTC
Labels: Area: Release, triage

**Comment by jasric89** [comment] 2021-07-06 09:07
Please do not close this, its not fixed
