### ISSUE TITLE
Nuget Restore: not adding ApiKey feeds to temporary nuget.config

### ISSUE THREAD

**Issue by mstephano** [Microsoft/azure-pipelines-tasks#8510] opened 2018-10-05 16:04 UTC
## Environment
- We are using TFS on-premises.
- We built the source code and deployed Nuget task on our server.
- Task version is now 2.0.45 (see task log below)

## Issue Description
Using v2 of NuGet Restore task with these options:
- no path to nuget.config entered
- selected 1 ApiKey outside feed
- disable local cache to test the outside feed
![image](https://user-images.githubusercontent.com/18444266/46544901-d2aaf600-c892-11e8-8e11-f3a3cdb69b97.png)

## Expected behavior
Because no path to nuget.config is entered, nuget is creating a temporary .config file. My expected behavior is that Nuget would insert the outside feed Url to the \<packageSources> list in the temporary nuget.config file.

### Task logs

```
2018-10-05T15:44:52.3247612Z ==============================================================================
2018-10-05T15:44:52.3247955Z Task         : NuGet
2018-10-05T15:44:52.3248383Z Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Package Management and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
2018-10-05T15:44:52.3248784Z Version      : 2.0.45
2018-10-05T15:44:52.3249021Z Author       : Microsoft Corporation
2018-10-05T15:44:52.3249284Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613747)
2018-10-05T15:44:52.3249596Z ==============================================================================
...
2018-10-05T15:44:54.1789187Z Saving NuGet.config to a temporary config file.
2018-10-05T15:44:54.1846147Z ##[warning]No package sources were found in the NuGet.config file at D:\b\1\47\Nuget\tempNuGet_143620.config
2018-10-05T15:44:54.1849775Z [command]D:\b\1\_tool\NuGet\4.1.0\x64\nuget.exe restore D:\b\1\47\s\myproject.sln -NoCache -Verbosity Detailed -NonInteractive
```
My expected behavior would have been:
```
Saving NuGet.config to a temporary config file.
##[warning]No package sources were found in the NuGet.config file at D:\b\1\47\Nuget\tempNuGet_143620.config
[command] nuget.exe sources Add -Name "PublicNuget" -Source http://myserver/feed
[command] nuget.exe restore ...
```

Because of that, the Nuget Restore cannot restore packages in our internal feeds.

Anyone else having this error? Or am I not understand how to use the credential outside feeds..

**Comment by jotaylo** [comment] 2018-10-22 22:53
Can you please run the task again with system.debug set to true and include the logs (you can censor anything you wish from the log).

**Comment by alexmullans** [comment] 2019-01-25 20:11
Closing this as by design. You need a nuget.config checked in if you're using the "Feeds in my nuget.config" option. The task will then check that config for feeds, match up feeds with any credentials provided, and insert the feeds and credentials into a temporary nuget.config.

**Closed by alexmullans** 2019-01-25 20:11 UTC
Labels: Area: Artifacts
