### ISSUE TITLE
Task Bash version 3.211.0 requires agent version 2.206.1 and no agents with that version are registered.

### ISSUE THREAD

**Issue by lucasmior** [microsoft/azure-pipelines-tasks#17198] opened 2022-11-14 15:12 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Bash | Script  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
       
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  hpcodeway

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: ADO agent v2.200.2

## Issue Description

Last 2-3 hours most of our pipelines starting facing this issue: 

```
Task Bash version 3.211.0 requires agent version 2.206.1 and no agents with that version are registered.
```

We control the ado version, and we don't allow auto-update.

I would like to understand what was the change that is causing this issue. I don't see any change on the Bash task.

### Task logs

```
##[error]The pool CodeWayAWSLinux doesn't allow agent updates. Task Bash version 3.211.0 requires agent version 2.206.1 and no agents with that version are registered. An administrator can alter this by visiting the pool's Settings page at the organization level.
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by KonstantinTyukalov** [comment] 2022-11-16 07:09
Hi @lucasmior, thank you for the information provided. It seems this changes made by mistake, we will fix that

**Comment by lucasmior** [comment] 2022-11-17 19:45
> Hi @lucasmior, thank you for the information provided. It seems this changes made by mistake, we will fix that

Do you know why we were affected by this change just this week?
The mistaken pull request was merged on Sep 15, and we just got errors on Nov 14, almost 3 months after that.
What is the release lifecycle of the tasks? Does master code means release? I don't think so.

**Comment by KonstantinTyukalov** [comment] 2022-11-22 12:53
>Do you know why we were affected by this change just this week?
The mistaken pull request was merged on Sep 15, and we just got errors on Nov 14, almost 3 months after that.
What is the release lifecycle of the tasks? Does master code means release? I don't think so.

@lucasmior after merging to master the new versions are gradually rolling out to all users.
In general, the interval between merging changes and release is between 3 weeks and 2 months.

Could you check if the issue is solved in your case?

**Comment by KonstantinTyukalov** [comment] 2022-12-01 12:57
@lucasmior, I'm closing this issue.
If you still have problems, please let me know and we'll reopen it.
Thanks

**Closed by KonstantinTyukalov** 2022-12-01 12:57 UTC
Labels: bug, Area: ABTT, Task: Bash
