### ISSUE TITLE
ARM deployment tasks create resource groups when using Deployment mode Validation

### ISSUE THREAD

**Issue by mk-AVA** [microsoft/azure-pipelines-tasks#14326] opened 2021-02-02 20:07 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceManagerTemplateDeploymentV3  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines 
    
    - Can be provided as needed via email, not relevant

## Issue Description

When using the task AzureResourceManagerTemplateDeploymentV3 scoped to Resource group or AzureResourceGroupDeploymentV2 task and set to 'Create or Update' and in Validate only mode, I get a new resource group created. I investigated the code logic of both tasks to confirm that this is the case. 

This is either a bug in the logic of the tasks or the documentation needs to be updated to accurately reflect that resource groups will get created when running in Validation mode.

**Comment by 20shivangi** [comment] 2021-02-08 09:34
Transferring it to right team as confirmed from [CODEOWNERS](https://github.com/microsoft/azure-pipelines-tasks/blob/master/.github/CODEOWNERS#L74)

**Comment by t-dedah** [comment] 2021-02-17 19:06
Updating the helpMarkDown and docs to reflect the expected behaviour. https://github.com/microsoft/azure-pipelines-tasks/pull/14412

**Comment by tejasd1990** [comment] 2021-03-25 12:59
closing since this has been fixed

**Closed by tejasd1990** 2021-03-25 12:59 UTC
Labels: Area: Release
