### ISSUE TITLE
Job hangs for a good amount of time after finishing file copy.

### ISSUE THREAD

**Issue by vsd-codesode** [microsoft/azure-pipelines-tasks#12815] opened 2020-05-04 08:59 UTC
## Note  
I have a repository in Azure DevOps, pipeline of this repos copy the generated `tar` file to a remote server. Every step of the pipeline works very smooth. But, CopyFilesOverSSH task keeps waiting for the finish for good 30 minutes.
I have checked on the server that file is fully copied in 5 minutes, but the task is still showing `Copying file ****`

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: CopyFilesOverSSH  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by sdobrodeev** [comment] 2020-05-11 10:55
@vsd-codesode Can you please provide information about size of the file that you copied?

**Comment by vsd-codesode** [comment] 2020-05-21 17:20
File size is around 530mb.

**Comment by sdobrodeev** [comment] 2020-06-02 12:45
Reproduced a delay after finishing copy process depending on source file size. This behavior is caused by the scp2 library used by CopyFilesOverSSH task. Created https://github.com/microsoft/azure-pipelines-tasks/issues/13048 for future investigations.

**Comment by vsd-codesode** [comment] 2020-06-02 14:39
Hi @sdobrodeev ,

I could help you in doing the code change. Let me know; if your process allows.

**Comment by sdobrodeev** [comment] 2020-06-26 07:52
It was fixed in https://github.com/microsoft/azure-pipelines-tasks/pull/13084 PR. Tested on 500Mb and 1Gb files. Delay after copying now no longer occurs.

**Comment by anatolybolshakov** [comment] 2020-07-16 11:30
Reopened it at the moment due to reverted changes - https://github.com/microsoft/azure-pipelines-tasks/pull/13298, we are going to proceed on it further

**Closed** 2020-08-03 08:27 UTC
Labels: Area: ABTT, Task: CopyFilesOverSSH, bug
