### ISSUE TITLE
[DTS 1723934] Host Mac Agents: Xamarin build task has error: dSYM" doesn't exist

### ISSUE THREAD

**Issue by leantk** [microsoft/azure-pipelines-tasks#13002] opened 2020-05-26 18:10 UTC
Please look at work item 1723934 that has been opened here:
https://dev.azure.com/mseng/_workitems/edit/1723934

**Comment by anatolybolshakov** [comment] 2020-05-28 08:51
Duplicate of #11

**Closed by anatolybolshakov** 2020-05-28 08:51 UTC
Labels: Area: ABTT, Area: Release, DTS, P1, triage
