### ISSUE TITLE
Nuget tool installer should default to 4.x or 4.3.x at a minimum (not 4.3.0)

### ISSUE THREAD

**Issue by bryanmacfarlane** [Microsoft/azure-pipelines-tasks#6693] opened 2018-03-14 15:53 UTC
The hosted pool will precache  n major or n major.minor combos.

If you default to 4.3.x then you can update the hosted pool cache to carry a version with a bug fix (patch version) needed and it won't cause everyone else that created a build definition before you updated to the new version to get cache misses.

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/NuGetToolInstaller/task.json#L27

See the node installer and the samples for the pattern that will encourage cache hits while retaining stability

**Comment by KirillOsenkov** [comment] 2018-07-02 23:54
Why isn't the NuGet Tool Installer defaulting to 4.7.0? Should there be a checkbox "Default to the latest available NuGet.exe version" that should be checked by default?

Every time I add a NuGet Tool Installer task I have to manually switch it from 4.3.0 to 4.7.0.

**Comment by alexmullans** [comment] 2019-01-25 20:48
Closing this as a duplicate of Microsoft/azure-pipelines-image-generation#509, which will be fixed in a week or two.

@KirillOsenkov to your question, NuGet has a history of making breaking changes in minor versions, so we don't ever change the version of NuGet used by an existing build. We do periodically update the default suggested by the Tool Installer, and we're hopefully going to make some more structural improvements to this flow in an upcoming quarter.

**Closed by alexmullans** 2019-01-25 20:48 UTC
Labels: Area: Artifacts
