### ISSUE TITLE
Problem with accents during Release

### ISSUE THREAD

**Issue by RomBrz** [microsoft/azure-pipelines-tasks#12271] opened 2020-01-31 22:26 UTC
## Required Information

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: IISWebAppDeploymentOnMachineGroup

## Environment
TFS on-premise: Azure DevOps Server Version Dev17.M153.5

## Issue Description
I have files in my Repo with accents (in concrete case: "caminhão 01.JPG", but happen with files with "ç" like "conceição"), the resultant file after Release in my IIS server turns to be named "caminh�o 01.JPG".

I downloaded the Build file "drop.zip" and the file inside still is "caminhão 01.JPG". So if i use the "IIS web app deploy" task, this break my accentuated file names.

**Comment by RomBrz** [comment] 2020-02-04 23:07
Seems like this occurs with words inside files too, not only with file names.
Right now i uploaded an ASPX file that have this:
<label>Data publicação:</label>
The file when browsering from TFS/AzureDevOps still have "publicação".
The file after publishing to IIS server using the deploy task have this:
<label>Data publica��o:</label>
I can confirm that the "drop.zip" (the artifact after building the code) has inside the file with "publicação", so it's also changing the text inside files, breaking every "ç", "ã", "á".

**Comment by chperich** [comment] 2020-02-18 06:32
@RomBrz : We tried to reproduce this issue by creating a file conceição.html that also contains the text "conceição" and deployed it using the task. This seems to be working as expected on our end. Can you check the encoding in your web.config file and ensure it set to Unicode character encoding?

**Comment by SumiranAgg** [comment] 2020-03-09 10:39
Need more information to debug the issue. Closing it for now. Feel free to re-open if required with above required info.

**Closed by SumiranAgg** 2020-03-09 10:39 UTC
Labels: Area: Release, bug

**Comment by DavidRamosTR** [comment] 2022-02-25 09:21
I had this problem too, it sees it's because zip archive. when I deploy iis web app without zipping it works fine
