### ISSUE TITLE
[AzureResourceManagerTemplateDeployment@3] - support bicep deployment

### ISSUE THREAD

**Issue by ozbillwang** [microsoft/azure-pipelines-tasks#15337] opened 2021-09-26 13:04 UTC
## Note  

Azure Bicep can be deployed via `az deployment group create -f ./main.bicep -g my-rg` now. 

## Required Information

When feed bicep files, the task marks it invalid

**Question, Bug, or Feature?**  

Feature

**Enter Task Name**: here  

- AzureResourceManagerTemplateDeployment@3

## Environment

```
az version{
  "azure-cli": "2.27.1",
  "azure-cli-core": "2.27.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
  }
}
```

## Issue Description

>[error]Error: Ensure the Template file ( '/agent/_work/1/s/vm/main.bicep' ) is valid. Task failed while parsing with following error: Unexpected token p in JSON at position 0

**Comment by anthony-c-martin** [comment] 2021-11-01 11:46
Looks like we'll need to:
* Copy the code in https://github.com/microsoft/azure-pipelines-tasks/blob/32a89fc20495ed0ddf3d8577f66b89739143e0a8/Tasks/Common/utility-common-v2/helmutility.ts to create a utility to install the Bicep executable.
* Check the file extension when this command is invoked, and if it is `.bicep`, ensure Bicep is installed before invoking a `bicep build`.
* Report errors from the `build` step if there are any, or start the deployment if not.

Happy to help with questions or to review a change if someone else feels like attempting it. Otherwise, I'll try to implement this myself if I get some free time.

**Comment by anthony-c-martin** [comment] 2021-11-01 17:18
> Looks like we'll need to:
> 
> * Copy the code in https://github.com/microsoft/azure-pipelines-tasks/blob/32a89fc20495ed0ddf3d8577f66b89739143e0a8/Tasks/Common/utility-common-v2/helmutility.ts to create a utility to install the Bicep executable.
> * Check the file extension when this command is invoked, and if it is `.bicep`, ensure Bicep is installed before invoking a `bicep build`.
> * Report errors from the `build` step if there are any, or start the deployment if not.

@bishal-pdMSFT - would you be willing to accept a contribution following this design? Is there anything missing/needing to be changed?

**Comment by johndowns** [comment] 2021-11-22 02:16
This would be extremely helpful. @bishal-pdMSFT Any update on whether this might be accepted?

**Comment by bishal-pdMSFT** [comment] 2021-11-28 16:08
Adding @naga-bandi and @v-abajaj who own the ARM deploy task now

**Comment by marvinbuss** [comment] 2021-12-08 20:06
Agreed. The GH Action also supports this and it would be great to get a consistent experience in ADO and GH.

**Comment by johndowns** [comment] 2021-12-08 20:15
@NAGA-BANDI and @v-abajaj - any thoughts on @anthony-c-martin's [proposal](https://github.com/microsoft/azure-pipelines-tasks/issues/15337#issuecomment-956425303)?

**Comment by johndowns** [comment] 2022-01-06 23:50
@bishal-pdMSFT @NAGA-BANDI and @v-abajaj are you able to look at this please?

**Comment by t-dedah** [comment] 2022-01-17 22:38
@marvinbuss @johndowns Raised a PR for mitigation. https://github.com/microsoft/azure-pipelines-tasks/pull/15788

For first iteration, we are only supporting bicep if azure cli installed >= 2.20.0. we are still looking into installation script for bicep cli. 

Also we are only adding this support for "Linked Artifact" case as for the other case url for the template and parameters are directly passed to armclient. We will need to see if support for bicep can be added directly to armclient for second case as downloading the file and then converting it to json and then treating it as "Linked Artifact" case doesnt seem efficient. 

Please review the PR and let us know if anything else is needed.

**Comment by johndowns** [comment] 2022-01-17 22:44
Thanks @t-dedah. Great to see this progressing!

@anthony-c-martin is probably best to review this from a code perspective. I've made a few minor suggestions around wording of messages and Markdown files.

cc @alex-frankel

**Comment by marvinbuss** [comment] 2022-02-02 11:27
@t-dedah I think this can be closed, since https://github.com/microsoft/azure-pipelines-tasks/pull/15788 was merged?

**Comment by anthony-c-martin** [comment] 2022-02-02 12:27
@t-dedah thanks for adding this feature! Would you mind confirming when the next release will occur so that customers can start using this functionality?

**Comment by marvinbuss** [comment] 2022-02-02 12:28
I also just tried to test this feature and I can confirm that the feature was not released yet.

**Comment by alex-frankel** [comment] 2022-02-02 16:13
@mumian -- can we keep an eye on this thread? Once this change is released, we will need to update our [DevOps CI/CD quickstart](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/add-template-to-azure-pipelines?tabs=CLI)

**Comment by mumian** [comment] 2022-02-02 16:16
@alex-frankel - I have created a content task to track the issue.

**Comment by johndowns** [comment] 2022-08-01 18:23
@mumian This change seems to have been released.

**Comment by mumian** [comment] 2022-08-01 18:28
@johndowns - I will take a look this week.

**Comment by mumian** [comment] 2022-08-05 15:10
The article has been updated - https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/add-template-to-azure-pipelines?tabs=CLI

**Closed** 2022-11-07 03:47 UTC
Labels: Area: Release, triage

**Comment by johnnyreilly** [comment] 2023-06-02 13:34
Probably should be a separate issue, but *I think* that the bicep deployment doesn't support authenticating for private Bicep registries.  We see:

```bash
/home/vsts/work/1/s/infra/database/cosmos.bicep(57,17) : Error BCP192: Unable to restore the module with reference "br:icebox.azurecr.io/bicep/ice/providers/document-db/database-accounts:v1.3": Service request failed.
Status: 401 (Unauthorized)

Content:
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information."}]}

Headers:
Server: openresty
Date: Fri, 02 Jun 2023 13:11:24 GMT
Connection: keep-alive
X-Ms-Correlation-Request-Id: b1ac068c-f69d-4495-90c3-302ff1c93ff6
x-ms-ratelimit-remaining-calls-per-second: 333.066667
Strict-Transport-Security: REDACTED
Content-Type: text/plain; charset=utf-8
Content-Length: 134

/home/vsts/work/1/s/infra/database/cosmos.bicep(72,25) : Error BCP192: Unable to restore the module with reference "br:icebox.azurecr.io/bicep/ice/providers/document-db/sql-databases:v1.2": Service request failed.
Status: 401 (Unauthorized)

```
