### ISSUE TITLE
Azure SQL Database Deployment Task doesn't escape special characters in Connection Strings

### ISSUE THREAD

**Issue by ptfaulkner** [microsoft/azure-pipelines-tasks#12012] opened 2019-12-19 15:55 UTC
## Required Information

*Type*: Bug

**Enter Task Name**: Azure SQL Database Deployment

## Environment
- Agent - Azure Pipelines Hosted `windows-2019`

## Issue Description

When using the Azure SQL Database Deployment task with the `Connection String` Authentication Type, the task will not authenticate correctly if there are special characters in the password of the connection string.

I discovered this while trying to get the task to work with my release pipeline and it seemed to be failing for no reason other than that it couldn't authenticate correctly.  I then switched to `SQL Server Authentication` and filled out the properties with the same values as my connection string and it worked.  I then came here and started looking at the powershell code for the task and see that when `SQL Server Authentication` is selected, the password field is escaped for special characters.

https://github.com/microsoft/azure-pipelines-tasks/blob/868328fff79bd1b789f8bcb568be7886b9b9a8d9/Tasks/SqlAzureDacpacDeploymentV1/SqlAzureActions.ps1#L260

Also, looking bit further down I see that the connection string is not.  

https://github.com/microsoft/azure-pipelines-tasks/blob/868328fff79bd1b789f8bcb568be7886b9b9a8d9/Tasks/SqlAzureDacpacDeploymentV1/SqlAzureActions.ps1#L272

So when using a connection string authentication type with a password with something like a `$` in it, the call to `Invoke-Expression` isn't correct, thus causing what looks like an authentication error.

**Comment by chperich** [comment] 2020-02-13 10:33
@ptfaulkner: We are unable to re-pro this problem on our end. Are you still running into this issue? If yes, can you please set a variable "System.debug" to true, create a release and share the debug logs? A sample of the password you tried out might come handy as well.

**Comment by ptfaulkner** [comment] 2020-02-19 16:15
@chperich I am not still having this issue because I changed my password and removed all the `$`'s in it.  As soon as I as changed the password the error stopped happening.  The password that was failing was about 10 characters with a `$` in the middle.  All the logs say is that there is a login failure when using this password with the `ConnectionString` `Authentication Type`.

**Comment by SumiranAgg** [comment] 2020-03-12 08:28
@ptfaulkner We cannot reproduce the issue. I am closing the issue since you have moved to another password. Feel free to re-open this issue, with requested information, if you run into the error again.

**Closed by SumiranAgg** 2020-03-12 08:28 UTC
Labels: Area: Release, bug
