### ISSUE TITLE
Publish Symbols from Release Manager

### ISSUE THREAD

**Issue by danebou** [Microsoft/azure-pipelines-tasks#6916] opened 2018-04-09 17:01 UTC
Symbols cannot be published from the release manager using the Index Sources & Publish Symbols
version 2.*. 

When attempting to use the task the following error occurs:

`##[error]Required: 'Build.SourcesDirectory' task variable.`

A workaround was described in issue [3897](https://github.com/Microsoft/vsts-tasks/issues/3897#issuecomment-290524004]). But this was patched and does not work anymore. Instead this error occurs when attempting to use the workaround:
`Write-Host "##vso[task.setvariable variable=Build_SourcesDirectory;]$env:SYSTEM_ARTIFACTSDIRECTORY"`

```
##[error]Unable to process command '##vso[artifact.associate artifacttype=SymbolRequest;artifactname=libraries/...]...' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Associating server artifact is not supported in Release.
```

**Comment by GitHubSriramB** [comment] 2018-04-10 07:38
This looks similar to issue 3897. 

@sprendermsft - could you pl. take a look?

**Comment by danebou** [comment] 2018-06-29 19:30
I've come up with a minor workaround for now which setting:
> Continue on error
Ignores the error, and it appears to still successful publish the symbols either way. (The original powershell workaround described in the original issue is still required)

**Comment by alohaninja** [comment] 2019-03-29 01:42
@natemcmaster - looks like you have a fix for this, will this get merged into a new release task?

**Comment by natemcmaster** [comment] 2019-03-29 04:28
They didn’t want to take my fix because they told me they had a better plan to address the issue, so I closed my PR without merging. 

Unfortunately, until there is a fix for this issue, I cannot use the publish symbols task.

**Comment by alohaninja** [comment] 2019-04-04 05:19
@natemcmaster - I just ended up calling this immediately after the build and it works fine. Just using the intended design for this task now. They should disable this task for release definitions and restrict it only for builds since it doesn't work.😉

**Comment by danebou** [comment] 2019-04-04 14:15
But what’s weird is it does work with the workaround. You’d think because of that it wouldn’t be too hard to get fully supporting.  

Top of that publishing is not inherently a build procedure. Especially when you need to build test PRs.

**Comment by mitchdenny** [comment] 2019-04-04 21:39
The issue is that the work around publishes symbols without associating them with a build, which means that they aren't subject to retention. For the time being publishing symbols from a release pipeline is not a supported scenario.

**Closed** 2019-04-04 21:40 UTC
Labels: Area: Release

**Comment by danebou** [comment] 2019-04-05 16:06
@mitchdenny 

What's the workflow then if we need to test build PRs but don't want to publish symbols. Do we really have to manage two build configurations one with the publish symbols and one without?

**Comment by alohaninja** [comment] 2019-04-05 21:31
@mitchdenny  - thanks for the clarification on task support - [looks like there is a regression on pipeline task visibility](https://stackoverflow.com/a/52315549/175679) - this task [shouldn't be showing up for releases by task definition.](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishSymbolsV2/task.json#L10). Would have saved me hours! 😮 

@danebou - you could [use a conditional task](https://www.nebbiatech.com/2019/02/15/variables-and-conditional-build-steps-in-azure-devops/) based upon branch name (!=master,  etc.) or [here if you are using YAML builds](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml). We don't publish symbols for PRs, but we do for CI builds from master.

**Comment by mitchdenny** [comment] 2019-04-06 06:15
@alohaninja - sadly those visibility settings have never resulted in hiding the tasks. Adding @shashban for the feedback though.

**Comment by natemcmaster** [comment] 2019-04-06 11:18
> For the time being publishing symbols from a release pipeline is not a supported scenario.

Is there any plans to change this that I can track on GitHub? My team would still prefer to only publish symbols via release pipeline. We had to invent our own tech to do this which basically duplicates what this task does.

**Comment by danebou** [comment] 2019-04-06 18:04
Thanks for the tip alohaninja!

I agree nate. It would be great to make this a TODO. As far as I'm concerned this issue is hasn't quite been resolved. I understand it being low priority though.

**Comment by danebou** [comment] 2019-04-16 13:55
I really need to double-down on the importance of this issue.

Given the direction of Azure DevOps, it seems pertinent that organizations have a simple method to host their own Nuget packages/debugging symbols, then have CI/CD to support this. While possible, this issue makes it very unnatural for a setup to accomplish this. I'm yet to see a good document from Microsoft explaining the common CI/CD and I can only assume this issue is a contributor of that. I'm inferring this issue is being throw away only for it to continuously re-arise while organizations spend time finding ways around it or switching to different products. 

@mitchdenny Could you elaborate if there's any roadmap to this issue?

**Comment by shashban** [comment] 2019-04-16 15:43
Hello folks, our roadmap has unified YAML pipelines i.e. a common pipeline definition for builds & releases. We'll ensure all capabilities (tasks) are functional across stages in those pipelines. You'll be able to split pipelines into stages, each behaving like a milestone of sorts for the pipeline, with approvals & checks in between.

**Comment by danebou** [comment] 2019-04-16 17:03
Thanks shashban!
