### ISSUE TITLE
Test run fails but it doesn't fail the task - Task keeps running forever unless manual timeout is configured

### ISSUE THREAD

**Issue by MertSenel** [Microsoft/azure-pipelines-tasks#8733] opened 2018-10-30 02:04 UTC
## Environment
- Server - Azure Pipelines or TFS on-premises?  **Azure Pipelinens** 
   

    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    

    - If using private agent, provide the OS of the machine running the agent and the agent version: **[AGENT_VERSION] --> [2.123.0]**

**Windows Server 2016- Azure IaaS VM**

## Issue Description

Test run fails but it doesn't fails the task, so unless we specify a manual timeout control for the Task itself it runs forever, setting up manual timeout for the task is not ideal either. 

This behaviour was different on v1 of this task. When all tests have failed it would fail the task as well and the release would keep continuing. 

### Task logs

[ReleaseLogs_4739.zip](https://github.com/Microsoft/azure-pipelines-tasks/files/2527723/ReleaseLogs_4739.zip)

### Error logs

[Insert error from the logs here for a quick overview]

2018-10-30T01:30:12.0126231Z Microsoft (R) Test Execution Command Line Tool Version 15.8.0
2018-10-30T01:30:12.0126231Z Copyright (c) Microsoft Corporation.  All rights reserved.
2018-10-30T01:30:12.0126231Z 
2018-10-30T01:30:12.0276223Z vstest.console.exe 
2018-10-30T01:30:12.0276223Z "C:\agent\_work\r1\a\Well - Application Build-(Dev Branch)\TEST DLL\bin\Release\Flexstar.AcceptanceTests.dll"
2018-10-30T01:30:12.0276223Z /TestCaseFilter:"Name=UISmokeTest"
2018-10-30T01:30:12.0276223Z /Settings:"C:\agent\_work\_temp\5754e240-dbe3-11e8-84c9-7d084e19c408.runsettings"
2018-10-30T01:30:12.0276223Z /logger:"trx"
2018-10-30T01:30:12.0276223Z /TestAdapterPath:"C:\agent\_work\r1\a\Well - Application Build-(Dev Branch)\TEST DLL\bin\Release"
2018-10-30T01:30:12.0276223Z /diag:"C:\agent\_work\_temp\57463c40-dbe3-11e8-84c9-7d084e19c408.txt"
2018-10-30T01:30:12.7776367Z Starting test execution, please wait...
2018-10-30T01:30:12.7776367Z Logging Vstest Diagnostics in file: C:\agent\_work\_temp\57463c40-dbe3-11e8-84c9-7d084e19c408.txt
2018-10-30T01:30:16.4966816Z Starting ChromeDriver 2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab) on port 57178
2018-10-30T01:30:16.4966816Z Only local connections are allowed.
2018-10-30T01:32:23.6242154Z Failed   UISmokeTest
2018-10-30T01:32:23.6436250Z Error Message:
2018-10-30T01:32:23.6436250Z  Class Initialization method Flexstar.AcceptanceTests.UITests.SmokeTests.UISmokeTests.SetupTests threw exception. OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:57178/session/6b6655e577621055885369047d074fde/execute_async timed out after 120 seconds. ---> System.Net.WebException: The operation has timed out.
2018-10-30T01:32:23.6436250Z Stack Trace:
2018-10-30T01:32:23.6436250Z    at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2018-10-30T01:32:23.6436250Z    at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2018-10-30T01:32:23.6436250Z    at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2018-10-30T01:32:23.6436250Z    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2018-10-30T01:32:23.6436250Z    at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
2018-10-30T01:32:23.6436250Z    at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteAsyncScript(String script, Object[] args)
2018-10-30T01:32:23.6436250Z    at Protractor.NgWebDriver.set_Url(String value) in c:\Users\Bruno\Projets\GitHub\bbaia\protractor-net\src\Protractor\NgWebDriver.cs:line 163
2018-10-30T01:32:23.6436250Z    at Flexstar.AcceptanceTests.WellFunctions.initializeDriverAndNavigate(String url, Int32 timeoutSeconds) in C:\agent\_work\3\s\Development-branch\Flexstar.AcceptanceTests\WellFunctions.cs:line 103
2018-10-30T01:32:23.6436250Z    at Flexstar.AcceptanceTests.UITests.SmokeTests.UISmokeTests.SetupTests(TestContext testContext) in C:\agent\_work\3\s\Development-branch\Flexstar.AcceptanceTests\UITests\UISmokeTests.cs:line 37
2018-10-30T01:32:23.6436250Z 
2018-10-30T01:32:23.6436250Z Standard Output Messages:
2018-10-30T01:32:23.6436250Z  Navigating to: https://*****************/
2018-10-30T01:32:23.6436250Z  timeoutSeconds: 120
2018-10-30T01:32:23.6436250Z 
2018-10-30T01:32:23.6436250Z 
2018-10-30T01:32:23.6711037Z Results File: C:\agent\_work\r1\a\TestResults\BuildSvcAcct_DEV-TEST-UAT-VM_2018-10-30_12_32_23.trx
2018-10-30T01:32:23.6711037Z 
2018-10-30T01:32:23.6711037Z Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
2018-10-30T01:32:23.6711037Z Test Run Failed.
2018-10-30T01:32:23.6711037Z Test execution time: 2.1709 Minutes
2018-10-30T01:34:04.8322974Z ##[error]The task has timed out.
2018-10-30T01:34:04.8322974Z ##[section]Finishing: UISmokeTest - Task v2

**Comment by kaadhina** [comment] 2018-11-01 06:50
Most likely the test is not cleaning up any processes it started (such as browser, driver exe). Please ensure all these are cleaned up before the test completes. You can find out the root cause by logging onto the agent machine, use a proc explorer to see what process is stale under vstest exe

**Comment by MertSenel** [comment] 2018-11-08 00:39
I've monitored the agent and this is how it looks while the run is going 

![image](https://user-images.githubusercontent.com/32119844/48169994-bb57a080-e349-11e8-944b-6a7043a23a27.png)

And after between 2-3 minutes the test is failing and worker is releasing the chromedriver.exe 

However as you can see the task's conhost.exe is continues to run 

![image](https://user-images.githubusercontent.com/32119844/48170040-ef32c600-e349-11e8-9d83-31305636ef34.png)

This is the screenshot from the VSTS GUI.  
![image](https://user-images.githubusercontent.com/32119844/48170081-14bfcf80-e34a-11e8-82d3-6d6d1a9c86f2.png)

The task doesn't stop. I would like to repeat the behaviour is different on VSTS task v1 
task v1 does not support VS2017 vstest.console.exe path by default but if I specify it manually it works as intended for us and task fails when test fails.  However this is a workaround and I would like to upgrade to task v2. 

If you require more logs, screen recording of proc explorer etc. let me know. 

@cameronmco

**Comment by Izzmo** [comment] 2018-11-15 03:51
+1 I'm also having this issue.

**Comment by Ryanman** [comment] 2018-11-15 22:14
+1 Also having this issue executing functional UI tests with Selenium and NOT using chrome (IE).

`Publishing test case results
Published test case results
Publishing test run level attachments
Published test run level attachments
Slice with id = 218, of type = 'Execution' finished.
Test run '4311' is in 'Completed' state with 'Total Tests' : 9 and 'Passed Tests' : 8.
System.Exception: Some tests in the test run did not pass, failing the task.
##########################################################################`

After this the task never fails, never reports to the server. I've tried a number of different variable values and adding a "dummy" powershell task afterwards to no avail. Obviously if all tests succeed it also does not report.

I, too, can provide anything asked for in terms of logs etc. This seems identical  to #8838. OnPrem TFS 2018.

**Comment by prawalagarwal** [comment] 2018-11-27 08:08
@MertSenel @Izzmo Does browser.Quit() solve your issue?

**Comment by MertSenel** [comment] 2018-11-28 06:16
> @MertSenel @Izzmo Does browser.Quit() solve your issue?

We are already using browser.quit();  in our ClassCleanup, yet we are still experiencing this issue. 

@cameronmco

**Comment by manu4rhyme** [comment] 2018-11-28 15:48
Hi,

I have been facing the same issue, while trying to on board our product to continuous testing using Selenium. Locally all our Selenium tests are passing, however they are failing on AzDev Ops instead.

I’ve tried following this tutorial
https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=vsts

But I’m facing few issues:

Unable to finish/terminate VSTest task (it keeps running indefinitely until I add timeout in control options)
Unable to collect video recordings of the test run https://docs.microsoft.com/en-us/azure/devops/test/collect-screenshots-and-video?view=vsts , so cannot debug failures on the pipeline
Clearly, if the VSTest task were to terminate gracefully, it should ideally publish test results including screenshots/video_recordings, so that we could debug why some test cases are failing on remote agent.

But the VSTest task is not closing, I've already tried multiple timeout values and hosted agent versions but still the same issue.

I've also mailed multiple instances of my logs during testing, to devops_tools@microsoft.com

Also I've tried browser.Quit() as well with no help.

**Comment by prawalagarwal** [comment] 2018-12-10 09:10
@MertSenel Can you go through this [post](https://stackoverflow.com/questions/15067107/difference-between-webdriver-dispose-close-and-quit) to see if this helps? I wil suggest to use both driver.quit and driver.dispose in your cleanup. Let us know if this helps.

**Comment by prawalagarwal** [comment] 2018-12-13 05:12
@MertSenel Any updates here?

**Comment by ShreyasRmsft** [comment] 2018-12-27 08:38
@MertSenel did Prawal latest suggestion work for you?

`@MertSenel Would like you try two things:

Instead of ClassCleanup, please keep these dispose commands in TestCleanup.
If the above doesn't work, please use a try-finally block around your tests with the finally block containing these dispose commands.`

**Comment by ppopowicz** [comment] 2019-01-10 14:36
It appears I am facing the same issue with our tests, selenium tests execute, fail, and the VSTest Task never completes just hangs.

**Comment by ShreyasRmsft** [comment] 2019-01-11 05:19
can you please try this and tell us if the problem still persists?

> If the above doesn't work, please use a try-finally block around your tests with the finally block containing these dispose commands.

**Comment by ppopowicz** [comment] 2019-01-11 13:46
> can you please try this and tell us if the problem still persists?
> 
> > If the above doesn't work, please use a try-finally block around your tests with the finally block containing these dispose commands.

That appears to resolve the issue, I wrapped the line of code throwing an exception in a try catch with a call to Browser.Close() then Browser.Quit() then Browser.Dispose(). That allowed the test to complete. Without the try catch even with those calls in the teardown the step hangs. I'm hoping this can be fixed.

**Comment by ppopowicz** [comment] 2019-01-11 14:03
I've actually noticed the test hangs even if it successfully completes if I don't call Browser.Quit() inside the test method but instead call it inside the teardown step.

**Comment by ShreyasRmsft** [comment] 2019-01-29 08:09
@ppopowicz the rollout is complete, the task shouldn't be hanging anymore can you check and get back to us if the issue is solved for you?

**Closed** 2019-01-31 05:49 UTC
Labels: Area: Test
