### ISSUE TITLE
Unit tests passing but dotnet.exe fails

### ISSUE THREAD

**Issue by phatcher** [microsoft/azure-pipelines-tasks#13059] opened 2020-06-03 09:55 UTC
## Required Information
 
*Type*: Bug

**Enter Task Name**: DotNetCoreCLI

## Environment
- Server - Azure Pipelines     
- Agent - Hosted   

## Issue Description

The unit step test of my pipeline has started failing, even though the tests pass; lots of other pipelines with the same structure pass, can't see any differences.

```
- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  inputs:
    command: 'test'
    projects: 'Meerkat.EntityFrameworkCore.sln'
    arguments: '--no-build --configuration Release --filter "(TestCategory!=Integration)&(TestCategory!=Smoke)" --settings coverlet.runsettings'
    testRunTitle: 'Unit Tests'
    publishTestResults: true

```
### Task logs
```
Starting: Unit Tests
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.169.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
C:\windows\system32\chcp.com 65001
Active code page: 65001
"C:\Program Files\dotnet\dotnet.exe" test D:\a\1\s\Meerkat.EntityFrameworkCore.sln --logger trx --results-directory D:\a\_temp --no-build --configuration Release --filter (TestCategory!=Integration)&(TestCategory!=Smoke) --settings coverlet.runsettings
Test run for D:\a\1\s\src\Meerkat.EntityFrameworkCore.Test\bin\Release\netcoreapp2.2\Meerkat.EntityFrameworkCore.Test.dll(.NETCoreApp,Version=v2.2)
D:\a\1\s\src\Training.Database\Training.Database.sqlproj(56,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.1.202\Microsoft\VisualStudio\v11.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\3.1.202\\Microsoft\VisualStudio\v11.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets" is correct, and that the file exists on disk.
Microsoft (R) Test Execution Command Line Tool Version 16.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Results File: D:\a\_temp\VssAdministrator_WIN-8RQJFJRHPBU_2020-06-03_09_23_07.trx

Attachments:
  D:\a\_temp\da6aa31a-ad43-4425-be2e-84b4c1c1b02e\coverage.cobertura.xml
Test Run Successful.
Total tests: 10
     Passed: 10
 Total time: 6.4511 Seconds
Test run for D:\a\1\s\src\Meerkat.EntityFrameworkCore.Test\bin\Release\netcoreapp3.0\Meerkat.EntityFrameworkCore.Test.dll(.NETCoreApp,Version=v3.0)
Microsoft (R) Test Execution Command Line Tool Version 16.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Results File: D:\a\_temp\VssAdministrator_WIN-8RQJFJRHPBU_2020-06-03_09_23_11.trx

Attachments:
  D:\a\_temp\1f259d8a-ae74-4c2c-98a4-9bd5f7804bc8\coverage.cobertura.xml
Test Run Successful.
Total tests: 10
     Passed: 10
 Total time: 2.3511 Seconds
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
Info: Azure Pipelines hosted agents have been updated to contain .Net Core 3.x (3.0 and 3.1) SDK/Runtime along with 2.1. Unless you have locked down a SDK version for your project(s), 3.x SDK might be picked up which might have breaking behavior as compared to previous versions. 
Some commonly encountered changes are: 
If you're using `Publish` command with -o or --Output argument, you will see that the output folder is now being created at root directory rather than Project File's directory. To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : D:\a\1\s\Meerkat.EntityFrameworkCore.sln
Async Command Start: Publish test results
Publishing test results to test run '1684058'
Publishing test results to test run '1684060'
Test results remaining: 10. Test run id: 1684058
Test results remaining: 10. Test run id: 1684060
Published Test Run : https://tfsprodweusu4.visualstudio.com/A3a3c2e63-e677-45e2-85b4-ea79de6c4e61/EXCITE/_TestManagement/Runs?runId=1684060&_a=runCharts
Published Test Run : https://tfsprodweusu4.visualstudio.com/A3a3c2e63-e677-45e2-85b4-ea79de6c4e61/EXCITE/_TestManagement/Runs?runId=1684058&_a=runCharts
Async Command End: Publish test results
Finishing: Unit Tests


```

**Comment by issacnitin** [comment] 2020-06-03 10:45
@phatcher Could you let us know if the command works fine in local environment? 
There seems to be a limitation with dotnet core CLI to build sqlproj. Reference: https://github.com/dotnet/sdk/issues/10441

**Comment by issacnitin** [comment] 2020-06-03 10:48
The accepted solution is to use VsBuild/VsTest task

**Comment by phatcher** [comment] 2020-06-04 10:23
@issacnitin Unfortunately I can't easily switch it to the VsTest task as that takes assemblies rather than projects.

I change the task so that rather than running against the solution, it ran against the test projects e.g. **/*.Test.csproj, unfortunately although the sqlproj project was not referenced by any of the other projects in the solution, it was somehow detected by the dotnet test command.

My solution at the moment is to exclude the sqlproj from the Release build, that means that the project is no longer detected by dotnet test; I'll see if I can produce a repo to further isolate the behaviour.

**Comment by issacnitin** [comment] 2020-06-04 11:43
Awesome, thanks @phatcher, do let us know once you have an easily reproable scenario. If the issue can be reproduced locally, I'd recommend you take the issue with https://github.com/dotnet/sdk/ as they'll be able to help you better.

**Comment by anuragc617** [comment] 2020-06-19 14:32
@phatcher it seems that you have got a work around, should we close this issue?

**Comment by anuragc617** [comment] 2020-06-19 14:32
@phatcher it seems that you have got a workaround, should we close this issue?

**Comment by anuragc617** [comment] 2020-06-24 05:14
Closing this issue there is no active query.

**Closed by anuragc617** 2020-06-24 05:14 UTC
Labels: Area: Release, bug
