### ISSUE TITLE
@AzureWebApp Failed to Deploy: Thread was being aborted

### ISSUE THREAD

**Issue by AndresPeralta** [microsoft/azure-pipelines-tasks#12479] opened 2020-03-04 16:33 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure Web App (1.163.2)

## Environment
- Server - Azure Pipelines
      
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:
           Account Name: azurecom, Project Name: acom, ReleaseId=44427

- Private Agent: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
              -  Agent.OS: Windows_NT, Agent.OSVersion: 10.0.14393, Agent Version: 2.165.0

## Issue Description

We're getting the intermittent error "Thread was being aborted". 
![imagen](https://user-images.githubusercontent.com/40349052/75896424-d939f600-5e15-11ea-94ae-4a817cc74c83.png)

### Task logs

```
2020-03-04T05:45:43.2881139Z ##[section]Starting: Deploy xxx (eastasia)
2020-03-04T05:45:43.3033523Z ==============================================================================
2020-03-04T05:45:43.3037906Z Task         : Azure Web App
2020-03-04T05:45:43.3038231Z Description  : Deploy an Azure Web App for Linux or Windows
2020-03-04T05:45:43.3038442Z Version      : 1.163.2
2020-03-04T05:45:43.3038646Z Author       : Microsoft Corporation
2020-03-04T05:45:43.3039055Z Help         : https://aka.ms/azurewebapptroubleshooting
2020-03-04T05:45:43.3039345Z ==============================================================================
2020-03-04T05:45:45.2368179Z Got service connection details for Azure App Service:'xxx-eastasia-02'
2020-03-04T05:45:46.5833595Z Deleting App Service Application settings. Data: ["WEBSITE_RUN_FROM_PACKAGE","WEBSITE_RUN_FROM_ZIP"]
2020-03-04T05:45:47.6771140Z Updated App Service Application settings and Kudu Application settings.
2020-03-04T05:45:49.9381883Z Package deployment using ZIP Deploy initiated.
2020-03-04T05:50:56.1510058Z Updating submodules.
2020-03-04T05:50:56.1510364Z Preparing deployment for commit id '345a625d7a'.
2020-03-04T05:50:56.1510592Z Generating deployment script.
2020-03-04T05:50:56.8752016Z Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "D:\local\Temp\zipdeploy\extracted" -o "D:\home\site\deployments\tools" --basic --sitePath "D:\local\Temp\zipdeploy\extracted"').
2020-03-04T05:50:56.8752597Z Running deployment command...
2020-03-04T05:50:57.7138955Z Command: "D:\home\site\deployments\tools\deploy.cmd"
2020-03-04T05:50:57.7139275Z Handling Basic Web Site deployment.
2020-03-04T05:50:57.7139453Z Creating app_offline.htm
2020-03-04T05:50:57.7139807Z KuduSync.NET from: 'D:\local\Temp\zipdeploy\extracted' to: 'D:\home\site\wwwroot'
2020-03-04T05:50:57.7140189Z Copying file: 'ApplicationInsights.config'
2020-03-04T05:50:57.7140408Z Copying file: 'Global.asax'
2020-03-04T05:50:57.7140609Z Copying file: 'googled9fe0b0c7b4b4ecd.html'
2020-03-04T05:50:57.7140842Z Copying file: 'log4net.dll'
2020-03-04T05:50:57.7141034Z Copying file: 'Onyx.Mvc.Contracts.XML'
2020-03-04T05:50:57.7141299Z Copying file: 'Onyx.Mvc.CulturesApi.XML'
2020-03-04T05:50:57.7141608Z Copying file: 'views-metadata.json'
2020-03-04T05:50:57.7141856Z Copying file: 'App_Data\analytics-blacklisted-agents.json'
2020-03-04T05:50:57.7142128Z Copying file: 'App_Data\analytics-custom-properties-whitelist.json'
2020-03-04T05:50:57.7142400Z Copying file: 'App_Data\ServicesStatus.xml'
2020-03-04T05:50:57.7142612Z Copying file: 'App_Data\tenants.json'
2020-03-04T05:50:57.7142824Z Copying file: 'App_Data\users.json'
2020-03-04T05:50:57.7143033Z Copying file: 'bin\Acom.CognitiveServices.dll'
2020-03-04T05:50:57.7143313Z Copying file: 'bin\Acom.CognitiveServices.dll.config'
2020-03-04T05:50:57.7143562Z Copying file: 'bin\Acom.CognitiveServices.pdb'
2020-03-04T05:50:57.7143769Z Copying file: 'bin\Acom.Email.dll'
2020-03-04T05:50:57.7143985Z Copying file: 'bin\Acom.Email.dll.config'
2020-03-04T05:50:57.7144193Z Copying file: 'bin\Acom.Email.pdb'
2020-03-04T05:50:57.7144408Z Copying file: 'bin\Acom.Entities.dll'
2020-03-04T05:50:57.7144618Z Copying file: 'bin\Acom.Entities.dll.config'
2020-03-04T05:50:57.7144844Z Copying file: 'bin\Acom.Entities.pdb'
2020-03-04T05:50:57.7145059Z Copying file: 'bin\Acom.Json.DisplayStrings.dll'
2020-03-04T05:50:57.7145315Z Copying file: 'bin\Acom.Json.DisplayStrings.dll.config'
2020-03-04T05:50:57.7145825Z Copying file: 'bin\Acom.Json.DisplayStrings.pdb'
2020-03-04T05:50:57.7146053Z Copying file: 'bin\Acom.Json.dll'
2020-03-04T05:50:57.7146255Z Copying file: 'bin\Acom.Json.dll.config'
2020-03-04T05:50:57.7146472Z Copying file: 'bin\Acom.Json.pdb'
2020-03-04T05:50:57.7146682Z Copying file: 'bin\Acom.Messaging.dll'
2020-03-04T05:50:57.7146897Z Copying file: 'bin\Acom.Messaging.dll.config'
2020-03-04T05:50:57.7147124Z Copying file: 'bin\Acom.Messaging.pdb'
2020-03-04T05:50:57.7147329Z Copying file: 'bin\Acom.Pricing.dll'
2020-03-04T05:50:57.7148350Z Copying file: 'bin\Acom.Pricing.dll.config'
2020-03-04T05:50:57.7148562Z Copying file: 'bin\Acom.Pricing.pdb'
2020-03-04T05:50:57.7148779Z Copying file: 'bin\ACOM.Resources.dll'
2020-03-04T05:50:57.7148985Z Copying file: 'bin\ACOM.Resources.pdb'
2020-03-04T05:50:57.7149201Z Copying file: 'bin\Acom.Search.dll'
2020-03-04T05:50:57.7149408Z Copying file: 'bin\Acom.Search.dll.config'
2020-03-04T05:50:57.7149634Z Copying file: 'bin\Acom.Search.pdb'
2020-03-04T05:50:57.7149842Z Copying file: 'bin\Acom.SharedHelpers.dll'
2020-03-04T05:50:57.7150080Z Copying file: 'bin\Acom.SharedHelpers.dll.config'
2020-03-04T05:50:57.7150304Z Copying file: 'bin\Acom.SharedHelpers.pdb'
2020-03-04T05:50:57.7150519Z Copying file: 'bin\ACOM.Web.dll'
2020-03-04T05:50:57.7150707Z Copying file: 'bin\ACOM.Web.pdb'
2020-03-04T05:50:57.7150907Z Copying file: 'bin\ACOM.Web.XML'
2020-03-04T05:50:57.7151103Z Copying file: 'bin\AntiXSSLibrary.dll'
2020-03-04T05:50:57.7151333Z Copying file: 'bin\ApplicationInsights.config'
2020-03-04T05:50:57.7151542Z Copying file: 'bin\log4net.dll'
2020-03-04T05:50:57.7151765Z Copying file: 'bin\Microsoft.CookieCompliance.dll'
2020-03-04T05:50:57.7151980Z Omitting next output lines...
2020-03-04T05:50:57.7152143Z Processed 143 files...
2020-03-04T05:50:57.7152309Z Processed 717 files...
2020-03-04T05:50:57.7152463Z Processed 1384 files...
2020-03-04T05:50:57.7152629Z Processed 2005 files...
2020-03-04T05:50:57.7152786Z Processed 2645 files...
2020-03-04T05:50:57.7152953Z Processed 3269 files...
2020-03-04T05:50:57.7153105Z Processed 3897 files...
2020-03-04T05:50:57.7153269Z Processed 4580 files...
2020-03-04T05:50:57.7153422Z Processed 5049 files...
2020-03-04T05:50:57.7153585Z Processed 5515 files...
2020-03-04T05:50:57.7153737Z Processed 5971 files...
2020-03-04T05:50:57.7153905Z Thread was being aborted.
2020-03-04T05:50:57.7154252Z Thread was being aborted.
2020-03-04T05:50:57.7178144Z ##[error]Failed to deploy web package to App Service.
2020-03-04T05:50:57.7188038Z ##[error]To debug further please check Kudu stack trace URL : https://$xxx-eastasia-02__Staging:***@xxx-eastasia-02-staging.scm.azurewebsites.net/api/vfs/LogFiles/kudu/trace
2020-03-04T05:50:57.7189314Z ##[error]Error: Package deployment using ZIP Deploy failed. Refer logs for more details.
2020-03-04T05:50:58.6092461Z Successfully updated deployment History at https://xxxx-eastasia-02-staging.scm.azurewebsites.net/api/deployments/444271583301057708
2020-03-04T05:50:59.7292985Z App Service Application URL: http://xxx-eastasia-02-staging.azurewebsites.net
2020-03-04T05:50:59.7464868Z ##[section]Finishing: Deploy xxxx (eastasia)
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
```
Trace info from Kudu:
<step title="Error occurred" date="2020-03-04T05:50:51.500" type="error" text="Thread was being aborted." stackTrace="   at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Kudu.Core.Deployment.FetchDeploymentManager.&lt;&gt;c__DisplayClass11_1.&lt;PerformBackgroundDeployment&gt;b__3() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 343
   at Kudu.Contracts.Infrastructure.LockExtensions.TryLockOperation(IOperationLock lockObj, Action operation, String operationName, TimeSpan timeout) in C:\Kudu Files\Private\src\master\Kudu.Contracts\Infrastructure\LockExtensions.cs:line 35
   at Kudu.Contracts.Infrastructure.LockExtensions.LockOperation(IOperationLock lockObj, Action operation, String operationName, TimeSpan timeout) in C:\Kudu Files\Private\src\master\Kudu.Contracts\Infrastructure\LockExtensions.cs:line 46
   at Kudu.Core.Deployment.FetchDeploymentManager.&lt;&gt;c__DisplayClass11_0.&lt;PerformBackgroundDeployment&gt;b__1() in C:\Kudu Files\Private\src\master\Kudu.Core\Deployment\FetchDeploymentManager.cs:line 323" />
                <!-- duration: 16ms -->
```

**Comment by SumiranAgg** [comment] 2020-03-05 07:43
@AndresPeralta This error occurs when we make kudu rest call to zipDeploy your package. You can check https://github.com/projectkudu/kudu/issues/2089 thread and try suggestions like increasing SCM_COMMAND_IDLE_TIMEOUT or this could be caused by using a free site that runs our of quota.

For any more information or help you can open issue on projectkudu.

**Comment by SumiranAgg** [comment] 2020-03-11 07:08
Assuming the previous comment helped. Closing this issue for now. Feel free to reopen if required.

**Closed by SumiranAgg** 2020-03-11 07:08 UTC
Labels: Area: Release, bug
