### ISSUE TITLE
The FileTransformV2 task does not correctly escape XML values

### ISSUE THREAD

**Issue by aarondandy** [microsoft/azure-pipelines-tasks#12355] opened 2020-02-13 19:40 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

*Type*: Bug

**Enter Task Name**: FileTransformV2  

## Environment
- Server - Azure Pipelines
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number:  N/A

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines

## Issue Description

The FileTransformV2 task does not correctly escape attribute values when updating an XML file.

If you try to update a settings variable with a value such as "Apples & Oranges" invalid XML will be generated. Values written to XML should be escaped correctly.

## Notes

I can't really tell what is going on from reading the code but I suspect that a direct text replacement is being made after a placeholder token of some kind is inserted, instead of manipulating the XML document directly and allowing escaping to take place. This indicates to me that avoiding the correct XML escaping was intended behavior which is troubling. If that is the case perhaps there should be a toggle to allow users to select between normal behavior and corner-case behavior. I feel it would be common for a user to expect XML to be generated correctly as a default and direct text replacement should be an explicit override, that is just my opinion though.

https://github.com/microsoft/azure-pipelines-tasks/blob/12273b195c3477d3bd9eb0d482ee55d7b25c7e99/Tasks/Common/webdeployment-common-v2/xmlvariablesubstitutionutility.ts#L216

**Comment by aarondandy** [comment] 2020-02-26 14:18
Can somebody confirm if this is expected behavior or a bug? Obviously this is going to be a breaking change for any users if you wanted to change the default behavior, so it would be a big deal to change. I am asking because I am curious if I should be making my own task to update XML app.config files.

**Comment by SumiranAgg** [comment] 2020-03-11 05:54
@aarondandy I cannot reproduce the issue. I am able to successfully substitute a value containing & in my sample xml.

Original Content:
![image](https://user-images.githubusercontent.com/8316321/76386556-ccc01b00-638a-11ea-91d9-58ceb1dac956.png)

Transformed content:
![image](https://user-images.githubusercontent.com/8316321/76386592-df3a5480-638a-11ea-96dd-358a3a7ee8dd.png)

Can you help me with steps on how to repro the issue.

**Comment by SumiranAgg** [comment] 2020-03-11 07:04
We used to handle special characters but it was causing issues in case of connectionstring/ other passwords. Hence we removed the support and expect the user to provide escaped value in the variable itself. You can try this as a workaround. 
This is duplicate of #12320. Please follow the issue for more info. Closing this as dupe.

**Closed by SumiranAgg** 2020-03-11 07:04 UTC
Labels: Area: Release, bug

**Comment by aarondandy** [comment] 2020-03-11 13:52
I found another related issue (not a dupe) that seems to be the root cause of this problem: #4001

**Comment by knunery** [comment] 2021-11-10 15:38
Can we reopen this issue? It should escape special xml characters when doing substitutions in an xml file. We have variables that need to be fed to xml and json files so preescaping a variable doesn't work.
