### ISSUE TITLE
VSTestV2: Tests are running twice in Azure devops pipeline

### ISSUE THREAD

**Issue by yorhpokie** [microsoft/azure-pipelines-tasks#12184] opened 2020-01-21 18:45 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VSTestV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: https://dev.azure.com/mediakind/MediaFirst/_build/results?buildId=278334&view=logs

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows 10 Enterprise, Agent version 
[logs_278334.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4092976/logs_278334.zip)
2.144.0

## Issue Description

Issue was reported here by my colleague Mohan Sheshadri:
https://developercommunity.visualstudio.com/content/problem/891521/tests-are-running-twice-in-azure-devops-pipeline.html

### Task logs

[logs_278334.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4092997/logs_278334.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

from the logs its clear that each test is run twice.. there are 9 tests that are run as part of the build.. but logs shows 18 tests (each test runs twice) 2020-01-21T10:24:46.3583892Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.BulkAccountOperationsTests.SubscriberFunctionalTests_BulkOffersToAccount_SuccessOnExecution SubscriberFunctionalTests_BulkOffersToAccount_SuccessOnExecution 2020-01-21T10:24:48.5599109Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:24:48.5600595Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.BulkAccountOperationsTests.SubscriberFunctionalTests_BulkOffersToAccount_RemoveOpFailWithBadParams SubscriberFunctionalTests_BulkOffersToAccount_RemoveOpFailWithBadParams 2020-01-21T10:24:51.4012444Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:24:51.4013465Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.DevicePropertiesTests.SubscriberFunctionalTests_DeviceProperties_ApiVerify SubscriberFunctionalTests_DeviceProperties_ApiVerify 2020-01-21T10:24:54.6390757Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:24:54.6391717Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.DownloadTests.SubscriberFunctionalTests_DownloadTests_BulkDelete SubscriberFunctionalTests_DownloadTests_BulkDelete 2020-01-21T10:24:56.2552131Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:24:56.2554807Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.DownloadTests.SubscriberFunctionalTests_DownloadTests_DeleteAllForLoggedInDevice SubscriberFunctionalTests_DownloadTests_DeleteAllForLoggedInDevice 2020-01-21T10:24:58.7001370Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:24:58.7003757Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.DownloadTests.SubscriberFunctionalTests_DownloadTests_GetDownloadByAssetType SubscriberFunctionalTests_DownloadTests_GetDownloadByAssetType 2020-01-21T10:25:08.2582419Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:25:08.2585605Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.LibraryByIdTestsV4.SubscriberFunctionalTests_LibraryByIdTestV4_DownLoadandGo_CatalogInfo_Entitlements_NoError SubscriberFunctionalTests_LibraryByIdTestV4_DownLoadandGo_CatalogInfo_Entitlements_NoError 2020-01-21T10:25:59.2777620Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:25:59.2778115Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.ProgramPlayOptionsTests.SubscriberFunctionalTests_ProgramPlayOptions_DownloadCount SubscriberFunctionalTests_ProgramPlayOptions_DownloadCount 2020-01-21T10:26:03.5543108Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:26:03.5543977Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.VodMediaRightsTests.SubscriberFunctionalTests_GetVodMediaRights_DownloadAssetScenario_NoError SubscriberFunctionalTests_GetVodMediaRights_DownloadAssetScenario_NoError 2020-01-21T10:26:05.0238646Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:26:21.9934303Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:26:21.9935036Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.BulkAccountOperationsTests.SubscriberFunctionalTests_BulkOffersToAccount_SuccessOnExecution SubscriberFunctionalTests_BulkOffersToAccount_SuccessOnExecution 2020-01-21T10:26:24.1036050Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:26:24.1037604Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.BulkAccountOperationsTests.SubscriberFunctionalTests_BulkOffersToAccount_RemoveOpFailWithBadParams SubscriberFunctionalTests_BulkOffersToAccount_RemoveOpFailWithBadParams 2020-01-21T10:26:26.7037598Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:26:26.7041200Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.DevicePropertiesTests.SubscriberFunctionalTests_DeviceProperties_ApiVerify SubscriberFunctionalTests_DeviceProperties_ApiVerify 2020-01-21T10:26:29.3363688Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:26:29.3365698Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.DownloadTests.SubscriberFunctionalTests_DownloadTests_BulkDelete SubscriberFunctionalTests_DownloadTests_BulkDelete 2020-01-21T10:26:31.5776238Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:26:31.5776908Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.DownloadTests.SubscriberFunctionalTests_DownloadTests_DeleteAllForLoggedInDevice SubscriberFunctionalTests_DownloadTests_DeleteAllForLoggedInDevice 2020-01-21T10:26:33.7874656Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:26:33.7875313Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.DownloadTests.SubscriberFunctionalTests_DownloadTests_GetDownloadByAssetType SubscriberFunctionalTests_DownloadTests_GetDownloadByAssetType 2020-01-21T10:26:37.7722461Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:26:37.7722970Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.LibraryByIdTestsV4.SubscriberFunctionalTests_LibraryByIdTestV4_DownLoadandGo_CatalogInfo_Entitlements_NoError SubscriberFunctionalTests_LibraryByIdTestV4_DownLoadandGo_CatalogInfo_Entitlements_NoError 2020-01-21T10:27:28.8018813Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:27:28.8036247Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.ProgramPlayOptionsTests.SubscriberFunctionalTests_ProgramPlayOptions_DownloadCount SubscriberFunctionalTests_ProgramPlayOptions_DownloadCount 2020-01-21T10:27:33.9819704Z ##[debug]ProxyRunRequest: HandleTestRunComplete Entered 2020-01-21T10:27:33.9821281Z ##[debug]ProxyRunRequest: HandleTestRunStatsChange Entered 2020-01-21T10:27:33.9821755Z Passed Microsoft.TV.Cloud.FunctionalTest.TestScripts.Subscriber.VodMediaRightsTests.SubscriberFunctionalTests_GetVodMediaRights_DownloadAssetScenario_NoError SubscriberFunctionalTests_GetVodMediaRights_DownloadAssetScenario_NoError

**Comment by vagisha-nidhi** [comment] 2020-01-22 13:02
@yorhpokie We have mitigated the issue for now. Can you please create another build and check if the issue is still reproing?

**Comment by yorhpokie** [comment] 2020-01-22 18:38
The issue seems to be resolved in the latest test builds!  @vagisha-nidhi, thank you for the quick turnaround!  Please let me know when you have implemented the full fix and we can try it out.

**Comment by yorhpokie** [comment] 2020-01-22 22:45
Actually, we're seeing repro of this issue again today.  The latest test build is at https://dev.azure.com/mediakind/MediaFirst/_build/results?buildId=280591&view=logs.  Please review, @vagisha-nidhi and @ShreyasRmsft.  Thanks!

**Comment by vagisha-nidhi** [comment] 2020-01-23 05:24
@yorhpokie Is the issue still reproing for you? Can you share the logs of the latest builds where you see this?

**Comment by yorhpokie** [comment] 2020-01-23 23:02
The builds are looking good since this morning.  I will keep monitoring the builds and keep you updated, @vagisha-nidhi.

**Comment by vagisha-nidhi** [comment] 2020-01-24 04:21
Thanks @yorhpokie

**Comment by yorhpokie** [comment] 2020-01-25 00:45
We're seeing the double runs again today...

**Comment by yorhpokie** [comment] 2020-01-27 23:48
@vagisha-nidhi, some runs ran test cases once, but some ran test cases twice.  Please look into this ASAP as this breaks our pipeline.  One of the latest runs is at https://dev.azure.com/mediakind/MediaFirst/_build/results?buildId=288701.

**Comment by sulabh-msft** [comment] 2020-01-29 18:16
@yorhpokie , We deployed the mitigation/fix on the org "mediakind". So This issue shouldn't happen in this org.

**Comment by vagisha-nidhi** [comment] 2020-01-31 12:18
Closing the issue since the fix has been deployed. Please reopen if this occurs again.

**Closed by vagisha-nidhi** 2020-01-31 12:18 UTC
Labels: Area: Test, bug

**Comment by subhaKiruba** [comment] 2020-07-13 09:24
im facing it today after including codeCoverage in the yml file
Can someone please let me know if this is fixed ? and what is the cause for this twice execution ?

**Comment by ShreyasRmsft** [comment] 2020-07-13 11:14
@subhaKiruba please open a new issue with all details such as onprem or hosted, versions, task logs zip with system.debug with the issue and before turning on codecoverage option and link the new issue here.

**Comment by subhaKiruba** [comment] 2020-07-13 11:40
sure will update in few mins

**Comment by samridhamla06** [comment] 2022-07-12 11:40
Is there a further update on this?

**Comment by samridhamla06** [comment] 2022-07-12 11:41
with codecoverage enabled, tests run twice for me too and 2nd run is failing for some reason

**Comment by gnaneshwar-kondapaka** [comment] 2022-10-04 05:27
do we have any update on this ?
I am facing same issue while executing the scenarios using azure pipeline (selenium+specflow)

**Comment by gnaneshwar-kondapaka** [comment] 2022-10-04 05:29
> sure will update in few mins

@subhaKiruba - please let us if you were you able to resolve the issue. I am struggling to solve this issue.
