### ISSUE TITLE
File Transform (preview) does not work

### ISSUE THREAD

**Issue by jepzen** [Microsoft/azure-pipelines-tasks#9571] opened 2019-02-13 13:16 UTC
Im trying to use the File Transform (Preview) in my release pipeline but nothing gets transformed. I named my stage PP and i have a config named Web.PP.config. I turn on debug and it does seem to pick up the right stage. 

I can see in my previous step the Web.PP.config is downloaded from the artifact folder.

Log

```
2019-02-13T12:11:39.9891155Z ##[debug]release.environments.PP.status=InProgress
2019-02-13T12:11:39.9891666Z ##[debug]agent.id=5
2019-02-13T12:11:39.9892213Z ##[debug]release.artifacts._Build Master.projectId=21e97914-0468-4057-b0cd-c76ca34e6ed9
2019-02-13T12:11:39.9892369Z ##[debug]build.buildNumber=4.5.5+2
2019-02-13T12:11:39.9892662Z ##[debug]release.artifacts._Build Master.definitionName=Build Master

.. //finds my main web.config
2019-02-13T12:11:40.0288840Z ##[debug]Initiated variable substitution in config file : D:\a\_temp\temp_web_package_21249088411579398\Content\D_C\a\1\s\MyProject.Web\obj\Release\Package\PackageTmp\Web.config
2019-02-13T12:11:40.0290239Z ##[debug]Detecting file encoding using BOM
2019-02-13T12:11:40.0398581Z ##[debug]Unable to find node with tag 'applicationSettings' in provided xml file.
2019-02-13T12:11:40.0399510Z ##[debug]Processing substitution for xml node : appSettings
2019-02-13T12:11:40.0401524Z ##[debug]Processing substitution for xml node : connectionStrings
2019-02-13T12:11:40.0406204Z ##[debug]No substitution variables found for parameters.xml
2019-02-13T12:11:40.0409463Z ##[debug]Processing substitution for xml node : configSections
2019-02-13T12:11:40.0469289Z ##[debug]Skipped Updating file: D:\a\_temp\temp_web_package_21249088411579398\Content\D_C\a\1\s\MyProject.Web\obj\Release\Package\PackageTmp\Web.config
```

I know it is a preview but maybe I am using it wrong? Not a lot of options for configuring though

**Comment by vincentdass** [comment] 2019-02-14 02:21
@jepzen , Can you please share the task version and the full logs to `RM_CUSTOMER_QUEIRES@Microsoft.com`? 
Are you using **XML Transformation** or **XML variable substitution**?

**Comment by jepzen** [comment] 2019-02-14 07:49
Thanks. Task version is 1.*(preview) I sent the log to the email address

**Comment by vincentdass** [comment] 2019-02-14 07:54
@jepzen , sorry. here you go `RM_CUSTOMER_QUERIES@Microsoft.com`

**Comment by crowcoder** [comment] 2019-03-13 17:30
Seems to do nothing for me as well. 

2019-03-13T17:28:32.6429164Z ##[section]Starting: File Transform: 
2019-03-13T17:28:32.6429164Z ==============================================================================
2019-03-13T17:28:32.6429164Z Task         : File Transform
2019-03-13T17:28:32.6429164Z Description  : File Transform
2019-03-13T17:28:32.6429164Z Version      : 1.1.1
2019-03-13T17:28:32.6429164Z Author       : Microsoft Corporation
2019-03-13T17:28:32.6466145Z Help         : File transformation and variable substitution task: Update tokens in your XML based configuration files and then replaces those tokens with variable values. <br/>Currently only XML, JSON file formats are supported for variable substitution.
2019-03-13T17:28:32.6466145Z ==============================================================================
2019-03-13T17:28:33.0312167Z XML variable substitution applied successfully.
2019-03-13T17:28:33.0386129Z ##[section]Finishing: File Transform:

**Comment by vincentdass** [comment] 2019-03-21 09:51
@jepzen , the issue is fixed. Can you please retry the deployment?

**Comment by jepzen** [comment] 2019-03-25 09:24
No luck. But I am really not sure I know how to use it. I tried creating a new test project for this. I added an extra Build config named PP. I then added a the Web.PP.config. Edit the project file so this is not dependent on on web.config. Then i added the task to my release pipeline. But the log just goes 

```
2019-03-25T09:22:28.3544852Z ##[section]Starting: XML Transform
2019-03-25T09:22:28.3650135Z ==============================================================================
2019-03-25T09:22:28.3650430Z Task         : File Transform
2019-03-25T09:22:28.3650527Z Description  : File Transform
2019-03-25T09:22:28.3650597Z Version      : 1.1.1
2019-03-25T09:22:28.3650682Z Author       : Microsoft Corporation
2019-03-25T09:22:28.3650756Z Help         : File transformation and variable substitution task: Update tokens in your XML based configuration files and then replaces those tokens with variable values. <br/>Currently only XML, JSON file formats are supported for variable substitution.
2019-03-25T09:22:28.3650869Z ==============================================================================
2019-03-25T09:22:29.4121758Z ##[warning]Unable to apply transformation for the given package.
2019-03-25T09:22:30.6099796Z ##[section]Finishing: XML Transform
```

**Comment by EdGrant63** [comment] 2019-03-25 18:10
@jepzen  I was able to confirm that this task does work, but the output is definitely lacking. I actually just opened a developer community issue a few minutes ago:

https://developercommunity.visualstudio.com/content/idea/504813/file-transform-preview-task-should-have-some-outpu.html

But for actually using it, maybe you can look at my settings and see if you have some luck.

My Task Settings (Folder is the root of the Default Working Directory as I want to transform all instances of this setting in my config files):
![image](https://user-images.githubusercontent.com/15986435/54943071-deed4300-4f06-11e9-97a3-4024a11a2f23.png)

Variables Tab:
![image](https://user-images.githubusercontent.com/15986435/54943296-5b802180-4f07-11e9-87b0-8b9066a3e9cf.png)

I'm looking for all instances of a connection string Name (Context) and replacing it with the connection string in the Value field.

Please let me know if that works.

**Comment by SumiranAgg** [comment] 2019-03-27 07:29
@jepzen Can you please share the task version and the full logs to RM_CUSTOMER_QUERIES at Microsoft dot com ?

**Comment by jepzen** [comment] 2019-03-27 13:06
@EdGrant63 Thanks for suggestions. But the projec ti am working is an old with a huge web.config file and the transformation I am trying to do is getting from one file Web.PP.config into the web.config. I try to avoid sitting and copying all the values into pipeline variables.

**Comment by jepzen** [comment] 2019-03-27 13:45
@SumiranAgg I emailed it.

Question: Is it necessary to have a copy files step for this to work? (i have that) Or is this Task suppose to find my Web.[Env].config file inside the zip package?

**Comment by SumiranAgg** [comment] 2019-04-02 14:05
@jepzen This task  will find that file inside your package for both zip or folder.
The task  input for transformation rules just has to be-
-transform **\*.PP.config -xml **\*.config

Infact you can provide complete file names as well. The default values are just for reference.
Please try and let us know if this fixes the issue.

**Comment by hanssonfredrik** [comment] 2019-04-04 08:45
Thanks @EdGrant63!

**Comment by SumiranAgg** [comment] 2019-04-08 05:35
For more details about the task please go through reference doc https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/file-transform?view=azure-devops

@jepzen The issue should be resolved now. Closing the issue. Feel free to reopen if required.

**Closed by SumiranAgg** 2019-04-08 05:35 UTC
Labels: Area: Release
