### ISSUE TITLE
Ant not found

### ISSUE THREAD

**Issue by JaydeepUniverse** [microsoft/azure-pipelines-tasks#15834] opened 2022-01-27 04:21 UTC
## Required Information

**Issue**  

**Enter Task Name**: Ant

## Environment
- Server - Azure DevOps Pipelines

- Agent - Private: 
   
    - Ubuntu, Agent version: 2.196.2 

## Issue Description

I am facing this issue even though tried with all possible configurations.

In the agent
```
nnadmin@cc-base-vm:~$ echo $PATH
/usr/local/ant/bin:/usr/local/ant/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
nnadmin@cc-base-vm:~$ echo $ANT_HOME
/usr/local/ant
nnadmin@cc-base-vm:~$ which ant
/usr/local/ant/bin/ant
nnadmin@cc-base-vm:~$ ls -ltrh /usr/local/ant/bin
total 72K
-rw-r--r-- 1 root root 1.8K Oct 13 04:41 runrc.cmd
-rwxr-xr-x 1 root root 3.3K Oct 13 04:41 runant.py
-rwxr-xr-x 1 root root 4.1K Oct 13 04:41 runant.pl
-rw-r--r-- 1 root root 1.1K Oct 13 04:41 lcp.bat
-rw-r--r-- 1 root root 4.3K Oct 13 04:41 envset.cmd
-rwxr-xr-x 1 root root 3.4K Oct 13 04:41 complete-ant-cmd.pl
-rw-r--r-- 1 root root 3.4K Oct 13 04:41 antenv.cmd
-rwxr-xr-x 1 root root 2.1K Oct 13 04:41 antRun.pl
-rw-r--r-- 1 root root 1.5K Oct 13 04:41 antRun.bat
-rwxr-xr-x 1 root root  862 Oct 13 04:41 antRun
-rw-r--r-- 1 root root 2.8K Oct 13 04:41 ant.cmd
-rw-r--r-- 1 root root 7.3K Oct 13 04:41 ant.bat
-rwxr-xr-x 1 root root  12K Oct 13 04:41 ant
```

But while running through the pipeline
```
##[debug]which 'ant'
##[debug]not found
##[debug]Unable to locate executable file: 'ant'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
##[error]Error: Unable to locate executable file: 'ant'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

In the pipeline running through simple commands just to verify if ant is working
```
##[debug]/usr/bin/bash arg: --noprofile
##[debug]/usr/bin/bash arg: --norc
##[debug]/usr/bin/bash arg: /home/nnadmin/azure-devops-agent/_work/_temp/26d82427-22eb-4318-be3c-b03114ea4482.sh
##[debug]exec tool: /usr/bin/bash
##[debug]arguments:
##[debug]   --noprofile
##[debug]   --norc
##[debug]   /home/nnadmin/azure-devops-agent/_work/_temp/26d82427-22eb-4318-be3c-b03114ea4482.sh
/usr/bin/bash --noprofile --norc /home/nnadmin/azure-devops-agent/_work/_temp/26d82427-22eb-4318-be3c-b03114ea4482.sh
+ java -version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
+ /usr/local/ant/bin/ant -version
Apache Ant(TM) version 1.10.12 compiled on October 13 2021
+ which ant
+ ant -version
/home/nnadmin/azure-devops-agent/_work/_temp/26d82427-22eb-4318-be3c-b03114ea4482.sh: line 5: ant: command not found
##[debug]Exit code 127 received from tool '/usr/bin/bash'
##[debug]STDIO streams have closed for tool '/usr/bin/bash'
```

Kindly advise how to resolve this issue?
User is same for which ant is installed and pipeline agent is running

This issue is similar to [https://github.com/microsoft/azure-pipelines-tasks/issues/3540](https://github.com/microsoft/azure-pipelines-tasks/issues/3540) but since that's closed opening new one here

**Comment by JaydeepUniverse** [comment] 2022-01-27 14:26
@tatyana-kostromskaya Could you please share information about the tag "Bug" added - When shall we expect to resolve it? What's the workaround of it?

**Comment by davidstaheli** [comment] 2022-01-27 14:32
@JaydeepUniverse you might want to try running `echo $PATH` in the pipeline to ensure that ant is in the path for the user that the pipeline is running as.

**Comment by JaydeepUniverse** [comment] 2022-01-27 18:53
@davidstaheli  Thanks for your reply! Here's the output of `echo $PATH`

```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
/home/nnadmin/azure-devops-agent/_work/_temp/6820edcd-250f-4dfe-86f4-95826bdd5ec2.sh: line 4: ant: command not found
```

Here's how I have configured ANT:
```
sudo tar -xf ant.tar.gz -C /usr/local
sudo ln -s /usr/local/apache-ant-1.10.12/ /usr/local/ant
sudo vim /etc/profile.d/ant.sh
      export ANT_HOME=/usr/local/ant
      export PATH=${ANT_HOME}/bin:${PATH}
source /etc/profile
ant -version
```

If I run `echo $PATH` directly from server then I get below output with ant path:
`/usr/local/ant/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

I have just one user in the system through I have done the configuration of ant, java, azure devops agent and through same user pipeline is being executed.

Here's the pipeline configuration:
```
trigger:
- Feature/12345

variables:
  System.Debug: True 

pool:
  # vmImage: ubuntu-latest
  name: ClaimCenter

steps:
- script: |
    echo $PATH
    java -version
    which ant
    ant -version
  displayName: 'Run a multi-line script'
```

Last 2 command is not working in the pipeline.

**Comment by tatyana-kostromskaya** [comment] 2022-01-31 12:17
@JaydeepUniverse , did you restart your agent after ant installation? 
Do you run the agent as service or as an interactive process?

**Comment by JaydeepUniverse** [comment] 2022-02-01 09:36
@tatyana-kostromskaya @davidstaheli  I was able to resolve this issue.

In azure devops linux based agent we have to run `./env.sh` and then restart agent service in order to sync the environment variables, After doing this it worked.

Thanks for your help.

**Comment by tatyana-kostromskaya** [comment] 2022-02-01 09:40
Thank you for the response. 

May I close this issue?

**Closed** 2022-02-03 08:34 UTC
Labels: question, Area: Release, Area: ABTT, Task: Bash

**Comment by vmpriti** [comment] 2023-03-18 05:43
I am seeing the same error on a windows agent. 
##[error]Error: Unable to locate executable file: 'ant'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
##[error]Unable to locate executable file: 'ant'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

PATHhas  C:\apache-ant-1.9.16\bin 
and ANT_HOME is setto C:\apache-ant-1.9.16

Can you please help

**Comment by davidstaheli** [comment] 2023-03-18 18:59
Hi, @vmpriti! Could you please try running `echo %PATH%` as a command in part of your pipeline? The error you see is usually caused by Ant being in the path for *you* as a user logged into the machine, but the Windows agent runs as a different user that doesn't have Ant in its path. If you run `echo %PATH%` in your pipeline that runs on the Windows agent, the pipeline logs will show what is truly in the path for the agent.
