### ISSUE TITLE
SSH Task creates temporary files with time-dependent name

### ISSUE THREAD

**Issue by schibu007** [microsoft/azure-pipelines-tasks#13036] opened 2020-05-29 11:24 UTC
## Required Information
*Type*: Bug
**Task Name**: SSH
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/SshV0

## Environment
Azure DevOps Server Version Dev17.M153.5

## Issue Description
There are several agents which run an inline script on a remote Linux server via SSH. By a chance, the name of the temporary script file on the remote machine is the same for more than one agent. I suspect this is the reason for the problem below under "Task logs". 
To minimize this problem, I suggest to change the name of the temporary file from time-dependent to GUID. I think it's this located here: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/SshV0/ssh.ts, line 74:
`scriptFile = path.join(tempDir, 'sshscript_' + new Date().getTime()); // default name`

### Task logs
```
2020-05-28T08:19:53.5295196Z tr -d '\015' <"./sshscript_1590653991888" > "./sshscript_1590653991888._unix"
2020-05-28T08:19:53.5442491Z chmod +x "./sshscript_1590653991888._unix"
2020-05-28T08:19:53.5595054Z ##[error]chmod: 
2020-05-28T08:19:53.5606855Z ##[error]cannot access './sshscript_1590653991888._unix'
2020-05-28T08:19:53.5607514Z ##[error]: No such file or directory
2020-05-28T08:19:53.5607950Z 
2020-05-28T08:19:53.5608593Z ##[error]Command failed with errors on remote machine.
```

**Comment by alexander-smolyakov** [comment] 2020-07-06 09:58
Hi, @schibu007! Thanks for opening the issue!

The [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/13205) with the fix was merged. It may take some time for the fix to be deployed. I'll let you know once the fix is deployed.

**Comment by alexander-smolyakov** [comment] 2020-07-27 09:04
@schibu007, fix was already released, I'm closing it at the moment - please feel free to reopen if the issue is still reproducible.

**Closed by alexander-smolyakov** 2020-07-27 09:04 UTC
Labels: Area: ABTT, awaiting deployment, bug
