### ISSUE TITLE
##[error]Unhandled: Unable to locate executable file: 'mvn'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

### ISSUE THREAD

**Issue by ankurrawat66** [microsoft/azure-pipelines-tasks#15483] opened 2021-11-08 06:43 UTC
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Maven@3

## Issue Description

While running below task:
task: Maven@3
      displayName: 'Maven: validate'
      inputs:
        mavenPomFile: pom.xml
        goals: 'validate'
Getting "unable to locate executable mvn".
We are using **ubuntu 1804**.

### Error logs
##[error]Unhandled: Unable to locate executable file: 'mvn'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

**Comment by anatolybolshakov** [comment] 2021-11-08 10:10
Hi @ankurrawat66 I can't reproduce this issue with parameters above and ubuntu-18.04 for Maven task - do you have M2_HOME variables specifeid in a pipeline, or any modifications to the Path variables?
Maven tasks uses path from M2_HOME first, and if it was not found - it tries to find path to the 'mvn' executable in the path environment variable.

**Comment by ankurrawat66** [comment] 2021-11-09 04:31
@anatolybolshakov we are providing below maven settings only-
mavenGoal - "package"
mavenPublishJUnitResults - true
serviceCoreMavenOptions - "-Dmaven.repo.local=<path>"
mavenOptions - "-Dmaven.repo.local=<path>"
mavenSettingsFile - "setting.xml"

**Comment by anatolybolshakov** [comment] 2021-11-09 11:38
@ankurrawat66 could you please share full pipeline logs to investigate? You can send them to my email - v-anbols@microsoft.com

**Comment by ankurrawat66** [comment] 2021-11-09 11:49
I have sent the details in mail. Please let me know if anything else is needed.

**Comment by anatolybolshakov** [comment] 2021-11-11 12:38
Per offline discussion - seems that issue is relevant to the images used by (maven directory seems to be missed in PATH variable for some reason) - it's better to open a ticket on https://developercommunity.visualstudio.com/search?space=21 to get right eyes on it.
Closing this at the moment since it does not seem to be an agent issue - please feel free to ask any other questions.

**Closed by anatolybolshakov** 2021-11-11 12:38 UTC
Labels: bug, Area: ABTT, Task: Maven

**Comment by Jasmeen0506** [comment] 2023-05-29 05:38
##[error]Unhandled: Unable to locate executable file: 'mvn'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file. Getting this issue while creating .yml file

**Comment by amantcs** [comment] 2023-07-13 10:40
After installing Maven, I have to restart the agent service in Windows before pipeline can detect the value from PATH

**Comment by Seema82** [comment] 2023-09-08 10:29
do you resolve this issue, i am also getting same issue could you please provide and solution
