### ISSUE TITLE
FTP Upload skips node_modules from the build archive while uploading to the App Service

### ISSUE THREAD

**Issue by TheNetJedi** [microsoft/azure-pipelines-tasks#16606] opened 2022-07-19 14:08 UTC
## Required Information

*Type*: Bug

**Enter Task Name**: FtpUpload

## Environment
- Server - Azure Pipelines

## Issue Description

FtpUpload task skips node_modules folder while uploading the artifact for deployment

![image](https://user-images.githubusercontent.com/35243383/179770509-e06a801d-bb14-404d-b70b-4ffbbc89a0b4.png)
^Screenshot from archive of the published build artifact

![image](https://user-images.githubusercontent.com/35243383/179770636-891c8433-38b8-4104-a685-cdf34cce172f.png)
^Screenshot of the wwwroot

Seems like node_modules folder is being skipped while uploading to the App Service

**Comment by KonstantinTyukalov** [comment] 2022-07-20 13:29
Hi @TheNetJedi, thank you for reporting.
I cannot reproduce this problem from my side, `node_modules` folder uploads as expected.

Could you share some additional information:
- Pipeline logs with debug mode enabled. This can be done with this [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#view-and-download-logs)
You can enable debug mode as described [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs)
- Could you please share a snippet of the pipeline yaml schema in which the FtpUpload task appears

thank you

**Comment by KonstantinTyukalov** [comment] 2022-08-02 07:14
Hi @TheNetJedi  is this issue still reproduced in your case? 
Could you please share information described here: https://github.com/microsoft/azure-pipelines-tasks/issues/16606#issuecomment-1190289178
thanks

**Comment by KonstantinTyukalov** [comment] 2022-08-05 09:39
@TheNetJedi We are unable to reproduce this problem, let me then close this issue.
If you have further questions, please contact us in this ticket and we will reopen it.
Thank you

**Closed by KonstantinTyukalov** 2022-08-05 09:39 UTC
Labels: bug, Area: ABTT
