### ISSUE TITLE
Azure App Service Deploy Error: TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by nemetht** [microsoft/azure-pipelines-tasks#11101] opened 2019-08-10 07:27 UTC
## The Azure App Service deploy task fails with the following error: TypeError: Cannot read property 'getPath' of undefined

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure App Service deploy

## Environment
    - If using Azure Pipelines, provide the account name, team project name, release definition name/release number: anysight/anysight installation-service-release/41-73
## Issue Description

Stage: Dev - Service Deploy 
Task: Deploy installation service (Azure App Service deploy)

The task fails with the following error: TypeError: Cannot read property 'getPath' of undefined

### Task logs

2019-08-10T06:41:46.2806184Z ##[debug]Evaluating condition for step: 'Deploy installation service'
2019-08-10T06:41:46.2933156Z ##[debug]Evaluating: succeeded()
2019-08-10T06:41:46.2951733Z ##[debug]Evaluating succeeded:
2019-08-10T06:41:46.3062348Z ##[debug]=> True
2019-08-10T06:41:46.3094790Z ##[debug]Result: True
2019-08-10T06:41:46.3179201Z ##[section]Starting: Deploy installation service
2019-08-10T06:41:46.5133089Z ==============================================================================
2019-08-10T06:41:46.5133257Z Task         : Azure App Service deploy
2019-08-10T06:41:46.5133349Z Description  : Deploy to Azure App Service a web, mobile, or API app using Docker, Java, .NET, .NET Core, Node.js, PHP, Python, or Ruby
2019-08-10T06:41:46.5133448Z Version      : 4.156.3
2019-08-10T06:41:46.5133516Z Author       : Microsoft Corporation
2019-08-10T06:41:46.5133637Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment
2019-08-10T06:41:46.5133725Z ==============================================================================
2019-08-10T06:41:46.8521208Z ##[debug]agent.TempDirectory=d:\a\_temp
2019-08-10T06:41:46.8521823Z ##[debug]loading inputs and endpoints
2019-08-10T06:41:46.8522190Z ##[debug]loading ENDPOINT_AUTH_671f04cc-c22f-443f-9e83-31a61e9ebc0a
2019-08-10T06:41:46.8522592Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_671f04cc-c22f-443f-9e83-31a61e9ebc0a_AUTHENTICATIONTYPE
2019-08-10T06:41:46.8522871Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_671f04cc-c22f-443f-9e83-31a61e9ebc0a_SERVICEPRINCIPALID
2019-08-10T06:41:46.8523128Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_671f04cc-c22f-443f-9e83-31a61e9ebc0a_SERVICEPRINCIPALKEY
2019-08-10T06:41:46.8523380Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_671f04cc-c22f-443f-9e83-31a61e9ebc0a_TENANTID
2019-08-10T06:41:46.8523647Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-08-10T06:41:46.8523890Z ##[debug]loading ENDPOINT_AUTH_SCHEME_671f04cc-c22f-443f-9e83-31a61e9ebc0a
2019-08-10T06:41:46.8524313Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-08-10T06:41:46.8524541Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-08-10T06:41:46.8524764Z ##[debug]loading INPUT_ADDITIONALARGUMENTS
2019-08-10T06:41:46.8524964Z ##[debug]loading INPUT_APPSETTINGS
2019-08-10T06:41:46.8525184Z ##[debug]loading INPUT_CONNECTEDSERVICENAME
2019-08-10T06:41:46.8525401Z ##[debug]loading INPUT_CONNECTIONTYPE
2019-08-10T06:41:46.8525656Z ##[debug]loading INPUT_DEPLOYMENTTYPE
2019-08-10T06:41:46.8525863Z ##[debug]loading INPUT_DEPLOYTOSLOTORASEFLAG
2019-08-10T06:41:46.8526143Z ##[debug]loading INPUT_DOCKERIMAGETAG
2019-08-10T06:41:46.8528321Z ##[debug]loading INPUT_DOCKERNAMESPACE
2019-08-10T06:41:46.8531775Z ##[debug]loading INPUT_DOCKERREPOSITORY
2019-08-10T06:41:46.8533598Z ##[debug]loading INPUT_EXCLUDEFILESFROMAPPDATAFLAG
2019-08-10T06:41:46.8535188Z ##[debug]loading INPUT_INLINESCRIPT
2019-08-10T06:41:46.8536950Z ##[debug]loading INPUT_PACKAGE
2019-08-10T06:41:46.8538662Z ##[debug]loading INPUT_PUBLISHPROFILEPATH
2019-08-10T06:41:46.8541131Z ##[debug]loading INPUT_REMOVEADDITIONALFILESFLAG
2019-08-10T06:41:46.8542851Z ##[debug]loading INPUT_RENAMEFILESFLAG
2019-08-10T06:41:46.8544893Z ##[debug]loading INPUT_SCRIPTPATH
2019-08-10T06:41:46.8546572Z ##[debug]loading INPUT_SETPARAMETERSFILE
2019-08-10T06:41:46.8549289Z ##[debug]loading INPUT_SLOTNAME
2019-08-10T06:41:46.8552086Z ##[debug]loading INPUT_TAKEAPPOFFLINEFLAG
2019-08-10T06:41:46.8553790Z ##[debug]loading INPUT_USEWEBDEPLOY
2019-08-10T06:41:46.8555700Z ##[debug]loading INPUT_WEBAPPKIND
2019-08-10T06:41:46.8557599Z ##[debug]loading INPUT_WEBAPPNAME
2019-08-10T06:41:46.8561603Z ##[debug]loading INPUT_XMLTRANSFORMATION
2019-08-10T06:41:46.8564240Z ##[debug]loading INPUT_XMLVARIABLESUBSTITUTION
2019-08-10T06:41:46.8583646Z ##[debug]loaded 33
2019-08-10T06:41:46.8618833Z ##[debug]Agent.ProxyUrl=undefined
2019-08-10T06:41:46.8620397Z ##[debug]Agent.CAInfo=undefined
2019-08-10T06:41:46.8620998Z ##[debug]Agent.ClientCert=undefined
2019-08-10T06:41:46.8632656Z ##[debug]Agent.SkipCertValidation=undefined
2019-08-10T06:41:47.3191446Z ##[debug]agent.proxyurl=undefined
2019-08-10T06:41:47.3348441Z ##[debug]VSTS_ARM_REST_IGNORE_SSL_ERRORS=undefined
2019-08-10T06:41:47.3349383Z ##[debug]AZURE_HTTP_USER_AGENT=VSTS_184e36c6-d0f7-47c8-a2d9-3313ef91701c_Release__323_465_1
2019-08-10T06:41:47.3349719Z ##[debug]Agent.TempDirectory=d:\a\_temp
2019-08-10T06:41:47.3350102Z ##[debug]check path : d:\a\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\4.156.3\task.json
2019-08-10T06:41:47.3350424Z ##[debug]adding resource file: d:\a\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\4.156.3\task.json
2019-08-10T06:41:47.3351175Z ##[debug]system.culture=en-US
2019-08-10T06:41:47.3351449Z ##[debug]check path : d:\a\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\4.156.3\node_modules\azure-arm-rest-v2\module.json
2019-08-10T06:41:47.3351697Z ##[debug]adding resource file: d:\a\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\4.156.3\node_modules\azure-arm-rest-v2\module.json
2019-08-10T06:41:47.3352028Z ##[debug]system.culture=en-US
2019-08-10T06:41:47.3352187Z ##[debug]check path : d:\a\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\4.156.3\node_modules\webdeployment-common-v2\module.json
2019-08-10T06:41:47.3354540Z ##[debug]adding resource file: d:\a\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\4.156.3\node_modules\webdeployment-common-v2\module.json
2019-08-10T06:41:47.3354820Z ##[debug]system.culture=en-US
2019-08-10T06:41:47.3355128Z ##[debug]ConnectionType=AzureRM
2019-08-10T06:41:47.3355501Z ##[debug]WebAppKind=webAppContainer
2019-08-10T06:41:47.3355849Z ##[debug]DeployToSlotOrASEFlag=false
2019-08-10T06:41:47.3356300Z ##[debug]GenerateWebConfig=null
2019-08-10T06:41:47.3356672Z ##[debug]WebConfigParameters=null
2019-08-10T06:41:47.3356809Z ##[debug]XmlTransformation=false
2019-08-10T06:41:47.3356903Z ##[debug]JSONFiles=null
2019-08-10T06:41:47.3357076Z ##[debug]XmlVariableSubstitution=false
2019-08-10T06:41:47.3357214Z ##[debug]TakeAppOfflineFlag=true
2019-08-10T06:41:47.3357324Z ##[debug]RenameFilesFlag=true
2019-08-10T06:41:47.3357741Z ##[debug]AdditionalArguments=-retryAttempts:6 -retryInterval:10000
2019-08-10T06:41:47.3357985Z ##[debug]ScriptType=null
2019-08-10T06:41:47.3358146Z ##[debug]InlineScript=:: You can provide your deployment commands here. One command per line.
2019-08-10T06:41:47.3358272Z ##[debug]ScriptPath=d:\a\r1\a
2019-08-10T06:41:47.3358462Z ##[debug]DockerNamespace=anysightweudevcr.azurecr.io
2019-08-10T06:41:47.3359699Z ##[debug]AppSettings=-Auth0__Authority https://anysight-dev.eu.auth0.com -Auth0__SwaggerClientId OEfhqhbdyzjgzjbnttsOHqvCsn3hSBk1
2019-08-10T06:41:47.3360359Z ##[debug]StartupCommand=null
2019-08-10T06:41:47.3361061Z ##[debug]ConfigurationSettings=null
2019-08-10T06:41:47.3361223Z ##[debug]ConnectedServiceName=671f04cc-c22f-443f-9e83-31a61e9ebc0a
2019-08-10T06:41:47.3361799Z ##[debug]WebAppName=anysight-weu-dev-asvc
2019-08-10T06:41:47.3574280Z ##[debug]Processed: ##vso[telemetry.publish area=TaskEndpointId;feature=AzureRmWebAppDeployment]{"endpointId":"671f04cc-c22f-443f-9e83-31a61e9ebc0a"}
2019-08-10T06:41:47.9226987Z ##[debug]Depolyment started for linux app service
2019-08-10T06:41:47.9437019Z ##[debug]Deployment Failed with Error: TypeError: Cannot read property 'getPath' of undefined
2019-08-10T06:41:47.9440389Z ##[debug]task result: Failed
2019-08-10T06:41:47.9505744Z ##[error]TypeError: Cannot read property 'getPath' of undefined
2019-08-10T06:41:47.9515143Z ##[debug]Processed: ##vso[task.issue type=error;]TypeError: Cannot read property 'getPath' of undefined
2019-08-10T06:41:47.9534884Z ##[debug]Processed: ##vso[task.complete result=Failed;]TypeError: Cannot read property 'getPath' of undefined
2019-08-10T06:41:47.9535273Z ##[debug]Deployment failed
2019-08-10T06:41:47.9566345Z ##[section]Finishing: Deploy installation service

**Comment by tndata** [comment] 2019-08-11 17:30
I have the same problem

**Comment by ceemafour** [comment] 2019-08-12 02:24
I have the same problem here. Have tried recreating the pipelines as well as the target app service on Azure but doesn't work. 
This issue is affecting all docker(linux) pipelines. 
Non-docker deployments are not affected.

**Comment by vincentdass** [comment] 2019-08-12 05:24
@nemetht , @tndata , @ceemafour , thanks for reporting the issue. We identified the issue and working on the fix.
In the meanwhile, Can you use the `Azure Web App for container` task to get unblocked?
![image](https://user-images.githubusercontent.com/20121508/62846646-794ff680-bcef-11e9-9288-335343060077.png)

**Comment by valt449** [comment] 2019-08-12 06:09
Works for me @vincentdass. Thx :)

**Comment by gpj1** [comment] 2019-08-12 08:53
Any update on this?

**Comment by ahoak** [comment] 2019-08-12 20:00
@nemetht,  A workaround that I found is that you can use version 3 (not version 4). Example task in .yml file:
- task: AzureRmWebAppDeployment@3
    inputs:
      azureSubscription: ''
      appType: 'applinux'
      WebAppName: ''
      DeployToSlotFlag: true
      ResourceGroupName: ''
      SlotName: 'latest'
      DockerNamespace: ''
      DockerRepository: ''
      DockerImageTag: '$(Build.BuildId)'

Hope that helps!

**Comment by Lanrey** [comment] 2019-08-12 21:25
works for me @ahoak Thanks a lot

**Comment by dikhakha** [comment] 2019-08-13 04:59
The fix is now available. Can you please check if you are still facing this issue ?

**Comment by vincentdass** [comment] 2019-08-13 05:01
@gpj1 , we have rolled out the fix.
@ahoak , @Lanrey , Can you please change the task from "AzureRmWebAppDeployment@`3`"
to "AzureWebAppDeployment@`1`"

```
- task: AzureWebAppContainer@1
            inputs:
              azureSubscription: "$(my_sub)"
              appName: "my_app"
              imageName: 'appservice/python:latest'
```

**Comment by gpj1** [comment] 2019-08-13 07:18
Thanks @vincentdass . Now the issue is resolved with our existing task AzureWebAppDeployment@4. Thank you.

**Comment by yzhaopost** [comment] 2019-08-13 16:31
The hot-fix is working for me. Thank you. Just a quick question, as for the deployment of container to Azure web app, can we keep using "Azure App Service deployment" as recommended by the Azure docs "deploy to an Azure web app for container"  (https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-docker-webapp?view=azure-devops), or it is time switching to "Azure Web App for Container"? I mean for the existing Pipelines. What is your recommendation?

**Comment by Lanrey** [comment] 2019-08-13 22:35
Thanks @vincentdass . The issue has been resolved using AzureWebAppDeployment@4. Thanks

**Comment by vincentdass** [comment] 2019-08-14 05:28
Closing the issue, as it is resolved.

**Closed by vincentdass** 2019-08-14 05:28 UTC
Labels: Area: AzureAppService, Area: Release, bug

**Comment by karinapatel02** [comment] 2022-06-09 05:42
@vincent1173  Can you please help
Cannot read property 'portalUrl' of undefined
I am getting this when I try to deploy my flask app to azure web service that has 2 imports flask and pandas.
On the web page it shows application error.
