### ISSUE TITLE
.NET Core tasks are ignoring VersionPrefix value provided in *.csproj files during build process

### ISSUE THREAD

**Issue by rybczak** [microsoft/azure-pipelines-tasks#12989] opened 2020-05-25 07:31 UTC
**Question, Bug, or Feature?**  
*Type*: 
**Question**

**Enter Task Name**: 
- .NET Core

## Environment
- Server - Azure Pipelines
  - Account name: kmddk
  - Project name: combas
  - BuildId: 365750

- Agent - Hosted or Private: 
  - Pool: Azure Pipelines
  - Spec: windows-2019

## Issue Description

.NET Core tasks (both _build_ and _pack_) are ignoring **VersionPrefix** property which is provided inside projects *.csproj files. What's important - Version value is updated on build agent (by Powershell script). 

Every time we're running those tasks - default version 1.0.0 is used to produce NuGet packages. However, after downloading artifacts and running _dotnet build_ / _dotnet pack_ locally - value from *.csproj is used.

**Comment by issacnitin** [comment] 2020-06-01 11:19
@rybczak I'm unable to reproduce the issue. I even tried setting the VersionPrefix with Powershell using the following script
```
[xml]$myXML = Get-Content $(System.DefaultWorkingDirectory)/Application/aspnet-core-dotnet-core/aspnet-core-dotnet-core.csproj
$myXML.Project.PropertyGroup.VersionPrefix 
$myXML.Project.PropertyGroup.VersionPrefix = "1.2.4"
$myXML.Save("$(System.DefaultWorkingDirectory)/Application/aspnet-core-dotnet-core/aspnet-core-dotnet-core.csproj")
```
And NuGet package generated was of 1.2.4

Would you mind sharing the PowerShell script you've used

**Comment by issacnitin** [comment] 2020-06-03 04:19
@rybczak Could you share the PowerShell script you used for updating VersionPrefix?

**Comment by issacnitin** [comment] 2020-06-08 06:49
@rybczak We're closing the issue for now, as we couldn't get a response from you. Please feel free to re-open if you have any queries or concerns. Thanks!

**Closed by issacnitin** 2020-06-08 06:49 UTC
Labels: Area: Release, triage

**Comment by rybczak** [comment] 2020-06-08 08:46
@issacnitin Sorry for late response. I was able to run script with proper results but only when I switch to YAML. In first version I've used classic pipelines and that is not working.

**Comment by rouke-broersma** [comment] 2021-09-03 21:01
@issacnitin I'm late to the party but I hit this issue today. Even if using custom command, or using a run script task and specifying --configuration Debug the `DotNetCoreCLI` task refuses to acknowledge the VersionSuffix in our csproj.

Command on azure pipelines: `dotnet pack --output $(Build.ArtifactStagingDirectory)/release`
Command on my system: `dotnet pack`

Result left is azure pipelines and right is local system:

![image](https://user-images.githubusercontent.com/3595932/132064880-95d57403-e1fe-4711-a059-488c54fe5962.png)

I am at a loss here. This is from exactly the same commit in the repo. Only difference being one being executed by a azure pipeline.

**Comment by jenskloster** [comment] 2023-08-03 17:20
I have the same problem - 2 years later.
