### ISSUE TITLE
JavaToolInstaller support for Java 18

### ISSUE THREAD

**Issue by MarcBuch** [microsoft/azure-pipelines-tasks#16877] opened 2022-09-13 09:10 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

**Enter Task Name**: JavaToolInstaller

## Environment
- Server - Azure Pipelines
- Agent - Hosted ubuntu-22.04

## Issue Description

Please add JDK version support for Java 18.

**Comment by vmapetr** [comment] 2022-09-13 10:16
Hi @MarcBuch, thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by Heatmanofurioso** [comment] 2022-10-10 10:26
Hi all.

Any news regarding this support request?
Java 18 has been out for a while, and Java 19 is already out too

**Comment by MarcBuch** [comment] 2022-10-10 14:57
Hi @Heatmanofurioso, we decided to implement a pipeline template which does the build in a Docker Image.

**Comment by andre9494** [comment] 2022-11-09 15:15
Looking foward to it as well, this feature will be very important for us too


> Hi all.
> 
> Any news regarding this support request? Java 18 has been out for a while, and Java 19 is already out too, which we should consider adding support to as well IMO

**Comment by rodrigo-67** [comment] 2022-11-10 09:09
This feature will be very important for our development!

**Comment by thiagoalexsilva** [comment] 2022-11-10 09:16
> Hi all.
> 
> Any news regarding this support request? Java 18 has been out for a while, and Java 19 is already out too, which we should consider adding support to as well IMO

Looking forward to this fix too! It will make the project I'm working on continue ahead more smoothly

**Comment by RodolfoCIM** [comment] 2022-11-10 09:19
Hello everyone!
Do you know any news about this request? It would be great if you could fix this issue!
Thank you!

**Comment by Heatmanofurioso** [comment] 2022-11-22 09:43
@vmapetr Sorry for tagging, but any possibility on giving a look into the referenced PR?

**Comment by Heatmanofurioso** [comment] 2023-03-08 14:45
@LiliaSabitova Would you be able to give some support on this? Sorry for pinging.

Many people seem to want this feature, and we don't really get any feedback on why it isn't being added, considering how small of a change it is.

**Comment by aleksandrlevochkin** [comment] 2023-08-08 01:50
Hi everyone! It seems to me that the problem is that JDK 18/19 isn't installed on our [runner images](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java).

You can open an issue in the runner-images [repo](https://github.com/actions/runner-images/tree/main).

Meanwhile you can acquire any version of JDK from an Azure blob or a local directory, I've just tested it and it works regardless of the JDK's version. Here is the [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/java-tool-installer-v0?view=azure-pipelines)

**Comment by MarcBuch** [comment] 2023-08-08 08:20
I've opened an issue on the runner-images: https://github.com/actions/runner-images/issues/8057

**Comment by aleksandrlevochkin** [comment] 2023-08-08 11:33
I'm closing this issue as it's not really a problem related to this repo. When the next LTS version of JDK is pre-installed on the agent it will be supported by this task. For now, please, refer to my message above for alternative solutions.

**Closed by aleksandrlevochkin** 2023-08-08 11:33 UTC
Labels: enhancement, Area: ABTT, Task: JavaToolInstaller
