### ISSUE TITLE
GradleV2 demands java but java is no longer existing on agents.

### ISSUE THREAD

**Issue by majorvin** [microsoft/azure-pipelines-tasks#10579] opened 2019-06-05 13:36 UTC
We are using the azure pipeline image generation to generate our private agents and we noticed that "java" env variable is no longer available as it was migrated from oracle java to zulu open jdk. https://github.com/Microsoft/azure-pipelines-image-generation

When i run the gradle v2 task, it forces me to add demand java exist but this demand is no longer existing. 

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/GradleV2/task.json#L24

**Comment by leantk** [comment] 2020-07-08 02:24
This issue is stale because it has been open for a year with no activity. Remove the stale label or comment on the issue otherwise this will be closed in 5 days

**Comment by alexander-smolyakov** [comment] 2020-07-08 11:04
Hi, @majorvin! Is this issue still appears?

If yes, could you please run the pipeline again with the debug option set on and send full logs? It would be great if you are able to share the YAML file for your pipeline. Also, if you are able to provide a minimal reproducible sample it will speed up our investigation.

**Comment by alexander-smolyakov** [comment] 2020-07-13 15:04
Closing now this issue due to a lack of reproducible information, please feel free to reopen it.

**Closed by alexander-smolyakov** 2020-07-13 15:04 UTC
Labels: Area: ABTT, bug
