### ISSUE TITLE
Install-Module AzTable is no longer working

### ISSUE THREAD

**Issue by packersking** [microsoft/azure-pipelines-tasks#10633] opened 2019-06-11 18:26 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug:
Install-Module AzTable stopped working this morning.

Azure PowerShell (Preview)
version 4

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    msi-cie/RadioNext-DeviceMgmt/Pipelines/Releases/AgencyDeployment-UsingVMImage-CD

- Agent - Hosted or Private: 
   Hosted VS2017 
   
## Issue Description

Task: Get Image names. Using powershell script to read rows from an Azure storage table. Using AzTable module.
Import of module stopped working today (6/11/19) around 10am CDT

### Task logs

##[error]The specified module 'AzTable' was not loaded because no valid module file was found in any module directory.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]
![image](https://user-images.githubusercontent.com/3279216/59296792-67e56200-8c4c-11e9-9e51-a9ef226ca942.png)

**Comment by DaftDev** [comment] 2019-06-11 19:40
My team is also seeing this issue.

**Comment by 20shivangi** [comment] 2019-06-12 04:52
@packersking 

We are not able to reproduce the issue. Please try to run the Azure PowerShell task version 4 with Hosted VS2017 .
If the issue reproduces , please attach the debug logs.

**Comment by 20shivangi** [comment] 2019-06-18 04:59
@packersking
Any update ?

**Comment by niadak** [comment] 2019-06-26 06:39
@packersking , @DaftDev , Are you still facing the issue? Can you please try "Install-Module AzTable -Force" if so?

Please share the debug logs with us if you are still facing the issue.

**Comment by DaftDev** [comment] 2019-06-26 12:43
@niadak - No further issues here. The issue was resolved shortly after I commented.

**Comment by 20shivangi** [comment] 2019-06-27 04:06
Closing this issue

**Closed by 20shivangi** 2019-06-27 04:06 UTC
Labels: Area: Release
