### ISSUE TITLE
PackerBuild Build fails when build_resource_group_name is used

### ISSUE THREAD

**Issue by maniSbindra** [microsoft/azure-pipelines-tasks#10221] opened 2019-04-25 07:02 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: PackerBuild 

## Environment
- Server - Azure Pipelines
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - Hosted Ubuntu 1604, Hosted VS2017 and Private Ubuntu agent

## Issue Description

As mentioned in https://www.packer.io/docs/builders/azure.html normally the Service Principal used by packer needs full access to the subscription. This is because packer normally creates temp resource groups in which it creates temporary VM to do the provisioning and creating the VM image. For many customers getting such a service principal is not possible, so the correct option as mentioned in https://www.packer.io/docs/builders/azure.html, is to use  **build_resource_group_name**, which is the resource group where the service principal has full access and packer creates all temporary resources including VMs in this resource group. There is no need for a service principal with full access to the subscription. 

Currently when using **build_resource_group_name** the PackerBuild task throws an error in the final step (after the vm image has been created), probably while parsing the output.

### Task logs
```
azure-arm: Provisioning with powershell script: /tmp/packer-powershell-provisioner799929758

    azure-arm:
    azure-arm: Success Restart Needed Exit Code      Feature Result
    azure-arm: ------- -------------- ---------      --------------
    azure-arm: True    No             Success        {ASP.NET 4.6, .NET Framework 3.5 (includes...

==> azure-arm: Provisioning with Powershell...

==> azure-arm: Provisioning with powershell script: /tmp/packer-powershell-provisioner176009567
.
.

==> azure-arm:  -> ResourceGroupName : '<provisioning-resource-group>'

==> azure-arm:  -> ComputeName       : 'pkrvm7h9wkpvnkp'

==> azure-arm:  -> Managed OS Disk   : '/subscriptions/redacted/resourceGroups/<provisioning-resource-group>/providers/Microsoft.Compute/disks/pkros7h9wkpvnkp'
==> azure-arm: Querying the machine's additional disks properties ...

==> azure-arm:  -> ResourceGroupName : '<provisioning-resource-group>'
==> azure-arm:  -> ComputeName       : 'pkrvm7h9wkpvnkp'

==> azure-arm: Powering off machine ...

==> azure-arm:  -> ResourceGroupName : 'dev-otn-api-img'

==> azure-arm:  -> ComputeName       : 'pkrvm7h9wkpvnkp'

==> azure-arm: Capturing image ...

==> azure-arm:  -> Compute ResourceGroupName : '<provisioning-resource-group>'

==> azure-arm:  -> Compute Name              : 'pkrvm7h9wkpvnkp'

==> azure-arm:  -> Compute Location          : 'southcentralus'

==> azure-arm:  -> Image ResourceGroupName   : '<image-generation-resource-group-name>'

==> azure-arm:  -> Image Name                : 'corewebapp-20190415.3'

==> azure-arm:  -> Image Location            : 'southcentralus'

==> azure-arm: Deleting resource group ...

==> azure-arm:  -> ResourceGroupName : '<provisioning-resource-group>'

==> azure-arm: 
==> azure-arm: **The resource group was not created by Packer, only deleting individual resources** ...

==> azure-arm:  -> Microsoft.Compute/virtualMachines : 'pkrvm7h9wkpvnkp'

==> azure-arm:  -> Microsoft.Network/networkInterfaces : 'pkrni7h9wkpvnkp'

==> azure-arm:  -> Microsoft.Network/virtualNetworks : 'pkrvn7h9wkpvnkp'

==> azure-arm:  -> Microsoft.Network/publicIPAddresses : 'pkrip7h9wkpvnkp'

**Build 'azure-arm' errored: unexpected EOF**


==> Some builds didn't complete successfully and had errors:
--> **azure-arm: unexpected EOF**

==> Builds finished but no artifacts were created.

##[error]Error: /tmp/1555314108896/packer/packer failed with return code: 1
##[section]Finishing: Build immutable image`
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting
```
### Error logs

**Build 'azure-arm' errored: unexpected EOF**
 **azure-arm: unexpected EOF**

**Comment by bishal-pdMSFT** [comment] 2019-04-30 11:34
> **Build 'azure-arm' errored: unexpected EOF**

@maniSbindra this failure seems to be coming from Packer itself

How are you adding this property `build_resource_group_name` to builder? Are you trying a user-defined packer template or have you modified task to add this property to builtin templates? If using custom template can you please check that it does not have windows line ending as your task seems to be running on Linux agent.

**Comment by bishal-pdMSFT** [comment] 2019-04-30 11:36
If possible can you please share your custom template if you are using one

**Comment by maniSbindra** [comment] 2019-04-30 12:09
Sure will do that

**Comment by maniSbindra** [comment] 2019-04-30 13:02
Sample Packer Template : https://gist.github.com/maniSbindra/6b801b1494a91d8ab7ec50aebac96ae3

**Comment by anuragc617** [comment] 2019-05-02 17:19
Hi @maniSbindra, I have tested the packer build task with the custom template provided by you with service principal scope to the build_resource_group. For me, it worked fine, I am not able to reproduce this. Also, the error `**Build 'azure-arm' errored: unexpected EOF**` is not thrown by our task, it's a Packer error. Can you please retry and verify that you are able to reproduce it or not?

**Comment by maniSbindra** [comment] 2019-05-04 04:01
Hi @anuragc617  I am able to reproduce this, just tried using hosted agent as well as private agent. Please make sure that the service principal has access only to the resource groups specified in build_resource_group_name and resource_group. You are correct, I have tried locally using packer 1.2.4 and the same error is received.

**Comment by maniSbindra** [comment] 2019-05-04 04:50
@anuragc617 I have now tried on my local machine with packer version 1.4.0 and packer does not throw an error with the exact same packer build command. So I think to fix this we may need upgrade of packer version used in the task

**Packer 1.2.4 output on local machine (ERROR)** 
```
==> azure-arm: Capturing image ...
==> azure-arm:  -> Compute ResourceGroupName : 'dev-api-img'
==> azure-arm:  -> Compute Name              : 'pkrvmbz17j2yd9h'
==> azure-arm:  -> Compute Location          : 'southcentralus'
==> azure-arm:  -> Image ResourceGroupName   : 'dev-api'
==> azure-arm:  -> Image Name                : 'mytempimage'
==> azure-arm:  -> Image Location            : 'southcentralus'
==> azure-arm: Deleting resource group ...
==> azure-arm:  -> ResourceGroupName : 'dev-api-img'
==> azure-arm: 
==> azure-arm: The resource group was not created by Packer, only deleting individual resources ...
==> azure-arm:  -> Microsoft.Compute/virtualMachines : 'pkrvmbz17j2yd9h'
==> azure-arm:  -> Microsoft.Network/networkInterfaces : 'pkrnibz17j2yd9h'
==> azure-arm:  -> Microsoft.Network/virtualNetworks : 'pkrvnbz17j2yd9h'
==> azure-arm:  -> Microsoft.Network/publicIPAddresses : 'pkripbz17j2yd9h'
Build 'azure-arm' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> azure-arm: unexpected EOF

==> Builds finished but no artifacts were created.
``` 

**Packer 1.4.0 output on local machine (SUCCESS)**
```
==> azure-arm: Capturing image ...
==> azure-arm:  -> Compute ResourceGroupName : 'dev-api-img'
==> azure-arm:  -> Compute Name              : 'pkrvmvbo2f1zbw0'
==> azure-arm:  -> Compute Location          : 'southcentralus'
==> azure-arm:  -> Image ResourceGroupName   : 'dev-api'
==> azure-arm:  -> Image Name                : 'mytempimage2'
==> azure-arm:  -> Image Location            : 'southcentralus'
==> azure-arm: Deleting resource group ...
==> azure-arm:  -> ResourceGroupName : 'dev-api-img'
==> azure-arm: 
==> azure-arm: The resource group was not created by Packer, only deleting individual resources ...
==> azure-arm:  -> Microsoft.Compute/virtualMachines : 'pkrvmvbo2f1zbw0'
==> azure-arm:  -> Microsoft.Network/networkInterfaces : 'pkrnivbo2f1zbw0'
==> azure-arm:  -> Microsoft.Network/virtualNetworks : 'pkrvnvbo2f1zbw0'
==> azure-arm:  -> Microsoft.Network/publicIPAddresses : 'pkripvbo2f1zbw0'
==> azure-arm:  -> Microsoft.KeyVault/vaults/secrets : 'pkrkvvbo2f1zbw0/packerKeyVaultSecret'
==> azure-arm:  -> Microsoft.KeyVault/vaults : 'pkrkvvbo2f1zbw0'
==> azure-arm: Deleting the temporary OS disk ...
==> azure-arm:  -> OS Disk : '/subscriptions/redacted/resourceGroups/dev-api-img/providers/Microsoft.Compute/disks/pkrosvbo2f1zbw0'
==> azure-arm: Deleting the temporary Additional disk ...
Build 'azure-arm' finished.

==> Builds finished. The artifacts of successful builds are:
--> azure-arm: Azure.ResourceManagement.VMImage:

OSType: Windows
ManagedImageResourceGroupName: dev-api
ManagedImageName: mytempimage2
ManagedImageId: /subscriptions/redacted/resourceGroups/dev-api/providers/Microsoft.Compute/images/mytempimage2
ManagedImageLocation: southcentralus
```

**Comment by anuragc617** [comment] 2019-05-07 05:13
Yes, you are right, we should update the version of Packer installed by the task to 1.4.0. Currently, the task installs Packer version 0.12.3, if not installed on the agent machine. 
When I queued the task on the hosted agent where packer wasn't installed, task installs 0.12.3. And I was getting this: 
> Packer validate command failed. This could happen if the task does not support packer version.

I used a private agent and the packer version installed on my local machine is 1.4.0, so the task picked up the installed version of packer on my machine. That's why I wasn't able to reproduce. I am able to reproduce with the Packer build version 1.2.4.

**Comment by maniSbindra** [comment] 2019-05-09 01:20
Hi @anuragc617 while working on https://github.com/microsoft/azure-pipelines-tasks/pull/8015 it was found that when you update packer version there may be breaking changes. I have the end to end tests ready, if I find time later this month will test it out and submit PR

**Comment by bishal-pdMSFT** [comment] 2019-05-20 08:19
Bumping up Packer version might be a breaking change and hence we have to be very careful to do so. It would be preferable to bump up the major version of task as well so as to not cause any customer impact.
Is this support of build resource group important enough to require a new major version of task? Can we postpone it to collate more fixes in future? For now, we can mention this issue and workaround in task input help text.

**Comment by sachinma** [comment] 2019-05-20 11:05
@bishal-pdMSFT #10413 tries to solve this without break

**Comment by vinodkumar3** [comment] 2019-06-17 06:43
Required changes are merged and will be available in upcoming release cycle.

**Closed by vinodkumar3** 2019-06-17 06:43 UTC
Labels: Area: Release, bug
