### ISSUE TITLE
TFS Service End Point for Azure connection during verification throughs error- Failed to obtain the Json Web Token(JWT) for service principal id '<Service ID>' Exception Message: Object reference not set to an instance of an object.   

### ISSUE THREAD

**Issue by 199219921992** [microsoft/azure-pipelines-tasks#10321] opened 2019-05-07 03:53 UTC
Hello,

I am using TFS 2018 and trying to create service end point for TFS-Azure bridge using service clinet ID, after verifying the connection i am getting - **Failed to obtain the Json Web Token(JWT) for service principal id +  Exception Message: Object reference not set to an instance of an object.**  error.

Added Service principal client ID to subscription and providing the contributor role and made the secret key as Never expires during app registration.

Could anybody suggest me on this?

Thanks in advance.

**Comment by Ajay-MS** [comment] 2019-05-14 10:16
@199219921992 

Can you please run below script from the TFS 2018 server machine and can verify if able to generate the access token.
[Script to generate accessToken](https://github.com/Ajay-MS/UtilityScripts/blob/master/Subscription/GetAccessToken.ps1)

**Comment by Ajay-MS** [comment] 2019-05-24 06:19
Closing as more info required.

**Closed by Ajay-MS** 2019-05-24 06:19 UTC
Labels: Area: Release

**Comment by engineering-dotcms** [comment] 2022-02-23 07:50
Good morning,
I know the issue Is closed but I'm facing the same problem with our on-prem Azure DevOps installation (server 2019) when we try to create an ARM service connection using an app registration.

Regards,
Graziano
