### ISSUE TITLE
Xamarin Android Build fails with Multi-Dex and ProGuard

### ISSUE THREAD

**Issue by soooraj** [microsoft/azure-pipelines-tasks#9765] opened 2019-03-08 11:15 UTC
When I enable **Multi-Dex** in Xamarin.Android Build. The build fails with below error.

##[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2610,3): Error MSB6006: "java.exe" exited with code 2.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2610,3): error MSB6006: "java.exe" exited with code 2. 
Done Building Project "<< MY Project Path>>" (PackageForAndroid target(s)) -- FAILED.

"<< MY Project Path>>" (PackageForAndroid target) (1) ->
(_CompileToDalvikWithDx target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2610,3): error MSB6006: "java.exe" exited with code 2. [<< MY Project Path>>]

    23 Warning(s)
    1 Error(s)

Time Elapsed 00:03:29.78
##[error]Process 'msbuild.exe' exited with code '1'.

## Environment
Xamarin.Android - Azure DevOps - Hosted VS 2017

**Comment by david-chambers** [comment] 2019-08-25 21:33
@soooraj or @bryanmacfarlane - seeing this as well.  Is this a confirmed bug and are there any workarounds at this time? Did you have to bump the hosted build agent to VS2019?

**Comment by sdobrodeev** [comment] 2020-05-14 13:07
@soooraj Please confirm that this issue is still actual for you.

**Comment by sdobrodeev** [comment] 2020-05-26 10:19
Closing the issue due to lack of information, please feel free to reopen it.

**Closed by sdobrodeev** 2020-05-26 10:19 UTC
Labels: Area: ABTT
