### ISSUE TITLE
[BUG]: Azure yml pipeline Gradle task failed - ##[error]Error: The process '/Users/runner/work/1/s/gradlew' failed with exit code 1

### ISSUE THREAD

**Issue by LeeCeline** [microsoft/azure-pipelines-tasks#19896] opened 2024-05-21 14:01 UTC
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Gradle

### Task version

2.231.2

### Issue Description

The Azure yml pipeline is not working from 17 of May.
Please find the logs and guide how to fix it.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

MacOS

### Relevant log output

```shell
2024-05-21T13:42:35.2639320Z > Task :eventoffers:kaptReleaseKotlin
...

2024-05-21T13:42:35.8736530Z e: java.lang.IllegalStateException: failed to analyze: com.sun.tools.javac.code.ClassFinder$BadClassFile: bad class file: /Users/runner/.gradle/caches/transforms-2/files-2.1/b76cdde0b2066ae171788a3f563269b3/jetified-realm-android-library-10.3.1-api.jar(/io/realm/MutableRealmInteger.class)
2024-05-21T13:42:35.8787760Z   unable to access file: java.nio.file.ClosedFileSystemException
2024-05-21T13:42:35.9780010Z   Please remove or make sure it appears in the correct subdirectory of the classpath.
2024-05-21T13:42:35.9987670Z 	at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:56)
2024-05-21T13:42:36.0181180Z 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:105)
2024-05-21T13:42:36.0993320Z 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
2024-05-21T13:42:36.1221110Z 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
2024-05-21T13:42:36.2024790Z 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
2024-05-21T13:42:36.2293710Z 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
2024-05-21T13:42:36.2859230Z 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
2024-05-21T13:42:36.2865490Z 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
2024-05-21T13:42:36.3012210Z 	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1618)
2024-05-21T13:42:36.3873910Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-05-21T13:42:36.4877490Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-05-21T13:42:36.5880680Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-05-21T13:42:36.6151090Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024-05-21T13:42:36.6155700Z 	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
2024-05-21T13:42:36.6159420Z 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
2024-05-21T13:42:36.7100310Z 	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
2024-05-21T13:42:36.7245800Z 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2024-05-21T13:42:36.7712910Z 	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
2024-05-21T13:42:36.7979910Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
2024-05-21T13:42:36.7982030Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
2024-05-21T13:42:36.8002770Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
2024-05-21T13:42:36.8009300Z 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2024-05-21T13:42:36.8010940Z 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
2024-05-21T13:42:36.8012730Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2024-05-21T13:42:36.8014570Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2024-05-21T13:42:36.8016230Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2024-05-21T13:42:36.8018960Z Caused by: com.sun.tools.javac.code.ClassFinder$BadClassFile: bad class file: /Users/runner/.gradle/caches/transforms-2/files-2.1/b76cdde0b2066ae171788a3f563269b3/jetified-realm-android-library-10.3.1-api.jar(/io/realm/MutableRealmInteger.class)
2024-05-21T13:42:36.8020100Z   unable to access file: java.nio.file.ClosedFileSystemException
2024-05-21T13:42:36.8021640Z   Please remove or make sure it appears in the correct subdirectory of the classpath.
2024-05-21T13:42:36.8023490Z 	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.badClassFile(ClassReader.java:310)
2024-05-21T13:42:36.8025350Z 	at jdk.compiler/com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:2866)
2024-05-21T13:42:36.8027530Z 	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:359)
2024-05-21T13:42:36.8029250Z 	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:291)
2024-05-21T13:42:36.8031480Z 	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:642)
2024-05-21T13:42:36.8684210Z 	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1326)
2024-05-21T13:42:36.8689850Z 	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.complete(Type.java:1140)
2024-05-21T13:42:36.8698710Z 	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.getTypeArguments(Type.java:1066)
2024-05-21T13:42:36.8703550Z 	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.toString(Type.java:1025)
2024-05-21T13:42:36.8705740Z 	at java.base/java.lang.String.valueOf(String.java:2951)
2024-05-21T13:42:36.8709740Z 	at java.base/java.lang.StringBuilder.append(StringBuilder.java:172)
2024-05-21T13:42:36.8729580Z 	at org.jetbrains.kotlin.utils.kapt.MemoryLeakDetector.inspectStatics(MemoryLeakDetector.kt:104)
2024-05-21T13:42:36.8732590Z 	at org.jetbrains.kotlin.utils.kapt.MemoryLeakDetector.process(MemoryLeakDetector.kt:66)
2024-05-21T13:42:36.8740240Z 	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:240)
2024-05-21T13:42:36.8777640Z 	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:194)
2024-05-21T13:42:36.8785730Z 	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:102)
2024-05-21T13:42:36.8787040Z 	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:112)
2024-05-21T13:42:36.8789360Z 	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:122)
2024-05-21T13:42:36.8939550Z 	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:96)
2024-05-21T13:42:36.8965830Z 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:262)
2024-05-21T13:42:36.8968470Z 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
2024-05-21T13:42:36.8969990Z 	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
2024-05-21T13:42:36.9091500Z 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
2024-05-21T13:42:36.9093430Z 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
2024-05-21T13:42:36.9094780Z 	... 24 more
...

2024-05-21T13:42:42.2951850Z FAILURE: Build failed with an exception.
2024-05-21T13:42:42.2959950Z 
2024-05-21T13:42:42.2961330Z * What went wrong:
2024-05-21T13:42:42.2963300Z Execution failed for task ':eventoffers:kaptReleaseKotlin'.
2024-05-21T13:42:42.2972770Z > Internal compiler error. See log for more details
2024-05-21T13:42:42.2975120Z 
2024-05-21T13:42:42.2986300Z * Try:
2024-05-21T13:42:42.2987450Z Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
2024-05-21T13:42:42.3172420Z 
2024-05-21T13:42:42.4179710Z * Get more help at https://help.gradle.org
2024-05-21T13:42:42.4180870Z 
2024-05-21T13:42:42.4767940Z BUILD FAILED in 5m 53s
2024-05-21T13:42:42.5078220Z 228 actionable tasks: 152 executed, 65 from cache, 11 up-to-date
2024-05-21T13:42:43.5711090Z 
2024-05-21T13:42:43.6348580Z Error: The process '/Users/runner/work/1/s/gradlew' failed with exit code 1
2024-05-21T13:42:43.6353290Z     at ExecState._setResult (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.231.2/node_modules/azure-pipelines-task-lib/toolrunner.js:943:25)
2024-05-21T13:42:43.6397070Z     at ExecState.CheckComplete (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.231.2/node_modules/azure-pipelines-task-lib/toolrunner.js:926:18)
2024-05-21T13:42:43.6528710Z     at ChildProcess.<anonymous> (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.231.2/node_modules/azure-pipelines-task-lib/toolrunner.js:839:19)
2024-05-21T13:42:43.6569330Z     at ChildProcess.emit (node:events:518:28)
2024-05-21T13:42:43.6574520Z     at maybeClose (node:internal/child_process:1105:16)
2024-05-21T13:42:43.6577900Z     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
2024-05-21T13:42:44.0723790Z ##[error]Error: The process '/Users/runner/work/1/s/gradlew' failed with exit code 1
2024-05-21T13:42:44.2767240Z ##[section]Finishing: Gradle
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by DmitriiBobreshev** [comment] 2024-05-22 07:04
Hi @LeeCeline, thanks for the detailed log! This seems like a duplicate of https://github.com/microsoft/azure-pipelines-tasks/issues/19892, I'm closing this issue, you can track https://github.com/microsoft/azure-pipelines-tasks/issues/19892 for new info

**Closed by DmitriiBobreshev** 2024-05-22 07:04 UTC
Labels: bug, Area: Release, triage, Area: ABTT
