### ISSUE TITLE
Failed to Publish Junit Results

### ISSUE THREAD

**Issue by saikrishna321** [Microsoft/azure-pipelines-tasks#9576] opened 2019-02-13 19:47 UTC
I was trying to publish JUnit xml results to azure pipeline and it fails saying Invalid Junit format. 

https://github.com/saikrishna321/taiko/pull/2/checks?check_run_id=62900422

JUnit XML:

```
<testsuites>
	<testsuite id="1" tests="8" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/ElementsAPI.spec" time="16.692" timestamp="2019-02-13T14:38:03" name="API" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="API" name="Combo Box" time="1.931"></testcase>
		<testcase classname="API" name="Check Box" time="1.848"></testcase>
		<testcase classname="API" name="Radio Button" time="1.847"></testcase>
		<testcase classname="API" name="File field" time="1.341"></testcase>
		<testcase classname="API" name="Text Field" time="1.992"></testcase>
		<testcase classname="API" name="$ element" time="3.854"></testcase>
		<testcase classname="API" name="Page" time="1.305"></testcase>
		<testcase classname="API" name="Button with alert" time="2.574"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="2" tests="8" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/ElementsAPIIFrame.spec" time="18.214" timestamp="2019-02-13T14:38:03" name="API accessing IFrame Elements" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="API accessing IFrame Elements" name="Combo Box" time="2.004"></testcase>
		<testcase classname="API accessing IFrame Elements" name="Check Box" time="2.013"></testcase>
		<testcase classname="API accessing IFrame Elements" name="Radio Button" time="2.014"></testcase>
		<testcase classname="API accessing IFrame Elements" name="Attach file" time="1.422"></testcase>
		<testcase classname="API accessing IFrame Elements" name="Text Field" time="2.241"></testcase>
		<testcase classname="API accessing IFrame Elements" name="$ element" time="4.139"></testcase>
		<testcase classname="API accessing IFrame Elements" name="Page" time="1.307"></testcase>
		<testcase classname="API accessing IFrame Elements" name="Button with alert" time="3.074"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="3" tests="2" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/waitForNavigation.spec" time="29.283" timestamp="2019-02-13T14:38:03" name="Wait for navigation" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="Wait for navigation" name="Should get the text of an element after page is loaded" time="3.274"></testcase>
		<testcase classname="Wait for navigation" name="Should get text after ajax calls" time="26.009"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="4" tests="1" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/alertIFrame.spec" time="2.960" timestamp="2019-02-13T14:38:03" name="Alert in IFrame" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="Alert in IFrame" name="Should be able to accept a dialog box in IFrame" time="2.960"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="5" tests="11" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/browserActions.spec" time="58.907" timestamp="2019-02-13T14:38:03" name="Browser Action" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="Browser Action" name="Switch To" time="5.662"></testcase>
		<testcase classname="Browser Action" name="Open/Close Tab" time="4.266"></testcase>
		<testcase classname="Browser Action" name="Close Tab with no parameters" time="12.916"></testcase>
		<testcase classname="Browser Action" name="Reload" time="6.513"></testcase>
		<testcase classname="Browser Action" name="Reload should not clear local cache" time="4.737"></testcase>
		<testcase classname="Browser Action" name="Get all cookies" time="2.518"></testcase>
		<testcase classname="Browser Action" name="Cookie should be present for valid options urls" time="3.407"></testcase>
		<testcase classname="Browser Action" name="Cookie not should be present for invalid options urls" time="3.701"></testcase>
		<testcase classname="Browser Action" name="Set mock location" time="3.818"></testcase>
		<testcase classname="Browser Action" name="Emulate device" time="5.205"></testcase>
		<testcase classname="Browser Action" name="Browser forward and back" time="6.164"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="6" tests="6" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/pageActionsIFrame.spec" time="51.932" timestamp="2019-02-13T14:38:03" name="Page Actions in IFrame" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="Page Actions in IFrame" name="Write, Press, Click" time="7.295"></testcase>
		<testcase classname="Page Actions in IFrame" name="Write, Clear" time="16.424"></testcase>
		<testcase classname="Page Actions in IFrame" name="Double Click" time="13.743"></testcase>
		<testcase classname="Page Actions in IFrame" name="Right Click" time="3.712"></testcase>
		<testcase classname="Page Actions in IFrame" name="Hover" time="7.738"></testcase>
		<testcase classname="Page Actions in IFrame" name="Drag and drop" time="3.020"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="7" tests="2" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/waitForNavigationIFrame.spec" time="17.628" timestamp="2019-02-13T14:38:03" name="Wait for navigation IFrame" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="Wait for navigation IFrame" name="Should get the text of an element after page is loaded" time="5.335"></testcase>
		<testcase classname="Wait for navigation IFrame" name="Should get text after ajax calls" time="12.293"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="8" tests="2" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/positionalSelectors.spec" time="4.899" timestamp="2019-02-13T14:38:03" name="Positional Selectors" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="Positional Selectors" name="Into" time="2.450"></testcase>
		<testcase classname="Positional Selectors" name="To" time="2.449"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="9" tests="3" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/proximitySelectors.spec" time="16.407" timestamp="2019-02-13T14:38:03" name="Proximity Selectors" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="Proximity Selectors" name="Below" time="7.404"></testcase>
		<testcase classname="Proximity Selectors" name="Above" time="6.374"></testcase>
		<testcase classname="Proximity Selectors" name="Right Of" time="2.628"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="10" tests="1" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/selectors.spec" time="5.774" timestamp="2019-02-13T14:38:03" name="Selectors" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="Selectors" name="Contains" time="5.774"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="11" tests="3" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/proximitySelectorsIFrame.spec" time="15.007" timestamp="2019-02-13T14:38:03" name="Proximity Selectors in IFrame" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="Proximity Selectors in IFrame" name="Below" time="4.254"></testcase>
		<testcase classname="Proximity Selectors in IFrame" name="Above" time="7.247"></testcase>
		<testcase classname="Proximity Selectors in IFrame" name="Right Of" time="3.506"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="12" tests="1" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/alert.spec" time="3.851" timestamp="2019-02-13T14:38:03" name="Alert" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="Alert" name="Should be able to accept a dialog box" time="3.851"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="13" tests="5" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/intercept.spec" time="18.309" timestamp="2019-02-13T14:38:03" name="Intercept Api" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="Intercept Api" name="With simple response body" time="3.737"></testcase>
		<testcase classname="Intercept Api" name="With array as a response body" time="3.455"></testcase>
		<testcase classname="Intercept Api" name="With object as a response body" time="3.724"></testcase>
		<testcase classname="Intercept Api" name="With regex in URL" time="3.042"></testcase>
		<testcase classname="Intercept Api" name="Override a response for a URL" time="4.351"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="14" tests="8" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/pageActions.spec" time="57.674" timestamp="2019-02-13T14:38:03" name="Page Actions" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="Page Actions" name="Scroll To, Up" time="4.416"></testcase>
		<testcase classname="Page Actions" name="Write, Press, Click" time="6.384"></testcase>
		<testcase classname="Page Actions" name="Write, Clear" time="15.865"></testcase>
		<testcase classname="Page Actions" name="Double Click" time="13.413"></testcase>
		<testcase classname="Page Actions" name="Right Click" time="2.992"></testcase>
		<testcase classname="Page Actions" name="Hover" time="7.774"></testcase>
		<testcase classname="Page Actions" name="Drag and drop" time="3.154"></testcase>
		<testcase classname="Page Actions" name="Validate Current Url" time="3.675"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
	<testsuite id="15" tests="2" failures="0" package="/Users/saikrisv/git/taiko/test/functional-tests/specs/positionalSelectorsIFrame.spec" time="5.546" timestamp="2019-02-13T14:38:03" name="Positional Selectors in IFrame" errors="0" hostname="in-Saikrisv.local">
		<properties></properties>
		<testcase classname="Positional Selectors in IFrame" name="Into" time="2.722"></testcase>
		<testcase classname="Positional Selectors in IFrame" name="To" time="2.824"></testcase>
		<system-out></system-out>
		<system-err></system-err>
	</testsuite>
</testsuites>

```

**Comment by SadagopanRajaram** [comment] 2019-03-18 09:00
@saikrishna321 - I am able to publish the Junit file above. Can you please share a more recent build where this publish did not happen?

**Comment by saikrishna321** [comment] 2019-03-18 22:00
@SadagopanRajaram Thanks for reverting. I did try to publish again and it works. I have three jobs and how do I publish the results to independent test results. Is this possible ?

**Comment by SadagopanRajaram** [comment] 2019-03-19 05:51
@saikrishna321 - the current pipeline definition you have should publish three separate runs, one for each job. In the latest run, I see that the Linux job has not generated any results file and windows job failed before publish happened. Once you fix these issues in your pipeline, you should see three separate runs. 
Let me know if this clarifies and I can close this issue.

**Comment by SadagopanRajaram** [comment] 2019-03-22 04:56
I assume the issue is resolved now and closing the issue

**Closed by SadagopanRajaram** 2019-03-22 04:56 UTC
Labels: Area: Test, Area: TestManagement
