### ISSUE TITLE
helm lint does not recognize chartType / chartPath

### ISSUE THREAD

**Issue by agilekevin** [microsoft/azure-pipelines-tasks#13786] opened 2020-10-27 17:59 UTC
**Question, Bug, or Feature?**  
*Bug*: 
I expected to be able to set the chart path with the chartPath input variable, but it is ignored.

Expected to work:
```
          - task: HelmDeploy@0
            displayName: Helm Lint
            inputs:
              ConnectionType: Kubernetes Service Connection
              kubernetesServiceEndpoint: k8s
              command: lint
              arguments: -f $(Build.SourcesDirectory)/multi-helm/spec/LINT/values.yaml
              chartType: filepath
              chartPath: ./multi-helm/
```

Instead, I had to wedge it into arguments:
```
              arguments: ./multi-helm -f $(Build.SourcesDirectory)/multi-helm/spec/LINT/values.yaml
```

**HelmDeploy**: HelmDeploy@0

## Environment
- Server - Azure Pipelines

**Comment by ds-ms** [comment] 2020-10-29 08:56
This is not a bug, this is expected behaviour. That's because there's no special handling for `lint`.
These are the ones which have special handling which leverage the inputs of the task.

https://github.com/microsoft/azure-pipelines-tasks/blob/8c47ce21c73f825c635054fa77582e4195a63870/Tasks/HelmDeployV0/task.json#L173-L187

Any other command goes into the default handling, i.e. only the argument section is leveraged. If you'd like to have special handling for this command instead of it being under the generic bucket, feel free to raise a PR I'd be happy to take it forward. 😄 

cc: @shigupt202 @ammohant @anraghun

**Comment by ds-ms** [comment] 2020-11-25 17:51
Closing this issue. If you still think this needs attention, feel free to reopen this.

**Closed by ds-ms** 2020-11-25 17:51 UTC
Labels: Area: Release, triage
