### ISSUE TITLE
Azure IoT Edge Task is busted on Hosted Ubuntu 16.04 pool since 09/17

### ISSUE THREAD

**Issue by hiteshmadan** [microsoft/azure-pipelines-tasks#11387] opened 2019-09-20 17:29 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information
The Azure IoT Edge deployment task has started crashing 3 days ago. Attaching the verbose task logs.
Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Azure IoT Edge

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
Azure Piplines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
Account: msazure
Team: One
https://msazure.visualstudio.com/One/_build?definitionId=74883

- Agent - Hosted or Private: 
Hosted
    
    - If using Hosted agent, provide agent queue name:
Hosted Ubuntu 1604
[log_16_25172259.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3637084/log_16_25172259.zip)

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description
cannot deploy to azure iot edge via the IoT Edge Task any more.

[Include task name(s), screenshots and any other relevant details]

### Task logs
Attached
[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
[Insert error from the logs here for a quick overview]

[command]/usr/bin/az iot edge deployment create --config-id one-devops-deployment-xenial --hub-name eg-iot-edge-end2end-iothub --content /tmp/deployment_1568949552073.json --target-condition deviceId='eg-iot-edge-end2end-ubuntu1604-1' --priority 0 --output none
ERROR: The command failed with an unexpected error. Here is the traceback:

ERROR: The 'jsonschema' distribution was not found and is required by the application
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 305, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/home/vsts/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 524, in iot_edge_deployment_create
    login=login, edge=True)
  File "/home/vsts/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 558, in _iot_hub_configuration_create
    content = _process_config_content(content, 'module' if edge else 'device')
  File "/home/vsts/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 613, in _process_config_content
    _validate_payload_schema(content)
  File "/home/vsts/.azure/cliextensions/azure-cli-iot-ext/azext_iot/operations/hub.py", line 626, in _validate_payload_schema
    from jsonschema import validate
  File "/home/vsts/.azure/cliextensions/azure-cli-iot-ext/jsonschema/__init__.py", line 33, in <module>
    __version__ = get_distribution(__name__).version
  File "/opt/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 472, in get_distribution
    dist = get_provider(dist)
  File "/opt/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 344, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/opt/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/az/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jsonschema' distribution was not found and is required by the application

**Comment by blackchoey** [comment] 2019-09-29 09:04
This is caused by a bug in Azure IoT extension for Azure CLI: https://github.com/Azure/azure-iot-cli-extension/issues/95
Azure IoT extension for Azure CLI already fixed this error. You should no longer see this error.
I'm going to close this issue. Feel free to open new issues if you meet other problems when using Azure IoT Edge tasks.

**Closed by blackchoey** 2019-09-29 09:04 UTC
Labels: Area: Release
