### ISSUE TITLE
no matching key exchange method found.

### ISSUE THREAD

**Issue by zdavatz** [microsoft/azure-pipelines-tasks#10642] opened 2019-06-12 15:19 UTC
I am trying to copy my build Artifacts to my Linux Server using azure-piplines and this task:
```
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'pillbox'
    sourceFolder: '$(build.artifactstagingdirectory)'
    contents: 'AmiKoWindows/bin/Release/Amiko-Installer/Amiko-Installer.msi'
    targetFolder: '/home/ftp/Amiko_Desitin_Win7.msi'
```
The SSH Copy-Job always fails. My SSH log on the receiving end says:
```
Jun 12 16:02:15 [sshd] Unable to negotiate with 137.135.130.50 port 1984: no matching key exchange method found. Their offer: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1 [preauth]
```
I use `Ed25519` which is the most recommended public-key algorithm available [today](https://medium.com/risan/upgrade-your-ssh-key-to-ed25519-c6e8d60d3c54).

any thoughts on when Azure-Pipeline-Tasks may support that? The offered key exchange methods seem a bit outdated AFAICT.

You can find the build here: https://dev.azure.com/ywesee/AmiKo_Csharp/_build/results?buildId=33

This may be related: #8818, https://github.com/MicrosoftDocs/vsts-docs/issues/3169

**Comment by egor-bryzgalov** [comment] 2020-04-28 16:11
Closed because this issue was mentioned in #11443.

**Comment by zdavatz** [comment] 2020-04-28 17:28
Ok, but does it work now? It seems not!

**Comment by anatolybolshakov** [comment] 2020-04-28 18:24
@zdavatz Sorry for closing it, I reopened issue and marked as duplicate - you can follow the link below to be up to date with the progress regarding this issue

Duplicate of #11443

**Comment by zdavatz** [comment] 2020-04-29 08:06
Ok, thank you! Would be great, if this would work.

**Comment by olljanat** [comment] 2021-10-03 11:40
FYI. #12317 contained solution to this one but I closed it now as it didn't got reviewed on ~1,5 years someone else of those who need this can try to create alternative PR.

**Comment by zdavatz** [comment] 2021-10-04 07:22
Ok, thank you! I will try to test it.

**Comment by anatolybolshakov** [comment] 2022-05-18 13:15
Hi everyone! Current 'ssh2' version for CopyFilesOverSSHV0 task is [1.4.0](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/CopyFilesOverSSHV0/package.json#L20), which should resolve this issue - please let us know if you still see it.

**Comment by alexander-smolyakov** [comment] 2022-06-14 18:02
I'm closing this due to inactivity, feel free to request a reopening if you have further questions.

**Closed by alexander-smolyakov** 2022-06-14 18:02 UTC
Labels: enhancement, Area: ABTT, backlog, Task: CopyFilesOverSSH
