### ISSUE TITLE
Nuget Push to Github Packages fails with 401 Unauthorized

### ISSUE THREAD

**Issue by photomoose** [microsoft/azure-pipelines-tasks#14168] opened 2021-01-04 10:45 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: 
- NuGetCommandV2
- DotNetCoreCLIV2

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

When using a Nuget Service Connection, the Azure Pipeline tasks add the "--api-key" switch to the nuget command line, with a hardcoded value of "RequiredApiKey". In the past, this worked when pushing packages to GitHub Packages - however, it looks like a [recent change made in GitHub to support the ApiKey switch](https://github.blog/changelog/2020-10-29-nuget-supports-api-key-option/) causes these tasks to fail with a 401 Unauthorized error. 

### Task logs

```
/usr/bin/dotnet nuget push /home/vsts/work/1/a/packages/release/<package-name>.nupkg --source https://nuget.pkg.github.com/<owner> --api-key RequiredApiKey
Pushing <package-name>.nupkg to 'https://nuget.pkg.github.com/<owner>'...
  PUT https://nuget.pkg.github.com/<owner>/
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
  Unauthorized https://nuget.pkg.github.com/<owner>/ 810ms
error: Response status code does not indicate success: 401 (Unauthorized).
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by damccorm** [comment] 2021-01-05 16:30
Closing as dupe of #14169 - looks like the issue got created twice

**Closed by damccorm** 2021-01-05 16:30 UTC
Labels: bug, route
