### ISSUE TITLE
Azure MySQL Deployment Task wrongly sets the path to the script

### ISSUE THREAD

**Issue by AsierVillanueva** [microsoft/azure-pipelines-tasks#14371] opened 2021-02-10 08:48 UTC
*Type*: Bug

**Enter Task Name**: Azure Database for MySQL deployment (AzureMysqlDeploymentV1)

## Environment
- Server - Azure Pipelines
Account Name: DesarrollosEdatalia
Team Project Name: Fábrica Edatalia
Release: Deploy PSC (Release-99)

- Agent - Hosted  
    
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az354-502'
Current agent version: '2.181.1'
Operating System: Microsoft Windows Server 2016

## Issue Description

The task returns error: ERROR at line 1: Unknown command '\a'.

The command isn't well format: 
[command]C:\mysql-5.7.21-winx64\bin\mysql.exe -hxxxxx.mysql.database.azure.com -uxxxxx@xxxxx -p*** -Dxxxxxxx.xxxxxxxdev **-e "source** D:\a\r1\a\_PSC Web Build\MigrationsScripts\script.sql;"

In previous versions the command was:

[command]C:\mysql-5.7.21-winx64\bin\mysql.exe -hxxxxxx.mysql.database.azure.com -uxxxxx@xxxxx -p*** -Dxxxxxxx.xxxxxxxdev "**-e source** D:\a\r1\a\_PSC Web Build\MigrationsScripts\script.sql"

### Task logs

2021-02-10T08:16:34.2302536Z ##[section]Starting: Execute Azure MySQL : SqlTaskFile
2021-02-10T08:16:34.2446172Z ==============================================================================
2021-02-10T08:16:34.2447167Z Task         : Azure Database for MySQL deployment
2021-02-10T08:16:34.2447565Z Description  : Run your scripts and make changes to your Azure Database for MySQL
2021-02-10T08:16:34.2447884Z Version      : 1.182.1
2021-02-10T08:16:34.2448148Z Author       : Microsoft Corporation
2021-02-10T08:16:34.2448536Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-mysql-deployment
2021-02-10T08:16:34.2448942Z ==============================================================================
2021-02-10T08:16:35.1530144Z [command]C:\mysql-5.7.21-winx64\bin\mysql.exe -hxxxxxx.mysql.database.azure.com -uxxxxxx@xxxxxx -p***
2021-02-10T08:16:35.6517575Z mysql: [Warning] Using a password on the command line interface can be insecure.
2021-02-10T08:16:35.6737923Z [command]C:\mysql-5.7.21-winx64\bin\mysql.exe -hxxxxxx.mysql.database.azure.com -uxxxxxxx@xxxxxx -p*** "-eCREATE DATABASE IF NOT EXISTS `xxxxxx.xxxxxxxdev` ;"
2021-02-10T08:16:35.6924073Z mysql: [Warning] Using a password on the command line interface can be insecure.
2021-02-10T08:16:35.9833656Z [command]C:\mysql-5.7.21-winx64\bin\mysql.exe -hxxxxxx.mysql.database.azure.com -uxxxxxx@xxxxxx -p*** -Dxxxxxx.xxxxxxxdev -e "source D:\a\r1\a\_PSC Web Build\MigrationsScripts\script.sql;"
2021-02-10T08:16:35.9983488Z mysql: [Warning] Using a password on the command line interface can be insecure.
2021-02-10T08:16:36.0886157Z ERROR at line 1: Unknown command '\a'.
2021-02-10T08:16:36.0970190Z ##[error]Error: The process 'C:\mysql-5.7.21-winx64\bin\mysql.exe' failed with exit code 1
2021-02-10T08:16:36.1020707Z ##[section]Finishing: Execute Azure MySQL : SqlTaskFile

**Comment by 20shivangi** [comment] 2021-02-10 09:59
This issue is a duplicate of issue : https://github.com/microsoft/azure-pipelines-tasks/issues/14352 so marking this as closed
We have fixed this with PR : https://github.com/microsoft/azure-pipelines-tasks/pull/14367

Please wait for the deployment to reach your account. Thank you for your patience :)

**Closed by 20shivangi** 2021-02-10 09:59 UTC
Labels: Area: Release, Task: MysqlDeployment, bug, environment:bug

**Comment by AsierVillanueva** [comment] 2021-02-15 10:47
@20shivangi 
How long can it take?
We have the release pipelines crashing since last Wednesday and the task still not updated. We can't deploy any new feature since then.

**Comment by 20shivangi** [comment] 2021-02-15 15:14
@AsierVillanueva The deployment usually takes 3-4 weeks to roll out.

**Comment by AsierVillanueva** [comment] 2021-02-15 23:22
3-4 weeks with the releases stopped ¿really?

**Comment by 20shivangi** [comment] 2021-02-16 10:50
Please wait at least till this week. Deployment might reach your account by this week
