### ISSUE TITLE
AzurePowerShellV4 PowerShell Core (pwsh) task fails if agent running from directory with special characters

### ISSUE THREAD

**Issue by HQJaTu** [microsoft/azure-pipelines-tasks#12093] opened 2020-01-08 07:51 UTC
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzurePowerShellV4

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzurePowerShellV4

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Microsoft Windows 10.0.17763, v2.160.1

## Issue Description

When running Deployment Agent from subdirectory containing a space, all PowerShell Core (pwsh) tasks fail with following error:
`The term '-partial-path-here-' is not recognized as the name of a cmdlet, function, script file, or operable program.`

### Task logs

```
2020T3Z ========================== Starting Command Output ===========================
2020T6Z ##[debug]Entering Invoke-VstsTool.
2020T2Z ##[debug] FileName: 'C:\Program Files\PowerShell\6\pwsh.exe'
2020T8Z ##[debug] Arguments: '-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\Users\d-agent\Deployment agent\_work\_temp\ad6ae3b4-8e7e-421a-b6eb-7826df1a948a.ps1'"'
2020T4Z ##[debug] WorkingDirectory: 'C:\Users\d-agent\Deployment agent\_work\r1\a'
2020T4Z ##[command]"C:\Program Files\PowerShell\6\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\Users\d-agent\Deployment agent\_work\_temp\ad6ae3b4-8e7e-421a-b6eb-7826df1a948a.ps1'"
2020T6Z ##[debug]STDERR: . : The term 'C:\Users\d-agent\Deployment' is not recognized as the name of a cmdlet, function, script file, or operable program.
2020T6Z ##[debug]STDERR: Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2020T6Z ##[debug]STDERR: At C:\Users\d-agent\Deployment agent\_work\_temp\ad6ae3b4-8e7e-421a-b6eb-7826df1a948a.ps1:3 char:3
2020T9Z ##[debug]STDERR: + . C:\Users\d-agent\Deployment agent\_work\_tasks\AzurePowerShell_72a1931b ...
2020T7Z ##[debug]STDERR: +   ~~~~~~~~~~~~~~~~~~~~~~~
2020T0Z ##[debug]STDERR: + CategoryInfo          : ObjectNotFound: (C:\Users\d-agent\Deployment:String) [], ParentContainsErrorRecordException
2020T7Z ##[debug]STDERR: + FullyQualifiedErrorId : CommandNotFoundException
2020T2Z ##[debug]STDERR:  
2020T8Z ##[debug]Exit code: 1
2020T1Z ##[debug]Leaving Invoke-VstsTool.
```

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

## Source of the problem
In `azure-pipelines-task-lib\powershell\VstsTaskSdk\ToolFunctions.ps1`, function `Invoke-Tool` the call is made as:
```
Invoke-Expression "& '$FileName' --% $Arguments"
```
All my attempts to replicate the problem on an interactive session failed. Since the same code works with PowerShell 5.1, there must be a failure to escape characters which is specific to pwsh.

### Potential problem
https://devblogs.microsoft.com/powershell/invoke-expression-considered-harmful/
Using `Invoke-Expression` is not the best approach. I would consider something in this fashion instead:
```
$Cmd = {
	$escapeparser = '--%'
    & $FileName $escapeparser $Arguments
}
Invoke-Command -NoNewScope -ScriptBlock $Cmd
```
That should be more robust approach for special characters.

**Comment by 20shivangi** [comment] 2020-01-13 09:00
@HQJaTu 
Have you tried to run the AzurePowerShellV5 task ? Is it failing in this also?

**Comment by HQJaTu** [comment] 2020-01-13 09:18
I have not tested V5. Is it available in cloud yet? The source code is in git-repo, but how can one use it from Azure DevOps?

**Comment by 20shivangi** [comment] 2020-01-21 07:20
Please refer to this screenshot, it shows where we can change the major version of task in Azure Devops pipeline.
![azurepowershell](https://user-images.githubusercontent.com/45754171/72783507-9d274900-3c4c-11ea-951e-47659fda18eb.png)

**Comment by 20shivangi** [comment] 2020-01-23 05:25
@HQJaTu Have you tried AzurePowerShellV5 using above sreenshot ?

**Comment by HQJaTu** [comment] 2020-01-23 07:48
Sorry, I haven't.
I was building a Deployment Agent at the time, but now I have it working and moved on to other things.

**Comment by 20shivangi** [comment] 2020-01-23 08:11
Let me know if the issue is same in AzurePowerShellV5

**Comment by 20shivangi** [comment] 2020-01-27 04:51
@HQJaTu Have you tried in  AzurePowerShellV5 ?

**Comment by HQJaTu** [comment] 2020-01-27 13:22
No I haven't and I'm not likely to.

At the time of reporting the problem, I was working with Deployment Agent. Now I have it working and moved on to other tasks. Unfortunately, I do not have possibility of testing and tinkering with my pipeline at this point.

**Comment by 20shivangi** [comment] 2020-01-28 05:50
I am closing this issue. If you face any issue, please feel free to reopen it.

**Closed by 20shivangi** 2020-01-28 05:50 UTC
Labels: Area: Release, bug
