### ISSUE TITLE
ShellScriptV2 cwd not working

### ISSUE THREAD

**Issue by weidongxu-microsoft** [microsoft/azure-pipelines-tasks#11271] opened 2019-09-04 02:58 UTC
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ShellScriptV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
https://dev.azure.com/azure-sdk/public/_build/results?buildId=101715&view=results
https://github.com/Azure/azure-sdk-for-java/blob/repo_restructure/eng/pipelines/mgmt.yml

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]
```
      - task: ShellScript@2
        displayName: 'call mvn for each mgmt sdk individually'
        inputs:
          scriptPath: "$(System.DefaultWorkingDirectory)/eng/pipelines/scripts/mgmt_sdk_compiler.sh"
          cwd: "$(System.DefaultWorkingDirectory)"
          failOnStandardError: true
          args: "$(JavaVersion) $(MavenGoals)"
```

From sh output:
```
#### CWD : 
/home/vsts/work/1/s/eng/pipelines/scripts
```

Still in sub directory instead of project root.

Compare
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ShellScriptV2/shellscript.ts
and
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/BashV3/bash.ts

It seems `cwd` not set into `bash.exec` option in shellscript.ts.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by damccorm** [comment] 2019-11-20 18:58
I got a repro of this and it looks like its working correctly. Output - https://dev.azure.com/damccorm-repros/shellscriptCwd/_build/results?buildId=242&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=dd349f25-7095-58cb-1ea1-12e8abf37d4a

My yml file - https://dev.azure.com/damccorm-repros/_git/shellscriptCwd?path=%2Fazure-pipelines.yml&version=GBmaster

This doesn't look like a bug to me

**Comment by weidongxu-microsoft** [comment] 2019-11-21 01:53
@damccorm 
Thanks for the investigation.

Our current CI yaml https://github.com/Azure/azure-sdk-for-java/blob/master/eng/pipelines/mgmt.yml
Script that yaml calls https://github.com/Azure/azure-sdk-for-java/blob/master/eng/pipelines/scripts/mgmt_sdk_compiler.sh
Output of CI https://dev.azure.com/azure-sdk/public/_build/results?buildId=192579&view=logs&jobId=572c5e49-83d5-5271-390a-e6dc77f89c6b&j=572c5e49-83d5-5271-390a-e6dc77f89c6b&t=ce15895e-78ad-5525-f978-6dca7b73c3f9
```
#### CWD : 
/home/vsts/work/1/s/eng/pipelines/scripts
```

I've got a tool project setup, what I found is that it is good to get the a specific folder under project root, but fails to get just at project root.
https://dev.azure.com/weidxu/_git/testCwd?path=%2Fazure-pipelines.yml&version=GBmaster

`cwd: "$(System.DefaultWorkingDirectory)"`

**Comment by damccorm** [comment] 2019-11-21 03:28
Huh, interesting. Could you try a run with system diagnostics enabled?

**Comment by weidongxu-microsoft** [comment] 2019-11-21 03:33
Run with system diagnostics enabled
https://dev.azure.com/weidxu/testCwd/_build/results?buildId=14&view=logs&j=572c5e49-83d5-5271-390a-e6dc77f89c6b&t=ce15895e-78ad-5525-f978-6dca7b73c3f9

**Comment by damccorm** [comment] 2020-01-27 21:13
So this is a little bit of an odd case. The key here is that it only fails when cwd is set equal to the repo root.

Basically when we pass in file paths to tasks, we default to the system.working directory. There's a number of reasons for this, but the simplest is that we need a reasonable default for our visual designer, and that's what it ended up being. That behavior, right or wrong, is very unlikely to change.

Because of that, when we read `cwd` and it equals the repo root, **we treat it like it wasn't passed in at all**.

This actually would normally be fine - the `cwd` is the repo root by default for tasks (another reason filepaths are empty by default - it implicitly means root).

Unfortunately, we have another thing interfering here: when no `cwd` arg is passed in, we automatically use the path of the script as the cwd. Because of this issue, and the inability to change most of this for back compat reasons, we introduced a variable [disableAutoCwd](https://github.com/microsoft/azure-pipelines-tasks/blob/bc4c91cb2c3ec22911c499d6036c74e4ee741b5d/Tasks/ShellScriptV2/task.json#L52) for exactly cases like this. So, you should be able to get the behavior you want by adding `disableAutoCwd: true` to your definition. I'd actually leave `cwd: "$(System.DefaultWorkingDirectory)"` simply for robustness/clarity, but you could probably get rid of that as well.

**Comment by damccorm** [comment] 2020-01-31 15:16
Closing since this is actually working as designed (even if it is an odd case)

**Closed by damccorm** 2020-01-31 15:16 UTC
Labels: Area: Core, bug
