### ISSUE TITLE
DeleteFiles fails to delete a long pathname during Build Deletion

### ISSUE THREAD

**Issue by japj** [microsoft/azure-pipelines-tasks#14459] opened 2021-02-24 13:58 UTC
**Question, Bug, or Feature?**  
*Type*:  Bug

**Enter Task Name**: DeleteFiles

## Environment
- AzureDevOps Server Dev18.M170.6
- Private Agent:
  - Window Server 2016
  - Agent 2.175.2
  - DeleteFiles 1.166.2
    
## Issue Description

The Artifacts of a Build were not correctly deleted by DeleteFiles.
It seems there is a file that was published to a fileshare that has total unc path length of 263 characters and this specific file is not removed at all when the build is deleted (all other artifact content has been correctly removed)
The agent worker log shows that the 'Delete files from <fileshare location>' step has Failed, but there is no other information.

### Task logs

Unfortunately, we have no control on enabling the diagnostic logging on the Artifact Deletion Job (it is fully generated by the AzureDevOps Server).

**Comment by japj** [comment] 2021-02-25 08:00
it seems tl.rmRF (https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DeleteFilesV1/deletefiles.ts#L101) is from the https://github.com/microsoft/azure-pipelines-task-lib

rmRF seems to use `rd /s /q` on the windows platform (https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/task.ts#L1171)

When I manually (on the buildserver) run the `rd /s /q` on the problematic UNC path get "The path xxxxx is too long"

**Comment by DaniilShmelev** [comment] 2021-03-12 07:03
Hi @japj! I'll take a look at this issue.

**Comment by vladislav-ryzhov** [comment] 2021-03-16 08:29
Hi @japj!

The 260 character limit on a path is a core Windows system issue.
You can do 1 of 2 things:

1. Change the name of the files/folders that is too long for the path.
2. If you use self-hosted agent, you can enable long paths. You can find instructions here https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

**Comment by vladislav-ryzhov** [comment] 2021-03-16 08:32
@japj Let me close this one since this is external issue. Please feel free to ask any further questions.

**Comment by japj** [comment] 2021-04-08 15:05
@vladislav-ryzhov the server already has long path support enabled (and is able to publish long paths without issues).
The removing of files (through azure-pipelines-task-lib) seems to have an issue as mentioned earlier

**Comment by vladislav-ryzhov** [comment] 2021-04-13 13:39
Hi @japj
We have reproduced this issue and it looks like an external issue. The DeleteFiles task works as expected on all images. It doesn't work in Windows server 2016, but this is due to image or environment errors.
Alternatively, you can try to delete this file using the PowerShell "Remove-item" cmdlet. After our investigation, it deletes files with a pathname longer than 260 characters.
Please ping me if you have any further questions.

**Closed by vladislav-ryzhov** 2021-04-13 13:39 UTC
Labels: Area: ABTT, Area: Core, Task: DeleteFiles, question

**Comment by japj** [comment] 2021-04-14 05:53
@vladislav-ryzhov thanks for clarifying that it doesn't work in Windows Server 2016.
I can reproduce and confirm that the underlying error with "rd" is indeed fixed on a Windows Server 2019 (Version 1809, Build 17763.1817) with LongPathsEnabled.

Related to your alternative solution, that is unfortunately not usable in this case since one of the core issues here is that the DeleteFiles task is part of the build retention cleanup job that is generated by the AzureDevOps Server itself, we have no control over this (and thus cannot replace it with an alternative).

However, I will try to see if we can use the `Build.Cleanup` capability (see also https://github.com/MicrosoftDocs/azure-devops-docs/issues/3685#issuecomment-575648590) to pin the cleanup jobs on a (new) Windows Server 2019 server. We are still using Windows Server 2016 on our build servers, but we are doing some preparation work for migrating our build servers to Windows Server 2019 later this year.
